// Course registry. Each course owns a key block (base) so progress never collides.
window.HALCYON_COURSES=[
  {id:"pmp",title:"PMP",full_title:"The Halcyon Launch",exam:"Project Management Professional (PMI)",story:"Sam Okafor gets drafted to rescue Halcyon AI's biggest customer launch with fourteen weeks left.",base:0,root:"",status:"live",
   taskDomain:{P:"People",R:"Process",B:"Business Environment"},refArt:{1:1,2:4,3:6,4:7,5:9,6:10},
   fullName:"Full Course",fullHours:"about 15 to 20 hours",mockTitle:"PMP practice exam",mockMinutes:240,mockBreaks:[60,120],
   mockBlurb:"Weighted like the July 2026 exam: People 33 percent, Process 41 percent, Business Environment 26 percent, with most questions agile or hybrid. All questions are single answer; the real exam also has multi-select, matching, and hotspot items.",
   mockShort:"180 questions in 240 minutes, weighted like the real exam."},
  {id:"cphims",title:"CPHIMS",scripts:["meta.js","full/ch01.js"],taskDomain:{E:"Environments",C:"Clinical Informatics",S:"Systems Management",L:"Leadership"},
   fullName:"Full Course",fullHours:"about 13 to 16 hours",mockTitle:"CPHIMS practice exam",mockMinutes:120,mockBreaks:[],
   mockBlurb:"Weighted like the HIMSS outline: Environments 25 percent, Clinical Informatics 20 percent, Systems Management 30 percent, Leadership 25 percent. Four options per question at recall, application, and analysis levels.",
   mockShort:"115 questions in 120 minutes, 100 of them scored, weighted like the real exam.",
   mentor:"Ochoa",lessonName:"Ochoa's Legal Pad",levels:true,options:4,
   flags:["solofix","skippedprivacy","blamedmarcus","dismissedwalt","allalerts","softroi","tookthetickets","nodrtest","skippedregression","sharedlogin"],
   speakers:["Maria","Ochoa","Kiran","Marcus","Aisha","Joan","Brett","Walt","Tasha","Glenn","Nate","Denise","Lucia","Sam","Ruth"],
   exam:"Certified Professional in Healthcare Information and Management Systems (HIMSS)",full_title:"One Chart",story:"Maria Santos inherits a legacy EHR at three Wyoming hospitals that loses vendor support in twenty months.",base:10000,root:"courses/cphims/",status:"live"},
  {id:"asep",title:"INCOSE ASEP",scripts:["meta.js","full/ch01.js"],taskDomain:{T:"Technical",M:"Technical management",A:"Agreement and organizational",O:"Agreement and organizational",X:"Cross-cutting"},
   fullName:"Full Course",fullHours:"about 12 to 15 hours",mockTitle:"ASEP practice exam",mockMinutes:120,mockBreaks:[],
   mockBlurb:"Built from the INCOSE Systems Engineering Handbook and the ISO/IEC/IEEE 15288 processes, heavy on each process's purpose, inputs, outputs, and how they connect. Single answer, four options. INCOSE doesn't publish a passing score, so aim high.",
   mockShort:"120 questions in 120 minutes, one minute per question like the real exam.",
   mentor:"Ruth",lessonName:"Ruth's Flight Notes",options:4,
   flags:["skippedconops","acceptedwesreqs","nointerfacecontrol","unweightedtrade","blamedsupplier","hidrisk","paddedmargin","cuttest","noconfigcapture","rushedtrr"],
   speakers:["Nadia","Ruth","Wes","Amara","Luis","Helen","Pavel","Jun","Tess","Sam","Frank"],
   exam:"Associate Systems Engineering Professional (INCOSE)",full_title:"Hearth",story:"Nadia Brooks, a test engineer in her first systems job, helps build a habitat module for a private space station and learns the crew needs more than the volume the contract promises.",base:20000,root:"courses/asep/",status:"live"},
  {id:"gh300",title:"GH-300",full_title:"The Copilot Rollout",exam:"GitHub Copilot (Microsoft)",story:"Priya Shah gets handed Halcyon's Copilot rollout and a skeptical team.",base:30000,root:"courses/gh300/",status:"live",scripts:["meta.js","full/ch01.js"],taskDomain:{F:"Copilot Features",R:"Responsible AI",S:"Privacy and Safeguards",P:"Prompt Engineering",D:"Data and Architecture",V:"Developer Productivity"},fullName:"Full Course",fullHours:"about 6 to 8 hours",mockTitle:"GH-300 practice exam",mockMinutes:100,mockBreaks:[],mockBlurb:"Weighted like the Microsoft Learn outline: Features 25 to 30 percent, Responsible AI 15 to 20 percent, and Privacy, Prompting, Data, and Productivity 10 to 15 percent each. The real exam may also include interactive items.",mockShort:"60 questions in 100 minutes, weighted like the real exam.",mentor:"Ruth",lessonName:"Ruth's Whiteboard",levels:true,options:4,scenes:11,flags:["personalseats","agentblur","blamedevin","noinstructions","filteroff","cliunsafe"],speakers:["Priya","Ruth","Sam","Elena","Lena","Theo","Ken","Nora","Devin","Tomasz","Renata"]},
  {id:"pilot",title:"Private Pilot",full_title:"Danny's Logbook",exam:"FAA Private Pilot Airplane knowledge test (PAR)",story:"Jordan Reyes inherits his late brother's share of a 1978 Cessna and one year to learn to fly it or sell it.",base:40000,root:"courses/pilot/",
   scripts:["meta.js","full/ch01.js"],taskDomain:{"I":"Preflight","II":"Preflight","III":"Airport and flight","IV":"Airport and flight","V":"Airport and flight","VII":"Airport and flight","VIII":"Airport and flight","XII":"Airport and flight","VI":"Navigation and emergencies","IX":"Navigation and emergencies","XI":"Navigation and emergencies"},
   fullName:"Full Course",fullHours:"about 12 to 15 hours",mockTitle:"Private pilot practice test",mockMinutes:120,mockBreaks:[],
   mockBlurb:"Weighted like the FAA PAR knowledge test: heavy on regulations, airspace, weather, performance, and systems, with at least 15 calculation questions. Three options per question, like the real test. 70 percent passes.",
   mockShort:"60 questions in 2 hours, three options each, 70 percent to pass.",
   mentor:"Abby",lessonName:"Abby's Ground School",levels:false,options:3,
   flags:["rushedpreflight","ignoredwind","noflightfollowing","skippedwb","forcedlanding","nopersonalmins","thinfuel","pushedweather"],
   speakers:["Jordan","Abby","Walt","Marisol","Lourdes","Claire","Ellie","Russ","Danny","Kendra"],
   status:"live"}
];
