(((window.HALCYON_DATA=window.HALCYON_DATA||{}).cphims=window.HALCYON_DATA.cphims||{}).full=window.HALCYON_DATA.cphims.full||[]).push({
  num: 1, part: `Part One: The Inheritance`, title: `The Corner Office`, weeks: `Month 1`,
  tasks: [`E1`,`E2`,`E3`,`E6`,`SA7`,`L1`,`L2`,`L12`],
  cast: [
    [`Dr. Walt Hagen`,`General surgeon at the Laramie hospital, 31 years in practice. Prints every note. Counts clicks out loud.`],
    [`Sam Okafor`,`Director of Delivery at Halcyon AI. Owns the phase two discharge instructions agents.`],
    [`Lucia Santos`,`Maria's daughter, 17. Applying to nursing school.`]
  ],
  opening: [
    `Maria Santos had been a vice president for forty minutes when the letter arrived.`,
    `The office was on the fourth floor of the Cascade Valley Health administration building in Fort Collins, and it had a window, which was new. For fourteen years her office had been an ICU nurses' station in Greeley with a coffee maker that leaked and a view of a hallway. Then three years as nurse informatics director, in a cubicle. Then eight months as the Cascade product owner on the Halcyon AI launch, which mostly meant a conference room at two in the morning. Now there was a window, a nameplate that still said the last person's name, and an inbox that already had two hundred and eleven messages in it.`,
    `Her new title was Vice President of Clinical Systems. It meant she owned the electronic health record, every clinical application that plugged into it, the interfaces that carried data between them, and the team of analysts who kept all of it running across eleven hospitals, forty clinics, and a home health agency. It meant she reported to Dr. Raymond Ochoa, the CIO, who had hired her by saying, <span class="said" data-who="Ochoa">"You're the only person in this building who has been woken up by every system we own. I'd like that to stop being an accident."</span>`,
    `The letter was a PDF attached to an email from a company most of Cascade had forgotten it paid.`,
    `<prop type="email" from="MedaLink Customer Success" to="Cascade Valley Health, IT leadership" time="Monday, 9:02 AM" subject="End of support notice">Dear valued partner,<br>MedaLink will end support for the MedaLink EHR platform twenty months from the date of this notice. After that date we will no longer provide updates, security patches, regulatory changes, or help desk services. We encourage you to begin planning your transition now.</prop>`,
    `Maria read it twice. Eight of Cascade's hospitals ran Corvane, the system-wide EHR. Three didn't. Cheyenne, Laramie, and Rawlins had come in through an old affiliation with their own system, MedaLink, and everyone had agreed for six years that someone would deal with that eventually. She looked at the nameplate with the wrong name on it. She was apparently someone.`,
    `Her phone buzzed. A text from Lucia, seventeen, who was supposed to be in AP Chemistry. <span class="said" data-who="Lucia">"how's the big office. do u have a plant yet"</span>`,
    `Maria typed back that she didn't have a plant. Then she forwarded the letter to Ochoa with one line: <span class="said" data-who="Maria">"I assume you've seen this."</span> He replied in under a minute. <span class="said" data-who="Ochoa">"I have. It's why you have that office. Breakfast tomorrow, 7:30, the diner. Bring a legal pad."</span>`
  ],
  lesson: {
    title: `Ochoa's Legal Pad: the map of the territory`,
    sections: [
      { h: `Know what kind of place you're standing in`,
        body: [`Ochoa ordered eggs, pushed the plate aside, and drew a box on her legal pad. <span class="said" data-who="Ochoa">"Before you fix anything, know what you own and who you serve."</span> Healthcare isn't one kind of organization. An acute care hospital treats patients who need a bed and round the clock nursing. A critical access hospital is a small rural hospital, usually 25 beds or fewer, with special federal payment rules that keep care close to home in places like Rawlins. An academic medical center adds teaching and research. Ambulatory care covers clinics, surgery centers, and urgent care, where patients go home the same day. Community health centers serve patients regardless of their ability to pay. Home health brings nurses and therapists to the patient's house. Long term care and rehab handle the weeks and months after a hospital stay.`,
          `Then there are the organizations that never touch a patient but shape everything. Payers, like commercial insurers, Medicare, and Medicaid, decide what gets paid and how claims must look. Regulators, like CMS and state health departments, set the rules. Accreditors, like The Joint Commission, survey hospitals against standards. Public health agencies collect reportable diseases and immunizations. Research and academic institutions run studies and train the next generation. Every one of them wants data from Maria's systems, in a different format, on a different schedule.`],
        terms: [[`Critical access hospital`,`A small rural hospital with special federal designation and payment rules, typically 25 inpatient beds or fewer.`],[`Ambulatory care`,`Outpatient care where the patient goes home the same day.`],[`Payer`,`An organization that pays for care, such as a commercial insurer, Medicare, or Medicaid.`]],
        exam: `HIMSS likes to describe an organization and ask what it is or what it needs. Match the services to the type: same day care is ambulatory, small rural inpatient care is often a critical access hospital, and an organization that pays claims is a payer.` },
      { h: `Nobody is an island`,
        body: [`Ochoa drew lines between the boxes. A patient in Rawlins sees a family doctor at a Cascade clinic, gets transferred to Cheyenne for surgery, goes home with a home health nurse, and has her claim paid by Medicaid. Every handoff is a place where information can get lost. Continuity of care is the idea that the next caregiver should know what the last one knew. A health information exchange, or HIE, moves clinical data between organizations that don't share a system, so the emergency department in Fort Collins can see the medication list from a clinic in Wyoming. Referrals, transfers, lab results, claims, and public health reports all travel across those lines.`,
          `<span class="said" data-who="Ochoa">"When you change a system,"</span> Ochoa said, <span class="said" data-who="Ochoa">"you change every line that touches it. People forget the lines."</span>`],
        terms: [[`Health information exchange (HIE)`,`An organization or network that moves clinical data securely between different providers and systems.`],[`Continuity of care`,`Making sure each caregiver has the information the previous caregiver had, across settings and organizations.`]],
        exam: `When a question asks who is affected by a system change, the best answer usually reaches beyond the walls: referring clinics, the HIE, payers, public health, and the receiving hospital in a transfer.` },
      { h: `Who does what`,
        body: [`The CIO owns the information technology strategy and budget for the organization and answers to the CEO and the board. The CMIO, a physician, bridges medicine and IT and leads clinical decision support and physician adoption. The CNIO does the same for nursing. The CISO owns information security: protecting systems and data from threats. The privacy officer owns how patient information is used and disclosed, and handles privacy complaints and breach assessments. A VP of clinical systems, like Maria, owns the clinical applications and the team that builds and supports them. Clinical analysts translate workflow into system build. Data stewards define and protect the quality of specific data. Superusers are front line staff trained to help their peers.`,
          `The lines matter. A clinical content decision, like what an order set should contain, belongs to clinicians through governance, usually a clinical informatics council. IT builds it. Security decisions belong to the CISO. Privacy questions go to the privacy officer. <span class="said" data-who="Ochoa">"Your job,"</span> Ochoa said, <span class="said" data-who="Ochoa">"isn't to make every decision. It's to make sure the right person makes it, on time, and writes it down."</span>`],
        terms: [[`CMIO`,`Chief Medical Information Officer. A physician leader who connects clinical practice and information systems.`],[`CNIO`,`Chief Nursing Information Officer. The nursing counterpart to the CMIO.`],[`Superuser`,`A front line staff member with extra training who supports peers during and after go-live.`]],
        exam: `Expect "who should" questions. Clinical content goes to clinicians and governance, security to the CISO, privacy to the privacy officer, overall IT strategy to the CIO.` },
      { h: `What you actually own`,
        body: [`Healthcare applications fall into families. Clinical systems support care: the EHR, computerized provider order entry (CPOE), the electronic medication administration record (eMAR), bar code medication administration (BCMA), the laboratory information system, pharmacy, and imaging through PACS. Administrative systems run the operation: registration and ADT (admit, discharge, transfer), scheduling, and supply chain. Financial systems handle the revenue cycle: charge capture, coding, billing, and claims. Consumer systems face the patient: the portal, telehealth, and remote monitoring. Business intelligence pulls data from all of them into a warehouse for reports, dashboards, and analytics.`,
          `MedaLink wasn't one system. In those three hospitals it was the clinical record, the registration system, part of the billing, and the feed to the HIE. Retiring it would touch every family on the list.`],
        terms: [[`CPOE`,`Computerized provider order entry. Clinicians enter orders electronically instead of on paper.`],[`ADT`,`Admit, discharge, transfer. The registration events that tell every other system where a patient is.`],[`PACS`,`Picture archiving and communication system, which stores and displays medical images.`]],
        exam: `Know which family an application belongs to. Billing and claims are financial, registration and scheduling are administrative, the portal is consumer, and the data warehouse is business intelligence.` },
      { h: `Strategy comes first`,
        body: [`Ochoa turned the pad over. <span class="said" data-who="Ochoa">"The board doesn't fund projects. It funds strategy."</span> Strategic planning starts with the organization's mission, vision, and goals, then looks at the environment with tools like a SWOT analysis, then sets priorities. The IT strategic plan should trace back to the organization's plan, goal by goal. A project that can't show which goal it serves will lose every budget fight, no matter how urgent it feels to IT. Culture matters as much as the plan: the values, habits, and history of the people who'll live with the change. Three Wyoming hospitals that joined through an affiliation have their own culture, and they'll judge Maria by whether she learns it before she changes it.`],
        terms: [[`Strategic alignment`,`Showing how an IT initiative supports the organization's strategic goals.`],[`SWOT`,`Strengths, weaknesses, opportunities, threats. A structured look at the internal and external environment.`]],
        exam: `When a question asks how to justify or prioritize an IT initiative, look for the answer that ties it to organizational goals. "Because the technology is better" or "because the vendor said so" is rarely the best answer.` }
    ],
    video: [`dK4EV9wJPm0`,`Anatomy of Healthcare | The U.S. Healthcare System Explained`,`Med School Insiders`,`10:26`]
  },
  scenes: [
    { id:`f1s1`, domain:`Environments`, task:`E3`, title:`Whose call is it`,
      text:(s,all,G)=>[`By ten o'clock Kiran Bhatt was at her door with a laptop and the look of a man who had been waiting for someone with authority. Kiran was the senior EHR analyst, a former pharmacy tech who built order sets the way some people build ship models.`,`<span class="said" data-who="Kiran">"Quick one. The Greeley hospitalists want the heparin order set changed. New starting dose, a different lab check. It's maybe two hours of build. You were a nurse, you know heparin. Can you just approve it so I can move it to production this week?"</span>`,`She did know heparin. She had given it a thousand times. What does Maria do?`],
      opts:[
        {t:`Approve it now, since it's small, she knows the drug, and Kiran is waiting on it.`, s:0, d:{trust:2,conf:-3,health:-4},
          after:`Kiran builds it by Thursday. On Monday a pharmacist at Cheyenne calls, upset: nobody told pharmacy the dosing changed, and their protocol still says the old dose. Two different heparin answers are now live in the same health system.`,
          why:`You were a nurse. You aren't the clinical informatics council. Order set content is a clinical decision, and it belongs to the clinicians who own it through governance. Your team builds what they approve. Skip that and you get two versions of the truth.`},
        {t:`Send it to Aisha's informatics council and build only what it approves.`, s:3, best:true, d:{trust:1,conf:4,health:4},
          after:`Kiran sighs, but he files it. The council takes it up the next Wednesday. Pharmacy is at the table, catches the protocol mismatch, and the order set and the protocol change together. Aisha sends Maria a one line note: <span class="said" data-who="Aisha">"Thank you for not going around us."</span>`,
          why:`Clinical content belongs to clinicians, decided through governance. IT is the builder, not the owner. Routing it correctly is slower by a week and saves you from a patient safety problem. That's the trade every time.`},
        {t:`Tell Kiran to ask the Greeley hospitalists for written approval, then build it.`, s:1, d:{trust:2,conf:1,health:0},
          after:`The hospitalists sign off in an email. It's better than nothing. But Cheyenne and Fort Collins use the same order set, and nobody asked them.`,
          why:`Getting clinician sign off is the right instinct. One group of physicians can't approve a system-wide order set for everyone, though. That's why the council exists.`},
        {t:`Ask Corvane's support line whether the change is safe, and follow what they say.`, s:0, d:{trust:-1,conf:-2,health:-2},
          after:`The vendor's answer, three days later, is polite and useless: the system can be configured either way, and clinical content is the customer's decision.`,
          why:`The vendor builds the tool. Your clinicians decide what goes in it. Asking a vendor to make a clinical call is asking the wrong person.`}
      ]},
    { id:`f1s2`, domain:`Environments`, task:`E6`, title:`What MedaLink actually is`,
      text:(s,all,G)=>[`Monday afternoon Maria opened a blank document and typed "MedaLink replacement." Then she stopped. She realized she didn't know exactly what MedaLink did.`,`She knew the nurses charted in it. She knew the doctors hated it. Beyond that, the three Wyoming hospitals were a gray box on every diagram she'd ever seen.`],
      opts:[
        {t:`Build an inventory of every function MedaLink does, who owns it, and its feeds.`, s:3, best:true, d:{trust:2,conf:3,health:5},
          after:`It takes two weeks and a lot of phone calls. MedaLink turns out to be the clinical record, the registration and ADT system, part of the billing, the feed to the HIE, and the source for two state reports. Nobody had the whole list. Now Maria does.`,
          why:`You can't replace what you can't describe. Inventory before you plan: every application, the family it belongs to, who owns it, and what it connects to. The gray box always has more in it than people think.`},
        {t:`Treat it as an EHR swap and assume Corvane covers everything MedaLink did.`, s:0, d:{trust:0,conf:-2,health:-6},
          after:`The plan looks simple for about a month. Then someone from revenue cycle asks who's going to handle the Wyoming claims.`,
          why:`An EHR in a small hospital is often the registration system, the billing system, and the reporting engine too. Assume it's one thing and you'll find the rest at go-live.`},
        {t:`Ask MedaLink for a full list of the modules Cascade licenses and plan from that.`, s:1, d:{trust:0,conf:1,health:1},
          after:`The vendor sends a contract schedule with eleven module names on it. It tells her what Cascade pays for. It doesn't tell her what the hospitals actually use, or what's been bolted on locally.`,
          why:`The license list is a good input. It isn't an inventory. What matters is what's actually in use, who depends on it, and what it feeds.`},
        {t:`Get a replacement RFP out this month, since twenty months will go by fast.`, s:0, d:{trust:-1,conf:0,health:-3},
          after:`Ochoa reads the draft and hands it back. <span class="said" data-who="Ochoa">"Replacing it with what? You haven't told me what it does."</span>`,
          why:`Urgency is real, but buying before you understand the need is how organizations end up with expensive tools that don't fit. Assessment first, then requirements, then selection.`}
      ]},
    { id:`f1s3`, domain:`Environments`, task:`E1`, title:`Three hospitals, one plan`,
      text:(s,all,G)=>[`Maria's first draft of a timeline treated Cheyenne, Laramie, and Rawlins as one unit. Same training plan, same staffing model, same go-live weekend.`,`Kiran read it and frowned. <span class="said" data-who="Kiran">"Rawlins has twenty-two beds. It's a critical access hospital. They have swing beds and an ER with one doc at night. Cheyenne is a regional referral center. I don't think they're the same project."</span>`],
      opts:[
        {t:`Keep the single plan for simplicity, and adjust at Rawlins if problems show up.`, s:0, d:{trust:-2,conf:-1,health:-4},
          after:`Kiran stops raising it. Two months later the Rawlins CNO asks how she's supposed to send eight nurses to a three day class when she has nine on the schedule.`,
          why:`One size fits nobody. A small rural hospital has different staffing, different services, and different rules than a referral center. Plan for what each one actually is.`},
        {t:`Ask Kiran to rework it so each hospital gets its own training and staffing plan.`, s:1, d:{trust:3,conf:0,health:2},
          after:`Kiran builds three versions. They're better, but they're his guess at what each hospital needs. Nobody from Wyoming has seen them yet.`,
          why:`Tailoring is right. Doing it from Fort Collins without the people who run those hospitals is still guessing.`},
        {t:`Profile each hospital with its own leaders, then tailor the plan to each one.`, s:3, best:true, d:{trust:4,conf:3,health:4},
          after:`Maria spends an hour on the phone with each CNO. Rawlins needs training in four hour blocks over two weeks. Laramie has a surgical service that Cheyenne doesn't. Cheyenne takes transfers from both. The plan gets longer and a lot more real.`,
          why:`Know the type of organization before you plan for it. A critical access hospital and a referral center serve different patients with different resources. Tailor with their leaders, not around them.`},
        {t:`Do Cheyenne first as the pilot, then copy whatever worked at the smaller two.`, s:0, d:{trust:0,conf:1,health:-3},
          after:`It sounds disciplined. But what works in a referral center with a full IT staff doesn't copy to a twenty-two bed hospital with one IT tech who also fixes the printers.`,
          why:`Piloting is a good idea. Copying a large hospital's playbook onto a critical access hospital ignores the very differences that make it hard.`}
      ]},
    { id:`f1s4`, domain:`Environments`, task:`E2`, title:`Who else is on the line`,
      text:(s,all,G)=>[`Ochoa wanted a stakeholder list for One Chart by Friday. That was what he'd started calling it, One Chart, as if naming it made it real.`,`Maria's first pass had the three hospitals on it: their executives, nurses, physicians, and department heads. Forty names. It looked thorough.`],
      opts:[
        {t:`Send it. The people inside the three hospitals are the ones who'll feel the change.`, s:0, d:{trust:0,conf:-3,health:-3},
          after:`Ochoa reads it in the elevator. <span class="said" data-who="Ochoa">"Where's the HIE? Where's Medicaid? Where's the Cheyenne transfer center?"</span> She doesn't have an answer.`,
          why:`The people inside are the obvious stakeholders. The ones outside are the ones who break at go-live: the exchange, the payers, the clinics that refer in, the hospitals that take transfers out.`},
        {t:`Add the vendors, Corvane and MedaLink, since they'll do most of the technical work.`, s:1, d:{trust:0,conf:1,health:1},
          after:`The vendors go on the list. It's a real gap closed. The HIE, the payers, and public health are still missing.`,
          why:`Vendors belong on the list. They're only one of the outside connections, though. Follow the data and the patients out the door.`},
        {t:`Map everyone the data touches: clinics, the HIE, payers, labs, and public health.`, s:3, best:true, d:{trust:2,conf:5,health:4},
          after:`The list grows to ninety names and fourteen outside organizations. Maria draws the lines on a whiteboard. Every line is a feed or a handoff that One Chart will have to keep working. Ochoa takes a picture of it with his phone.`,
          why:`Interrelationships are the whole point. A system change at three hospitals ripples into referring clinics, home health, the HIE, payers, reference labs, and public health reporting. Map the lines before you cut any of them.`},
        {t:`Ask each hospital CEO to name the stakeholders that matter for their site.`, s:0, d:{trust:2,conf:0,health:-2},
          after:`Each CEO sends back a list of their own department heads. Nobody names anything outside their hospital, because nobody looks there.`,
          why:`Local leaders know their own building. They're not the right source for the outside connections, and you can't delegate the whole map away.`}
      ]},
    { id:`f1s5`, domain:`Systems Management`, task:`SA7`, title:`Why we're doing this`,
      text:(s,all,G)=>[`Tuesday, 7:30 AM, the first official one-on-one. Ochoa read her one page status and set it down.`,`<span class="said" data-who="Ochoa">"Your page says we're replacing MedaLink because the vendor is ending support. That's true. It's also the weakest reason you could give the board. They'll ask why we don't just pay somebody to keep it limping along."</span>`],
      opts:[
        {t:`Add a second reason to the page: Corvane is simply a much better product than MedaLink.`, s:0, d:{trust:0,conf:-3,health:0},
          after:`Ochoa almost smiles. <span class="said" data-who="Ochoa">"The board doesn't buy products. Try again."</span>`,
          why:`"The new system is better" is a technology argument. Boards fund outcomes that serve their goals. Lead with the goals.`},
        {t:`Tie One Chart to the system's strategic goals: one record, safety, rural access, and cost.`, s:3, best:true, d:{trust:1,conf:6,health:2},
          after:`She pulls up Cascade's strategic plan. Goal one is a single patient record across the system. Goal two is safer transitions of care. Goal four is sustaining rural access in Wyoming. She rewrites the page so One Chart serves three of the five goals by name. Ochoa reads it twice and says, <span class="said" data-who="Ochoa">"That one I can take upstairs."</span>`,
          why:`Strategic alignment means showing which organizational goals the initiative serves. End of support is the trigger. The goals are the reason. Lead with the reason.`},
        {t:`Emphasize the risk: unsupported software means no security patches after twenty months.`, s:1, d:{trust:0,conf:3,health:1},
          after:`It lands better. Security risk gets attention. Then Ochoa asks what it does for patients, and the page doesn't say.`,
          why:`Risk is a real argument and belongs in the case. On its own it invites the cheapest fix. Tie it to the goals and the risk becomes part of a bigger story.`},
        {t:`Ask Ochoa which reasons the board cares about and write those up for him.`, s:0, d:{trust:0,conf:-2,health:0},
          after:`<span class="said" data-who="Ochoa">"I'm asking you,"</span> he says. <span class="said" data-who="Ochoa">"You'll be the one in front of them in six months."</span>`,
          why:`The strategic plan is a public document inside the organization. Read it. Bringing your boss a question he expects you to answer costs you the room.`}
      ]},
    { id:`f1s6`, domain:`Leadership`, task:`L2`, title:`The stepchildren`,
      text:(s,all,G)=>[`Kiran forwarded her a message from a Laramie nurse who'd seen the news on the intranet. He'd added only: <span class="said" data-who="Kiran">"FYI. This is the general mood."</span>`,`<prop type="chat" from="Laramie nurse, unit chat" time="2:14 PM">so Fort Collins is coming to take MedaLink away. we built half of it. nobody asked us last time either</prop>`,`The three Wyoming hospitals had joined Cascade six years ago. Most of what they knew about Fort Collins came from memos.`],
      opts:[
        {t:`Post a reassuring message on the intranet explaining the benefits of Corvane.`, s:0, d:{trust:-3,conf:0,health:-1},
          after:`The post gets eleven views and one reply: <span class="said" data-who="woman">"cool, another memo."</span>`,
          why:`A memo answering a complaint about memos proves the complaint. When the issue is trust and culture, the channel is people, not the intranet.`},
        {t:`Ask the three CNOs to calm their staff down while she finishes the plan.`, s:1, d:{trust:-1,conf:1,health:0},
          after:`The CNOs agree, a little coolly. They've been asked to carry Fort Collins' message before.`,
          why:`Local leaders matter, and you'll need them. Handing them your message to deliver, before you've listened, repeats the pattern the nurse described.`},
        {t:`Go to Wyoming in person, round on the units, and ask what they built.`, s:3, best:true, d:{trust:7,conf:1,health:2},
          after:`She drives up Wednesday and spends two days on the floors in scrubs and a badge. A Laramie charge nurse shows her a MedaLink shortcut the staff built for transfer checklists. It's good. Maria writes it down and says so. By Thursday the unit chat has a new message: <span class="said" data-who="woman">"the new VP was a nurse. she actually charted with us."</span>`,
          why:`Learn the organization's culture before you change it. These hospitals have their own history and their own values. Showing up, listening, and naming what they did well buys you the trust you'll spend for the next eighteen months.`},
        {t:`Let it pass. People always grumble before a change and settle down later.`, s:0, d:{trust:-4,conf:0,health:-1},
          after:`They don't settle down. The grumbling hardens into a story: Fort Collins does things to Wyoming. Every decision for the next year gets read through it.`,
          why:`Grumbling is data about culture. Ignoring it lets the worst version of the story win before you've said a word.`}
      ]},
    { id:`f1s7`, domain:`Leadership`, task:`L12`, title:`The first all-hands`,
      text:(s,all,G)=>[`Ochoa scheduled a virtual all-hands for the clinical systems team and the three Wyoming hospitals for the following Monday. Three hundred people, thirty minutes. <span class="said" data-who="Ochoa">"It's your meeting,"</span> he said. <span class="said" data-who="Ochoa">"I'll introduce you and then I'm furniture."</span>`,`She had a plan that was two weeks old, a stakeholder map, and a lot of things she didn't know yet.`],
      opts:[
        {t:`Wait to hold the all-hands until the full project plan and timeline are done.`, s:1, d:{trust:-1,conf:0,health:0},
          after:`She asks Ochoa to push it a month. He does. In the meantime the rumor mill fills the silence with a go-live date that doesn't exist.`,
          why:`Wanting to have answers is natural. But silence doesn't stay empty. Communicate early, say what you know and what you don't, and say when they'll hear more.`},
        {t:`Say what's happening and why, what's still unknown, and when they'll hear more.`, s:3, best:true, d:{trust:5,conf:4,health:1},
          after:`She uses six slides. One says "What we don't know yet" in large type, with a date for each answer. She takes questions for fifteen minutes and writes every one on a list she posts that afternoon. The Laramie nurse from the unit chat asks a question. Maria answers it by name.`,
          why:`Good business communication is clear, honest, and two way. Name the change and the reason, separate what's decided from what isn't, commit to when people will hear more, and give them a way to ask. Then keep the commitment.`},
        {t:`Walk through Corvane's best features with a demo so people get excited about it.`, s:0, d:{trust:-2,conf:0,health:0},
          after:`The demo runs long. The Wyoming nurses watch someone in Fort Collins click through a system they didn't choose. The chat fills with questions about staffing, and there's no time left to answer them.`,
          why:`Features answer a question nobody asked yet. People want to know what's happening to them, when, and why. Lead with that.`},
        {t:`Read the MedaLink notice aloud and explain that the vendor forced the decision.`, s:0, d:{trust:-2,conf:-1,health:0},
          after:`It's accurate. It's also the start of a story where nobody at Cascade is responsible for anything, and the staff can tell.`,
          why:`Blaming the vendor feels safe. It tells people the change is being done to all of you, and it gives away the reason that actually matters: what it does for patients.`}
      ]},
    { id:`f1s8`, domain:`Environments`, task:`E6`, title:`Phase two`,
      text:(s,all,G)=>[`Sam Okafor from Halcyon AI called Thursday. They'd worked together on the documentation agents launch, a year of late nights and one very good go-live. He was a director now.`,`<span class="said" data-who="Sam">"Congratulations on the office. Quick thing. The discharge instructions agents are ready to build. Cheyenne asked for them first. We can integrate with MedaLink in about three months. Want me to put it on the schedule?"</span>`,`It would be a win for Cheyenne. And Sam was a friend.`],
      opts:[
        {t:`Say yes. Cheyenne asked, Sam's team is ready, and it's a quick win for the hospital.`, s:0, d:{trust:2,conf:-2,health:-5},
          after:`The work starts. Four months later Halcyon has built an interface to a system with sixteen months left to live, and will now have to build it again for Corvane.`,
          why:`A quick win on a dying platform is a slow loss. Building on MedaLink means paying twice. Look at the whole application portfolio before adding to it.`},
        {t:`Sequence it after One Chart, building it once on Corvane as part of the clinical portfolio.`, s:3, best:true, d:{trust:1,conf:4,health:4},
          after:`Sam doesn't argue. <span class="said" data-who="Sam">"That's the call I'd make. I'll tell Cheyenne the why."</span> Phase two goes on the roadmap for the month after go-live. One interface, one build, one set of testing.`,
          why:`Every new clinical application belongs in the portfolio, sequenced against what's already moving. Integrating with a system you're retiring doubles the cost and the risk. Build it once, on the platform you're keeping.`},
        {t:`Ask Sam to build it as a standalone tool that doesn't connect to MedaLink at all.`, s:0, d:{trust:0,conf:-1,health:-3},
          after:`A standalone tool means nurses copy and paste between two screens. Within a week someone pastes the wrong patient's instructions. It's caught at the bedside.`,
          why:`A clinical application that doesn't integrate with the record creates double entry, and double entry creates errors. Integration isn't optional for clinical tools.`},
        {t:`Ask Cheyenne's leaders whether they'd rather have it now or wait until One Chart.`, s:1, d:{trust:2,conf:0,health:-1},
          after:`Cheyenne says now, of course. Nobody asked them to weigh the cost of building it twice, because nobody told them.`,
          why:`Engaging the hospital is good. Asking them to choose without the facts isn't consultation. Bring the cost of building twice and recommend.`}
      ]},
    { id:`f1s9`, domain:`Leadership`, task:`L1`, title:`The ninety day plan`,
      text:(s,all,G)=>[`Ochoa wanted her priorities for the next ninety days. Not just One Chart. Everything in clinical systems: forty open requests, two upgrades, the analyst team's backlog, and whatever was about to break.`,`<span class="said" data-who="Ochoa">"Give me five things, not forty,"</span> he said.`],
      opts:[
        {t:`Rank the forty requests by who's asking loudest and start from the top.`, s:0, d:{trust:-2,conf:-2,health:-2},
          after:`The loudest requests come from the two physicians with the most email stamina. Rawlins, which never complains, gets nothing.`,
          why:`Volume isn't value. Priorities should come from the organization's goals and an honest look at the environment, not from who's most persistent.`},
        {t:`Do a quick SWOT with her leads, check it against the system's goals, and pick five.`, s:3, best:true, d:{trust:4,conf:5,health:3},
          after:`She gets her leads in a room for two hours. Strengths, weaknesses, opportunities, threats, on a whiteboard. MedaLink's end of support is a threat. Marcus's interface knowledge is a strength and a weakness at the same time. Five priorities fall out, each tied to a system goal. Ochoa reads them and crosses nothing out.`,
          why:`Strategic planning starts with the mission and goals, looks at the environment with a tool like SWOT, and then sets a small number of priorities that serve the goals. Involving your leads gives you better information and their buy in.`},
        {t:`Make One Chart the only priority and freeze every other request for ninety days.`, s:1, d:{trust:-3,conf:2,health:1},
          after:`It's focused. It also means the Greeley upgrade that fixes a known safety bug sits for three months. Aisha finds out and isn't happy.`,
          why:`Focus is good, and One Chart is the biggest thing. Freezing everything ignores real risks elsewhere. Prioritize; don't pretend the rest of the portfolio stopped.`},
        {t:`Ask each analyst to send in their own top five, then combine all the lists.`, s:0, d:{trust:2,conf:-2,health:-1},
          after:`She gets nine lists and thirty-one distinct priorities. Combining them takes a week and pleases nobody.`,
          why:`Input from the team is valuable. Adding up personal priorities isn't strategy. Start from the organization's goals and let the team help you test them.`}
      ]},
    { id:`f1s10`, domain:`Systems Management`, task:`SA7`, title:`The shiny thing`,
      text:(s,all,G)=>[`Friday morning the head of cardiology at Fort Collins sent Maria a vendor brochure for a new heart failure app. Remote weight monitoring, a patient phone app, a dashboard for nurses. He'd already done a demo. <span class="said" data-who="man">"We want it live by summer. Budget's not an issue, my service line has the money."</span>`,`It looked good. It might even help patients.`],
      opts:[
        {t:`Approve it, since cardiology is paying and the app supports patient care.`, s:0, d:{trust:2,conf:-3,health:-4},
          after:`Cardiology buys it. Nine months later IT discovers it stores patient data in a cloud nobody reviewed, doesn't connect to Corvane, and duplicates a remote monitoring module Cascade already licenses.`,
          why:`Who pays isn't the question. Every application has to fit the strategy, the architecture, and the security model, and you have to check whether you already own something that does it.`},
        {t:`Tell him no, because nothing new gets started until One Chart is finished.`, s:0, d:{trust:-4,conf:-1,health:0},
          after:`He goes over her head. Ochoa calls her, mildly annoyed, to ask why she said no without looking at it.`,
          why:`A blanket no is as unexamined as a blanket yes. Evaluate it. Some requests should wait, and some shouldn't.`},
        {t:`Run it through intake against the strategic plan and what Cascade owns.`, s:3, best:true, d:{trust:1,conf:4,health:4},
          after:`Intake takes three weeks. The review finds Cascade already licenses a remote monitoring module in Corvane that does most of it. Cardiology pilots that instead, on Maria's analysts' time, and the heart failure program becomes part of the system's population health goal.`,
          why:`Strategic alignment applies to every request, not just the big ones. Check it against the organization's goals, the existing portfolio, the architecture, and security. Often the answer is already sitting in a module you pay for.`},
        {t:`Let cardiology run it as a pilot on their own, and evaluate it after summer.`, s:1, d:{trust:3,conf:0,health:-2},
          after:`The pilot is small and well meant. But a pilot without IT and security review still puts patient data somewhere nobody checked.`,
          why:`Pilots are a smart way to learn. A pilot is still a system with patient data in it. It goes through the same review, just smaller.`}
      ]},
    { id:`f1s11`, domain:`Leadership`, task:`L2`, title:`The surgeon`,
      text:(s,all,G)=>[`Dr. Walt Hagen met her in the Laramie surgeons' lounge with a stack of paper. Thirty-one years in practice, reading glasses on a cord, a printed copy of every note he had signed that week.`,`<span class="said" data-who="Walt">"I count clicks,"</span> he said. <span class="said" data-who="Walt">"Forty-one to discharge a gallbladder in MedaLink. I'm told your new system is better. I've been told that three times in my career. Every time it was worse."</span>`,`He wasn't hostile. He was tired, and he'd been right before.`],
      opts:[
        {t:`Promise him Corvane will take fewer clicks, since she's seen it at the other hospitals.`, s:0, d:{trust:-3,conf:-1,health:0},
          after:`He writes it down. <span class="said" data-who="Walt">"Fewer clicks. I'll hold you to that."</span> She has no idea how many clicks it will take to discharge a gallbladder in Corvane.`,
          why:`Never promise what you haven't measured. To a skeptic, a broken promise is proof. Ask, observe, and promise only what you can deliver.`},
        {t:`Ask him to show her his discharge workflow, and invite him to help design it.`, s:3, best:true, d:{trust:6,conf:2,health:2},
          after:`He shows her all forty-one clicks, narrating. Three are a workaround for a lab feed that sometimes doesn't post. She writes that down twice. Then she asks if he'll sit on the physician design group. He looks at her over the glasses for a long time. <span class="said" data-who="Walt">"Fine. But I'll tell you when it's worse."</span> She says she's counting on it.`,
          why:`Respect the culture and the people in it. A thirty year surgeon's skepticism is earned, and his workflow knowledge is something you need. Listen, observe, and bring skeptics inside the design. They become your best testers.`},
        {t:`Explain that the decision is made, and focus him on how training will help him adjust.`, s:1, d:{trust:-2,conf:1,health:0},
          after:`It's true. He nods and says nothing. You can't tell whether he agrees or has just stopped talking to you.`,
          why:`Being clear that the decision is final is honest. Skipping straight to training tells him his experience doesn't matter.`},
        {t:`Ask the Laramie CMO to talk to him, since physician concerns belong to medical staff.`, s:0, d:{trust:-2,conf:0,health:0},
          after:`The CMO talks to him. Walt now believes Fort Collins sends people to manage him rather than listen to him, and he's not wrong.`,
          why:`Medical staff leadership matters, and you'll work with them. But he came to you. Handing off the conversation you were invited to costs you the relationship.`}
      ]},
    { id:`f1s12`, domain:`Environments`, task:`E3`, title:`11:40 PM`,
      text:(s,all,G)=>[`Maria was asleep on the couch with a binder on her chest when her phone buzzed.`,`<prop type="chat" from="Marcus Bell" time="11:40 PM"><span class="said" data-who="Marcus">lab results interface to laramie is down. relay queue backed up. looks like since about 8:30. nobody called it in. i can restart it but you should know.</span></prop>`,`Three hours. She had admin access to Relay; she'd been given it for the Halcyon project and nobody had taken it back. She could log in from the couch and restart it herself in five minutes.`],
      opts:[
        {t:`Log in and restart the interface herself, then sort out the paperwork in the morning.`, s:1, flag:`solofix`, d:{trust:-3,conf:1,health:-2},
          after:`It comes back up at 11:58. It's fast. It's also undocumented, outside change control, and Marcus watches the queue drain without knowing what she changed. In the morning nobody can say for certain what was done.`,
          why:`Old habits. The nurse who fixes it at 2 AM got you here, and she's the wrong person for this one. You aren't on call and you aren't the engineer. Undocumented midnight fixes are how the next outage gets harder to diagnose.`},
        {t:`Have Marcus restart it under emergency change, and alert the Laramie supervisor.`, s:3, best:true, d:{trust:5,conf:3,health:5},
          after:`Marcus opens an emergency change and restarts it at 11:52. Maria calls the Laramie house supervisor, who has the lab phone every critical result from the last three hours to the floors. A potassium of 6.8 reaches a nurse at 12:20. Then Maria opens a notes file titled "Why nobody noticed."`,
          why:`Roles matter most at midnight. The engineer fixes it through the emergency change process. Your job is patient safety and coordination: get clinical leadership running downtime procedures so critical results reach caregivers, and make sure someone owns finding the cause.`},
        {t:`Tell Marcus to restart it, then go back to sleep and review it at Tuesday's meeting.`, s:0, d:{trust:0,conf:-2,health:-5},
          after:`The interface comes back. Nobody tells Laramie that three hours of lab results just arrived at once. A critical potassium sits in a result queue until a day nurse finds it at 7 AM.`,
          why:`Restoring the system isn't the same as restoring care. Results that arrive late and silently can still hurt someone. Clinical notification is part of the response.`},
        {t:`Ask Marcus to wait until she reaches Ochoa and gets his approval to restart it.`, s:0, d:{trust:-3,conf:-1,health:-3},
          after:`Ochoa's phone is off. It takes twenty-five minutes to reach him. He says, <span class="said" data-who="Ochoa">"Why are you calling me? Marcus knows how to fix it."</span>`,
          why:`Escalate what's above your authority, not what's already covered. The emergency change process exists so the on call engineer can act. Waiting for the CIO costs patients time.`}
      ]}
  ],
  exercise: { after:`f1s4`, title:`Who owns it?`, intro:`New leaders in health IT mix up these roles. Match each situation to the person who owns it.`,
    items:[
      {prompt:`Decides what a sepsis alert should say and when it should fire, through the clinical informatics council.`, choices:[`CIO`,`CMIO`,`CISO`,`Privacy officer`], answer:1, why:`Clinical decision support content belongs to clinicians. The CMIO leads it through governance.`},
      {prompt:`Investigates a complaint that a staff member looked at a neighbor's chart without a reason.`, choices:[`CISO`,`Nurse manager`,`Privacy officer`,`CNIO`], answer:2, why:`Use and disclosure of patient information, privacy complaints, and breach assessments belong to the privacy officer.`},
      {prompt:`Owns the program that protects systems from malware, phishing, and unauthorized access.`, choices:[`CISO`,`CIO`,`Data steward`,`Interface engineer`], answer:0, why:`Information security, the protection of systems and data from threats, belongs to the CISO.`},
      {prompt:`Owns the IT strategic plan and budget, and presents them to the board.`, choices:[`CMIO`,`CFO`,`VP of clinical systems`,`CIO`], answer:3, why:`The CIO owns overall IT strategy and budget and answers to executive leadership and the board.`},
      {prompt:`Leads nursing adoption of the eMAR and BCMA and represents nursing in system design.`, choices:[`CNIO`,`CMIO`,`Superuser`,`Chief nursing officer`], answer:0, why:`The CNIO bridges nursing practice and informatics, the way the CMIO does for physicians.`},
      {prompt:`Defines what "active patient" means in reports and protects the quality of that data.`, choices:[`Clinical analyst`,`Data steward`,`CIO`,`Help desk manager`], answer:1, why:`A data steward defines and protects specific data. The data owner decides; IT is the custodian.`}
    ]},
  quiz: [
    {q:`A 22-bed rural hospital with swing beds receives special federal payment rules that help keep inpatient care available locally. What type of facility is it most likely to be?`, opts:[`An academic medical center`,`A critical access hospital`,`An ambulatory surgery center`,`A long term acute care facility`], a:1, why:`Small rural hospitals, typically 25 beds or fewer, with special federal designation and payment rules are critical access hospitals.`, task:`E1`, domain:`Environments`, level:`RE`},
    {q:`A health system plans to retire the EHR at three of its hospitals. Which group is MOST likely to be missed in the stakeholder analysis?`, opts:[`Nurses on the inpatient units`,`Hospital department directors`,`The regional HIE and payers`,`The hospitals' physicians`], a:2, why:`Internal staff are obvious. Organizations connected by data, like the HIE, payers, public health, and referring providers, are the ones most often missed.`, task:`E2`, domain:`Environments`, level:`AP`},
    {q:`Hospitalists ask an EHR analyst to change the starting dose in a heparin order set used across the health system. What should happen next?`, opts:[`The analyst builds it after hospitalist approval`,`The CIO approves it as the owner of the EHR`,`The vendor confirms the dose is clinically safe`,`It goes to clinical governance for approval first`], a:3, why:`Clinical content belongs to clinicians through governance, such as a clinical informatics council that includes pharmacy. IT builds what governance approves.`, task:`E3`, domain:`Environments`, level:`AP`},
    {q:`Which application family does a patient portal belong to?`, opts:[`Consumer`,`Administrative`,`Financial`,`Business intelligence`], a:0, why:`Patient facing tools like portals, telehealth, and remote monitoring are consumer applications.`, task:`E6`, domain:`Environments`, level:`RE`},
    {q:`An IT leader learns that a legacy EHR at three hospitals will lose vendor support. What should the leader do FIRST?`, opts:[`Issue an RFP for a replacement system`,`Inventory what the system does and feeds`,`Request a support extension from the vendor`,`Announce a go-live date to hold the team`], a:1, why:`Assess before acting. In small hospitals the EHR often handles registration, billing, interfaces, and reports. You can't plan a replacement until you know everything it does.`, task:`E6`, domain:`Environments`, level:`AP`},
    {q:`A CIO asks for the justification for a major EHR migration. Which argument will be MOST persuasive to the board?`, opts:[`The new system has a more modern user interface`,`The current vendor is ending product support soon`,`It advances three of the system's strategic goals`,`Other health systems in the region already use it`], a:2, why:`Boards fund strategy. Showing which organizational goals the initiative serves is the strongest justification. End of support is a trigger, not the reason.`, task:`SA7`, domain:`Systems Management`, level:`AN`},
    {q:`A service line chief wants to buy a remote monitoring app with department funds. What is the BEST next step?`, opts:[`Approve it, since the department is paying`,`Run it through intake and portfolio review`,`Decline until the current project is done`,`Let the department pilot it independently`], a:1, why:`Every application, whoever pays, should be checked for strategic fit, architecture, security, and overlap with what the organization already owns.`, task:`SA7`, domain:`Systems Management`, level:`AP`},
    {q:`A new vice president must set priorities from forty open requests. Which approach BEST reflects strategic planning?`, opts:[`Assess the environment and tie priorities to goals`,`Rank requests by how often they have been raised`,`Combine each team member's personal top five list`,`Work requests in the order they were submitted`], a:0, why:`Strategic planning starts from the mission and goals, assesses the environment (for example with SWOT), and sets a few priorities that serve those goals.`, task:`L1`, domain:`Leadership`, level:`AN`},
    {q:`In a SWOT analysis, a vendor's announcement that it will end support for a core system is BEST classified as a:`, opts:[`Strength`,`Weakness`,`Opportunity`,`Threat`], a:3, why:`It's an external factor that could harm the organization, which makes it a threat.`, task:`L1`, domain:`Leadership`, level:`RE`},
    {q:`Staff at three recently affiliated hospitals post complaints that the parent system never asks for their input. What should the clinical systems leader do FIRST?`, opts:[`Post an intranet message on the project's benefits`,`Ask local leaders to deliver the project message`,`Visit the units in person and listen to the staff`,`Wait, since resistance tends to fade over time`], a:2, why:`Understanding organizational culture comes before changing it. Showing up and listening addresses the trust problem directly; another memo confirms it.`, task:`L2`, domain:`Leadership`, level:`AP`},
    {q:`A veteran surgeon says three previous EHR rollouts made his work slower. What is the MOST effective response?`, opts:[`Promise the new system will take fewer clicks`,`Observe his workflow and invite him to design`,`Explain that the decision has already been made`,`Refer his concerns to the chief medical officer`], a:1, why:`Skeptical clinicians hold real workflow knowledge. Observing and involving them in design builds trust and catches problems early.`, task:`L2`, domain:`Leadership`, level:`AN`},
    {q:`A leader is announcing a major system change before all details are known. Which message is MOST effective?`, opts:[`A detailed demo of the new system's features`,`A notice that the vendor forced the change`,`A delay until the complete plan is finished`,`What is known, what isn't, and when updates come`], a:3, why:`Effective change communication is honest and two way: what's happening and why, what's decided and what isn't, when people will hear more, and how to ask questions.`, task:`L12`, domain:`Leadership`, level:`AN`},
    {q:`A lab interface fails overnight and results stop reaching a hospital for three hours. After the engineer restores the feed, what is the MOST important next step for patient safety?`, opts:[`Notify nursing so delayed critical results are called`,`Write a root cause report for the morning meeting`,`Restrict admin access to the interface engine`,`Tell the CIO about the outage before morning`], a:0, why:`Restoring the interface doesn't restore care. Delayed critical results must reach caregivers, so clinical leadership needs to run the downtime and callback procedures.`, task:`E3`, domain:`Environments`, level:`AN`},
    {q:`Which term describes a clinician entering medication and lab orders directly into the EHR?`, opts:[`eMAR`,`CPOE`,`BCMA`,`PACS`], a:1, why:`Computerized provider order entry (CPOE) is electronic ordering by clinicians. eMAR records administration, BCMA scans at the bedside, and PACS stores images.`, task:`C2`, domain:`Clinical Informatics`, level:`RE`},
    {q:`A nurse scans a patient's wristband and the medication barcode before giving a dose. Which system function is being used?`, opts:[`Computerized order entry`,`Clinical decision support`,`Bar code administration`,`Admit, discharge, transfer`], a:2, why:`Bar code medication administration (BCMA) verifies the right patient and right medication at the bedside by scanning both.`, task:`C4`, domain:`Clinical Informatics`, level:`AP`}
  ],
  closing:(s,all,G)=>[
    ((s.flags.solofix||G.solofix)
      ?`By 12:30 the queue was empty and the interface was green. Maria sat on the couch with her laptop open, looking at a system she had restarted without writing down how. Marcus had gone quiet in the chat. She couldn't tell whether he was relieved or offended. Probably both.`
      :`By 12:30 the queue was empty and the interface was green. The Laramie house supervisor called back to say every critical result from the last three hours had reached a nurse, including a potassium of 6.8 on a dialysis patient who was now on a monitor. Marcus typed <span class="said" data-who="Marcus">"emergency change closed. thx for the call to laramie."</span> It was the most words he'd ever sent her.`),
    `Lucia came downstairs at one for a glass of water and found her mother at the kitchen table in the blue light of a laptop. <span class="said" data-who="Lucia">"Is someone dying?"</span> she asked, the way teenagers ask things they half mean.`,
    `<span class="said" data-who="Maria">"No,"</span> Maria said. <span class="said" data-who="Maria">"Somebody almost didn't find out about a lab result. It's fine now."</span>`,
    `<span class="said" data-who="Lucia">"Isn't that, like, the whole job? Finding out about the lab result?"</span> Lucia filled her glass and went back upstairs, leaving the question in the kitchen.`,
    (s.score>=30
      ?`Maria thought about the week. She'd sent the heparin change to the council, walked the floors in Laramie, said no to a shiny app without saying no to a doctor, and gotten a surgeon to agree to tell her when she was wrong. It had been a good first week. That was what bothered her. A good first week, and a lab interface had been dead for three hours without a single alarm.`
      :`Maria thought about the week. She'd made some calls she'd want back. Ochoa would tell her which ones on Tuesday, probably before she sat down. But the thing that kept her awake wasn't any of her decisions. It was the three hours.`),
    `She opened a new file and typed the question at the top. Not how it broke. Marcus would find that. The other question. Why had a lab interface to a hospital been down for three hours, in a health system with eleven hospitals and a twenty-four hour help desk, and nobody had noticed until one engineer happened to look?`,
    `At 6:45 AM her phone buzzed again. Ochoa. <span class="said" data-who="Ochoa">"Heard about Laramie. I want to know why it took three hours before I want to know why it broke. And there's something else. The Joint Commission is at Greeley this morning. Unannounced."</span>`
  ],
  episode:{src:`audio/full-ch01.mp3`, len:`about 35 minutes`},
  next:`The Rulebook`
});
