(((window.HALCYON_DATA=window.HALCYON_DATA||{}).gh300=window.HALCYON_DATA.gh300||{}).full=window.HALCYON_DATA.gh300.full||[]).push({
  num: 1, part: `Part One: Wheels Up`, title: `The Mandate`, weeks: `Week 1`,
  tasks: [`F1`,`F4`,`R1`,`S1`,`V1`],
  cast: [
    [`Devin Ruiz`,`Engineer. Fast, talented, and already letting Copilot write whole functions.`],
    [`Renata Vega`,`Junior engineer in her first month. Asks the questions everyone else is embarrassed to ask.`],
    [`Tomasz Nowak`,`Leads the Kraków engineering team, eight hours ahead of Denver.`],
    [`Raj Shah`,`Priya's father. Retired machinist in Aurora.`]
  ],
  opening: [
    `The email arrived at 6:12 on a Monday morning, which meant Elena had written it on the treadmill.`,
    `<prop type="email" from="Elena Vasquez" to="All Engineering" time="Monday, 6:12 AM" subject="Copilot, this quarter">Team,<br>Every engineer at Halcyon will be using GitHub Copilot by the end of the quarter. Our competitors already are. Priya Shah will lead the rollout and has my full support. Lena is the sponsor. Please give Priya whatever she needs.<br>Elena</prop>`,
    `Priya Shah read it on her phone in the parking garage, still in the car, the engine off and the radio still talking about the Broncos. She read it a second time to make sure her name was actually in it. It was. It was in the same sentence as "full support," which at Halcyon could mean anything from a real budget to a blessing and a deadline.`,
    `Six months ago she'd been a data engineer who kept quiet in meetings. Then Theo Lindqvist took another job, and somebody had to own the platform, and the somebody turned out to be her. Then she ran the phase two discharge project for Cascade, her first project with her name at the top of the plan, and it shipped on time because she'd been too scared to let it slip. Now this. A rollout to ninety engineers, most of them older than her, several of them people who had trained her.`,
    `Her phone buzzed before she got to the elevator. Theo, who was back at Halcyon on a six month contract, which still felt strange. <span class="said" data-who="Theo">"congrats on the robot job. I'll trust it when it can explain my own Terraform to me."</span>`,
    `She typed three replies and deleted all of them. Then Sam Okafor's name lit up the screen. He was Director of Delivery now, and somewhere along the way he'd become the person she called before she panicked.`,
    `<span class="said" data-who="Sam">"Saw the email,"</span> he said. <span class="said" data-who="Sam">"Before you do anything, what do you actually know about how people here use Copilot today?"</span>`,
    `<span class="said" data-who="Priya">"Honestly? Not much."</span>`,
    `<span class="said" data-who="Sam">"Good. That's the right starting point. Ruth left you something on your desk."</span>`,
    `On her keyboard was a sheet of paper in green ink. At the top Ruth Calder had written: <span class="said" data-who="Ruth">"Flight rules for a new kind of copilot. Read before you fly."</span>`
  ],
  lesson: {
    title: `Ruth's Whiteboard: what you're actually rolling out`,
    sections: [
      { h: `Know what you're buying`,
        body: [`Ruth's first line was underlined twice. <span class="said" data-who="Ruth">"Before you put a new system in the cockpit, know exactly which system it is."</span> GitHub Copilot comes in individual plans and organization plans. The individual plans are Copilot Free, Copilot Student, Copilot Pro, Copilot Pro+, and Copilot Max. Free is for trying it out, with limits, including a cap on inline suggestions each month. Student is free for verified students. Pro, Pro+, and Max add more models and larger usage allowances for one person, who pays for it and manages it.`,
          `The organization plans are Copilot Business and Copilot Enterprise. Business is for organizations and adds the thing a rollout needs most: centralized management and policy control over the people the organization gives a seat to. Enterprise includes everything in Business plus enterprise grade capabilities and a larger usage allowance, and it's for companies on GitHub Enterprise Cloud. Copilot isn't available for GitHub Enterprise Server. Today GitHub measures usage in AI credits, with a monthly allowance by plan. Older study material and some exam questions may still say "premium requests." Learn the stable idea: plans include a usage allowance, and heavier features and models use more of it.`],
        terms: [[`Copilot Business`,`The organization plan that adds central seat management and Copilot policy control for members.`],[`Copilot Enterprise`,`Everything in Business plus enterprise grade capabilities, for organizations on GitHub Enterprise Cloud.`],[`Individual plan`,`Free, Student, Pro, Pro+, or Max. Owned and managed by one person, not the organization.`]],
        exam: `When a question asks which plan lets an organization set policies for its members, the answer is Business or Enterprise. When it mentions GitHub Enterprise Cloud and enterprise grade features, lean Enterprise. An individual plan never gives the company control.` },
      { h: `Where Copilot lives`,
        body: [`Copilot shows up in several places, and the exam expects you to know which is which. In the editor you get inline suggestions as you type, Copilot Chat in a side panel, and agent mode, where Copilot makes multi file edits and proposes terminal commands while you watch and approve. In the terminal there's GitHub Copilot CLI. On GitHub.com you get chat, pull request summaries, Copilot code review, and the coding agent you can assign an issue to.`,
          `The editor support comes from extensions. GitHub documents setup for Visual Studio Code, Visual Studio, JetBrains IDEs, Vim and Neovim, Xcode, Eclipse, and Azure Data Studio. GitHub.com is not an IDE, and there's no GitHub.com extension to install. To turn Copilot on in an editor, you install the extension and sign in with the GitHub account that holds the Copilot seat. Signed in with the wrong account, a developer sees nothing, and it looks like Copilot is broken.`],
        terms: [[`Inline suggestion`,`Code Copilot proposes as you type, which you accept, reject, or ignore.`],[`Agent mode`,`An IDE mode where Copilot makes multi file edits and proposes terminal commands while the developer reviews and approves.`]],
        exam: `Expect a list of environments with one that doesn't belong. GitHub.com is the usual trap: Copilot works there, but it isn't an IDE extension.` },
      { h: `Turning it on for an organization`,
        body: [`An organization owner manages Copilot from the organization's Settings, under Copilot. The Access page is where seats are granted, either to all members, which covers current and future members, or to selected teams and members. Billing starts when a seat is granted, not when someone first uses it. Seats can also be managed through the REST API, which is how larger companies automate it.`,
          `The Policies page controls which features are available and the privacy related settings, and the Models page controls access to models beyond the basic ones. If the organization belongs to an enterprise, enterprise policies win. When an enterprise owner sets a policy, the organization can't override it. The audit log records Copilot plan and policy changes and seats being added or removed. It does not include the prompts people send to Copilot in their editors. Events are kept for 180 days, so a company that needs longer evidence streams the log somewhere else.`],
        terms: [[`Seat`,`A Copilot license an organization grants to a member. Billing starts when it's granted.`],[`Policy`,`An organization or enterprise setting that controls a Copilot feature, a privacy setting, or model access for people with seats.`]],
        exam: `Know who wins: enterprise policy over organization policy. Know what the audit log shows: settings, policy changes, and seat changes, not prompts or suggestions.` },
      { h: `What your fences don't reach`,
        body: [`Here Ruth had drawn a box with a line running outside it. Organization policies apply to the seats the organization grants. Content exclusions, which stop Copilot from using chosen files or repositories as context, are a Business and Enterprise feature, and an organization owner sets them for the people who have a seat through that organization. A developer using a personal Pro plan on company code is outside that box. The company can't apply its policies to that plan, can't see it in its audit log, and can't promise an auditor what it did.`],
        terms: [[`Content exclusion`,`A setting that keeps chosen files or repositories from being used as Copilot context and from getting inline suggestions.`]],
        exam: `If a scenario says some developers use personal plans and the company wants consistent policies or exclusions, the answer moves them onto organization seats.` },
      { h: `Flight rules`,
        body: [`The last section was short. <span class="said" data-who="Ruth">"A copilot is a crew member, not a pilot. It can be confidently wrong."</span> Generative AI predicts likely output from patterns. That means it can produce code that looks right and isn't, use outdated or insecure patterns, invent an API that doesn't exist, reflect bias in its training data, or produce code that matches public code with a license attached. The mitigations are ordinary engineering discipline: a human reviews it, tests prove it, and the person who accepts a suggestion owns it exactly as if they'd typed it.`,
          `Ruth added one more line about how it works. When you ask Copilot for something, it builds a prompt from what you typed plus context from your editor, like the file you're in, the code near your cursor, and other open files. That prompt goes to the Copilot service, passes through filters, and the response is filtered again before it reaches you. <span class="said" data-who="Ruth">"Better context in, better answers out. Everything out still gets checked."</span>`],
        terms: [[`Hallucination`,`Output that sounds confident and is wrong, such as a function or library that doesn't exist.`],[`Context`,`The information Copilot uses to build a prompt, such as the current file, nearby code, and open tabs.`]],
        exam: `Responsible use answers almost always include human review and testing. "Trust it because it's usually right" is the wrong answer every time.` }
    ],
    video: [`MOM0Fj5V0f0`,`Setup GitHub Copilot for Business`,`GitHub`,`2:20`]
  },
  scenes: [
    { id:`f1s1`, domain:`Copilot Features`, task:`F1`, title:`Where to start`,
      text:(s,all,G)=>[`By nine, Priya had a blank document titled "Copilot rollout" and eleven Slack messages asking when people would "get it." Lena Cho stopped by with coffee and the look of a sponsor who would rather not be asked hard questions.`,`<span class="said" data-who="Lena">"Elena wants a plan by Friday. What do you need?"</span>`,`Priya didn't know yet. That was the problem. What does she do first?`],
      opts:[
        {t:`Survey the team: who uses Copilot now, on what plan, in which editors.`, s:3, best:true, d:{trust:3,conf:3,health:4},
          after:`The survey takes two days and fifty seven people answer. Thirty one are already using Copilot. Most are on personal plans they expense. They use five different editors. Two people are pasting code into a chatbot in a browser tab. None of this was on any diagram.`,
          why:`Assess before you act. You can't pick a plan, set policies, or plan training until you know what's already happening. The current state is always messier than the org chart says.`},
        {t:`Buy Business seats for all ninety engineers today so nobody is left waiting.`, s:0, d:{trust:2,conf:1,health:-5},
          after:`The seats are live by lunch. Billing starts the same minute. By Wednesday Ken asks which repositories have exclusions set. None do. Nobody had asked.`,
          why:`Speed feels like leadership on day one. Granting seats before you know the current state and before policies are set means people start using it with no guardrails, and you're paying from the moment the seat exists.`},
        {t:`Ask Theo which plan to buy, since he's the one people will listen to.`, s:1, d:{trust:1,conf:0,health:0},
          after:`Theo says Enterprise, because it has the most features. He hasn't looked at what Halcyon's GitHub account actually is. It's useful input from a sharp person, and it isn't a picture of the team.`,
          why:`Talking to an expert is fine. One expert's preference isn't an inventory of how ninety people actually work.`},
        {t:`Book a vendor demo with GitHub sales for this week and decide based on that.`, s:0, d:{trust:0,conf:-1,health:-2},
          after:`The demo is polished. Every feature looks great on a sample repo. Nobody in the room can say which of them Halcyon needs.`,
          why:`A demo tells you what the product can do. It doesn't tell you what your people do today or what they need.`}
      ]},
    { id:`f1s2`, domain:`Copilot Features`, task:`F1`, title:`The odd editors`,
      text:(s,all,G)=>[`The survey had a free text box, and people used it. One answer said: "I use Neovim, so I assume I'm out." Another said: "Can we install the GitHub.com extension so it works in the browser?" A third said Xcode, from the one engineer who still maintained the old iPad app.`,`Priya needed to answer before the questions turned into folklore.`],
      opts:[
        {t:`Tell them Neovim and Xcode have Copilot extensions, and Copilot on GitHub.com is built in.`, s:3, best:true, d:{trust:4,conf:2,health:2},
          after:`She posts the supported list from GitHub's docs in the channel: VS Code, Visual Studio, JetBrains IDEs, Vim and Neovim, Xcode, Eclipse, Azure Data Studio. And a line underneath: GitHub.com isn't an IDE, so there's nothing to install there. The Neovim engineer replies with a single thumbs up, which from him is a parade.`,
          why:`Know the supported editors. Neovim and Xcode both have Copilot support. GitHub.com isn't an IDE extension at all. Copilot is part of the site itself.`},
        {t:`Standardize everyone on VS Code, since it's the editor with the best support.`, s:0, d:{trust:-6,conf:0,health:-1},
          after:`The JetBrains users take it personally. Theo starts a thread titled "editor freedom" that runs to ninety replies. Nobody needed to switch editors at all.`,
          why:`Forcing a tool change people don't need creates resistance you'll pay for all quarter. Copilot supports the editors they already use.`},
        {t:`Say Neovim is supported and the browser extension is coming, and promise to check on Xcode.`, s:1, d:{trust:1,conf:0,health:0},
          after:`Two out of three. The "browser extension" line spreads, and a week later someone is still searching the marketplace for a GitHub.com extension that doesn't exist.`,
          why:`Close. The mistake is treating GitHub.com as something you install an extension for. Copilot on GitHub.com is part of the site.`},
        {t:`Tell the Neovim and Xcode users to use Copilot Chat on GitHub.com instead.`, s:0, d:{trust:-2,conf:0,health:-2},
          after:`They try it for a day and go back to doing everything by hand. Pasting code into a browser tab isn't how anyone wants to work.`,
          why:`There's no reason to push them out of their editors. Both editors are supported. Check the docs before you invent a workaround.`}
      ]},
    { id:`f1s3`, domain:`Copilot Features`, task:`F4`, title:`Which plan`,
      text:(s,all,G)=>[`Wednesday Priya sat down with the account details. Halcyon's code lived in a GitHub organization on the Team plan. Nobody had ever moved it to GitHub Enterprise Cloud. Theo had said Enterprise. Devin had said, in the survey, "Pro is ten bucks, just expense it for everybody."`,`What she needed, more than anything, was a way to set rules once and have them apply to everyone.`],
      opts:[
        {t:`Copilot Pro for each engineer, expensed, since it's cheaper and they already know it.`, s:0, d:{trust:2,conf:-3,health:-5},
          after:`It's cheap. It's also ninety separate subscriptions the company doesn't control, can't apply policies to, and can't show an auditor.`,
          why:`Individual plans are managed by the individual. A rollout that needs consistent policies and evidence needs an organization plan.`},
        {t:`Copilot Business, revisiting Enterprise if Halcyon moves to Enterprise Cloud.`, s:3, best:true, d:{trust:1,conf:4,health:4},
          after:`Lena signs off in ten minutes. Priya writes down the condition that would change the answer: if Halcyon ever moves to GitHub Enterprise Cloud, look at Enterprise again. It goes in the plan as a dated decision, not a vague maybe.`,
          why:`Business gives an organization central seat management and policy control, which is the core need. Enterprise is for organizations on GitHub Enterprise Cloud that want its enterprise grade capabilities. Pick what fits today and write down what would change it.`},
        {t:`Copilot Enterprise now, because it has every feature and they'll grow into it.`, s:1, d:{trust:0,conf:-1,health:-1},
          after:`The sales engineer is thrilled. Then he asks whether Halcyon is on GitHub Enterprise Cloud. It isn't. The project just got a migration nobody planned.`,
          why:`Enterprise is a real option, but it's built for organizations on GitHub Enterprise Cloud. Buying the biggest plan without checking that turns a rollout into a migration.`},
        {t:`Let each team pick its own plan, since teams know their needs best.`, s:0, d:{trust:3,conf:-4,health:-4},
          after:`Within a week there are four kinds of plans across six teams and no single place to see who has what.`,
          why:`Team autonomy is good for how work gets done. It's bad for licensing and policy, which only work when they're consistent.`}
      ]},
    { id:`f1s4`, domain:`Copilot Features`, task:`F4`, title:`The personal accounts`,
      text:(s,all,G)=>[`Thirty one engineers already used Copilot. Twenty six of them did it on personal Pro plans, on company code, expensed or paid out of pocket.`,`Devin was one of them, and he wasn't shy about it. <span class="said" data-who="Devin">"Mine works fine. I've got my settings how I like them. Just let us keep what we have and give seats to everybody else."</span>`,`A few people in the channel added a plus one. Priya felt the old pull to keep the peace.`],
      opts:[
        {t:`Let personal plan users keep them and give org seats only to people with nothing.`, s:0, flag:`personalseats`, d:{trust:4,conf:-3,health:-5},
          after:`Nobody complains. That's the problem with it. A third of the people writing Halcyon code are now on plans the company's policies, exclusions, and audit log can't touch.`,
          why:`Organization policies and content exclusions apply to the seats the organization grants. Personal plans sit outside that fence. Keeping the peace now means a gap you can't explain to an auditor later.`},
        {t:`Move everyone onto org seats, explain why, and help them switch.`, s:3, best:true, d:{trust:2,conf:4,health:5},
          after:`She writes a short note: one plan, one set of rules, one audit trail, and why that matters for code that touches patient workflows. She offers to sit with anyone moving over. Devin grumbles, then asks her to help him find where his editor settings live. They do it in ten minutes.`,
          why:`Consistency is the point of an organization plan. Explain the reason, not just the rule, and make the switch easy. People accept a change when they understand it and someone helps them through it.`},
        {t:`Require org seats, but let people keep personal plans for side projects at home.`, s:1, d:{trust:3,conf:2,health:2},
          after:`Mostly fine. A few people stay signed into the personal account in their work editor out of habit, and nobody notices for a month.`,
          why:`The rule is right. Without checking which account each editor is actually signed into, some company code still runs through personal plans.`},
        {t:`Block anyone with a personal plan from company repos until they cancel it.`, s:0, d:{trust:-7,conf:1,health:-1},
          after:`Devin can't push a hotfix for half a day. The story of the lockout reaches Elena before the reason does.`,
          why:`Right goal, wrong first move. Lead with the reason and an easy path, and escalate only for people who won't move.`}
      ]},
    { id:`f1s5`, domain:`Responsible AI`, task:`R1`, title:`The kickoff`,
      text:(s,all,G)=>[`Thursday's kickoff had sixty people on the call and Theo in the front row of the conference room, arms folded.`,`Devin got there first. <span class="said" data-who="Devin">"Honestly the main thing is speed. It writes it, I ship it. Why would I reread code the machine already wrote?"</span>`,`Theo didn't look up. <span class="said" data-who="Theo">"And that's why I'll be on call."</span>`,`Sixty people waited to see what the new rollout lead would say.`],
      opts:[
        {t:`Agree speed is the goal and say the CI pipeline will catch whatever slips through.`, s:0, d:{trust:-2,conf:-3,health:-6},
          after:`Devin nods. Theo leaves the meeting early. Two weeks later a pull request passes every check and still sends the wrong date to a customer.`,
          why:`Tests catch what someone thought to test for. Generative AI can be confidently wrong in ways nobody wrote a test for. A pipeline doesn't replace a human who understands the code.`},
        {t:`Set the rule: the person who accepts a suggestion owns it, so review and test it.`, s:3, best:true, d:{trust:4,conf:3,health:5},
          after:`She puts it on the shared screen in one line: you own what you accept. Then she asks Theo what he'd look for in a review of Copilot code. He's surprised to be asked. His list is good, and it goes in the guide.`,
          why:`Responsible use starts with accountability. Copilot is a crew member, not the pilot. Treat its output like code from a new teammate: read it, understand it, and test it before it ships.`},
        {t:`Tell the team to use Copilot only for tests and docs until it proves itself.`, s:1, d:{trust:1,conf:0,health:1},
          after:`It's safe. It also teaches people that Copilot is a toy, and the engineers who were already using it well quietly ignore the rule.`,
          why:`Caution is reasonable, but limiting it by task misses the real control. Any output, in any file, needs a human who reviews and owns it.`},
        {t:`Let Theo and Devin argue it out so the team hears both sides.`, s:0, d:{trust:-3,conf:-2,health:-1},
          after:`They argue for twenty minutes. Neither one changes his mind, and the call ends without a rule.`,
          why:`Hearing both sides is fine. Ending the meeting without a clear norm leaves everyone to guess. The rollout lead's job is to set it.`}
      ]},
    { id:`f1s6`, domain:`Copilot Features`, task:`F4`, title:`All at once`,
      text:(s,all,G)=>[`Lena caught her after the kickoff. <span class="said" data-who="Lena">"Can we just turn it on for everyone Friday? Elena would love to see the number go to ninety."</span>`,`Priya knew what the Access page offered. One button covered all members, current and future. The other let her pick teams.`],
      opts:[
        {t:`Turn it on for all members Friday so the number looks good for Elena.`, s:0, d:{trust:1,conf:2,health:-6},
          after:`Ninety seats, Friday afternoon. Every new hire gets one automatically. On Monday Ken asks why the team that works on patient data integrations has Copilot with no exclusions set.`,
          why:`All members is a real option, and it covers future members too. Choosing it before policies and exclusions are ready means the riskiest teams get the tool with no guardrails.`},
        {t:`Grant seats to selected teams in waves, policies set first.`, s:3, best:true, d:{trust:2,conf:3,health:5},
          after:`Wave one is the platform team and Kraków, the people already using it. The integrations team waits a week for Ken's exclusions. Lena gets a number that grows every week and a reason for each step.`,
          why:`Selected teams and members lets you roll out in order. Set the rules first, then hand out the keys. It's slower by days and it saves you weeks.`},
        {t:`Grant seats to selected teams, starting with whoever asks most loudly.`, s:1, d:{trust:2,conf:1,health:0},
          after:`The loud teams are mostly the ones already using it, which is fine. One of them is the integrations team, which isn't.`,
          why:`Using selected teams is right. Ordering by who asks loudest ignores which teams need guardrails in place first.`},
        {t:`Wait until next quarter, when everything is ready, and then do it all at once.`, s:0, d:{trust:-3,conf:-5,health:0},
          after:`Elena reads "next quarter" and calls Lena. Meanwhile twenty six people keep using personal plans.`,
          why:`Waiting for perfect leaves the uncontrolled usage in place. Roll out in waves so control arrives sooner.`}
      ]},
    { id:`f1s7`, domain:`Privacy and Safeguards`, task:`S1`, title:`Ken's list`,
      text:(s,all,G)=>[`Ken Ito sent his message on Friday morning, polite and precise as always. <span class="said" data-who="Ken">"Before the integrations team gets seats, I want to know which repositories hold Cascade configuration and test data. Some of it is patient adjacent. I don't want it used as context."</span>`,`Nora Kim was copied. So was Lena.`],
      opts:[
        {t:`List the sensitive repos with Ken and set exclusions before granting seats.`, s:3, best:true, d:{trust:3,conf:4,health:5},
          after:`They find four repositories and two folders in a fifth. Ken sets the exclusions at the organization level. Nora writes one line in her evidence log: exclusions configured before access granted, with the date.`,
          why:`Content exclusions keep chosen files and repositories out of Copilot's context. On Business and Enterprise an organization owner sets them for people with org seats. Set them before the team that touches the sensitive code gets access.`},
        {t:`Tell the integrations team to just avoid opening those files while Copilot is on.`, s:0, d:{trust:-1,conf:-4,health:-5},
          after:`Ken reads the message twice and replies with a single word. "No."`,
          why:`A request to remember isn't a control. Copilot can use open files and nearby code as context. Exclusions are the control built for this.`},
        {t:`Set exclusions, but grant seats now and let Ken add the repos when he finds them.`, s:1, d:{trust:2,conf:0,health:-1},
          after:`Ken finds the last two repos on Wednesday. For five days they weren't excluded.`,
          why:`Right control, wrong order. Exclusions protect people from the moment access starts only if they're set before it does.`},
        {t:`Keep the integrations team off Copilot entirely, permanently, to be safe.`, s:0, d:{trust:-5,conf:1,health:-2},
          after:`The integrations team feels punished, and three of them sign up for personal Pro plans the next week.`,
          why:`Blanket bans push people around the fence. The safeguard is the control, not keeping a team out forever.`}
      ]},
    { id:`f1s8`, domain:`Copilot Features`, task:`F1`, title:`Nothing happens`,
      text:(s,all,G)=>[`Renata Vega had been at Halcyon three weeks. She was in wave one because she sat with the platform team, and on Monday she messaged Priya directly, which took courage for someone in her first month.`,`<span class="said" data-who="Renata">"Sorry if this is dumb. I installed the Copilot extension in VS Code and nothing happens. No suggestions. Is it me?"</span>`,`Priya remembered being three weeks in and afraid to ask anything.`],
      opts:[
        {t:`Check which GitHub account she's signed into, since the seat is on her work account.`, s:3, best:true, d:{trust:4,conf:1,health:3},
          after:`She's signed in with the personal account she made in college. Two minutes later suggestions are appearing. Priya adds "check which account you're signed into" to the top of the setup guide, and thanks Renata in the channel for finding it.`,
          why:`To use Copilot in the IDE you install the extension and sign in with the account that holds the seat. Wrong account, no Copilot. Check the simple thing first, and make it safe for new people to ask.`},
        {t:`Have her reinstall VS Code and the extension from scratch to rule out a bad install.`, s:0, d:{trust:0,conf:0,health:-2},
          after:`An hour later, reinstalled, signed into the same personal account, nothing still happens.`,
          why:`Reinstalling feels thorough and skips the likely cause. Check the sign in and the seat before you rebuild anything.`},
        {t:`Confirm on the Access page that she has a seat, then have her restart the editor.`, s:1, d:{trust:2,conf:0,health:1},
          after:`She does have a seat. The restart doesn't help, because the editor is still signed into the wrong account.`,
          why:`Confirming the seat is half the check. The other half is whether the editor is signed into the account that holds it.`},
        {t:`Tell her it's probably a rollout issue and to wait for the next wave.`, s:0, d:{trust:-4,conf:-1,health:-1},
          after:`Renata waits a week and doesn't ask anything again for a while.`,
          why:`Guessing costs her a week and teaches a new engineer that asking doesn't help. Find the cause.`}
      ]},
    { id:`f1s9`, domain:`Developer Productivity`, task:`V1`, title:`Theo's Terraform`,
      text:(s,all,G)=>[`Theo hadn't installed it. He'd made that clear in two meetings and one very long Slack thread. People were starting to quote him, and Priya could feel the rollout bending around his doubt.`,`It was hard to be the one leading Theo. He had shown her where everything lived, back when she was the quietest person on the team. She still had a runbook with "ask Theo" written in the margins in her own handwriting.`],
      opts:[
        {t:`Ask Theo privately to try Chat on his own Terraform and tell her honestly what it gets wrong.`, s:3, best:true, d:{trust:6,conf:2,health:2},
          after:`He opens the module he wrote three years ago and asks Copilot Chat to explain it. It gets most of it right and one thing wrong, a lifecycle rule it describes backwards. Theo is delighted to find the mistake. He's also a little annoyed at how good the rest was. <span class="said" data-who="Theo">"Fine. It's a decent junior. A junior I have to check."</span> That sentence does more for the rollout than any email could.`,
          why:`Copilot Chat can explain existing code, which speeds up learning and cuts context switching. Inviting a skeptic to test it on what he knows best turns resistance into an honest evaluation, and his review becomes the team's standard.`},
        {t:`Tell Theo that Elena's email applies to contractors too, and he needs to start this week.`, s:0, d:{trust:-7,conf:1,health:-1},
          after:`Theo installs it and never opens it. His next thread is about mandates.`,
          why:`Authority gets you compliance, not adoption. You need his real judgment, and an order shuts it off.`},
        {t:`Leave Theo alone and focus on the engineers who are already excited.`, s:1, d:{trust:0,conf:1,health:0},
          after:`The excited engineers adopt it quickly. Theo's doubt keeps spreading in the quiet places where people decide what to believe.`,
          why:`Starting with willing adopters is sensible. Ignoring the most respected skeptic leaves his doubts as the story everyone else hears.`},
        {t:`Ask Devin to show Theo how much faster he ships with it now.`, s:0, d:{trust:-3,conf:0,health:-1},
          after:`It goes about as well as you'd expect. Theo asks Devin what he checked before shipping. Devin doesn't have a good answer.`,
          why:`Speed without review is exactly what Theo distrusts. Show him quality on code he knows, not speed on code he doesn't.`}
      ]},
    { id:`f1s10`, domain:`Copilot Features`, task:`F4`, title:`Nora's question`,
      text:(s,all,G)=>[`Nora Kim booked thirty minutes, which for Nora meant she had five questions and would ask all of them.`,`<span class="said" data-who="Nora">"The SOC 2 auditors will ask who has Copilot, when they got it, and what the settings were. Can we prove that? And can we see what people typed into it?"</span>`],
      opts:[
        {t:`Tell her the audit log shows seats and policy changes, but not prompts, and plan for 180 days.`, s:3, best:true, d:{trust:3,conf:5,health:3},
          after:`Nora writes it all down. Seat grants and removals, plan and policy changes, all in the audit log for 180 days, so they'll stream it to the security team's log store for the full audit period. Prompts from editors aren't in it. <span class="said" data-who="Nora">"Good. I'd rather know what we can't show than find out in the room."</span>`,
          why:`The audit log records Copilot settings, policy changes, and seat changes. It doesn't include the prompts people send from their editors. Know the retention too, and plan for evidence that has to outlast it.`},
        {t:`Tell her the audit log captures everything, including every prompt and suggestion.`, s:0, d:{trust:0,conf:-6,health:-2},
          after:`Nora puts it in the audit plan. In March an auditor asks for a sample of prompts. There aren't any.`,
          why:`Promising evidence you don't have is worse than having none. The audit log doesn't include editor prompts.`},
        {t:`Export the seat list from the Access page each month and give that to the auditors.`, s:1, d:{trust:1,conf:2,health:1},
          after:`It shows who has a seat today. It doesn't show when policies changed or who removed whom.`,
          why:`A seat list is a snapshot. The audit log gives you the history the auditors want.`},
        {t:`Suggest a monthly self attestation where engineers confirm they used Copilot properly.`, s:0, d:{trust:-2,conf:-2,health:0},
          after:`Ninety people click "I agree." Nora is unimpressed.`,
          why:`Attestations don't replace system records. Use the audit log for what it can show and be honest about what it can't.`}
      ]},
    { id:`f1s11`, domain:`Responsible AI`, task:`R1`, title:`The quota`,
      text:(s,all,G)=>[`On Friday Elena called Priya directly, which had never happened before.`,`<span class="said" data-who="Elena">"Love the progress. One idea. Let's track acceptance rates per engineer and set a target. If we're paying for it, people should be using it."</span>`,`Priya thought about Devin shipping code he hadn't read. She thought about Renata, who'd be afraid of a number with her name on it.`],
      opts:[
        {t:`Track team adoption and outcomes like defects, not per person acceptance.`, s:3, best:true, d:{trust:4,conf:3,health:4},
          after:`Elena pushes back for exactly one minute, then asks what outcomes Priya would report. Priya has three. Elena likes the third one best, the one about escaped defects. <span class="said" data-who="Elena">"Fine. Show me those in a month."</span>`,
          why:`A per person acceptance target rewards accepting suggestions, not good code. That pushes people toward overreliance, one of the main harms of generative AI. Measure outcomes and team adoption, and keep humans accountable for what they accept.`},
        {t:`Agree, and set the target at a 30 percent acceptance rate for every engineer.`, s:0, d:{trust:-6,conf:3,health:-6},
          after:`Acceptance rates climb fast. So does the number of pull requests that need a second fix.`,
          why:`When you reward acceptance, people accept. Some of what they accept is wrong, and a quota tells them not to look too hard.`},
        {t:`Track per person usage privately, and only discuss it with people who are below average.`, s:1, d:{trust:-3,conf:2,health:-1},
          after:`It leaks within a week. People start opening chat windows just to show activity.`,
          why:`Softer than a quota, but it's still pressure on a number that doesn't measure quality.`},
        {t:`Tell Elena metrics aren't possible yet and ask her to wait until the end of the quarter.`, s:0, d:{trust:1,conf:-5,health:0},
          after:`Elena hears "no" and sets the target herself.`,
          why:`Saying no without an alternative hands the decision back. Offer the better measure.`}
      ]}
  ],
  exercise: { after:`f1s3`, title:`Which plan fits?`, intro:`Plans come up on the exam as short scenarios. Pick the plan that fits each one.`,
    items:[
      {prompt:`A company wants one place to grant seats and set Copilot policies for all its developers. It isn't on GitHub Enterprise Cloud.`, choices:[`Copilot Pro`,`Copilot Business`,`Copilot Enterprise`,`Copilot Free`], answer:1, why:`Business adds central seat management and policy control for an organization.`},
      {prompt:`A verified student wants Copilot at no cost.`, choices:[`Copilot Student`,`Copilot Pro+`,`Copilot Business`,`Copilot Max`], answer:0, why:`Copilot Student is free for verified students.`},
      {prompt:`An organization on GitHub Enterprise Cloud wants enterprise grade capabilities and a larger usage pool.`, choices:[`Copilot Business`,`Copilot Max`,`Copilot Enterprise`,`Copilot Pro`], answer:2, why:`Enterprise includes everything in Business plus enterprise grade capabilities, for GitHub Enterprise Cloud.`},
      {prompt:`A freelancer wants to try Copilot before paying anything.`, choices:[`Copilot Business`,`Copilot Enterprise`,`Copilot Pro+`,`Copilot Free`], answer:3, why:`Free is for trying Copilot at no cost, with limits.`},
      {prompt:`A company runs GitHub Enterprise Server in its own data center and wants Copilot for it.`, choices:[`Copilot Enterprise, installed on the server`,`None. Copilot isn't available for Server`,`Copilot Business with a server license`,`Copilot Pro for each of its developers`], answer:1, why:`GitHub's docs say Copilot isn't available for GitHub Enterprise Server.`},
      {prompt:`An individual developer uses Copilot heavily all day and wants the largest individual usage allowance.`, choices:[`Copilot Pro`,`Copilot Free`,`Copilot Max`,`Copilot Student`], answer:2, why:`Max is the individual plan with the largest allowance.`}
    ]},
  quiz: [
    {q:`An organization wants to apply the same Copilot policies to every developer who uses Copilot on company code. Several developers currently use personal Copilot Pro plans. What should the organization do?`, opts:[`Ask the developers to match the org settings by hand`,`Grant them org seats and move them off personal plans`,`Apply the organization policies to their personal plans`,`Require a monthly attestation from each developer`], a:1, why:`Organization policies apply to seats the organization grants. Personal plans are managed by the individual, so the fix is moving those developers onto organization seats.`, task:`F4`, domain:`Copilot Features`, level:`AP`},
    {q:`Which of these is NOT an environment where you install a GitHub Copilot extension?`, opts:[`Visual Studio Code`,`JetBrains IDEs`,`GitHub.com`,`Neovim`], a:2, why:`GitHub.com isn't an IDE. Copilot features on GitHub.com are part of the site. The others are supported editors with Copilot extensions.`, task:`F1`, domain:`Copilot Features`, level:`RE`},
    {q:`A developer installs the Copilot extension in VS Code but gets no suggestions. The organization confirms the developer has a seat. What should the developer check first?`, opts:[`Whether a newer VS Code version exists`,`Whether the repository is public or private`,`Whether the org has content exclusions on`,`Which GitHub account the editor is signed into`], a:3, why:`Copilot in the IDE needs the extension and a sign in with the account that holds the seat. Signing in with a different account is a common cause.`, task:`F1`, domain:`Copilot Features`, level:`AP`},
    {q:`An enterprise owner disables a Copilot feature for all organizations in the enterprise. An organization owner wants it on. What happens?`, opts:[`The organization owner can't override it`,`The organization setting wins for that org`,`The most recent change wins`,`Members choose in their own settings`], a:0, why:`Enterprise policies take precedence. When the enterprise sets a policy, the organization can't override it.`, task:`F4`, domain:`Copilot Features`, level:`RE`},
    {q:`A compliance lead asks whether the organization audit log shows the prompts developers send to Copilot from their editors. What's the correct answer?`, opts:[`Yes, for 90 days`,`Yes, but only for Copilot Enterprise`,`No, it records settings and seat changes`,`Only when content exclusions are on`], a:2, why:`The audit log records Copilot plan and policy changes and seat changes. It doesn't include client session data such as editor prompts.`, task:`F4`, domain:`Copilot Features`, level:`RE`},
    {q:`An organization grants a Copilot seat to a new member on the 10th of the month. When does billing for that seat begin?`, opts:[`When the member first uses Copilot`,`When the seat is granted`,`At the start of the next month`,`After a 30 day trial period`], a:1, why:`Billing starts when access is granted, prorated for the rest of the cycle, not when someone first uses it.`, task:`F4`, domain:`Copilot Features`, level:`RE`},
    {q:`An organization wants to roll out Copilot to a few teams first, then expand. Which option on the Access page fits?`, opts:[`Purchase for all members`,`Enable it for each repository`,`Have each developer buy Copilot Pro`,`Purchase for selected members`], a:3, why:`Selected members lets an owner grant seats to chosen teams or users. All members covers everyone, current and future.`, task:`F4`, domain:`Copilot Features`, level:`AP`},
    {q:`Which plan is required for an organization that wants enterprise grade Copilot capabilities on GitHub Enterprise Cloud?`, opts:[`Copilot Enterprise`,`GitHub Copilot Pro+`,`Copilot Business`,`GitHub Copilot Max`], a:0, why:`Copilot Enterprise is for organizations on GitHub Enterprise Cloud and includes everything in Business plus enterprise grade capabilities.`, task:`F4`, domain:`Copilot Features`, level:`RE`},
    {q:`A developer says, "Copilot wrote it, so it's probably right," and ships without review. Which principle does this violate most directly?`, opts:[`Copilot only works on public code`,`AI output must be validated by a human`,`Suggestions are all public code matches`,`Copilot can't generate business logic`], a:1, why:`Generative AI can be confidently wrong. Responsible use means a human reviews, understands, and tests what they accept.`, task:`R1`, domain:`Responsible AI`, level:`AP`},
    {q:`Copilot suggests a call to a library function that doesn't exist. What is this an example of?`, opts:[`A content exclusion`,`A public code match`,`A hallucination`,`A policy conflict`], a:2, why:`A hallucination is confident output that's wrong, such as an API or function that doesn't exist.`, task:`R1`, domain:`Responsible AI`, level:`RE`},
    {q:`Leadership wants to set a per developer target for the share of Copilot suggestions accepted. What is the main risk?`, opts:[`It rewards accepting output nobody validated`,`It uses more AI credits than the plan allows`,`It turns off the duplicate detection filter`,`It hides Copilot activity from the audit log`], a:0, why:`Rewarding acceptance encourages overreliance. Measure outcomes and keep people accountable for what they accept.`, task:`R1`, domain:`Responsible AI`, level:`AN`},
    {q:`A security lead wants to keep certain repositories from being used as Copilot context for developers with organization seats. What should the organization use?`, opts:[`A repository ruleset`,`A personal plan setting`,`An audit log filter`,`Content exclusions`], a:3, why:`Content exclusions keep chosen files and repositories from being used as context and from getting inline suggestions, for people with seats from the organization.`, task:`S1`, domain:`Privacy and Safeguards`, level:`AP`},
    {q:`A developer wants Copilot Chat to explain an unfamiliar module before changing it. Which benefit is this?`, opts:[`Skipping the code review on that module`,`Faster learning, less context switching`,`Removing the need for unit tests later`,`Getting around the content exclusions`], a:1, why:`Explaining existing code helps developers learn faster and stay in the editor, without replacing review or tests.`, task:`V1`, domain:`Developer Productivity`, level:`AP`},
    {q:`What does Copilot use to build the prompt for a suggestion in the editor?`, opts:[`Only the single line where the cursor sits now`,`All the code in every repository in the org`,`Your input plus editor context, like open files`,`Only code pulled from public repositories`], a:2, why:`Copilot builds a prompt from what you typed plus editor context, such as the current file, nearby code, and other open files.`, task:`P1`, domain:`Prompt Engineering`, level:`RE`},
    {q:`After the prompt leaves the editor, what happens before a response reaches the developer?`, opts:[`It returns to the editor without changes`,`A GitHub staff member reviews it first`,`It's written to the audit log first`,`Filters on the way in and on the way back`], a:3, why:`The prompt goes to the Copilot service through filters, and the response is filtered again before it's returned.`, task:`D1`, domain:`Data and Architecture`, level:`RE`}
  ],
  closing:(s,all,G)=>[
    ((s.flags.personalseats||G.personalseats)
      ?`By Friday night the dashboard said fifty eight seats. It didn't say that twenty six other people were still on plans nobody at Halcyon could see. Priya knew. She left it off the slide and felt it sitting there anyway, like a warning light she'd put tape over.`
      :`By Friday night the dashboard said fifty eight seats, every one of them on the organization plan. Wave two was scheduled. Ken's exclusions were in. Nora had a page of evidence with dates on it. It wasn't ninety yet. It was real.`),
    `She drove to Aurora on Sunday for dinner, the way she did most weeks. Her father had been a machinist for thirty one years. He could tell you the tolerance on a part by the sound it made in the lathe. He asked about work while he served the dal.`,
    `<span class="said" data-who="man">"So the computer writes the code now?"</span> he said. <span class="said" data-who="man">"Then what do they pay you for?"</span>`,
    `<span class="said" data-who="Priya">"To check it,"</span> she said, and realized it was the truest thing she'd said all week. <span class="said" data-who="Priya">"And to decide what it's allowed to touch."</span>`,
    `He thought about that. <span class="said" data-who="man">"When they put the first CNC machines in the shop, the young guys trusted them completely. The old guys didn't trust them at all. Both kinds scrapped a lot of parts."</span> He passed her the rice. <span class="said" data-who="man">"The ones who did well measured everything."</span>`,
    (s.score>=26
      ?`Driving home she thought about Theo calling Copilot a decent junior, and Renata finding the setup bug, and Elena saying "show me in a month." For years she had been the person who asked Theo. This week, for the first time, Theo had asked her a question back: how she wanted the reviews done. She didn't know what to do with that yet.`
      :`Driving home she replayed the week and kept landing on the same thought. She had made some calls fast to keep people happy, and she wasn't sure the fences were where they needed to be. Sam would ask her what she'd do differently. She wanted to have an answer before he did.`),
    `At 2:14 in the morning her phone lit up on the nightstand. Tomasz, from Kraków, where it was already mid morning. <span class="said" data-who="Tomasz">"We assigned the logging issue to Copilot on GitHub, like the docs say. Then we waited in our IDE for it to start working. Nothing. Where did it go?"</span>`,
    `Priya stared at the message. She realized she didn't know, either.`
  ],
  episode:{src:`audio/full-ch01.mp3`, len:`about 35 minutes`},
  next:`Two Kinds of Agent`
});
