// Chapter 1. Schema: see README (num, title, opening[], scenes[], closing(s), videos{}, deeper[], episode{}).
(window.HALCYON=window.HALCYON||[]).push(Object.assign({
 num:1, title:"The Promotion",
 opening:[
  "The email came in at 6:12 on a Monday morning, which was how Sam Okafor knew it was bad news. Nobody at Halcyon AI sent good news before seven.",
  "Halcyon had six hundred people, a Series C, and one deal that mattered more than all the others combined. Cascade Valley Health, a network of eleven hospitals across Colorado and Wyoming, had signed a contract to put Halcyon's AI agents into its clinical documentation workflow. Go-live was fourteen weeks out. The date was in the contract. Grant Mercer, the Chief Revenue Officer, had rung a bell in the office when it closed.",
  "On Friday the project manager running Cascade had quit. No exit interview, no handoff, just a two-line email and an empty desk.",
  "By 8:30 Sam was in Elena Vasquez's office. The CEO didn't sit down. <span class=\"said\">\"You've run our data centers for three years and I have never once had to think about them. That's what I need on Cascade. You start today.\"</span>",
  "Sam had never run a software project. He'd kept F-16s flying and kept racks humming. He said that. Elena said she knew. Then she said, <span class=\"said\">\"Ruth Calder is on our board. She ran launches at NASA for twenty years. I've asked her to check in with you.\"</span>",
  "Sam walked back to his desk with a project that wasn't his, a team that didn't know him, and fourteen weeks."
 ],
 scenes:[
 {id:"c1s1", domain:"Process", task:"Assess before acting",
  text:s=>["It's 9:15. Sam has a calendar full of meetings the last PM left behind, a shared drive with forty folders, and a Slack channel with three hundred unread messages. Elena wants an update by Friday.","What does Sam do first?"],
  opts:[
   {t:"Rebuild the schedule from scratch this week so it reflects what's really happening.",s:1,d:{trust:-2,conf:0,health:2},
    after:"Sam spends two days in a spreadsheet. The schedule looks clean. Nobody on the team was asked a single question, and on Wednesday two engineers point out dependencies he couldn't have known about.",
    why:"A new plan is coming, but not yet. You can't re-plan what you don't understand, and the people who know the real state of the work haven't been heard. On the exam, building something before gathering information is almost always the wrong first move."},
   {t:"Call an all-hands, introduce himself as the new lead, and set how work will run now.",s:0,d:{trust:-6,conf:1,health:0},
    after:"Sam stands up in front of forty people and lays out how things will run now. The room is polite. The Slack channel goes quiet for the rest of the day, which is worse than complaints.",
    why:"Authority from a title is the weakest kind you have. The team just lost their PM and is waiting to see who you are. Announcing control before you've listened tells them exactly that. PMI wants servant leadership: earn it by understanding them first."},
   {t:"Read the key documents, then meet each lead one on one to learn the real status.",s:3,d:{trust:6,conf:1,health:3},best:true,
    after:"Sam reads the contract, the statement of work, and whatever passes for a plan. Then he sits down with each lead for thirty minutes and mostly listens. By Wednesday he has a page of notes that doesn't match the status reports at all.",
    why:"This is the PMI pattern: assess before you act. Review what exists, talk to the people closest to the work, and form your own picture. On a project you inherit, discovery is the first deliverable. The exam rewards the answer that gathers information before deciding."},
   {t:"Tell Elena right away that fourteen weeks can't be done, before expectations harden.",s:0,d:{trust:0,conf:-6,health:0},
    after:"Elena's jaw tightens. <span class=\"said\">\"Based on what?\"</span> Sam doesn't have an answer, and now the CEO thinks her new project lead is a pessimist.",
    why:"Maybe it is impossible. You don't know yet, and neither does anyone you'd tell. Escalating without data costs you credibility you'll need later. Bring evidence and options, not a gut feeling."}
  ]},
 {id:"c1s2", domain:"Business Environment", task:"Project charter and authority",
  text:s=>["In the shared drive Sam finds a signed contract and a statement of work written by the sales team. He does not find a project charter. Nothing says who the sponsor is, what Sam is authorized to decide, or what success looks like beyond the go-live date.","Lena Cho, the CTO, shrugs when he asks. <span class=\"said\">\"We've never really done charters. Grant's contract is the charter.\"</span>"],
  opts:[
   {t:"Treat the signed contract as the charter, since it's legally binding on both sides.",s:0,d:{trust:0,conf:-2,health:-3},
    after:"The contract tells Sam what Halcyon owes Cascade. It doesn't tell anyone inside Halcyon that Sam can pull an engineer off another project. The first time he tries, the other manager says no and nobody overrules him.",
    why:"A contract defines obligations to the customer. A charter formally authorizes the project inside your own company and names the PM's authority. Without one, every resource request turns into a negotiation."},
   {t:"Draft a short charter naming Elena as sponsor and his authority, and get it signed.",s:3,d:{trust:2,conf:4,health:4},best:true,
    after:"It's two pages. Elena reads it, changes one line about budget authority, and signs it Thursday. When Sam needs Theo's time later in the week, he points to page one and the conversation takes five minutes.",
    why:"The charter is issued by the sponsor and it formally authorizes the project and the PM. Even on a project already in motion, creating one is right: it fixes who decides, what success means, and where your authority comes from."},
   {t:"Skip the charter for now and put every hour into delivery, since the date is tight.",s:0,d:{trust:0,conf:-1,health:-4},
    after:"Sam saves a day. Over the next three weeks he loses far more than that to arguments about who owns what.",
    why:"The exam treats 'skip the process, there's no time' as a trap. Lightweight is fine, and tailoring is good. Having no authorization and no agreed success measures isn't tailoring, it's risk."},
   {t:"Ask Lena to write the charter, since engineering owns most of the work and people.",s:1,d:{trust:0,conf:0,health:1},
    after:"Lena agrees, then doesn't do it. Two weeks later it's still on her list.",
    why:"Close, but the charter comes from the sponsor, usually with the PM drafting it. The CTO isn't the sponsor here, and handing it off leaves your authority undefined. Draft it yourself and get the sponsor to sign."}
  ]},
 {id:"c1s3", domain:"People", task:"Remove impediments and protect capacity",
  text:s=>[(s.flags.allhands?"The team is still guarded after Monday's all-hands, but people answer when Sam asks direct questions. ":"")+"Every thread Sam pulls leads back to the same name. Theo Lindqvist, the ML platform lead, is assigned to eleven of the fourteen critical tasks. He's also the only person who can deploy model updates, and he answers support questions for three other customers.","At standup Theo says he's fine. He looks like he hasn't slept since Labor Day."],
  opts:[
   {t:"Ask Theo to cover weekends until go-live, with comp time and a bonus once it ships.",s:0,d:{trust:-5,conf:0,health:-2},
    after:"Theo says yes. He'd say yes to anything. His error rate climbs and in week three a bad deploy takes the demo environment down for a day.",
    why:"Adding hours to the bottleneck makes the bottleneck worse. This is Brent from The Phoenix Project. The PMI answer protects the constraint, reduces the work flowing through it, and spreads the knowledge."},
   {t:"Route Theo's requests through Sam, cut his open work, and pair Priya with him.",s:3,d:{trust:5,conf:1,health:6},best:true,
    after:"Theo's queue drops from nineteen items to six. A junior engineer, Priya, shadows him on every deploy and writes the runbook as she goes. Theo stops answering Slack at midnight.",
    why:"You protected the constraint, limited work in progress, and started knowledge transfer so one person stops being a single point of failure. Removing impediments and shielding the team from interruptions is core servant leadership."},
   {t:"Take Theo off the Cascade project for two weeks so he can recover from the load.",s:0,d:{trust:-1,conf:-2,health:-6},
    after:"Theo is relieved for about an hour, then three tasks stop moving because nobody else knows how they work.",
    why:"Pulling the only person who knows the system without a transition plan creates a crisis. The issue is overload and concentration, not Theo. Fix the flow of work to him, don't remove him."},
   {t:"Escalate to Lena, as Theo's manager, and ask her to rebalance his workload now.",s:1,d:{trust:0,conf:0,health:1},
    after:"Lena promises to look at it. She talks to Theo, who tells her he's fine.",
    why:"Escalation is sometimes right, but this is in Sam's lane. The exam usually wants the PM to act on what they can control first, then escalate what they can't."}
  ]},
 {id:"c1s4", domain:"Business Environment", task:"Manage scope and change",
  text:s=>["Thursday afternoon Sam joins Grant on a call with Cascade's project team. It's friendly until Cascade's nursing director asks whether the agents can also draft patient discharge instructions.","Grant doesn't hesitate. <span class=\"said\">\"Absolutely, we can make that happen for go-live.\"</span>","Sam has read the statement of work twice. Discharge instructions aren't in it, and nobody has estimated them."],
  opts:[
   {t:"Correct Grant politely on the call so Cascade doesn't leave with the wrong idea.",s:1,d:{trust:0,conf:-5,health:1},
    after:"The call goes cold. Grant smiles through it and doesn't speak to Sam for two days.",
    why:"Your instinct is right but the method costs you. Contradicting a senior colleague in front of the customer damages the relationship you need. Handle it privately, then fix the commitment through the proper process."},
   {t:"Say nothing, then add discharge instructions to the backlog to keep Cascade happy.",s:0,d:{trust:-2,conf:1,health:-6},
    after:"Three engineers quietly start on discharge instructions. Two planned features slip and nobody decided that they should.",
    why:"That's scope creep: new work added with no analysis and no decision. Sooner or later someone pays, usually the schedule. Every change needs an impact assessment and an approval."},
   {t:"Let it pass on the call, then raise it with Grant privately and log a change request.",s:3,d:{trust:2,conf:3,health:4},best:true,
    after:"After the call Sam walks Grant through the statement of work. Grant pushes back, then agrees to a change request. The impact analysis says six weeks of work. Cascade gets a formal answer: discharge instructions in a phase two, with a price.",
    why:"Protect the relationship in public, address the issue in private, then use the change control process. Analyze the impact before any approval. That's the textbook sequence the exam expects."},
   {t:"Email Elena after the call that Grant is promising work the contract doesn't cover.",s:0,d:{trust:-2,conf:-2,health:0},
    after:"Elena forwards the email to Grant. Now Sam has an enemy in the C-suite in his first week.",
    why:"Going over someone's head before talking to them breaks trust, and it skips the change process entirely. Talk to the person first."}
  ]},
 {id:"c1s5", domain:"People", task:"Build trust and healthy conflict",
  text:s=>["Friday's planning meeting has eight people around the table. Sam proposes a sequence for the next three sprints and asks for concerns. Silence. Lena nods. Theo stares at his laptop.","Two hours later, in the kitchen, Sam overhears two engineers saying the sequence is backwards and the integration work should come first."],
  opts:[
   {t:"Find the two engineers and ask why they didn't raise the concern in the meeting.",s:1,d:{trust:-1,conf:0,health:1},
    after:"They apologize and say they didn't want to cause trouble. Sam gets their input. Next meeting, the room is just as quiet.",
    why:"You got this decision right but didn't fix the pattern. The real problem is that the team doesn't feel safe disagreeing out loud. That's Lencioni's fear of conflict, and it needs a team-level fix."},
   {t:"Set ground rules with the team, then ask them directly to poke holes in his plan.",s:3,d:{trust:7,conf:0,health:3},best:true,
    after:"It feels awkward. Sam starts the next meeting by saying, <span class=\"said\">\"I've never run a software release. Tell me where this plan is wrong.\"</span> After a long pause, one of the kitchen engineers does. The plan gets better and the meeting runs over.",
    why:"Creating a team charter with working agreements, and showing vulnerability as the leader, builds the trust that makes productive conflict possible. Five Dysfunctions starts with trust; PMI calls it psychological safety."},
   {t:"Keep the plan as agreed, since everyone had a fair chance to object in the room.",s:0,d:{trust:-4,conf:0,health:-4},
    after:"The team executes the plan they think is wrong. In sprint two the integration problem the engineers predicted shows up right on schedule.",
    why:"Silence isn't agreement. A leader who knows there are unspoken objections and moves ahead anyway gets compliance, not commitment."},
   {t:"Ask Lena to remind her engineers that they're expected to speak up in planning.",s:0,d:{trust:-1,conf:0,health:0},
    after:"Lena sends a Slack message encouraging open discussion. It changes nothing.",
    why:"You can't order people into feeling safe, and handing it to a conflict-averse CTO makes it worse. The PM shapes the team's working environment directly."}
  ]},
 {id:"c1s6", domain:"Process", task:"Tailor the approach",
  text:s=>["Sam maps the work. Half of it is physical: a new GPU cluster at the IronPeak colocation site, network links to Cascade's data center, and a fixed install window IronPeak won't move. The other half is software. The agent and integration teams run two-week sprints and their scope changes every time Cascade's clinicians try a demo.","Lena wants everything agile. The IronPeak contract manager wants a dated plan with no surprises."],
  opts:[
   {t:"Run all the work in two-week sprints, hardware included, so there's one rhythm.",s:0,d:{trust:-1,conf:-2,health:-4},
    after:"The infrastructure team tries to fit a ninety-day hardware lead time into a sprint backlog. IronPeak asks for a schedule and gets a burndown chart.",
    why:"Agile fits work where the requirements are uncertain and change is cheap. Hardware with long lead times and fixed install windows needs a plan-driven approach. One method for everything ignores the nature of the work."},
   {t:"Put the whole project on one detailed waterfall schedule so dates are predictable.",s:0,d:{trust:-3,conf:1,health:-3},
    after:"The plan is beautiful for two weeks. Then Cascade's clinicians change three requirements after a demo and the plan is fiction.",
    why:"The software requirements really are changing, so locking them into a predictive plan just means constant rework of the plan. Match the approach to each part of the work."},
   {t:"Use a hybrid: a fixed plan for the cluster, sprints for software, shared milestones.",s:3,d:{trust:3,conf:3,health:6},best:true,
    after:"Sam builds a milestone plan with the IronPeak dates fixed and the software sprints lined up beneath them. Integration testing is set for the week after the cluster is commissioned. Lena and the IronPeak manager both get what they need.",
    why:"Tailoring the life cycle to the work is a big theme on the current exam. Predictive where scope is fixed, adaptive where it's changing, with integration points that let both sides plan around each other."},
   {t:"Let each team pick its own method and coordinate through a weekly sync meeting.",s:1,d:{trust:2,conf:-1,health:-2},
    after:"The teams are happy. Nobody can say whether the software will be ready when the cluster is.",
    why:"Team autonomy is good, but the project needs one integrated view of milestones and dependencies. Tailoring is deliberate; no plan isn't tailoring."}
  ]},
 {id:"c1s7", domain:"Process", task:"Manage vendors and contracts",
  text:s=>["LabelForge, the vendor labeling twenty thousand clinical notes to train and test the agents, was due to deliver the first batch last Tuesday. It hasn't arrived. Their account manager says they had \"onboarding challenges\" with their annotator team.","The contract is fixed price, with delivery dates and a clause for late delivery."],
  opts:[
   {t:"Terminate LabelForge for the missed delivery and start onboarding a backup vendor.",s:0,d:{trust:0,conf:-2,health:-6},
    after:"Procurement tells Sam a new vendor would take six weeks to onboard and needs a new security review. The delay just got worse.",
    why:"Termination is a last resort. It's expensive and slow, and you don't even know the cause yet. Understand the problem and use the contract's remedies first."},
   {t:"Meet LabelForge to find the cause, ask for a recovery plan, and document it all.",s:3,d:{trust:1,conf:2,health:4},best:true,
    after:"The meeting reveals LabelForge lost its two clinical annotation leads. Their recovery plan adds a nurse annotator team and delivers in three batches. Sam logs the delay in the risk register and keeps a written record in case the late delivery clause is needed.",
    why:"Find the root cause, work with the vendor on a recovery plan, and know your contract. Document it so contractual remedies are available if needed. That's collaborative vendor management with your rights protected."},
   {t:"Have Halcyon's engineers label the overdue batch themselves to protect the date.",s:0,d:{trust:-4,conf:0,health:-3},
    after:"Three engineers spend a week labeling clinical notes they aren't qualified to judge. The quality team rejects forty percent of them.",
    why:"Taking on a vendor's contracted work pulls your team off the critical path and may waive your rights under a fixed price contract. It also wasn't their skill set."},
   {t:"Send LabelForge a formal notice invoking the contract's late delivery clause today.",s:1,d:{trust:0,conf:0,health:1},
    after:"LabelForge's lawyers reply. The account manager stops returning calls.",
    why:"You may get there, but leading with legal notice before understanding the cause usually damages the relationship you need for recovery. Talk first, document as you go, escalate formally only if needed."}
  ]},
 {id:"c1s8", domain:"Business Environment", task:"Compliance requirements",
  text:s=>["Cascade's security office sends a forty-page questionnaire. They need a signed business associate agreement under HIPAA, Halcyon's SOC 2 report, and an explanation of how patient data is kept out of model training. Go-live depends on their sign-off.","Nobody at Halcyon owns this. Legal thinks security owns it. Security thinks sales handled it in the contract."],
  opts:[
   {t:"Forward the questionnaire to Halcyon's security team and ask them to handle it.",s:0,d:{trust:0,conf:-2,health:-4},
    after:"Security puts it in their queue behind three other questionnaires. Cascade follows up twice.",
    why:"Forwarding it isn't managing it. A requirement that gates go-live belongs in your project scope with an owner and a date."},
   {t:"Add it to scope and the risk register, name owners, and schedule it as a dependency.",s:3,d:{trust:1,conf:4,health:5},best:true,
    after:"Sam sets up a weekly thirty-minute check with security and legal. The business associate agreement is signed in week three. The training data question takes longer, so Sam tracks it as a risk and Elena knows about it.",
    why:"Compliance requirements are project requirements. Identify them, assign owners, schedule them, and track the risk. On the exam, compliance isn't someone else's problem when it affects your deliverables."},
   {t:"Ask Grant what he promised Cascade about security before deciding who handles it.",s:1,d:{trust:0,conf:0,health:1},
    after:"Grant says he told them Halcyon was \"enterprise ready.\" Helpful context, but nobody owns the work yet.",
    why:"Understanding past commitments is useful, but it's a first step, not the answer. Somebody has to own and schedule the work."},
   {t:"Tell Cascade that Halcyon's standard terms already cover their security needs.",s:0,d:{trust:0,conf:-6,health:-2},
    after:"Cascade's CISO replies that standard terms don't include a business associate agreement, which is required by law. The relationship takes a hit.",
    why:"Regulations aren't negotiable and the customer's compliance team knows it. Guessing at compliance answers is a fast way to lose trust."}
  ]},
 {id:"c1s9", domain:"People", task:"Stakeholder engagement",
  text:s=>["Ruth Calder calls on Thursday evening. <span class=\"said\">\"Have you talked to Raymond Ochoa yet?\"</span>","Sam hasn't. Ochoa is Cascade's CIO. He signed the deal. According to his assistant, nobody from Halcyon has spoken to him in three weeks, and he's started asking his team whether Halcyon is in trouble."],
  opts:[
   {t:"Hold off on contacting Ochoa until there's real progress and good news to share.",s:0,d:{trust:0,conf:-6,health:0},
    after:"Ochoa calls Elena directly on Monday. Elena calls Sam. It isn't a good call.",
    why:"Silence lets stakeholders fill the gap with their worst guess. Proactive, honest communication, especially when things are uncertain, is what keeps engagement high."},
   {t:"Call Ochoa, give an honest status with the risks, and agree how they'll talk.",s:3,d:{trust:1,conf:7,health:1},best:true,
    after:"The call runs forty minutes. Ochoa appreciates that Sam named the LabelForge delay before he had to ask. They agree on a weekly fifteen-minute call and a one-page status every Friday. Ochoa ends with, <span class=\"said\">\"This is the first time I've felt like I know what's going on.\"</span>",
    why:"Engage key stakeholders early and directly, be transparent about risks, and agree on a communication plan that fits them. That's stakeholder engagement and a communications plan in one move."},
   {t:"Send Ochoa a detailed status email with the full project plan and risk log attached.",s:1,d:{trust:0,conf:2,health:0},
    after:"Ochoa's assistant replies that he'll review it. He doesn't.",
    why:"Information sent isn't communication received. A senior stakeholder who is anxious needs a conversation, and you need to learn what they actually want to hear."},
   {t:"Ask Grant to call Ochoa, since Grant owns the relationship and closed the deal.",s:1,d:{trust:0,conf:1,health:0},
    after:"Grant calls Ochoa and tells him everything is on track. That's not quite true.",
    why:"The account owner should stay involved, but Sam is now responsible for delivery and the customer needs to hear from the person accountable for it."}
  ]},
 {id:"c1s10", domain:"Business Environment", task:"Communicate forecasts to the sponsor",
  text:s=>["Friday, 4 PM. Elena's office again. <span class=\"said\">\"So. Will we hit the date?\"</span>","Sam has a week of real data now. With the LabelForge delay, the security review, and the integration work moving to the front, his forecast says eighteen weeks, not fourteen. There are ways to close the gap. None of them are free."],
  opts:[
   {t:"Say yes. It's week one, the team needs confidence, and there's time to recover.",s:0,d:{trust:-2,conf:-8,health:-4},
    after:"Elena smiles and tells the board on Tuesday that Cascade is on track. Sam spends the weekend unable to sleep.",
    why:"Telling the sponsor what they want to hear is the most expensive thing a PM can do. The gap doesn't close because you hid it; it just surfaces later, when there are fewer options."},
   {t:"Show the eighteen week forecast and its causes, give options, and let Elena decide.",s:3,d:{trust:2,conf:6,health:5},best:true,
    after:"Elena reads the page twice. She doesn't like it. Then she picks a phased release: the core documentation agents go live on the contract date with three hospitals, the rest follow over four weeks. <span class=\"said\">\"Get Grant in here,\"</span> she says. <span class=\"said\">\"He's going to hate this.\"</span>",
    why:"Give the sponsor an honest forecast based on data, explain the drivers, and bring options with their tradeoffs. The decision belongs to the sponsor. The PM's job is to make it an informed one."},
   {t:"Say no, the date can't be met, and recommend Elena tell Cascade it will slip.",s:1,d:{trust:0,conf:-2,health:2},
    after:"Elena asks if there's any other way. Sam realizes he should have led with options.",
    why:"Honest, but incomplete. Jumping to one recommendation skips the options a sponsor needs to weigh. Bring choices, not a verdict."},
   {t:"Ask for two more weeks of data before committing to any forecast at all.",s:0,d:{trust:0,conf:-4,health:-2},
    after:"Elena gives him one week, and tells him she expected more.",
    why:"You have enough data to forecast with stated uncertainty. Waiting for perfect information burns the time the sponsor needs to act. Share what you know now and how sure you are."}
  ]}
 ],
 closing:s=>[
  "Saturday morning Sam meets Ruth at a coffee shop in Golden. She has the one-page plan he gave Elena, with notes in the margins.",
  "<span class=\"said\">\"At NASA we had a saying,\"</span> she says. <span class=\"said\">\"Failure is not an option. Everybody quotes it. Nobody remembers that it only worked because the flight directors told the truth about the numbers every single day. The optimists didn't get people home. The honest ones did.\"</span>",
  (s.score>=24?"She taps the page. <span class=\"said\">\"You did that this week. Most people in your chair don't.\"</span>":"She taps the page. <span class=\"said\">\"You're learning. Next week, listen first and decide second. The team will tell you what's wrong if you let them.\"</span>"),
  "Sam's phone buzzes. It's Theo. <span class=\"said\">\"The IronPeak cluster failed its burn-in test. Half the GPUs. Can you call me?\"</span>",
  "Ruth finishes her coffee. <span class=\"said\">\"Chapter two,\"</span> she says, and stands up."
 ]
},{
 videos:{
 c1s1:["EHnKAgDyz1o","Master the PMP Exam Mindset: 9 Key Principles","PM Aspirant","11:46"],
 c1s2:["xvj0bbOfyTg","What is a Project Charter? Explained in 4 Minutes","Max Mao","4:39"],
 c1s3:["YASLijHmB54","Agile: Servant Leadership","David McLachlan","4:23"],
 c1s4:["_c-qzFV5yM4","Project Management Scope Creep: Manage It Like a Pro","Adriana Girdler","4:37"],
 c1s5:["75bO_XWk7fw","The Five Dysfunctions of a Team","Patrick Lencioni","6:08"],
 c1s6:["qf0Yzrzr_i4","Waterfall vs Agile vs Hybrid Approaches Explained","Alvin the PM","9:08"],
 c1s7:["JWI_wZeebO8","Types of Contracts: Key Concepts in Project Management","David McLachlan","6:31"],
 c1s8:["p5qTCI-alfw","PMP Exam Mindset: Confirm Project Compliance Requirements","Praizion","10:53"],
 c1s9:["5VrHeEfRceo","Stakeholder Engagement: Five-step Process","Mike Clayton","4:05"],
 c1s10:["qNEVrb1Bq-Q","When Your Projects Are Late","ProjectManager","4:17"]
},
 deeper:["-u0rO-YQr9c","Complete PMP Mindset: 50 Principles and Questions","Andrew Ramdayal","2:53:56"],
 episode:{src:"audio/ch1-the-promotion.mp3",len:"20 minutes"},
 next:"Burn-In"
}));
