// Chapter 2. Burn-In. Schema: see chapters/ARC.md.
(window.HALCYON=window.HALCYON||[]).push({
 num:2, title:"Burn-In",
 cast:[["Hal Brennan","Site operations manager at IronPeak, the GPU colocation vendor."],["Priya Shah","Junior engineer. Shadows Theo on deploys and writes the runbook."]],
 opening:[
  "Sam called Theo back from the parking lot of the coffee shop. Theo talked fast. The IronPeak cluster had run its seventy-two hour burn-in test overnight, the standard stress run before anyone trusts new hardware. Half the GPUs had thrown errors, shut down, or both.",
  "<span class=\"said\">\"It's not software,\"</span> Theo said. <span class=\"said\">\"I checked. It's the hardware.\"</span>",
  "IronPeak's colocation site sat in an industrial park east of the airport, a long gray building with no windows and a guard who checked IDs twice. Sam drove out Monday morning. He'd spent three years in rooms like this one. The air was cold and loud and smelled faintly of hot dust. For the first time since Elena's office, he felt like he knew what he was looking at.",
  "Hal Brennan, IronPeak's site operations manager, met him at the cage. Hal was friendly, tired, and already had a theory. <span class=\"said\">\"Bad batch of GPUs from the manufacturer,\"</span> he said. <span class=\"said\">\"Happens. We'll swap them out.\"</span>",
  "Sam looked at the dark half of the racks. Integration testing was supposed to start on this cluster in three weeks. Cascade's go-live depended on that date. Nobody had told Elena yet, and nobody had told Cascade."
 ],
 scenes:[
 {id:"c2s1", domain:"Process", task:"Log the issue",
  text:s=>["Back at the office, Sam opens the risk register the last PM left behind. Line fourteen reads: <i>Hardware defects found during commissioning could delay integration testing.</i> Probability medium, impact high. No owner. No response plan.","That risk isn't a risk anymore. It happened Sunday night."],
  opts:[
   {t:"Raise line fourteen's probability to high and keep watching it in the risk register.",s:0,d:{trust:0,conf:-1,health:-4},
    after:"The register now says the risk is very likely. It's also already true. Theo asks Sam what that changes. It changes nothing.",
    why:"A risk is something that might happen. Once it happens, it's an issue. Updating the probability on an event that already occurred is busywork. The exam wants you to recognize the shift and manage the issue."},
   {t:"Move it to the issue log with an owner and a date, and tell the people it affects.",s:3,d:{trust:2,conf:4,health:4},best:true,
    after:"Sam opens an issue log entry, names Theo as technical owner and himself as the owner of the fix plan, and sets a Wednesday date for a root cause answer. He tells Elena and Lena that afternoon, plainly, and adds it to Friday's note to Ochoa. Nobody is surprised later.",
    why:"A realized risk moves to the issue log with an owner, actions, and a date. Then you tell the people it affects, early. Stakeholders forgive problems. They don't forgive finding out late."},
   {t:"Order a full set of replacement GPUs today so no time is lost waiting on IronPeak.",s:0,d:{trust:0,conf:-2,health:-3},
    after:"Procurement says the order is $1.1 million and needs Elena's signature. Elena asks Sam why he's buying hardware before anyone knows what broke. He doesn't have an answer.",
    why:"Acting before you understand the problem is the classic trap. You might be replacing the wrong thing at full price. Log it, find the cause, then decide."},
   {t:"Tell Elena that go-live will slip and ask her to warn Cascade before Friday's call.",s:1,d:{trust:0,conf:-3,health:1},
    after:"Elena asks how long the slip will be. Sam doesn't know yet. She decides to wait until he does.",
    why:"Telling the sponsor fast is right. Predicting the outcome before you've assessed the impact isn't. Report the issue and what you're doing about it, and give the schedule impact once you actually know it."}
  ]},
 {id:"c2s2", domain:"People", task:"Find the root cause together",
  text:s=>["Tuesday's call with IronPeak goes sideways in four minutes. Hal says the GPUs are defective and the manufacturer will replace them in six weeks. Theo says IronPeak's install was sloppy. Hal says Halcyon's power spec was wrong. Theo unmutes to say something Sam is fairly sure he'll regret.","Six weeks would sink go-live."],
  opts:[
   {t:"Accept Hal's diagnosis and press the GPU maker to ship replacements in two weeks.",s:1,d:{trust:-1,conf:0,health:-1},
    after:"The manufacturer agrees to expedite. Sam feels good about it until Thursday, when two of the new test boards fail in the same racks as before.",
    why:"Pushing the vendor is reasonable, but you accepted a cause nobody had verified. Fixing a symptom without the root cause means it comes back."},
   {t:"Get both teams in the cage to work the problem with a fishbone and five whys.",s:3,d:{trust:5,conf:2,health:5},best:true,
    after:"Wednesday morning, Theo, Hal, and two IronPeak techs stand in front of a whiteboard in the cage. Why did the GPUs fail? Power faults. Why? The power distribution units were dropping voltage under load. Why? A bad batch of units, plus firmware that didn't match the GPU model. By noon the blame is gone and they have a list.",
    why:"Root cause analysis tools like a fishbone diagram and the five whys move people from blaming each other to solving the problem. Putting both sides on the same problem is also the collaborative conflict style the exam favors."},
   {t:"Mute the call, then tell Theo privately to stop blaming IronPeak and let Sam talk.",s:1,d:{trust:-3,conf:1,health:0},
    after:"Theo goes quiet for the rest of the call and the rest of the day. Hal relaxes. The actual problem is no closer to solved.",
    why:"Calming a heated moment has value, and talking to Theo privately beats doing it in public. But it doesn't find the cause, and silencing your best technical person costs you."},
   {t:"Escalate to IronPeak's account executive that Hal's team caused the outage.",s:0,d:{trust:0,conf:-3,health:-2},
    after:"The account executive defends Hal. Hal stops picking up Sam's calls. Nobody knows yet whose fault it was.",
    why:"Escalating blame before you know the cause damages the relationship you need to fix it. Find the facts first."}
  ]},
 {id:"c2s3", domain:"Process", task:"Build quality in",
  text:s=>["The fix is clear now: new power distribution units and the right firmware. IronPeak can install them by the end of next week.","Lena, relieved, proposes a plan. <span class=\"said\">\"After they finish, we run burn-in twice instead of once. If anything's wrong, we'll catch it.\"</span>"],
  opts:[
   {t:"Agree to double burn-in. A second full test round is cheap insurance for this.",s:1,d:{trust:1,conf:0,health:1},
    after:"The second run adds three days. It catches nothing new, because the problem was never in the testing. It was in how the install was checked before testing started.",
    why:"More inspection at the end is quality control. It finds defects after they exist. Useful, but the exam prefers preventing defects in the first place."},
   {t:"Add install checklists and spot checks with IronPeak before burn-in even starts.",s:3,d:{trust:2,conf:2,health:5},best:true,
    after:"Sam and Hal write a one-page install checklist: unit serials logged, firmware version confirmed per rack, voltage checked under load before burn-in. Priya spot-checks three racks herself. Burn-in runs once and passes.",
    why:"That's quality assurance: improving the process so defects don't happen, instead of hunting for them later. Prevention over inspection is one of the most reliable exam themes."},
   {t:"Leave testing to IronPeak, since they own the hardware and know the equipment best.",s:0,d:{trust:0,conf:-1,health:-4},
    after:"IronPeak runs its standard test, which is the same test that missed the firmware mismatch the first time.",
    why:"You can rely on a vendor's work, but you still own the quality of your project's deliverables. Hands-off is how the first failure happened."},
   {t:"Skip burn-in on the new units this time, since the root cause is already known.",s:0,d:{trust:-1,conf:-1,health:-5},
    after:"Lena looks at Sam like he's lost his mind. She's right. Skipping verification to save three days is how you lose three weeks.",
    why:"Knowing the cause of the last failure doesn't prove the fix works. Never skip verification to save time on a quality problem."}
  ]},
 {id:"c2s4", domain:"Business Environment", task:"Use the contract",
  text:s=>["Hal calls Thursday. IronPeak will install the new units, but they want Halcyon to pay $94,000 for the expedited parts and labor. <span class=\"said\">\"Your timeline, your rush fee,\"</span> he says.","Sam pulls the IronPeak contract. Section 9 covers equipment IronPeak supplies and installs. It includes a ninety-day workmanship and defect warranty."],
  opts:[
   {t:"Pay the $94,000 now to keep things moving, then sort out who owes what later on.",s:1,d:{trust:0,conf:0,health:2},
    after:"The parts ship. Getting the money back later takes four months and a lot of email.",
    why:"Protecting the schedule matters, but paying before you check the contract can waive a claim you were entitled to. Read the terms first."},
   {t:"Send Hal the warranty clause with a written claim and negotiate from there.",s:3,d:{trust:0,conf:3,health:4},best:true,
    after:"Sam sends Hal the warranty clause, the root cause notes from Wednesday, and a written claim. IronPeak's contracts team agrees the units and firmware fall under warranty. They split the expedite shipping, about $6,000. Everything is in writing.",
    why:"Know your contract, raise the claim in writing with evidence, and try to settle it by negotiation. That's claims administration. Litigation is a last resort, and paying first gives up leverage."},
   {t:"Have Halcyon's lawyers send a notice of breach before IronPeak does any more work.",s:0,d:{trust:0,conf:-2,health:-4},
    after:"IronPeak pauses all work while its own lawyers review the notice. The install slips a week.",
    why:"Formal legal action before you've even negotiated stalls the work you need and poisons the relationship. Use the contract's normal claim process first."},
   {t:"Offer to split the $94,000 evenly so the relationship stays good for later.",s:0,d:{trust:0,conf:-1,health:1},
    after:"Hal accepts immediately, which tells Sam he offered too much.",
    why:"Compromising on something the contract already covers isn't relationship building. It's giving away money. Start from what the contract says."}
  ]},
 {id:"c2s5", domain:"Process", task:"Read the earned value",
  text:s=>["End of week four. Elena wants numbers for Tuesday's board meeting. The project's budget at completion is $2.4 million.","Sam's status sheet shows: planned value to date $640,000. Earned value to date $544,000. Actual cost to date $680,000."],
  opts:[
   {t:"Report SPI 0.85 and CPI 0.80: behind and over budget, with causes and fixes.",s:3,d:{trust:0,conf:5,health:3},best:true,
    after:"Sam's one page says: for every dollar of planned work, we've finished 85 cents. For every dollar spent, we've gotten 80 cents of value. Then it says why, the cluster failure and rework, and what's being done. Ruth reads it before the meeting and says only, <span class=\"said\">\"Good. No adjectives.\"</span>",
    why:"SPI is EV divided by PV: 544 over 640 is 0.85, behind schedule. CPI is EV divided by AC: 544 over 680 is 0.80, over budget. Anything under 1.0 is bad news. Report it straight, with the drivers and the corrective actions."},
   {t:"Report that spending is about on plan, since $680K actual is close to $640K planned.",s:0,d:{trust:0,conf:-5,health:-3},
    after:"A board member who used to run a defense program asks what the earned value is. The room gets quiet.",
    why:"Comparing actual cost to planned value is the trap. It ignores how much work actually got done. You need earned value to know whether the money bought progress."},
   {t:"Report the CPI as 1.25 since the team earned less than it spent so far this month.",s:0,d:{trust:0,conf:-4,health:-2},
    after:"Lena checks the math on her phone during the meeting. It's upside down.",
    why:"CPI is EV divided by AC, not the other way around. Here that's 0.80. Flipping the ratio turns a warning into good news, which is the worst possible mistake to make in front of a board."},
   {t:"Report the numbers but leave out the indices so the board doesn't fixate on them.",s:1,d:{trust:0,conf:-1,health:0},
    after:"The board does the math itself. Elena asks Sam afterward why he made them.",
    why:"Raw numbers without interpretation push the work onto the audience. Give them SPI, CPI, and what they mean. Transparency beats softening."}
  ]},
 {id:"c2s6", domain:"Process", task:"Compress the schedule",
  text:s=>["The cluster rework cost about two weeks. Cascade's three-hospital go-live is still on the contract date, and there's no float left on the critical path.","Lena has ideas. Grant has louder ones. Elena wants Sam's recommendation by Friday."],
  opts:[
   {t:"Add eight contract engineers across all teams to speed up every open workstream.",s:0,d:{trust:-2,conf:0,health:-3},
    after:"Onboarding the eight contractors eats Theo's and Priya's time for two weeks. The project gets slower before it gets faster.",
    why:"Adding people to everything is expensive crashing, and late additions slow a project down while they ramp up. Crash only critical path tasks where more people actually shorten the work."},
   {t:"Overlap integration testing with commissioning wherever it's safe to do so.",s:3,d:{trust:1,conf:2,health:6},best:true,
    after:"Sam and Lena walk the critical path. Integration testing for the documentation agents doesn't need the whole cluster, just eight healthy nodes. They start it on the first racks that pass burn-in. They log the added risk of rework and buy back nine days.",
    why:"That's fast tracking: doing activities in parallel that were planned in sequence. It adds risk, not cost, so you pick overlaps carefully and log the risk. Always start from the critical path."},
   {t:"Ask the team to work six-day weeks until go-live to recover the two lost weeks.",s:0,d:{trust:-6,conf:0,health:-2},
    after:"The team agrees. By week three the error rate is up and two engineers are out sick.",
    why:"Sustained overtime is the least effective way to recover a schedule. It burns out the team and adds defects. The exam treats it as a last resort, not a plan."},
   {t:"Pay IronPeak extra to run its install crew around the clock on the remaining racks.",s:1,d:{trust:0,conf:0,health:3},
    after:"IronPeak finishes four days early, at a premium that eats a chunk of the contingency reserve.",
    why:"That's crashing, adding money to shorten a critical task. It's legitimate, but it costs more than overlapping work that's already safe to overlap. Look at fast tracking first, then crash where the cost is worth it."}
  ]},
 {id:"c2s7", domain:"Process", task:"Use the right reserve",
  text:s=>["The settlement with IronPeak and the overlapped testing still leave $52,000 in unplanned costs: extra test hardware and some overtime at IronPeak.","When the project was planned, the cost baseline included a $120,000 contingency reserve for identified risks. Line fourteen, the hardware defect risk, was one of them. Separately, Elena holds a management reserve for things nobody saw coming."],
  opts:[
   {t:"Ask Elena to release management reserve, since the failure was a serious surprise.",s:1,d:{trust:0,conf:-1,health:1},
    after:"Elena asks why. Sam points to line fourteen in the risk register. Elena points out that line fourteen means it wasn't a surprise.",
    why:"Management reserve covers unknown unknowns and needs management approval. This risk was identified and planned for. Its money already sits in the contingency reserve."},
   {t:"Use the contingency reserve for line fourteen and record the draw in the register.",s:3,d:{trust:0,conf:3,health:4},best:true,
    after:"Sam draws $52,000 from contingency, updates the risk register and the cost report, and notes the reserve left: $68,000. It takes ten minutes and nobody has to call a meeting.",
    why:"Contingency reserve is inside the cost baseline and is there for identified risks. The PM can use it for exactly this. Record it and keep track of what's left."},
   {t:"Move $52,000 from the LabelForge budget line, since that vendor is behind anyway.",s:0,d:{trust:0,conf:-3,health:-3},
    after:"Three weeks later LabelForge delivers its recovery batches and invoices on time. The money isn't there.",
    why:"Quietly shifting money between budget lines hides the real cost and creates a new problem down the road. Use the reserve that exists for this purpose."},
   {t:"Ask Grant to bill Cascade for the overrun, since the deadline was their requirement.",s:0,d:{trust:0,conf:-6,health:0},
    after:"Grant actually tries. Ochoa's reply is short and not friendly.",
    why:"The customer didn't cause the defect and the contract doesn't let you pass it on. Trying burns trust you'll need at go-live."}
  ]},
 {id:"c2s8", domain:"Business Environment", task:"Escalate what isn't yours",
  text:s=>["Priya finds something in a facilities calendar. Halcyon's building is getting a power upgrade the week before go-live. It'll take down the staging environment, where Cascade's final acceptance testing is supposed to run, for three days.","The upgrade is run by Halcyon's facilities team. It isn't part of Sam's project, and he has no say over its dates."],
  opts:[
   {t:"Build a second staging environment at IronPeak so the upgrade won't matter at all.",s:0,d:{trust:0,conf:0,health:-3},
    after:"The quote comes back at $70,000 and three weeks of Theo's time. Neither is available.",
    why:"That's an expensive response to a risk you don't own, and it might not even be needed. Find out whether the owner can solve it first."},
   {t:"Escalate it to the facilities owner and Lena, and confirm someone accepts ownership.",s:3,d:{trust:1,conf:3,health:4},best:true,
    after:"Sam sends a short note to the facilities director and Lena with the dates and the impact, and asks for a fifteen minute call. The facilities director had no idea. She moves the upgrade back one week. Sam marks the risk escalated and closed in his register.",
    why:"When a risk sits outside the project's scope or the PM's authority, the response is to escalate it to the person who owns it. Make sure they accept it, then record it. You don't solve other people's risks with your budget."},
   {t:"Accept the risk and plan to run acceptance testing on the production cluster instead.",s:0,d:{trust:0,conf:-3,health:-2},
    after:"Lena vetoes testing on production a few hours after she hears about it, and she's right.",
    why:"Acceptance is a valid strategy, but this response trades one risk for a worse one: testing in production with patient workflows next door."},
   {t:"Note the risk in the register and plan to revisit it the week before go-live.",s:1,d:{trust:0,conf:0,health:-1},
    after:"By the time Sam revisits it, the facilities contractor is booked and the date is fixed.",
    why:"Recording it is a start. Waiting until it's too late to act turns a cheap fix into a crisis. Escalate early, while the owner still has options."}
  ]},
 {id:"c2s9", domain:"Business Environment", task:"Run the change request",
  text:s=>["One more thing came out of the root cause work. To keep the new firmware stable, the cluster needs a monitoring tool IronPeak doesn't provide. It costs $38,000 a year and needs two weeks of setup.","It isn't in the scope or the budget. Lena says just buy it. <span class=\"said\">\"It's obviously needed.\"</span>"],
  opts:[
   {t:"Buy it today with a team credit card and explain it at next week's status review.",s:0,d:{trust:0,conf:-4,health:1},
    after:"Finance flags the purchase in its monthly review. Elena hears about it from the CFO, not from Sam.",
    why:"Necessary or not, adding scope and cost without approval skips change control. The exam is consistent: assess impact, submit the change, get a decision, then act."},
   {t:"Write a change request with cost and schedule impact for Elena to decide.",s:3,d:{trust:0,conf:4,health:4},best:true,
    after:"Sam's change request is one page: what, why, cost, schedule impact, and what happens without it. Elena approves it the same day. Sam updates the scope, the cost baseline, and the plan, then tells the team.",
    why:"Every change goes through integrated change control: analyze the impact, submit it, get approval from the right authority, then update the baselines and communicate. Fast is fine. Skipped isn't."},
   {t:"Skip the tool and have Theo write monitoring scripts himself over the weekend.",s:0,d:{trust:-4,conf:0,health:-2},
    after:"Theo writes them. They mostly work. He's the only one who understands them.",
    why:"Loading more critical work onto your bottleneck to avoid a process is the opposite of what chapter one taught. It also creates a single point of failure."},
   {t:"Ask Lena to approve it, since she's the CTO and owns the technical decisions here.",s:1,d:{trust:1,conf:0,health:2},
    after:"Lena approves it. Elena later asks why a budget change went around her.",
    why:"Lena may be the right technical voice, but the charter says budget changes go to the sponsor. Route the change to whoever holds that authority."}
  ]},
 {id:"c2s10", domain:"People", task:"Close the loop with the team",
  text:s=>["Friday afternoon of week four, burn-in passes. All 128 GPUs, green across every rack.","The team has been running on adrenaline and cold pizza for nine days. Lena wants to go straight into integration testing Monday. <span class=\"said\">\"Momentum,\"</span> she says."],
  opts:[
   {t:"Run a short retrospective on the failure and thank people by name, specifically.",s:3,d:{trust:6,conf:1,health:3},best:true,
    after:"Forty-five minutes, no slides. What went well, what didn't, what we change. They add the install checklist to the standard process and agree to put an owner on every risk in the register. Then Sam thanks Theo, Priya, and the IronPeak techs by name, with what each did. Priya turns red.",
    why:"Capture lessons while they're fresh, and recognize people specifically and publicly. Retrospectives aren't just for agile teams. They turn a crisis into process improvements, and recognition keeps a tired team going."},
   {t:"Order dinner for the team Friday night and save the debrief for after go-live.",s:1,d:{trust:3,conf:0,health:0},
    after:"Dinner is great. By the time go-live is over, nobody remembers the details of what went wrong at IronPeak.",
    why:"Celebrating is good. Waiting months to capture lessons means losing them. Do both, and do the lessons learned now."},
   {t:"Send a thank you note about the team to Elena and the board, and copy the team.",s:1,d:{trust:2,conf:2,health:0},
    after:"The board likes the note. The team likes it less than Sam expected. It reads like it was written for the board.",
    why:"Visibility for the team's work is good, but recognition lands best when it's direct and specific. And it doesn't replace capturing the lessons."},
   {t:"Agree with Lena and start integration testing Monday to keep the momentum going.",s:0,d:{trust:-4,conf:0,health:-1},
    after:"Monday comes. The same install mistakes are waiting for the next rack expansion, because nobody wrote them down.",
    why:"Skipping reflection to save an hour means you'll relearn the same lesson the expensive way. And a team that never hears thanks stops going the extra mile."}
  ]}
 ],
 closing:s=>[
  "Sunday morning Ruth meets Sam at the same coffee shop in Golden. She's read his earned value page twice.",
  "<span class=\"said\">\"Apollo 13 didn't come home because the plan was good,\"</span> she says. <span class=\"said\">\"It came home because when the plan broke, people found out why before they decided what to do. You did that this week.\"</span>",
  (s.score>=24?"She slides the page back across the table. <span class=\"said\">\"0.85 and 0.80. Most people would've hidden those numbers. You put them on top.\"</span>":"She slides the page back across the table. <span class=\"said\">\"Next time, slow down when it breaks. Find the cause, then act. The fast answer is usually the expensive one.\"</span>"),
  "Monday at 8:05, Theo knocks on Sam's open door and closes it behind him. He doesn't sit down.",
  "<span class=\"said\">\"I accepted an offer,\"</span> he says. <span class=\"said\">\"I'm sorry. I've been running on fumes since summer. My last day is three weeks from Friday.\"</span>",
  "Sam does the math before Theo finishes the sentence. Three weeks from Friday is four days before go-live."
 ],
 videos:{
  c2s1:["iVcFpzmqtzA","The Issue Log: Project Management Key Concepts","David McLachlan","3:53"],
  c2s2:["zvkYFZUsBnw","Learn to Use the 5 Whys Root Cause Analysis Tool","Velaction Continuous Improvement","5:52"],
  c2s3:["cnvDYN8udGM","Quality Assurance vs Quality Control","Belinda Goodrich","4:07"],
  c2s4:["EuWaxT2o-iE","Claims Administration: Key Concepts in Project Management","David McLachlan","2:36"],
  c2s5:["sAZZ5av9kk0","What is Earned Value Management?","Mike Clayton","5:53"],
  c2s6:["HUP39ZoCaTQ","Project Schedule Compression Techniques","David McLachlan","3:37"],
  c2s7:["kVHlqlAM1bs","Management Reserves versus Contingency Reserves","David McLachlan","3:06"],
  c2s8:["eeV1lHivPXk","Risk Response Strategy: Escalate Risks","PMC Lounge","10:37"],
  c2s9:["lA9PkCOAUQE","Perform Integrated Change Control: Change Request Flow","iZenBridge","7:42"],
  c2s10:["aht1Px8FvMs","What are Lessons Learned?","Mike Clayton","3:56"]
 },
 deeper:["RET8LcOUJLA","All the PMP and CAPM Formulas in One Video","Andrew Ramdayal","1:10:52"],
 episode:{src:"audio/ch2-burn-in.mp3",len:"19 minutes"},
 next:"Storming"
});
