// Chapter 3. Schema: see chapters/ARC.md.
(window.HALCYON=window.HALCYON||[]).push({
 num:3, title:"Storming",
 opening:[
  "Theo told Sam on a Thursday, in the parking garage, which was the only place at Halcyon without a whiteboard. He'd taken a job at a research lab in Seattle. Better pay, no pager, a team of twelve instead of a company of six hundred that all needed him at once. His last day was three weeks out.",
  "Sam didn't argue. He'd watched Theo answer Slack at two in the morning for a month. He just said, <span class=\"said\" data-who=\"Sam\">\"Thank you for telling me first.\"</span>",
  "The cluster was fixed. IronPeak had swapped the bad power units and the firmware matched now, but the burn-in mess had eaten about two weeks of float. Go-live for the first three Cascade hospitals was nine weeks away, and the one person who understood the whole ML platform was leaving in three.",
  "By Monday everyone knew. Standup was eleven minutes of people looking at their shoes. Lena Cho canceled her one on ones. Grant Mercer sent Elena a message that started with <span class=\"said\" data-who=\"Grant\">\"I warned you about engineering\"</span> and went downhill from there.",
  "Ruth Calder called that night. <span class=\"said\" data-who=\"Ruth\">\"So your team just lost its best player and found out it has opinions,\"</span> she said. <span class=\"said\" data-who=\"Ruth\">\"Good. Now you'll find out what they're made of.\"</span>"
 ],
 scenes:[
 {id:"c3s1", domain:"Process", task:"Plan the knowledge transfer",
  text:s=>["Sam spends Tuesday listing what Theo knows that nobody else does. The deploy pipeline. The model evaluation harness. The IronPeak cluster configuration, which lives mostly in Theo's head and partly in a text file called \"notes_final_v3.\"","Three weeks. Theo is willing. He's also still carrying four critical tasks."],
  opts:[
   {t:"Map what only Theo knows, rank it by risk, and have him hand it to Priya in pairs.",s:3,best:true,d:{trust:4,conf:2,health:6},
    after:"Sam and Theo spend an hour ranking the list by what would hurt most if it walked out the door. The deploy pipeline goes first. Priya pairs with Theo every afternoon and runs the deploys herself while he watches. By day ten she's done four without him touching the keyboard.",
    why:"Knowledge transfer is a planned activity, not a hope. Find the knowledge that's at risk, prioritize it, and transfer it by doing the work together, because the most important knowledge is the kind nobody thinks to write down. Then update the risk register."},
   {t:"Ask Elena to make Theo a counteroffer so he stays with Halcyon at least through go-live.",s:0,d:{trust:-2,conf:-1,health:-2},
    after:"Elena makes the offer. Theo turns it down politely, and now everyone knows the company tried to buy him back. Three days are gone and the transfer hasn't started.",
    why:"Retention is leadership's call and Theo has already decided. The PM's job is to protect the project from the loss. Plan as if he's leaving, because he is."},
   {t:"Have Theo write complete documentation for every system he owns before his last day.",s:1,d:{trust:0,conf:0,health:2},
    after:"Theo writes forty pages. They're accurate and nobody reads them. The first time Priya deploys alone, she hits a step that isn't in the document because Theo never thought of it as a step.",
    why:"Documentation helps, so this isn't wrong. But written docs only capture what people know they know. The tacit knowledge transfers through pairing, shadowing, and doing the work with the expert in the room."},
   {t:"Post Theo's job today and hold his critical tasks until the replacement starts work.",s:0,d:{trust:-1,conf:-3,health:-6},
    after:"Recruiting says a senior ML platform hire takes three to four months. Four critical tasks sit untouched for two weeks before Sam realizes nobody is coming in time.",
    why:"Hiring is a long term fix for a short term problem. Freezing critical path work while you wait guarantees a slip. Transfer the knowledge to the people you have."}
  ]},
 {id:"c3s2", domain:"People", task:"Coach a new lead",
  text:s=>["Priya Shah has been at Halcyon two years. She's quick, careful, and the only person Theo trusts with production. On Wednesday she asks Sam for ten minutes and closes the door.","<span class=\"said\" data-who=\"Priya\">\"Everyone's acting like I'm the new Theo,\"</span> she says. <span class=\"said\" data-who=\"Priya\">\"I'm not. I don't think I'm ready for this.\"</span>"],
  opts:[
   {t:"Give Priya full ownership of the platform now. People grow fastest when thrown in.",s:0,d:{trust:-5,conf:0,health:-3},
    after:"Priya says okay because Sam is her boss's boss's peer and it feels like an order. She stops sleeping well. In week two she misses a warning sign in the evaluation results because she's covering four jobs.",
    why:"Sink or swim isn't empowerment. It ignores what she told you. Growing someone into a role means support that tapers off as their confidence and skill rise."},
   {t:"Ask what worries her most, agree what she owns first, and coach her weekly.",s:3,best:true,d:{trust:6,conf:1,health:4},
    after:"It turns out she's fine with deploys. What scares her is the evaluation harness and being the one who says \"no\" to Grant. They agree she owns deploys now, the harness in two weeks, and Sam takes the Grant conversations until she's ready. They meet every Friday for thirty minutes.",
    why:"Coaching starts with listening. Find out what she's actually worried about, give her a clear and limited scope to start, and support her as she grows. That's how a servant leader builds capability instead of just assigning it."},
   {t:"Keep Priya as backup for now and take on Theo's coordination work personally.",s:0,d:{trust:-2,conf:0,health:-4},
    after:"Sam becomes the new bottleneck. He spends his evenings in Slack answering platform questions he half understands, and the status reports start arriving late.",
    why:"The PM absorbing technical work just moves the single point of failure to a different desk. Your job is to build the team's capacity, not replace a missing person yourself."},
   {t:"Send Priya to a two-week ML platform course before she takes over any of the work.",s:1,d:{trust:2,conf:0,health:-2},
    after:"Priya is grateful. She's also gone for two of Theo's last three weeks, which means she learns the platform from slides instead of from Theo.",
    why:"Training is a good idea, so this gets partial credit. The timing is wrong. With Theo leaving, on the job learning beside the expert is worth more than a course. Schedule the formal training after he's gone."}
  ]},
 {id:"c3s3", domain:"People", task:"Resolve conflict between leaders",
  text:s=>["Thursday's sprint planning. Fifteen people in the room, four on video from Kraków. Grant walks in late and says, to nobody in particular, that the phased release is <span class=\"said\" data-who=\"Grant\">\"engineering covering for itself.\"</span>","Lena, who never raises her voice, raises her voice. <span class=\"said\" data-who=\"Lena\">\"Engineering is covering for promises you made without asking us.\"</span>","The room goes silent. Fifteen people watch the CTO and the CRO stare at each other."],
  opts:[
   {t:"Call a break and tell them both this argument needs to happen outside the meeting.",s:1,d:{trust:2,conf:-1,health:1},
    after:"The meeting recovers. Grant and Lena both leave annoyed with Sam, and with each other, and nothing gets resolved. They avoid each other for a week.",
    why:"Stopping a public fight is reasonable, so this gets partial credit. But ending the meeting isn't resolving the conflict. It's smoothing. The real fix happens after: getting both people to work the problem together."},
   {t:"Meet Grant and Lena together, in private, and work the problem from the shared goal.",s:3,best:true,d:{trust:4,conf:4,health:3},
    after:"Sam books thirty minutes with both of them. He opens with the one thing they agree on: Cascade has to go live. Grant admits he's taking heat from the board. Lena admits sales has never once been in a planning meeting. They leave with a standing invite for Grant to sprint reviews and a rule that commitments to Cascade go through Sam first.",
    why:"Collaborating, also called problem solving, is the conflict mode PMI prefers when the stakes and the relationships both matter. Bring the parties together privately, find the shared goal, and work toward a solution both can commit to."},
   {t:"Back Lena in front of the team, since the phased release was the right call to make.",s:0,d:{trust:1,conf:-6,health:-1},
    after:"Engineering loves it. Grant goes straight to Elena and tells her the project lead has picked a side. He's not wrong.",
    why:"Taking sides in public turns a conflict between two people into a conflict between camps. Even when one side is right on the facts, the PM's role is to resolve, not to win."},
   {t:"Ask Elena to settle it, since Grant and Lena both report to her as executives.",s:0,d:{trust:-1,conf:-2,health:0},
    after:"Elena talks to each of them separately and tells them to get along. They nod. The next planning meeting is just as tense.",
    why:"Escalate what you can't resolve, not what you haven't tried. Going to the CEO first takes the problem out of the room where it has to be solved."}
  ]},
 {id:"c3s4", domain:"People", task:"Lead through storming",
  text:s=>["Week six. Standups have teeth now. Two senior engineers argue about code reviews every morning. One thinks the other rubber stamps everything. The other thinks the first one blocks merges to prove a point.","Velocity is down thirty percent. Lena asks Sam whether the team is falling apart."],
  opts:[
   {t:"Pull the two engineers aside and tell them to keep personal friction out of work.",s:1,d:{trust:0,conf:0,health:1},
    after:"The two engineers stop arguing in standup and start arguing in pull request comments, which is worse because now it's written down.",
    why:"Talking to them directly is a reasonable start, so this gets partial credit. But this is a team pattern, not a personality clash. The tension after losing a key person is the team renegotiating how it works."},
   {t:"Call it a normal stage, run a retro, and let the team rewrite its agreements.",s:3,best:true,d:{trust:6,conf:1,health:5},
    after:"Sam tells the team what he sees: they're storming, it's normal after a big change, and it ends when they decide how they want to work now. The retro is loud. It produces a written code review agreement: two reviewers, a twenty four hour turnaround, and comments about code, never about people. Velocity is back within two sprints.",
    why:"Losing Theo reset the team. Storming is a normal Tuckman stage and the way through it is facilitation, not discipline. Retrospectives and team written working agreements turn conflict into the norms a team will actually follow."},
   {t:"Skip this sprint's retrospective so the team can spend the time getting velocity back.",s:0,d:{trust:-4,conf:0,health:-4},
    after:"The team gets back two hours and loses the one meeting where they could have fixed the problem. Velocity drops again.",
    why:"Cutting the retrospective when the team is struggling is like canceling the post flight debrief because the flight went badly. That's exactly when you need it."},
   {t:"Assign every code review himself so nobody has to argue about who reviews what.",s:0,d:{trust:-4,conf:0,health:-2},
    after:"The arguments stop. So does any sense that the team owns its own process. Two engineers ask Lena whether Sam is a project manager or a supervisor.",
    why:"Directing the work removes the conflict and the team's ownership along with it. Self organizing teams decide how they work. The PM facilitates that decision instead of making it for them."}
  ]},
 {id:"c3s5", domain:"People", task:"Lead a virtual team",
  text:s=>["To backfill Theo's work, Halcyon has brought on a six person contractor team in Kraków led by Tomasz Nowak. Kraków is eight hours ahead of Denver.","Two weeks in, it isn't working. Standup is at 9 AM Denver, which is 5 PM in Kraków, so they skip it. Handoffs get missed. Tomasz's engineers almost never ask questions, and Sam can't tell whether that means they understand or they don't."],
  opts:[
   {t:"Set overlap hours and handoff rules with Tomasz, and bring his team into ceremonies.",s:3,best:true,d:{trust:5,conf:1,health:5},
    after:"Sam and Tomasz set a two hour overlap window, 7 to 9 AM Denver. Standup moves to 7:30. Every handoff gets a short written note in the ticket. Sam also learns that Tomasz's engineers were raised not to question a client in public, so he starts asking them directly by name. The questions start coming.",
    why:"Virtual teams need deliberate working agreements: overlap hours, clear handoffs, the right tools, and inclusion in the team's ceremonies. Cultural awareness matters too. Silence doesn't always mean agreement."},
   {t:"Ask the Kraków team to shift to Denver hours so everyone works the very same day.",s:0,d:{trust:-5,conf:0,health:-1},
    after:"Tomasz agrees, then two of his engineers quit within the month. Working midnight shifts wasn't in their contract.",
    why:"Forcing a distributed team onto one time zone ignores the people doing the work. Design the collaboration around the team you actually have."},
   {t:"Record each standup and send the Kraków team the video and notes the next morning.",s:1,d:{trust:1,conf:0,health:1},
    after:"The Kraków team watches the recordings. They're always a day behind, and they still have no way to ask questions in the moment.",
    why:"Async communication is useful, so this gets partial credit. But recordings make the Kraków team spectators. They need real overlap time and a seat in the conversation."},
   {t:"Give the Kraków team self-contained tasks so they never depend on the Denver team.",s:0,d:{trust:-2,conf:0,health:-2},
    after:"It works for a sprint. Then integration week arrives and nothing the Kraków team built fits what Denver built.",
    why:"Isolating a remote team creates a second team. Dependencies don't disappear because you stopped talking about them. Integrate the team instead of fencing it off."}
  ]},
 {id:"c3s6", domain:"People", task:"Address underperformance",
  text:s=>["Devin Ruiz, a backend engineer, has missed his last three commitments. His pull requests come back from review twice before they merge. At lunch, Sam hears two people complaining that they're carrying Devin.","Devin was solid for a year before this. Sam hasn't talked to him about it yet."],
  opts:[
   {t:"Raise Devin's misses at standup so the team can see the problem is being handled.",s:0,d:{trust:-7,conf:0,health:-1},
    after:"Devin turns red and says nothing. The team learns that missing a date gets you named in front of everyone, and two people start padding their estimates.",
    why:"Performance problems are handled privately. Calling someone out in public damages trust across the whole team, not just with that person."},
   {t:"Quietly move Devin's critical tasks to stronger engineers and keep him on small work.",s:0,d:{trust:-2,conf:0,health:1},
    after:"The critical path is safer for a week. The two stronger engineers are now overloaded, and Devin can tell he's been sidelined without anyone saying why.",
    why:"Working around a performance problem without talking about it doesn't solve it. It spreads the load and the resentment. Have the conversation first."},
   {t:"Talk to Devin privately, find out what's going on, and agree on next steps.",s:3,best:true,d:{trust:5,conf:0,health:4},
    after:"Devin's father went into the hospital a month ago. He's been driving to Pueblo three nights a week. He also admits he doesn't understand the new integration interface and has been too embarrassed to ask. They agree on a lighter load for two weeks, Priya walks him through the interface, and Sam points him to the employee assistance program.",
    why:"Start with a private conversation to understand the cause before you judge. Then set clear expectations together. Most performance problems have a reason, and coaching beats discipline as a first step."},
   {t:"Let Devin's functional manager know about the misses and leave next steps to HR.",s:1,d:{trust:-1,conf:0,health:0},
    after:"Devin's manager schedules a performance conversation for the following month. Nothing changes on the project in the meantime.",
    why:"In a matrix organization the functional manager may need to be involved, so this isn't wrong. But the PM should talk to the team member directly first. Escalate only if the direct approach doesn't work."}
  ]},
 {id:"c3s7", domain:"Process", task:"Negotiate for a shared resource",
  text:s=>["Halcyon has one healthcare security engineer, Nora Kim. Cascade needs her for two weeks to finish the security review. So does Ben Adler, the project manager running Halcyon's pilot with Northgate Bank. Same two weeks.","Ben is new, careful, and as stuck as Sam is."],
  opts:[
   {t:"Sit down with Ben, compare both schedules, and work out a split both can live with.",s:3,best:true,d:{trust:2,conf:2,health:4},
    after:"It turns out Northgate needs Nora for three days of design review and then mostly for answering questions. Cascade needs her heads down for the full review. They agree Nora starts with Northgate's design review, then moves to Cascade full time, with a half hour a day held for Ben. They take the plan to Lena together and she signs off in five minutes.",
    why:"In a matrix organization, resources are negotiated. Talk to the other PM first, understand their real need, and look for an arrangement that works for both projects. Escalate to the sponsors only if you can't agree."},
   {t:"Ask Elena to make Cascade the priority, since it's the larger and older contract.",s:1,d:{trust:0,conf:0,health:2},
    after:"Elena does. Ben's pilot slips a week and Ben stops sharing information with Sam.",
    why:"Priority calls between projects do belong to leadership in the end, so this gets partial credit. But you skipped the step where you and Ben might have solved it yourselves, and you burned a relationship you'll need again."},
   {t:"Book Nora's calendar for both weeks right now, before Ben gets a chance to ask her.",s:0,d:{trust:-3,conf:-2,health:0},
    after:"Nora sees two conflicting requests and tells both of them to figure it out. Ben now knows Sam tried to go around him.",
    why:"Grabbing a shared resource first is a trust killer. It also doesn't work, because the people and their managers will notice. Negotiate in the open."},
   {t:"Hire an outside security contractor for Cascade so Nora can stay on the bank work.",s:0,d:{trust:0,conf:-1,health:-3},
    after:"Procurement needs three weeks to onboard a contractor, and Cascade's security office wants to review the new person's credentials. The review slips anyway.",
    why:"Bringing in outside help without checking the cost, the lead time, and the customer's requirements creates new risks. Look at the options you have before adding new ones."}
  ]},
 {id:"c3s8", domain:"People", task:"Manage your own reaction",
  text:s=>["Friday, 6:10 PM. An engineer pushes a change to the demo environment without the test run the team agreed to in the retro. The demo environment goes down. Ochoa's team was going to look at it Monday morning.","Priya is already rolling it back. Sam is staring at the team channel with a message half typed. It's not a nice message."],
  opts:[
   {t:"Post in the team channel that skipping tests is unacceptable and won't happen again.",s:0,d:{trust:-6,conf:0,health:0},
    after:"Thirty people see the message. The engineer who pushed the change goes quiet for a week. Two others start asking Sam for permission before every deploy.",
    why:"A public reprimand in the heat of the moment teaches the team to hide mistakes, not to prevent them. Manage your own emotions first. That's the first part of emotional intelligence."},
   {t:"Step away, cool off, and talk with the engineer Monday about what broke down.",s:3,best:true,d:{trust:5,conf:0,health:3},
    after:"Sam deletes the draft and goes for a walk. Monday he asks the engineer what happened. The answer: the test run takes forty minutes and the engineer was trying to make a train. They agree to speed up the test suite and add a check that blocks deploys without a passing run. Ochoa's review moves to Tuesday, and Sam tells him why.",
    why:"Self awareness and self regulation come before anything else. Address the issue once you're calm, in private, and look for the process gap behind the behavior. Most mistakes are system problems."},
   {t:"Call the engineer tonight and tell him exactly how much damage the change caused.",s:0,d:{trust:-5,conf:0,health:0},
    after:"The call lasts four minutes and goes badly. The engineer apologizes and spends the weekend dreading Monday.",
    why:"The rollback is already happening. Nothing gets better tonight because of that call. All it does is put your frustration on someone else."},
   {t:"Say nothing to anyone and add a required approval to every deploy from now on.",s:1,d:{trust:-1,conf:0,health:2},
    after:"The new approval step works. It also slows every deploy by half a day, and nobody understands why it was added.",
    why:"Fixing the process is the right instinct, so this gets partial credit. But changing how the team works without talking to them skips the people part. Understand what happened, then fix it with the team."}
  ]},
 {id:"c3s9", domain:"People", task:"Recognize the team",
  text:s=>["Week seven turns out to be a good week. Priya runs her first deploy without Theo in the room and it goes clean. Overnight, Tomasz's team in Kraków finds and fixes an integration bug that had been blocking Denver for three days.","Sam wants the team to know it mattered."],
  opts:[
   {t:"Order lunch for the whole team on Friday to celebrate a strong week together.",s:1,d:{trust:2,conf:0,health:0},
    after:"Lunch is nice. The Kraków team, eight hours ahead, gets a photo of the sandwiches.",
    why:"Celebrating is good, so this gets partial credit. But general rewards don't tell people what they did well, and this one left out the people who earned it most."},
   {t:"Ask Elena for spot bonuses for Priya and the Kraków team as a thank-you gift.",s:0,d:{trust:0,conf:0,health:-1},
    after:"Finance says contractors can't receive bonuses through payroll, and Priya's bonus takes six weeks to process. By then the moment has passed.",
    why:"Money isn't always the motivator, and recognition loses its power when it's slow. Recognition works best when it's specific, timely, and matched to what the person values."},
   {t:"Thank Priya and Tomasz's team by name, in the way each of them would value most.",s:3,best:true,d:{trust:7,conf:1,health:1},
    after:"Sam asks first. Priya doesn't want a public fuss, so he tells Lena exactly what she did and copies Priya. Tomasz's team wants their client to know, so Sam names them in the Friday note to Ochoa. Tomasz forwards it to his whole company.",
    why:"Good recognition is specific, timely, and tailored to the person. Ask what they value. Some people want the spotlight and some want their boss to know. Both work when it fits the person."},
   {t:"Hold the thank-yous until go-live, so the recognition means more when it comes.",s:0,d:{trust:-3,conf:0,health:-1},
    after:"Nobody hears anything for six weeks. Priya assumes the deploy was simply expected.",
    why:"Delayed recognition feels like no recognition. Recognize good work when it happens, and celebrate the milestone too."}
  ]},
 {id:"c3s10", domain:"Business Environment", task:"Check compliance before sharing data",
  text:s=>["Tomasz asks for a copy of real Cascade clinical notes. His team is debugging how the agents handle unusual abbreviations, and the synthetic test notes don't have enough of them.","Grant, copied on the thread, replies first. <span class=\"said\" data-who=\"Grant\">\"Just send them a sample. They're under contract.\"</span>","Kraków is in Poland. The notes contain patient information."],
  opts:[
   {t:"Send Tomasz a small sample of real notes, since his team is under a signed contract.",s:0,d:{trust:0,conf:-7,health:-2},
    after:"Three weeks later Cascade's privacy office asks where patient data has been processed. Sam has to tell them. It goes all the way to Ochoa.",
    why:"Being under contract with you doesn't make a subcontractor covered under the customer's agreements. Patient data rules aren't a judgment call. Check the obligations before anything moves."},
   {t:"Check the BAA and contracts with compliance, and give Kraków de-identified test data.",s:3,best:true,d:{trust:2,conf:5,health:3},
    after:"Halcyon's compliance lead confirms what Sam suspected: the business associate agreement with Cascade says patient data stays in US systems. They build a de-identified set with the abbreviations kept and the patient details stripped. Tomasz's team has it in four days. Sam tells Grant why, privately.",
    why:"Compliance requirements belong to the project. When data might cross a legal or contractual line, stop and confirm the requirements with the right people, then find a compliant way to meet the need. On the exam, you never trade compliance for speed."},
   {t:"Tell the Kraków team they can't debug clinical text and keep that work in Denver.",s:1,d:{trust:-2,conf:1,health:-3},
    after:"It's safe. It also means the team best placed to fix the bug can't, and Denver has no time to pick it up.",
    why:"Protecting the data is the right instinct, so this gets partial credit. But you shut down the work instead of finding a compliant way to do it. Confirm the requirement and look for options like de-identified data."},
   {t:"Give Tomasz's team remote access to the US environment so the data never leaves.",s:0,d:{trust:0,conf:-3,health:0},
    after:"Compliance stops it before it starts. Remote access from abroad still counts as access, and the agreement doesn't allow it.",
    why:"A technical workaround isn't a compliance answer. Confirm the requirement with the people who own it before designing around it."}
  ]}
 ],
 closing:s=>[
  "Theo's last day is a Friday. The team gets him a cake shaped like a GPU, which is mostly a rectangle. Priya runs the afternoon deploy while Theo eats cake and doesn't look over her shoulder once. Somebody notices, and it gets a round of applause.",
  "Tomasz joins on video from Kraków at midnight his time to say goodbye. Lena and Grant stand next to each other at the cake, which is the most anyone could have asked for.",
  "Saturday, Sam drives to Ruth's place in Evergreen. She's on the porch with two coffees.",
  "<span class=\"said\" data-who=\"Ruth\">\"In Florida we had afternoon storms almost every day in summer,\"</span> she says. <span class=\"said\" data-who=\"Ruth\">\"You don't cancel the launch program because it rains. You learn the pattern and plan around it. Teams are the same. Every one of them storms. The bad ones just never get out the other side.\"</span>",
  (s.score>=24?"She hands him a coffee. <span class=\"said\" data-who=\"Ruth\">\"Yours got out the other side. You let them fight about the right things.\"</span>":"She hands him a coffee. <span class=\"said\" data-who=\"Ruth\">\"You're closer than you think. Next time it gets loud, ask what the team is really arguing about. It's almost never the thing they say.\"</span>"),
  "Sam's phone buzzes. It's Ochoa. Cascade has named a product owner for the project, Maria Santos, their director of nursing informatics. She wants a live demo with real clinicians in two weeks.",
  "<span class=\"said\" data-who=\"Ruth\">\"Now comes the part where the customer touches it,\"</span> Ruth says. <span class=\"said\" data-who=\"Ruth\">\"That's always where it gets interesting.\"</span>"
 ],
 cast:[
  ["Priya Shah","Engineer stepping up as ML platform lead after Theo."],
  ["Tomasz Nowak","Leads the six person contractor team in Kraków."],
  ["Devin Ruiz","Backend engineer having a rough month."],
  ["Ben Adler","Project manager for Halcyon's Northgate Bank pilot."],
  ["Nora Kim","Halcyon's only healthcare security engineer."]
 ],
 videos:{
  c3s1:["SsFUw1u0kxo","How to Transition People Off a Project","ProjectManager","2:48"],
  c3s2:["odwOAAIcXoA","How to Power Mentor Your Team","ProjectManager","3:24"],
  c3s3:["wSwtbok3rv0","Conflict Management: Key Concepts in Project Management","David McLachlan","5:25"],
  c3s4:["-RwkZxGPQb8","Tuckman's 5 Stages of Team Development","The Right Questions","5:59"],
  c3s5:["95hRrCysWQw","Making Virtual Teams Work: Remote Team Best Practices","Adriana Girdler","11:58"],
  c3s6:["gDsos1wT26g","How to Deal with Underperforming Team Members","Adriana Girdler","8:34"],
  c3s7:["FGBZMJ--5cA","Project Management Organizational Structures: Functional, Matrix, and Projectized","Kandis Porter","6:30"],
  c3s8:["3NfWncucFTQ","How to Improve Your Emotional Intelligence at Work","ProjectManager","5:13"],
  c3s9:["gjEfybuF6Z4","How to Motivate Employees Using the Power of Recognition","Thinka Learning","3:14"],
  c3s10:["liCn3Xd3_y0","How to Manage Data Privacy and Compliance Risks in IT Projects","NxtChair","10:58"]
 },
 deeper:["LcZvGRTJnLo","The Complete Project Management Body of Knowledge in One Video (PMBOK Guide 8th Edition)","David McLachlan","1:15:03"],
 episode:{src:"audio/ch3-storming.mp3",len:"18 minutes"},
 next:"The Demo"
});
