// Chapter 4. Schema: see README (num, title, opening[], scenes[], closing(s), videos{}, deeper[], episode{}).
(window.HALCYON=window.HALCYON||[]).push({
 num:4, title:"The Demo",
 opening:[
  "Week eight. Theo's desk had been empty for nine days, and for the first time in two months nothing was waiting on him.",
  "Priya Shah ran the platform work now. She kept the runbook open on a second monitor and updated it every time something surprised her, which at first was daily and now was weekly. The offshore team in Kraków had stopped apologizing for asking questions. Lena had started saying <span class=\"said\" data-who=\"Lena\">\"I disagree\"</span> out loud in meetings, which surprised everyone, Lena most of all.",
  "Cascade had sent a product owner. Maria Santos was a nurse for fourteen years before she ran nursing informatics for all eleven hospitals. She didn't care how the agents worked. She cared whether a tired night shift nurse could trust what they wrote.",
  "On Thursday, for the first time, real clinicians would use the agents on real workflows in a test environment. Six nurses and a hospitalist from the Laramie hospital. Ochoa would watch from the back of the room.",
  "Sam had stood on flight lines before an inspection. This felt the same. Everything looked fine, and that was exactly what worried him."
 ],
 scenes:[
 {id:"c4s1", domain:"Process", task:"Prepare the sprint review",
  text:s=>["Tuesday. The team wants to rehearse. Grant has a different idea. He wants a polished slide deck and a scripted walkthrough using the three patient scenarios that always work. <span class=\"said\" data-who=\"Grant\">\"First impressions,\"</span> he says. <span class=\"said\" data-who=\"Grant\">\"We control the story.\"</span>","Maria asked for something else: her nurses using the agents on cases they choose."],
  opts:[
   {t:"Build the scripted walkthrough with Grant so the first impression lands well.",s:0,d:{trust:-3,conf:2,health:-3},
    after:"The scripted demo would have looked great. Maria hears about the plan Wednesday and asks, politely, what exactly she's supposed to learn from a rehearsal.",
    why:"A sprint review isn't a sales pitch. It exists to inspect the real increment with real stakeholders and adapt the backlog from what they see. A scripted show hides the information you most need."},
   {t:"Let the nurses use the working agents on their own cases and capture their feedback.",s:3,d:{trust:3,conf:4,health:3},best:true,
    after:"Sam tells Grant the slides can come later. The team sets up seven workstations, a feedback form, and a shared notes doc so every reaction gets written down.",
    why:"Show the working increment, let the people who'll use it drive, and collect feedback to shape the backlog. That's the purpose of the review. Transparency beats polish, especially early."},
   {t:"Run Grant's scripted demo first, then give nurses ten minutes on their own cases.",s:1,d:{trust:0,conf:2,health:0},
    after:"The script eats forty minutes. The nurses get ten, and half of that is spent waiting for logins.",
    why:"Better than script only, but the balance is backwards. The real feedback comes from users working with the product, so give that the time."},
   {t:"Postpone the review a sprint so the team can harden the agents before anyone sees them.",s:0,d:{trust:-1,conf:-5,health:-1},
    after:"Maria writes back that she's already cleared seven nurses' schedules. Ochoa asks Sam whether something is wrong.",
    why:"Delaying feedback to look better later is the opposite of agile. The earlier real users touch the product, the cheaper every fix is."}
  ]},
 {id:"c4s2", domain:"People", task:"Own a failure in front of the customer",
  text:s=>["Thursday, 10:40 AM. Dr. Nadia Fields, a hospitalist, dictates a short admission note. The agent drafts it cleanly. Then she stops scrolling.","<span class=\"said\" data-who=\"Nadia\">\"I never said metoprolol. This patient isn't on metoprolol.\"</span>","The agent added a medication that was never mentioned. The room goes quiet. Ochoa puts his coffee down. Grant is already leaning toward Sam to whisper something."],
  opts:[
   {t:"Say it's a known edge case in the test build and move to the next scenario.",s:0,d:{trust:-2,conf:-7,health:-2},
    after:"Dr. Fields doesn't move to the next scenario. <span class=\"said\" data-who=\"Nadia\">\"In my hospital that edge case is a patient getting the wrong drug.\"</span> The room turns colder than if Sam had said nothing.",
    why:"Minimizing a safety problem in front of the customer destroys trust faster than the defect itself. Own it plainly. Spinning it tells everyone you'll spin the next one."},
   {t:"Thank her, say plainly it's a serious defect, and pause that workflow until it's fixed.",s:3,d:{trust:3,conf:5,health:2},best:true,
    after:"Sam writes it on the whiteboard in front of everyone. <span class=\"said\" data-who=\"Sam\">\"That's exactly why we're here. We won't put this in front of a patient until we know why it happened.\"</span> Ochoa nods slowly. Dr. Fields keeps testing.",
    why:"Be transparent, take ownership, and contain the risk. Pausing the affected workflow protects patients while the team investigates. Stakeholders trust a vendor who names problems before being forced to."},
   {t:"Have Priya debug it live in the room so the customer sees the team respond fast.",s:0,d:{trust:-3,conf:-2,health:-1},
    after:"Priya digs through logs while seven clinicians watch. After twenty minutes she still doesn't know why, and now everyone has seen that.",
    why:"Live debugging under pressure rarely works and wastes the customer's time. Acknowledge, contain, log it, and do the root cause work properly afterward."},
   {t:"Note the defect quietly and send Ochoa a full write-up after the session ends.",s:1,d:{trust:0,conf:1,health:1},
    after:"The write-up is good. But Ochoa spent the rest of the demo wondering whether Sam had even noticed.",
    why:"The write-up is right, but the moment needed acknowledgment in the room. Transparency in real time is part of stakeholder engagement."}
  ]},
 {id:"c4s3", domain:"Process", task:"Fix the definition of done",
  text:s=>["Friday. The root cause takes Priya six hours to find. The prompt for admission notes pulled from a medication list template, and when the transcript was silent, the model filled the gap.","The story was marked done two sprints ago. It passed code review and unit tests. Nobody checked whether the agent ever wrote something the clinician didn't say, because nothing required it."],
  opts:[
   {t:"Add a clinical safety review step at the end, run by Maria's nurses before release.",s:1,d:{trust:0,conf:2,health:2},
    after:"The nurses catch two more issues the next week. They also become a bottleneck, and they have day jobs.",
    why:"Better than nothing, but it inspects quality in at the end instead of building it in. Fix the team's own standard so every increment meets it."},
   {t:"Have the team update the definition of done to require a no-invented-facts test.",s:3,d:{trust:4,conf:2,health:5},best:true,
    after:"The team writes it together: every note must trace each medication, allergy, and diagnosis to the transcript, checked against a test set Maria's nurses help build. Two old stories get reopened.",
    why:"The definition of done is the team's shared quality standard. When a defect escapes, strengthen the standard so quality is built into every increment rather than inspected at the end."},
   {t:"Reopen the medication story, fix the prompt, and keep the done standard as it is.",s:0,d:{trust:0,conf:0,health:-3},
    after:"The fix works for medications. The next week the agent invents an allergy.",
    why:"Fixing the one defect without fixing the standard that let it through leaves the door open. Treat the root cause, not just the symptom."},
   {t:"Ask Lena to make clinical accuracy a release gate owned by the engineering leads.",s:0,d:{trust:-2,conf:0,health:0},
    after:"Lena adds a line to the release checklist. Nobody on the team helped write it, and nobody quite owns it.",
    why:"Quality standards stick when the team owns them. A gate imposed from above, with no shared definition, becomes a box people tick."}
  ]},
 {id:"c4s4", domain:"Process", task:"Write acceptance criteria",
  text:s=>["Maria's backlog has a story that reads, in full: \"As a nurse, I want the agent to draft accurate shift notes.\"","The team estimated it at thirteen points and nobody agreed on what accurate meant. Two engineers built different things for it last sprint."],
  opts:[
   {t:"Have the team define accurate themselves, since they'll build and test it anyway.",s:0,d:{trust:1,conf:-2,health:-2},
    after:"The team writes a good technical definition. Maria reads it and says it misses the two things her nurses complain about most.",
    why:"The product owner represents the customer's needs. The team helps refine, but acceptance criteria that skip the PO miss what the customer actually values."},
   {t:"Work with Maria and the team to write testable acceptance criteria for the story.",s:3,d:{trust:3,conf:3,health:4},best:true,
    after:"In a forty-minute refinement session they turn one vague sentence into three stories, each with criteria a tester can check, like vitals pulled from the chart and never from memory.",
    why:"Backlog refinement with the product owner and the team turns vague requests into stories with clear, testable acceptance criteria. That's how you get a shared understanding of done for each item."},
   {t:"Ask Maria to write a detailed requirements spec for shift notes before the next sprint.",s:1,d:{trust:0,conf:0,health:1},
    after:"Maria sends eleven pages. It's thorough, and half of it changes after the next demo.",
    why:"Detail is good, but a big upfront spec fights the agile approach on the software side. Refine collaboratively, story by story, close to when the work starts."},
   {t:"Leave the story as written and let the next demo show whether it's accurate enough.",s:0,d:{trust:0,conf:-1,health:-4},
    after:"The team builds another version. The demo shows it isn't what Maria meant, again.",
    why:"Feedback loops don't replace clear acceptance criteria. Without them, you pay for the same misunderstanding every sprint."}
  ]},
 {id:"c4s5", domain:"People", task:"Handle work added mid-sprint",
  text:s=>["Tuesday of sprint nine. Maria messages Priya directly. <span class=\"said\" data-who=\"Maria\">\"Can the team also add the wound care note template this sprint? The Cheyenne nurses really need it.\"</span>","The sprint is half done. The goal is getting the new definition of done working across all three note types."],
  opts:[
   {t:"Tell Priya to fit it in. Maria's the product owner, so it's her call to make.",s:0,d:{trust:-4,conf:2,health:-4},
    after:"Priya says yes. The team quietly drops testing on one note type to make room, which is exactly the shortcut that caused the metoprolol problem.",
    why:"The PO owns the backlog, not the sprint the team already committed to. Forcing new work mid-sprint without the team erodes the commitment and usually costs quality."},
   {t:"Ask Maria to add it to the backlog and weigh it against everything else at planning.",s:3,d:{trust:3,conf:2,health:3},best:true,
    after:"Maria isn't thrilled, but she agrees once she sees the sprint goal. Wound care goes to the top of the backlog and starts on Monday.",
    why:"Protect the sprint goal. New requests go to the backlog where the PO prioritizes them for the next sprint. If something truly can't wait, the PO and team negotiate scope together, they don't just add it."},
   {t:"Say no outright. Mid-sprint changes are never allowed once the sprint has started.",s:1,d:{trust:1,conf:-3,health:1},
    after:"The sprint is protected. Maria feels shut out and stops raising requests in the open.",
    why:"Right instinct, wrong delivery. Agile isn't rigid: if the goal is at risk the PO can negotiate with the team. Explain the why and route it properly."},
   {t:"Have a second engineer start wound care in parallel so the sprint goal isn't touched.",s:0,d:{trust:-1,conf:1,health:-3},
    after:"The engineer pulled in was the one testing the new definition of done. Two stories miss it.",
    why:"Starting unplanned work in parallel just splits capacity quietly. It's the same scope change without the conversation."}
  ]},
 {id:"c4s6", domain:"Business Environment", task:"Define the MVP for phase one",
  text:s=>["The backlog has ninety-one items. The three hospital go-live is six weeks out. Grant wants the voice-activated summary feature because it demos beautifully. Maria wants the agents to get medication reconciliation right every time. Lena wants everything.","Ochoa asks a simple question: <span class=\"said\" data-who=\"Ochoa\">\"What exactly will my nurses get on day one?\"</span>"],
  opts:[
   {t:"Include Grant's voice feature in phase one, since it wins customer enthusiasm.",s:0,d:{trust:-1,conf:1,health:-4},
    after:"The voice feature takes two engineers for three weeks. Medication reconciliation slips into phase two.",
    why:"Prioritize by value to the customer, not by how well it demos. The most valuable thing here is safe, accurate documentation."},
   {t:"Promise all ninety-one items by go-live and add contractors to cover the gap.",s:0,d:{trust:-3,conf:2,health:-6},
    after:"Ochoa looks at the list and asks which ones actually matter. Sam can't answer, because he hasn't decided.",
    why:"Overcommitting to everything hides the real decision and adding people late rarely helps. Phase one needs a minimum viable product that delivers the core value safely."},
   {t:"Have Maria rank the backlog by value with stakeholders and cut phase one to an MVP.",s:3,d:{trust:2,conf:5,health:5},best:true,
    after:"Maria, Sam, and Ochoa sort it in an afternoon: must, should, could, won't. Phase one is three note types and medication reconciliation, done right. The voice feature lands in could.",
    why:"The product owner prioritizes the backlog by business value with stakeholder input. Defining a minimum viable product for the first release delivers the core value early and leaves room to learn."},
   {t:"Let the team pick phase one scope based on what they can build with least risk.",s:1,d:{trust:2,conf:-2,health:2},
    after:"The team's list is very safe. It also leaves out the one feature Maria's nurses asked for most.",
    why:"Team input on feasibility matters, but value decisions belong to the product owner. Balance the two; don't let either decide alone."}
  ]},
 {id:"c4s7", domain:"People", task:"Respond to a velocity drop",
  text:s=>["Elena forwards a chart with a single line circled. Velocity dropped from forty points to twenty-eight over two sprints.","Her note says: <span class=\"said\" data-who=\"Elena\">\"What happened? Can the team commit to forty again starting Monday?\"</span>"],
  opts:[
   {t:"Commit to forty points per sprint and ask the team to push a bit harder until go-live.",s:0,d:{trust:-6,conf:1,health:-4},
    after:"The team hits forty the next sprint. Somehow the stories got bigger point values. Nothing more actually shipped.",
    why:"Turning velocity into a target invites inflation and burnout. Velocity is a planning tool for the team, not a performance score."},
   {t:"Explain the drop to Elena and re-forecast with the team using the new velocity.",s:3,d:{trust:4,conf:3,health:3},best:true,
    after:"Sam shows Elena the cause: the stricter definition of done and onboarding the Kraków team. The forecast holds for phase one at twenty-eight. Elena says, <span class=\"said\" data-who=\"Elena\">\"Fine. That's a better answer than forty.\"</span>",
    why:"Find out why with the team, explain it honestly, and use actual velocity to forecast. A drop after raising the quality bar is expected and healthy. Don't let velocity become a stick."},
   {t:"Ask each engineer to report their individual points so the slow ones can be found.",s:0,d:{trust:-7,conf:0,health:-2},
    after:"The team stops pairing, because pairing makes individual numbers look bad. Quality slips.",
    why:"Velocity is a team measure. Breaking it down to individuals damages collaboration, which is the main thing that produces velocity in the first place."},
   {t:"Tell Elena velocity is the team's business and not something executives should track.",s:1,d:{trust:2,conf:-4,health:0},
    after:"Technically fair. Elena hears that she's not allowed to ask questions about her own biggest project.",
    why:"The team owns its velocity, but stakeholders deserve transparent forecasts. Educate the sponsor instead of shutting the door."}
  ]},
 {id:"c4s8", domain:"Process", task:"Manage technical debt",
  text:s=>["Priya brings Sam a list. During the burn-in crisis the team took shortcuts: hard-coded hospital settings, a test suite that skips the slow cases, a logging setup nobody fully understands. Fourteen items.","<span class=\"said\" data-who=\"Priya\">\"None of it's broken yet,\"</span> she says. <span class=\"said\" data-who=\"Priya\">\"It will be when we add eight more hospitals.\"</span> Grant overhears and says features first."],
  opts:[
   {t:"Defer all of it to after phase one. Customers can't see debt and the date matters.",s:0,d:{trust:-3,conf:1,health:-5},
    after:"The hard-coded settings bite during rollout planning for hospital four. Nobody can remember which values are real.",
    why:"Ignoring technical debt doesn't remove the cost, it adds interest. And this debt sits directly in the path of the next release."},
   {t:"Put the debt items in the backlog and have Maria and the team reserve capacity for it.",s:3,d:{trust:3,conf:1,health:5},best:true,
    after:"Maria agrees to fifteen percent of each sprint. The hard-coded settings go first, since they block the next eight hospitals.",
    why:"Make technical debt visible in the backlog and let the PO and team balance it against features. Steady capacity for debt keeps delivery sustainable."},
   {t:"Run a full hardening sprint now with no features, fixing all fourteen items at once.",s:1,d:{trust:2,conf:-3,health:2},
    after:"The code gets cleaner. Maria loses two weeks of features she was counting on, and says so.",
    why:"Hardening sprints sometimes make sense, but they often signal that debt wasn't managed continuously. Paying a bit every sprint, prioritized by the PO, is usually better."},
   {t:"Have Priya fix the worst items quietly on her own time so velocity isn't affected.",s:0,d:{trust:-5,conf:0,health:-1},
    after:"Priya does it. She's now working nights, the exact pattern that burned out Theo.",
    why:"Hidden work isn't free and it recreates the hero problem. Make it visible and plan it like any other work."}
  ]},
 {id:"c4s9", domain:"People", task:"Run the retrospective",
  text:s=>["End of sprint nine. The team's first retrospective since the metoprolol demo. Everyone knows the story. Two engineers have already decided privately whose fault it was."],
  opts:[
   {t:"Open by asking who signed off on the medication story so it doesn't happen again.",s:0,d:{trust:-7,conf:0,health:-2},
    after:"The engineer who marked it done goes red. Nobody says anything useful for the next hour.",
    why:"Hunting for blame shuts down honesty, and honesty is the only fuel a retrospective runs on. Focus on the system and process, not the person."},
   {t:"Run a blameless retro and have the team commit to one or two concrete improvements.",s:3,d:{trust:6,conf:0,health:3},best:true,
    after:"Sam starts by naming his own miss: he never asked what done meant for clinical safety. The team picks two changes, pairing on every prompt change and a weekly nurse review of sample notes.",
    why:"A blameless retrospective looks at what happened in the process, lets the team own the improvements, and limits them to a few they'll actually do. Leaders going first with their own mistakes makes it safe."},
   {t:"Skip the retro this sprint. The team already fixed the problem and is short on time.",s:0,d:{trust:-2,conf:0,health:-3},
    after:"The fix is in. The resentment isn't, and it shows up in the next planning meeting.",
    why:"The retrospective is how a team learns and improves. Skipping it after the biggest failure so far wastes the most valuable lesson you'll get."},
   {t:"Write a lessons learned memo himself and share it with the team for comments.",s:1,d:{trust:0,conf:1,health:1},
    after:"The memo is accurate. The team skims it, and nothing in how they work actually changes.",
    why:"Documenting lessons matters, but improvement sticks when the team discovers it themselves. Facilitate; don't dictate."}
  ]},
 {id:"c4s10", domain:"Business Environment", task:"Make progress visible",
  text:s=>["Week ten. The second demo is in four days. Ochoa calls. <span class=\"said\" data-who=\"Ochoa\">\"My CMO asked me if we should pull the plug after Laramie. I need to show her this is under control, and I don't want another slide deck.\"</span>"],
  opts:[
   {t:"Send Ochoa a confident summary saying the defect is fixed and everything's on track.",s:0,d:{trust:0,conf:-3,health:0},
    after:"Ochoa forwards it. The CMO replies with one question: how do you know? Nobody has an answer that isn't another email.",
    why:"Assurances without evidence don't build confidence after a failure. Stakeholders need to see the facts for themselves."},
   {t:"Share a live dashboard of progress and safety results, and invite the CMO to the demo.",s:3,d:{trust:1,conf:7,health:2},best:true,
    after:"The team puts the burnup chart, the definition of done, and the no-invented-facts test results on one page that updates daily. The CMO comes to the demo. Afterward she asks for the link.",
    why:"Information radiators make progress and quality visible to anyone, any time. Inviting a skeptical stakeholder into the review lets them inspect the work themselves. That's transparency in practice."},
   {t:"Ask Elena to call Ochoa's CMO directly, executive to executive, to restore trust.",s:1,d:{trust:0,conf:2,health:0},
    after:"Elena's call goes fine. The CMO still wants to see evidence, so the question just comes back to Sam.",
    why:"Executive alignment helps, but it doesn't replace transparency about the actual work. Pair the relationship with the data."},
   {t:"Delay the second demo two weeks so there's more time to build the CMO's confidence.",s:0,d:{trust:-1,conf:-5,health:-2},
    after:"The CMO reads the delay as confirmation that something's wrong.",
    why:"Delaying the inspection point makes skeptics more skeptical. Show the work sooner, not later."}
  ]}
 ],
 closing:s=>[
  "Monday, week ten. The second demo runs two hours. Dr. Fields dictates eleven notes and tries to break the agents on purpose with half-finished sentences and a patient who changes their story. Every medication in every draft traces back to something someone actually said.",
  "The CMO stays for all of it. At the end she says, <span class=\"said\" data-who=\"woman\">\"Okay. Laramie, Cheyenne, and Fort Collins. Week fourteen.\"</span>",
  "Ruth is waiting in the lobby, the way she does. <span class=\"said\" data-who=\"Ruth\">\"At NASA we flew a lot of tests that didn't go well,\"</span> she says. <span class=\"said\" data-who=\"Ruth\">\"The failures weren't the problem. Hiding them was. You put that one on a whiteboard in front of the customer.\"</span>",
  (s.score>=24?"She smiles. <span class=\"said\" data-who=\"Ruth\">\"That's the whole job, honestly.\"</span>":"She pauses. <span class=\"said\" data-who=\"Ruth\">\"Next time, slow down when the room goes quiet. That's when people decide whether to trust you.\"</span>"),
  "Sam's phone shows a calendar invite from Elena. Subject: Go/No-Go, Week 14. Underneath, a second notification. Cascade's union representative at the Cheyenne hospital has requested a meeting about \"AI replacing nursing judgment.\"",
  "Ruth reads it over his shoulder. <span class=\"said\" data-who=\"Ruth\">\"Chapter five,\"</span> she says."
 ],
 cast:[
  ["Maria Santos","Director of Nursing Informatics, Cascade. The product owner."],
  ["Dr. Nadia Fields","Hospitalist at Cascade's Laramie hospital. Finds the defect."]
 ],
 videos:{
  c4s1:["Fbp9eLbcf7A","How to Facilitate the Sprint Review","Scrum.org","5:52"],
  c4s2:["5cj0zeuCrR8","Sprint Review Agenda: How to Make the Most of Your Time","Mountain Goat Software","4:40"],
  c4s3:["Hq9O7mnUNM4","Definition of Done vs Acceptance Criteria","Mountain Goat Software","4:42"],
  c4s4:["DavPyEFeEFw","What Are User Story Acceptance Criteria?","BA-EXPERTS","4:55"],
  c4s5:["VltdPhzsvxo","When the Product Owner Brings Unplanned Work Mid-Sprint","AI Product Leadership","4:55"],
  c4s6:["OUStxocWTso","What is a Minimum Viable Product (MVP)?","Mike Clayton","6:13"],
  c4s7:["f0sHvWmKusY","What is Velocity? Agile Velocity 101","Mountain Goat Software","5:20"],
  c4s8:["qGcm6GVyDNw","What is Technical Debt?","ProductPlan","2:53"],
  c4s9:["TD-XsdD2n3s","How to Facilitate the Sprint Retrospective","Scrum.org","7:56"],
  c4s10:["msg96wt0ie0","Setting Up Agile Information Radiators","Bill Dow","7:08"]
 },
 deeper:["8j-76_QQX30","21 Agile Topics in 21 Minutes for the PMP","PMPwithRay","21:21"],
 episode:{src:"audio/ch4-the-demo.mp3",len:"16 minutes"},
 next:"Go-Live"
});
