// Chapter 5. Schema: see chapters/ARC.md.
(window.HALCYON=window.HALCYON||[]).push({
 num:5, title:"Go-Live",
 cast:[
  ["Denise Harmon","Nurse manager, Cascade's Cheyenne hospital. Not a fan of AI."],
  ["Joan Whitfield","Privacy officer, Cascade Valley Health."],
  ["Ken Ito","Security lead, Halcyon AI."]
 ],
 opening:[
  "The second demo worked. Nobody cheered, which Sam took as a good sign. Cascade's clinicians just kept typing questions into the agent and nodding at the drafts, and at the end of the hour one of the hospitalists asked when she could have it for real.",
  "The answer was in the plan. Go-live for the first three hospitals, Fort Collins, Greeley, and Cheyenne, was set for the Monday after week fourteen, the date in the contract. The go/no-go meeting was the Friday before. Four weeks.",
  "Priya Shah ran the platform now. She'd inherited Theo's runbook, half his Slack channels, and none of his habits, which was the point. The offshore team in Kraków handled overnight testing. The board had stopped asking Elena about Cascade every meeting, which Ruth said was the highest compliment a board knows how to give.",
  "On Monday morning Sam opened his inbox and found an email from Cascade's Cheyenne hospital. The subject line was <span class=\"said\">\"Concerns from the nursing staff.\"</span> It had sixty-two signatures.",
  "Ruth called while he was still reading it. <span class=\"said\">\"The last four weeks before a launch are when the work stops being technical,\"</span> she said. <span class=\"said\">\"Everything that's left is people, paperwork, and nerve. Call me Friday.\"</span>"
 ],
 scenes:[
 {id:"c5s1", domain:"People", task:"Lead people through change",
  text:s=>["The petition is polite and specific. The Cheyenne nurses worry the agents will make mistakes they'll be blamed for, that charting will take longer while they learn, and that this is the first step toward cutting staff. Denise Harmon, their nurse manager, signed it first.","Ochoa forwards it to Sam with one line: <span class=\"said\">\"How do you want to handle this?\"</span>"],
  opts:[
   {t:"Ask Ochoa to tell the Cheyenne nurses that using the agents is now required policy.",s:0,d:{trust:0,conf:-5,health:-3},
    after:"Ochoa sends the memo. The nurses comply on paper. Two weeks later the usage reports show half of them open the agent and close it without reading the draft.",
    why:"A mandate gets compliance, not adoption. People resist change they don't understand and had no say in. The exam wants you to engage the people affected and address the concerns behind the resistance."},
   {t:"Swap Cheyenne out of the first wave for a hospital whose nurses are more willing.",s:1,d:{trust:0,conf:-2,health:1},flag:"swapped",
    after:"Ochoa says he'll think about it. Denise hears about the idea anyway and tells her staff that Halcyon tried to route around them. The trust problem moves with the hospital.",
    why:"Changing which sites go first is a scope change that needs the change process and the customer's agreement, and it avoids the real issue. Resistance doesn't go away because you scheduled around it."},
   {t:"Go to Cheyenne, hear out the nurses with Denise, and plan the change with them.",s:3,d:{trust:3,conf:6,health:3},best:true,flag:"listened",
    after:"Sam and Ochoa drive up Thursday. The meeting starts tense. Denise does most of the talking. By the end there's a list of seven concerns, and Denise agrees to pick two nurses from each unit to test the agents early and report back to their peers.",
    why:"Organizational change is a people problem first. Go to the people affected, understand the resistance, and involve them in shaping the change. Champions from inside the group carry more weight than any message from the project."},
   {t:"Send the nurses an FAQ and a demo video answering each concern on the petition.",s:0,d:{trust:0,conf:-1,health:0},
    after:"The FAQ is accurate and thorough. Denise replies that her nurses don't need a brochure, they need someone to listen.",
    why:"Information is part of change management, but one-way communication doesn't address fear. When stakeholders are resisting, a conversation comes before a document."}
  ]},
 {id:"c5s2", domain:"People", task:"Plan training that sticks",
  text:s=>["Cascade's education team has a training plan: one two-hour classroom session per nurse in the week before go-live. Sam looks at the shift schedules. Nurses work twelve-hour shifts, nights and weekends included. The pilot session last week got eleven people out of forty.",(s.flags.listened?"Denise's unit champions say the same thing: nobody can leave the floor for two hours.":"The education director insists the classroom format is how Cascade always trains.")],
  opts:[
   {t:"Make attendance mandatory and have each nurse manager track who completes it.",s:1,d:{trust:-2,conf:1,health:1},
    after:"Attendance climbs to sixty percent. Managers pull nurses off the floor to sit in a classroom, and staffing gets tight. Nobody remembers much a week later.",
    why:"Tracking completion is fine. Forcing a format that doesn't fit how people work treats the symptom. Tailor the training to the audience and their constraints."},
   {t:"Replace the classes with a short e-learning module nurses can finish on breaks.",s:0,d:{trust:0,conf:0,health:-2},
    after:"Completion hits ninety percent in a week. On the first test day it's clear most nurses clicked through without trying the agent once.",
    why:"Convenient isn't the same as effective. A new clinical workflow needs hands-on practice and support on the floor, not just a module that records a completion."},
   {t:"Train unit champions, teach in short on-shift sessions, and staff the floor.",s:3,d:{trust:4,conf:4,health:4},best:true,flag:"champions",
    after:"Each unit gets two champions trained a week early. Sessions shrink to twenty minutes at shift change. Sam books six Halcyon staff to stand on the floors during the first week, at the elbow, for any question.",
    why:"Good training fits the learners: short, in their workflow, with peers who can help and real support when it goes live. Champions and at-the-elbow support are standard for clinical go-lives and good change management on the exam."},
   {t:"Skip formal training and hand out quick reference cards at go-live instead.",s:0,d:{trust:-1,conf:-3,health:-4},
    after:"The cards are well designed. On Monday morning most of them are still in a box at the nurses' station.",
    why:"Training is part of the project scope and the transition. Leaving users to figure it out pushes the cost onto them and onto the support team in the first week."}
  ]},
 {id:"c5s3", domain:"Process", task:"Set go/no-go criteria",
  text:s=>["Elena stops Sam in the hall. <span class=\"said\">\"What does the go/no-go meeting actually decide? I want to know now, not on the Friday.\"</span>","Sam realizes nobody has written it down. Engineering thinks it means the tests pass. Grant thinks it means the date holds. Ochoa thinks it means his nurses are ready."],
  opts:[
   {t:"Use the final test results as the criteria, since passing tests means it works.",s:1,d:{trust:0,conf:0,health:1},
    after:"Engineering is happy. Ochoa asks what passing tests says about whether his nurses can use it. Nobody has an answer.",
    why:"Test results are one criterion, not the whole decision. Readiness also covers training, support, rollback, compliance, and the customer's operations."},
   {t:"Agree measurable criteria with both companies now, and record who decides.",s:3,d:{trust:2,conf:6,health:4},best:true,
    after:"It takes two meetings. The list has eight criteria: accuracy above the agreed threshold, zero open critical defects, eighty-five percent of nurses trained, rollback rehearsed, support staffed, the privacy review signed, and two more. Ochoa and Elena are named as the decision makers.",
    why:"Define go/no-go criteria in advance, make them measurable, and agree on who has decision rights. Then the meeting compares facts against a standard instead of debating feelings."},
   {t:"Let Elena make the call on the day after hearing from each team lead in turn.",s:0,d:{trust:-1,conf:-3,health:-2},
    after:"Elena likes it. Three weeks later she hears five different definitions of ready in one hour and picks the one closest to what she wanted.",
    why:"A decision with no agreed standard turns into politics. Criteria set ahead of time protect the decision from pressure on the day."},
   {t:"Ask Cascade's IT team to define readiness, since their hospitals carry the risk.",s:0,d:{trust:0,conf:1,health:-2},
    after:"Cascade's list is careful about their systems and silent about anything Halcyon has to deliver.",
    why:"Both organizations own part of readiness. The criteria need input from all the key stakeholders, and the PM is the one who brings them together."}
  ]},
 {id:"c5s4", domain:"Process", task:"Plan the cutover and rollback",
  text:s=>["Cutover is Sunday night into Monday. Agents switch on at the three hospitals at 4 AM, two hours before day shift. Priya knows every step. She says so herself, and she's right.","Sam asks to see the rollback plan. Priya says rollback is easy: turn the agents off. Sam asks what happens to the notes drafted between 4 AM and the moment they turn it off. There's a long pause."],
  opts:[
   {t:"Trust Priya's command of the system and keep the cutover plan lightweight.",s:0,d:{trust:1,conf:-2,health:-5},
    after:"Priya is grateful. Sam lies awake Saturday night wondering what happens if Priya gets sick.",
    why:"A plan that lives in one person's head is the Theo problem again. Cutover needs a written plan anyone qualified can follow."},
   {t:"Write a runbook with owners, times, checkpoints, and rollback, then rehearse it.",s:3,d:{trust:3,conf:4,health:6},best:true,
    after:"The runbook is nine pages. The dry run on Wednesday finds two problems, including the answer to Sam's question: draft notes need to be exported before shutdown or they're lost. They fix it. The rollback rehearsal takes forty minutes.",
    why:"A cutover plan has every step, owner, timing, and decision point, with a rollback that's been tested, not just described. Rehearsals find the gaps while they're cheap to fix."},
   {t:"Rehearse the go-live steps in staging, and work out a rollback if one is needed.",s:1,d:{trust:1,conf:1,health:2},
    after:"The go-live rehearsal is smooth. Nobody knows how long a rollback takes, because nobody has done one.",
    why:"Half right. Rehearsing the forward steps is good. A rollback you've never tested is a hope, and you find out it doesn't work at 5 AM with nurses arriving."},
   {t:"Ask Cascade's IT team to own rollback, since they control the hospital systems.",s:0,d:{trust:0,conf:-2,health:-2},
    after:"Cascade's IT team agrees, then asks for documentation on how Halcyon's agents shut down cleanly. There isn't any.",
    why:"Rollback steps touch both companies, so ownership has to be agreed and documented, not handed off. The project owns making sure the plan exists and works."}
  ]},
 {id:"c5s5", domain:"Business Environment", task:"Handle a privacy incident",
  text:s=>["Wednesday of week twelve, 10 PM. Priya calls. <span class=\"said\">\"I was chasing a slow query and found patient names and record numbers in our debug logs. Real ones, from the test hospitals. The logs go to a monitoring tool the Kraków contractors can see.\"</span>","She's already checked. It's been happening for nine days."],
  opts:[
   {t:"Stop the logging, lock down access, and report it through incident response.",s:3,d:{trust:3,conf:3,health:2},best:true,flag:"reported",
    after:"Priya disables the debug logging and cuts the contractors' access within the hour. Sam calls Ken Ito, Halcyon's security lead, at 10:40. Ken opens an incident, preserves the logs as evidence, and loops in legal. Under the business associate agreement, Cascade's privacy officer, Joan Whitfield, is notified the next morning.",
    why:"Contain the problem, preserve the evidence, and escalate through the organization's incident and compliance process right away. Privacy incidents have legal reporting duties the PM doesn't decide alone. Hiding or delaying them is never the answer."},
   {t:"Purge the logs tonight and fix the logging, so there's nothing left to expose.",s:0,d:{trust:-3,conf:-8,health:-2},
    after:"The logs are gone by midnight. Two weeks later Cascade's own audit finds the access records. Halcyon now has a breach and evidence that it tried to hide one.",
    why:"Destroying evidence turns an incident into a cover-up. The exam's ethics answer is always transparency and following the required process, even when it hurts the schedule."},
   {t:"Fix the logging tonight and report the incident after the go-live is safely done.",s:0,d:{trust:-1,conf:-6,health:0},
    after:"Sam tells himself it's only a few days. It's the kind of decision that ends careers when it comes out, and it does come out.",
    why:"Reporting obligations don't wait for your milestones. Delaying a required report to protect a date is a compliance and ethics failure."},
   {t:"Fix the logging, then call Ochoa tonight and tell him everything that happened.",s:1,d:{trust:1,conf:1,health:0},
    after:"Ochoa appreciates the honesty. He also asks whether Halcyon's security and legal teams know yet. They don't.",
    why:"Your instinct toward transparency is right, but you skipped your own organization's incident process. Security and legal decide how and when breaches are reported, with the evidence intact. Escalate internally first, then the formal notification follows."}
  ]},
 {id:"c5s6", domain:"Business Environment", task:"Respond to new guidance",
  text:s=>["Week thirteen. The state health department publishes guidance on AI in clinical documentation. Any AI-drafted note must be clearly labeled, a clinician has to review it before signing, and the system has to keep an audit trail of what the AI wrote versus what the clinician changed.","Halcyon's agents label drafts. They don't keep the audit trail. Go-live is in eleven days."],
  opts:[
   {t:"Note it for phase two, since guidance isn't the same as a law or regulation.",s:0,d:{trust:0,conf:-5,health:-2},
    after:"Cascade's compliance team disagrees. Joan Whitfield emails Ochoa that Cascade won't go live with something that doesn't meet state guidance.",
    why:"Your customer's compliance standards are your requirements. Whether guidance is binding is a question for compliance and legal, not a reason for the project to set it aside."},
   {t:"Assess impact with compliance and Cascade, then run it through change control.",s:3,d:{trust:2,conf:5,health:3},best:true,
    after:"Ken, Joan, and Halcyon's lawyer meet Monday. They agree the audit trail is required for go-live. Priya's estimate is four days. The change request goes through Tuesday, two smaller features move to week fifteen, and the date holds.",
    why:"When the external environment changes, assess the impact on the project with the right experts, then use change control to update scope, schedule, and risk. That's how the exam expects you to handle a new regulation or standard."},
   {t:"Have Priya add the audit trail quietly this week so the date isn't at risk.",s:0,d:{trust:-1,conf:-1,health:-3},
    after:"Priya builds it over a weekend. It isn't tested against Cascade's requirements, and Joan's team finds two gaps during the go/no-go review.",
    why:"Adding scope without change control skips the impact analysis and the people who should check the work. Even urgent changes go through the process, sized to the urgency."},
   {t:"Ask Halcyon's lawyer whether the guidance is binding before making any changes.",s:1,d:{trust:0,conf:0,health:-1},
    after:"The lawyer takes four days to answer, and the answer is that it depends. Four of the eleven days are gone.",
    why:"Legal input matters, but waiting on it alone stalls the work. Run the impact assessment in parallel with the legal question so you're ready either way."}
  ]},
 {id:"c5s7", domain:"Business Environment", task:"Baseline the benefits",
  text:s=>["Cascade's CFO joins the Friday status call for the first time. <span class=\"said\">\"The business case says this saves each nurse forty minutes a shift on documentation. When do I see that number?\"</span>","Sam checks. Nobody has measured how long documentation takes today."],
  opts:[
   {t:"Use the forty minute figure from Halcyon's sales deck as the expected benefit.",s:0,d:{trust:0,conf:-4,health:0},
    after:"The CFO asks where the forty minutes came from. Grant says it was a pilot at another customer. The CFO writes something down.",
    why:"A benefit you can't measure at your own site is a claim, not a result. Benefits need a baseline from the actual environment."},
   {t:"Baseline documentation time on the go-live units now, and name a metric owner.",s:3,d:{trust:1,conf:6,health:2},best:true,
    after:"Cascade's quality team times a sample of notes on six units for one week. Today's average is fifty-one minutes a shift. The CFO and Ochoa agree the metric, and Cascade's nursing operations director will own the measurement after the project closes.",
    why:"Benefits management starts with a measured baseline, an agreed metric, and an owner who'll track it after delivery. Without the before number, you can't prove the after."},
   {t:"Measure documentation time after go-live and compare it against industry averages.",s:1,d:{trust:0,conf:1,health:0},
    after:"It gives the CFO something. It won't tell him whether Cascade's nurses got faster, only how they compare to someone else's.",
    why:"Measuring after is necessary but not enough. Compare against your own baseline, captured before the change, or the comparison doesn't mean much."},
   {t:"Tell the CFO benefits are tracked in phase two, once all eleven hospitals are live.",s:0,d:{trust:0,conf:-3,health:0},
    after:"The CFO doesn't like waiting a year to know whether he's getting what he paid for.",
    why:"Waiting means you can never capture the before. Plan benefits measurement early, while the baseline still exists."}
  ]},
 {id:"c5s8", domain:"Process", task:"Protect quality under pressure",
  text:s=>["Week thirteen, Thursday. The audit trail change ate four days. The final regression test cycle needs four more, and there are three left before the go/no-go meeting.","Elena calls Sam in. <span class=\"said\">\"We've tested this thing to death. Skip the last regression run. I'm not missing this date over a formality.\"</span>"],
  opts:[
   {t:"Skip the regression run as Elena asks, and watch closely after go-live.",s:0,d:{trust:-3,conf:-2,health:-6},
    after:"The skipped cycle would have caught a bug in the new audit trail code. It shows up on day two, at Greeley.",
    why:"Quietly accepting a risk the sponsor doesn't fully understand isn't respecting the sponsor. It's skipping your job. Quality gets built in, and a sponsor deserves the data before deciding to cut it."},
   {t:"Show Elena the risk, and offer a two-day test of the critical clinical paths.",s:3,d:{trust:2,conf:5,health:5},best:true,
    after:"Sam shows her the change log: the audit trail code is new and touches every note. Priya proposes testing the twenty workflows nurses use most, which fits in two days. Elena agrees. The test finds one bug, in the audit trail, and it's fixed by Friday.",
    why:"Don't refuse and don't just comply. Make the risk visible with data, offer a tailored option, and let the sponsor make an informed decision. Risk-based testing is a legitimate way to protect both quality and the date."},
   {t:"Refuse to sign off and tell Elena you'll raise it with the board if she insists.",s:0,d:{trust:-1,conf:-6,health:1},
    after:"Elena goes very quiet. Ruth hears about it before Sam can call her.",
    why:"Threatening to escalate over the sponsor's head before you've offered options damages the relationship you need. Escalation is a last resort after collaboration fails."},
   {t:"Run the full regression cycle overnight with the Kraków team to finish in time.",s:1,d:{trust:-2,conf:1,health:2},
    after:"Kraków works three straight nights. The cycle finishes. Two of the testers quit the following week.",
    why:"Crashing the schedule can work, but not by burning out a team without asking them or telling the sponsor the cost. Look for options that don't hide the tradeoff."}
  ]},
 {id:"c5s9", domain:"Business Environment", task:"Run the go/no-go decision",
  text:s=>["Friday of week fourteen. Ochoa and Elena at the head of the table, everyone else around it. Seven of the eight criteria are green.","The eighth is training. Fort Collins and Greeley are above eighty-five percent. Cheyenne is at seventy-eight. "+(s.flags.listened?"Denise Harmon is in the room. Her champions have been training nurses on every shift, and she thinks they'll pass eighty-five by Sunday.":"Nobody from Cheyenne is in the room.")],
  opts:[
   {t:"Report Cheyenne as on track, since its champions expect to hit the target by Monday.",s:0,d:{trust:-2,conf:-6,health:-2},
    after:"The meeting is short and happy. On Monday, Cheyenne has the most support calls of the three hospitals, and Ochoa finds out the number was seventy-eight.",
    why:"Reporting a forecast as a fact misleads the people making the decision. Show the real status against the criteria and let them weigh it."},
   {t:"Present each criterion as it stands, with Cheyenne's gap and a plan to close it.",s:3,d:{trust:2,conf:7,health:3},best:true,
    after:"Sam puts the eight criteria on the screen, Cheyenne in amber, with the mitigation: champions training through the weekend and two extra Halcyon staff on the Cheyenne floors all week. Ochoa and Elena talk for five minutes. Go, all three hospitals.",
    why:"Transparent reporting against agreed criteria, plus a mitigation for the gap, gives the decision makers what they need. The decision belongs to the people named as decision makers, not the PM."},
   {t:"Recommend going live at Fort Collins and Greeley, and holding Cheyenne a week.",s:1,d:{trust:0,conf:1,health:1},
    after:"Ochoa considers it, then asks what holding Cheyenne does to the nurses who've been training for three weeks.",
    why:"A recommendation is fine, but leading with one option skips the mitigation that might close the gap. Lay out the status and the options, then let the decision makers choose."},
   {t:"Postpone the decision a week so all three hospitals can meet every criterion.",s:0,d:{trust:-1,conf:-3,health:-2},
    after:"Elena points out that postponing misses the contract date for all three hospitals over a gap at one.",
    why:"Criteria inform the decision, they don't make it. Postponing everything for one amber item with a credible mitigation isn't your call, and it isn't proportional."}
  ]},
 {id:"c5s10", domain:"Process", task:"Run hypercare",
  text:s=>["Monday, 4 AM. The agents switch on. By 9 AM there are forty-one support tickets. Most are small. Three are about the agents slowing down badly at shift change, when every nurse logs in at once.","Grant wants to post the go-live on LinkedIn. Priya wants to fix the slowdown directly in production, right now."],
  opts:[
   {t:"Let Priya fix the slowdown directly in production now, since nurses are waiting.",s:0,d:{trust:1,conf:-2,health:-4},
    after:"Priya's fix works at Greeley and breaks login at Cheyenne for twenty minutes.",
    why:"Urgent fixes still need control. Use the emergency change process, test where you can, and know how to back it out. Hypercare doesn't suspend change management."},
   {t:"Run hypercare: triage by severity, daily calls with Cascade, and exit criteria.",s:3,d:{trust:3,conf:5,health:5},best:true,
    after:"Sam opens a war room channel and a twice-daily call with Cascade's command center. The slowdown is triaged as high. Priya ships a tested fix through the emergency change process by Tuesday afternoon. Hypercare ends after ten days, when tickets drop below the agreed threshold.",
    why:"Hypercare is a planned period of heightened support with clear triage, communication, and criteria for handing off to normal support. It's part of transition, and it ends on agreed terms, not when everyone's exhausted."},
   {t:"Route all tickets to Cascade's help desk, since go-live means the system is theirs.",s:0,d:{trust:0,conf:-5,health:-3},
    after:"Cascade's help desk has never seen the system. Tickets pile up. Ochoa calls Sam by noon.",
    why:"Transition to operations happens after support teams are ready and the hypercare period ends, not at the moment of go-live."},
   {t:"Keep the full project team on support until every open ticket has been closed.",s:1,d:{trust:-2,conf:2,health:1},
    after:"The team stays on support for three weeks. The rollout to the next eight hospitals starts slipping.",
    why:"Support is right; open-ended support isn't. Hypercare needs exit criteria so the team can move on and normal support can take over."}
  ]}
 ],
 closing:s=>[
  "Monday, 6 AM, Fort Collins. Sam watches the first day-shift nurse open a patient's chart, read the agent's draft, change two words, and sign it. It takes her ninety seconds. She doesn't look up.",
  "Ochoa texts at 7:15. <span class=\"said\">\"Three hospitals. On the date. Thank you.\"</span>",
  "Ruth calls that evening. <span class=\"said\">\"At NASA, launch day was never the end,\"</span> she says. <span class=\"said\">\"It was the start of the part where everyone stops watching. That's when you find out who actually built a program.\"</span>",
  (s.score>=24?"<span class=\"said\">\"You kept your head every time someone asked you to lose it,\"</span> she adds. <span class=\"said\">\"That's the job.\"</span>":"<span class=\"said\">\"You got there,\"</span> she adds. <span class=\"said\">\"Next time, put the facts in front of people sooner. Pressure goes away when the numbers are on the table.\"</span>"),
  "Tuesday morning there are two emails waiting. One is from LabelForge's finance team: a final invoice, and a note disputing the late delivery penalty. The other is from Elena. <span class=\"said\">\"Come see me when hypercare is done. I want to talk about what's next for you.\"</span>"
 ],
 videos:{
  c5s1:["84u5faiWDwM","How to Overcome Resistance in Project Change Management","Adriana Girdler","9:05"],
  c5s2:["fpSM6inJuRw","Project Manager's Guide to Change Management","Advisicon","14:39"],
  c5s3:["jZlPDyamGoM","Go/No-Go Decisions in Business Analysis and Project Management","InterfaceTT","7:13"],
  c5s4:["JVzvohTJLMo","Cut Over/Go Live Planning","The PMO Strategy And Execution Hub","4:09"],
  c5s5:["X4lPEpATNxg","The Six Phases of Incident Response","Ascend Technologies","5:40"],
  c5s6:["waCz0cI47G4","PMP Exam Rule Book 5: Managing Compliance on Projects","Praizion","4:01"],
  c5s7:["NC8WrPFyoeE","What is Benefits Management?","Mike Clayton","3:49"],
  c5s8:["F7Cs4CQLoqg","Cost of Quality (Cost of Conformance and Non-Conformance)","PMC Lounge","6:50"],
  c5s9:["iedacIdty8Y","Governance Confusion on Your PMP Exam? The Decision Rights Trap","Steven | PMP + AI","7:57"],
  c5s10:["SOIV3jKjQTE","Planning Solutions Implementation: Part 9, Hypercare","PMsquare","4:20"]
 },
 deeper:["LcZvGRTJnLo","The Complete Project Management Body of Knowledge in One Video (PMBOK Guide 8th Edition)","David McLachlan","1:15:03"],
 episode:{src:"audio/ch5-go-live.mp3",len:"about 20 minutes"},
 next:"Closeout"
});
