// Chapter 6. Schema: see chapters/ARC.md (num, title, opening[], scenes[], closing(s), videos{}, deeper[], episode{}).
(window.HALCYON=window.HALCYON||[]).push({
 num:6, title:`Closeout`,
 cast:[
  [`Marcus Bell`,`Head of customer support at Halcyon. Inherits Cascade after go-live.`],
  [`Joan Pruitt`,`Procurement lead at Halcyon. Reads every contract twice.`]
 ],
 opening:[
  `On the Monday of week fifteen, three Cascade hospitals were running Halcyon's agents and nobody had called Sam at two in the morning. That was the whole celebration. Somebody brought donuts. Priya ate two and went back to the hypercare dashboard.`,
  `Ruth had sent a text on go-live night. <span class="said">"Splashdown isn't the end of a mission. Recovery is. Get some sleep."</span> Sam had read it four times and slept five hours, which felt like a vacation.`,
  `Eight hospitals were still waiting. Phase one wasn't done until all eleven were live, Cascade had signed off, the support team owned the system, and the vendors were paid and closed out. Elena wanted the whole thing wrapped by the end of week eighteen. The board met that Friday.`,
  `Sam opened a new page in his notebook and wrote one word at the top. <span class="said">"Finish."</span>`
 ],
 scenes:[
 {id:`c6s1`, domain:`Process`, task:`Plan the remaining rollout waves`,
  text:s=>[`The plan said eight hospitals over four weeks, in three waves. Wave one had gone well, but not perfectly. The night shift at one site never got its training, and a printer driver at another kept two nursing units on paper for a day.`,`Grant stops by with coffee and a pitch. <span class="said">"The first three went great. Let's flip all eight next Monday. The board will love it."</span>`],
  opts:[
   {t:`Roll all eight hospitals live next Monday, since the first three went smoothly.`,s:0,d:{trust:-4,conf:-3,health:-6},
    after:`Eight hospitals go live on the same morning. Five of them have the night shift training gap from wave one, and Marcus's support line takes ninety calls before noon. Two hospitals ask to roll back.`,
    why:`One good result doesn't remove the risk, it just hides it. The lessons from wave one hadn't been applied yet, and going big bang multiplies every gap by eight. Use what the last phase taught you before you scale.`},
   {t:`Run the next waves on the same go/no-go criteria, folding in lessons from wave one.`,s:3,d:{trust:3,conf:4,health:6},best:true,
    after:`Sam adds two items to the go/no-go checklist: night shift training confirmed, and every printer and device model tested on site. Wave two goes live on schedule with four hospitals. The support line takes eleven calls.`,
    why:`This is progressive elaboration in practice. Keep the criteria that worked, add what the first wave taught you, and plan each wave in more detail as it gets closer. Capturing lessons during the project, not only at the end, is what makes the next phase better.`},
   {t:`Keep the four-week plan exactly as written, with no changes from what wave one taught.`,s:1,d:{trust:0,conf:1,health:1},
    after:`The waves hold their dates. So do the problems. The night shift at wave two's largest hospital has the same training gap, and Sam watches the same calls come in.`,
    why:`Sticking with a phased plan is right, so this isn't a disaster. But a plan that ignores what you just learned is a plan you've stopped managing. Lessons learned are only worth something if they change the next piece of work.`},
   {t:`Let each hospital's IT team set its own go-live date once they feel ready for it.`,s:0,d:{trust:1,conf:-4,health:-4},
    after:`Two hospitals pick the same week as Cascade's annual audit. One never picks a date at all. Ochoa calls to ask who's running the rollout.`,
    why:`Local readiness matters, but someone still has to own the integrated plan. Handing the schedule to eight separate teams gives up the coordination that is the PM's job.`}
  ]},
 {id:`c6s2`, domain:`Process`, task:`Get formal acceptance`,
  text:s=>[`By the end of week seventeen all eleven hospitals are live. Ochoa emails that he's ready to sign the acceptance certificate, which also triggers Halcyon's final milestone payment.`,`There's one open defect. At the Rawlins hospital, notes from an older handheld device sometimes land in the wrong section of the chart. A nurse catches it each time. Priya has a fix planned for the next release, three weeks out.`],
  opts:[
   {t:`Check the defect against the acceptance criteria with Ochoa before he signs.`,s:3,d:{trust:1,conf:6,health:3},best:true,
    after:`Sam and Ochoa walk through the criteria together. The defect is minor under the agreed definition, has a workaround, and has a fix date. Ochoa signs with the defect listed on the certificate and the fix date beside it. Nobody is surprised later.`,
    why:`Acceptance is measured against the acceptance criteria you agreed on, not against perfection and not against how eager anyone is to sign. Be open about known defects, document any conditions, and get the acceptance in writing. That's validating scope.`},
   {t:`Get Ochoa's signature now while he's willing, and fix the defect under warranty.`,s:0,d:{trust:-1,conf:-5,health:-1},
    after:`Ochoa signs. Two weeks later his chief nursing officer asks why a known charting defect wasn't mentioned at sign-off. Ochoa forwards the question to Elena.`,
    why:`Taking a signature while holding back a known issue saves a week and spends trust you can't easily earn back. Transparency at acceptance is not optional, even when the defect is small.`},
   {t:`Hold the sign-off until every known defect is fixed, however minor it turns out.`,s:1,d:{trust:0,conf:-1,health:-2},
    after:`Ochoa agrees to wait. The final payment slips a month, Elena is unhappy, and the defect turns out to be one Cascade would have accepted.`,
    why:`Your caution is honest, which counts. But the acceptance criteria decide what's acceptable. If a minor defect meets the agreed criteria with a documented fix, holding acceptance for it just delays value and payment.`},
   {t:`Ask Grant to handle acceptance, since the signature triggers his final invoice.`,s:0,d:{trust:-1,conf:-3,health:-1},
    after:`Grant sends Ochoa a DocuSign link with a friendly note. The defect isn't mentioned. Ochoa calls Sam to ask what he's signing.`,
    why:`The commercial side cares about the invoice. Acceptance is about whether the deliverables meet the criteria, and the person accountable for delivery should walk the customer through it.`}
  ]},
 {id:`c6s3`, domain:`Process`, task:`Transition to operations`,
  text:s=>[`Marcus Bell runs customer support at Halcyon. His team will own Cascade once the project closes. In week sixteen he tells Sam his people have never seen the system outside a sales demo.`,`Lena has a simpler idea. <span class="said">"The engineers built it. Let them keep supporting it. It's easier."</span> The engineers, who have phase two waiting, do not think it's easier.`],
  opts:[
   {t:`Have the engineering team keep supporting Cascade, since they know the system best.`,s:0,d:{trust:-5,conf:0,health:-4},
    after:`The engineers become the support desk. Phase two starts late because its team is answering tickets about printer drivers.`,
    why:`A project has to end, and ending means operations owns what you built. Leaving the project team on support indefinitely blocks the next work and never builds the support capability the customer needs.`},
   {t:`Agree a handover plan with Marcus: training, runbooks, and a hypercare exit date.`,s:3,d:{trust:4,conf:3,health:6},best:true,
    after:`Priya's runbook becomes the core of it. Marcus's team shadows the engineers for two weeks, then the engineers shadow them for one. On the exit date Marcus signs the handover checklist himself.`,
    why:`Transition is a planned deliverable, not a forwarded email. Agree the criteria with the receiving team, transfer knowledge with training and documentation, and set a clear point where ownership moves. The receiving team confirms they're ready.`},
   {t:`Send Marcus the runbook Priya wrote and set his team as owners starting Monday.`,s:1,d:{trust:-1,conf:0,health:1},
    after:`Marcus's team owns it on Monday. By Wednesday they've escalated nine tickets back to engineering because the runbook assumes things they don't know.`,
    why:`The runbook is the right asset and setting an owner is the right instinct. But documentation alone isn't a handover. The receiving team needs training and a chance to confirm they're ready before you walk away.`},
   {t:`Extend hypercare by a month so support has more time to watch the engineers work.`,s:0,d:{trust:-2,conf:1,health:-3},
    after:`Hypercare runs another month. Marcus's team watches. Nobody plans when they'll actually take over, so at the end of the month they still haven't.`,
    why:`More time without a plan doesn't create readiness. Hypercare needs exit criteria and a handover plan, or it just becomes the project that never closes.`}
  ]},
 {id:`c6s4`, domain:`Process`, task:`Settle the vendor claim`,
  text:s=>[`LabelForge delivered all three batches. The data was good. The last batch landed seventeen days late, and their final invoice is for the full contract price.`,`Joan Pruitt from procurement points out the late delivery clause: a credit for each week late. LabelForge's account manager points out something else. In week six Halcyon changed the labeling guide halfway through a batch. It's in the change log.`],
  opts:[
   {t:`Pay the full invoice to keep the relationship, since the data turned out to be good.`,s:0,d:{trust:0,conf:-1,health:-3},
    after:`LabelForge is delighted. Joan is not. At the next procurement audit she has to explain why a contract remedy was ignored with no record of the decision.`,
    why:`Good relationships matter, but waiving contract terms with no documented reason isn't relationship management, it's a gap in procurement control. Decisions about claims need a record.`},
   {t:`Withhold the whole final payment until LabelForge agrees to the full late credit.`,s:1,d:{trust:0,conf:0,health:-1},
    after:`LabelForge pushes back hard and cites the labeling guide change. The dispute drags for six weeks and the contract stays open the whole time.`,
    why:`Enforcing the contract is legitimate, and you were right to use the clause. But ignoring the delay your own side caused makes the claim weaker and slower. Look at the whole record before you take a position.`},
   {t:`Review the record with Joan, net out the delay Halcyon caused, and settle the claim.`,s:3,d:{trust:1,conf:3,health:4},best:true,
    after:`The change log shows the guide change cost LabelForge about a week. Joan applies the credit for the other ten days. LabelForge accepts in one call. Joan issues the formal closure notice and files the procurement audit notes.`,
    why:`That's claims administration done right. Use the documentation, account for changes the buyer caused, and settle by negotiation where you can. Then close the contract formally: final payment, written closure, and an audit of what went well and what didn't.`},
   {t:`Hand the dispute to Halcyon's lawyers so the late clause is enforced to the letter.`,s:0,d:{trust:0,conf:-2,health:-2},
    after:`Legal sends a letter. LabelForge sends a longer letter. The cost of the lawyers' time passes the value of the credit in week two.`,
    why:`Litigation and formal disputes are the last resort for claims. Negotiation comes first, and here the facts were clear enough to settle in a day.`}
  ]},
 {id:`c6s5`, domain:`People`, task:`Run lessons learned without blame`,
  text:s=>[`Sam schedules a lessons learned session for the whole team. Grant asks to be added and sends an agenda of his own: <span class="said">"What IronPeak and LabelForge did wrong."</span>`,`Priya tells Sam quietly that people are nervous. The burn-in failure, the scope fight in week one, and Theo leaving are all still sore. Some of them expect to be blamed.`],
  opts:[
   {t:`Run it with the whole team, focused on process not people, and log every lesson.`,s:3,d:{trust:7,conf:1,health:3},best:true,
    after:`Sam opens by naming one of his own mistakes from week one. The room loosens. The team finds twelve lessons, including three about how Halcyon sells deals, and they go into the company's lessons learned register with owners.`,
    why:`Lessons learned look at what happened and why, not at who to blame. Include the people who did the work, make it safe to be honest, record the lessons, and put them where the next project will find them.`},
   {t:`Send an anonymous survey instead, so nobody feels exposed in a room together.`,s:1,d:{trust:1,conf:0,health:1},
    after:`The survey comes back with honest answers and no follow-up. Nobody can ask what a comment meant, and half the lessons are one line long.`,
    why:`Anonymous input can help when trust is low, so this isn't wrong. But the discussion is where the real causes come out. A survey can feed the session, not replace it.`},
   {t:`Let Grant run it, since he has the customer view and the vendor history.`,s:0,d:{trust:-6,conf:0,health:-2},
    after:`Grant spends forty minutes on vendors. The engineers say nothing. The lessons register gets three entries, all about other companies.`,
    why:`A session pointed at blaming vendors teaches nothing about your own process, and it tells the team the meeting isn't safe. The PM facilitates so every voice is heard.`},
   {t:`Hold it after phase two starts, once people have had time to reflect on it.`,s:0,d:{trust:-1,conf:0,health:-2},
    after:`Phase two starts. The session gets moved twice. By the time it happens, half the details are gone and two of the contractors have left.`,
    why:`Lessons fade fast and people move on. Capture them throughout the project and hold the final session at closeout, while the team is still together and memories are fresh.`}
  ]},
 {id:`c6s6`, domain:`People`, task:`Release the team`,
  text:s=>[`The offshore contractors' terms end in week eighteen. Priya and three engineers are wanted for phase two and another customer.`,`Lena messages Sam on Thursday. <span class="said">"I'm moving Priya and the others Monday. Phase two needs them."</span> Marcus's handover still has a week to run.`],
  opts:[
   {t:`Let Lena move the engineers Monday, since phase two needs them more right now.`,s:0,d:{trust:-2,conf:-1,health:-5},
    after:`The engineers move Monday. Marcus's team loses its shadows halfway through the handover, and Cascade's tickets start bouncing between two teams.`,
    why:`Releasing people before the work they're needed for is finished pushes the risk onto the customer. Release resources as the project closes, in a planned way.`},
   {t:`Agree release dates with Lena tied to handover, and write each person's feedback.`,s:3,d:{trust:6,conf:1,health:4},best:true,
    after:`Lena agrees to a Wednesday release instead of Monday. Sam writes a short note on each person for their manager, specific about what they did. Priya reads hers twice.`,
    why:`Releasing team members is a planned part of closing. Coordinate with the functional managers in a matrix organization, tie the dates to the work, and give performance input on each person so their contribution follows them.`},
   {t:`Keep the whole team on Cascade through week eighteen in case anything breaks.`,s:0,d:{trust:-1,conf:0,health:-2},
    after:`The team sits on a quiet project for two weeks. Phase two's kickoff slips and Lena stops returning Sam's messages.`,
    why:`Holding resources you don't need hurts the rest of the organization. Keep what the remaining work requires and release the rest on a plan.`},
   {t:`Release the offshore contractors first, since they cost the most per hour.`,s:1,d:{trust:0,conf:0,health:1},
    after:`The contractors finish on their contract dates. It saves money. It doesn't answer Lena's question about the engineers.`,
    why:`Following the contract dates is fine, and cost is a fair factor. But it dodges the real decision, which is how to release the core team without breaking the handover.`}
  ]},
 {id:`c6s7`, domain:`People`, task:`Recognize the team`,
  text:s=>[`Elena drafts a company-wide email. The subject line is <span class="said">"Congratulations to Sam and his team!"</span> She sends it to Sam first and asks if he wants to add anything.`,`Sam thinks about the people who carried this. Priya, who learned Theo's job in three weeks. The nurse annotators LabelForge brought in. An offshore engineer who stayed up through a cutover at 3 AM his time. Marcus's team, who are just starting.`],
  opts:[
   {t:`Let Elena's email stand, since public thanks from the CEO means the most.`,s:1,d:{trust:1,conf:1,health:0},
    after:`The email goes out. It's nice. Priya's name isn't in it, and the offshore engineer isn't on the company mailing list.`,
    why:`CEO thanks are worth having, so this is half right. But generic thanks that lead with the PM's name miss the people who did the work. Recognition works when it's specific.`},
   {t:`Give every team member the same gift card so nobody feels left out of it.`,s:0,d:{trust:-1,conf:0,health:0},
    after:`Everyone gets fifty dollars. Some say thanks. It's forgotten by Friday.`,
    why:`Identical rewards are fair on paper, but they don't tell anyone what they did that mattered. Recognition should be tied to real contributions.`},
   {t:`Thank people by name for specific work, in the way each of them prefers.`,s:3,d:{trust:7,conf:1,health:1},best:true,
    after:`Sam rewrites Elena's draft around the team, with names and what each person did. Priya gets a public mention at the all-hands. The offshore engineer gets a call from Elena herself, which he asked Sam about afterward, twice.`,
    why:`Recognize specific contributions, include everyone who did the work, contractors too, and fit the recognition to the person. Some people want the stage and some want a quiet word. A servant leader points the credit at the team.`},
   {t:`Ask Elena to thank Sam by name, since he carried the project to the finish.`,s:0,d:{trust:-6,conf:0,health:0},
    after:`Elena does. The team reads it. Somebody screenshots it into a private chat with an eye-roll emoji.`,
    why:`Taking the credit costs the trust you spent eighteen weeks building. The leader's job at the finish is to make sure the team gets seen.`}
  ]},
 {id:`c6s8`, domain:`Business Environment`, task:`Hand off benefits realization`,
  text:s=>[`The point of Cascade's investment was never the software. It was nurses spending less time on documentation and less charting after their shifts. Some of that shows up in weeks. Most of it takes a year to prove.`,`The project ends in week eighteen. Somebody has to keep measuring after that.`],
  opts:[
   {t:`Keep measuring benefits himself every quarter, even after the project closes.`,s:0,d:{trust:0,conf:1,health:-2},
    after:`Sam does it for one quarter. Then the new role starts, the spreadsheet goes stale, and nobody at Cascade knows it exists.`,
    why:`The project ends, but benefits keep arriving long after. The PM can't own them forever. They need an owner in the business that gets the value.`},
   {t:`Hand the benefits measures to an owner at Cascade, with the baseline and targets.`,s:3,d:{trust:1,conf:5,health:3},best:true,
    after:`Cascade's chief nursing officer agrees to own the measures. Sam hands over the baseline, the twelve-month targets, and how each number is pulled. Halcyon commits to sending the system data each quarter.`,
    why:`Benefits realization belongs to the business that receives the benefit. Transfer the measures, baseline, targets, and timing to a named owner, and agree what the delivering side still provides. That's how value gets tracked past closeout.`},
   {t:`Report the pilot results as final, since the numbers already look strong.`,s:0,d:{trust:0,conf:-3,health:-1},
    after:`The board slide says the project delivered. Six months later Cascade's finance team asks whether the savings held. Nobody knows.`,
    why:`Early results aren't realized benefits. Calling them final stops the measurement right when the real answer starts to show up.`},
   {t:`Leave benefits tracking to Grant, since renewals depend on proving value.`,s:1,d:{trust:0,conf:1,health:0},
    after:`Grant tracks the numbers that help the renewal. The ones that don't look good stop appearing in his decks.`,
    why:`Halcyon does have a real interest in proving value, so involving Grant isn't wrong. But the benefits are Cascade's, and the owner should be someone who'll report them straight.`}
  ]},
 {id:`c6s9`, domain:`Business Environment`, task:`Start phase two the right way`,
  text:s=>[`Ochoa signs the change order for discharge instructions, the request that started as a promise on a sales call in week one.`,`Grant is thrilled. <span class="said">"Same team, same backlog, keep the sprints rolling. Why stop?"</span> It's a fair question. The team is warm and the code base is fresh.`],
  opts:[
   {t:`Treat phase two as its own project, with a business case and a new charter.`,s:3,d:{trust:2,conf:4,health:4},best:true,
    after:`Sam drafts a one-page business case and a charter with Elena as sponsor. It takes three days. It also surfaces that discharge instructions need a clinical safety review the first release never had.`,
    why:`New scope with its own contract, budget, and risks is a new project. A business case confirms the value and a charter authorizes the work and the PM. Starting clean is what lets you find the new risks before you're in the middle of them.`},
   {t:`Add discharge instructions to the current backlog and keep the same team going.`,s:1,d:{trust:1,conf:0,health:-2},
    after:`The sprints keep rolling. Three weeks in, a clinician asks who approved the safety review process. Nobody did, because nobody planned one.`,
    why:`Continuous delivery with a stable team is good agile practice, so this is half right. But this work has a separate contract and new risks, and it needs its own authorization and plan.`},
   {t:`Start building now and write the charter later, while the momentum is there.`,s:0,d:{trust:0,conf:-2,health:-3},
    after:`The team builds for two weeks. Then Elena asks what the budget is. There isn't one.`,
    why:`This is chapter one again. Work without a charter has no defined authority, no success measures, and no sponsor. Momentum doesn't replace authorization.`},
   {t:`Wait to plan phase two until phase one is fully closed and the team has rested.`,s:0,d:{trust:1,conf:-2,health:-1},
    after:`The team rests. Cascade's nursing leaders, who were excited, start asking whether Halcyon still wants the work.`,
    why:`Closing one project and initiating the next can overlap. Waiting to even begin planning burns time and goodwill the customer gave you.`}
  ]},
 {id:`c6s10`, domain:`Business Environment`, task:`Close the project formally`,
  text:s=>[`Friday of week eighteen. Elena calls Sam in. She wants him to build Halcyon's delivery practice, a new role, Director of Delivery, starting Monday.`,`Then she adds, <span class="said">"And skip the closeout report. Everyone knows how it went."</span>`],
  opts:[
   {t:`Start the new role Monday and let the closeout report wait until things calm down.`,s:0,d:{trust:0,conf:-2,health:-4},
    after:`Things never calm down. The project files stay scattered across three drives. In a year, when someone asks how Cascade was delivered, the answer is a shrug.`,
    why:`A project isn't closed until it's formally closed. Skipping it loses the record the organization needs, and in a new delivery practice it sets the wrong example on day one.`},
   {t:`Take the role, but close properly first: sign-offs, final report, and archive.`,s:3,d:{trust:2,conf:5,health:5},best:true,
    after:`Sam asks for one week. He confirms every acceptance and contract closure is signed, writes a four-page final report, archives the project files where the next PM will find them, and gets Elena's sign-off. Then he starts the new job.`,
    why:`Closing means confirming acceptance, closing contracts, releasing resources, archiving records, writing the final report, and getting the sponsor's formal sign-off. It's short work that turns one project's experience into the organization's.`},
   {t:`Turn the role down, since leaving before phase two starts would hurt the team.`,s:0,d:{trust:1,conf:-1,health:0},
    after:`Elena looks surprised. She offers the role to someone else, who has never run a project.`,
    why:`Loyalty is admirable, but this isn't the decision in front of you. The PM question is how to close properly, not whether to grow.`},
   {t:`Ask Priya to write the closeout report, so Sam can start the new job Monday.`,s:1,d:{trust:1,conf:0,health:1},
    after:`Priya writes a good report. It's missing the commercial history and the sponsor decisions she was never in the room for.`,
    why:`Delegating parts of closing is fine and good for Priya's growth. But the PM stays accountable for formal closure and the sponsor sign-off, and some of it only the PM can write.`}
  ]}
 ],
 closing:s=>[
  `The board meeting was short. Elena showed one slide with eleven hospitals on it, all green. Grant thanked the team by name, reading from a list Sam had sent him the night before.`,
  `Afterward Ruth found Sam in the hallway and walked him out to the parking lot. It was the first cold evening of the year.`,
  `<span class="said">"In Houston,"</span> she said, <span class="said">"when a mission ended, the flight director's last job was the debrief. Then you handed the room to the next team and walked out. Nobody clapped. The next crew needed the consoles."</span>`,
  (s.score>=24?`<span class="said">"You ran this like a flight director,"</span> she said. <span class="said">"You told the truth about the numbers, you listened before you decided, and you gave the credit away. That's the whole job."</span>`:`<span class="said">"You made some calls I'd have made differently,"</span> she said. <span class="said">"So did I, my first time in the chair. What matters is you can see them now. Write them down. The next person in your seat will need them."</span>`),
  `Sam asked her the question he'd been carrying since week one. Why she'd spent her Saturdays on a data center manager she'd never met.`,
  `Ruth laughed. <span class="said">"Somebody did it for me. A flight director named Pete, my first year. He said he wasn't doing me a favor, he was paying a debt."</span> She unlocked her car. <span class="said">"You owe one now. Find somebody on their first launch."</span>`,
  `On Monday somebody had taped a paper sign to a conference room door. It said Delivery and it was crooked. Priya was already inside with the phase two charter printed out, still unsigned, and a question about the clinical safety review she'd been chewing on all weekend.`,
  `<span class="said">"Do we do the business case first or the safety stuff?"</span> she asked.`,
  `Sam sat down across from her. <span class="said">"Tell me what you've got so far,"</span> he said, and then he didn't say anything for a while.`
 ],
 videos:{
  c6s1:[`PwESbblSdQ0`,`Agile Practice Guide: Rolling Wave Planning`,`David McLachlan`,`4:44`],
  c6s2:[`yNRO3tajQCE`,`5.5 Validate Scope`,`David McLachlan`,`11:44`],
  c6s3:[`OLibddcR3Yg`,`Project Handover Process`,`Adriana Girdler`,`8:08`],
  c6s4:[`EuWaxT2o-iE`,`Claims Administration: Key Concepts in Project Management`,`David McLachlan`,`2:36`],
  c6s5:[`cemERTeeQ7M`,`Lessons Learned Meeting: How to Make it Excellent`,`Mike Clayton`,`12:51`],
  c6s6:[`SsFUw1u0kxo`,`How to Transition People Off a Project`,`ProjectManager`,`2:48`],
  c6s7:[`ehyBnuCpOhY`,`Team Performance Assessments: Recognition and Rewards`,`PMC Lounge`,`7:39`],
  c6s8:[`NC8WrPFyoeE`,`What is Benefits Management?`,`Mike Clayton`,`3:49`],
  c6s9:[`c95wGysj9Nc`,`What is a Business Case?`,`Mike Clayton`,`4:43`],
  c6s10:[`29M-mDQAoQQ`,`4.7 Close Project or Phase`,`David McLachlan`,`11:50`]
 },
 deeper:[`LcZvGRTJnLo`,`The Complete Project Management Body of Knowledge in One Video (PMBOK Guide 8th Edition)`,`David McLachlan`,`1:15:03`],
 episode:{src:`audio/ch6-closeout.mp3`,len:`about 20 minutes`}
});
