(((window.HALCYON_DATA=window.HALCYON_DATA||{}).pilot=window.HALCYON_DATA.pilot||{}).full=window.HALCYON_DATA.pilot.full||[]).push({
  num: 1, part: `Part One: The Share`, title: `Discovery Flight`, weeks: `April`,
  tasks: [`I.A`,`I.G`,`I.H`,`II`,`V`,`IX`],
  cast: [
    [`Russ Kim`,`The fourth partner. Travels for work. Lives in the club group chat.`],
    [`Biscuit`,`N4791E, a 1978 Cessna 172N. Sticky fuel selector, a door that pops on rotation, a tach that reads 50 RPM high.`]
  ],
  opening: [
    `The lawyer read the will in a conference room that smelled like carpet glue, and the part about the airplane took eleven seconds.`,
    `<prop type="doc" title="Last will of Daniel A. Reyes, article six">To my brother Jordan, my one quarter share in the Hangar Six Flying Club and the aircraft N4791E, with my logbook and my headset if Marisol can find it. Learn to fly it or sell it to Walt. Don't let it sit.</prop>`,
    `Claire laughed once, the short tired laugh she'd been using since March, and then put her hand over her mouth. Their mother looked at the table. Jordan looked at the sentence until it stopped being words.`,
    `Danny had been forty one. He'd collapsed on the sideline of a U10 soccer game in Parker on a bright Saturday morning, cheering for Ellie, and he'd been gone before the ambulance got out of the parking lot. Sudden cardiac arrest, the doctor said, the kind nobody sees coming, the kind that has nothing to do with anything you did. The airplane had nothing to do with it either. Jordan kept having to remind people of that, and then kept having to remind himself.`,
    `Jordan was thirty five. He estimated commercial HVAC jobs for a mechanical contractor in Aurora, which meant he read drawings for a living and found the thing the architect forgot. He was good at it. He was the brother who did the sensible things. Danny was the brother who called from Moab at midnight to say he'd landed on a dirt strip and you should've seen it.`,
    `In the parking lot after the reading, his phone buzzed. A number he didn't have saved.`,
    `<prop type="text" from="Walt Herrera" time="4:41 PM">Jordan, this is Walt Herrera from Hangar Six. I'm sorry about your brother. He was a good man and a better partner. I'll be straight with you because Danny would want that. The club agreement gives you a year. I'll buy the share back at book value today if you want, no hard feelings. Call me when you're ready.</prop>`,
    `Jordan read it twice. Then he did something he could only explain later as stubbornness. He searched "discovery flight Centennial Airport," found a club page with a photo of a white and maroon Cessna he'd seen in a hundred of Danny's texts, and booked the first open Saturday with an instructor named Abby Strand.`,
    `He told himself he was doing it so he could say no with a clear conscience. You can't turn something down properly if you've never looked at it.`
  ],
  lesson: {
    title: `Abby's Ground School: what you're signing up for`,
    sections: [
      { h: `The road to a private pilot certificate`,
        body: [`Abby met him at the club's briefing room, which was a folding table, a whiteboard, and a coffee maker older than she was. She drew a line across the board and put a box at each end. <span class="said" data-who="Abby">"Left box, you. Right box, private pilot. Everything in between is paperwork, money, and about sixty hours of being wrong in an airplane."</span>`,
          `The first piece is the student pilot certificate. You apply through the FAA's online system, IACRA, usually with your instructor, and the certificate comes in the mail a few weeks later. You need to be at least 16 to get one for airplanes and able to read, speak, write, and understand English. You can take lessons before it arrives. You can't fly solo without it.`,
          `The second piece is the medical certificate. To fly solo, a student pilot needs at least a third class medical, issued by an aviation medical examiner, called an AME, after you fill out the application online in MedXPress. A third class medical is what a private pilot needs. If you're under 40 on the day of the exam, it's good through the last day of the 60th month after the month of the exam. At 40 or older, the 24th month. <span class="said" data-who="Abby">"Get the medical first,"</span> Abby said. <span class="said" data-who="Abby">"Before you spend three thousand dollars. If anything in your history needs a closer look, you want to know now."</span>`,
          `To be eligible for the private certificate itself, 14 CFR 61.103 says you must be at least 17, meet the English requirement, pass the knowledge test, pass the practical test, called the checkride, and meet the experience requirements. Those are in 61.109: at least 40 hours of flight time, including at least 20 hours of flight training from an authorized instructor and at least 10 hours of solo flight. Inside those numbers sit specific requirements: 3 hours of cross country training, 3 hours of night training with one night cross country over 100 nautical miles total and 10 night takeoffs and full stop landings, 3 hours of flying by reference to instruments, 3 hours of checkride prep within the preceding 2 calendar months, 5 hours of solo cross country, one solo cross country of at least 150 nautical miles total with full stop landings at three points and one leg of at least 50 nautical miles, and 3 solo takeoffs and full stop landings at an airport with an operating control tower.`,
          `<span class="said" data-who="Abby">"Forty is a legal minimum, not a prediction,"</span> she said. <span class="said" data-who="Abby">"Most people take more. Nobody gets a prize for forty."</span> Schools that train under Part 141 have an FAA approved syllabus and a 35 hour minimum. Clubs and independent instructors like Abby train under Part 61. Either way you take the same knowledge test and the same checkride.`],
        terms: [[`IACRA`,`The FAA's online system for airman certificate applications, including the student pilot certificate.`],[`AME`,`Aviation medical examiner. A physician designated by the FAA to issue medical certificates.`],[`Third class medical`,`The medical certificate a private pilot needs. Valid 60 calendar months if you're under 40 at the exam, 24 if you're 40 or older.`],[`Part 61 and Part 141`,`Two ways to train. Part 141 schools follow an FAA approved syllabus with a 35 hour private minimum. Part 61 training has a 40 hour minimum.`]],
        exam: `Memorize 61.103 and 61.109. The test loves the numbers: 17 years old, 40 hours total, 20 dual, 10 solo, 150 nautical miles with three landings and one 50 mile leg, and 3 full stop landings at a towered field.` },
      { h: `Four forces`,
        body: [`Abby drew an airplane that looked like a fish and four arrows. Lift points up, perpendicular to the relative wind. Weight points down, toward the center of the earth. Thrust points forward, from the propeller. Drag points back, opposing motion through the air. In steady, unaccelerated flight, the forces are in balance: the sum of the upward forces equals the sum of the downward forces, and the sum of the forward forces equals the sum of the rearward forces. Change one, and the airplane accelerates, climbs, or descends until a new balance arrives.`,
          `<span class="said" data-who="Abby">"Pilots spend their whole lives managing these four,"</span> she said. <span class="said" data-who="Abby">"More power, more thrust. Pull back, more lift for a moment, then more drag. Every bag you throw in the back is weight. You'll see."</span>`],
        terms: [[`Lift`,`The aerodynamic force acting perpendicular to the relative wind.`],[`Drag`,`The force that resists the airplane's motion through the air.`],[`Steady flight`,`Unaccelerated flight, where the opposing forces are equal.`]],
        exam: `Watch the wording. In straight and level unaccelerated flight the opposing forces are equal. "Lift is greater than weight" describes a climb starting, not a steady climb.` },
      { h: `Parts of the airplane`,
        body: [`Biscuit has the five main parts every airplane has. The fuselage holds the people, the cargo, and the controls. The wings make lift; Biscuit's are mounted high and braced by struts. The empennage is the tail: the vertical stabilizer with the rudder hinged to it, and the horizontal stabilizer with the elevator hinged to it, and a small trim tab on the elevator. The landing gear on a 172 is fixed tricycle gear, a nose wheel and two mains. The powerplant is the engine and propeller, in Biscuit's case a carbureted four cylinder Lycoming with 160 horsepower.`],
        terms: [[`Empennage`,`The tail section: vertical and horizontal stabilizers, rudder, elevator, and trim tab.`],[`Tricycle gear`,`Landing gear with a nose wheel and two main wheels.`]],
        exam: `Expect a figure of an airplane with parts labeled by number. Know where the elevator, rudder, ailerons, flaps, and trim tab live.` },
      { h: `Three axes and the controls that move them`,
        body: [`An airplane rotates around three axes, and all three pass through the center of gravity. The longitudinal axis runs nose to tail; rotation around it is roll, controlled by the ailerons. The lateral axis runs wingtip to wingtip; rotation around it is pitch, controlled by the elevator. The vertical axis runs top to bottom; rotation around it is yaw, controlled by the rudder.`,
          `Turn the yoke left and the left aileron goes up while the right aileron goes down. The wing with the lowered aileron makes more lift, and it also makes more induced drag, which pulls the nose the wrong way, away from the turn. That's adverse yaw. You fix it by pressing the rudder pedal on the same side as the turn. That's coordinated flight, and the ball in the turn coordinator tells you whether you've got it. <span class="said" data-who="Abby">"Step on the ball,"</span> Abby said. <span class="said" data-who="Abby">"You'll hear me say that four hundred times."</span>`,
          `The trim tab relieves control pressure so you don't have to hold the yoke forward or back the whole flight. It moves opposite the elevator: to hold the nose down, the tab moves up, which pushes the elevator down. In Biscuit you turn a wheel between the seats. Fly the attitude you want, then trim until your hands can relax.`],
        terms: [[`Adverse yaw`,`The nose yawing away from the turn because the raised wing's lowered aileron makes more induced drag.`],[`Coordinated flight`,`Using rudder with aileron so the airplane doesn't slip or skid. The ball stays centered.`],[`Trim tab`,`A small movable surface on the elevator that relieves control pressure. It moves opposite the elevator.`]],
        exam: `Two classics: which axis does each control move (ailerons and roll, elevator and pitch, rudder and yaw), and which way the airplane yaws when you roll with ailerons alone (away from the turn).` },
      { h: `Your logbook`,
        body: [`A discovery flight with a certificated flight instructor is real flight training, and it can be logged as dual instruction received toward 61.109. You keep your own logbook, in your own name. The instructor writes the entry and signs it. <span class="said" data-who="Abby">"Buy the logbook,"</span> she said. <span class="said" data-who="Abby">"It's twelve bucks, and it's the only thing in aviation that is."</span>`],
        terms: [[`Dual instruction`,`Flight training received from an authorized instructor, logged by the student and signed by the instructor.`]],
        exam: `Training time from an authorized instructor counts toward the minimums when it's logged and signed. The pilot keeps the record; the instructor endorses it.` }
    ],
    video: [`iMaf0gG8yNc`,`How Airplanes Fly: The Four Forces of Flight`,`FLY8MA.com Flight Training`,`5:36`]
  },
  scenes: [
    { id:`f1s1`, domain:`Preflight`, task:`I.A`, title:`The whiteboard`,
      text:(s,all,G)=>[`Tuesday night, alone in the estimating office after everyone left, Jordan did what he always did with a job he didn't understand. He took it apart.`,`He wiped the whiteboard and wrote PRIVATE PILOT at the top, then a column of everything he'd read in two hours of FAA websites, forum arguments, and a YouTube video of a man eating a sandwich while explaining airspace. One year on Walt's clock. Danny had done it in seven months, while working, which Jordan knew because Danny had told him about forty times.`,`He had to decide what went first. What does Jordan put at the top of the plan?`],
      opts:[
        {t:`Book lessons now, and deal with the medical exam once he's close to his first solo.`, s:1, d:{trust:0,conf:-1,health:-2},
          after:`It's legal. A student doesn't need a medical until solo. But it means that if anything in his history needs a closer look, he finds out after spending months and thousands of dollars.`,
          why:`You don't need the medical to take lessons, so this isn't wrong. It's backwards. The medical is the one thing that can stop you cold, and it's cheap to check first.`},
        {t:`Plan for exactly 40 hours, since that's the minimum, and set the budget to match.`, s:0, d:{trust:0,conf:-2,health:-3},
          after:`The budget looks great on the whiteboard. It'll look less great at hour 41.`,
          why:`Forty hours is the legal floor in 61.109, not a forecast. Most students need more. A plan built on the minimum is a plan to run out of money.`},
        {t:`Get the medical first, then the student certificate, then train past the minimums.`, s:3, best:true, d:{trust:2,conf:3,health:4},
          after:`He circles MEDICAL and writes "first, before money." Under it: student certificate through IACRA with the instructor, then the 61.109 list, then a budget with a fat margin. It looks like an estimate. That makes him feel better than it should.`,
          why:`Medical first, because it's the only item that can end the whole thing, and you want to know before you've spent anything. Then the student certificate, so you're ready to solo when you're ready. Then budget for reality, not the minimum.`},
        {t:`Skip the medical exam entirely and plan to fly under BasicMed like many pilots.`, s:0, d:{trust:0,conf:-2,health:-4},
          after:`He reads the fine print an hour later. BasicMed requires that you've held an FAA medical certificate at some point after July 14, 2006. He never has.`,
          why:`BasicMed is real, but it isn't a way to start. You need to have held a medical certificate after July 2006 to use it. A brand new student goes through an AME.`}
      ]},
    { id:`f1s2`, domain:`Preflight`, task:`I.A`, title:`Which medical`,
      text:(s,all,G)=>[`Abby called on Wednesday to confirm Saturday. She talked fast, like someone who billed in tenths of an hour.`,`<span class="said" data-who="Abby">"Do you have a medical yet? Doesn't matter for Saturday. Matters for everything after."</span>`,`Jordan had the MedXPress page open in another tab. There were three classes, and the form wanted to know which one.`],
      opts:[
        {t:`A first class, since it's the highest and covers everything he could ever need.`, s:1, d:{trust:0,conf:1,health:0},
          after:`<span class="said" data-who="Abby">"You can,"</span> Abby says. <span class="said" data-who="Abby">"I did, because I want the airlines. You're flying a 1978 Cessna to get pie. A third class does the job."</span>`,
          why:`A first class medical is valid for private privileges, so it isn't wrong. It's more exam than you need. Some people take it to find out early whether an airline career is possible. If that's not you, a third class is the right tool.`},
        {t:`A third class, which is what private pilot privileges require.`, s:3, best:true, d:{trust:3,conf:2,health:3},
          after:`<span class="said" data-who="Abby">"Good. You're thirty five, so it's good for 60 calendar months. Book the AME this week. Tell me what they say."</span> He books one in Englewood for the following Thursday.`,
          why:`Private pilots need a third class. Because Jordan is under 40 at the exam, it lasts through the end of the 60th month after the month of the exam. Book it early, before you're invested.`},
        {t:`None yet, because a student only needs one right before the checkride.`, s:0, d:{trust:-2,conf:-1,health:-3},
          after:`<span class="said" data-who="Abby">"No. You need it to solo. Which is a lot sooner than the checkride, if I'm doing my job."</span>`,
          why:`A student pilot must hold a medical certificate, or qualify for BasicMed, before flying solo. The checkride is months after that.`},
        {t:`A second class, so he could fly paying passengers if he ever wanted to.`, s:0, d:{trust:-1,conf:-1,health:-1},
          after:`Abby pauses. <span class="said" data-who="Abby">"A second class medical doesn't make you a commercial pilot. A commercial certificate does. Different thing."</span>`,
          why:`The medical class and the pilot certificate are separate. Carrying passengers for hire takes a commercial pilot certificate, not just a second class medical. For a private pilot, a third class is the requirement.`}
      ]},
    { id:`f1s3`, domain:`Preflight`, task:`I.A`, title:`Choosing an instructor`,
      text:(s,all,G)=>[`Russ Kim, the partner Jordan had never met, added him to the club group chat on Thursday. The first message was a welcome. The second was advice nobody asked for.`,`<prop type="chat" from="Russ Kim" time="8:14 PM">welcome jordan. sorry about danny, he was the best of us. unsolicited tip: abby's great but she's leaving for the airlines eventually, they all do. the 141 school at the north end has a 35 hr minimum. just saying</prop>`,`Jordan had read about Part 141 too. He'd also read Abby's bio, which said she was at 1,040 hours and counting.`],
      opts:[
        {t:`Switch to the Part 141 school, since 35 hours is cheaper than 40.`, s:1, d:{trust:-1,conf:0,health:-1},
          after:`The school is good. Its airplanes are rentals, though, and Biscuit isn't on its certificate. He'd be learning in someone else's airplane to fly his own.`,
          why:`The Part 141 minimum really is 35 hours, so the fact is right. But minimums aren't what people fly, and the cheapest path on paper skips what matters here: training in the airplane you'll actually fly.`},
        {t:`Ask Abby when she's leaving, and what happens to his training then.`, s:3, best:true, d:{trust:4,conf:2,health:3},
          after:`Abby doesn't blink. <span class="said" data-who="Abby">"Probably a year. When I go, you get a handoff, my notes, and a CFI I trust. I'll put that in writing if you want."</span> He doesn't need it in writing. He liked that she offered.`,
          why:`Choosing an instructor is choosing a person. Ask the hard question early: availability, schedule, what happens if they leave. A good instructor has a plan for continuity and isn't offended that you asked.`},
        {t:`Pick whichever instructor in the area has the lowest hourly rate.`, s:0, d:{trust:-1,conf:-1,health:-2},
          after:`He finds one twelve dollars cheaper. The calendar is open every day. That turns out to be a clue.`,
          why:`The hourly rate is the least important number in flight training. Fit, consistency, and availability decide how many hours you need. A cheap instructor who adds ten hours isn't cheap.`},
        {t:`Look for whoever trained Danny eleven years ago, so he learns the same way.`, s:0, d:{trust:0,conf:-1,health:-2},
          after:`Danny's instructor retired to Arizona in 2019. Jordan sits with that longer than he expected to.`,
          why:`Wanting to learn the way your brother did is understandable. It isn't a training plan. You need an instructor who's here now and fits how you learn.`}
      ]},
    { id:`f1s4`, domain:`Preflight`, task:`I.H`, title:`Anything I should know`,
      text:(s,all,G)=>[`Saturday came in clear and cold. Centennial sat at the south edge of the city, flat and wide, with the mountains standing up along the whole west side like a wall someone forgot to finish.`,`Abby met him in the club office with a clipboard and a cup of coffee she didn't offer to share. She was shorter than he'd pictured, with a pencil behind her ear and the expression of someone running numbers.`,`<span class="said" data-who="Abby">"Before we go out. Anything I should know? Sleep, meds, sick, anything. I ask everybody."</span>`,`He'd slept about four hours. He'd been sleeping about four hours since March.`],
      opts:[
        {t:`Say he's fine. It's a demo flight with an instructor, so what he's carrying doesn't matter.`, s:0, d:{trust:-3,conf:0,health:-3},
          after:`She nods and moves on. Over the plains he goes quiet for a full minute and doesn't hear her ask him something twice.`,
          why:`The instructor can only manage the risks she knows about. Fatigue and stress are real, even in the right seat. Honesty is part of the preflight.`},
        {t:`Tell her the truth: his brother died in March, and he's barely sleeping.`, s:3, best:true, d:{trust:5,conf:2,health:4},
          after:`Abby is quiet for a second. <span class="said" data-who="Abby">"Danny."</span> She doesn't make it a question. <span class="said" data-who="Abby">"Okay. We keep it short and easy. You say stop, we stop. No speech."</span> He's grateful for the no speech.`,
          why:`IMSAFE: illness, medication, stress, alcohol, fatigue, emotion. Grief is stress, fatigue, and emotion at once. Saying it out loud lets the pilot in command plan around it. That's how risk management starts.`},
        {t:`Cancel the flight and rebook for once he's sleeping better.`, s:1, d:{trust:0,conf:-1,health:1},
          after:`It isn't the wrong call. Abby says so. But he doesn't know when he'll sleep better, and he drove forty minutes to be told that he's allowed to try.`,
          why:`Cancelling is always a legitimate answer, and nobody should talk you out of it. With an instructor flying and a short, easy plan, though, telling the truth and adjusting is the better fit here.`},
        {t:`Mention he's a little tired, but leave out why.`, s:0, d:{trust:-1,conf:0,health:-1},
          after:`<span class="said" data-who="Abby">"Everybody's tired,"</span> she says, and they go. She plans a full hour of maneuvers he doesn't have in him.`,
          why:`A half truth gets you a half plan. The instructor heard "tired" and planned for tired. She didn't know to plan for grief.`}
      ]},
    { id:`f1s5`, domain:`Preflight`, task:`II`, title:`The walkaround`,
      text:(s,all,G)=>[`Biscuit sat on the ramp in a row of tied down Cessnas, white with a maroon stripe, a little faded. Jordan had seen her in a hundred photos with Danny's thumb in the corner. In person she was smaller. She looked like a used car somebody loved.`,`Abby handed him a laminated checklist, worn soft at the corners, with a coffee ring on the back. <span class="said" data-who="Abby">"You do the walkaround. I'll follow you and keep my mouth shut. Mostly."</span>`],
      opts:[
        {t:`Do it from memory, the way the pilot did it in the video he watched last night.`, s:0, d:{trust:-2,conf:-2,health:-3},
          after:`He skips the fuel caps without noticing. Abby notices. She points at them with her coffee cup.`,
          why:`Checklists exist because memory fails, especially when you're nervous, tired, or new. Pilots with thirty years use them every flight.`},
        {t:`Read and do each item, and ask about what he doesn't know.`, s:3, best:true, d:{trust:3,conf:3,health:4},
          after:`It takes twenty five minutes. He asks about the stall warning horn, the static port, and why the pitot tube has a cover on it. Abby answers every one. At the end she says, <span class="said" data-who="Abby">"You read the whole thing. Most people read the bold parts."</span>`,
          why:`Read and do, one item at a time, and ask about what you don't know. A preflight inspection is where you find what will hurt you later on the ground, where it's cheap.`},
        {t:`Follow the checklist but skip the items he doesn't understand, since Abby will catch them.`, s:1, d:{trust:0,conf:0,health:-1},
          after:`Abby does catch them. She also makes him go back and do them.`,
          why:`Leaning on the instructor is natural on day one. But the checklist is yours. Ask about what you don't understand; don't skip it.`},
        {t:`Let Abby do the walkaround while he watches, since it's his first day.`, s:0, d:{trust:-1,conf:-1,health:-1},
          after:`<span class="said" data-who="Abby">"No,"</span> she says, cheerfully. <span class="said" data-who="Abby">"Your hands. My eyes."</span>`,
          why:`You learn a preflight by doing it. Watching feels efficient and teaches almost nothing.`}
      ]},
    { id:`f1s6`, domain:`Preflight`, task:`II`, title:`The bead in the cup`,
      text:(s,all,G)=>[`Under the left wing, Abby handed him a clear plastic tube with a pin on the end. <span class="said" data-who="Abby">"Fuel sample. Push it up into the drain, fill the cup, look at it."</span>`,`The fuel was pale blue, the color of a swimming pool in a commercial. At the bottom of the cup sat a small clear bead that didn't mix, like a drop of oil in reverse.`],
      opts:[
        {t:`Pour the sample back in through the filler cap so the fuel isn't wasted.`, s:0, d:{trust:-2,conf:-2,health:-4},
          after:`Abby's hand closes over his before the cup gets near the wing. <span class="said" data-who="Abby">"You just found water. Let's not give it back."</span>`,
          why:`Bad sample goes in the jug by the fuel pump. Never back in the wing. I've watched a guy do it at Front Range, and I still think about him every time I sump.`},
        {t:`Show Abby, and keep draining until the samples come out clean.`, s:3, best:true, d:{trust:3,conf:3,health:5},
          after:`He drains three more cups. The third is clear and blue all the way down. Abby nods. <span class="said" data-who="Abby">"Cold night, partly full tank, condensation. That's why we look every single time."</span>`,
          why:`Water's heavier than gas. It sinks, so the sump catches it first. You drain until it's blue top to bottom with no junk in it. Won't clear? Then we're not going, and I'm calling Marisol.`},
        {t:`Note it, and mention it to Abby after the flight.`, s:1, d:{trust:-1,conf:0,health:-2},
          after:`He almost says nothing. Then he says it, a minute later. She makes him drain it until it's clean, and asks why he waited.`,
          why:`You noticed. Good, that's the hard part. But you tell me right then, on the ground, where we can do something about it. After the flight is a story, not a preflight.`},
        {t:`Ignore it. It's one small drop in a tank holding twenty gallons.`, s:0, d:{trust:-2,conf:-2,health:-5},
          after:`Abby sees the cup over his shoulder. Doesn't say a word. Just holds her hand out for the tester and starts draining it herself, which is somehow worse than a lecture.`,
          why:`One bead in the cup can mean a lot more sitting in the tank. Get enough of it in the line and the engine coughs, or quits, usually right after takeoff because that's how the universe works. We don't fly with it. Ever.`}
      ]},
    { id:`f1s7`, domain:`Preflight`, task:`I.G`, title:`The sticky selector`,
      text:(s,all,G)=>[`Abby put him in the left seat like it was nothing. It wasn't nothing. Danny's seat. Jordan ran a hand over the panel: six round gauges, a radio stack, a GPS bolted in sometime this century, a crack in the glare shield held together with silver tape. A sticker by the mag switch said HI DAD in a nine year old's handwriting. He looked at it a while.`,`Down on the floor between the seats was the fuel selector, a red handle. The checklist said: Fuel selector valve, BOTH. He turned it. It stuck a few degrees short of the click and wouldn't go.`],
      opts:[
        {t:`Leave it where it stopped. It's close enough to BOTH.`, s:0, d:{trust:-2,conf:-2,health:-4},
          after:`Abby reaches down, wiggles it, and seats it with a click. <span class="said" data-who="Abby">"Close enough isn't a fuel position."</span>`,
          why:`Half in a detent isn't a setting. You don't actually know what it's feeding. BOTH means clicked into BOTH, and you feel for it every time.`},
        {t:`Tell Abby it won't seat, and ask her to check it.`, s:3, best:true, d:{trust:4,conf:3,health:4},
          after:`<span class="said" data-who="Abby">"Ah. Biscuit's famous selector."</span> She shows him the trick, lift and twist, and it clicks home. <span class="said" data-who="Abby">"Marisol knows. It's on the squawk list. It's safe, it's just ornery. Good catch, though. You'll always feel for the click."</span>`,
          why:`Something feels off, you say so, and you say it before we start the engine. Takeoff and landing in this airplane are on BOTH. Ten seconds of asking beats a very bad afternoon.`},
        {t:`Force it hard into the detent himself so he doesn't look nervous.`, s:0, d:{trust:-1,conf:-1,health:-3},
          after:`It clicks. It also makes a noise Abby doesn't like. She makes a note for Marisol.`,
          why:`Nobody's grading you on looking calm. Muscle a stiff part and you can break it, and then Marisol has a new least favorite person. Tell me instead.`},
        {t:`Turn it to LEFT instead, since that one moved easily.`, s:1, d:{trust:-1,conf:0,health:-2},
          after:`It's a real fuel position, so the engine would run. Abby turns it back. <span class="said" data-who="Abby">"Checklist says BOTH for takeoff. We don't freelance."</span>`,
          why:`LEFT works. The engine would've run fine. But we fly the checklist, and when something on it doesn't work, that's a squawk, not a workaround.`}
      ]},
    { id:`f1s8`, domain:`Preflight`, task:`I.G`, title:`Explain it back`,
      text:(s,all,G)=>[`They took off on 35R behind a Cirrus. Biscuit's door popped open with a bang at rotation, which Abby had warned him about and which still nearly stopped his heart. She latched the top and said, <span class="said" data-who="Abby">"Biscuit does that. Danny never fixed it. Said it kept him humble."</span> It was the first time anyone had said Danny's name like it was normal.`,`East of the airport the city gave up and the plains took over, brown squares and a few center pivots and a feedlot you could smell at altitude, honestly. Abby kept tapping the chart on her knee where the Class B shelf sat over their heads like a low ceiling. Then she let go of the yoke. <span class="said" data-who="Abby">"Yours. Roll left. Just your hands. Feet flat. Watch the nose, not me."</span>`,`He rolled. The nose did a little shrug to the right, wrong way, then came around. <span class="said" data-who="Abby">"See that? Why'd it do that?"</span>`],
      opts:[
        {t:`Right aileron went down, so that wing's got more lift and drag. Left rudder fixes it.`, s:3, best:true, d:{trust:3,conf:4,health:3},
          after:`Abby turns in her seat to look at him. <span class="said" data-who="Abby">"You read the book."</span> <span class="said" data-who="Jordan">"I read the book."</span> <span class="said" data-who="Abby">"Okay. Do it again with left rudder."</span> The nose swings straight into the turn. The ball sits in the middle.`,
          why:`That's adverse yaw. The right aileron went down, so the right wing makes more lift and more induced drag. The drag pulls the nose right, away from the turn. Rudder in the direction of the turn coordinates it.`},
        {t:`Gust from the left. It's April over the plains, the air's lumpy and doesn't care.`, s:0, d:{trust:0,conf:-2,health:-1},
          after:`<span class="said" data-who="Abby">"Again."</span> Same thing. <span class="said" data-who="Abby">"Wind's pretty punctual today, huh?"</span>`,
          why:`It isn't the wind. It happens every time you roll with ailerons alone. That's adverse yaw, and the fix is coordinated rudder.`},
        {t:`Left aileron dropped, so the left wing got heavy and dragged the nose right.`, s:0, d:{trust:0,conf:-2,health:-1},
          after:`<span class="said" data-who="Abby">"Other way around. Roll left, left aileron goes up."</span>`,
          why:`Backwards. Yoke left means left aileron UP. The right one's the one that dropped, so the right wing's the one hauling extra drag. Get that flipped in your head and you'll stomp the wrong pedal someday.`},
        {t:`Airplanes are slow to react. Just hold the yoke steady and give it a second.`, s:1, d:{trust:0,conf:0,health:0},
          after:`<span class="said" data-who="Abby">"Sort of. Airplanes are slow. But that swing has a name, and you've got two feet that fix it."</span>`,
          why:`Waiting a beat isn't dumb, Biscuit's a 1978 Cessna, she's not a fighter jet. But the nose went the wrong direction first. That's not slow. That's adverse yaw, and it's your feet's job.`}
      ]},
    { id:`f1s9`, domain:`Airport and flight`, task:`V`, title:`Look first`,
      text:(s,all,G)=>[`<span class="said" data-who="Abby">"Okay. Before anything fun, we look around. Every single time. I'll do the first one."</span> Ninety degrees left, ninety back right, her head on a swivel the entire time, chattering about how she once found a hot air balloon this way.`,`Second turn was his. Bottom right corner of the windshield, a dot. Two o'clock-ish, below them. He watched it for a full breath waiting for it to drift. It didn't drift. It got bigger.`],
      opts:[
        {t:`Call "Traffic, two o'clock low," and point.`, s:3, best:true, d:{trust:3,conf:3,health:5},
          after:`Abby's head whips around. <span class="said" data-who="Abby">"Got him. Piper Warrior, climbing. My airplane, turning left."</span> Over they go. The Piper passes behind the wing, close enough to read the N number if he'd been looking, which he wasn't, because his heart was in his ears. <span class="said" data-who="Abby">"Nice call. That's the most important thing I'll ever teach you and you did it on day one. Don't get cocky."</span>`,
          why:`Out here, in good weather, the traffic system is mostly us, looking out the window. So you call it like a clock, plus high or low, and you keep your eyes glued to it. A dot that won't move on the glass but keeps growing? Collision course. Remember that one forever.`},
        {t:`Say nothing. It's probably way out there, and Abby's seen it anyway.`, s:0, d:{trust:-2,conf:-2,health:-5},
          after:`She hadn't. Four seconds later she does, and rolls them hard left. Not a movie moment. Just closer than she'd like, which she mentions twice on the ride home.`,
          why:`Never assume I saw it. I'm a person, I miss stuff. That's the entire reason you're sitting up front with me. Say it out loud.`},
        {t:`Yank the yoke and turn them away himself, right now.`, s:1, d:{trust:-1,conf:0,health:1},
          after:`It works, technically. It also scares Abby more than the Piper did, because a second ago she was flying. <span class="said" data-who="Abby">"Hey. Words first. Then we turn. I need to know whose hands are on this thing."</span>`,
          why:`Getting away from it, sure, good. But I had the airplane. Two pilots both grabbing at once is its own emergency. Words, then hands.`},
        {t:`Ask Abby if that dot at two o'clock is a bird or what.`, s:1, d:{trust:0,conf:0,health:0},
          after:`<span class="said" data-who="Abby">"That's a Piper, and it's closing. Next time, just call it."</span>`,
          why:`Asking beats sitting there quiet. But skip the question and just call it: clock position, high or low, fast. Bird, airplane, balloon, I don't care. Call it.`}
      ]},
    { id:`f1s10`, domain:`Preflight`, task:`I.G`, title:`Heavy hands`,
      text:(s,all,G)=>[`Back up to altitude. Five minutes later Jordan's right forearm was on fire. Biscuit wanted up. He wanted level. So he pushed. And pushed. His watch buzzed to tell him his heart rate was elevated, which, thanks.`,`Abby looked at his arm. Then out the window. Then at his arm. She didn't say anything. He was starting to learn that her not saying anything was a kind of saying something.`],
      opts:[
        {t:`Keep pushing. Fifteen more minutes, he's done worse at the gym.`, s:0, d:{trust:0,conf:-1,health:-2},
          after:`His arm gives out a little at a time. Two hundred feet sneaks onto the altimeter. He doesn't notice. Abby does, and writes something on her kneeboard.`,
          why:`Your arm loses that fight every time. It gets tired, you drift, you don't notice. Trim does the holding so you don't have to.`},
        {t:`Hold the attitude he wants, then trim until the pressure is gone.`, s:3, best:true, d:{trust:3,conf:4,health:4},
          after:`Three turns forward on the wheel. The yoke goes soft in his hand. He lets go, cautiously, like taking his hand off a kid's bike seat, and Biscuit stays put, level, droning along. He laughs. It surprises both of them. <span class="said" data-who="Abby">"Yep. That's trim. Welcome to not arm wrestling your airplane."</span>`,
          why:`Attitude, then trim. The trim tab rides on the back of the elevator and moves opposite it, which is a test question, write that down. Its whole job is to hold the elevator so your arm doesn't have to.`},
        {t:`Pull some power so the nose sags down on its own.`, s:1, d:{trust:0,conf:0,health:-1},
          after:`The nose sags. So does the airspeed. Now he's got a slower, lower airplane he didn't order.`,
          why:`Honestly not crazy, power does move the nose. You just bought a speed change and an altitude change you didn't want with it. Power where you want it, nose where you want it, then trim.`},
        {t:`Hand it back to Abby for a minute and shake his arm out.`, s:0, d:{trust:0,conf:-1,health:0},
          after:`<span class="said" data-who="Abby">"My airplane."</span> She doesn't even look. Hand drops to the wheel between the seats, spin, spin, done. He feels dumb for about a second, then mostly curious.`,
          why:`You can always hand it to me. I'll never be mad about that. This time, though, the answer was a wheel eight inches from your knee.`}
      ]},
    { id:`f1s11`, domain:`Navigation and emergencies`, task:`IX`, title:`Power to idle`,
      text:(s,all,G)=>[`<span class="said" data-who="Abby">"Last thing, then home. I'm going to show you something. Nothing is wrong with the airplane. Say it back."</span> <span class="said" data-who="Jordan">"Nothing is wrong with the airplane."</span> <span class="said" data-who="Abby">"Great."</span> Carb heat knob, out. Throttle, all the way back to the stop.`,`The engine dropped to a mutter. The quiet was enormous. Jordan's stomach dropped with the nose, and for a second the only thing in his head was a Saturday sideline in Parker and a phone call he didn't make in time.`,`<span class="said" data-who="Abby">"Your airplane,"</span> she said gently. <span class="said" data-who="Abby">"The engine just quit. What's the first thing you do?"</span>`],
      opts:[
        {t:`Bank back toward Centennial. A runway beats a cornfield.`, s:0, d:{trust:-1,conf:-2,health:-4},
          after:`He banks. The airspeed sags. Abby points at the airport, a gray smudge way off past the reservoir. <span class="said" data-who="Abby">"Eleven miles, not very high. We don't make that. And you just traded away speed to not make it."</span>`,
          why:`Everybody wants the runway, me included. Turning for one you can't reach just bleeds off speed, and speed is what keeps an off airport landing a bad day instead of a headline. Speed first. Then a field that's actually in reach.`},
        {t:`Go straight for the key and the mags and get it running again.`, s:1, d:{trust:0,conf:-1,health:-2},
          after:`His hand's halfway to the key when hers lands on his wrist. <span class="said" data-who="Abby">"In a minute, maybe. Fly first."</span>`,
          why:`You'll learn the restart checklist, I promise. It comes second. Lose your glide speed while you're fiddling with the key and it won't matter if the engine catches.`},
        {t:`Get the nose down to best glide speed, then go hunting for a field.`, s:3, best:true, d:{trust:3,conf:4,health:5},
          after:`Nose down. The needle creeps to the spot Abby's fingernail is tapping on the glass and sits there. Then he looks outside: a long brown field, a dirt road along one side, a windmill, no power lines that he can find. <span class="said" data-who="Abby">"Yep. That's it. That's the whole trick."</span> Throttle in, engine roaring, and he notices he hasn't breathed since Parker.`,
          why:`Fly first. Best glide gets you the most ground for the altitude you've got. Then pick your spot, then the checklist, then the radio. Aviate, navigate, communicate. In that order, every time.`},
        {t:`Key the mic and tell Centennial Tower he's declaring an emergency.`, s:1, d:{trust:0,conf:0,health:-2},
          after:`Thumb on the push to talk. <span class="said" data-who="Abby">"Love the instinct. Wrong order. Tower can wait thirty seconds, the airplane can't."</span>`,
          why:`You'll make that call, and you should. Third, though. Tower can't fly the airplane for you.`}
      ]},
    { id:`f1s12`, domain:`Preflight`, task:`I.A`, title:`Answering Walt`,
      text:(s,all,G)=>[`After they tied Biscuit down, a man in a canvas jacket was waiting at the hangar door with two coffees. Gray at the temples, reading glasses on a cord, the posture of somebody who'd spent thirty years telling people things they didn't want to hear. Walt Herrera.`,`He handed Jordan a coffee. <span class="said" data-who="Walt">"How was it?"</span> Then, before Jordan could answer: <span class="said" data-who="Walt">"I meant what I said. I'm not trying to take anything from you. But you've got a lot on you right now, you've never flown, and that's a quarter of an airplane four people trust their lives to. So. Selling?"</span>`],
      opts:[
        {t:`Tell Walt it's his share now and to stay out of it.`, s:0, d:{trust:-5,conf:-3,health:-2},
          after:`Walt nods slowly and takes his coffee back, which Jordan didn't know was possible.`,
          why:`Walt is the club's safety officer, and he's right to ask. Turning a fair safety concern into a fight costs you the person who'll sign off on your progress.`},
        {t:`Sell the share back to keep the peace, and let the airplane go.`, s:1, d:{trust:0,conf:0,health:0},
          after:`It would be a reasonable decision. Lots of people make it. But the note said don't let it sit, and selling it isn't the same thing as deciding.`,
          why:`Selling is a legitimate choice, and nobody should feel ashamed of it. Making it to avoid a hard conversation isn't the same as making it on the merits.`},
        {t:`Promise Walt he'll solo in three months, like Danny did.`, s:0, d:{trust:-2,conf:-3,health:-3},
          after:`Walt's eyebrows go up. <span class="said" data-who="Walt">"Danny soloed at five months. He just told people three."</span>`,
          why:`Promising a date to win an argument is how pilots end up pushing to meet it. Progress comes from the syllabus and your instructor, not a bet.`},
        {t:`Show Walt the plan, and ask what he needs to see along the way.`, s:3, best:true, d:{trust:5,conf:4,health:3},
          after:`He pulls up the whiteboard photo on his phone: medical first, student certificate, training, a budget with margin. Walt reads it twice with his glasses on. <span class="said" data-who="Walt">"Medical first,"</span> he says. <span class="said" data-who="Walt">"Huh."</span> Then: <span class="said" data-who="Walt">"I want to see your logbook every month. And you come to the safety meetings."</span> It isn't a yes. It isn't a no.`,
          why:`Walt's worry is legitimate. Answer it with a plan and checkpoints, not with feelings. Inviting the skeptic to watch your progress turns him from an obstacle into a safety net.`}
      ]}
  ],
  drills:[
    {after:`f1s12`, title:`The first entry`,
     setup:[`Abby writes up the discovery flight. Biscuit's Hobbs meter read 2,814.3 before engine start and 2,815.2 after shutdown. The club logs Hobbs time, which runs a little long but close enough that most clubs and instructors use it.`,`Under 61.109, Jordan needs at least 40 hours total, including at least 20 hours of dual flight training and 10 hours of solo.`],
     fields:[{label:`Time flown (hours)`,answer:0.9,tol:0.01},{label:`Total time still needed for the 40 hour minimum`,answer:39.1,tol:0.01},{label:`Dual training still needed for the 20 hour minimum`,answer:19.1,tol:0.01},{label:`Solo time still needed`,answer:10,tol:0.01}],
     solution:[`Time flown = 2,815.2 minus 2,814.3 = 0.9 hours.`,`Total remaining = 40 minus 0.9 = 39.1 hours. Dual remaining = 20 minus 0.9 = 19.1 hours, because the discovery flight was dual instruction from a CFI. Solo remaining = 10 hours, since none of today was solo.`,`Those are minimums. Abby would say they're the numbers you pass on your way to the real number.`]}
  ],
  exercise: { after:`f1s8`, title:`Controls and axes`, intro:`Abby taped a sticky note to each control. Match each one to what it does.`,
    items:[
      {prompt:`The ailerons move the airplane around this axis.`, choices:[`Longitudinal`,`Lateral`,`Vertical`], answer:0, why:`The longitudinal axis runs nose to tail. Rotation around it is roll, and the ailerons control it.`},
      {prompt:`The elevator moves the airplane around this axis.`, choices:[`Longitudinal`,`Lateral`,`Vertical`], answer:1, why:`The lateral axis runs wingtip to wingtip. Rotation around it is pitch, controlled by the elevator.`},
      {prompt:`The rudder moves the airplane around this axis.`, choices:[`Longitudinal`,`Lateral`,`Vertical`], answer:2, why:`The vertical axis runs top to bottom through the center of gravity. Rotation around it is yaw, controlled by the rudder.`},
      {prompt:`Turning the yoke to the right makes the right aileron move this way.`, choices:[`Up`,`Down`,`It doesn't move`], answer:0, why:`Turn right and the right aileron goes up, lowering that wing's lift so the airplane rolls right. The left aileron goes down.`},
      {prompt:`To hold the nose down without pushing the yoke, the trim tab on the elevator moves this way.`, choices:[`Up`,`Down`,`It doesn't move`], answer:0, why:`The trim tab moves opposite the elevator. Tab up pushes the trailing edge of the elevator down, which lowers the nose.`},
      {prompt:`All three axes pass through this point.`, choices:[`The center of lift`,`The center of gravity`,`The firewall`], answer:1, why:`The longitudinal, lateral, and vertical axes all intersect at the airplane's center of gravity.`}
    ]},
  quiz: [
    {q:`What is the minimum age to be eligible for a private pilot certificate with an airplane rating?`, opts:[`16 years old`,`17 years old`,`18 years old`], a:1, why:`14 CFR 61.103 requires at least 17 years of age. Sixteen is the minimum for a student pilot certificate in an airplane.`, task:`I.A`, domain:`Preflight`},
    {q:`A pilot who is 35 years old receives a third class medical certificate. For private pilot privileges, it is valid through the`, opts:[`last day of the 24th month after the month of the exam`,`last day of the 60th month after the month of the exam`,`same calendar day five years after the date of the exam`], a:1, why:`Under 61.23, a third class medical for a pilot under 40 at the exam is valid through the end of the 60th calendar month after the month of the exam. At 40 or older it's 24 months.`, task:`I.A`, domain:`Preflight`},
    {q:`Which of the following does a student pilot need before the first solo flight?`, opts:[`A passed knowledge test and a medical certificate`,`20 hours of dual and a student pilot certificate`,`A student pilot certificate, medical, and endorsements`], a:2, why:`To solo, a student needs a student pilot certificate, a medical certificate or BasicMed qualification, and the required instructor endorsements under 61.87. The knowledge test comes later.`, task:`I.A`, domain:`Preflight`},
    {q:`Under Part 61, a private pilot applicant for an airplane single engine rating must log at least`, opts:[`40 hours, with 20 hours dual and 10 hours solo`,`35 hours, with 20 hours dual and 5 hours solo`,`40 hours, with 10 hours dual and 20 hours solo`], a:0, why:`61.109(a) requires at least 40 hours of flight time, including at least 20 hours of flight training from an authorized instructor and 10 hours of solo flight.`, task:`I.A`, domain:`Preflight`},
    {q:`The required long solo cross country for a private pilot applicant must be at least`, opts:[`100 NM total, with landings at two points`,`150 NM total, with one leg of at least 50 NM`,`150 NM total, with every leg at least 50 NM`], a:1, why:`61.109 requires one solo cross country of at least 150 nautical miles total, with full stop landings at three points and one segment of at least 50 nautical miles between takeoff and landing.`, task:`I.A`, domain:`Preflight`},
    {q:`During steady, unaccelerated level flight, which statement about the four forces is true?`, opts:[`Lift is greater than weight, and thrust equals drag`,`Lift equals weight, and thrust is greater than drag`,`Lift equals weight, and thrust equals drag`], a:2, why:`In steady, unaccelerated flight the opposing forces are in balance: the sum of the upward forces equals the downward forces, and forward equals rearward.`, task:`I.F`, domain:`Preflight`},
    {q:`Movement of the airplane about its longitudinal axis is called`, opts:[`pitch, and it is controlled by the elevator`,`roll, and it is controlled by the ailerons`,`yaw, and it is controlled by the rudder`], a:1, why:`The longitudinal axis runs nose to tail. Rotation around it is roll, controlled by the ailerons.`, task:`I.G`, domain:`Preflight`},
    {q:`A pilot rolls into a left turn using ailerons alone. The nose will initially`, opts:[`yaw to the right`,`yaw to the left`,`pitch up sharply`], a:0, why:`Adverse yaw. The right aileron lowers, so the right wing makes more lift and more induced drag, which yaws the nose right, away from the turn. Left rudder corrects it.`, task:`I.G`, domain:`Preflight`},
    {q:`To counter adverse yaw while rolling into a right turn, the pilot should apply`, opts:[`left rudder`,`right rudder`,`forward elevator`], a:1, why:`Apply rudder in the direction of the turn. Rolling right, the nose yaws left from adverse yaw, so right rudder keeps the turn coordinated.`, task:`I.G`, domain:`Preflight`},
    {q:`To relieve a constant forward pressure on the yoke, the elevator trim tab will move`, opts:[`up, opposite the elevator`,`down, the same as the elevator`,`up, the same as the elevator`], a:0, why:`The trim tab moves opposite the elevator. To hold the nose down, the tab moves up, which pushes the elevator down.`, task:`I.G`, domain:`Preflight`},
    {q:`A fuel sample shows a clear bead resting at the bottom of the sampling cup. The pilot should`, opts:[`return the sample to the tank to conserve fuel`,`continue sampling until no water remains`,`note it in the logbook and continue the flight`], a:1, why:`Water is heavier than fuel and settles to the bottom. Keep draining until the samples are free of water and sediment. If it won't clear, don't fly.`, task:`II`, domain:`Preflight`},
    {q:`Aviation gasoline grade 100LL is dyed`, opts:[`blue`,`green`,`red`], a:0, why:`100LL avgas is dyed blue. A sample that's the wrong color, or clear, may be the wrong fuel or contaminated.`, task:`II`, domain:`Preflight`},
    {q:`Before beginning a practice maneuver, a pilot should`, opts:[`perform clearing turns to check for traffic`,`climb to the top of the practice area`,`request permission from the nearest tower`], a:0, why:`Clearing turns, usually two 90 degree turns in opposite directions, let the pilot look for traffic before maneuvering. See and avoid is every pilot's responsibility.`, task:`V`, domain:`Airport and flight`},
    {q:`After an engine failure at altitude, the pilot's first priority should be to`, opts:[`turn toward the departure airport`,`attempt an immediate engine restart`,`establish the best glide airspeed`], a:2, why:`Fly the airplane first. Pitch for best glide airspeed to get the most distance from your altitude, then choose a landing site, then run the checklist and communicate.`, task:`IX`, domain:`Navigation and emergencies`},
    {q:`A pilot whose brother died recently plans to fly. Which IMSAFE items most directly apply?`, opts:[`Illness and medication`,`Alcohol and eating`,`Stress and emotion`], a:2, why:`IMSAFE covers illness, medication, stress, alcohol, fatigue, and emotion. Grief is stress and emotion, and it usually brings fatigue with it.`, task:`I.H`, domain:`Preflight`}
  ],
  closing:(s,all,G)=>[
    `Walt left. Abby went inside to write up the flight. Jordan said he'd be a minute.`,
    `He walked back out to the ramp and untied nothing and opened Biscuit's left door, the one that popped, and sat down in the left seat. The cabin smelled like old vinyl and avgas and, faintly, something he couldn't name and then could. Danny's car had smelled like that. He'd thought it was Danny's cologne.`,
    `In the side pocket of the door there was a fuel tester, a pencil, half a roll of Tums, and a composition notebook with a cracked green spine. On the cover, in Sharpie: <b>D. REYES. IF FOUND, I'M PROBABLY NEARBY.</b>`,
    `It wasn't the official logbook. That was in a box at Claire's house. This was the other one, the one Danny kept in the airplane. He opened it to the first page.`,
    `<prop type="doc" title="Danny's logbook, first page">March 14. First lesson. 0.9 dual. Cessna 152. Instructor says I'm a natural. Instructor says that to everyone. Did steep turns, almost threw up, didn't. Felt like I was ten years old. Bring Jordan someday. He'll hate it and then he won't.</prop>`,
    (s.score>=27
      ?`Jordan read it three times. Then he closed the notebook and put both hands on the yoke and sat there for ten minutes, not flying anywhere, not doing anything, watching a Cirrus taxi out and the light go long and gold across the field toward the mountains.`
      :`Jordan read it three times. Some of the morning had gone sideways, and he knew which parts. He closed the notebook and put both hands on the yoke and sat there for ten minutes, not flying anywhere, watching the light go long and gold across the field toward the mountains.`),
    `Abby came out once, saw him through the windshield, and went back inside without a word. He'd thank her for that later.`,
    `He didn't tell anyone what he did in those ten minutes. He didn't really know.`,
    `That night his mother called. He let it ring twice before he answered. <span class="said" data-who="Lourdes">"Claire said you went to the airport."</span> A pause long enough to fly through. <span class="said" data-who="Lourdes">"Mijo. Please don't do this."</span>`,
    `He looked at the green notebook on his kitchen counter. <span class="said" data-who="Jordan">"I booked the medical,"</span> he said. <span class="said" data-who="Jordan">"Thursday. That's all I've done, Ma. That's all I've decided."</span>`,
    `It was true. It just didn't feel like the whole truth.`
  ],
  episode:{src:`audio/full-ch01.mp3`, len:`about 35 minutes`},
  next:`The Machine`
});
