(window.HALCYON_FULL=window.HALCYON_FULL||[]).push({
  num: 1, part: `Part One: The Cascade Launch`, title: `The Promotion`, weeks: `Week 1`,
  tasks: [`P1`,`B1`,`R1`,`P4`,`R9`,`P5`],
  cast: [
    [`Dana Okafor`,`Sam's wife. High school chemistry teacher. Notices when he isn't sleeping.`],
    [`Ray Mendez`,`Sam's old flight chief, MSgt (ret.). Lives in his head more than his phone.`]
  ],
  opening: [
    `The email came in at 6:12 on a Monday morning, which was how Sam Okafor knew it was bad news. Nobody at Halcyon AI sent good news before seven.`,
    `He read it standing at the kitchen counter in his socks. Dana was grading lab reports at the table with a red pen and a cold cup of coffee. She watched him read it twice. <span class="said" data-who="Dana">"That's your work face,"</span> she said. <span class="said" data-who="Dana">"Not your normal work face. The one from the flight line."</span>`,
    `Sam had spent nine years in the Air Force keeping F-16s ready to fly, the last four as a crew chief who answered to a flight chief named Ray Mendez. Ray had one rule he said so often it got painted on a toolbox: the jet doesn't care how you feel. You did the inspection anyway. You signed the forms honestly anyway. You told the pilot the truth about the aircraft even when the truth meant nobody flew that day.`,
    `Twelve years later Sam ran the data centers for Halcyon AI, a six hundred person company in a renovated warehouse in LoDo that built AI agents to draft clinical documentation for doctors and nurses. His racks were boring, which was the point. He liked boring. Boring meant nobody was paging him at two in the morning.`,
    `The email was from Elena Vasquez, the CEO. Subject line: "Need you at 8:30." No body. Elena only skipped the body when something was on fire.`,
    `<prop type="email" from="Elena Vasquez" to="Sam Okafor" time="6:12 AM" subject="Need you at 8:30"></prop>`,
    `Halcyon had one deal that mattered more than all the others combined. Cascade Valley Health, eleven hospitals across Colorado and Wyoming, had signed a contract to put Halcyon's agents into its clinical documentation workflow. Go-live was fourteen weeks out. The date was in the contract, written by the sales team and signed before anyone in engineering had estimated a single task. Grant Mercer, the Chief Revenue Officer, had rung a brass bell in the office when it closed. People had cheered. Sam had been in the server room and missed it.`,
    `On Friday afternoon the project manager running Cascade had quit. Two lines in an email, a badge left on the desk, and a shared drive with forty folders that nobody else understood.`,
    `<prop type="email" from="Cascade project manager" to="Elena Vasquez" time="Friday, 4:51 PM" subject="Resignation">Elena, I'm resigning effective today. Everything is on the shared drive.</prop>`,
    `Dana capped her pen. <span class="said" data-who="Dana">"Go,"</span> she said. <span class="said" data-who="Dana">"And eat something that isn't a granola bar."</span> He took the granola bar anyway.`
  ],
  lesson: {
    title: `Starting right: charters, governance, and stakeholders`,
    sections: [
      { h: `What a project is, and why it needs a start`,
        body: [`A project is a temporary effort to create a unique product, service, or result. Temporary means it has a beginning and an end. Unique means you haven't done this exact thing before, so you can't run it like a factory line. Operations keep the business running; projects change the business. Cascade is a project. Sam's data centers, on a normal day, are operations.`,
          `Because a project is temporary and unique, it needs a formal start. On the exam, that start is the project charter. Without one, nobody has agreed what the project is for, who is in charge, or what authority the project manager has. Most of the trouble Sam finds in his first week traces back to a project that started without one.`],
        terms: [[`Project`,`A temporary effort that creates a unique product, service, or result.`],[`Operations`,`Ongoing, repetitive work that sustains the business.`]],
        exam: `If a question describes ongoing, repeated work, it's operations, not a project. If it asks what formally starts a project, the answer is the sponsor approving the charter.` },
      { h: `The project charter`,
        body: [`The charter is a short document, usually issued by the sponsor, that formally authorizes the project and names the project manager. It ties the project to a business need, states high-level objectives and success criteria, lists key stakeholders, summarizes milestones and budget, and names major risks and assumptions. It is deliberately high level. The detail lives in the project management plan later.`,
          `The most tested idea is authority. The charter is where the project manager's authority comes from. A contract tells you what your company owes a customer. A charter tells your own organization that this project exists and that the PM can use its resources. The PM often drafts it, but the sponsor issues and signs it. In agile settings the same purpose is often served by a lighter project vision or a product vision statement, but someone with authority still has to say "yes, this is ours, go."`, `The charter also protects the project manager. When a functional manager refuses to release a person, or a stakeholder questions whether the project is a priority, the signed charter is the answer. It is the organization saying, in writing, that this work matters and that this person leads it. That's why exam questions about a PM who can't get resources so often point back to the charter, not to persuasion or workarounds.`],
        terms: [[`Sponsor`,`The person or group who provides resources and support and is accountable for enabling success.`],[`Business case`,`The documented economic justification for the project.`],[`Success criteria`,`Measurable conditions that tell you the project worked.`]],
        exam: `Watch for answers that skip authorization. "Start work now and write the charter later" is usually a trap. If the PM lacks authority to get resources, the fix is the sponsor and the charter, not working around people.` },
      { h: `Governance: who decides what`,
        body: [`Governance is the framework for how decisions get made, who makes them, and how issues escalate. It includes the sponsor, any steering committee, phase gates, approval thresholds, and the escalation path. Good governance answers simple questions before they become fights: Who can approve a scope change? Who can move the date? How much budget can the PM spend without asking?`,
          `On the current exam, defining and establishing governance is its own task in the Business Environment domain. Expect questions where the right move is to clarify decision rights before acting, or to escalate a decision to the right level instead of making it yourself. The PM doesn't own every decision. The PM owns making sure decisions get made by the right people, on time, and get written down.`, `On a hybrid project, governance also covers how the predictive and adaptive parts check in with each other. A common pattern is milestone reviews for the plan-driven work and sprint reviews for the adaptive work, with a regular forum where both are visible to the sponsor. Write it down in the governance section of the plan so new people can find it. And give every change request a home: a change log that records what was asked, who decided, and whether it was approved or rejected. When Grant promises something on a call, the change log is where that promise becomes a decision instead of a rumor.`],
        terms: [[`Escalation path`,`The agreed route for raising issues the team can't resolve.`],[`Steering committee`,`Senior stakeholders who guide the project and make decisions above the PM's authority.`]],
        exam: `When a question asks who should decide something big, like moving a contract date, the answer is rarely the project manager alone. The PM analyzes and recommends; governance decides.` },
      { h: `Stakeholders and a common vision`,
        body: [`A stakeholder is anyone who affects or is affected by the project. Identify them early and keep identifying them, because they keep appearing. Record them in a stakeholder register with their interest, influence, current engagement, and desired engagement. A power and interest grid is a quick way to decide how to engage each one. High power and high interest: manage closely. High power, low interest: keep satisfied, without burying them in detail. Low power, high interest: keep informed. Low power, low interest: monitor.`,
          `A common vision means the team and key stakeholders share the same picture of what success looks like and why it matters. When sales thinks success is the go-live date and engineering thinks success is a stable system, you don't have a project, you have two projects pulling against each other. Aligning those expectations early, and writing the agreed success criteria into the charter, saves weeks of conflict later.`],
        terms: [[`Stakeholder register`,`A list of stakeholders with their interests, influence, and engagement levels.`],[`Power and interest grid`,`A tool that groups stakeholders by their authority and their concern about the project.`]],
        exam: `The exam loves "the PM just discovered a new stakeholder." The answer is to update the stakeholder register and assess their needs, not to ignore them because planning is done.` },
      { h: `Inheriting a project in trouble`,
        body: [`When you take over a project already in motion, the PMI mindset is consistent: assess before you act. Review the existing documents, talk to the people closest to the work, and form your own picture. Only then re-plan, escalate, or change course. Announcing changes on day one, or telling the sponsor the date is impossible before you have data, both fail the same test. You haven't earned the information yet.`],
        terms: [[`Progressive elaboration`,`Adding detail to the plan as more information becomes available.`]],
        exam: `For "what should the PM do first" questions, look for the option that gathers information or reviews documents before making a big decision.` }
    ],
    video: [`xvj0bbOfyTg`,`What is a Project Charter? Explained in 4 Minutes`,`Max Mao`,`4:39`]
  },
  scenes: [
    { id:`f1s1`, domain:`Process`, task:`R9`, title:`Day one`,
      text:(s,all,G)=>[`Elena didn't sit down. <span class="said" data-who="Elena">"You've run our data centers for three years and I have never once had to think about them. That's what I need on Cascade. You start today."</span>`,`Sam said he'd never run a software project. Elena said she knew. By 9:15 he was back at his desk with a calendar full of meetings the last PM had left behind, a shared drive of forty folders, and a Slack channel with three hundred unread messages. Elena wanted an update Friday.`,`What does Sam do first?`],
      opts:[
        {t:`Rebuild the schedule from scratch this week so it shows where things really stand.`, s:1, d:{trust:-2,conf:0,health:2},
          after:`Sam spends two days in a spreadsheet. The new schedule looks clean. On Wednesday two engineers point out dependencies he couldn't have known about, and he starts over.`,
          why:`A new plan is coming, but not yet. You can't re-plan what you don't understand, and the people who know the real state of the work haven't been heard. Building before gathering information is almost always the wrong first move.`},
        {t:`Read the key documents, then meet each lead one on one to learn the real status.`, s:3, best:true, d:{trust:6,conf:1,health:3},
          after:`Sam reads the contract, the statement of work, and whatever passes for a plan. Then he gives each lead thirty minutes and mostly listens. By Wednesday he has a page of notes that doesn't match the status reports at all.`,
          why:`This is the PMI pattern when you inherit a project: assess before acting. Review what exists, talk to the people closest to the work, and form your own picture. On a project already in motion, understanding the real status is the first deliverable.`},
        {t:`Tell Elena that fourteen weeks can't be done, before her expectations harden.`, s:0, d:{trust:0,conf:-6,health:0},
          after:`Elena's jaw tightens. <span class="said" data-who="Elena">"Based on what?"</span> Sam doesn't have an answer. Now the CEO thinks her new project lead is a pessimist.`,
          why:`Maybe it is impossible. You don't know yet, and neither does anyone you'd tell. Escalating without data costs credibility you'll need later. Bring evidence and options, not a gut feeling.`},
        {t:`Ask the last PM's manager for a full handoff briefing and wait for it first.`, s:0, d:{trust:0,conf:-1,health:-2},
          after:`The manager is on vacation until next Wednesday. Sam loses three days waiting for a briefing from someone who barely knew the project.`,
          why:`Getting context from people is good, but waiting on one person while the work sits idle isn't. The information you need is in the documents and in the team. Go get it.`}
      ]},
    { id:`f1s2`, domain:`Business Environment`, task:`B1`, title:`The missing charter`,
      text:(s,all,G)=>[`In folder thirty-one Sam finds the signed contract and a statement of work written by the sales team. He does not find a project charter. Nothing says who the sponsor is, what he's allowed to decide, or what success means beyond a date.`,`Lena Cho, the CTO, shrugs when he asks. <span class="said" data-who="Lena">"We've never really done charters. Grant's contract kind of is the charter."</span> She says it kindly. Lena says most things kindly, and avoids most things that might start an argument.`],
      opts:[
        {t:`Treat the signed contract as the charter, since it binds both companies legally.`, s:0, d:{trust:0,conf:-2,health:-3},
          after:`The contract tells Sam what Halcyon owes Cascade. It doesn't tell anyone inside Halcyon that Sam can pull an engineer off another project. The first time he tries, the other manager says no and nobody overrules him.`,
          why:`A contract defines obligations to the customer. A charter authorizes the project inside your own organization and gives the PM authority. They do different jobs, and you need both.`},
        {t:`Draft a short charter naming Elena as sponsor and his authority, then get it signed.`, s:3, best:true, d:{trust:2,conf:4,health:4},
          after:`It's two pages: objectives, success criteria, milestones, budget, key stakeholders, his authority. Elena changes one line about spending limits and signs it Thursday. Later that week, when Sam needs time from another team, he points to page one and the conversation takes five minutes.`,
          why:`The sponsor issues the charter, often with the PM drafting it. Even mid-flight, creating one is right. It fixes who decides, what success means, and where your authority comes from.`},
        {t:`Skip the charter for now and put every hour into delivery, since the date is tight.`, s:0, flag:`nocharter`, d:{trust:0,conf:-1,health:-4},
          after:`Sam saves a day. Over the next month he loses far more than that to arguments about who owns what and who can approve what.`,
          why:`"No time for process" is a classic exam trap. Lightweight is fine and tailoring is good. Having no authorization and no agreed success criteria isn't tailoring. It's unmanaged risk.`},
        {t:`Ask Lena to write the charter, since engineering owns most of the work and people.`, s:1, d:{trust:0,conf:0,health:1},
          after:`Lena agrees, then doesn't do it. Two weeks later it's still on her list under three other things she's avoiding.`,
          why:`Close, but the charter comes from the sponsor, and the CTO isn't the sponsor here. Handing it off also leaves your own authority undefined. Draft it and get the sponsor to sign.`}
      ]},
    { id:`f1s3`, domain:`People`, task:`P4`, title:`Who matters here`,
      text:(s,all,G)=>[`By Tuesday Sam has a list of names longer than his rack inventory. Elena. Grant. Lena. Theo Lindqvist, the ML platform lead, who seems to touch everything. A CIO at Cascade named Dr. Raymond Ochoa. A data labeling vendor called LabelForge. A colocation provider called IronPeak. Cascade's security office. Somebody in Cascade nursing leadership nobody can name.`,`He has an hour before his next meeting.`],
      opts:[
        {t:`Start a stakeholder register listing each person's interest, influence, and stake.`, s:3, best:true, d:{trust:1,conf:3,health:2},
          after:`It takes forty minutes. Plotting them on a power and interest grid shows him something uncomfortable: the two people with the most power over the outcome, Elena and Ochoa, are the two he hasn't really talked to yet.`,
          why:`Identify stakeholders early and record them with their interest, influence, and current versus desired engagement. That register drives how you engage each one. It's a living document, not a one-time list.`},
        {t:`Focus on the internal team first and deal with Cascade people once the plan is set.`, s:0, d:{trust:1,conf:-4,health:0},
          after:`Two weeks later Cascade's security office sends a forty-page questionnaire that gates go-live. Nobody at Halcyon knew they were a stakeholder.`,
          why:`External stakeholders don't wait for your plan. Missing one early is how surprises show up late. Identify all of them, inside and outside the company, from the start.`},
        {t:`Ask Grant for the Cascade org chart, since he knows everyone on the customer side.`, s:1, d:{trust:0,conf:1,health:0},
          after:`Grant sends a slide from the sales deck. It lists executives who signed the deal and nobody who will actually use the system.`,
          why:`Getting input from people who know the customer is useful, but a sales org chart isn't a stakeholder analysis. You still need to identify everyone affected, including users, and assess each one.`},
        {t:`Email every name on the list a project intro and ask them to confirm their role.`, s:0, d:{trust:0,conf:-1,health:0},
          after:`Six people reply. Two of them ask what Halcyon is. Ochoa doesn't reply at all.`,
          why:`Blasting everyone the same message isn't engagement. You first need to understand who matters most and how, then tailor how you engage each one.`}
      ]},
    { id:`f1s4`, domain:`People`, task:`P3`, title:`Meeting the team`,
      text:(s,all,G)=>[`The Cascade team is forty people across engineering, data, and infrastructure. They just lost their PM with no warning. Rumors in Slack range from "the project's cancelled" to "Sam's a hatchet man from ops."`,`Lena suggests he do something to reset the mood.`],
      opts:[
        {t:`Call an all-hands, introduce himself as the new lead, and set how work runs now.`, s:0, flag:`allhands`, d:{trust:-6,conf:1,health:0},
          after:`Sam stands up in front of forty people and lays out how things will run. The room is polite. Slack goes quiet for the rest of the day, which is worse than complaints.`,
          why:`Authority from a title is the weakest kind you have. The team is waiting to see who you are. Announcing control before listening tells them exactly that. Servant leadership earns it by understanding them first.`},
        {t:`Hold short listening sessions with each team and ask what's in their way.`, s:3, best:true, d:{trust:7,conf:0,health:3},
          after:`Sam runs five forty-minute sessions and talks for maybe five minutes in each. He leaves with a list of nineteen blockers, three of which he can fix by Friday. He fixes them by Thursday.`,
          why:`Servant leadership starts with listening and removing obstacles. Asking what's in the way, then actually clearing some of it fast, builds trust far quicker than any announcement.`},
        {t:`Send a warm intro email and let people come to him when they need something.`, s:1, d:{trust:1,conf:0,health:0},
          after:`The email is fine. Almost nobody comes to him. The people who need help most are the least likely to ask a stranger.`,
          why:`Being approachable is good, but passive. A new leader on a troubled project should go to the team, not wait for the team to come.`},
        {t:`Ask Lena to reassure the team, since they already know her and trust her well.`, s:0, d:{trust:-1,conf:0,health:0},
          after:`Lena posts a kind message in Slack. The rumors keep going. People want to hear from the person who's actually running the project.`,
          why:`Borrowing someone else's trust doesn't build your own. The team needs to know their project lead, and that's work only you can do.`}
      ]},
    { id:`f1s5`, domain:`People`, task:`P1`, title:`Why it matters`,
      text:(s,all,G)=>[`In one of the listening sessions, a data engineer named Priya Shah says something quietly that sticks with Sam. <span class="said" data-who="Priya">"I don't actually know why the date is the date. Or what happens to anyone if we miss it. It just feels like a number."</span>`,`Nobody in the room disagrees.`],
      opts:[
        {t:`Explain the contract penalties so the team understands what's at stake financially.`, s:1, d:{trust:0,conf:0,health:1},
          after:`The team now knows about the penalties. They're more anxious, not more motivated.`,
          why:`Honesty about stakes is good, but fear isn't a vision. A common vision explains the why in terms people can believe in, including who benefits, not just what it costs to fail.`},
        {t:`Work with the leads to write a short vision of who this helps and what success means.`, s:3, best:true, d:{trust:5,conf:2,health:3},
          after:`They land on two sentences: nurses at Cascade spend almost three hours a shift on documentation, and this gives some of that time back to patients. Success is clinicians trusting the drafts enough to use them. Priya pins it in the channel. People start quoting it.`,
          why:`Developing a common vision is a People task on the current exam. Build it with the team, tie it to real value for real people, and connect it to clear success criteria. A shared why holds a team together under pressure.`},
        {t:`Tell the team the date is set by contract and the reasons aren't theirs to worry about.`, s:0, d:{trust:-5,conf:0,health:-1},
          after:`Priya nods and stops asking questions. So does everyone else.`,
          why:`Shutting down "why" questions kills engagement. People do better work when they understand the purpose. Keeping the team in the dark is the opposite of servant leadership.`},
        {t:`Ask Elena to record a short video about the company's mission and share it with all.`, s:0, d:{trust:0,conf:0,health:0},
          after:`Elena's video is polished and about the whole company. It says nothing about Cascade or about anyone's work this week.`,
          why:`A generic mission message isn't a project vision. The team needs a vision for this project, built with them and tied to what they're actually doing.`}
      ]},
    { id:`f1s6`, domain:`Business Environment`, task:`B3`, title:`The promise on the call`,
      text:(s,all,G)=>[`Thursday afternoon Sam joins Grant on a call with Cascade's project team. It's friendly until a nursing director asks whether the agents can also draft patient discharge instructions.`,`Grant doesn't hesitate. <span class="said" data-who="Grant">"Absolutely. We can make that happen for go-live."</span>`,`Sam has read the statement of work twice. Discharge instructions aren't in it, and nobody has estimated them.`],
      opts:[
        {t:`Correct Grant politely on the call so Cascade doesn't leave with the wrong idea.`, s:1, d:{trust:0,conf:-5,health:1},
          after:`The call goes cold. Grant smiles through it and doesn't speak to Sam for two days.`,
          why:`Right instinct, costly method. Contradicting a senior colleague in front of the customer damages a relationship you'll need. Handle it privately, then fix the commitment through the proper process.`},
        {t:`Say nothing, then add discharge instructions to the backlog to keep Cascade happy.`, s:0, d:{trust:-2,conf:1,health:-6},
          after:`Three engineers quietly start on discharge instructions. Two planned features slip and nobody decided that they should.`,
          why:`That's scope creep: new work added with no analysis and no approval. Sooner or later the schedule pays. Every change needs an impact assessment and a decision.`},
        {t:`Let it pass on the call, then raise it privately with Grant and log a change request.`, s:3, best:true, d:{trust:2,conf:3,health:4},
          after:`After the call Sam walks Grant through the statement of work. Grant pushes back, then agrees to a change request. The analysis says six weeks of work. Cascade gets a formal answer: discharge instructions in a phase two, with a price.`,
          why:`Protect the relationship in public, address it in private, then use change control. Analyze the impact before anything is approved. That's the sequence the exam expects.`},
        {t:`Email Elena after the call that Grant is promising work the contract doesn't cover.`, s:0, d:{trust:-2,conf:-2,health:0},
          after:`Elena forwards the email to Grant. Now Sam has an enemy in the C-suite in his first week.`,
          why:`Going over someone's head before talking to them breaks trust and skips the change process entirely. Talk to the person first.`}
      ]},
    { id:`f1s7`, domain:`Business Environment`, task:`B1`, title:`Who decides`,
      text:(s,all,G)=>[`The discharge instructions question exposes a bigger problem. Sam asks four people who can approve a scope change on Cascade. He gets four different answers: Elena, Grant, Lena, and "whoever's loudest."`,`Change requests are going to keep coming. Cascade is a big customer with a lot of opinions.`],
      opts:[
        {t:`Set up a small change board with Elena, Lena, and Grant, plus approval limits.`, s:3, best:true, d:{trust:2,conf:3,health:4},
          after:`Elena agrees on the spot. They meet thirty minutes each Tuesday. Sam can approve small changes under a set threshold himself; anything touching the date, budget, or contract goes to the board. The arguments about who decides stop.`,
          why:`Defining governance means setting decision rights, thresholds, and an escalation path before the fights start. A change control board with clear limits is a standard, effective structure.`},
        {t:`Decide every scope change himself, since he's accountable for delivering it all.`, s:0, d:{trust:-2,conf:-2,health:-1},
          after:`The first time Sam turns down a request Grant made to Cascade, Grant goes straight to Elena and gets it reversed. Sam's authority takes a visible hit.`,
          why:`The PM is accountable for the process, not for every decision. Changes that affect contracts, dates, or money need the right governance level. Taking all of it on yourself sets you up to be overruled.`},
        {t:`Send every change to Elena so the CEO always makes the final call on Cascade.`, s:1, d:{trust:0,conf:0,health:-2},
          after:`Elena's inbox fills with small requests. Decisions take a week. Grant starts making promises anyway because waiting is slower than asking forgiveness.`,
          why:`Escalating to the sponsor is right for big decisions, but sending everything up creates a bottleneck. Good governance sets thresholds so small things move fast and big things get the right eyes.`},
        {t:`Wait until a few more change requests arrive, then design a process from patterns.`, s:0, d:{trust:0,conf:-1,health:-2},
          after:`Three more requests arrive in a week. Each one is handled differently, and two contradict each other.`,
          why:`Governance is cheapest before conflict. Waiting for patterns means the patterns are fights. Set decision rights early and refine them later.`}
      ]},
    { id:`f1s8`, domain:`People`, task:`P4`, title:`The silent CIO`,
      text:(s,all,G)=>[`Ruth Calder calls Thursday evening. Sam has never met her. She introduces herself as a Halcyon board member, retired from NASA, where she spent twenty years as a flight director. <span class="said" data-who="Ruth">"Elena asked me to keep an eye on you,"</span> she says. <span class="said" data-who="Ruth">"Don't worry. I mostly ask annoying questions. Here's the first one. Have you talked to Raymond Ochoa yet?"</span>`,`He hasn't. Ochoa signed the deal. According to his assistant, nobody from Halcyon has spoken with him in three weeks, and he's started asking his team whether Halcyon is in trouble.`],
      opts:[
        {t:`Hold off on contacting Ochoa until there's real progress and good news to share.`, s:0, d:{trust:0,conf:-6,health:0},
          after:`Ochoa calls Elena directly on Monday. Elena calls Sam. It isn't a good call.`,
          why:`Silence lets stakeholders fill the gap with their worst guess. Proactive, honest communication, especially when things are uncertain, keeps engagement and trust high.`},
        {t:`Call Ochoa, give an honest status with the risks, and agree how they'll talk.`, s:3, best:true, d:{trust:1,conf:7,health:1},
          after:`The call runs forty minutes. Ochoa appreciates that Sam names the problems before he has to ask. They agree on a weekly fifteen-minute call and a one-page status every Friday. Ochoa ends with, <span class="said" data-who="Ochoa">"First time I've felt like I know what's going on."</span>`,
          why:`Engage key stakeholders early and directly, be transparent about risk, and agree on a communication approach that fits them. That's stakeholder engagement and communication planning in one move.`},
        {t:`Send Ochoa a detailed status email with the full project plan and risk log attached.`, s:1, d:{trust:0,conf:2,health:0},
          after:`Ochoa's assistant replies that he'll review it. He doesn't.`,
          why:`Information sent isn't communication received. An anxious senior stakeholder needs a conversation, and you need to learn how he wants to hear from you.`},
        {t:`Ask Grant to call Ochoa, since Grant owns the relationship and closed the deal.`, s:1, d:{trust:0,conf:1,health:0},
          after:`Grant calls Ochoa and says everything is on track. That isn't quite true, and Sam now owns a promise he didn't make.`,
          why:`The account owner should stay involved, but the customer needs to hear about delivery from the person accountable for it. Keep Grant in the loop, and own the delivery conversation yourself.`}
      ]},
    { id:`f1s9`, domain:`Process`, task:`R1`, title:`A plan by Friday`,
      text:(s,all,G)=>[`Elena messages Wednesday night: <span class="said" data-who="Elena">"For Friday I need the full plan. Every task, every date, through go-live."</span>`,`Sam knows the infrastructure work well enough to plan it in detail. The software work is different. Cascade's clinicians haven't seen a single demo yet, and their feedback will reshape half the backlog.`],
      opts:[
        {t:`Build a fully detailed task schedule for all fourteen weeks to meet the request.`, s:0, d:{trust:-2,conf:1,health:-3},
          after:`Sam stays up until two building it. By week three, a third of the software tasks are wrong, and he's spending hours a week updating a plan nobody trusts.`,
          why:`Detailing work you can't yet see gives false precision. The plan looks complete and isn't. Plan the near term in detail and the far term at a higher level.`},
        {t:`Plan near-term work in detail, later phases at milestone level, and explain why.`, s:3, best:true, d:{trust:1,conf:4,health:4},
          after:`Friday, Sam shows Elena a plan with the next six weeks in detail and the rest as dated milestones, plus a note on when each phase will be detailed. Elena pushes, then accepts it. <span class="said" data-who="Elena">"As long as the milestones are real."</span>`,
          why:`This is rolling wave planning, a form of progressive elaboration. You detail what you can see clearly and refine the rest as you learn. It's honest, and it's what the integrated plan should look like on a hybrid project.`},
        {t:`Tell Elena a full plan isn't possible yet and ask for three more weeks to build one.`, s:0, d:{trust:0,conf:-4,health:0},
          after:`Elena gives him one week and tells him she expected more.`,
          why:`You can always provide a plan with the information you have, and state the uncertainty. Refusing to plan until everything is known isn't an option on a fourteen-week project.`},
        {t:`Reuse the departed PM's old schedule with updated dates so Elena has something now.`, s:1, d:{trust:0,conf:1,health:-1},
          after:`The old schedule gets Sam through Friday. By next Friday nobody can explain where half its dates came from.`,
          why:`Starting from existing material saves time, but a plan you don't understand can't be defended or managed. Use what helps, and rebuild the parts you can't stand behind.`}
      ]},
    { id:`f1s10`, domain:`Business Environment`, task:`B4`, title:`Everything goes through Theo`,
      text:(s,all,G)=>[`Every thread Sam pulls leads to the same name. Theo Lindqvist is assigned to eleven of the fourteen critical tasks. He's the only person who can deploy model updates, and he answers support questions for three other customers.`,`At standup Theo says he's fine. He looks like he hasn't slept since Labor Day. Sam recognizes the look. He used to see it on crew chiefs during a surge, right before somebody made a mistake on a jet.`],
      opts:[
        {t:`Ask Theo to cover weekends until go-live, with comp time and a bonus once it ships.`, s:0, d:{trust:-5,conf:0,health:-2},
          after:`Theo says yes. He'd say yes to anything. His error rate climbs, and in week three a bad deploy takes the demo environment down for a day.`,
          why:`Adding hours to a bottleneck makes it worse, not better. Protect the constraint, reduce the work flowing to it, and spread the knowledge.`},
        {t:`Route Theo's requests through Sam, cut his open work, and pair Priya with him.`, s:3, best:true, d:{trust:5,conf:1,health:6},
          after:`Theo's queue drops from nineteen items to six. Priya shadows him on every deploy and writes the runbook as she goes. Theo stops answering Slack at midnight. He doesn't say thank you, but he brings Sam a coffee on Friday.`,
          why:`You removed an impediment: you protected the constraint, limited work in progress, and started knowledge transfer so one person stops being a single point of failure. That's servant leadership in practice.`},
        {t:`Take Theo off Cascade for two weeks so he can rest before the busy stretch hits.`, s:0, d:{trust:-1,conf:-2,health:-6},
          after:`Theo is relieved for about an hour. Then three critical tasks stop moving because nobody else knows how they work.`,
          why:`Pulling the only person who knows the system, without a transition plan, creates a crisis. The problem is overload and concentration, not Theo himself.`},
        {t:`Escalate to Lena, as Theo's manager, and ask her to rebalance his workload now.`, s:1, d:{trust:0,conf:0,health:1},
          after:`Lena promises to look at it. She talks to Theo, who tells her he's fine.`,
          why:`Escalation is sometimes right, but this one is in your lane. Act on what you can control first, then escalate what you can't.`}
      ]},
    { id:`f1s11`, domain:`People`, task:`P5`, title:`Two kinds of success`,
      text:(s,all,G)=>[`At Tuesday's first change board, it becomes clear Grant and Lena are running different projects. Grant thinks success is going live on the contract date, full stop. Lena thinks success is a system clinicians will trust, and she'd rather slip than ship something shaky. Neither has said this to the other.`,`Elena looks at Sam. <span class="said" data-who="Elena">"Well?"</span>`],
      opts:[
        {t:`Side with Lena, since a shaky system would hurt Halcyon more than a late one.`, s:0, d:{trust:-2,conf:-3,health:1},
          after:`Grant feels ambushed. He spends the next week lobbying Elena around Sam.`,
          why:`Taking a side isn't aligning expectations. Both views have merit, and the PM's job is to surface them and get an agreed definition of success, not to pick a winner.`},
        {t:`Get both views on the table and agree measurable success criteria with Elena.`, s:3, best:true, d:{trust:4,conf:4,health:3},
          after:`It takes forty minutes. They agree success means three hospitals live on the contract date with clinician acceptance above an agreed threshold, and the rest within four weeks. Sam writes it into the charter. Grant and Lena both sign it.`,
          why:`Aligning stakeholder expectations means making hidden differences visible and agreeing on measurable success criteria. Write them down where everyone can see them.`},
        {t:`Suggest each leader write their own success measures and track them separately.`, s:0, d:{trust:0,conf:-1,health:-2},
          after:`Now there are two scorecards that contradict each other, and every status meeting turns into a debate about which one counts.`,
          why:`Separate definitions of success guarantee conflict. The project needs one agreed set of success criteria.`},
        {t:`Note the disagreement and take it offline with each leader one at a time later.`, s:1, d:{trust:1,conf:0,health:0},
          after:`The one-on-ones help Sam understand both of them. They don't produce an agreement, because the two never hear each other.`,
          why:`Private conversations can help, but alignment needs the stakeholders to agree together. Use the one-on-ones to prepare, then bring them to a shared decision.`}
      ]},
    { id:`f1s12`, domain:`People`, task:`P6`, title:`Friday, 4 PM`,
      text:(s,all,G)=>[`Elena's office again. <span class="said" data-who="Elena">"So. Will we hit the date?"</span>`,`Sam has a week of real data now. With the LabelForge delay, the security review, and integration work that has to move earlier, his forecast says eighteen weeks, not fourteen. There are ways to close the gap. None of them are free.`,(G.nocharter?`He also has no signed charter to point to when he says what success means. That makes this harder.`:`He has the signed charter in his folder, with success criteria Elena herself approved.`)],
      opts:[
        {t:`Say yes. It's week one, the team needs confidence, and there's time to recover.`, s:0, d:{trust:-2,conf:-8,health:-4},
          after:`Elena smiles and tells the board on Tuesday that Cascade is on track. Sam spends the weekend not sleeping.`,
          why:`Telling the sponsor what they want to hear is the most expensive thing a PM can do. The gap doesn't close because you hid it. It surfaces later, when there are fewer options.`},
        {t:`Show the eighteen week forecast and its causes, give options, and let Elena decide.`, s:3, best:true, d:{trust:2,conf:6,health:5},
          after:`Elena reads the page twice. She doesn't like it. Then she chooses a phased release: core agents live at three hospitals on the contract date, the other eight over four weeks. <span class="said" data-who="Elena">"Get Grant in here,"</span> she says. <span class="said" data-who="Elena">"He's going to hate this."</span>`,
          why:`Give the sponsor an honest, data-based forecast, explain the drivers, and bring options with tradeoffs. The decision belongs to the sponsor. Your job is to make it an informed one.`},
        {t:`Say no, the date can't be met, and recommend Elena tell Cascade it will slip.`, s:1, d:{trust:0,conf:-2,health:2},
          after:`Elena asks if there's any other way. Sam realizes he should have led with options.`,
          why:`Honest, but incomplete. Jumping to one recommendation skips the choices a sponsor needs to weigh. Bring options, not a verdict.`},
        {t:`Ask for two more weeks of data before committing to any forecast at all.`, s:0, d:{trust:0,conf:-4,health:-2},
          after:`Elena gives him one week, and tells him she expected more.`,
          why:`You have enough data to forecast with stated uncertainty. Waiting for perfect information burns the time the sponsor needs to act.`}
      ]}
  ],
  exercise: { after:`f1s9`, title:`Which document is it?`, intro:`New PMs mix these up. Match each description to the right document.`,
    items:[
      {prompt:`Formally authorizes the project and gives the project manager authority to use resources.`, choices:[`Project charter`,`Contract`,`Business case`,`Project management plan`], answer:0, why:`The charter, issued by the sponsor, authorizes the project and the PM.`},
      {prompt:`Legally binds Halcyon to deliver agreed work to Cascade by a set date.`, choices:[`Project charter`,`Contract`,`Business case`,`Project management plan`], answer:1, why:`The contract defines obligations between two organizations. It doesn't authorize anything inside Halcyon.`},
      {prompt:`Explains why the investment is worth it, with expected costs and benefits.`, choices:[`Project charter`,`Contract`,`Business case`,`Project management plan`], answer:2, why:`The business case is the economic justification. The charter often references it.`},
      {prompt:`Describes how the project will be executed, monitored, controlled, and closed, with baselines.`, choices:[`Project charter`,`Contract`,`Business case`,`Project management plan`], answer:3, why:`The project management plan is the detailed, integrated plan built after the charter.`},
      {prompt:`Lists who is affected by the project, their influence, and how engaged they are.`, choices:[`Stakeholder register`,`Risk register`,`Issue log`,`Change log`], answer:0, why:`The stakeholder register records stakeholders and their engagement.`},
      {prompt:`Records every requested change and whether it was approved or rejected.`, choices:[`Stakeholder register`,`Risk register`,`Issue log`,`Change log`], answer:3, why:`The change log tracks change requests and their status.`}
    ]},
  quiz: [
    {q:`A project manager is assigned to a project already underway after the previous PM left suddenly. What should the project manager do first?`, opts:[`Re-baseline the schedule using the team's latest estimates`,`Review project documents and meet key team members`,`Inform the sponsor the project is likely to be late`,`Hold a kickoff meeting to reset expectations for all`], a:1, why:`On an inherited project, assess before acting. Review what exists and learn the real status from the people doing the work.`, task:`R9`, domain:`Process`},
    {q:`Who typically issues the project charter?`, opts:[`The project manager, once planning is complete`,`The customer, as part of the signed contract`,`The project sponsor or initiator with authority`,`The PMO, after the business case is approved`], a:2, why:`The sponsor issues the charter, which authorizes the project. The PM may draft it.`, task:`B1`, domain:`Business Environment`},
    {q:`A project manager can't get engineers released from another team because no one recognizes the project's authority. What is the most likely cause?`, opts:[`The project was started without an approved charter`,`The resource calendar hasn't been fully updated yet`,`The stakeholder register is missing several names`,`The work breakdown structure has too little detail`], a:0, why:`The charter gives the PM authority to use organizational resources. Without it, requests have no standing.`, task:`B1`, domain:`Business Environment`},
    {q:`During a customer call, a senior salesperson promises a feature that isn't in scope. What should the project manager do?`, opts:[`Correct the salesperson on the call to keep expectations accurate`,`Add the feature to the backlog so the customer stays satisfied`,`Discuss it privately with the salesperson and follow change control`,`Report the salesperson to the sponsor right after the call ends`], a:2, why:`Address it privately, then route it through change control with an impact analysis. Don't contradict a colleague in front of the customer.`, task:`B3`, domain:`Business Environment`},
    {q:`A project manager learns that a new department will be affected by the project midway through execution. What should the PM do first?`, opts:[`Continue as planned, since the stakeholder analysis is complete`,`Ask the sponsor whether the department should be included`,`Update the stakeholder register and assess their interests`,`Send the department head the current project status report`], a:2, why:`Stakeholder identification is ongoing. Add them to the register and assess their needs and influence.`, task:`P4`, domain:`People`},
    {q:`Early in a project, the project manager wants the team and key stakeholders to share one picture of success. Which approach best develops a common vision?`, opts:[`Draft the vision alone and send it out for everyone to acknowledge`,`Wait until the plan is baselined, then write a vision that fits it`,`Build it with team leads and stakeholders, tied to success criteria`,`Adopt the company mission statement as the vision for this project`], a:2, why:`A common vision is built with the people who have to carry it, early, and tied to measurable success criteria in the charter. A memo, a borrowed mission statement, or a vision written after planning won't hold the team together.`, task:`P1`, domain:`People`},
    {q:`Two senior stakeholders define project success differently. One cares most about the date, the other about quality. What should the project manager do?`, opts:[`Support the stakeholder with more authority over the budget`,`Facilitate agreement on measurable shared success criteria`,`Track both definitions and report on each one separately`,`Escalate the disagreement to the steering committee to decide`], a:1, why:`Aligning expectations means surfacing differences and agreeing on one measurable definition of success.`, task:`P5`, domain:`People`},
    {q:`Which is the best description of project governance?`, opts:[`The set of templates the PMO requires for each project phase`,`The framework of decision rights, oversight, and escalation`,`The process for collecting requirements from stakeholders`,`The plan describing how the team will communicate status`], a:1, why:`Governance defines who decides what, how decisions are made, and how issues escalate.`, task:`B1`, domain:`Business Environment`},
    {q:`The sponsor asks for a fully detailed schedule for a 14-week hybrid project, but software requirements will change after early demos. What should the PM provide?`, opts:[`A detailed schedule for every task, updated weekly as needed`,`A rolling wave plan with near-term detail and later milestones`,`A request for more time until all requirements are confirmed`,`The previous project manager's schedule with revised dates`], a:1, why:`Rolling wave planning details what is known now and elaborates the rest as information becomes available.`, task:`R1`, domain:`Process`},
    {q:`One team member is assigned to most critical tasks and is visibly exhausted. What should the project manager do first?`, opts:[`Ask the team member to work extra hours until the crunch is over`,`Remove the team member from the project so they can recover`,`Reduce their work in progress and start knowledge transfer`,`Ask the functional manager to address the person's workload`], a:2, why:`Protect the bottleneck, limit work in progress, and spread knowledge so one person isn't a single point of failure.`, task:`B4`, domain:`Business Environment`},
    {q:`A key customer executive hasn't heard from the project in three weeks and is worried. What should the project manager do?`, opts:[`Wait until there is positive progress to report to the executive`,`Send the full project plan and risk register by email right away`,`Ask the account manager to reassure the executive about progress`,`Meet the executive, share honest status, and agree how to stay in touch`], a:3, why:`Engage directly and transparently, and agree on a communication approach that fits the stakeholder.`, task:`P4`, domain:`People`},
    {q:`The sponsor asks if the project will meet its date. The PM's forecast shows a four-week slip. What should the PM do?`, opts:[`Present the forecast, its causes, and options for the sponsor`,`Say the date is still achievable to protect team morale for now`,`Recommend telling the customer now that the project will be late`,`Ask for more time to gather better data before giving a forecast`], a:0, why:`Be transparent, explain the drivers, and give the sponsor options with tradeoffs. The sponsor decides.`, task:`P6`, domain:`People`},
    {q:`Which statement best distinguishes a project from operations?`, opts:[`Projects are larger in budget than ongoing operational work`,`Projects are temporary and unique; operations are ongoing`,`Projects need a sponsor; operations need a functional manager`,`Projects use agile methods while operations use predictive`], a:1, why:`A project is temporary and produces a unique result. Operations sustain the business through repeated work.`, task:`R1`, domain:`Process`},
    {q:`A new project manager wants to build trust with a team that recently lost its PM. Which approach best reflects servant leadership?`, opts:[`Announce new ground rules at an all-hands meeting this week`,`Send an introduction email and keep an open-door policy`,`Ask the team's former lead to vouch for the new manager`,`Meet the team to listen and remove obstacles they raise`], a:3, why:`Servant leadership starts with listening and removing impediments, earning trust through action.`, task:`P3`, domain:`People`},
    {q:`A stakeholder with high power and low interest in the project should generally be:`, opts:[`Managed closely with frequent detailed updates`,`Kept satisfied without overloading them with detail`,`Kept informed through regular general communication`,`Monitored with minimal effort until interest changes`], a:1, why:`On a power and interest grid, high power and low interest means keep satisfied.`, task:`P4`, domain:`People`}
  ],
  closing:(s,all,G)=>[
    `Saturday morning Sam drives to Golden to meet Ruth Calder in person for the first time. She's already at a corner table in a coffee shop near the creek, reading the one-page plan he gave Elena, with notes in the margins in green ink.`,
    `She's smaller than he expected, with short white hair and a windbreaker that says JSC on it. <span class="said" data-who="Ruth">"You're the Air Force guy,"</span> she says. <span class="said" data-who="Ruth">"Good. Maintainers don't lie to pilots. The ones who do don't last."</span>`,
    `She taps the page. <span class="said" data-who="Ruth">"At NASA everybody quotes 'failure is not an option.' Nobody remembers that it only worked because the flight directors told the truth about the numbers every single day. The optimists didn't get people home. The honest ones did."</span> She doesn't explain how she knows. Sam gets the sense there's a story there, and that she isn't ready to tell it.`,
    (s.score>=27?`<span class="said" data-who="Ruth">"You did that this week,"</span> she says. <span class="said" data-who="Ruth">"Most people in your chair don't."</span>`:`<span class="said" data-who="Ruth">"You're learning,"</span> she says. <span class="said" data-who="Ruth">"Next week, listen first and decide second. The team will tell you what's wrong if you let them."</span>`),
    `She hands him back the page. On the bottom, in green, she's written: <span class="said" data-who="Ruth">"Now build the real plan."</span>`,
    `At home that night Dana asks how the new job is. <span class="said" data-who="Sam">"It's a jet with no forms,"</span> Sam says. She laughs, then stops when she sees he means it.`,
    `Sunday night his phone buzzes. Hal Brennan, IronPeak. <span class="said" data-who="Hal">"Sorry, I know it's Sunday. Your GPU racks go in week three and nobody on your side ever sent me a power plan. Is there one?"</span> Sam opens his mouth to say yes. There isn't one.`
  ],
  episode:{src:`audio/full-ch01.mp3`, len:`about 35 minutes`},
  next:`The Plan`
});
