(window.HALCYON_FULL=window.HALCYON_FULL||[]).push({
  num: 2, part: `Part One: The Cascade Launch`, title: `The Plan`, weeks: `Weeks 1 to 2`,
  tasks: [`R1`,`R2`,`R8`,`B3`,`R9`],
  cast: [[`Hal Brennan`,`IronPeak account manager. Calls on Sundays.`]],
  opening: [
    `Sam didn't sleep much Sunday night. At 5 AM he was at the kitchen table with a legal pad, drawing boxes and arrows the way he used to sketch an engine change on the back of a work order.`,
    `On the flight line nobody did anything to an F-16 without the technical order open in front of them. The tech order told you what to do, in what sequence, with what tools, and what to check before you called it done. Ray Mendez used to tap the binder and say, <span class="said" data-who="Ray">"This isn't for you. It's for the guy who has to fix what you did."</span> Sam had always liked that. A plan wasn't a promise. It was a way to make sure the next person could see what you meant.`,
    `Cascade didn't have a tech order. It had a contract, a two-page charter Elena had signed on Thursday, and forty people who each carried a slightly different version of the project in their heads.`,
    `Dana came down at six, saw the legal pad, and poured him a coffee without comment. Then she looked closer. <span class="said" data-who="Dana">"Those arrows are going in circles."</span>`,
    `<span class="said" data-who="Sam">"That's the problem,"</span> Sam said.`,
    `By the time he got to LoDo he had a list. A scope statement nobody had written. A power plan IronPeak needed by Wednesday. A software backlog that lived in four different Jira projects. And estimates, which so far were mostly vibes.`,
    `Ruth texted at 7:40.`,
    `<prop type="text" from="Ruth Calder" time="7:40 AM"><span class="said" data-who="Ruth">A plan is a hypothesis. The launch is the experiment. Write it down so you can tell when you're wrong.</span></prop>`,
    `Sam read it twice, then put the phone face down and started writing.`
  ],
  lesson: {
    title: `Building the integrated plan: scope, estimates, and the schedule`,
    sections: [
      { h: `The integrated project management plan`,
        body: [`The project management plan is the master document that says how the project will be executed, monitored, controlled, and closed. It integrates subsidiary plans for scope, schedule, cost, quality, resources, communications, risk, procurement, and stakeholder engagement, plus the baselines. On a hybrid project it also says which parts run predictively and which run adaptively, and how they connect.`,
          `"Integrated" is the important word. A power plan from IronPeak, a test plan from engineering, and a release plan from product are all useless if they don't fit together. The PM's job is to make them one plan with one set of dates and one set of dependencies. When one part changes, the PM checks what it does to every other part. Once the scope, schedule, and cost baselines are approved, together they form the performance measurement baseline. That's what status gets measured against, and it's what integrated change control protects: any change that would move a baseline gets logged, analyzed for impact, and decided by the right authority before anyone acts on it.`],
        terms: [[`Baseline`,`The approved version of scope, schedule, or cost that performance is measured against. Changed only through change control.`],[`Tailoring`,`Choosing and adapting processes and practices to fit the project.`]],
        exam: `If a question describes a subsidiary plan that conflicts with another, the answer is to integrate them in the project management plan, not to pick one and ignore the other.` },
      { h: `Scope: statement, WBS, and backlog`,
        body: [`The project scope statement describes the scope, major deliverables, acceptance criteria, assumptions, constraints, and exclusions. Exclusions matter more than people think. Writing "discharge instructions are not in phase one" stops a lot of arguments before they start.`,
          `For predictive work, the work breakdown structure (WBS) decomposes the total scope into smaller pieces, ending in work packages that can be estimated, scheduled, and assigned. The 100 percent rule says the WBS includes all the work and only the work. A WBS dictionary describes each element. The scope baseline is the scope statement plus the WBS plus the WBS dictionary.`,
          `For adaptive work, scope lives in a product backlog: an ordered list of features and user stories, owned and prioritized by the product owner. It's expected to change. Detail is added just in time through refinement. A hybrid project like Cascade uses both: a WBS for the cluster and facilities, a backlog for the software.`, `Requirements come before scope. Collect them through interviews, workshops, focus groups, observation, and prototypes, then trace each one to the deliverable that satisfies it with a requirements traceability matrix. When a stakeholder later asks why a feature exists, or whether one was ever agreed, the traceability matrix answers in seconds. On adaptive work the same idea lives in the backlog: each story traces to a user need and carries acceptance criteria that say when it's done.`],
        terms: [[`Work package`,`The lowest level of the WBS, where cost and duration can be estimated and managed.`],[`Product backlog`,`An ordered list of work for an adaptive team, owned by the product owner.`],[`Scope creep`,`Uncontrolled growth in scope without adjusting time, cost, or resources.`]],
        exam: `"The 100 percent rule" and "decomposition" point to the WBS. "Prioritized by the product owner" points to the backlog. The PM doesn't own backlog priority on an agile team.` },
      { h: `Estimating`,
        body: [`Analogous estimating uses a similar past project; fast, less accurate. Parametric estimating uses a statistical relationship, like hours per rack times number of racks. Bottom-up estimating rolls up estimates from work packages; slow, more accurate. Three-point estimating uses optimistic (O), most likely (M), and pessimistic (P) values. The beta or PERT formula is (O + 4M + P) / 6, and the standard deviation is (P minus O) / 6. A triangular estimate is (O + M + P) / 3.`,
          `Adaptive teams often estimate in story points using relative sizing, for example planning poker, where the team estimates together and discusses outliers. The key principle on the exam: the people doing the work estimate it. A PM who cuts the team's estimates to hit a date hasn't shortened the work. They've only hidden the risk.`, `Estimates also need a basis. Write down the assumptions behind each one, such as which data set, which team, and which tools, so that when an assumption breaks you know which estimates to revisit. Uncertainty you can name belongs in contingency reserve, sized from the ranges in your three-point estimates and owned by the project manager. Uncertainty you can't name belongs in management reserve, held by the sponsor. Neither should be hidden inside individual task estimates.`],
        terms: [[`Padding`,`Adding hidden buffer to an estimate. Handle uncertainty with explicit reserves instead.`],[`Story points`,`A relative measure of effort and complexity used by agile teams.`]],
        exam: `PERT questions are common. Learn (O + 4M + P) / 6 and (P minus O) / 6 cold. One standard deviation covers about 68 percent of outcomes, two about 95 percent.` },
      { h: `The schedule and the critical path`,
        body: [`Activities connected by dependencies form a network. The critical path is the longest path through the network, and it sets the shortest possible project duration. Activities on it have zero total float: delay one, and the project slips. Total float is how long an activity can slip without delaying the project end. You find it by subtracting a path's length from the critical path length, or with a forward and backward pass.`,
          `When you need to shorten a schedule, there are two classic moves. Fast tracking runs activities in parallel that were planned in sequence; it adds risk and rework. Crashing adds resources to critical path activities; it adds cost. Only compress activities on the critical path, or you spend money and gain nothing.`],
        terms: [[`Critical path`,`The longest path through the schedule network; it determines project duration.`],[`Total float`,`The time an activity can be delayed without delaying the project finish.`],[`Fast tracking`,`Doing sequential work in parallel to save time, with added risk.`],[`Crashing`,`Adding resources to shorten critical activities, with added cost.`]],
        exam: `If a question asks how to shorten the schedule without adding cost, it's fast tracking. If it says money is available but no overlap is possible, it's crashing.` }
    ],
    video: [`Nui3YvFV64o`,`Calculating Critical Path with Forward and Backward Pass`,`David McLachlan`,`5:27`]
  },
  scenes: [
    { id:`f2s1`, domain:`Process`, task:`R1`, title:`The power plan`,
      text:(s,all,G)=>[`Hal Brennan from IronPeak wants the power plan by Wednesday or Cascade loses its week-three install window. Sam calls Lena. Lena says the engineers are focused on software and the power plan is "an infrastructure thing." The infrastructure team says they can't size power until engineering decides how many GPUs the models need.`,`Both are right. Neither is moving.`],
      opts:[
        {t:`Write the power plan himself tonight from what he knows about the old racks.`, s:1, d:{trust:0,conf:1,health:1},
          after:`Sam gets something to Hal by Wednesday. It's off by thirty percent because the new models need different cards, and IronPeak has to re-quote.`,
          why:`Meeting the deadline matters, but a subsidiary plan built without the people who know the inputs is a guess. Integration means getting the dependent decisions made together.`},
        {t:`Get engineering and infrastructure in one room to settle the GPU count and plan.`, s:3, best:true, d:{trust:4,conf:2,health:5},
          after:`It takes ninety minutes and a whiteboard. Engineering commits to a GPU count with a ten percent margin. Infrastructure sizes power from it. Hal gets a real plan Tuesday night, and the dependency goes into the integrated schedule with an owner.`,
          why:`Integrating the plan means connecting dependent decisions across teams. The PM convenes the people who own each input, gets the decision made, and puts the result into one plan.`},
        {t:`Ask Hal for a two-week extension so the teams have more time to agree.`, s:0, d:{trust:0,conf:-2,health:-4},
          after:`Hal can do it, but the next install window is week six. Two weeks of float disappear before the project has a schedule.`,
          why:`Asking for more time doesn't solve the problem, which is that two teams are waiting on each other. Resolve the dependency first. Extensions are a last resort when they cost the schedule.`},
        {t:`Escalate to Elena that Lena's team isn't supporting the infrastructure work.`, s:0, d:{trust:-3,conf:-1,health:0},
          after:`Elena tells Lena to help. Lena feels thrown under the bus. The GPU count still isn't decided.`,
          why:`This is a coordination gap you can close yourself. Escalating it as a people problem damages a relationship and doesn't make the decision.`}
      ]},
    { id:`f2s2`, domain:`Process`, task:`R2`, title:`What's in and what's out`,
      text:(s,all,G)=>[`Sam asks five people what's in scope for go-live. He gets five lists. Two include discharge instructions. One includes a mobile app nobody has ever mentioned to him. Grant's list says "whatever Cascade needs."`],
      opts:[
        {t:`Write a scope statement with deliverables, acceptance criteria, and exclusions.`, s:3, best:true, d:{trust:2,conf:3,health:5},
          after:`The statement runs three pages. Section five says, in bold, what's not in phase one: discharge instructions, the mobile app, and two analytics dashboards. Elena signs it. Grant grumbles and initials it.`,
          why:`A project scope statement defines deliverables, acceptance criteria, assumptions, constraints, and exclusions. Writing down what's out is as important as what's in.`},
        {t:`Let the team build the most-requested items first and settle scope as they go.`, s:0, d:{trust:0,conf:-2,health:-5},
          after:`The team builds two features that turn out to be out of contract, and a required integration slips.`,
          why:`Even adaptive work needs a clear vision and boundaries. "Build what's popular" with no agreed scope is how scope creep starts.`},
        {t:`Use the contract's statement of work as the scope and point people to it when asked.`, s:1, d:{trust:0,conf:1,health:1},
          after:`The statement of work helps, but it was written by sales and is vague in exactly the places people disagree.`,
          why:`The statement of work is a good input, but it isn't a full scope statement. You still need agreed deliverables, acceptance criteria, and exclusions for the team.`},
        {t:`Ask each lead to send their list, then merge all five into one master scope list.`, s:0, d:{trust:1,conf:-1,health:-3},
          after:`The merged list includes everything anyone ever wanted. Now the mobile app is officially in scope.`,
          why:`Merging every request isn't defining scope. Scope needs decisions, including what's excluded, approved by the right people.`}
      ]},
    { id:`f2s3`, domain:`Process`, task:`R2`, title:`Breaking down the cluster`,
      text:(s,all,G)=>[`For the infrastructure work, Sam starts a list of tasks: order cables, rack servers, run power, configure the network, test. It's sixty lines long and he's not sure it's complete.`,`Ruth looks at it over a video call. <span class="said" data-who="Ruth">"That's a to-do list. Where's the thing you're building?"</span>`],
      opts:[
        {t:`Keep the task list but add owners and dates so it works as a schedule for now.`, s:1, d:{trust:0,conf:0,health:1},
          after:`The list becomes a schedule. Two weeks later they realize nobody planned the cooling upgrade, because it wasn't anybody's task.`,
          why:`Tasks with owners help, but a list of activities doesn't prove the scope is complete. Decompose the deliverables first, then derive activities from work packages.`},
        {t:`Build a WBS that breaks the deliverables down into work packages, all the work.`, s:3, best:true, d:{trust:1,conf:1,health:5},
          after:`Breaking down "commissioned GPU cluster" into power, cooling, network, hardware, and acceptance testing turns up the cooling upgrade nobody had planned. It's a three-week lead item. Finding it now saves the schedule.`,
          why:`A WBS decomposes deliverables, not tasks, and follows the 100 percent rule: all the work and only the work. That's how you catch missing scope like the cooling upgrade.`},
        {t:`Ask IronPeak for their standard install checklist and use it as the plan.`, s:0, d:{trust:0,conf:0,health:-2},
          after:`IronPeak's checklist covers their work only. Halcyon's network configuration and testing aren't on it.`,
          why:`A vendor's checklist covers the vendor's scope. Your WBS has to cover all of your project's work, including what you do yourselves.`},
        {t:`Have the infrastructure lead own the details and track just the go-live date.`, s:0, d:{trust:1,conf:-1,health:-3},
          after:`The infrastructure lead does a good job on his part. Nobody connects it to the software testing that depends on it.`,
          why:`Delegating detail is fine, but the PM still needs the integrated view of deliverables and dependencies. Tracking one date hides everything that feeds it.`}
      ]},
    { id:`f2s4`, domain:`Process`, task:`R1`, title:`Agile or not`,
      text:(s,all,G)=>[`Lena wants everything in two-week sprints. <span class="said" data-who="Lena">"It's how we work. Planning far out is fiction."</span>`,`Hal from IronPeak wants a dated plan. Cascade's procurement team wants milestone dates in writing. The cluster has a ninety-day hardware lead time that no sprint can shorten.`],
      opts:[
        {t:`Run everything in two-week sprints, hardware included, so there's one rhythm.`, s:0, d:{trust:-1,conf:-2,health:-4},
          after:`The infrastructure team tries to fit a ninety-day lead time into a sprint backlog. IronPeak asks for a schedule and gets a burndown chart.`,
          why:`Adaptive approaches fit uncertain requirements where change is cheap. Hardware with long lead times and fixed windows needs a predictive approach.`},
        {t:`Use a fixed plan for the cluster, sprints for software, and shared milestones.`, s:3, best:true, d:{trust:3,conf:3,health:6},
          after:`The IronPeak dates stay fixed, and the software sprints line up under them, with integration testing set for the week after the cluster is commissioned. Lena and Hal both get what they need.`,
          why:`Tailoring the approach to the nature of the work is a central idea on the current exam. Predictive where scope is fixed, adaptive where it's changing, tied together by milestones and integration points.`},
        {t:`Put the whole project on one detailed waterfall schedule so dates are predictable.`, s:0, d:{trust:-3,conf:1,health:-3},
          after:`The plan is beautiful for two weeks. Then Cascade's clinicians change three requirements after a demo and the plan becomes fiction.`,
          why:`The software requirements really are uncertain, so locking them into a predictive plan just means constant rework of the plan.`},
        {t:`Let each team pick its own method and coordinate through a weekly sync meeting.`, s:1, d:{trust:2,conf:-1,health:-2},
          after:`The teams are happy. Nobody can say whether the software will be ready when the cluster is.`,
          why:`Team autonomy is good, but the project needs one integrated view of milestones and dependencies. Deliberate tailoring isn't the same as no plan.`}
      ]},
    { id:`f2s5`, domain:`Process`, task:`R2`, title:`Who writes the stories`,
      text:(s,all,G)=>[`The software backlog is a mess: four Jira projects, three hundred tickets, half of them written by engineers guessing what nurses want. Nobody at Cascade has looked at it. Ochoa tells Sam his nursing staff are "too busy for software meetings."`],
      opts:[
        {t:`Have the engineers clean up the backlog based on their best read of clinical needs.`, s:0, d:{trust:0,conf:-1,health:-3},
          after:`The backlog gets tidier. It's still built on guesses, and the first demo will prove it.`,
          why:`Requirements need to come from the people who will use the product. A clean backlog of guesses is still guesses.`},
        {t:`Ask Ochoa for two hours with a few nurses and run a story workshop with them.`, s:3, best:true, d:{trust:2,conf:4,health:4},
          after:`Ochoa sends three nurses and an informatics analyst. In two hours they rewrite the top thirty stories and throw out forty. One nurse says, <span class="said" data-who="woman">"Nobody's ever asked us before they built something."</span>`,
          why:`Eliciting requirements from real users, through workshops, interviews, or observation, is how you build the right thing. Make it easy for busy stakeholders by asking for a small, focused time commitment.`},
        {t:`Send Cascade the backlog as a spreadsheet and ask them to mark what they need.`, s:1, d:{trust:0,conf:1,health:1},
          after:`Cascade returns it with ninety percent of rows marked "needed." It tells Sam almost nothing about priority.`,
          why:`Asking for input is right, but a spreadsheet gets you a wish list, not understanding. Facilitated elicitation with real users works better.`},
        {t:`Wait for Cascade to assign a product owner before touching the backlog at all.`, s:0, d:{trust:0,conf:-1,health:-3},
          after:`Cascade takes five weeks to assign one. The team builds on guesses in the meantime.`,
          why:`A product owner is important, but you don't stop discovering requirements while you wait. Engage users now and keep pushing for a product owner.`}
      ]},
    { id:`f2s6`, domain:`Process`, task:`R8`, title:`Theo's estimate`,
      text:(s,all,G)=>[`Sam asks Theo how long fine-tuning the documentation model will take. Theo says, <span class="said" data-who="Theo">"Four weeks."</span> Sam has learned that Theo's estimates come in two flavors: wildly optimistic when he's excited and quietly doubled when he's tired. Right now he's tired.`],
      opts:[
        {t:`Accept four weeks, since Theo knows the model better than anyone at Halcyon.`, s:1, d:{trust:1,conf:0,health:-1},
          after:`Four weeks goes into the plan. Sam has no idea whether it's a stretch or a cushion.`,
          why:`The person doing the work should estimate it, but a single number hides the uncertainty. Ask for a range so you can see it.`},
        {t:`Ask Theo for an optimistic, likely, and pessimistic estimate and use PERT.`, s:3, best:true, d:{trust:2,conf:1,health:3},
          after:`Theo says ten days best case, sixteen likely, twenty-eight if the clinical data is messy. Sam runs the numbers with him. The conversation about what makes it twenty-eight turns into a real risk on the register.`,
          why:`Three-point estimating makes uncertainty visible and turns it into something you can manage. The conversation about the pessimistic case is often worth more than the number.`},
        {t:`Cut the estimate to three weeks, since Theo pads his numbers when he's tired.`, s:0, d:{trust:-5,conf:0,health:-3},
          after:`Theo stops giving Sam honest estimates. Why bother, if they get cut?`,
          why:`Cutting an estimate doesn't shorten the work; it hides the risk and teaches people to inflate. Handle uncertainty with ranges and explicit reserves, not hidden cuts.`},
        {t:`Use the duration of a similar model project last year as the estimate instead.`, s:1, d:{trust:0,conf:0,health:1},
          after:`Last year's project took five weeks. It used a different model and cleaner data, so nobody's sure it applies.`,
          why:`Analogous estimating is fast and useful early, but it's only as good as the comparison. Here, the person doing the work can give you a better range.`}
      ]},
    { id:`f2s7`, domain:`Process`, task:`R8`, title:`Make it fit`,
      text:(s,all,G)=>[`The first full estimate rolls up to fifteen weeks for the phase one scope, one more than the contract allows. Elena reads it and says, <span class="said" data-who="Elena">"Have everyone take ten percent off. Engineers always pad."</span>`],
      opts:[
        {t:`Have every lead take ten percent off their estimates to meet Elena's request.`, s:0, d:{trust:-6,conf:1,health:-4},
          after:`The plan now shows fourteen weeks. Nothing about the work has changed. The team starts calling it "the Friday plan."`,
          why:`Arbitrary cuts don't shorten work, they hide risk and wreck trust in estimates. Change the plan by changing scope, resources, or approach, not the numbers.`},
        {t:`Show Elena the estimate's basis and offer real ways to save a week, with tradeoffs.`, s:3, best:true, d:{trust:4,conf:3,health:4},
          after:`Sam shows the three-point ranges and two options: move two low-value stories to the second wave, or run integration testing partly in parallel. Elena picks the first. The plan fits, honestly.`,
          why:`When the schedule doesn't fit, adjust scope, resources, or sequencing and show the tradeoffs. Estimates should reflect the work. The sponsor chooses among real options.`},
        {t:`Keep fifteen weeks and tell Elena the estimates are final and can't be changed.`, s:0, d:{trust:2,conf:-5,health:0},
          after:`Elena hears "no" and goes to Grant, who suggests a vendor who claims they can do it in ten.`,
          why:`Defending estimates is right, but refusing to look for options isn't. The PM's job is to find honest ways to meet the goal, or show clearly why they don't exist.`},
        {t:`Add a week of buffer quietly to the plan so the team has room either way.`, s:1, flag:`paddedestimates`, d:{trust:1,conf:-1,health:1},
          after:`The buffer helps the team. When Elena finds it later, she wonders what else isn't visible.`,
          why:`Reserves are good, but hidden ones aren't. Contingency should be explicit and owned, so the sponsor knows what it's for.`}
      ]},
    { id:`f2s8`, domain:`Process`, task:`R8`, title:`The long path`,
      text:(s,all,G)=>[`With the network drawn, one chain of work jumps out: racks installed, burn-in tested, integration tested, clinicians test it. Nothing on that chain has room to slip. Everything else does.`,`Grant, reading over his shoulder, asks why Sam is so worried about burn-in testing. <span class="said" data-who="Grant">"It's just running the machines, right?"</span>`],
      opts:[
        {t:`Focus his weekly reviews on critical path work and track float on everything else.`, s:3, best:true, d:{trust:1,conf:2,health:5},
          after:`Burn-in, integration testing, and clinician testing get named owners and a weekly check. When a non-critical task slips two days later, Sam doesn't panic, because it has four days of float.`,
          why:`The critical path determines the project's duration. Watch it closely, and use float to manage everything else calmly. Not every slip is a crisis.`},
        {t:`Treat every task as critical so nothing slips anywhere in the whole project.`, s:0, d:{trust:-3,conf:0,health:-1},
          after:`The team burns out chasing tasks that have days of slack. The truly critical work gets the same attention as everything else, which is to say not enough.`,
          why:`If everything is critical, nothing is. Float exists so you can focus energy where it matters.`},
        {t:`Add extra people to burn-in testing right away to get ahead of the schedule.`, s:1, d:{trust:0,conf:0,health:1},
          after:`Burn-in can't start until the racks arrive, so the extra people sit idle for two weeks.`,
          why:`Crashing the critical path is a valid tool, but only where adding resources actually shortens the work, and only when you need to. Don't compress before you know you have a problem.`},
        {t:`Move clinician testing earlier, before integration testing, to save time.`, s:0, d:{trust:0,conf:-2,health:-4},
          after:`Clinicians test a system that isn't integrated. They find problems that would have been fixed anyway and lose faith in the product.`,
          why:`Fast tracking runs work in parallel, but not when the later work genuinely depends on the earlier work. Some dependencies are hard logic.`}
      ]},
    { id:`f2s9`, domain:`Process`, task:`R8`, title:`Finding a week`,
      text:(s,all,G)=>[`Hal calls: IronPeak's cable supplier is a week late. The cluster install moves back five days, straight on the critical path. Elena wants the week back. The budget has some room. The integration test plan has two parts that were scheduled in sequence but don't strictly depend on each other.`],
      opts:[
        {t:`Fast track the two integration test parts so they run at the same time.`, s:3, best:true, d:{trust:1,conf:2,health:4},
          after:`Running the two test parts in parallel saves four days. It adds risk, so Sam logs it and adds an extra review on the handoff between them. The schedule nearly holds.`,
          why:`Fast tracking overlaps activities that were in sequence. It's the first choice when there's no extra cost available or needed, but it adds risk, so manage that risk explicitly.`},
        {t:`Pay IronPeak's premium rate for weekend install crews to recover the week.`, s:1, d:{trust:0,conf:1,health:3},
          after:`The weekend crews recover three days at a cost Elena winces at. Fast tracking the tests would have saved more for nothing.`,
          why:`Crashing is valid, but it costs money. When cheaper options like fast tracking exist, try them first, and crash only what the critical path still needs.`},
        {t:`Shorten clinician testing from two weeks to one since it's last in the chain.`, s:0, d:{trust:0,conf:-3,health:-4},
          after:`The schedule recovers on paper. Clinicians get half the time to find problems, and two serious ones slip through to go-live.`,
          why:`Cutting testing time isn't schedule compression, it's reducing quality. If you change scope or quality, make it an explicit, approved decision, not a quiet trim.`},
        {t:`Accept the five-day slip and ask Cascade to move the contract date a week.`, s:0, d:{trust:0,conf:-4,health:0},
          after:`Cascade says no and asks what else Halcyon is going to slip.`,
          why:`Asking the customer to move a date should come after you've tried to recover the schedule. There were real options inside the project.`}
      ]},
    { id:`f2s10`, domain:`Process`, task:`R1`, title:`Locking it in`,
      text:(s,all,G)=>[`By Friday of week two Sam has a scope statement, a WBS for the cluster, a prioritized backlog, a schedule with a critical path, and a budget. Lena asks, <span class="said" data-who="Lena">"Can we just start? We've been planning for two weeks."</span>`],
      opts:[
        {t:`Start execution now and treat the plan as a living draft that changes as needed.`, s:0, d:{trust:2,conf:-2,health:-3},
          after:`The plan changes eleven times in the next month. Nobody can say whether the project is ahead or behind, because there's nothing to measure against.`,
          why:`Without baselines you can't measure performance or control change. A living plan still needs an approved reference point.`},
        {t:`Get the scope, schedule, and cost baselines approved, then start execution.`, s:3, best:true, d:{trust:1,conf:4,health:5},
          after:`Elena and the change board approve the baselines in a thirty-minute meeting. From now on, changes to scope, dates, or budget go through change control, and the status report shows variance against the baseline.`,
          why:`The performance measurement baseline is scope, schedule, and cost, approved. It's what you measure against and what change control protects. Get it approved before you execute.`},
        {t:`Ask Cascade to approve every detail of the internal plan before the team begins.`, s:1, d:{trust:0,conf:1,health:-2},
          after:`Cascade's procurement team takes two weeks to review the internal plan and asks about things that aren't theirs to decide.`,
          why:`Customer agreement on milestones and scope matters, but internal baselines are approved through your own governance. Involve the customer on what affects them.`},
        {t:`Keep planning another week to add detail to the later phases before baselining.`, s:0, d:{trust:-1,conf:-1,health:-3},
          after:`A week of planning adds detail nobody can trust yet, and the team loses a week of execution.`,
          why:`Rolling wave planning means you don't need full detail on later phases before you start. Baseline what you have, elaborate later.`}
      ]},
    { id:`f2s11`, domain:`Business Environment`, task:`B3`, title:`A small change`,
      text:(s,all,G)=>[`Monday of week three, an engineer wants to swap a data library for a better one. It's a good idea. It adds three days to a task on the critical path. Lena says, <span class="said" data-who="Lena">"It's an internal technical decision. We don't need to bother the change board with it."</span>`],
      opts:[
        {t:`Let Lena's team make the swap, since it's an internal technical decision.`, s:0, d:{trust:2,conf:-1,health:-3},
          after:`The swap goes in. Three days later the schedule slips and nobody on the change board knows why.`,
          why:`Any change that affects a baseline, here the schedule, needs to go through change control, even if the idea is good and the decision is technical.`},
        {t:`Log a change request, assess the schedule impact, and take it to the board.`, s:3, best:true, d:{trust:1,conf:3,health:4},
          after:`The analysis takes an hour. The board approves the swap and asks the team to fast track a test to absorb two of the three days. The baseline is updated and everyone knows why.`,
          why:`Integrated change control: document the change, analyze its impact on scope, schedule, cost, and risk, then get a decision from the right authority. Update the baselines if it's approved.`},
        {t:`Reject the swap, since the baseline was just approved and shouldn't change.`, s:0, d:{trust:-3,conf:0,health:-1},
          after:`The team keeps the worse library and quietly resents it. Two bugs it causes later cost more than three days.`,
          why:`Baselines can change. They just change through a controlled process. Rejecting good changes by reflex isn't control, it's rigidity.`},
        {t:`Approve the swap himself as long as the team can absorb the three days.`, s:1, d:{trust:1,conf:0,health:1},
          after:`The team absorbs two of the three days. The third shows up as an unexplained slip in the next report.`,
          why:`PMs can approve small changes within their authority, but a change to the critical path schedule is above the threshold the change board set. Use the process you built.`}
      ]},
    { id:`f2s12`, domain:`Process`, task:`R9`, title:`The first Friday status`,
      text:(s,all,G)=>[`The first status report under the new baseline is due. The old PM's reports were lists of everything that happened that week, two pages long. Ochoa told Sam he stopped reading them in June.`],
      opts:[
        {t:`List every task completed this week so stakeholders see how much got done.`, s:0, d:{trust:0,conf:-2,health:0},
          after:`The report is long, impressive, and tells nobody whether the project is on track.`,
          why:`Activity isn't status. Stakeholders need to know performance against the plan, what's at risk, and what decisions are needed.`},
        {t:`Report progress against the baseline, key risks, and any decisions needed.`, s:3, best:true, d:{trust:0,conf:5,health:2},
          after:`One page: milestones green, amber, or red against the baseline, the top three risks, one decision needed from Cascade. Ochoa replies within an hour with the decision.`,
          why:`Evaluating and reporting status means comparing actual performance to the baseline, highlighting variance and risk, and asking for decisions. Short and honest beats long and busy.`},
        {t:`Send a dashboard link so stakeholders can check the data whenever they want.`, s:1, d:{trust:0,conf:1,health:0},
          after:`The dashboard is useful for people who look. Most don't. Nobody notices the amber milestone.`,
          why:`Information radiators are great, but they don't replace telling key stakeholders what matters and what you need. Pull plus push.`},
        {t:`Report only good news this week, since the baseline was just approved Friday.`, s:0, d:{trust:0,conf:-3,health:-1},
          after:`The cable delay doesn't appear. When Cascade hears about it from IronPeak, they wonder what else is missing.`,
          why:`Selective reporting destroys trust. Report variance and risks honestly from the very first report.`}
      ]}
  ],
  drills: [
    { after:`f2s6`, title:`Three-point estimate (PERT)`, setup:[`Theo's estimates for fine-tuning the documentation model are: optimistic 10 days, most likely 16 days, pessimistic 28 days.`,`Use the beta (PERT) formulas.`],
      table:[[`Estimate`,`Days`],[`Optimistic (O)`,`10`],[`Most likely (M)`,`16`],[`Pessimistic (P)`,`28`]],
      fields:[{label:`PERT estimate (days)`, answer:17, tol:0.05},{label:`Standard deviation (days)`, answer:3, tol:0.05},{label:`Upper end of a one standard deviation range (days)`, answer:20, tol:0.05}],
      solution:[`PERT estimate = (O + 4M + P) / 6 = (10 + 64 + 28) / 6 = 102 / 6 = 17 days.`,`Standard deviation = (P minus O) / 6 = (28 minus 10) / 6 = 3 days.`,`One standard deviation range = 17 plus or minus 3, so 14 to 20 days, which covers about 68 percent of likely outcomes. For about 95 percent, use two standard deviations: 11 to 23 days.`] },
    { after:`f2s8`, title:`Critical path and float`, setup:[`Here's a simplified piece of the Cascade network. Durations are in working days.`,`Find the project duration and the total float of activities B and D.`],
      table:[[`Activity`,`Duration`,`Depends on`],[`A Rack delivery and install`,`5`,`none`],[`B Network links`,`4`,`A`],[`C Burn-in testing`,`6`,`A`],[`D Deployment pipeline`,`7`,`none`],[`E Integration testing`,`5`,`B, C, D`],[`F Clinician testing`,`4`,`E`]],
      fields:[{label:`Project duration (days)`, answer:20, tol:0},{label:`Total float of B (days)`, answer:2, tol:0},{label:`Total float of D (days)`, answer:4, tol:0}],
      solution:[`List the paths: A, B, E, F = 5 + 4 + 5 + 4 = 18 days. A, C, E, F = 5 + 6 + 5 + 4 = 20 days. D, E, F = 7 + 5 + 4 = 16 days.`,`The longest path, A, C, E, F at 20 days, is the critical path. It sets the project duration.`,`B sits on an 18-day path, so its total float is 20 minus 18 = 2 days. D sits on a 16-day path, so its total float is 20 minus 16 = 4 days. That's why the burn-in testing (C) on the critical path gets Sam's attention and the pipeline (D) doesn't.`] }
  ],
  exercise: { after:`f2s7`, title:`Name the estimating technique`, intro:`Each sentence describes how an estimate was made. Pick the technique.`,
    items:[
      {prompt:`"Last year's similar rollout took nine weeks, so let's start with nine."`, choices:[`Analogous`,`Parametric`,`Bottom-up`,`Three-point`,`Planning poker`], answer:0, why:`Using a similar past project as the basis is analogous estimating.`},
      {prompt:`"Each rack takes six hours to install, and we have twenty racks, so 120 hours."`, choices:[`Analogous`,`Parametric`,`Bottom-up`,`Three-point`,`Planning poker`], answer:1, why:`A unit rate times a quantity is parametric estimating.`},
      {prompt:`"We estimated every work package in the WBS and added them up."`, choices:[`Analogous`,`Parametric`,`Bottom-up`,`Three-point`,`Planning poker`], answer:2, why:`Rolling up detailed estimates from the lowest level is bottom-up estimating.`},
      {prompt:`"Best case ten days, likely sixteen, worst case twenty-eight."`, choices:[`Analogous`,`Parametric`,`Bottom-up`,`Three-point`,`Planning poker`], answer:3, why:`Optimistic, most likely, and pessimistic values make a three-point estimate.`},
      {prompt:`"Everyone flipped a card at once, then the high and low voters explained their reasoning."`, choices:[`Analogous`,`Parametric`,`Bottom-up`,`Three-point`,`Planning poker`], answer:4, why:`Simultaneous relative estimates followed by discussion is planning poker, common on agile teams.`}
    ]},
  quiz: [
    {q:`Using three-point estimating with the beta distribution, what is the expected duration if O is 6 days, M is 9 days, and P is 18 days?`, opts:[`9 days`,`10 days`,`11 days`,`12 days`], a:1, why:`(6 + 36 + 18) / 6 = 60 / 6 = 10 days.`, task:`R8`, domain:`Process`},
    {q:`What is the standard deviation for an activity with an optimistic estimate of 4 days and a pessimistic estimate of 22 days?`, opts:[`2 days`,`4 days`,`6 days`,`3 days`], a:3, why:`(P minus O) / 6 = (22 minus 4) / 6 = 3 days.`, task:`R8`, domain:`Process`},
    {q:`A schedule has three paths of 14, 17, and 12 days. What is the total float of an activity that sits only on the 14-day path?`, opts:[`0 days`,`2 days`,`3 days`,`5 days`], a:2, why:`The critical path is 17 days. 17 minus 14 = 3 days of float.`, task:`R8`, domain:`Process`},
    {q:`A project is behind schedule. There's no extra budget, but two sequential activities could overlap. What should the project manager consider first?`, opts:[`Fast tracking the two activities`,`Crashing the critical path activities`,`Reducing the project's quality targets`,`Requesting a new end date from the sponsor`], a:0, why:`Fast tracking overlaps sequential work without adding cost, though it adds risk.`, task:`R8`, domain:`Process`},
    {q:`Which statement best describes the 100 percent rule?`, opts:[`Every work package must be assigned to exactly one owner`,`The WBS must include all the project work and only that work`,`All stakeholders must approve the WBS before execution`,`Each activity must be fully complete before the next starts`], a:1, why:`The WBS captures 100 percent of the scope: all the work and only the work.`, task:`R2`, domain:`Process`},
    {q:`On an agile team, who is responsible for ordering the product backlog?`, opts:[`The project manager, based on the schedule`,`The development team, based on effort`,`The product owner, based on value`,`The sponsor, based on the business case`], a:2, why:`The product owner owns and prioritizes the backlog to maximize value.`, task:`R3`, domain:`Process`},
    {q:`The sponsor asks the project manager to cut all estimates by 15 percent to meet a deadline. What should the project manager do?`, opts:[`Apply the cut evenly across all work packages to meet the date`,`Refuse the request because team estimates should never change`,`Add hidden buffer elsewhere to protect the team from the cut`,`Explain the estimate basis and present options with tradeoffs`], a:3, why:`Arbitrary cuts hide risk. Show the basis of estimates and offer real options like scope or resource changes.`, task:`R8`, domain:`Process`},
    {q:`A team member proposes a good technical change that would delay a critical path activity by two days. What should the project manager do?`, opts:[`Document the change, assess its impact, and follow change control`,`Approve it, since the change is technically sound and small`,`Reject it, since the schedule baseline was already approved`,`Let the technical lead decide, since it's an engineering issue`], a:0, why:`Changes affecting a baseline go through integrated change control: document, analyze impact, decide at the right level.`, task:`B3`, domain:`Business Environment`},
    {q:`Which documents together make up the scope baseline?`, opts:[`Scope statement, WBS, and WBS dictionary`,`Charter, scope statement, and product backlog`,`Requirements, WBS, and schedule`,`Scope statement, schedule, and budget`], a:0, why:`The scope baseline is the approved scope statement, WBS, and WBS dictionary.`, task:`R2`, domain:`Process`},
    {q:`A hybrid project has hardware with long lead times and software whose requirements are still emerging. Which approach is best?`, opts:[`Use agile sprints for all work to keep one cadence`,`Use a predictive plan for all of the work to fix the dates`,`Tailor: predictive for hardware, adaptive for software`,`Let each team decide its own approach independently`], a:2, why:`Tailor the approach to the work: predictive where scope is fixed, adaptive where it's uncertain, integrated by milestones.`, task:`R1`, domain:`Process`},
    {q:`A project manager is preparing the first status report against a new baseline. What should the report focus on?`, opts:[`A complete list of all activities completed this period`,`A link to the dashboard so readers can explore the details`,`Highlights of recent wins to build stakeholder confidence`,`Performance against baseline, key risks, and decisions needed`], a:3, why:`Status means variance from the baseline, risks, and decisions needed, presented clearly.`, task:`R9`, domain:`Process`},
    {q:`Which technique estimates by multiplying a unit rate by a quantity, such as hours per unit times units?`, opts:[`Analogous estimating`,`Parametric estimating`,`Bottom-up estimating`,`Three-point estimating`], a:1, why:`Parametric estimating uses a statistical relationship like a unit rate times a quantity.`, task:`R8`, domain:`Process`},
    {q:`On a hybrid project, the approved scope, schedule, and cost baselines together are called the:`, opts:[`Project charter`,`Requirements traceability matrix`,`Performance measurement baseline`,`Project management plan`], a:2, why:`The performance measurement baseline is the approved scope, schedule, and cost baselines combined. Status is measured against it, and change control protects it. The project management plan contains it, but is much broader.`, task:`R1`, domain:`Process`},
    {q:`During planning, the team realizes a needed cooling upgrade was never in anyone's task list. Which tool would most likely have caught it?`, opts:[`A detailed task list with owners`,`A WBS decomposing all deliverables`,`A vendor's standard installation checklist`,`A weekly status meeting agenda`], a:1, why:`Decomposing deliverables in a WBS, following the 100 percent rule, surfaces missing scope.`, task:`R2`, domain:`Process`},
    {q:`Two subsidiary plans conflict: the vendor's power plan and engineering's capacity plan assume different equipment. What should the project manager do?`, opts:[`Use the vendor's plan, since the vendor has the install window`,`Use engineering's plan, since engineering owns the capacity`,`Escalate the conflict to the sponsor for a quick decision`,`Bring both owners together and integrate them into one plan`], a:3, why:`Integration is the PM's job: resolve dependent decisions with the owners and reflect them in one integrated plan. Escalate only if they can't resolve it.`, task:`R1`, domain:`Process`}
  ],
  closing:(s,all,G)=>[
    `Friday night of week two, Sam gets home at seven, which Dana marks with a small round of applause from the couch.`,
    `He tells her about the critical path over dinner, which is not something either of them planned. She asks good questions. She teaches stoichiometry to sixteen-year-olds; she knows what it's like to explain why one thing has to happen before another.`,
    `<span class="said" data-who="Dana">"So the whole thing hangs on the machines passing their test,"</span> she says.`,
    `<span class="said" data-who="Sam">"Burn-in. Six days of running them hot to see what breaks."</span>`,
    `<span class="said" data-who="Dana">"And if something breaks?"</span>`,
    `<span class="said" data-who="Sam">"Then that's what the float's for."</span> He says it more confidently than he feels.`,
    (s.score>=27?`Ruth texts at nine: <span class="said" data-who="Ruth">"Saw the baseline. That's a plan I'd sign. Now go meet your team. Really meet them."</span>`:`Ruth texts at nine: <span class="said" data-who="Ruth">"Saw the baseline. It'll do. Next week, stop managing the plan and go meet your team."</span>`),
    `Saturday morning Hal calls again. <span class="said" data-who="Hal">"Good news for once. Your first racks are on the truck. Burn-in starts the Monday after next. Hope you've got people ready."</span> Sam looks at his team list, half in Denver, and half in a city eight hours ahead he hasn't visited yet.`
  ],
  episode:{src:`audio/full-ch02.mp3`, len:`about 35 minutes`},
  next:`The Team`
});
