(window.HALCYON_FULL=window.HALCYON_FULL||[]).push({
  num: 3, part: `Part One: The Cascade Launch`, title: `The Team`, weeks: `Weeks 2 to 3`,
  tasks: [`R4`,`P3`,`P8`,`P1`],
  cast: [
    [`Priya Shah`,`Data engineer. Shadows Theo on deploys. Quiet, sharp, underestimates herself.`],
    [`Tomasz Nowak`,`Leads the Kraków contractor team, eight hours ahead of Denver. Direct and proud.`],
    [`Devin Ruiz`,`Engineer. Talented, coasting since his last manager left.`],
    [`Owen Pike`,`Halcyon project lead on a smaller payments integration. Always short a data engineer.`]
  ],
  opening: [
    `The Kraków team came with the budget. The departed PM had signed a contract with a software firm in Poland for six engineers, starting in week two, to build the integration layer between Halcyon's agents and Cascade's records system. Sam found the contract in folder twelve, under a file called "misc."`,
    `Tomasz Nowak, their lead, joined his first Halcyon call at 4 PM Denver time, which was midnight in Kraków. He had his camera on, a mug of tea, and the patient expression of a man who had been told the meeting was at 3 PM. Nobody had told him about daylight saving time.`,
    `<span class="said">"We are ready to start,"</span> Tomasz said. <span class="said">"Someone should tell us what we are building. So far we have a repository and a Slack invite."</span>`,
    `That night Sam couldn't stop thinking about it. In the Air Force, when a new crew chief arrived from another base, nobody handed them a wrench and walked away. You walked the jet with them. You showed them where the forms lived, which tools stuck, who to ask at two in the morning. Ray Mendez called it "plugging them in." He'd say a new airman without a sponsor was just an expensive spectator.`,
    `Dana found him at the kitchen table at eleven. <span class="said">"Plan problems or people problems?"</span>`,
    `<span class="said">"People,"</span> he said. <span class="said">"I have forty people in Denver, six in Poland, and I've never managed a single one of them."</span>`,
    `<span class="said">"You managed a flight line."</span>`,
    `<span class="said">"Everybody on a flight line already knew what the jet needed."</span>`,
    `She thought about it. <span class="said">"So tell them what the jet needs."</span>`
  ],
  lesson: {
    title: `Resources, teams, and communication`,
    sections: [
      { h: `Planning resources`,
        body: [`Resource planning covers people, equipment, materials, and facilities. For people, the resource management plan says what roles you need, when, for how long, how you'll acquire them, how they'll be developed, and how they'll be released at the end. Resource calendars show when people are actually available, which catches vacations, holidays in other countries, and the engineer who is also on call for three other customers.`,
          `A responsibility assignment matrix, often in RACI form, shows who is Responsible, Accountable, Consulted, and Informed for each deliverable or decision. The rule that matters most: only one person is Accountable for any item. Two accountable people means nobody is.`,
          `Organizational structure shapes your authority. In a functional organization, functional managers control resources and the PM has little authority. In a projectized organization, the PM controls the team. Most companies, Halcyon included, are matrix organizations, somewhere in between, where team members report to a functional manager and work for the PM. In a matrix, the PM negotiates for people and the functional manager is a key stakeholder.`, `Acquiring resources is only half of it. The plan should also say how people will be developed, through training, mentoring, pairing, or coaching, and how they'll be released when their part is done, so they don't drift off the project without a handoff. Physical resources follow the same logic: the GPU racks, the colocation space, and the network gear all have lead times and availability windows that belong in the plan alongside the people.`],
        terms: [[`RACI`,`A matrix showing who is Responsible, Accountable, Consulted, and Informed.`],[`Resource calendar`,`When each resource is available to the project.`],[`Matrix organization`,`A structure where people report to a functional manager and work on projects for a PM.`]],
        exam: `If two people both think they own a decision, the fix is a RACI with one Accountable. If a PM in a matrix can't get a person released, the answer usually involves negotiating with the functional manager.` },
      { h: `Building a team`,
        body: [`Tuckman's ladder describes how teams develop: forming, where people are polite and unsure; storming, where conflict and friction show up; norming, where the team agrees on how to work; performing, where it runs smoothly; and adjourning, when the work ends. Teams can slide back a stage when people join or leave. Storming isn't a failure. It's a stage, and the PM's job is to get the team through it.`,
          `A team charter, built by the team, records values, working agreements, decision-making rules, communication norms, and how conflict will be handled. It works because the team writes it. On virtual and distributed teams, working agreements are even more important: core overlap hours, response time expectations, which channel is for what, and how meetings rotate so the same people don't always take the midnight call.`],
        terms: [[`Team charter`,`The team's own agreement on values, norms, decisions, and conflict handling.`],[`Virtual team`,`A team that works across locations, often across time zones, mainly through technology.`]],
        exam: `When a question describes new team members joining and friction rising, think "the team went back to storming." The fix is facilitation and working agreements, not discipline.` },
      { h: `Motivation and leadership`,
        body: [`A few theories show up on the exam. Herzberg separates hygiene factors, like pay and working conditions, from motivators, like achievement, recognition, and growth. Fixing hygiene stops dissatisfaction but doesn't create motivation. McGregor's Theory X assumes people avoid work and need control; Theory Y assumes people want to do good work. Maslow's hierarchy runs from basic needs up to self-actualization. Expectancy theory says people are motivated when they believe effort leads to results and results lead to rewards they value.`,
          `Leadership styles show up too. Autocratic leaders decide alone. Transactional leaders manage by rewards and corrections against agreed targets. Laissez-faire leaders step back and let the team run. Each has its moment, but servant leadership is the posture behind most correct answers: the leader removes obstacles, protects the team, builds capability, and puts the team's needs ahead of their own status. Emotional intelligence, knowing your own emotions, managing them, reading others, and handling relationships, is what makes servant leadership possible under pressure.`],
        terms: [[`Hygiene factors`,`Conditions that prevent dissatisfaction but don't motivate on their own.`],[`Servant leadership`,`Leading by serving the team: removing impediments and enabling their success.`]],
        exam: `Recognition and growth are motivators. A raise fixes a hygiene problem. If a question offers "public recognition tied to team goals" against "bonus for the top individual," the team-focused option usually wins.` },
      { h: `Planning communication`,
        body: [`The communications management plan says who needs what information, in what format, how often, from whom, and through which channel. Methods fall into three groups. Interactive communication, like meetings and calls, is best for complex or sensitive topics. Push communication, like emails and reports, sends information to people. Pull communication, like dashboards and wikis, lets people get it when they need it.`,
          `The number of communication channels grows fast as people are added: n(n minus 1) divided by 2, where n is the number of people. Ten people have 45 channels. Sixteen have 120. That's why adding a team in another country multiplies the communication work far beyond its headcount, and why the plan has to change when the team does.`, `Communication isn't finished when a message is sent. The basic model has a sender who encodes a message, a medium that carries it, noise that distorts it, and a receiver who decodes it and confirms understanding. On a team spread across two countries and two native languages, noise is real: idioms, sarcasm, and terse written feedback all decode badly. The plan should be reviewed whenever the team, the stakeholders, or the risks change.`],
        terms: [[`Push communication`,`Sending information to recipients, such as email or reports.`],[`Pull communication`,`Making information available for people to access, such as a wiki or dashboard.`]],
        exam: `Learn n(n minus 1) / 2. Questions often ask how many channels are added, which is the new total minus the old total.` }
    ],
    video: [`-RwkZxGPQb8`,`Tuckman's 5 Stages of Team Development`,`The Right Questions`,`5:59`]
  },
  scenes: [
    { id:`f3s1`, domain:`Process`, task:`R4`, title:`Who's actually available`,
      text:(s,all,G)=>[`Sam's schedule assumes everyone is available full time. Then Priya mentions she's out the week of Thanksgiving. Tomasz mentions three Polish public holidays in November. Theo is still on the support rotation for three other customers.`,`The burn-in window is fixed. The people aren't.`],
      opts:[
        {t:`Build resource calendars for key people and check them against the schedule.`, s:3, best:true, d:{trust:2,conf:1,health:5},
          after:`The calendars expose two clashes: Kraków's November 11 holiday lands on an integration deadline, and Theo's support week overlaps burn-in. Both get fixed now, with three weeks of warning, instead of the night before.`,
          why:`Resource calendars show when people are really available. Checking them against the schedule turns hidden conflicts into planned adjustments. That's part of planning and managing resources.`},
        {t:`Ask everyone to avoid taking time off until go-live, given how tight things are.`, s:0, d:{trust:-6,conf:0,health:-1},
          after:`Nobody says no. Two people start quietly updating their resumes.`,
          why:`Canceling people's lives to fit a plan damages morale and doesn't change public holidays. Plan around real availability.`},
        {t:`Add a ten percent buffer to every task to cover absences across the whole team.`, s:1, d:{trust:1,conf:0,health:1},
          after:`The buffer helps a little, but it's spread evenly, while the real conflicts are concentrated on two specific dates.`,
          why:`A general buffer is better than nothing, but it doesn't find the specific clashes. Resource calendars do.`},
        {t:`Let each lead manage their own team's time off and flag problems as they appear.`, s:0, d:{trust:1,conf:0,health:-3},
          after:`The Kraków holiday surfaces two days before the deadline it collides with.`,
          why:`Leads should manage their people, but the PM needs the integrated view. A conflict is only visible when availability meets the schedule.`}
      ]},
    { id:`f3s2`, domain:`Process`, task:`R4`, title:`Who approves the deploy`,
      text:(s,all,G)=>[`A model update goes to the demo environment Tuesday. Lena thought Theo approved it. Theo thought Lena approved it. Nobody did. It breaks the demo for half a day.`,`In the postmortem, four people describe themselves as "kind of responsible" for deploy approvals.`],
      opts:[
        {t:`Have Lena personally approve every deploy from now on to stop the confusion.`, s:1, d:{trust:-1,conf:0,health:1},
          after:`Deploys now wait for Lena, who is in meetings most of the day. Releases slow to a crawl.`,
          why:`Clear ownership is right, but piling every approval on the CTO creates a bottleneck. Decide the roles deliberately, with one accountable person at the right level.`},
        {t:`Build a RACI for deploys and approvals with one Accountable person per item.`, s:3, best:true, d:{trust:3,conf:1,health:4},
          after:`The RACI fits on one page. Priya is Responsible for running deploys, Theo is Accountable for approving model changes, Lena is Consulted on anything touching patient data, and Sam is Informed. The next deploy goes out on time.`,
          why:`A responsibility assignment matrix removes ambiguity. The key rule is one Accountable per item. When several people are "kind of responsible," nobody is.`},
        {t:`Add a second approver to every deploy so there's always a backup check in place.`, s:0, d:{trust:0,conf:0,health:-2},
          after:`Now two people each assume the other one checked.`,
          why:`Adding approvers without defining who is accountable makes the original problem worse.`},
        {t:`Remind everyone in Slack that deploys need approval before they go out.`, s:0, d:{trust:0,conf:0,health:-1},
          after:`Everyone agrees. Nobody knows whose approval.`,
          why:`A reminder doesn't fix unclear roles. Define who is responsible and who is accountable.`}
      ]},
    { id:`f3s3`, domain:`People`, task:`P3`, title:`Plugging in Kraków`,
      text:(s,all,G)=>[`Tomasz's team has had repository access for a week and very little else. In a direct message he writes: <span class="said">"My engineers are asking if we are a team or a supplier. I would like to give them an answer."</span>`],
      opts:[
        {t:`Send Tomasz a detailed spec so his team can work independently without delays.`, s:1, d:{trust:0,conf:0,health:2},
          after:`The spec helps them start. It doesn't answer Tomasz's question, and his team still feels like a vendor taking orders.`,
          why:`Clear requirements help, but onboarding a team means integrating them: shared goals, real relationships, and a place in how decisions are made.`},
        {t:`Run a joint kickoff with both sites and pair each Kraków engineer with a buddy.`, s:3, best:true, d:{trust:6,conf:0,health:3},
          after:`The kickoff happens at 8 AM Denver, 4 PM Kraków, so nobody's up at midnight. Priya walks them through the clinical problem. Each Kraków engineer gets a Denver buddy. By Friday, Tomasz's team is asking questions in the main channel instead of in DMs.`,
          why:`Onboarding is how you build one team instead of two. A shared kickoff, a clear purpose, and peer buddies help a virtual team form trust faster. This is plugging them in.`},
        {t:`Tell Tomasz they're a supplier under contract and will be managed through it.`, s:0, d:{trust:-6,conf:0,health:-2},
          after:`Tomasz's team does exactly what the contract says and nothing more. When the spec is wrong, they build the wrong thing correctly.`,
          why:`Even when the relationship is contractual, the work is collaborative. Treating people as a vendor gets you vendor behavior.`},
        {t:`Have Lena handle Kraków, since the integration work is part of her engineering org.`, s:0, d:{trust:0,conf:0,health:-1},
          after:`Lena adds them to her weekly meeting. They listen to updates about work they're not part of.`,
          why:`Delegation isn't integration. The PM leads the project team, and that includes the people on the other side of the world.`}
      ]},
    { id:`f3s4`, domain:`People`, task:`P8`, title:`The midnight standup`,
      text:(s,all,G)=>[`The daily standup is at 9 AM Denver, 5 PM Kraków. Fine. But the integration sync is at 4 PM Denver, midnight in Kraków, and Tomasz's engineers have joined it from their kitchens for six days straight.`,`Nobody in Denver has noticed.`],
      opts:[
        {t:`Move the sync to 8 AM Denver and agree on core overlap hours with both sites.`, s:3, best:true, d:{trust:5,conf:0,health:2},
          after:`The two sites agree on a four-hour overlap window and that anything outside it goes async in a shared channel. The sync moves to the morning. Tomasz sends Sam a photo of his engineer's kitchen, empty, with a thumbs up.`,
          why:`Virtual teams need working agreements about overlap hours and async communication. The aim is a fair, sustainable rhythm for every location.`},
        {t:`Thank the Kraków team for their commitment and keep the meeting time as it is.`, s:0, d:{trust:-5,conf:0,health:-1},
          after:`The Kraków team keeps joining at midnight. Their code review quality drops.`,
          why:`Thanking people for a burden you could remove isn't leadership. Fix the schedule.`},
        {t:`Cancel the sync and switch the integration updates to written reports only.`, s:1, d:{trust:1,conf:0,health:-1},
          after:`The written updates are fine for status but slow for the tricky integration questions, which now take days to resolve.`,
          why:`Async helps, but complex coordination still needs some live time. Find the overlap, don't eliminate interaction altogether.`},
        {t:`Rotate the meeting so Denver takes the late slot half the time to share the pain.`, s:1, d:{trust:2,conf:0,health:0},
          after:`It's fairer, but now Denver engineers are tired every other week, and there's a perfectly good morning slot nobody used.`,
          why:`Rotating is a good tool when no overlap exists. Here, a shared window works, so use it.`}
      ]},
    { id:`f3s5`, domain:`People`, task:`P8`, title:`Who needs to know what`,
      text:(s,all,G)=>[`Communication on Cascade is everywhere and nowhere: four Slack channels, two email lists, a Confluence page nobody updates, and Grant forwarding things to Cascade with "FYI" and no context. Ochoa got news of the cable delay from IronPeak before he got it from Halcyon.`],
      opts:[
        {t:`Write a comms plan: who needs what, how often, through which channel, from whom.`, s:3, best:true, d:{trust:2,conf:4,health:3},
          after:`It's a one-page table. Ochoa gets the Friday one-pager and a call within a day for anything red. The team gets standups and a dashboard. Executives get a biweekly review. Grant agrees that customer-facing updates come from Sam.`,
          why:`A communications management plan sets who needs what information, in what format, how often, through which channel, and who sends it. It's how you stop surprises.`},
        {t:`Move everything into one Slack channel so all information lives in one place.`, s:0, d:{trust:0,conf:-1,health:-1},
          after:`The channel gets two hundred messages a day. Important updates scroll away in minutes.`,
          why:`One channel for everyone isn't a plan. Different stakeholders need different information at different levels of detail.`},
        {t:`Ask Grant to stop forwarding things to Cascade without checking with Sam first.`, s:1, d:{trust:0,conf:1,health:0},
          after:`Grant agrees, mostly. Every other communication gap remains.`,
          why:`Fixing one leak helps, but the problem is the lack of a plan. Address the system, not just one person.`},
        {t:`Send a longer weekly email to all stakeholders so nobody misses anything.`, s:0, d:{trust:0,conf:-2,health:0},
          after:`The email is long. Ochoa stops reading it by week two, like he did the last PM's.`,
          why:`More information isn't better communication. Tailor content and channel to each audience.`}
      ]},
    { id:`f3s6`, domain:`People`, task:`P3`, title:`How we work`,
      text:(s,all,G)=>[(G.allhands?`The team still remembers Sam's first-day all-hands. They're polite, but they wait to be told things. `:``)+`Working agreements on Cascade are mostly unwritten: some people expect replies within an hour, others check Slack twice a day. Code reviews range from a thumbs up to a forty-comment essay. Two arguments this week were really about expectations nobody ever stated.`],
      opts:[
        {t:`Write a set of team rules based on best practices and share it in the channel.`, s:1, d:{trust:-1,conf:0,health:1},
          after:`The rules are good. People follow the ones they already agreed with and ignore the rest.`,
          why:`Norms stick when the team creates them. A PM-written rulebook gets compliance at best.`},
        {t:`Facilitate a team charter session where both sites write their working agreements.`, s:3, best:true, d:{trust:6,conf:0,health:3},
          after:`Ninety minutes, both sites, a shared doc. They agree on response times, a review checklist, how decisions get made, and "disagree in the room, not in the kitchen." Tomasz adds one: "Assume the other site is not stupid." It stays in.`,
          why:`A team charter built by the team records values, working agreements, decision rules, and conflict handling. People keep agreements they helped write.`},
        {t:`Ask Lena to set standards for code reviews and response times as CTO.`, s:0, d:{trust:0,conf:0,health:0},
          after:`Lena writes a thoughtful doc that avoids every contentious point.`,
          why:`Leadership-issued standards have a place, but working agreements for a team belong to that team.`},
        {t:`Let norms form naturally, since forcing agreements this early can feel artificial.`, s:0, d:{trust:0,conf:0,health:-2},
          after:`Norms do form. Different ones in each city.`,
          why:`With two sites and real friction, waiting for norms to emerge means waiting for conflict. Make them explicit early.`}
      ]},
    { id:`f3s7`, domain:`People`, task:`P3`, title:`Tone in the code reviews`,
      text:(s,all,G)=>[`A Kraków engineer's pull request gets a review from a senior Denver engineer that reads, in full: <span class="said">"No. Rewrite."</span> Another gets a comment calling an approach "junior." Tomasz forwards both to Sam with no message. He doesn't need one.`],
      opts:[
        {t:`Talk privately with the reviewer about tone and the team's new review agreement.`, s:3, best:true, d:{trust:5,conf:0,health:2},
          after:`The reviewer is surprised. He thought he was being efficient. Sam walks him through how it read from the other side. The next review has reasons in it. Two weeks later the same engineer pairs with the Kraków dev on a hard problem.`,
          why:`Address behavior privately, directly, and early, tied to the agreements the team made. Coaching first; most people don't know how they're landing.`},
        {t:`Post a reminder in the main channel that all code reviews must be respectful.`, s:1, d:{trust:1,conf:0,health:0},
          after:`Everybody agrees in principle. The reviewer doesn't realize it was about him.`,
          why:`Broadcasting a general reminder avoids the conversation that needs to happen. Address it with the person.`},
        {t:`Tell Tomasz the reviewer is senior and his team should learn from direct feedback.`, s:0, d:{trust:-6,conf:0,health:-2},
          after:`Tomasz says "understood." His team stops opening pull requests until the end of each day, to avoid the reviews.`,
          why:`Defending disrespect because it comes from a senior person damages the whole team. Feedback can be direct and still respectful.`},
        {t:`Remove the senior engineer from reviewing Kraków work to avoid further friction.`, s:0, d:{trust:0,conf:0,health:-2},
          after:`The friction disappears, along with the most experienced reviewer on the integration code.`,
          why:`Separating people avoids the problem instead of fixing it. Coach the behavior so the team keeps the expertise.`}
      ]},
    { id:`f3s8`, domain:`People`, task:`P1`, title:`The why, in Polish`,
      text:(s,all,G)=>[`The vision statement Priya pinned in week one, giving nurses time back for patients, means a lot in Denver, where people have met the Cascade nurses. In Kraków it's a sentence in English in a channel. Tomasz says his team thinks of it as "the hospital integration project."`],
      opts:[
        {t:`Have Priya run a session for Kraków with the nurse workshop videos.`, s:3, best:true, d:{trust:4,conf:1,health:2},
          after:`Priya is nervous and does it anyway. She shows a two-minute clip from the story workshop: a nurse describing charting until midnight after a twelve-hour shift. Afterward, a Kraków engineer asks if they can add a field the nurse mentioned. The vision just became theirs.`,
          why:`A common vision has to be shared, not just written. Real stories and real users make it concrete for everyone, wherever they sit.`},
        {t:`Translate the vision statement into Polish and pin it in the Kraków channel.`, s:1, d:{trust:1,conf:0,health:0},
          after:`The gesture is appreciated. A translated sentence is still a sentence.`,
          why:`Respectful, but a vision lands through understanding the purpose and the people, not through a translated slogan.`},
        {t:`Remind Tomasz that the why matters less for contractors than clear specs do.`, s:0, d:{trust:-4,conf:0,health:-1},
          after:`Tomasz quietly agrees and his team goes back to building to spec.`,
          why:`Everyone on the team builds better when they understand the purpose. Contractors are part of the team.`},
        {t:`Have Elena record a short message for the Kraków team about Halcyon's mission.`, s:0, d:{trust:0,conf:0,health:0},
          after:`The video is polished and about the company. It doesn't mention nurses.`,
          why:`A company mission isn't a project vision. Share the project's why, with the people it serves.`}
      ]},
    { id:`f3s9`, domain:`Process`, task:`R4`, title:`Owen wants Priya`,
      text:(s,all,G)=>[`Owen Pike runs a smaller payments integration at Halcyon. He's short a data engineer and has asked Lena, who is Priya's functional manager, to move Priya to his project for three weeks starting Monday. Priya is the only person besides Theo who can run a model deploy.`],
      opts:[
        {t:`Go to Elena and have her overrule Lena so that Priya stays on Cascade.`, s:0, d:{trust:-3,conf:-1,health:1},
          after:`Elena overrules Lena. Priya stays. Lena feels undermined and Owen tells everyone Sam plays politics.`,
          why:`Escalating before negotiating damages relationships you'll need. Try to resolve it with the functional manager first.`},
        {t:`Meet Lena and Owen, show the dependency on Priya, and find a split.`, s:3, best:true, d:{trust:3,conf:2,health:3},
          after:`Laid side by side, the two needs fit: Owen needs data pipeline work, not deploy skills, and Devin Ruiz has pipeline experience and spare capacity. Devin goes to Owen for three weeks. Priya stays. Lena makes the call, which is how it should be.`,
          why:`In a matrix organization the functional manager controls resource assignments, and the PM negotiates. Make the dependency visible, look for options, and let the right person decide.`},
        {t:`Let Priya go, since resource decisions belong to her functional manager.`, s:1, d:{trust:0,conf:0,health:-4},
          after:`Priya goes to Owen. The next Cascade deploy waits for Theo, who is already overloaded.`,
          why:`It's true that the functional manager decides in a matrix, but the PM should make the impact clear and negotiate before accepting a loss to the critical path.`},
        {t:`Tell Priya to politely turn Owen down, since she's needed on Cascade.`, s:0, d:{trust:-2,conf:0,health:0},
          after:`Priya is caught between her project lead and her manager. She's miserable for a week.`,
          why:`Putting a team member in the middle of a resource dispute isn't fair to them. The leads should negotiate.`}
      ]},
    { id:`f3s10`, domain:`People`, task:`P3`, title:`The broken build`,
      text:(s,all,G)=>[`Wednesday the shared integration build breaks for eleven hours. Denver blames a Kraków commit. Kraków points out the Denver tests were failing before their commit. The Slack thread hits ninety messages, and two of them use the word "always."`,`Sam recognizes the stage. It's storming.`],
      opts:[
        {t:`Find the commit that caused it and make sure the right person is held accountable.`, s:0, d:{trust:-5,conf:0,health:0},
          after:`It turns out to be both, a little. Now both sites feel blamed.`,
          why:`Hunting for a culprit during storming deepens the divide. Focus on the process that let it happen.`},
        {t:`Pull leads from both sites into a blameless review to fix the process.`, s:3, best:true, d:{trust:6,conf:0,health:4},
          after:`Twenty minutes, cameras on. The finding: there's no shared rule that tests must pass before merging. They add one. The Slack thread ends with a Kraków engineer posting a gif of two people shaking hands.`,
          why:`Storming is a normal stage. A blameless, process-focused review moves the team toward norming. Address conflict directly and early, with facts.`},
        {t:`Post a message asking everyone to stay professional and move on from it.`, s:1, d:{trust:0,conf:0,health:0},
          after:`The thread goes quiet. The resentment doesn't.`,
          why:`Calming things down is fine, but unresolved conflict comes back. Address the cause.`},
        {t:`Separate the codebases so each site owns its own part and can't break the other.`, s:0, d:{trust:-2,conf:0,health:-4},
          after:`The sites stop breaking each other's builds. They also stop integrating, and the problems pile up for later.`,
          why:`Splitting a team to avoid conflict trades a short-term fix for a bigger integration problem. Build working agreements instead.`}
      ]},
    { id:`f3s11`, domain:`People`, task:`P8`, title:`Ochoa wants more`,
      text:(s,all,G)=>[`After the cable delay, Ochoa asks for a daily status update. Sam understands why. A daily report would also take about an hour a day of his time, for a project where most days nothing changes that Ochoa needs to act on.`],
      opts:[
        {t:`Agree to daily updates, since a key customer is asking for them directly.`, s:1, d:{trust:0,conf:2,health:-2},
          after:`Ochoa gets daily updates that say "no change" four days out of five. By week five he stops opening them.`,
          why:`Responsiveness is good, but the real need is confidence that he'll hear bad news fast. Solve that need.`},
        {t:`Agree to keep the weekly report plus a same-day call for anything that goes red.`, s:3, best:true, d:{trust:0,conf:5,health:1},
          after:`Sam asks what Ochoa really wants. It's simple: he never wants to hear bad news from IronPeak first again. They agree on the weekly one-pager plus a call within the same business day for anything red. Ochoa is satisfied. Sam keeps his hour.`,
          why:`Manage communication by understanding the stakeholder's underlying need, then agree on frequency and triggers. Exception-based escalation often beats more volume.`},
        {t:`Give Ochoa access to the internal dashboard so he can check status any time.`, s:1, d:{trust:0,conf:1,health:0},
          after:`Ochoa looks once. He doesn't want a dashboard, he wants someone to call him.`,
          why:`Pull communication helps some stakeholders. Ochoa needed a commitment, not a link.`},
        {t:`Explain that daily updates aren't in the communication plan and decline politely.`, s:0, d:{trust:0,conf:-4,health:0},
          after:`Ochoa escalates to Elena.`,
          why:`Plans should change when stakeholder needs change. Pointing to the plan as a reason to say no misses the point.`}
      ]},
    { id:`f3s12`, domain:`People`, task:`P3`, title:`Who gets the credit`,
      text:(s,all,G)=>[`The integration layer passes its first end-to-end test. Elena is thrilled and wants to give a spot bonus to "whoever made it happen." Sam knows it took both sites, Priya's runbook, and a Kraków engineer who rewrote the data mapping over a weekend nobody asked him to work.`],
      opts:[
        {t:`Give the bonus to the Kraków engineer who rewrote the mapping over the weekend.`, s:0, d:{trust:-2,conf:0,health:-1},
          after:`One person gets money. Everyone else learns that weekend heroics are what gets rewarded.`,
          why:`Rewarding individual heroics on team work sends the wrong message and encourages burnout. Recognition should reinforce the behaviors you want.`},
        {t:`Recognize the whole team publicly for the milestone, naming specific contributions.`, s:3, best:true, d:{trust:6,conf:1,health:1},
          after:`At Friday's demo, Sam names what each group did: Priya's runbook, the Kraków mapping, the Denver test harness. Elena turns the bonus into a team dinner in each city. Tomasz posts photos from Kraków. Priya, named in front of the CEO, turns red and stays late Monday out of pure pride.`,
          why:`Recognition is a motivator. Make it specific, timely, and tied to team goals. Shared success builds the team; singling out one hero can split it.`},
        {t:`Ask the team to vote on who deserves the bonus most to keep it fair and open.`, s:0, d:{trust:-3,conf:0,health:0},
          after:`The vote turns a celebration into a popularity contest. Two people are hurt.`,
          why:`Peer voting for individual rewards on collaborative work creates competition inside the team. Recognize collective success.`},
        {t:`Decline the bonus, since the team was just doing the job it's paid to do.`, s:1, d:{trust:-1,conf:0,health:0},
          after:`Nobody objects. Nobody feels seen, either.`,
          why:`Recognition matters even when the work was expected. Not every milestone needs money, but it does need acknowledgment.`}
      ]}
  ],
  drills: [
    { after:`f3s5`, title:`Communication channels`, setup:[`Before Kraków joined, the core Cascade working group was 10 people. Tomasz's team adds 6 more.`,`Use n(n minus 1) / 2.`],
      fields:[{label:`Channels with 10 people`, answer:45, tol:0},{label:`Channels with 16 people`, answer:120, tol:0},{label:`Channels added by the Kraków team`, answer:75, tol:0}],
      solution:[`With 10 people: 10 times 9 divided by 2 = 45 channels.`,`With 16 people: 16 times 15 divided by 2 = 120 channels.`,`Added: 120 minus 45 = 75 channels. Six new people nearly tripled the possible lines of communication, which is why the communication plan had to change when the team did.`] }
  ],
  exercise: { after:`f3s10`, title:`Which Tuckman stage?`, intro:`Read each moment from the Cascade team and name the stage of team development.`,
    items:[
      {prompt:`Week two. Everyone in the first joint meeting is polite, careful, and waits to be called on.`, choices:[`Forming`,`Storming`,`Norming`,`Performing`,`Adjourning`], answer:0, why:`Polite, uncertain, and dependent on the leader is forming.`},
      {prompt:`A broken build turns into a ninety-message argument about which city is to blame.`, choices:[`Forming`,`Storming`,`Norming`,`Performing`,`Adjourning`], answer:1, why:`Open friction and blame as people test boundaries is storming.`},
      {prompt:`The team writes its own working agreements and starts holding each other to them.`, choices:[`Forming`,`Storming`,`Norming`,`Performing`,`Adjourning`], answer:2, why:`Agreeing on how to work together and following it is norming.`},
      {prompt:`The team handles a production issue at night without Sam, and tells him in the morning.`, choices:[`Forming`,`Storming`,`Norming`,`Performing`,`Adjourning`], answer:3, why:`Self-organizing and effective without supervision is performing.`},
      {prompt:`Go-live is done and the Kraków contract ends. People trade contact details and write handoff notes.`, choices:[`Forming`,`Storming`,`Norming`,`Performing`,`Adjourning`], answer:4, why:`Closing out and disbanding is adjourning.`},
      {prompt:`Two new engineers join a team that was running smoothly, and arguments over process start again.`, choices:[`Forming`,`Storming`,`Norming`,`Performing`,`Adjourning`], answer:1, why:`Teams can slip back a stage when membership changes. Renewed conflict means storming.`}
    ]},
  quiz: [
    {q:`A project team grows from 9 to 14 members. How many communication channels are added?`, opts:[`36`,`55`,`91`,`5`], a:1, why:`9 people: 9 times 8 divided by 2 = 36 channels. 14 people: 14 times 13 divided by 2 = 91 channels. 91 minus 36 = 55 added. The trap answers are the old total, the new total, and the headcount change.`, task:`P8`, domain:`People`},
    {q:`In a RACI matrix, how many people should be Accountable for a single deliverable?`, opts:[`Exactly one`,`At least two`,`One per team`,`As many as needed`], a:0, why:`Only one person is Accountable for each item. Shared accountability means nobody is accountable.`, task:`R4`, domain:`Process`},
    {q:`New members join a high-performing team, and arguments about process begin again. What is most likely happening?`, opts:[`The team is adjourning before the project ends`,`The new members lack the right technical skills`,`The project manager's authority is being tested`,`The team has returned to the storming stage`], a:3, why:`Teams can move back to storming when membership changes. Facilitate working agreements again.`, task:`P3`, domain:`People`},
    {q:`A distributed team keeps scheduling meetings that fall at midnight for one location. What should the project manager do first?`, opts:[`Thank the affected members for their extra effort`,`Cancel the meeting and move all updates to email`,`Establish working agreements on core overlap hours`,`Record the meeting so the remote site can watch later`], a:2, why:`Working agreements on overlap hours and async communication create a fair rhythm. Rotation is for when no overlap exists.`, task:`P8`, domain:`People`},
    {q:`In a matrix organization, a functional manager plans to reassign a key project team member. What should the project manager do first?`, opts:[`Ask the sponsor to overrule the functional manager`,`Accept it, since the functional manager controls staff`,`Ask the team member to decline the new assignment`,`Discuss the impact with the functional manager and negotiate`], a:3, why:`In a matrix, the PM negotiates with the functional manager, makes the impact visible, and looks for options before escalating.`, task:`R4`, domain:`Process`},
    {q:`According to Herzberg, which is a motivator rather than a hygiene factor?`, opts:[`Recognition for achievement`,`Competitive salary levels`,`Good working conditions`,`Clear company policies`], a:0, why:`Recognition, achievement, and growth are motivators. Pay, conditions, and policies are hygiene factors.`, task:`P3`, domain:`People`},
    {q:`Which communication method is best for resolving a complex, sensitive disagreement between two leads?`, opts:[`Push communication, such as a detailed email`,`Pull communication, such as a shared wiki page`,`Interactive communication, such as a meeting`,`A dashboard both leads can check at any time`], a:2, why:`Interactive communication suits complex or sensitive topics where discussion and immediate feedback are needed.`, task:`P8`, domain:`People`},
    {q:`A team keeps having conflicts about response times and review standards that were never written down. What should the project manager do?`, opts:[`Write the rules and post them for everyone to follow`,`Facilitate the team in creating a team charter together`,`Ask the senior engineers to set standards for the others`,`Wait for norms to form on their own as the team matures`], a:1, why:`A team charter built by the team creates working agreements people actually keep.`, task:`P3`, domain:`People`},
    {q:`A senior engineer's code reviews are curt and discouraging to a remote team. What should the project manager do first?`, opts:[`Talk privately with the engineer about the impact and norms`,`Remind the whole team that reviews must be respectful`,`Remove the engineer from reviewing the remote team's work`,`Tell the remote team that direct feedback is normal here`], a:0, why:`Address behavior privately and early, tied to agreed norms. Coach before escalating or reassigning.`, task:`P3`, domain:`People`},
    {q:`A key stakeholder asks for daily updates after a surprise delay. What should the project manager do first?`, opts:[`Start daily updates right away to rebuild confidence`,`Understand the underlying need and agree on triggers`,`Give the stakeholder access to the project dashboard`,`Decline, since daily updates aren't in the current plan`], a:1, why:`Find out what the stakeholder really needs, then tailor frequency and escalation triggers.`, task:`P8`, domain:`People`},
    {q:`Which document shows when specific team members are available to work on the project?`, opts:[`Resource breakdown structure`,`Team charter`,`Resource calendar`,`Responsibility matrix`], a:2, why:`Resource calendars show availability, including holidays and other commitments.`, task:`R4`, domain:`Process`},
    {q:`A leader focuses on removing obstacles, developing team members, and putting the team's needs first. Which style is this?`, opts:[`Transactional leadership`,`Autocratic leadership`,`Laissez-faire leadership`,`Servant leadership`], a:3, why:`Servant leadership serves the team by removing impediments and enabling their success.`, task:`P3`, domain:`People`},
    {q:`After a major milestone, the sponsor wants to reward one individual, though the result came from the whole team. What should the project manager recommend?`, opts:[`Reward the individual who worked the most hours`,`Let the team vote on who deserves the reward most`,`Recognize the team, naming specific contributions`,`Skip recognition, since the team was doing its job`], a:2, why:`Team-based, specific recognition reinforces collaboration. Rewarding a lone hero can split the team.`, task:`P3`, domain:`People`},
    {q:`A remote team says they don't understand why the project matters. What should the project manager do?`, opts:[`Translate the vision statement for their team channel`,`Share real user stories so the purpose becomes concrete`,`Give them detailed specifications instead of a vision`,`Ask the CEO to present the company's overall mission`], a:1, why:`A common vision becomes real through stories and contact with the people the project serves.`, task:`P1`, domain:`People`},
    {q:`A team argues in Slack over who caused a broken build. What should the project manager do?`, opts:[`Identify who caused it and hold that person accountable`,`Ask everyone to stay professional and move forward`,`Split the codebase so the teams can't affect each other`,`Hold a blameless review focused on fixing the process`], a:3, why:`Blameless, process-focused reviews resolve conflict and move the team toward norming.`, task:`P2`, domain:`People`}
  ],
  closing:(s,all,G)=>[
    `Friday of week three is the first sprint review with both sites on screen. Sam expected it to feel like a milestone. It feels like a hallway after a fire drill.`,
    `Priya demos the integration layer. It works. Nobody asks a question. Tomasz's engineers keep their cameras off. A Denver engineer says <span class="said">"looks good"</span> in a tone that means nothing. Lena thanks everyone warmly and ends ten minutes early.`,
    `Afterward Sam sits in the empty conference room. On the flight line you could always tell when a crew didn't trust each other. Nobody said anything wrong. They just stopped telling each other things. A loose panel, a weird noise, a tool that went missing. Small silences. Ray Mendez used to say the silences were how jets got hurt.`,
    (s.score>=27?`He has the charter, the calendars, the RACI, and a team that wrote its own rules. What he doesn't have yet is a team that tells each other the truth. He's not sure a document can fix that.`:`He's got a RACI half the team ignores and a calendar nobody updates. Two sites, two teams, one project name. On a legal pad he writes what he'd redo from Monday. He stops at nine items and puts the pen down.`),
    `Ruth calls on his drive home. <span class="said">"How'd the review go?"</span>`,
    `<span class="said">"Quiet."</span>`,
    `<span class="said">"Quiet's the dangerous one,"</span> she says. <span class="said">"Loud teams are arguing. Quiet teams are hiding. I learned that the expensive way."</span> She doesn't say how. Sam doesn't ask. Not yet.`,
    `Monday, burn-in starts at IronPeak. Sam is brushing his teeth at 6:40 when his phone lights up on the sink. It's Theo, in the team channel, no greeting, no emoji: <span class="said">"rack 4 threw an error. then rack 7. looking."</span> Sam spits, rinses, and reads it again. Then he reaches for his keys.`
  ],
  episode:{src:`audio/full-ch03.mp3`, len:`about 35 minutes`},
  next:`Burn-In`
});
