// Full Course, Chapter 4. Burn-In. See full/BIBLE.md.
(window.HALCYON_FULL=window.HALCYON_FULL||[]).push({
 num:4, part:`Part One: The Cascade Launch`, title:`Burn-In`, weeks:`Weeks 3 to 5`,
 tasks:[`R7`,`B5`,`R5`,`B4`,`B6`],
 cast:[[`Hal Brennan`,`Site operations manager at IronPeak, the GPU colocation vendor.`],[`Joan Pruitt`,`Halcyon procurement lead. Reads every contract twice.`]],
 opening:[
  `The text came in at 5:48 on a Monday morning. Sam saw it because he was already awake, lying in the dark, replaying Friday's sprint review. Eight people on the call. Two questions. Nobody had disagreed with anything, and he'd learned enough by now to know that wasn't good news.`,
  `The text was from Theo. <span class="said" data-who="Theo">"Burn-in finished overnight. Half the GPUs failed. Call me when you're up."</span>`,
  `Dana rolled over and looked at him in the light of the phone. She taught chemistry to sixteen year olds and could read a face across a parking lot. <span class="said" data-who="Dana">"That's your work face,"</span> she said. <span class="said" data-who="Dana">"It's not even six."</span>`,
  `<span class="said" data-who="Sam">"The cluster failed its test."</span>`,
  `<span class="said" data-who="Dana">"Is that the expensive thing?"</span>`,
  `<span class="said" data-who="Sam">"That's the expensive thing."</span>`,
  `Burn-in is the seventy-two hour stress run every new rack of hardware goes through before anyone trusts it. The IronPeak cluster held the GPUs that would run Halcyon's agents for Cascade Valley Health. Integration testing was supposed to start on it in three weeks. Go-live sat nine weeks behind that, and the contract didn't care about burn-in.`,
  `By eight Sam was at IronPeak's site east of the airport, a long gray building with no windows and a guard who checked IDs twice. The air inside was cold and loud and smelled like hot dust. Hal Brennan, IronPeak's site operations manager, met him at the cage with coffee and a theory. <span class="said" data-who="Hal">"Bad batch from the manufacturer,"</span> Hal said. <span class="said" data-who="Hal">"Happens. We'll swap them and rerun."</span>`,
  `Sam looked at the dark half of the racks. Twelve years ago a crew chief named Ray Mendez had told him something on a flight line in the snow, and it came back to him now. <span class="said" data-who="Ray">"The jet doesn't care what you think broke it, Okafor. Prove it."</span>`
 ],
 lesson:{
  title:`Quality and risk`,
  sections:[
   {h:`Quality is planned, managed, and controlled`,
    body:[`The exam splits quality into three ideas. Planning quality means deciding what good looks like before work starts: the standards, the metrics, and the acceptance criteria. Managing quality, often called quality assurance, is about the process. Are we doing the work in a way that produces good results? Audits, process improvements, and checklists live here, and so does feeding what you learn back into the organization's standard procedures so the next project doesn't repeat the defect. Controlling quality, or quality control, is about the product. Inspect the deliverable, test it, measure it against the criteria.`,
     `The mindset the exam rewards is prevention over inspection. It's cheaper to build quality in than to find defects later. That's what cost of quality measures. The cost of conformance is what you spend to get it right: prevention, like training and standards, and appraisal, like reviews, tests, and burn-in. The cost of nonconformance is what you pay when you don't: internal failures caught before the customer sees them, like scrap and rework, and external failures the customer finds, like warranty work, rejected deliverables, and lost trust. When a question offers you "add more inspection" or "fix the process that let the defect through," the process fix is usually the better answer. In agile teams, the same idea shows up as a definition of done, automated tests, and small batches that surface problems early.`,`Quality is also different from grade. A basic model of a car can be high quality: it does exactly what it promises, every time. A luxury model with a dashboard that reboots on the highway is high grade and low quality. The exam treats low grade as a business choice and low quality as a problem. Precision and accuracy get the same treatment. Precise measurements cluster tightly; accurate ones land near the true value. You want both, and the quality management plan says how close is close enough.`],
    terms:[[`Quality assurance (QA)`,`Process focused. Prevents defects by improving how work is done.`],[`Quality control (QC)`,`Product focused. Finds defects by inspecting and testing deliverables.`],[`Cost of quality`,`Cost of conformance (prevention, appraisal) plus cost of nonconformance (internal and external failures).`],[`Grade`,`A category of features. Low grade is fine; low quality is not.`]],
    exam:`Look for whether the question is about the process or the product. "Audit," "improve the process," and "lessons applied" point to managing quality. "Inspect," "test," and "measure the deliverable" point to controlling it.`},
   {h:`Finding the real cause`,
    body:[`A defect is a symptom. Root cause analysis finds what produced it. The five whys keeps asking why until you hit something you can fix. A fishbone or Ishikawa diagram sorts possible causes into groups like people, process, materials, and environment. A Pareto chart ranks causes by how often they happen, because a few causes usually produce most of the problems.`,
     `Control charts show whether a process is stable. Points outside the control limits mean the process is out of control. So does the rule of seven: seven consecutive points on one side of the mean, even inside the limits, signal a pattern worth investigating.`],
    terms:[[`Control limits`,`The range a stable process naturally varies within, usually three standard deviations from the mean.`],[`Specification limits`,`What the customer requires. Set by the customer, not the process.`],[`Rule of seven`,`Seven points in a row on one side of the mean suggests a non-random cause.`]],
    exam:`If a question asks what to do first about a recurring defect, analyzing the root cause usually beats rework, more inspection, or replacing a person.`},
   {h:`Risks and issues`,
    body:[`A risk is uncertain. It might happen, and it might help or hurt. An issue is a risk that already happened, or a problem nobody saw coming. Risks go in the risk register with an owner, a probability and impact, a trigger that tells you it's starting, and a planned response. Issues go in the issue log with an owner and a due date for resolution.`,
     `Qualitative analysis ranks risks quickly with a probability and impact matrix so you spend effort on the ones that matter. Quantitative analysis puts numbers on the biggest risks. Expected monetary value, or EMV, is probability times impact. Threats carry negative values, opportunities positive. Decision trees chain EMV across choices. Monte Carlo simulation runs the schedule or budget thousands of times to show a range of likely outcomes.`,`Risk management starts with a plan, not a list. The risk management plan sets how the team will identify, analyze, and respond to risks, who is involved, how often the register gets reviewed, and the organization's risk appetite. Identification works best with the people closest to the work: interviews, brainstorming, assumption analysis, and reviewing lessons from past projects. A good risk statement has a cause, the uncertain event, and its effect. Compare "technical complexity" with "because the firmware process has no verification step, GPUs may ship with old firmware, which would fail burn-in and delay integration testing." Only the second one can be owned.`],
    terms:[[`Risk owner`,`The person who monitors a risk and carries out its response.`],[`Trigger`,`A warning sign that a risk is about to happen or is happening.`],[`Risk threshold`,`The level of exposure an organization will accept.`],[`EMV`,`Probability multiplied by impact, summed across outcomes.`]],
    exam:`When something has already happened, the exam wants it treated as an issue: act on it, log it, and update the register so the risk entry reflects reality.`},
   {h:`Responding to risk`,
    body:[`For threats you have five strategies. Escalate when the risk is outside your authority or your project's scope. Avoid by changing the plan so the risk can't happen. Transfer by shifting the impact to someone else, like insurance, a warranty, or a fixed price contract. Mitigate by reducing probability or impact. Accept by acknowledging it, sometimes with a contingency reserve set aside.`,
     `Opportunities mirror these: escalate, exploit (make sure it happens), share (partner with someone better placed), enhance (raise its probability or impact), and accept. Agile teams have their own tools for risk. A spike is a short, time boxed experiment that answers a technical question before the team commits to it. Small releases, frequent demos, and a risk-adjusted backlog all surface trouble early, when it's cheap. Every response can create a secondary risk, and whatever remains after a response is residual risk. A contingency plan runs if a trigger fires; a fallback plan runs if the contingency plan doesn't work.`,`Money for risk comes from two places. Contingency reserve covers identified risks, the known unknowns, and belongs to the project manager's cost baseline. Management reserve covers unidentified risks, the unknown unknowns, and sits outside the baseline under the sponsor's control. You'll see both again when the numbers come out in the next chapter.`],
    terms:[[`Secondary risk`,`A new risk created by a response.`],[`Residual risk`,`The risk left after a response is in place.`],[`Workaround`,`An unplanned response to a risk that occurred without a plan.`]],
    exam:`Transfer moves the impact but rarely removes the risk. Mitigate lowers probability or impact. If the question says the risk is outside the project manager's authority, escalate.`}
  ],
  video:[`oGYvxomQW-0`,`11.5 Plan Risk Responses | PMBOK Video Course`,`David McLachlan`,`12:07`]
 },
 scenes:[
  {id:`f4s1`, domain:`Business Environment`, task:`B4`, title:`Monday at the cage`,
   text:(s,all,G)=>[`Half the racks are dark. Hal wants to swap parts today. Theo is on the phone from home, talking too fast, sure it isn't software. Integration testing starts on this cluster in three weeks.`,`Sam has a few hours before Lena and Elena start asking questions. What does he do first?`],
   opts:[
    {t:`Log it as an issue, get Hal and Theo together today, and pull the failure data.`,s:3,best:true,d:{trust:3,conf:2,health:5},
     after:`By noon Hal, Theo, and Sam are standing around a laptop with the burn-in logs. Theo calms down once there's data to look at. Sam opens an issue in the log with himself as owner and a decision date of Wednesday.`,
     why:`This already happened, so it's an issue, not a risk. Own it, log it, and bring the people who can diagnose it together with the evidence. Acting on facts first is the move the exam rewards every time.`},
    {t:`Tell Elena the go-live date is at risk before anyone knows what failed and why.`,s:0,d:{trust:0,conf:-5,health:0},
     after:`Elena's reply comes in all capitals. She calls the board chair. By the time Sam has an answer, three executives are working from the worst case.`,
     why:`Escalating with no diagnosis spreads panic and costs you credibility. Find out what happened and what it means, then escalate with facts and options.`},
    {t:`Ask Theo to work overnight with IronPeak until every GPU passes burn-in again.`,s:0,d:{trust:-5,conf:0,health:-2},
     after:`Theo says yes. Of course he does. He's at the site until three in the morning, and nothing is fixed because nobody yet knows what's broken.`,
     why:`Throwing your most overloaded person at an undiagnosed problem burns him out and doesn't fix anything. Diagnose first.`},
    {t:`Raise the probability on the hardware risk in the register and wait for IronPeak.`,s:1,d:{trust:0,conf:0,health:-2},
     after:`The register is updated. IronPeak promises a report Thursday. Three days pass with nobody actively working the problem.`,
     why:`Updating the register is fine, but this isn't a risk anymore. It happened. It needs to be worked as an issue with an owner, not watched.`}
   ]},
  {id:`f4s2`, domain:`Process`, task:`R7`, title:`Hal's theory`,
   text:(s,all,G)=>[`Hal is sure it's a bad batch of GPUs. IronPeak can have replacements on site Thursday. It's the fastest fix on the table and Hal clearly wants to close this out.`,`Theo isn't so sure. The failures aren't random. They follow the power layout of the racks.`],
   opts:[
    {t:`Accept Hal's diagnosis and have IronPeak swap the failed GPUs this week.`,s:0,d:{trust:-2,conf:1,health:-4},
     after:`The new GPUs arrive Thursday. Burn-in runs again. Half of them fail in the same racks.`,
     why:`Replacing parts without confirming the cause treats the symptom. When the pattern points somewhere else, the fix is to find the cause, not repeat the swap.`},
    {t:`Ask for a root cause analysis, with data, before agreeing to any fix.`,s:3,best:true,d:{trust:3,conf:1,health:5},
     after:`Hal grumbles, then pulls the power logs. Theo maps the failures against the rack diagram. By Wednesday the pattern is clear: a bad batch of power distribution units, plus GPU firmware that never got updated during install.`,
     why:`Root cause before corrective action. A five whys or fishbone session, backed by the logs, finds what actually broke. Fixes chosen without it tend to fail twice.`},
    {t:`Rerun burn-in tonight to see whether the same GPUs fail a second time.`,s:1,d:{trust:0,conf:0,health:1},
     after:`They do fail again, in the same racks. Useful, but it cost three days to learn what the logs already showed.`,
     why:`More data helps, but repeating the test isn't analysis. Use the data you already have to find the cause.`},
    {t:`Have Halcyon's team take over the cluster and diagnose the failures themselves.`,s:0,d:{trust:-2,conf:-2,health:-2},
     after:`IronPeak's lawyers point out that Halcyon staff touching the hardware voids the warranty. Everyone backs off.`,
     why:`The cluster is IronPeak's to fix under the contract. Taking over their work can void protections you're paying for. Work through the vendor.`}
   ]},
  {id:`f4s3`, domain:`Process`, task:`R7`, title:`Two kinds of fixes`,
   text:(s,all,G)=>[`The power units and firmware explain everything. The bigger question is how it got through. IronPeak's install checklist had a line for firmware verification. Nobody on the install crew checked it.`,`Hal will replace the bad units. What should Sam ask for beyond that?`],
   opts:[
    {t:`Fix the units, then add firmware checks to IronPeak's install procedure.`,s:3,best:true,d:{trust:2,conf:2,health:5},
     after:`Hal agrees to a signed firmware verification step on every future install, with the readout attached to the handover. It costs IronPeak ten minutes per rack.`,
     why:`That's quality assurance: fixing the process that let the defect through, so it can't recur. Prevention beats inspection, and it's cheaper.`},
    {t:`Add a second full burn-in on every rack before handover from now on.`,s:1,d:{trust:0,conf:1,health:2},
     after:`It would catch the problem next time. It would also add three days to every install for a defect that a ten minute check prevents.`,
     why:`More inspection is quality control. It catches defects after the fact. It's not wrong, but the better answer prevents the defect at the source.`},
    {t:`Have Theo personally inspect every rack before Halcyon accepts handover.`,s:0,d:{trust:-4,conf:0,health:-1},
     after:`Theo adds one more thing to his list. He doesn't complain. Priya notices he's eating lunch at his desk again.`,
     why:`Adding inspection to your bottleneck person isn't a quality system. It's a single point of failure with a checklist.`},
    {t:`Accept the repair and move on, since this was a one time supplier problem.`,s:0,d:{trust:0,conf:-1,health:-3},
     after:`The repair holds. Two months later IronPeak installs a second cluster for another customer with the same skipped step.`,
     why:`If the process had a gap, the defect isn't one time. Lessons that don't change the process don't count as lessons.`}
   ]},
  {id:`f4s4`, domain:`People`, task:`P3`, title:`Who signed it`,
   text:(s,all,G)=>[`Tuesday standup has extra guests. Grant drops in, arms crossed. <span class="said" data-who="Grant">"So who signed off on this cluster?"</span> he asks the room.`,`Theo signed IronPeak's handover checklist. Everyone at the table knows it. Theo is looking at the floor.`],
   opts:[
    {t:`Say Theo signed the handover, so the team understands where the gap came from.`,s:0,flag:`blamedtheo`,d:{trust:-8,conf:1,health:-1},
     after:`Grant nods, satisfied. Theo says nothing for the rest of the meeting. Priya does the math on what happens to whoever is next.`,
     why:`Naming a person in public turns a process failure into a blame session. The team learns to hide problems, which is the opposite of what you need.`},
    {t:`Say the process had a gap, Sam owns the fix, and talk to Theo privately later.`,s:3,best:true,d:{trust:7,conf:1,health:2},
     after:`Grant opens his mouth, then closes it. After standup Sam finds Theo in the kitchen. <span class="said" data-who="Sam">"The checklist failed you,"</span> Sam says. <span class="said" data-who="Sam">"We're fixing the checklist."</span> Theo looks like he wants to believe it.`,
     why:`A leader takes public responsibility for the system and handles individual feedback in private. It protects trust and keeps people reporting problems.`},
    {t:`Say it's still being investigated and move the meeting on to the next topic.`,s:1,d:{trust:1,conf:-2,health:0},
     after:`The room exhales. Grant asks again in Slack an hour later.`,
     why:`Deflecting avoids the blame but leaves a vacuum. Better to answer the real question: the process failed, here's the fix, and you own it.`},
    {t:`Ask Theo to walk the room through what he missed during the handover.`,s:0,d:{trust:-6,conf:0,health:0},
     after:`Theo does it, voice flat. It's accurate and humiliating. Nobody learns anything they couldn't have read in the root cause report.`,
     why:`A public walk through of one person's miss is blame with extra steps. Share lessons learned as process lessons, not personal ones.`}
   ]},
  {id:`f4s5`, domain:`Business Environment`, task:`B5`, title:`The register nobody reads`,
   text:(s,all,G)=>[`Sam opens the project risk register for the first time since he inherited it. Forty-one rows. Most were written in the first week by the PM who quit. "Technical complexity." "Resource constraints." No owners. No triggers. The GPU hardware risk is row 33, rated low.`,`It's clear nobody has opened this file in a month.`],
   opts:[
    {t:`Score all forty-one risks on probability and impact before changing anything.`,s:1,d:{trust:0,conf:0,health:1},
     after:`It takes two afternoons. The scores are better. The rows are still vague and nobody owns them.`,
     why:`Qualitative analysis is useful, but scoring vague risks just ranks vague risks. Make them specific and owned first.`},
    {t:`Archive it and track risks in the weekly status email to keep things simple.`,s:0,d:{trust:0,conf:-2,health:-4},
     after:`The status email gets longer every week. Risks get mentioned once and forgotten.`,
     why:`A status email isn't a risk register. Risks need a home where they're tracked with owners, triggers, and responses over time.`},
    {t:`Rebuild it with specific risks, each with an owner, a trigger, and a response.`,s:3,best:true,d:{trust:3,conf:2,health:6},
     after:`Sam runs a ninety minute session with the leads. The register shrinks to nineteen real risks. Each one has a name next to it. "Key person dependency on Theo" goes in at high probability, high impact.`,
     why:`A register is only useful if it's specific and owned. Identify real risks with the people closest to the work, then assign owners, triggers, and planned responses.`},
    {t:`Ask each team lead to add any new risks they think of to the existing register.`,s:0,d:{trust:0,conf:0,health:-2},
     after:`Three new rows appear. They look a lot like the old ones.`,
     why:`Asking people to append to a broken tool keeps it broken. Fix the register, then make adding to it part of how the team works.`}
   ]},
  {id:`f4s6`, domain:`Business Environment`, task:`B5`, title:`Spares or cloud`,
   text:(s,all,G)=>[`Replacement power units are back ordered. Hal thinks there's a real chance the shipment slips past integration testing. Theo has two ideas. Buy a set of spare units outright, or rent cloud GPU capacity as a backup if the delay hits.`,`Joan from procurement can turn either one around in a week. Lena wants Sam to just pick.`],
   opts:[
    {t:`Compare expected value, using probability and cost for each option.`,s:3,best:true,d:{trust:2,conf:3,health:4},
     after:`Sam and Theo put numbers on it in an hour. The answer isn't the one either of them expected.`,
     why:`Quantitative risk analysis turns a gut call into a comparison. Expected monetary value weighs each option by how likely the bad outcome is.`},
    {t:`Pick the cloud backup, since it avoids a big purchase if nothing goes wrong.`,s:0,d:{trust:0,conf:0,health:-1},
     after:`It might be the right call. Sam just can't explain why to anyone who asks.`,
     why:`Choosing by instinct when the numbers are easy to get skips the analysis that makes the decision defensible.`},
    {t:`Ask Elena which option she prefers, since the money comes from her budget.`,s:1,d:{trust:0,conf:-1,health:0},
     after:`Elena asks what Sam recommends and why. He doesn't have an answer yet.`,
     why:`If the spend is above your authority, the sponsor decides. But bring analysis and a recommendation, not a blank question.`},
    {t:`Buy the spares now, since hardware delays are the bigger threat right now.`,s:0,d:{trust:0,conf:0,health:-1},
     after:`The spares arrive. So does the original shipment, on time. Joan asks who approved seventy thousand dollars.`,
     why:`Avoiding a risk at any price isn't a strategy. Compare the cost of each response against the expected cost of the risk.`}
   ]},
  {id:`f4s7`, domain:`Process`, task:`R5`, title:`Customer configuration`,
   text:(s,all,G)=>[`IronPeak's account team sends a polite email.`,`<prop type="email" from="IronPeak Account Team" to="Sam Okafor" time="9:14 AM" subject="Re: Burn-in failures">The power distribution units are covered under warranty and will be replaced at no charge. The firmware issue was a customer configuration matter and falls outside the warranty. We're happy to correct it at our standard rate.</prop>`,`Joan Pruitt has the contract open before Sam finishes reading. <span class="said" data-who="Joan">"Section nine,"</span> she says. <span class="said" data-who="Joan">"I want to read it twice."</span>`],
   opts:[
    {t:`Withhold IronPeak's next monthly payment until they fix the firmware for free.`,s:0,d:{trust:0,conf:-3,health:-3},
     after:`IronPeak's finance team flags the account. The relationship turns to letters between lawyers.`,
     why:`Withholding payment on your own may breach your side of the contract. Use the contract's dispute process instead.`},
    {t:`Review the terms with Joan, then send IronPeak a written claim citing them.`,s:3,best:true,d:{trust:1,conf:3,health:4},
     after:`Section nine says IronPeak installs and verifies firmware to the manufacturer's current release. Joan's claim cites it word for word. IronPeak fixes the firmware at no charge and adds a service credit.`,
     why:`Know your contract, document the claim, and go through the agreed process. Claims administration is a procurement task the exam expects you to own with your procurement team.`},
    {t:`Offer to split the cost with IronPeak to keep the relationship strong.`,s:1,d:{trust:0,conf:0,health:2},
     after:`IronPeak accepts immediately, which tells Joan everything she needed to know about their position.`,
     why:`Negotiating can be right, but not before you know what the contract says. You may be paying for something that's already covered.`},
    {t:`Have Halcyon's lawyers send IronPeak a formal breach notice this week.`,s:0,d:{trust:0,conf:-2,health:-1},
     after:`IronPeak's lawyers reply with their own letter. The firmware stays unfixed while both sides argue.`,
     why:`Legal escalation is a last resort. Start with the contract terms and a written claim through procurement.`}
   ]},
  {id:`f4s8`, domain:`Process`, task:`R8`, title:`Nine days`,
   text:(s,all,G)=>[`The repairs will finish nine days late. Integration testing was on the critical path, so the project just lost nine days of float it didn't have to spare.`,`Half the cluster is healthy now. Lena points out that some integration tests don't need the whole cluster at all.`],
   opts:[
    {t:`Start integration tests on the healthy half while repairs finish.`,s:3,best:true,d:{trust:2,conf:2,health:6},
     after:`Priya splits the test plan. The tests that need full scale wait. The rest start Monday. Six of the nine days come back.`,
     why:`That's fast tracking: doing work in parallel that was planned in sequence. It adds some risk of rework, but here the tests were independent, so the risk is low and the cost is zero.`},
    {t:`Pay IronPeak for a weekend crew to finish the repairs four days sooner.`,s:1,d:{trust:0,conf:1,health:3},
     after:`It works, and it costs twenty two thousand dollars Sam has to explain at the next board meeting.`,
     why:`That's crashing: adding resources to shorten the schedule. It's valid, but it costs money. When a free fast tracking option exists with low risk, start there.`},
    {t:`Cut performance testing from the plan to win back the nine days.`,s:0,d:{trust:-2,conf:-3,health:-5},
     after:`Lena goes quiet in a way Sam is learning to recognize. Maria at Cascade will eventually ask how the system performs under load.`,
     why:`Cutting quality activities to protect a date trades a visible problem for a hidden one. Look at fast tracking or crashing first.`},
    {t:`Move go-live nine days and tell Cascade on Friday's call.`,s:0,d:{trust:0,conf:-4,health:0},
     after:`Ochoa asks what options Sam considered. Sam realizes he didn't consider any.`,
     why:`Moving a contractual date is a last resort and not Sam's call alone. Try schedule compression first, then bring options to the sponsor.`}
   ]},
  {id:`f4s9`, domain:`Business Environment`, task:`B4`, title:`Locked out`,
   text:(s,all,G)=>[`After the incident, Halcyon's security team tightened remote access to staging. Nobody told Kraków. Tomasz's team has been locked out for two days.`,`Tomasz's message is short. <span class="said" data-who="Tomasz">"My team is billing you to wait. Tell me if that is the plan."</span>`],
   opts:[
    {t:`Have Tomasz's team write documentation until access is restored.`,s:1,d:{trust:-1,conf:0,health:-1},
     after:`They write documentation. Tomasz's next message is shorter.`,
     why:`Keeping people busy isn't removing the blocker. The servant leader's job is to clear the impediment, fast.`},
    {t:`Give Kraków temporary admin credentials so they aren't blocked any longer.`,s:0,d:{trust:1,conf:-2,health:-3},
     after:`Security finds out the next morning. Now there are two incidents.`,
     why:`Bypassing a security control to remove an impediment creates a compliance problem. Work with the control owner, not around them.`},
    {t:`Get security and Tomasz on a call today and agree on a safe access path.`,s:3,best:true,d:{trust:5,conf:1,health:4},
     after:`Forty minutes later Kraków has scoped access through the new jump host. Tomasz sends one word: <span class="said" data-who="Tomasz">"Good."</span> From Tomasz, that's a parade.`,
     why:`Removing impediments is a core servant leadership task. Bring the people who can clear it together quickly and solve it within the rules.`},
    {t:`Raise it at next week's steering meeting as an escalation for Lena.`,s:0,d:{trust:-3,conf:0,health:-3},
     after:`A week of contractor time is lost waiting for a meeting.`,
     why:`An impediment you can clear today shouldn't wait for a steering committee. Escalate only what you can't resolve yourself.`}
   ]},
  {id:`f4s10`, domain:`People`, task:`P8`, title:`Friday's page`,
   text:(s,all,G)=>[`Friday's one page status goes to Ochoa at four. This is the first week with real bad news in it.`,`Grant stops by Sam's desk. <span class="said" data-who="Grant">"Lead with the recovery,"</span> he says. <span class="said" data-who="Grant">"Nobody needs the gory details."</span>`],
   opts:[
    {t:`Report the recovery plan only, since the failure is already being fixed.`,s:1,d:{trust:0,conf:-2,health:0},
     after:`Ochoa reads it and asks on Monday's call what the recovery is recovering from.`,
     why:`Partial transparency still leaves the stakeholder guessing. Give the whole picture plainly, with the plan attached.`},
    {t:`Report the failure, its root cause, the recovery, and the days at risk.`,s:3,best:true,d:{trust:1,conf:6,health:1},
     after:`Ochoa replies in four minutes. <span class="said" data-who="Ochoa">"Thank you for not making me find this out myself."</span>`,
     why:`Stakeholders trust project managers who tell them bad news early, with facts and a plan. That's how communication management earns confidence.`},
    {t:`Leave the cluster out of this week's status until repairs are complete.`,s:0,flag:`hidfromochoa`,d:{trust:0,conf:-7,health:0},
     after:`Ochoa hears about it from his own infrastructure lead, who heard it from IronPeak.`,
     why:`Stakeholders always find out. When they find out from someone else, you lose trust you can't easily get back.`},
    {t:`Send IronPeak's full incident report and let Ochoa draw his own conclusions.`,s:0,d:{trust:0,conf:-1,health:0},
     after:`Ochoa forwards the twenty page report to his team with one line: "What does this mean for us?"`,
     why:`Information isn't communication. Tailor the message to what the stakeholder needs to know and decide.`}
   ]},
  {id:`f4s11`, domain:`Process`, task:`R7`, title:`One more burn-in`,
   text:(s,all,G)=>[`Repairs are done. A second full burn-in would take three days. Lena wants to skip it. <span class="said" data-who="Lena">"We know the cause. We fixed the cause. Why burn three days proving it?"</span>`,`It's a fair question, and it's the CTO asking it.`],
   opts:[
    {t:`Run a shorter burn-in on a sample of racks to save two of the three days.`,s:1,d:{trust:0,conf:0,health:2},
     after:`The sample passes. Nobody knows about the racks that weren't sampled.`,
     why:`Sampling can be reasonable, but on a cluster this critical a defect in an untested rack costs far more than a day.`},
    {t:`Skip it, since the root cause is known and the fixes are already in place.`,s:0,d:{trust:0,conf:0,health:-5},
     after:`Two weeks into integration testing, one rack throws errors. It costs nine days to isolate.`,
     why:`Knowing the cause isn't proof the fix worked. Verification is part of quality control.`},
    {t:`Let IronPeak decide, since the cluster is still their responsibility.`,s:0,d:{trust:0,conf:-1,health:-2},
     after:`IronPeak decides to skip it. Their incentives aren't Halcyon's.`,
     why:`Acceptance criteria belong to the buyer. Don't hand your quality decision to the vendor whose work is being checked.`},
    {t:`Run it. A bad GPU costs far less to find now than in production.`,s:3,best:true,d:{trust:2,conf:2,health:5},
     after:`Lena sighs and agrees. The burn-in catches one more bad unit the repair missed. It takes Hal an hour to swap.`,
     why:`That's the cost of quality. Appraisal now costs three days. An external failure in front of nurses would cost the contract.`}
   ]},
  {id:`f4s12`, domain:`Business Environment`, task:`B5`, title:`Row one`,
   text:(s,all,G)=>[`Late Friday, Sam looks at the new risk register. Row one: key person dependency on Theo. High probability, high impact. Theo was the only person who could read those burn-in logs, and he hasn't slept properly in three weeks.`,((s.flags&&s.flags.blamedtheo)||G.blamedtheo?`Since Tuesday's standup, Theo has stopped volunteering anything. He does what he's asked and nothing more.`:`Theo has been quieter since the burn-in. He still answers every message at midnight.`)],
   opts:[
    {t:`Ask Theo to document everything he knows by the end of the month.`,s:1,d:{trust:-1,conf:0,health:2},
     after:`Theo adds it to the list. The documentation is accurate and twelve pages long. Nobody else can use it yet.`,
     why:`Documentation helps, but explicit knowledge alone rarely transfers the tacit skill. A real response builds capability in someone else.`},
    {t:`Hire a senior contractor now as a backup in case Theo ever leaves.`,s:0,d:{trust:-3,conf:0,health:-1},
     after:`Theo finds out from the job posting. It reads exactly like what it is.`,
     why:`Acting on a people risk without talking to the person, and without a plan, damages the trust you were trying to protect.`},
    {t:`Leave it off the register, since Theo might take it as a threat.`,s:0,d:{trust:0,conf:0,health:-4},
     after:`The risk stays real whether or not anyone writes it down.`,
     why:`Avoiding an uncomfortable risk doesn't make it go away. Log it, own it, and respond with care for the person.`},
    {t:`Make Priya's shadowing the planned response, with Sam as the risk owner.`,s:3,best:true,d:{trust:3,conf:1,health:4},
     after:`Sam blocks two hours a week for Priya and Theo to pair. He tells Theo why, plainly. Theo almost smiles. <span class="said" data-who="Theo">"She's better than she thinks,"</span> he says.`,
     why:`A key person risk needs an owner and a mitigation that actually spreads the skill. Pairing transfers tacit knowledge in a way documents can't.`}
   ]}
 ],
 drills:[
  {after:`f4s6`, title:`Expected monetary value`,
   setup:[`Hal estimates a 40 percent chance the replacement power units arrive late. If they do and Halcyon has no backup, the delay costs about $150,000 in overtime, rework, and schedule penalties.`,`Option 1, accept: do nothing extra. Option 2, mitigate: rent cloud GPU backup now for $35,000. If the delay happens anyway, the impact drops to $40,000. Option 3, avoid: buy spare units for $70,000. With spares on hand, a late shipment costs nothing.`,`Treat costs as negative numbers.`],
   table:[[`Option`,`Up front cost`,`Probability of delay`,`Impact if delayed`],[`1. Accept`,`$0`,`40%`,`$150,000`],[`2. Cloud backup`,`$35,000`,`40%`,`$40,000`],[`3. Buy spares`,`$70,000`,`40%`,`$0`]],
   fields:[{label:`Expected cost of option 1 ($)`,answer:-60000,tol:1},{label:`Expected cost of option 2 ($)`,answer:-51000,tol:1},{label:`Expected cost of option 3 ($)`,answer:-70000,tol:1},{label:`Best option (1, 2, or 3)`,answer:2,tol:0}],
   solution:[`EMV = probability times impact, plus any certain cost.`,`Option 1: 0.40 times negative $150,000 = negative $60,000. Option 2: negative $35,000 plus 0.40 times negative $40,000 = negative $35,000 minus $16,000 = negative $51,000. Option 3: negative $70,000 plus 0.40 times $0 = negative $70,000.`,`Option 2 has the least negative expected value, so the cloud backup is the best mitigation. Buying spares removes the risk entirely but costs more than the risk is worth on average.`]}
 ],
 exercise:{after:`f4s9`, title:`Pick the risk response`, intro:`Match each situation to the threat response strategy it describes.`,
  items:[
   {prompt:`Halcyon adds a firmware verification step so the defect can't happen again on future installs.`,choices:[`Avoid`,`Transfer`,`Mitigate`,`Accept`,`Escalate`],answer:0,why:`Changing the plan or process so the risk can't occur is avoidance.`},
   {prompt:`The IronPeak contract makes IronPeak pay for hardware defects under warranty.`,choices:[`Avoid`,`Transfer`,`Mitigate`,`Accept`,`Escalate`],answer:1,why:`Shifting the financial impact to another party is transfer. The risk can still happen.`},
   {prompt:`Priya pairs with Theo every week so losing him would hurt less.`,choices:[`Avoid`,`Transfer`,`Mitigate`,`Accept`,`Escalate`],answer:2,why:`Reducing the impact of a risk is mitigation.`},
   {prompt:`A small chance the office internet fails during a demo is noted, with a phone hotspot ready.`,choices:[`Avoid`,`Transfer`,`Mitigate`,`Accept`,`Escalate`],answer:3,why:`Acknowledging a low risk with a simple contingency is active acceptance.`},
   {prompt:`A risk that a company wide AI policy will change is outside the project's authority, so it goes to Elena.`,choices:[`Avoid`,`Transfer`,`Mitigate`,`Accept`,`Escalate`],answer:4,why:`Risks outside the project's scope or authority are escalated to whoever owns them.`},
   {prompt:`Renting cloud GPUs as a backup lowers the cost if the shipment is late.`,choices:[`Avoid`,`Transfer`,`Mitigate`,`Accept`,`Escalate`],answer:2,why:`The risk can still happen, but its impact is smaller. That's mitigation.`}
  ]},
 quiz:[
  {q:`A team finds the same defect in three consecutive releases. What should the project manager do first?`,opts:[`Add a second round of testing before each release goes out`,`Perform a root cause analysis on the process producing the defect`,`Replace the team member responsible for the affected module`,`Raise the defect to the sponsor as a quality risk to the release`],a:1,why:`Recurring defects point to a process problem. Find the root cause before choosing a fix. More testing is inspection, not prevention.`,task:`R7`,domain:`Process`},
  {q:`Which activity is an example of quality assurance rather than quality control?`,opts:[`Testing a finished module against its acceptance criteria`,`Inspecting a sample of delivered units for visible damage`,`Auditing the build process to confirm standards are followed`,`Measuring response times of the release in a staging test`],a:2,why:`QA is about the process. Auditing whether the process is followed is QA. The others inspect or measure the product.`,task:`R7`,domain:`Process`},
  {q:`The test team plots defects per build. The last seven builds all sit below the mean, and every point is inside the control limits. What should the project manager conclude?`,opts:[`The process is stable, since every point is inside the limits`,`The sample size is too small to draw any useful conclusion`,`The specification limits need to be widened by the customer`,`The process may have a non random cause worth investigating`],a:3,why:`The rule of seven says seven points on one side of the mean suggests a non random pattern, even inside the limits.`,task:`R7`,domain:`Process`},
  {q:`A risk the team identified last month has now occurred. What should the project manager do?`,opts:[`Update its probability rating in the register to reflect it`,`Treat it as an issue, act on the planned response, and log it`,`Add it to the lessons learned register for the next project`,`Escalate it to the sponsor, since it can no longer be avoided`],a:1,why:`A risk that occurs becomes an issue. Implement the planned response, track it in the issue log, and update the register.`,task:`B4`,domain:`Business Environment`},
  {q:`A risk has a 25 percent chance of occurring with an impact of $80,000. A mitigation costs $12,000 and cuts the impact to $20,000. What is the expected cost with mitigation?`,opts:[`$17,000`,`$20,000`,`$32,000`,`$5,000`],a:0,why:`$12,000 plus 0.25 times $20,000 equals $12,000 plus $5,000, or $17,000. Without mitigation the EMV is $20,000, so mitigation saves $3,000 on average.`,task:`B5`,domain:`Business Environment`},
  {q:`The team buys an insurance policy to cover equipment damage during shipping. Which response is this?`,opts:[`Mitigate`,`Avoid`,`Accept`,`Transfer`],a:3,why:`Insurance shifts the financial impact to another party, which is transfer.`,task:`B5`,domain:`Business Environment`},
  {q:`A project manager learns of a regulatory risk that affects the whole company, not just the project. What is the best response?`,opts:[`Mitigate it within the project budget as soon as possible`,`Accept it, since it is outside the project manager's control`,`Escalate it to the appropriate owner outside the project`,`Avoid it by removing affected features from project scope`],a:2,why:`Risks outside the project's scope or authority are escalated to the right owner in the organization.`,task:`B5`,domain:`Business Environment`},
  {q:`A vendor says a failure is not covered by the contract. What should the project manager do first?`,opts:[`Withhold the vendor's next payment until it is resolved`,`Accept the vendor's position to protect the relationship`,`Ask legal to send a formal notice of breach to the vendor`,`Review the contract terms with procurement before responding`],a:3,why:`Know the contract before acting. Then pursue a claim through the agreed process with procurement.`,task:`R5`,domain:`Process`},
    {q:`A recurring installation defect has been fixed and the root cause found. What should the project manager do so it doesn't recur on future installs?`, opts:[`Record it in the issue log and close the entry once resolved`,`Update the standard install procedure and share the lesson`,`Ask the vendor to add more inspectors to each future install`,`Schedule a full re-test of every past installation this month`], a:1, why:`Continuous improvement means changing the process that let the defect through and feeding the lesson into the organization's standard procedures. Closing the issue fixes this project only, and more inspection is appraisal, not prevention.`, task:`B6`, domain:`Business Environment`},
  {q:`A remote team has been blocked for two days by an access problem. What should the project manager do?`,opts:[`Work with the access owner today to remove the blocker`,`Reassign the remote team to documentation work for now`,`Note the impediment for the next steering meeting agenda`,`Ask the remote team lead to resolve it with security alone`],a:0,why:`Removing impediments quickly is a servant leadership duty. Engage the people who can clear it now.`,task:`B4`,domain:`Business Environment`},
  {q:`Which of these is a cost of nonconformance?`,opts:[`Training the team on coding standards before work begins`,`Reworking a deliverable the customer rejected at acceptance`,`Running code reviews on every change before it is merged`,`Purchasing a test automation tool for the delivery team`],a:1,why:`Rework after a failure is a cost of nonconformance. Training, reviews, and tools are costs of conformance.`,task:`R7`,domain:`Process`},
  {q:`After a risk response is implemented, a new risk appears because of that response. What is it called?`,opts:[`Residual risk`,`Emergent risk`,`Secondary risk`,`Contingent risk`],a:2,why:`A secondary risk arises directly from implementing a risk response. Residual risk is what remains of the original risk.`,task:`B5`,domain:`Business Environment`},
  {q:`An agile team wants to reduce technical uncertainty about a new integration before committing to it. What is the best approach?`,opts:[`Add the integration to the risk register and monitor it closely`,`Plan a time boxed spike to explore the integration early`,`Ask the product owner to remove it from the release backlog`,`Assign the most senior developer to build it right away`],a:1,why:`A spike is a short, time boxed experiment that reduces risk early, a common agile risk response.`,task:`B5`,domain:`Business Environment`},
  {q:`During a status meeting, an executive asks who caused a defect. What should the project manager do?`,opts:[`Name the person so the team can learn from the mistake`,`Say the defect is under review and move to the next topic`,`Explain the process gap and the fix, and follow up privately`,`Ask the person responsible to explain the defect to everyone`],a:2,why:`Address process failures publicly and personal feedback privately. Blame discourages people from reporting problems.`,task:`P3`,domain:`People`},
  {q:`A risk register has many entries with no owners. What is the most important fix?`,opts:[`Assign an owner who will monitor each risk and its response`,`Rerun the qualitative analysis to rescore every listed risk`,`Move the low priority risks onto a separate watch list now`,`Have the sponsor review and approve the full register again`],a:0,why:`Every risk needs an owner who monitors it and carries out the response. Unowned risks aren't managed.`,task:`B5`,domain:`Business Environment`}
 ],
 closing:(s,all,G)=>[
  `The cluster passed its second burn-in on a Thursday at 2:14 in the afternoon. Theo sent the result to the channel with no comment.`,
  `<prop type="chat" from="Theo" time="2:14 PM">burn-in 2: all racks pass. 0 errors.</prop>`,
  `Priya added a thumbs up. Hal sent a photo of all the racks lit green, which Sam suspected was the closest IronPeak got to an apology.`,
  `Nine days of float were gone. Six came back through fast tracking. The plan held, barely.`,
  `That evening Sam had dinner with Ruth at a diner on Colfax she swore made the best green chile in Denver. She read the risk register on his phone while her food got cold.`,
  `<span class="said" data-who="Ruth">"Row one,"</span> she said. <span class="said" data-who="Ruth">"Good. Most people don't write that one down."</span> She was quiet for a moment. <span class="said" data-who="Ruth">"Early in my career I saw a sensor reading I didn't like. I talked myself out of mentioning it. I didn't want to be the alarmist in the room."</span>`,
  `Sam waited. She picked up her fork instead.`,
  `<span class="said" data-who="Ruth">"Another time,"</span> she said. <span class="said" data-who="Ruth">"Write things down, Sam. Even the ones that make people uncomfortable. Especially those."</span>`,
  (s.score>=27?`On the drive home he realized he hadn't checked his phone once during dinner. Dana noticed too.`:`On the drive home he checked his phone at every red light. Dana took it out of his hand at the last one.`),
  `At home there was an email from Elena.`,
  `<prop type="email" from="Elena Vasquez" to="Sam Okafor" time="8:47 PM" subject="Board moved up">The board meeting moved up. I need the budget, the burn-in costs, and a forecast by Tuesday.<br><span class="said" data-who="Elena">Real numbers. Last quarter a board member called our forecasts vibes.</span></prop>`,
  `Sam opened a spreadsheet and started building them.`
 ],
 episode:{src:`audio/full-ch04.mp3`, len:`about 35 minutes`},
 next:`The Numbers`
});
