// Full Course, Chapter 5. The Numbers. See full/BIBLE.md.
(window.HALCYON_FULL=window.HALCYON_FULL||[]).push({
 num:5, part:`Part One: The Cascade Launch`, title:`The Numbers`, weeks:`Weeks 5 to 6`,
 tasks:[`R6`,`R9`,`P6`],
 cast:[[`Douglas Reyes`,`Halcyon board member and audit committee chair. Former hospital CFO.`]],
 opening:[
  `At 1:20 in the morning Sam was still at the kitchen table with a laptop, a legal pad, and a mug of coffee that had gone cold around eleven. The board meeting was Tuesday. Elena wanted real numbers. Sam had discovered that Halcyon didn't really have any.`,
  `The Cascade budget was one line in the sales deal: two million and forty thousand dollars. Nobody could tell him how Grant's team had arrived at it. The finance system tracked spending by department, not by project. The engineers reported progress as percentages, and every percentage was somewhere between eighty and ninety, which in Sam's experience meant nobody knew.`,
  `Dana came down for water and found him there. She looked over his shoulder at the legal pad, which had the same column of numbers added up four times.`,
  `<span class="said" data-who="Dana">"You're doing the thing,"</span> she said. <span class="said" data-who="Dana">"Where you check it five times because you don't trust the first four."</span>`,
  `<span class="said" data-who="Sam">"I don't trust the inputs."</span>`,
  `<span class="said" data-who="Dana">"Then fix the inputs."</span> She kissed the top of his head. <span class="said" data-who="Dana">"I tell my juniors that every week. Garbage measurements, garbage results. Go to bed."</span>`,
  `He didn't go to bed. But he wrote one line at the top of the legal pad, underlined twice: "What did we plan to have done by now, and what is actually done?"`,
  `On Saturday morning he called Ruth. She listened to the whole mess without interrupting, then laughed. <span class="said" data-who="Ruth">"Sam, every program I ever ran had this problem in week five. You know what saved us? We stopped asking people how they felt about progress and started measuring what they'd finished."</span>`
 ],
 lesson:{
  title:`Money and measurement`,
  sections:[
   {h:`From estimates to a cost baseline`,
    body:[`Cost estimates come in a few flavors. Analogous estimating uses a similar past project, fast but rough. Parametric estimating uses a unit rate, like dollars per rack or hours per user story. Bottom up estimating adds up the estimates for each work package in the WBS, slower but the most accurate. Three point estimating uses optimistic, most likely, and pessimistic values; the beta, or PERT, formula is (O + 4M + P) / 6.`,
     `Add up the work package estimates and you get the cost of the work. Add contingency reserve for identified risks and you have the cost baseline. The baseline is what you measure performance against, and it can only change through formal change control. Add management reserve for unidentified risks and you have the total project budget. The project manager controls contingency reserve. Using management reserve takes the sponsor's approval and usually a change to the baseline.`,
     `Funding rarely arrives all at once. Funding limit reconciliation means checking that planned spending each period fits the cash the organization will actually release.`],
    terms:[[`BAC`,`Budget at completion. The total cost baseline.`],[`Contingency reserve`,`Money for known risks. Inside the cost baseline. PM controls it.`],[`Management reserve`,`Money for unknown risks. Outside the baseline. Sponsor controls it.`]],
    exam:`If the question asks where money for an identified risk comes from, it's contingency reserve. For something nobody saw coming, it's management reserve, with sponsor approval.`},
   {h:`Earned value, in plain words`,
    body:[`Planned value, PV, is the budgeted cost of the work you planned to finish by now. Earned value, EV, is the budgeted cost of the work you actually finished. Actual cost, AC, is what you really spent to finish it. Every earned value question is a comparison of those three.`,
     `Schedule variance, SV = EV minus PV. Negative means behind schedule. Cost variance, CV = EV minus AC. Negative means over budget. The indexes turn those into ratios: SPI = EV divided by PV, and CPI = EV divided by AC. Above 1 is good. Below 1 is bad. EV is always first in the formula, which is the easiest way to remember them.`,
     `To measure EV honestly, use objective rules instead of opinions. The 0/100 rule gives credit only when a work package is done. The 50/50 rule gives half credit at the start and half at the finish. Agile teams use completed story points against a release plan, counting only work that meets the definition of done.`],
    terms:[[`SV = EV minus PV`,`Schedule variance.`],[`CV = EV minus AC`,`Cost variance.`],[`SPI = EV / PV`,`Schedule performance index.`],[`CPI = EV / AC`,`Cost performance index.`]],
    exam:`Read which numbers the question gives you, write the formula, and check the sign. A negative variance or an index under 1 is bad news.`},
   {h:`Forecasting the finish`,
    body:[`Estimate at completion, EAC, is what the whole project will cost now. Which formula you use depends on what you believe about the future. If current cost performance will continue, EAC = BAC divided by CPI. If the overrun was a one time event and the rest will go to plan, EAC = AC + (BAC minus EV). If both cost and schedule performance will drag on the remaining work, EAC = AC + (BAC minus EV) divided by (CPI times SPI). If the original estimate was simply wrong, re-estimate the remaining work bottom up: EAC = AC + a new estimate to complete.`,
     `Estimate to complete, ETC, is what's left to spend: EAC minus AC. Variance at completion, VAC = BAC minus EAC; negative means you'll finish over budget.`,
     `To complete performance index, TCPI, asks how efficient you must be on the remaining work to hit a target. To hit BAC: (BAC minus EV) divided by (BAC minus AC). To hit a new EAC, put EAC in place of BAC in the bottom half. A TCPI well above 1 means you're asking the team for efficiency they haven't shown, which is a planning conversation, not a pep talk.`],
    terms:[[`EAC`,`Estimate at completion.`],[`ETC = EAC minus AC`,`Estimate to complete.`],[`VAC = BAC minus EAC`,`Variance at completion.`],[`TCPI`,`Efficiency needed on remaining work to hit a target.`]],
    exam:`The question usually tells you which EAC to use with words like "typical," "atypical," "expected to continue," or "one time." Match the words to the formula.`},
   {h:`Reporting status people can act on`,
    body:[`Status reports exist so someone can make a decision. A good one shows performance against the baseline, the trend, the forecast, the top risks and issues, and what you need from the reader. Variance thresholds, set in the plan, decide when a variance needs action or escalation, so nobody argues about whether 4 percent is a problem.`,
     `Agile teams make the same information visible with burndown and burnup charts, velocity trends, and cumulative flow diagrams on a big wall or dashboard. These are called information radiators. The point is the same: anyone can see where the work stands without asking.`,`Tailor the delivery, not the facts. A board wants trends and forecasts in five minutes. A customer CIO wants to know what affects his hospitals and when. The team wants to know what's blocked today. One source of truth, cut three ways, keeps every audience consistent. When the news is bad, say it early, say what caused it, and say what you're doing about it. Stakeholders forgive problems far more easily than they forgive surprises.`],
    terms:[[`Variance threshold`,`An agreed limit that triggers action when exceeded.`],[`Burnup chart`,`Shows completed work rising toward a total scope line.`],[`Information radiator`,`A highly visible display of project status.`]],
    exam:`When a stakeholder wants good news shaded, the exam's answer is always accurate reporting with a plan. Honesty is a PMI Code of Ethics requirement, not a style choice.`}
  ],
  video:[`7DLyZjsrG14`,`Earned Value Analysis Calculations Tutorial`,`Edward Shehab`,`16:47`]
 },
 scenes:[
  {id:`f5s1`, domain:`Process`, task:`R6`, title:`One line from sales`,
   text:(s,all,G)=>[`The budget is a single number, $2,040,000, with no breakdown. Finance can tell Sam what departments spent, not what Cascade cost. ${G.nocharter?`And because there was never a charter, nobody wrote down who actually owns this budget.`:`The charter Elena signed names Sam as the budget owner, which means this is his problem now.`}`,`The board meets Tuesday.`],
   opts:[
    {t:`Build the baseline bottom up from the WBS, then add the contingency reserve.`,s:3,best:true,d:{trust:2,conf:3,health:6},
     after:`Sam spends Saturday with the leads. Each work package gets an estimate. The bottom up total comes to $1,880,000 plus $160,000 of contingency for the risks in the register. It matches the sales number almost exactly, which is a relief and a mystery.`,
     why:`A cost baseline is built from the work: estimate each work package, roll them up, add contingency for identified risks. That gives you something to measure against.`},
    {t:`Use the sales number as the baseline, since that's what the customer signed.`,s:1,d:{trust:0,conf:0,health:-2},
     after:`It's a number. Nobody can tell Sam what it's made of or which part of it is already spent.`,
     why:`The contract price isn't a cost baseline. You can't measure performance against a number you can't break down.`},
    {t:`Ask finance to split the department spending across projects by headcount.`,s:0,d:{trust:0,conf:0,health:-3},
     after:`Finance produces a split. It says Cascade cost the marketing team forty thousand dollars.`,
     why:`Allocating costs by formula after the fact isn't a project budget. Tie costs to the work in the WBS.`},
    {t:`Have each lead give a gut estimate of what their team has left to spend.`,s:0,d:{trust:1,conf:0,health:-2},
     after:`The gut estimates add up to more than the whole budget. Nobody can say why.`,
     why:`Estimates need a basis: the work packages, rates, and assumptions. Gut feel isn't a baseline.`}
   ]},
  {id:`f5s2`, domain:`Process`, task:`R6`, title:`Whose money`,
   text:(s,all,G)=>[`The burn-in cost Halcyon $22,000 in overtime and the weekend crew. Lena wants to charge it to management reserve. <span class="said" data-who="Lena">"That's what reserve is for,"</span> she says.`,`Hardware failure was row four in the risk register before the cluster ever failed.`],
   opts:[
    {t:`Charge it to management reserve, since the failure caught everyone off guard.`,s:0,d:{trust:0,conf:-2,health:-1},
     after:`Elena asks why an identified risk is drawing on her reserve. Sam doesn't have a good answer.`,
     why:`Management reserve is for unknown unknowns, and it takes sponsor approval. This risk was identified, so it draws on contingency.`},
    {t:`Draw it from contingency reserve, since it was an identified risk.`,s:3,best:true,d:{trust:1,conf:3,health:3},
     after:`Contingency drops from $160,000 to $138,000. Sam logs the draw against the risk. It takes ten minutes and nobody has to ask Elena for anything.`,
     why:`Contingency reserve covers known risks and is in the cost baseline under the project manager's control. Use it, and record what it was used for.`},
    {t:`Ask Elena for a budget increase to cover the overtime and weekend crew.`,s:1,d:{trust:0,conf:-1,health:1},
     after:`Elena asks what the contingency reserve is for. Fair question.`,
     why:`You don't need to raise the budget for a risk you already planned money for. Use contingency first.`},
    {t:`Absorb it quietly in other work packages so the totals don't change.`,s:0,d:{trust:0,conf:-3,health:-2},
     after:`Two work packages now look over budget for reasons nobody can trace.`,
     why:`Hiding costs in other buckets corrupts your data and is a transparency problem. Record costs where they belong.`}
   ]},
  {id:`f5s3`, domain:`Process`, task:`R9`, title:`Ninety percent done`,
   text:(s,all,G)=>[`Sam asks each lead how far along they are. The integration team says ninety percent. The data team says eighty five. The infrastructure team says ninety, though the cluster passed burn-in four days ago.`,`Priya, quietly, at his desk afterward: <span class="said" data-who="Priya">"We've been ninety percent done for three weeks."</span>`],
   opts:[
    {t:`Average the leads' percentages and report that as overall progress.`,s:0,d:{trust:0,conf:-1,health:-3},
     after:`The average is eighty seven percent. The project is nowhere near eighty seven percent done.`,
     why:`Averaging opinions produces a precise looking guess. Use objective measures of finished work.`},
    {t:`Ask each lead for a more careful estimate before Tuesday's meeting.`,s:1,d:{trust:0,conf:0,health:-1},
     after:`The careful estimates are lower and still subjective.`,
     why:`Better guesses are still guesses. Change how progress is measured, not how hard people guess.`},
    {t:`Credit only finished work: done packages and done stories.`,s:3,best:true,d:{trust:2,conf:3,health:6},
     after:`Sam switches to the 0/100 rule for infrastructure work packages and completed story points for the software. Earned value drops to a number nobody likes and everybody believes.`,
     why:`Earned value needs objective rules. Crediting only finished work, or completed stories that meet the definition of done, removes the ninety percent illusion.`},
    {t:`Have Priya check each team's claims and report what she finds.`,s:0,d:{trust:-4,conf:0,health:0},
     after:`Priya becomes the progress police. Two leads stop talking to her.`,
     why:`Making one engineer audit her peers damages trust and doesn't fix the measurement method.`}
   ]},
  {id:`f5s4`, domain:`Process`, task:`R9`, title:`Reading the indexes`,
   text:(s,all,G)=>[`With honest measurement, the numbers come out clean. By the end of week six, the plan said $1,000,000 of work would be done. The work actually finished was budgeted at $850,000. Halcyon has spent $1,000,000 to get it.`,`Elena wants one sentence she can say to the board.`],
   opts:[
    {t:`On budget, since spending matches what we planned to spend by now.`,s:0,d:{trust:0,conf:-4,health:-2},
     after:`Douglas Reyes, the audit committee chair, will take that sentence apart in about thirty seconds.`,
     why:`Comparing actual cost to planned value says nothing about cost performance. Compare actual cost to earned value.`},
    {t:`Behind schedule and over budget; find the work packages driving it.`,s:3,best:true,d:{trust:1,conf:4,health:4},
     after:`SPI and CPI are both 0.85. Sam traces most of it to the burn-in and to integration work that started late. Now he can say what's wrong and where.`,
     why:`SPI = EV / PV = 0.85 and CPI = EV / AC = 0.85. Both under 1. The next step is to find the cause in the work packages, not just report the ratio.`},
    {t:`Behind schedule but on budget, since we've only spent what was planned.`,s:1,d:{trust:0,conf:-1,health:0},
     after:`Half right. The schedule read is correct. The cost read will embarrass Elena if a board member does the math.`,
     why:`Schedule is right: EV is below PV. Cost is wrong: EV is below AC, so you're getting less work per dollar than planned.`},
    {t:`Fifteen percent over budget, so the team needs to work faster now.`,s:0,d:{trust:-3,conf:0,health:-1},
     after:`The team hears "work faster." They already were.`,
     why:`Reporting a number and demanding speed skips the analysis. Find the cause first, then decide the response.`}
   ]},
  {id:`f5s5`, domain:`Process`, task:`R6`, title:`Sprints cost money too`,
   text:(s,all,G)=>[`The software teams run two week sprints with a fixed team. Lena says earned value doesn't fit agile. <span class="said" data-who="Lena">"We deliver value every sprint. Isn't that the measure?"</span>`,`The board still needs to know whether the money will last.`],
   opts:[
    {t:`Exempt the software teams from cost tracking, since they're agile.`,s:0,d:{trust:1,conf:-3,health:-3},
     after:`Half the budget becomes invisible. The board notices.`,
     why:`Agile teams still spend money. Fixed teams make cost predictable per sprint, which is easy to track.`},
    {t:`Track cost per sprint against points done and the release burnup.`,s:3,best:true,d:{trust:2,conf:3,health:4},
     after:`A sprint costs about $68,000. The burnup shows how much of the release is done. Divide one by the other and the board has a cost per point and a forecast. Lena admits it's not as painful as she feared.`,
     why:`Agile cost tracking uses team cost per iteration and completed work against the release scope. It's earned value in agile clothing.`},
    {t:`Convert every user story into a work package with its own budget.`,s:1,d:{trust:-2,conf:1,health:0},
     after:`It works, technically, and adds four hours of paperwork per sprint that the team resents.`,
     why:`You can force predictive tracking onto agile work, but tailoring means using measures that fit the approach.`},
    {t:`Report only velocity, since it shows whether delivery is on track.`,s:0,d:{trust:0,conf:-1,health:-1},
     after:`Velocity tells the board how fast the team moves. It doesn't tell them what it costs.`,
     why:`Velocity is a planning tool for the team, not a cost measure. Pair it with cost per sprint.`}
   ]},
  {id:`f5s6`, domain:`Process`, task:`R9`, title:`What will it cost`,
   text:(s,all,G)=>[`Elena asks the question every sponsor asks. <span class="said" data-who="Elena">"So what will the whole thing cost?"</span>`,`Sam knows CPI is 0.85. He also knows most of the overrun came from the burn-in, which shouldn't happen twice.`],
   opts:[
    {t:`Give one number, $2,400,000, using BAC divided by CPI.`,s:1,d:{trust:0,conf:1,health:1},
     after:`It's a defensible number. It also assumes the burn-in will keep happening, which Sam doesn't believe.`,
     why:`BAC / CPI fits when current performance will continue. Giving only one number hides what you believe about the cause.`},
    {t:`Give a range, with the assumptions behind each end.`,s:3,best:true,d:{trust:1,conf:5,health:3},
     after:`Sam shows two forecasts: $2,190,000 if the burn-in was a one time hit, $2,400,000 if this efficiency continues. He explains what would move them. Elena likes it better than she expected to.`,
     why:`Forecasting means choosing the right EAC for what you believe, and being clear about assumptions. A range with reasons is more honest and more useful than one number.`},
    {t:`Say it will still come in at the original $2,040,000 budget.`,s:0,d:{trust:0,conf:-5,health:-2},
     after:`Elena repeats it to the board. Three weeks later she has to un-repeat it.`,
     why:`With a CPI of 0.85, staying on budget would take efficiency the team hasn't shown. Don't forecast what you hope.`},
    {t:`Say it's too early to forecast until the next phase completes.`,s:0,d:{trust:0,conf:-3,health:0},
     after:`The board hears "we don't know." That's worse than a range.`,
     why:`You have enough data to forecast with stated uncertainty. Waiting leaves the sponsor without what she needs to decide.`}
   ]},
  {id:`f5s7`, domain:`People`, task:`P6`, title:`Grant's advice`,
   text:(s,all,G)=>[`Monday night Grant calls. He's heard about the numbers. <span class="said" data-who="Grant">"Sam, I've been in a lot of board meetings. Don't lead with point eight five. Lead with the recovery. Round up where you can. Boards punish bad news."</span>`,`He isn't wrong about boards. He might be wrong about everything else.`],
   opts:[
    {t:`Present the honest numbers, the causes, and the recovery plan together.`,s:3,best:true,d:{trust:1,conf:5,health:2},
     after:`Grant sighs. <span class="said" data-who="Grant">"Your funeral."</span> Then, after a pause: <span class="said" data-who="Grant">"Send me the deck. I'll tell you which questions they'll ask."</span>`,
     why:`Honesty is a PMI Code of Ethics standard. Present accurate data with context and a plan. It manages expectations instead of setting up a later surprise.`},
    {t:`Show only the one time forecast, since Sam believes it's the likelier one.`,s:1,d:{trust:0,conf:0,health:0},
     after:`It's honest, mostly. If performance doesn't recover, the board will wonder why they never saw the other number.`,
     why:`Picking only the favorable forecast isn't lying, but it isn't complete. Show the range and your reasoning.`},
    {t:`Round the indexes up to 0.9 and lead with the recovery plan, as Grant says.`,s:0,flag:`hidnumbers`,d:{trust:-2,conf:3,health:-2},
     after:`The meeting goes smoothly. Douglas Reyes writes something in his notebook and underlines it.`,
     why:`Rounding bad numbers to look better is misrepresenting data. It may buy a calm meeting and costs your credibility later, when it matters most.`},
    {t:`Skip the earned value slides and present only milestones and dates.`,s:0,d:{trust:0,conf:-2,health:-1},
     after:`The board asks about money. Sam has to pull the spreadsheet up live.`,
     why:`Leaving out the cost picture doesn't hide it. It just means it comes out unprepared.`}
   ]},
  {id:`f5s8`, domain:`Process`, task:`R9`, title:`The efficiency ask`,
   text:(s,all,G)=>[`Elena's preference is clear: finish at the original budget. Sam runs the to complete performance index. To hit $2,040,000, the team would have to perform at 1.14 for the rest of the project. They've been running at 0.85.`,`Elena asks if that's doable.`],
   opts:[
    {t:`Say it's unlikely, and lay out a revised target or the reserve to cover it.`,s:3,best:true,d:{trust:2,conf:4,health:4},
     after:`Elena is quiet. Then: <span class="said" data-who="Elena">"What's realistic?"</span> They work through it together. That's the meeting Sam wanted.`,
     why:`A TCPI of 1.14 against a CPI of 0.85 means asking for a jump in efficiency nobody has shown. Say so, and bring options: a revised EAC through change control or management reserve.`},
    {t:`Say yes, and ask the team to find savings to close the gap.`,s:0,d:{trust:-4,conf:-2,health:-3},
     after:`The team cuts testing time to find savings. Quality starts to slip.`,
     why:`Committing to an efficiency the data doesn't support pushes the problem onto the team, where it usually turns into quality problems.`},
    {t:`Say it depends on the team, and ask Lena to commit to the higher pace.`,s:1,d:{trust:-1,conf:-1,health:0},
     after:`Lena commits, because Elena is in the room. Nobody believes it.`,
     why:`Getting a commitment under pressure isn't the same as a realistic plan. Use the data to have the real conversation.`},
    {t:`Avoid a yes or no and say the team will do its best to hit it.`,s:0,d:{trust:0,conf:-3,health:-1},
     after:`Elena hears yes. Sam meant maybe.`,
     why:`Vague answers to a sponsor's direct question get heard as commitments. Be clear about what the numbers say.`}
   ]},
  {id:`f5s9`, domain:`Business Environment`, task:`B3`, title:`A new baseline`,
   text:(s,all,G)=>[`Elena agrees to a revised cost target of $2,190,000, with $150,000 from management reserve. Lena asks if Sam can just update the spreadsheet tonight.`,`The cost baseline is signed. It's what everyone measures against.`],
   opts:[
    {t:`Update the spreadsheet tonight, since Elena already said yes in the room.`,s:1,d:{trust:1,conf:0,health:0},
     after:`The number changes. There's no record of why, when, or who approved it, which the auditors will notice.`,
     why:`A verbal yes is a start. Baseline changes go through change control with a documented, approved change request.`},
    {t:`Submit a change request with the analysis and update it once approved.`,s:3,best:true,d:{trust:1,conf:3,health:4},
     after:`The change request takes an hour. Elena signs it the next morning. The new baseline has a paper trail that will survive any audit.`,
     why:`Baselines change only through integrated change control. Document the reason, the impact, and the approval.`},
    {t:`Keep the old baseline and report against both numbers from now on.`,s:0,d:{trust:0,conf:-2,health:-2},
     after:`Every report now has two sets of variances. Nobody knows which one matters.`,
     why:`Two baselines means no baseline. Make the change formally and measure against one.`},
    {t:`Wait until the end of the phase and rebaseline everything at once.`,s:0,d:{trust:0,conf:-1,health:-2},
     after:`For six weeks every variance report shows a problem that's already been decided.`,
     why:`Once a change is approved, update the baseline so performance reports stay meaningful.`}
   ]},
  {id:`f5s10`, domain:`People`, task:`P4`, title:`Douglas Reyes`,
   text:(s,all,G)=>[`Tuesday. The boardroom on the top floor has a view of the mountains nobody looks at. Douglas Reyes, the audit committee chair, ran finance at a hospital system for twenty years. He waits until Sam finishes, then asks the only question that matters.`,`<span class="said" data-who="Douglas">"Why should we believe this forecast when we didn't believe the last one?"</span>`],
   opts:[
    {t:`Say the new numbers come from a better process and ask for his trust.`,s:1,d:{trust:0,conf:1,health:0},
     after:`Reyes nods politely. He wanted to see the process, not hear about it.`,
     why:`Asking for trust is weaker than showing your basis. Engage skeptical stakeholders with evidence.`},
    {t:`Show the method, the assumptions, and what would change the forecast.`,s:3,best:true,d:{trust:1,conf:6,health:1},
     after:`Sam walks through the 0/100 rule, the two EACs, and the three triggers that would move them. Reyes asks two follow-ups and then says, <span class="said" data-who="Douglas">"Send this to me every month."</span>`,
     why:`Credibility comes from transparency about method and assumptions. Telling a stakeholder what would change your answer shows you understand it.`},
    {t:`Point out that the last forecast came from sales, not delivery.`,s:0,d:{trust:0,conf:-3,health:0},
     after:`Grant, at the end of the table, stops smiling.`,
     why:`Blaming another function in front of the board damages relationships you need and doesn't answer the question.`},
    {t:`Offer to come back next month with more data before he decides.`,s:0,d:{trust:0,conf:-2,health:0},
     after:`Reyes wanted to decide today. Now he decides without Sam's input.`,
     why:`You have the data now. Present it with its uncertainty instead of deferring.`}
   ]},
  {id:`f5s11`, domain:`People`, task:`P3`, title:`Theo`,
   text:(s,all,G)=>[`On Wednesday Theo misses standup. Thursday he snaps at Priya in front of the Kraków team over a deploy script, then apologizes in a message nobody else sees.`,(G.blamedtheo?`Since the burn-in standup, Theo hasn't said more than a sentence to Sam at a time.`:`Theo has been carrying more than anyone since the burn-in, and it shows.`)],
   opts:[
    {t:`Remind Theo in standup that the team needs respectful communication.`,s:0,d:{trust:-5,conf:0,health:-1},
     after:`Theo nods. He doesn't come to standup on Friday either.`,
     why:`A public correction of someone who's struggling makes things worse. Start with a private conversation.`},
    {t:`Ask Priya to work with someone else on deploys for a while.`,s:1,d:{trust:-1,conf:0,health:-1},
     after:`It protects Priya. It also cuts the knowledge transfer the risk register depends on.`,
     why:`Separating people treats the symptom. The cause is something going on with Theo, and that needs a conversation.`},
    {t:`Take Theo for coffee and ask, privately, how he's actually doing.`,s:3,best:true,d:{trust:5,conf:0,health:2},
     after:`It takes a while. Then Theo says he hasn't taken a day off since April, his partner is tired of it, and he's been talking to another company. He doesn't say yes. He doesn't say no.`,
     why:`Leading the team includes noticing when someone is struggling and talking privately, with curiosity before judgment. Emotional intelligence starts with listening.`},
    {t:`Send Theo a note about the employee assistance program and leave it there.`,s:0,d:{trust:-1,conf:0,health:0},
     after:`Theo reads it as HR handling him.`,
     why:`Resources are good to offer, but not as a substitute for a real conversation from his leader.`}
   ]},
  {id:`f5s12`, domain:`Process`, task:`R9`, title:`Every Friday`,
   text:(s,all,G)=>[`The board wants monthly numbers. Ochoa gets a weekly page. The team wants to know where things stand without asking Sam. Lena asks what the reporting is going to look like from now on.`,`Sam doesn't want to spend every Friday building slides.`],
   opts:[
    {t:`One live dashboard: EV trends, forecast, risks, and the burnup.`,s:3,best:true,d:{trust:3,conf:4,health:3},
     after:`Priya builds it in a day. It goes on the big screen by the kitchen. People start checking it on their way to coffee.`,
     why:`Consistent metrics shown the same way every time, visible to everyone, make status a fact instead of a meeting. That's an information radiator.`},
    {t:`Write a detailed report for each audience every Friday afternoon.`,s:1,d:{trust:0,conf:2,health:-1},
     after:`The reports are thorough. They also eat Sam's Friday, every Friday.`,
     why:`Tailoring messages to each audience is good. Building each one from scratch isn't sustainable. Use one source of truth, then tailor.`},
    {t:`Report status only when a variance threshold is crossed.`,s:0,d:{trust:0,conf:-2,health:-1},
     after:`Ochoa goes three weeks without hearing anything and gets nervous.`,
     why:`Thresholds decide when to act, not when to communicate. Stakeholders still need regular updates.`},
    {t:`Let each team lead report their own status to whoever asks.`,s:0,d:{trust:1,conf:-2,health:-2},
     after:`Three versions of the truth start circulating.`,
     why:`Integrated status reporting is the project manager's job. Fragmented reporting creates conflicting stories.`}
   ]}
 ],
 drills:[
  {after:`f5s4`, title:`Variances and indexes`,
   setup:[`End of week six on the Cascade project.`,`Planned value: $1,000,000. Earned value: $850,000. Actual cost: $1,000,000.`],
   fields:[{label:`Schedule variance, SV ($)`,answer:-150000,tol:1},{label:`Cost variance, CV ($)`,answer:-150000,tol:1},{label:`SPI (two decimals)`,answer:0.85,tol:0.005},{label:`CPI (two decimals)`,answer:0.85,tol:0.005}],
   solution:[`SV = EV minus PV = 850,000 minus 1,000,000 = negative $150,000. Behind schedule.`,`CV = EV minus AC = 850,000 minus 1,000,000 = negative $150,000. Over budget.`,`SPI = EV / PV = 850,000 / 1,000,000 = 0.85. CPI = EV / AC = 850,000 / 1,000,000 = 0.85. Both under 1, so for every dollar spent the project earns 85 cents of planned work, and it's progressing at 85 percent of the planned rate.`]},
  {after:`f5s6`, title:`Forecasting at completion`,
   setup:[`BAC is $2,040,000. EV is $850,000. AC is $1,000,000. CPI is 0.85.`,`Calculate the forecast two ways: assuming current cost performance continues, and assuming the overrun was a one time event.`],
   fields:[{label:`EAC if CPI continues ($)`,answer:2400000,tol:1},{label:`ETC for that EAC ($)`,answer:1400000,tol:1},{label:`VAC for that EAC ($)`,answer:-360000,tol:1},{label:`EAC if the overrun was one time ($)`,answer:2190000,tol:1}],
   solution:[`Typical: EAC = BAC / CPI = 2,040,000 / 0.85 = $2,400,000. ETC = EAC minus AC = 2,400,000 minus 1,000,000 = $1,400,000. VAC = BAC minus EAC = 2,040,000 minus 2,400,000 = negative $360,000.`,`Atypical: EAC = AC + (BAC minus EV) = 1,000,000 + (2,040,000 minus 850,000) = 1,000,000 + 1,190,000 = $2,190,000.`,`The gap between the two, $210,000, is the value of being right about whether the burn-in was a one time event.`]},
  {after:`f5s8`, title:`To complete performance index`,
   setup:[`Elena wants to know what efficiency the team would need on the remaining work.`,`BAC is $2,040,000. EV is $850,000. AC is $1,000,000. The revised target EAC is $2,190,000.`],
   fields:[{label:`TCPI to finish at BAC (two decimals)`,answer:1.14,tol:0.005},{label:`TCPI to finish at the revised $2,190,000 (two decimals)`,answer:1.00,tol:0.005}],
   solution:[`TCPI to BAC = (BAC minus EV) / (BAC minus AC) = 1,190,000 / 1,040,000 = 1.144, about 1.14. The team would need to be 14 percent more efficient than planned on every remaining dollar, after running at 0.85.`,`TCPI to EAC = (BAC minus EV) / (EAC minus AC) = 1,190,000 / (2,190,000 minus 1,000,000) = 1,190,000 / 1,190,000 = 1.00. The revised target only asks the team to perform as planned from here, which is a realistic ask.`]}
 ],
 quiz:[
  {q:`A project has a PV of $400,000, an EV of $360,000, and an AC of $300,000. What is the project's status?`,opts:[`Behind schedule and over budget`,`Ahead of schedule and under budget`,`Behind schedule and under budget`,`Ahead of schedule and over budget`],a:2,why:`SPI = 360/400 = 0.90, behind schedule. CPI = 360/300 = 1.20, under budget.`,task:`R9`,domain:`Process`},
  {q:`A project's BAC is $500,000 and CPI is 0.80. Current performance is expected to continue. What is the EAC?`,opts:[`$625,000`,`$400,000`,`$580,000`,`$600,000`],a:0,why:`EAC = BAC / CPI = 500,000 / 0.80 = $625,000.`,task:`R6`,domain:`Process`},
  {q:`A cost overrun was caused by a one time equipment failure that won't recur. Which EAC formula fits best?`,opts:[`EAC = BAC divided by CPI`,`EAC = AC plus a new bottom up ETC`,`EAC = AC divided by SPI times CPI`,`EAC = AC plus (BAC minus EV)`],a:3,why:`For an atypical, one time variance, the remaining work is expected to go to plan: EAC = AC + (BAC minus EV).`,task:`R6`,domain:`Process`},
  {q:`An identified risk occurs and costs $15,000 to address. Where should the money come from?`,opts:[`Management reserve, with the sponsor's approval`,`Contingency reserve within the cost baseline`,`A new change request to increase the budget`,`The organization's general operating budget`],a:1,why:`Known risks are funded from contingency reserve, which sits in the cost baseline under the PM's control.`,task:`R6`,domain:`Process`},
  {q:`The TCPI to meet BAC is 1.25 and the current CPI is 0.90. What does this tell the project manager?`,opts:[`The project is likely to finish under its budget`,`Hitting BAC requires efficiency the team hasn't shown`,`The schedule is behind but cost is on track overall`,`The team should increase its velocity by 25 percent`],a:1,why:`A TCPI well above the current CPI means meeting BAC needs a large efficiency gain. That calls for a realistic forecast and options, not pressure.`,task:`R9`,domain:`Process`},
  {q:`Team leads report their work as 90 percent complete for several weeks. What should the project manager do?`,opts:[`Use objective rules, such as crediting only finished work`,`Ask leads for more careful percentage estimates weekly`,`Average the leads' estimates for the status report now`,`Escalate the stalled work to the sponsor as an issue`],a:0,why:`Subjective percentages inflate progress. Rules like 0/100 or completed stories give objective earned value.`,task:`R9`,domain:`Process`},
  {q:`A sponsor asks the project manager to round performance numbers up before a board meeting. What should the project manager do?`,opts:[`Round the numbers, since the sponsor owns the board relationship`,`Present only milestone dates and leave out the cost metrics`,`Present accurate numbers with context and a recovery plan`,`Ask the PMO to present the numbers on the team's behalf`],a:2,why:`The PMI Code of Ethics requires honesty. Present accurate information with context and a plan.`,task:`P6`,domain:`People`},
  {q:`What is the difference between the cost baseline and the project budget?`,opts:[`The budget includes contingency; the baseline does not`,`They are the same figure, approved at different times`,`The baseline includes management reserve and contingency`,`The budget adds management reserve to the cost baseline`],a:3,why:`Cost baseline = cost estimates plus contingency reserve. Project budget = cost baseline plus management reserve.`,task:`R6`,domain:`Process`},
  {q:`An agile team of fixed size costs $60,000 per sprint and completes 30 points per sprint. 180 points remain. What is the estimated remaining cost?`,opts:[`$300,000`,`$360,000`,`$180,000`,`$420,000`],a:1,why:`180 points / 30 per sprint = 6 sprints. 6 times $60,000 = $360,000.`,task:`R6`,domain:`Process`},
  {q:`The sponsor approves a revised budget in a meeting. What should the project manager do next?`,opts:[`Update the cost baseline right away to match the decision`,`Report against both the old and new baselines going forward`,`Wait until the phase ends to update all baselines at once`,`Document an approved change request, then update the baseline`],a:3,why:`Baselines change only through integrated change control with a documented, approved change request.`,task:`B3`,domain:`Business Environment`},
  {q:`A skeptical board member doubts the project's forecast. What is the best way to engage them?`,opts:[`Show the method, assumptions, and what would change the forecast`,`Explain that the earlier forecast came from a different team`,`Offer to return next month with more data before deciding`,`Ask the sponsor to vouch for the new forecast's accuracy`],a:0,why:`Transparency about method and assumptions builds credibility with skeptical stakeholders.`,task:`P4`,domain:`People`},
  {q:`Which visual best shows completed work rising toward total scope, including scope that has been added?`,opts:[`Burndown chart`,`Burnup chart`,`Gantt chart`,`Pareto chart`],a:1,why:`A burnup chart shows completed work and the total scope line separately, so added scope is visible.`,task:`R9`,domain:`Process`},
  {q:`A team member who is usually reliable starts missing meetings and snapping at colleagues. What should the project manager do first?`,opts:[`Address the behavior with the whole team at the next standup`,`Reassign the team member's critical work to someone else`,`Refer the team member to human resources for a review now`,`Talk with the team member privately to understand what's going on`],a:3,why:`Start with a private, empathetic conversation. Understanding the cause comes before any corrective action.`,task:`P3`,domain:`People`},
  {q:`Optimistic, most likely, and pessimistic cost estimates are $40,000, $55,000, and $82,000. What is the PERT estimate?`,opts:[`$57,000`,`$59,000`,`$55,000`,`$56,500`],a:0,why:`(O + 4M + P) / 6 = (40,000 + 220,000 + 82,000) / 6 = 342,000 / 6 = $57,000.`,task:`R6`,domain:`Process`},
  {q:`What is the main purpose of variance thresholds in the project management plan?`,opts:[`To set the maximum budget the sponsor will ever approve`,`To decide in advance when a variance needs action`,`To limit how often stakeholders receive status reports`,`To calculate the contingency reserve for each risk`],a:1,why:`Thresholds define when a variance is large enough to require action or escalation, removing debate in the moment.`,task:`R9`,domain:`Process`}
 ],
 closing:(s,all,G)=>[
  `The board approved the revised target with a vote of six to one. Douglas Reyes stopped Sam at the elevator. <span class="said" data-who="Douglas">"Monthly,"</span> he said. <span class="said" data-who="Douglas">"And Sam? ${(s.flags&&s.flags.hidnumbers)||G.hidnumbers?`Next time, don't round. I can do arithmetic.`:`That's the first forecast from this company I've been able to check.`}"</span>`,
  `Elena didn't say much on the way down. In the lobby she stopped. <span class="said" data-who="Elena">"I hated every slide,"</span> she said. <span class="said" data-who="Elena">"I believed every one."</span>`,
  `Sam got home before seven for the first time in two weeks. Dana had made the enchiladas her grandmother taught her, the ones she only made when something was worth noticing. He told her about Reyes. She told him about a junior who had finally balanced a redox equation on her own and cried a little from relief. They both agreed the junior had the better week.`,
  `Friday, 5:40. Most of the office had gone. Theo knocked on the door frame, which he never did.`,
  `He had a letter. On paper. Nobody at Halcyon printed anything, so Sam knew before he read a word.`,
  `<span class="said" data-who="Theo">"I took the other job,"</span> Theo said. <span class="said" data-who="Theo">"Three weeks. Sorry. It isn't you."</span>`,
  `Sam read it twice anyway. Old habit. <span class="said" data-who="Sam">"Is it the work?"</span>`,
  `Theo did a half laugh, mostly air. <span class="said" data-who="Theo">"It's that nobody else can do the work. I can't get sick. I can't go to my sister's wedding without my laptop. I'm tired, man."</span> He nodded at the dashboard glowing over the empty kitchen. <span class="said" data-who="Theo">"Your row one. You called it."</span>`,
  `Sam didn't feel like he'd called anything. He felt like he'd watched it.`,
  `Three weeks. He grabbed a pen.`
 ],
 episode:{src:`audio/full-ch05.mp3`, len:`about 35 minutes`},
 next:`Storming`
});
