// Full Course, Chapter 6. Storming. See full/BIBLE.md.
(window.HALCYON_FULL=window.HALCYON_FULL||[]).push({
 num:6, part:`Part One: The Cascade Launch`, title:`Storming`, weeks:`Weeks 6 to 8`,
 tasks:[`P2`,`P7`,`P3`,`B4`],
 cast:[[`Devin Ruiz`,`Engineer. Coasting since his last manager left. More capable than he lets on.`]],
 opening:[
  `Sam told Lena first, Monday at 7:30, before the office filled up. She took it the way she took most bad news, quietly, looking at a spot on the table. <span class="said">"I knew,"</span> she said finally. <span class="said">"I didn't want to know, so I didn't ask."</span>`,
  `Elena took it the other way. <span class="said">"Counter him,"</span> she said. <span class="said">"Whatever they're paying, plus twenty."</span>`,
  `<span class="said">"It isn't money,"</span> Sam said. <span class="said">"It's that he's the only one who can do the job. If we pay him more to keep being the only one, we fix nothing."</span>`,
  `Elena looked at him for a long second. <span class="said">"Fine. Then don't lose what's in his head."</span>`,
  `Back at his desk Sam thought about Ray Mendez. On the flight line in Wisconsin, Ray had a rule nobody liked: before you could sign off a task, you had to teach it back to the youngest airman on the crew. It doubled the time of everything. It also meant that when Ray retired, the jets didn't notice.`,
  `Sam had fifteen working days. He wrote three names on his list. Theo. Priya. Tomasz.`,
  `Then, under them, a fourth he hadn't meant to write. Devin.`
 ],
 lesson:{
  title:`Conflict, teams, and knowledge`,
  sections:[
   {h:`Conflict is normal, and it can be useful`,
    body:[`Most project conflict comes from the same places: schedules, priorities, resources, technical opinions, and personalities. The exam doesn't treat conflict as a failure. It treats unmanaged conflict as one. Healthy disagreement about ideas makes plans better. Unhealthy conflict about people makes teams quiet.`,
     `There are five classic ways to handle it. Withdraw or avoid: step back or postpone. Smooth or accommodate: emphasize agreement and downplay the difference. Compromise or reconcile: each side gives something up. Force or direct: one view wins, usually through authority. Collaborate or problem solve: bring the perspectives together, work through the facts, and find a solution everyone can commit to.`,
     `Collaborating is usually the best answer when there's time and the relationship matters, because it addresses the cause and builds commitment. Forcing has its place in an emergency or a safety issue. Compromise often leaves both sides partly unhappy. Smoothing and withdrawing buy time, which is sometimes right, but they don't resolve anything. Address conflict privately, as early as possible, and focus on the issue, not the person.`],
    terms:[[`Collaborate / problem solve`,`Work through the facts together for a win win result.`],[`Compromise / reconcile`,`Each side gives up something. Lose lose, partly.`],[`Force / direct`,`One side wins by authority. Fast, but costs commitment.`],[`Smooth / accommodate`,`Emphasize agreement, play down differences.`],[`Withdraw / avoid`,`Retreat or postpone.`]],
    exam:`If the scenario has time and an ongoing relationship, collaborate. If it's an emergency with safety at stake, the PM may need to direct. Public conflict should move to a private conversation.`},
   {h:`How teams grow`,
    body:[`The Tuckman model describes five stages. Forming: polite, unsure, waiting for direction. Storming: friction as people push on roles and ways of working. Norming: agreements form and trust grows. Performing: the team works smoothly and needs little direction. Adjourning: the work ends and the team disbands. Teams can slide back when people leave or join.`,
     `The leader's job changes with the stage. In forming, provide direction and clarity. In storming, facilitate conflict instead of suppressing it, and help the team set or reset its working agreements. In norming, support and coach. In performing, delegate and remove impediments. A team charter, written by the team, captures values, ground rules, decision making, and how conflict will be handled.`],
    terms:[[`Team charter`,`The team's own agreements on values, ground rules, and decisions.`],[`Psychological safety`,`Belief that you can speak up without being punished or embarrassed.`],[`Servant leadership`,`Leading by removing obstacles and helping the team succeed.`]],
    exam:`A team arguing about how to work after a change in membership is storming. The best answer helps them revisit their working agreements together.`},
   {h:`Emotional intelligence and coaching`,
    body:[`Emotional intelligence has five parts in most PMP material: self awareness, self regulation, motivation, empathy, and social skills. The exam rewards the project manager who notices their own reaction, stays calm, tries to understand the other person, and repairs damage quickly when they get it wrong. An honest apology from a leader builds more trust than pretending nothing happened.`,
     `Coaching helps someone improve their own performance, usually by asking questions and setting goals together. Mentoring is longer term guidance from someone more experienced. For a struggling team member, the order is almost always the same: talk privately, understand the cause, agree on expectations and support, then follow up. Formal discipline comes after that, not before.`,`Motivation shows up on the exam too. Herzberg separates hygiene factors, like pay and working conditions, which cause dissatisfaction when they're missing, from motivators, like achievement, recognition, and growth, which actually drive effort. Pay someone more and the complaints stop; give them meaningful work and the effort starts. That's why a bored engineer often responds better to a hard, visible problem than to a raise. Recognition matters most when it's specific and timely, and public praise works best when it's earned and private correction comes first.`],
    terms:[[`Self regulation`,`Managing your own emotional reactions.`],[`Coaching`,`Helping someone build their own skills and solutions.`],[`Mentoring`,`Longer term guidance from someone more experienced.`]],
    exam:`When a team member underperforms, the first step is a private conversation to understand why. Replacing them or escalating to HR comes later, if at all.`},
   {h:`Keeping what people know`,
    body:[`Documents capture explicit knowledge. Tacit knowledge moves through practice: shadowing on live work, pairing every day, and having the successor do the job while the expert watches and corrects. A wiki full of runbooks still leaves a new engineer stuck on the first real incident if nobody has walked them through one. And capture lessons as they happen, in the lessons learned register, not in a meeting at the end when half of them are forgotten. That habit is where continuous improvement starts.`,
     `Explicit knowledge can be written down: procedures, configurations, decisions. Tacit knowledge lives in people's heads: judgment, instinct, the reason a strange workaround exists. Documents capture the first. The second moves through people, by pairing, shadowing, storytelling, walkthroughs of real incidents, and communities of practice.`,
     `Knowledge transfer is now its own task on the exam. Plan it early, not in someone's last week. Use a lessons learned register throughout the project, not only at the end. Make sure knowledge lands where it will be used, and verify it actually transferred by having the receiver do the work while the expert watches.`,`Succession is the same idea applied to roles. For every critical role, ask who could step in next month if the person left today. If the answer is nobody, that's a key person risk. Log it, give it an owner, and treat cross training as the response, long before anyone hands in a letter.`],
    terms:[[`Explicit knowledge`,`Knowledge that can be codified in words, numbers, or diagrams.`],[`Tacit knowledge`,`Personal know how and judgment that's hard to write down.`],[`Lessons learned register`,`A running record of lessons captured during the project.`]],
    exam:`If a key person is leaving, the best answer usually combines pairing or shadowing on real work with documentation, and verifies the transfer.`}
  ],
  video:[`wSwtbok3rv0`,`Conflict Management: Key Concepts in Project Management`,`David McLachlan`,`5:25`]
 },
 scenes:[
  {id:`f6s1`, domain:`People`, task:`P7`, title:`Fifteen days`,
   text:(s,all,G)=>[`Theo has fifteen working days left. Priya is the obvious successor and she knows it, which is making her quieter than usual. ${G.blamedtheo?`Theo is polite with Sam now, and careful. He hasn't forgotten the standup after the burn-in.`:`Theo seems lighter since he resigned, like a weight came off.`}`,`Sam needs a plan for getting what's in Theo's head into the team.`],
   opts:[
    {t:`Ask Theo to write full documentation of everything before he goes.`,s:1,d:{trust:0,conf:0,health:2},
     after:`Theo writes forty pages. They're accurate. Priya reads them twice and still can't answer the question Kraków asks her on Thursday.`,
     why:`Documentation captures explicit knowledge. Much of what Theo knows is tacit, and that moves through people working together.`},
    {t:`Pair Priya with Theo daily on real work, writing it up as they go.`,s:3,best:true,d:{trust:4,conf:1,health:5},
     after:`Every morning Priya drives and Theo watches. Every afternoon they write down what came up. By the second week Theo is mostly sitting on his hands.`,
     why:`Pairing on real work transfers tacit knowledge, and writing it down as you go captures the explicit part. Start early and do both.`},
    {t:`Hire a replacement now and have Theo train them during his final week.`,s:0,d:{trust:-2,conf:0,health:-3},
     after:`Hiring takes six weeks. The replacement arrives after Theo is gone.`,
     why:`A transfer plan that depends on someone who doesn't exist yet isn't a plan. Use the people you have.`},
    {t:`Offer Theo a bigger raise to stay, even though he's already decided.`,s:0,d:{trust:-1,conf:0,health:-1},
     after:`Theo says no, kindly. Two days of the fifteen are gone.`,
     why:`Retention is worth a conversation, but it doesn't address the real risk, which is that only one person knows the system.`}
   ]},
  {id:`f6s2`, domain:`People`, task:`P7`, title:`Why it's weird`,
   text:(s,all,G)=>[`Half of what makes the platform work is in comments like <span class="said">"don't touch this, ask Theo."</span> Priya finds a retry loop that waits exactly 47 seconds. Nobody knows why.`,`Theo knows why. Theo knows why about a hundred things like it.`],
   opts:[
    {t:`Ask Theo to list every odd workaround on a wiki page before he leaves.`,s:1,d:{trust:0,conf:0,health:2},
     after:`The list has sixty three items. Most of the reasons are one line long. The 47 seconds says "vendor quirk."`,
     why:`A list is better than nothing, but the why behind a workaround is the tacit part, and one line rarely carries it.`},
    {t:`Have Theo walk the team through real past incidents, and record it.`,s:3,best:true,d:{trust:3,conf:1,health:5},
     after:`Theo tells the story of the night the label vendor's API started throttling at 46 seconds. Kraków asks questions. Priya takes notes. The recording becomes the most watched video in the company wiki.`,
     why:`Storytelling and walkthroughs of real incidents are among the best ways to move tacit knowledge. Recording them makes the knowledge reusable.`},
    {t:`Clean up the workarounds before Theo leaves so nobody needs the history.`,s:0,d:{trust:0,conf:0,health:-4},
     after:`Priya removes the 47 second wait. The vendor API starts throttling the next day.`,
     why:`Changing code you don't understand to avoid learning its history creates new defects. Understand first.`},
    {t:`Leave it. Priya will figure out the workarounds as she hits them.`,s:0,d:{trust:-2,conf:0,health:-4},
     after:`She does figure them out, one production incident at a time.`,
     why:`Letting knowledge walk out the door and relearning it in production is the most expensive way to transfer it.`}
   ]},
  {id:`f6s3`, domain:`People`, task:`P2`, title:`Sprint planning`,
   text:(s,all,G)=>[`Sprint planning, twelve people in the room. Grant walks in mid meeting. Cascade's nursing director wants voice dictation in the first release. Grant has half promised it.`,`Lena says no, flatly, in front of everyone. Grant says engineering always says no. Lena says sales always says yes. The Kraków team is watching on the big screen. Devin is trying not to smile.`],
   opts:[
    {t:`Let them argue it out, since open conflict is healthy for the team.`,s:0,flag:`publicfight`,d:{trust:-6,conf:-1,health:-2},
     after:`It goes on for twenty minutes. Nobody else says a word. The sprint gets planned around a decision nobody made.`,
     why:`Healthy conflict is about ideas, in a safe setting. Two executives fighting in front of the team is the opposite. It teaches everyone else to stay quiet.`},
    {t:`Pause the meeting and meet with both of them privately after.`,s:3,best:true,d:{trust:5,conf:1,health:2},
     after:`<span class="said">"Let's take this offline,"</span> Sam says, more calmly than he feels. The room breathes out. Planning finishes on the work everyone agrees on.`,
     why:`Move a public conflict to a private setting quickly. It protects the people involved and the team, and gives you a real chance to resolve it.`},
    {t:`Back Lena, since the engineering estimate should decide what fits.`,s:0,d:{trust:0,conf:-3,health:0},
     after:`Lena wins the moment. Grant goes straight to Elena.`,
     why:`Picking a side in public is forcing. It may get the right answer, but it costs commitment and escalates the conflict.`},
    {t:`Suggest a middle ground: build half of the voice feature this release.`,s:1,d:{trust:0,conf:0,health:-2},
     after:`Both of them hate it, which feels fair, until engineering realizes half a voice feature is still most of the work.`,
     why:`Compromise ends the argument but often leaves a solution nobody wanted. Understand the real need first.`}
   ]},
  {id:`f6s4`, domain:`People`, task:`P2`, title:`Lena and Grant`,
   text:(s,all,G)=>[`Sam's office, door closed. Lena and Grant are both still angry, and both a little embarrassed about it.`,`Sam has twenty minutes and a feeling that the voice feature isn't really what they're fighting about.`],
   opts:[
    {t:`Agree on the goal first, then work through the data together.`,s:3,best:true,d:{trust:5,conf:3,health:4},
     after:`The goal turns out to be the same: Cascade's nurses spend too long on notes. Voice is one answer. Cascade's nursing director only asked for it because typing is slow on the unit tablets. A cheaper keyboard fix goes in this release. Voice goes to the backlog with a real estimate. Grant and Lena leave together.`,
     why:`Collaborating, or problem solving, starts from shared goals and facts and finds the underlying need. It's the mode the exam prefers when there's time and the relationship matters.`},
    {t:`Ask Elena to make the call, since they're both on her leadership team.`,s:1,d:{trust:0,conf:0,health:0},
     after:`Elena decides in five minutes. Neither of them is any closer to working well together.`,
     why:`Escalation is right when you can't resolve something. Try collaborating first; you'll often find a better answer than a ruling.`},
    {t:`Point out how much they actually agree on, and ask them to move on.`,s:0,d:{trust:0,conf:0,health:-1},
     after:`They nod. The same fight happens next sprint.`,
     why:`Smoothing lowers the temperature but leaves the cause in place.`},
    {t:`Give it a few days to cool down before bringing them back together.`,s:0,d:{trust:-1,conf:-1,health:-2},
     after:`A few days becomes two weeks. The backlog item sits in limbo.`,
     why:`Withdrawing can help when emotions are high, but leaving it unresolved lets the conflict grow.`}
   ]},
  {id:`f6s5`, domain:`People`, task:`P3`, title:`Devin`,
   text:(s,all,G)=>[`Devin has missed his sprint commitments three times running. Nobody says anything because nobody ever has. His last manager left in the spring and Devin quietly stopped trying.`,`He's also the only engineer who's ever made the integration tests run in under ten minutes.`],
   opts:[
    {t:`Talk with Devin privately about expectations, goals, and support.`,s:3,best:true,d:{trust:4,conf:0,health:4},
     after:`Devin is defensive for ten minutes and honest for twenty. He's bored. He's good at performance work and nobody has asked him to do any since spring. Sam gives him the slow test suite and a goal. Devin's next sprint is his best in a year.`,
     why:`Coaching starts with a private conversation to understand the cause, then clear expectations and support. Underperformance often has a reason you can fix.`},
    {t:`Pair Devin with Priya so her pace rubs off on him a little.`,s:1,d:{trust:-1,conf:0,health:1},
     after:`Priya, who has enough to carry already, now carries Devin too.`,
     why:`Pairing can help, but it puts your problem on someone else without understanding what's going on with Devin.`},
    {t:`Start a formal performance plan with HR to document the misses.`,s:0,d:{trust:-4,conf:0,health:-1},
     after:`Devin updates his resume that night.`,
     why:`Formal steps come after coaching has been tried, not before a single conversation.`},
    {t:`Raise the missed commitments at the retro so the team can address them.`,s:0,d:{trust:-5,conf:0,health:-1},
     after:`The retro becomes a trial. Devin stops talking in retros.`,
     why:`Individual performance is a private conversation. Retros are for how the team works, not for calling people out.`}
   ]},
  {id:`f6s6`, domain:`People`, task:`P3`, title:`The call`,
   text:(s,all,G)=>[`Thursday, 6 AM Denver time, mid afternoon in Kraków. A deploy from Tomasz's team broke staging an hour before a Cascade review. Sam, short on sleep, says on the call, in front of Tomasz's whole team, <span class="said">"Did anybody over there actually test this?"</span>`,`The line goes quiet. That night Dana finds him on the back step. <span class="said">"You've got the face,"</span> she says. <span class="said">"The one from the Guard, when somebody on your crew got hurt and you thought it was your fault."</span>`],
   opts:[
    {t:`Send Tomasz an email explaining the pressure Sam was under that day.`,s:1,d:{trust:1,conf:0,health:0},
     after:`Tomasz replies, <span class="said">"Understood."</span> It doesn't sound understood.`,
     why:`Explaining context helps, but it can read like an excuse. Own it directly first.`},
    {t:`Let it go. Tomasz is a professional, and it will blow over.`,s:0,d:{trust:-5,conf:0,health:-2},
     after:`It doesn't blow over. Kraków's commits get smaller and more cautious. Velocity drops.`,
     why:`Ignoring damage you caused tells the team it's acceptable. A leader repairs it.`},
    {t:`Call Tomasz, apologize plainly, then talk through what went wrong.`,s:3,best:true,d:{trust:6,conf:0,health:3},
     after:`<span class="said">"I was out of line,"</span> Sam says. <span class="said">"In front of your team. I'm sorry."</span> Silence, then Tomasz: <span class="said">"My team will hear this from me. Now. The deploy. We skipped a test because your environment was down. Shall we fix that together?"</span>`,
     why:`Self awareness and self regulation include repairing it when you lose your temper. A direct, specific apology rebuilds trust, and then you can solve the actual problem.`},
    {t:`Ask Lena to smooth things over with Tomasz on Sam's behalf.`,s:0,d:{trust:-3,conf:0,health:-1},
     after:`Lena does. Tomasz notes that Sam didn't.`,
     why:`An apology through a messenger isn't an apology. Repair it yourself.`}
   ]},
  {id:`f6s7`, domain:`Business Environment`, task:`B4`, title:`One approver`,
   text:(s,all,G)=>[`Every production deploy needs Theo's approval. Theo is spending his days teaching Priya. Kraków has six changes waiting in a queue.`,`Tomasz, newly polite: <span class="said">"We are not complaining. We are only noting the queue."</span>`],
   opts:[
    {t:`Ask Theo to approve deploys in a batch at the end of each day.`,s:1,d:{trust:0,conf:0,health:1},
     after:`The queue moves, slowly. Theo is now teaching all day and approving all evening.`,
     why:`Batching eases the symptom, but the impediment is that one person holds approval. Fix the constraint.`},
    {t:`Give Priya approval rights, with Theo checking her first few.`,s:3,best:true,d:{trust:4,conf:1,health:5},
     after:`Priya approves her first deploy with Theo reading over her shoulder. By Friday she's approving alone. The queue is empty.`,
     why:`Removing an impediment can mean redistributing authority. Doing it while the expert is still there to check the work is also knowledge transfer.`},
    {t:`Let Kraków deploy without approval until Theo leaves next month.`,s:0,d:{trust:1,conf:-2,health:-4},
     after:`One unapproved deploy breaks the Cascade test environment.`,
     why:`Removing a control to remove a blocker creates a different problem. Change who performs the control, not whether it happens.`},
    {t:`Pause Kraków's deploys until Priya is fully ready to take over.`,s:0,d:{trust:-3,conf:0,health:-3},
     after:`Kraków spends a week waiting. Tomasz notes it.`,
     why:`Blocking work to avoid the risk of a new approver makes the impediment worse.`}
   ]},
  {id:`f6s8`, domain:`People`, task:`P3`, title:`Code review wars`,
   text:(s,all,G)=>[`With Theo leaving and Devin waking up, standups get loud. Devin wants every change performance tested. Kraków thinks Denver reviews their code harder than its own. Priya wants one rule everyone follows.`,`Nobody is wrong. Everybody is annoyed.`],
   opts:[
    {t:`Set the review standard himself so everyone stops arguing about it.`,s:1,d:{trust:-1,conf:0,health:2},
     after:`The arguments stop. So does the team's interest in the rule.`,
     why:`Directing is sometimes needed, but a team in storming does better when it sets its own agreements.`},
    {t:`Facilitate a session where the team updates its working agreements.`,s:3,best:true,d:{trust:6,conf:0,health:4},
     after:`It takes ninety minutes. They agree on one review standard for both offices, a performance test only for changes that touch the hot path, and a rule that disagreements happen in the pull request, not in standup. Tomasz writes it up in better English than anyone in Denver.`,
     why:`This is the storming stage. The leader's job is to facilitate, not suppress, and help the team reset its working agreements together.`},
    {t:`Tell the team to work it out among themselves, outside of standups.`,s:0,d:{trust:-2,conf:0,health:-2},
     after:`They work it out by forming two camps.`,
     why:`Leaving a storming team alone without facilitation tends to harden the conflict.`},
    {t:`Split Denver and Kraków into separate teams with their own standards.`,s:0,d:{trust:-4,conf:0,health:-2},
     after:`Now there are two standards, and integration gets harder.`,
     why:`Splitting a team to avoid conflict creates silos and new integration problems.`}
   ]},
  {id:`f6s9`, domain:`People`, task:`P7`, title:`Theo's last week`,
   text:(s,all,G)=>[`Five days left. Priya has been driving for two weeks. The runbook has grown from four pages to thirty. The incident recordings have been watched by everyone, twice.`,`Sam needs to know whether the transfer actually worked, before Friday rather than after.`],
   opts:[
    {t:`Ask Priya directly whether she feels ready to take over from Theo.`,s:1,d:{trust:1,conf:0,health:0},
     after:`She says yes, because she's Priya. Her face says she isn't sure.`,
     why:`Confidence isn't verification. Test the transfer by having her do the work.`},
    {t:`Have Priya run a deploy and an incident drill as Theo watches.`,s:3,best:true,d:{trust:3,conf:1,health:5},
     after:`Priya runs both. She gets stuck once, on the 47 second retry, and finds the answer in the recording before Theo says a word. Theo grins for the first time in a month.`,
     why:`Verify knowledge transfer by having the receiver do the real work while the expert observes. Gaps show up while there's still time to close them.`},
    {t:`Have Theo sign off that the runbook is complete before he leaves.`,s:0,d:{trust:0,conf:0,health:0},
     after:`Theo signs. A signed document still doesn't tell you whether Priya can do the job.`,
     why:`A signature confirms the document exists, not that the knowledge transferred.`},
    {t:`Keep Theo on call as a paid contractor for the first month after.`,s:0,d:{trust:-1,conf:0,health:1},
     after:`It's a safety net. It also tells Priya and the team you don't trust the transfer.`,
     why:`A contractor backup can be sensible, but it isn't verification, and it can undercut the new lead before she starts.`}
   ]},
  {id:`f6s10`, domain:`People`, task:`P3`, title:`Not Theo`,
   text:(s,all,G)=>[`Thursday evening, Priya stops by Sam's desk. <span class="said">"I don't think I should be the lead,"</span> she says. <span class="said">"I'm not Theo. I can't do what he does."</span>`,`She's the best person for it, and the only one who doesn't see it.`],
   opts:[
    {t:`Offer her the role on a trial basis so there's less pressure on her.`,s:1,d:{trust:0,conf:0,health:1},
     after:`She accepts the trial. It also tells her Sam isn't sure either.`,
     why:`A trial can lower the stakes, but it can also signal doubt. Clear support usually works better.`},
    {t:`Say she doesn't need to be Theo, agree on support, and back her publicly.`,s:3,best:true,d:{trust:6,conf:1,health:4},
     after:`<span class="said">"Theo did it alone,"</span> Sam says. <span class="said">"That's why he's leaving. You'll do it with a team."</span> They agree on a weekly check in and that Devin owns performance. On Friday Sam announces her as platform lead and the Kraków team applauds on the screen.`,
     why:`Coaching addresses the real fear and sets up support. Public backing gives a new leader the authority to succeed.`},
    {t:`Hire an experienced lead from outside and keep Priya as the deputy.`,s:0,d:{trust:-5,conf:0,health:-2},
     after:`Priya hears it as a verdict. The outside hire takes two months to find.`,
     why:`Skipping over a capable internal person because she doubts herself loses her and the knowledge you just transferred.`},
    {t:`Split the lead role between Priya and Devin so neither carries it alone.`,s:0,d:{trust:-1,conf:0,health:-2},
     after:`Two leads means nobody is quite sure who decides.`,
     why:`Shared leadership without clear decision rights causes confusion. Support one leader instead.`}
   ]},
  {id:`f6s11`, domain:`Business Environment`, task:`B4`, title:`Cascade's environment`,
   text:(s,all,G)=>[`Cascade's integration test environment has been down for four days. It belongs to Cascade's IT team, not Halcyon. Halcyon's integration testing is stuck behind it.`,`Ochoa's infrastructure lead, when Sam finally reaches him, says it's on the list.`],
   opts:[
    {t:`Log it as an issue, get an owner at Cascade, and agree on a fix date.`,s:3,best:true,d:{trust:1,conf:3,health:4},
     after:`Sam raises it on the weekly call with Ochoa, with the dates and the impact. Ochoa assigns a named engineer. The environment is back Tuesday.`,
     why:`An issue outside your control still needs an owner and a date. Log it, make the impact visible, and work it through the stakeholder who can fix it.`},
    {t:`Have Halcyon's team rebuild a copy of Cascade's environment internally.`,s:0,d:{trust:-1,conf:0,health:-3},
     after:`It takes a week and doesn't match Cascade's setup closely enough to trust.`,
     why:`Working around another organization's environment usually creates a false test. Get the owner to fix it.`},
    {t:`Keep checking in with the infrastructure lead daily until it's fixed.`,s:1,d:{trust:0,conf:0,health:0},
     after:`He keeps saying it's on the list.`,
     why:`Persistence helps, but if the person you're talking to can't prioritize it, raise it with someone who can.`},
    {t:`Move integration testing to after go-live, since it's out of Halcyon's hands.`,s:0,d:{trust:0,conf:-4,health:-6},
     after:`Lena looks at Sam like he's lost his mind.`,
     why:`Skipping a quality activity because of an impediment trades a delay for a much bigger risk.`}
   ]},
  {id:`f6s12`, domain:`People`, task:`P3`, title:`Retro`,
   text:(s,all,G)=>[`Theo's last day ends with a retrospective, his idea. Pizza, the Kraków team on the screen with their own pizza, eight hours later in the evening.`,`Sam wants the team to leave this room working better than it walked in.`],
   opts:[
    {t:`Have the team choose two changes for next sprint, each with an owner.`,s:3,best:true,d:{trust:5,conf:1,health:4},
     after:`They pick two: a shared on call rotation so nobody is ever the only one again, and a monthly incident story session, Theo's idea. Devin volunteers to own the second. Nobody expected that.`,
     why:`Retros work when the team owns a small number of concrete improvements and actually tries them. That's continuous improvement driven by the team.`},
    {t:`Write up the action items himself after hearing the team's input.`,s:1,d:{trust:-1,conf:0,health:2},
     after:`The list is good. The team treats it like Sam's list.`,
     why:`Ownership matters. Improvements the team chooses get done; ones handed to them get filed.`},
    {t:`Make it a farewell for Theo and skip the improvement part this time.`,s:0,d:{trust:1,conf:0,health:-1},
     after:`It's a nice party. Nothing changes.`,
     why:`Celebrating is good, and you can do both. Skipping the reflection misses the moment the team is most open to change.`},
    {t:`Review every problem from the past three weeks in order, one by one.`,s:0,d:{trust:-1,conf:0,health:0},
     after:`It takes two hours. They run out of time before deciding anything.`,
     why:`A retrospective is about choosing a few improvements, not cataloging every problem.`}
   ]}
 ],
 exercise:{after:`f6s4`, title:`Name the conflict mode`, intro:`Each project manager is handling a conflict. Which mode are they using?`,
  items:[
   {prompt:`Two leads disagree on a design. The PM gets them to agree on the requirement, then they test both designs against it together.`,choices:[`Collaborate`,`Compromise`,`Force`,`Smooth`,`Withdraw`],answer:0,why:`Working through the facts toward a shared solution is collaborating, or problem solving.`},
   {prompt:`A server room is overheating. The PM orders an immediate shutdown over the objections of two engineers.`,choices:[`Collaborate`,`Compromise`,`Force`,`Smooth`,`Withdraw`],answer:2,why:`Directing by authority in an emergency is forcing, and here it's appropriate.`},
   {prompt:`Sales wants five features, engineering offers two. They settle on three and a half.`,choices:[`Collaborate`,`Compromise`,`Force`,`Smooth`,`Withdraw`],answer:1,why:`Each side gives something up. That's compromise.`},
   {prompt:`The PM tells two arguing team members they agree on far more than they disagree, and changes the subject.`,choices:[`Collaborate`,`Compromise`,`Force`,`Smooth`,`Withdraw`],answer:3,why:`Emphasizing agreement and playing down differences is smoothing.`},
   {prompt:`Tempers are high in a meeting, so the PM postpones the discussion until the next day.`,choices:[`Collaborate`,`Compromise`,`Force`,`Smooth`,`Withdraw`],answer:4,why:`Postponing is withdrawing. It can be a sensible short pause if you come back to it.`},
   {prompt:`A PM brings both vendors' engineers together, they share logs, and they find a fix that works for both systems.`,choices:[`Collaborate`,`Compromise`,`Force`,`Smooth`,`Withdraw`],answer:0,why:`Sharing information and solving the underlying problem together is collaboration.`}
  ]},
 quiz:[
  {q:`Two senior stakeholders argue loudly during a team meeting. What should the project manager do first?`,opts:[`Let the argument continue so the issue can surface fully`,`Move the discussion to a private meeting with both of them`,`Side with the stakeholder whose view the data supports`,`Ask the sponsor to settle the disagreement right away`],a:1,why:`Move public conflict to a private setting quickly, then work to resolve it.`,task:`P2`,domain:`People`},
  {q:`Which conflict resolution approach most often produces lasting commitment?`,opts:[`Compromising`,`Smoothing`,`Forcing`,`Collaborating`],a:3,why:`Collaborating, or problem solving, addresses the cause and gains everyone's commitment.`,task:`P2`,domain:`People`},
  {q:`A key engineer is leaving in three weeks. Which approach best transfers their tacit knowledge?`,opts:[`Have them pair with a successor on real work every day`,`Ask them to write a detailed handover document this week`,`Hire a contractor with similar skills before they leave`,`Record their working hours and tasks in a timesheet log`],a:0,why:`Tacit knowledge moves through people. Pairing on real work, plus documenting as you go, transfers it best.`,task:`P7`,domain:`People`},
  {q:`A team that worked well starts arguing about processes after two members leave and one joins. Which Tuckman stage is the team most likely in?`,opts:[`Forming`,`Norming`,`Storming`,`Adjourning`],a:2,why:`Membership changes can push a team back into storming, where roles and ways of working get contested.`,task:`P3`,domain:`People`},
  {q:`During storming, what is the project manager's most important role?`,opts:[`Assign roles and decide on processes for the team`,`Step back and let the team settle the friction itself`,`Facilitate conflict and help the team reset agreements`,`Report the friction to functional managers for action`],a:2,why:`In storming, the leader facilitates conflict and helps the team revisit its working agreements.`,task:`P3`,domain:`People`},
  {q:`A team member has missed commitments for three sprints. What should the project manager do first?`,opts:[`Talk with them privately to understand the cause`,`Start a formal performance improvement plan`,`Raise the issue in the next team retrospective`,`Reassign their work to higher performing members`],a:0,why:`Start with a private coaching conversation. Formal steps come later, if needed.`,task:`P3`,domain:`People`},
  {q:`The project manager loses their temper with a vendor's team during a call. What is the best next step?`,opts:[`Send a written explanation of the pressure the team was under`,`Ask a colleague to repair the relationship with the vendor`,`Wait for the vendor to raise the issue before responding`,`Apologize directly to the vendor lead and address the problem`],a:3,why:`Emotional intelligence includes owning and repairing your mistakes directly, then solving the underlying problem.`,task:`P3`,domain:`People`},
  {q:`Only one person can approve production deployments, and that person is overloaded. What should the project manager do?`,opts:[`Ask the approver to batch approvals once a day`,`Delegate approval authority, with oversight at first`,`Allow deployments without approval for a short time`,`Pause deployments until the approver is less busy`],a:1,why:`Removing an impediment can mean redistributing authority while keeping the control in place.`,task:`B4`,domain:`Business Environment`},
  {q:`How can a project manager best verify that knowledge was transferred before an expert leaves?`,opts:[`Have the successor do the work while the expert observes`,`Ask the successor to rate how ready they feel to take over`,`Have the expert sign that all documentation is complete`,`Keep the expert available on contract for several months`],a:0,why:`The best verification is the receiver doing the real work while the expert can still catch gaps.`,task:`P7`,domain:`People`},
  {q:`The team keeps detailed runbooks in its wiki, but new engineers still freeze on their first real production incident. What should the project manager add?`,opts:[`A longer wiki page with more detail for each incident type`,`A quiz on the runbooks before anyone goes on call alone`,`Shadowing on live incidents beside an experienced engineer`,`A recorded walkthrough video of the architecture diagrams`],a:2,why:`The gap is tacit knowledge: judgment that comes from doing the work with someone who has it. More documents add explicit knowledge, which the team already has. Shadowing on real incidents transfers what the runbooks can't.`,task:`P7`,domain:`People`},
  {q:`During Theo's handover, the team keeps finding small things that would have helped them weeks earlier. What should the project manager do with these lessons?`,opts:[`Hold them for the lessons learned session at project closure`,`Add them to the lessons learned register as the team finds them`,`Ask Theo to write them into his final handover document now`,`Share them in the next status report to the project sponsor`],a:1,why:`Lessons learned are captured throughout the project, not saved for the end, so the current team and future teams can act on them while they still matter. That habit is the start of continuous improvement.`,task:`B6`,domain:`Business Environment`},
  {q:`An issue owned by the customer's IT team is blocking the project. What should the project manager do?`,opts:[`Build a workaround environment within the project team`,`Defer the blocked testing until after the release date`,`Log the issue; set an owner and date with the customer`,`Keep following up daily with the original contact person`],a:2,why:`Issues outside your control still need an owner and a resolution date. Work through the stakeholder who can fix it.`,task:`B4`,domain:`Business Environment`},
  {q:`What makes a retrospective most effective?`,opts:[`The team chooses a few improvements and owns them`,`The project manager assigns actions after listening`,`Every issue from the iteration is reviewed in order`,`It's held only when the team has had a bad sprint`],a:0,why:`Retros work when the team commits to a small number of concrete improvements it owns.`,task:`P3`,domain:`People`},
  {q:`In which situation is forcing the most appropriate conflict resolution approach?`,opts:[`Two developers disagree on a coding style preference`,`A safety issue requires an immediate decision`,`Sales and engineering disagree on release scope`,`Team members disagree about meeting schedules`],a:1,why:`Forcing fits emergencies, especially safety issues, where there's no time for collaboration.`,task:`P2`,domain:`People`},
  {q:`Which document captures the team's own agreements on values, ground rules, and decision making?`,opts:[`Project charter`,`Resource management plan`,`Communications management plan`,`Team charter`],a:3,why:`The team charter is created by the team and records its values, ground rules, and working agreements.`,task:`P3`,domain:`People`}
 ],
 closing:(s,all,G)=>[
  `Theo's going away party ended at nine. He hugged Priya, shook Devin's hand, and gave Tomasz's team on the screen a salute that made them laugh. He stopped at Sam's desk on the way out.`,
  `<span class="said">"For what it's worth,"</span> Theo said, <span class="said">"this was the first time anyone made me teach it instead of do it. I should have been doing that for two years."</span>`,
  `<span class="said">"So should I,"</span> Sam said, and meant it.`,
  `On Monday the on call rotation went live with four names on it. Priya's was first. Devin had added a line to the team charter, in his own words: <span class="said">"Nobody is the only one."</span>`,
  (s.score>=27?`The dashboard by the kitchen showed velocity back above where it had been before the burn-in. Lena noticed. She bought donuts, which for Lena was a speech.`:`Velocity was still below where it had been before the burn-in. But the standups were louder now, in the useful way, and Sam decided that counted for something.`),
  `At 4:12 that afternoon Ochoa's email arrived. Cascade wanted a live demo of the documentation agents for clinicians in two weeks. Real nurses, real workflows, test data.`,
  `The last line was the one Sam read three times. <span class="said">"Maria Santos will run it from our side. She ran an ICU for eleven years before she ran informatics. Bring your best."</span>`
 ],
 episode:{src:`audio/full-ch06.mp3`, len:`about 35 minutes`},
 next:`The Demo`
});
