// Full Course, Chapter 7. See full/BIBLE.md for the format.
(window.HALCYON_FULL=window.HALCYON_FULL||[]).push({
 num:7, part:`Part One: The Cascade Launch`, title:`The Demo`, weeks:`Weeks 8 to 10`,
 tasks:[`R3`,`R2`,`P5`,`P6`,`R7`],
 cast:[[`Maria Santos`,`Nurse informatics director at Cascade. Product owner. Fourteen years in the ICU.`]],
 opening:[
  `Week eight started with an empty chair. Theo's desk had been cleared on Friday, and on Monday morning someone had already left a stack of loaner laptops on it, the way an office fills a gap before anybody has decided what the gap means.`,
  `Priya Shah ran the platform work now. She'd moved Theo's runbook into a shared doc and added a section at the top called "Things that surprised me," which she updated every day. Nobody had asked her to. When Sam mentioned it in standup she turned red and changed the subject to the deploy queue.`,
  `Cascade had sent a product owner. Maria Santos had spent fourteen years as an ICU nurse before she ran nursing informatics for all eleven hospitals. She showed up at Halcyon's office in LoDo on Monday with a canvas bag, a printed copy of the backlog covered in her handwriting, and no interest at all in how the agents worked.`,
  `<span class="said" data-who="Maria">"I don't need to understand the model,"</span> she told Sam in the elevator. <span class="said" data-who="Maria">"I need to know whether a nurse at four in the morning, on hour eleven of a twelve, can trust what it writes. Because she will. That's the danger. She'll trust it."</span>`,
  `The first live demo was set for Thursday of week nine. Six nurses and a hospitalist from Cascade's Laramie hospital would use the agents on real workflows in a test environment, with real looking patient records that weren't real. Ochoa would watch from the back of the room.`,
  `At home that night, Dana found Sam at the kitchen table at eleven, reading the backlog on his phone. <span class="said" data-who="Dana">"You've got the inspection face,"</span> she said. He did. On the flight line, the night before an inspection, everything always looked fine. That was exactly what used to worry him, and it worried him now.`
 ],
 lesson:{
  title:`Delivering value, not just output`,
  sections:[
   {h:`Value is the point`,
    body:[`A project exists to produce value, not deliverables. The July 2026 exam outline has a whole task for this: help ensure value-based delivery. In practice it means you keep asking which piece of work moves the customer's outcome most, and you deliver that first. For Cascade the outcome is less time charting and safer notes. A feature that looks impressive in a demo but doesn't save a nurse time has little value, however much effort it took.`,
     `Value-based delivery is why agile approaches release in small increments. Each increment is a chance to learn whether you're right before you've spent the budget. A predictive project can deliver value too, but it usually learns late. A hybrid project like Halcyon's uses plan-driven work where the scope is fixed and incremental delivery where it isn't.`],
    terms:[[`Value`,`The benefit the customer or organization actually gets, which may be money, time, safety, or risk reduction.`],[`Increment`,`A usable piece of the product delivered at the end of an iteration.`]],
    exam:`When a question asks what to deliver first, look for the answer that delivers the highest value or retires the biggest risk soonest, not the easiest or most visible item.`},
   {h:`The product owner and the backlog`,
    body:[`In an agile team, the product owner owns the product backlog. That person decides what's in it and in what order, based on value. The team decides how the work gets done and how much fits in an iteration. The project manager, or the scrum master in a pure scrum team, protects that arrangement. A PM who reorders the backlog because a sales executive asked is undermining the product owner, and the exam will treat it as a mistake.`,
     `Prioritization techniques you should recognize: MoSCoW sorts items into must have, should have, could have, and won't have this time. Kano separates basic needs, performance needs, and delighters. Weighted shortest job first divides the cost of delay by the job's size. You won't be asked to run Kano in depth, but you will be asked who prioritizes, and the answer is the product owner, in collaboration with stakeholders.`],
    terms:[[`Product backlog`,`The ordered list of everything that might go into the product.`],[`MoSCoW`,`Must, Should, Could, Won't. A quick way to agree on scope priorities.`],[`Backlog refinement`,`Ongoing work to clarify, split, and estimate backlog items before they're needed.`]],
    exam:`If a stakeholder asks the team directly for new work mid-iteration, the best answer usually routes it to the product owner and the backlog, not straight into the current sprint.`},
   {h:`The MVP`,
    body:[`A minimum viable product is the smallest release that lets you learn whether you're building the right thing with real users. It is not a half-finished product and it is not a prototype nobody can use. For Cascade, the MVP is the core documentation agent for three hospitals, done well, with nurses reviewing and signing every note. Discharge instructions, voice dictation, and the analytics dashboard all wait.`,
     `Two related terms: a minimum marketable feature is the smallest piece that has value on its own and can be released. A minimum business increment is the smallest amount of value that can be delivered to the business. You mostly need to know that an MVP exists to test a hypothesis cheaply.`],
    terms:[[`MVP`,`Minimum viable product, the smallest version that tests your key assumptions with real users.`],[`MMF`,`Minimum marketable feature, the smallest feature with standalone value.`]],
    exam:`Watch for answers that pile features into the first release to make the customer happy. The exam favors a lean first release with feedback.`},
   {h:`Agile ceremonies in a hybrid project`,
    body:[`Sprint planning is where the team pulls the top of the backlog into a sprint and commits to a sprint goal. The daily standup is a short planning meeting for the team, not a status report for a manager. The sprint review shows the finished increment to stakeholders and collects feedback. The retrospective looks at how the team worked and picks a few changes to try. Each one is a feedback loop at a different speed.`,
     `Once a sprint starts, protect the sprint goal. New ideas, even good ones from the product owner, go to the product backlog and get ordered for a later sprint. Only the product owner orders the backlog, so a sales request goes to them, not to the team. And velocity belongs to one team: it's built on that team's own estimates, so it forecasts that team's future and says nothing about whether another team is more productive.`,
     `In a hybrid project these ceremonies sit inside a larger plan. Halcyon's cluster work runs on a fixed schedule with milestones, while the agent work runs in two week sprints that feed those milestones. The project manager's job is to keep the two in step: the integrated plan shows when software increments must be ready for hardware milestones, and sprint reviews tell you early when they won't be.`,
     `Information radiators make status visible without a meeting: a task board on the wall, a burndown chart, a list of impediments. The exam likes them because they support transparency and self-organization. If a question asks how to keep stakeholders informed with less overhead, a visible board is often the answer.`],
    terms:[[`Sprint goal`,`The single objective the team commits to for the sprint.`],[`Information radiator`,`A highly visible display of project information, like a task board or burndown chart.`]],
    exam:`Know the purpose of each ceremony. A question that treats the standup as a status meeting for the PM, or the retrospective as a place to assign blame, is describing the wrong answer.`},
   {h:`Quality is built in`,
    body:[`The definition of done is the team's shared checklist for when any backlog item is finished, for example code reviewed, tested, documented, and passed a security scan. Acceptance criteria are specific to one item and say what must be true for the product owner to accept it. Done covers every item. Acceptance criteria cover one.`,
     `Quality in agile is built in, not inspected in at the end. That means automated tests, continuous integration, pairing, and fixing defects as soon as they're found. Technical debt is the cost you take on when you choose a shortcut now, and it accrues interest. The healthy answer is to make debt visible and pay it down steadily, often by reserving some capacity every iteration.`,
     `Two measures you'll see: velocity is the amount of work a team completes per iteration, used to forecast. A burndown chart shows work remaining against time. Never compare velocity between teams. It is a planning tool for one team, not a performance score.`],
    terms:[[`Definition of done`,`The team's checklist that applies to every item before it counts as complete.`],[`Acceptance criteria`,`Conditions a single item must meet for the product owner to accept it.`],[`Technical debt`,`Future rework created by taking a shortcut today.`],[`Velocity`,`Work completed per iteration, used for forecasting by the same team.`]],
    exam:`If a defect reaches a demo, the exam wants transparency with the customer first, then root cause and a process fix, not a quiet patch.`}
  ],
  video:[`ceqIFb84ugg`,`Difference Between MVP, PSI, MMF and MMP (PMP Exam Prep)`,`Praizion`,`4:38`]
 },
 scenes:[
 {id:`f7s1`, domain:`Process`, task:`R3`, title:`Who decides what comes first`,
  text:(s,all,G)=>[`Maria's handwritten backlog doesn't match the one in the tracker. She's moved medication reconciliation to the bottom and pulled nursing shift notes to the top. Grant sees it in the shared doc within the hour.`,`<span class="said" data-who="Grant">"Med rec is the feature we sold,"</span> he tells Sam. <span class="said" data-who="Grant">"It was on every slide. Put it back."</span>`],
  opts:[
   {t:`Explain to Grant that Maria owns the order, and set up a talk between them about value.`,s:3,best:true,d:{trust:3,conf:4,health:3},
    after:`Grant grumbles, but he meets Maria. She walks him through how many minutes a nurse spends on shift notes versus med rec. Grant leaves quiet. Two days later he's quoting her numbers to another prospect.`,
    why:`The product owner owns backlog order and makes it on value. The PM's job is to protect that and connect stakeholders who disagree to the person who decides, not to settle it by rank.`},
   {t:`Move med rec back to the top, since it was promised in the sales process to Cascade.`,s:0,d:{trust:-3,conf:-4,health:-2},
    after:`Maria finds out the next morning. She asks Sam, politely, what exactly she's there for. It takes a week to rebuild that.`,
    why:`Overriding the product owner to satisfy an internal executive undermines the role and the customer's trust. What was promised in a sales deck isn't automatically what delivers value first.`},
   {t:`Leave Maria's order but ask her to explain her reasoning in writing to the steering group.`,s:1,d:{trust:1,conf:1,health:1},
    after:`Maria writes a crisp page. It's good, and the steering group accepts it, but it reads to her like she's on trial.`,
    why:`Transparency about prioritization is good. Making the product owner justify every call to a committee erodes her authority. Better to bring the disagreeing stakeholder to her directly.`},
   {t:`Split the difference and put med rec in the middle so both of them get something.`,s:0,d:{trust:-1,conf:-1,health:-2},
    after:`Nobody is happy, and the backlog now reflects politics instead of value. The team notices.`,
    why:`Compromise isn't a prioritization method. Order should come from value, decided by the product owner, not from averaging the opinions of the loudest people.`}
  ]},
 {id:`f7s2`, domain:`Process`, task:`R2`, title:`What's in the MVP`,
  text:(s,all,G)=>[`The release for the first three hospitals has room for maybe sixty percent of the backlog. Maria, Lena, Priya, and Sam spend Tuesday afternoon in a conference room with sticky notes.`,`Lena wants voice dictation in, because the competitor has it. Maria wants nothing in that a nurse can't review in under a minute.`],
  opts:[
   {t:`Run a MoSCoW session with Maria deciding, and park voice dictation as a should have.`,s:3,best:true,d:{trust:3,conf:2,health:5},
    after:`The must haves fit with a week to spare. Voice dictation goes on the phase one and a half list with a date to revisit. Lena doesn't love it, but she agrees the MVP has to be something nurses can trust first.`,
    why:`MoSCoW gives the group a shared language and the product owner makes the final call. The MVP should be the smallest release that tests the key assumption, here that nurses will trust and sign the notes.`},
   {t:`Include voice dictation so Halcyon matches the competitor feature for feature on day one.`,s:0,d:{trust:0,conf:1,health:-6},
    after:`The release grows by three weeks of work. The team starts cutting testing time to make room.`,
    why:`Chasing a competitor's feature list inflates the first release and pushes out the learning. A lean MVP that works beats a full one that's late or brittle.`},
   {t:`Ask the team to estimate everything again before anyone agrees on what's in the release.`,s:1,d:{trust:1,conf:0,health:1},
    after:`The new estimates are better, but the room still can't agree, because estimates don't answer the question of value.`,
    why:`Good estimates help, but they don't decide priority. The decision is about value, and that belongs to the product owner with input from the team and stakeholders.`},
   {t:`Let Lena decide, since engineering will build it and she knows what's technically feasible.`,s:0,d:{trust:-2,conf:-2,health:-1},
    after:`Lena picks the technically interesting items. Maria sees the list and asks where shift notes went.`,
    why:`Engineering decides how to build and how much fits, not what's most valuable. Handing scope decisions to the technical lead sidelines the product owner.`}
  ]},
 {id:`f7s3`, domain:`Process`, task:`R7`, title:`What done means`,
  text:(s,all,G)=>[`Wednesday, the day before the demo. Priya mentions in standup that three stories are "done except for testing." Devin says two more are "basically done."`,`Sam has heard "basically done" on a flight line. It usually meant a panel wasn't torqued.`],
  opts:[
   {t:`Get the team to agree on a written definition of done and hold every story to it today.`,s:3,best:true,d:{trust:3,conf:1,health:5},
    after:`The team writes it on the whiteboard: reviewed, tested, clinical safety check passed, demo data loaded. Five stories turn out not to be done. Two get finished, three come out of the demo. Nobody argues, because they wrote the rule.`,
    why:`A shared definition of done removes the guesswork. It applies to every item and is set by the team. It's how quality gets built in rather than discovered in front of a customer.`},
   {t:`Count the stories as done for the demo and finish the testing in next week's sprint.`,s:0,d:{trust:0,conf:0,health:-5},
    after:`The demo includes features nobody has tested with clinical data. You can probably guess how that goes.`,
    why:`"Done except testing" isn't done. Moving untested work into a customer demo transfers your risk to the customer and to their patients.`},
   {t:`Ask Maria to write acceptance criteria for each story so the team knows what passes.`,s:1,d:{trust:1,conf:2,health:2},
    after:`Maria writes them that afternoon. They're excellent. They still don't cover code review or the safety check, which apply to everything.`,
    why:`Acceptance criteria are item specific and come from the product owner. They matter, but they don't replace the definition of done, which is the team's standard for every item.`},
   {t:`Delay the demo a week so every story can be fully finished before Cascade sees it.`,s:0,d:{trust:0,conf:-4,health:1},
    after:`Ochoa's team has already scheduled six nurses off the floor. Moving it costs Cascade more than it saves Halcyon.`,
    why:`The fix is to demo only what meets done, not to slip the event. A sprint review shows finished increments, and you can show fewer of them.`}
  ]},
 {id:`f7s4`, domain:`People`, task:`P5`, title:`Setting up the room`,
  text:(s,all,G)=>[`Grant wants a polished slide deck and a scripted walkthrough with perfect data. <span class="said" data-who="Grant">"First impressions,"</span> he says. Maria wants the nurses to use it cold, with no script, the way they'd use it at work.`,`Ochoa calls Sam that evening. <span class="said" data-who="Ochoa">"What exactly am I going to see tomorrow?"</span>`],
  opts:[
   {t:`Tell Ochoa it's an early working version, nurses will use it unscripted, and expect rough edges.`,s:3,best:true,d:{trust:1,conf:6,health:1},
    after:`Ochoa says that's exactly what he wanted to hear. <span class="said" data-who="Ochoa">"If it's perfect, I won't believe it."</span> Grant drops the script.`,
    why:`Aligning expectations before an event means stakeholders judge it against the right standard. An honest framing turns problems found tomorrow into progress instead of surprises.`},
   {t:`Promise Ochoa a smooth demo and run Grant's scripted walkthrough to protect the first impression.`,s:0,d:{trust:-2,conf:-3,health:0},
    after:`The script works for eleven minutes. Then a nurse asks to try a real scenario and the room goes quiet.`,
    why:`A scripted demo hides what you most need to learn and sets an expectation you can't keep. Sprint reviews are for honest feedback on working product.`},
   {t:`Run the scripted portion first, then let the nurses try it unscripted for the last half hour.`,s:1,d:{trust:0,conf:2,health:0},
    after:`It's a reasonable compromise, but the script eats most of the time and the nurses get twenty minutes.`,
    why:`Better than all script, but it still spends the customer's time on theater. The value of a review is real users on real work.`},
   {t:`Ask Maria to set Ochoa's expectations, since she's on the Cascade side and he trusts her.`,s:0,d:{trust:0,conf:-2,health:0},
    after:`Maria does, but Ochoa asked Sam. He notices Sam didn't answer.`,
    why:`The PM owns stakeholder expectations for what the project is delivering. Handing the conversation off, especially when you were asked directly, reads as avoidance.`}
  ]},
 {id:`f7s5`, domain:`Process`, task:`R7`, title:`The invented medication`,
  text:(s,all,G)=>[`Thursday, forty minutes in. A Laramie nurse named Becca asks the agent to draft a note for a post-op patient. The draft is clean and fast. It also lists metoprolol, which the patient has never taken.`,`Becca catches it in about four seconds. <span class="said" data-who="woman">"Where did that come from?"</span> The room goes still. Ochoa writes something down.`],
  opts:[
   {t:`Call it a serious defect out loud, log it live, and keep testing the rest with them.`,s:3,best:true,d:{trust:3,conf:5,health:2},
    after:`Sam says, <span class="said" data-who="Sam">"That's exactly what this session is for. That's a safety defect and we're logging it now."</span> Priya writes it up live on the screen. The nurses relax and get more aggressive about testing, and they find two smaller problems.`,
    why:`Acknowledge the defect openly, record it, and keep learning. A review is where you want problems to surface, and how the team reacts tells the customer whether they can trust you.`},
   {t:`Explain that the test data may have caused it and move on to the next scenario quickly.`,s:0,d:{trust:-2,conf:-6,health:-1},
    after:`Becca doesn't buy it, and neither does Ochoa. The rest of the session the nurses are polite and unconvinced.`,
    why:`Guessing at a cause to save face in front of the customer looks like minimizing a patient safety issue. You don't know the cause yet. Say so.`},
   {t:`End the demo early so the team can investigate before Cascade sees anything else go wrong.`,s:1,d:{trust:0,conf:-2,health:1},
    after:`It's cautious, but the nurses had cleared their afternoon, and Halcyon loses the feedback on everything else.`,
    why:`Pausing to protect patients can be right in production. In a test environment with no real patients, ending early throws away the learning the review exists for.`},
   {t:`Have Priya patch it on the spot so the nurses can see the fix working before they leave.`,s:0,d:{trust:-1,conf:-1,health:-4},
    after:`Priya tries. A rushed patch in front of the customer breaks the demo environment for twenty minutes.`,
    why:`Hot fixing in a review skips the root cause and the quality process. Log it, investigate it properly, and fix it the right way.`}
  ]},
 {id:`f7s6`, domain:`People`, task:`P6`, title:`Telling Cascade`,
  text:(s,all,G)=>[`After the demo, in the hallway, Grant pulls Sam aside. <span class="said" data-who="Grant">"Ochoa saw a blip. Let's not put 'invented medication' in writing. We fix it, we show him the fix, nobody makes it bigger than it is."</span>`,`Priya's preliminary look says it isn't a blip. The agent filled a gap in the record with something statistically likely.`],
  opts:[
   {t:`Send Ochoa and Maria a written summary today: what happened, what we know, next steps.`,s:3,best:true,d:{trust:2,conf:6,health:1},
    after:`Ochoa replies in nine minutes. <span class="said" data-who="Ochoa">"Thank you. This is why I'm still on this call every week."</span> Maria asks to join the root cause review.`,
    why:`Manage stakeholder expectations with honest, timely information, especially on safety. Putting it in writing the same day, with what you know and don't, is how trust survives a bad moment.`},
   {t:`Wait until the fix is ready, then tell Ochoa what happened and show him it's solved.`,s:0,flag:`hiddefect`,d:{trust:-1,conf:-5,health:0},
    after:`It takes eight days to fix properly. Maria hears about the root cause from a Halcyon engineer at lunch on day five. She doesn't say anything to Sam. She doesn't have to.`,
    why:`Holding back known safety information until you have good news is hiding it. Customers judge you more by how you handle problems than by whether you have them.`},
   {t:`Call Ochoa today to explain it verbally, and send the written report once there's a cause.`,s:1,d:{trust:1,conf:3,health:0},
    after:`The call goes well. The missing paper trail makes Cascade's own safety committee nervous the following week.`,
    why:`A call is good. Safety issues on a health system's project need a written record the customer can take to their own governance, the same day.`},
   {t:`Ask Elena how she wants to handle it, since this could affect the whole Cascade relationship.`,s:0,d:{trust:0,conf:-2,health:0},
    after:`Elena is in board prep until Monday. Four days pass.`,
    why:`Keep the sponsor informed, but don't wait on her to do something clearly within your role. Telling the customer the truth promptly is the PM's job.`}
  ]},
 {id:`f7s7`, domain:`Process`, task:`R7`, title:`Root cause`,
  text:(s,all,G)=>[`The root cause review is Monday. Priya, Maria, Lena, two Kraków engineers on video, and Sam.`,`Priya's finding: when a patient record has a gap, the model fills it with the most likely value. There's no check that every medication in a draft exists in the source record.`],
  opts:[
   {t:`Add an automated check that every drug traces to the record, and make it part of done.`,s:3,best:true,d:{trust:3,conf:4,health:6},
    after:`Priya builds a grounding check. Every medication, dose, and allergy must trace to the record or it's flagged in red for the nurse. It goes into the definition of done for every agent. Maria calls it the first thing she's seen that she'd trust at four in the morning.`,
    why:`Fix the process, not just the instance. Building the check into the definition of done means quality is designed in and every future item is protected.`},
   {t:`Have a nurse on Halcyon's side review every draft note before Cascade's pilot users see it.`,s:1,d:{trust:0,conf:2,health:-2},
    after:`It catches errors, but it doesn't scale past a pilot and it costs a salary.`,
    why:`Inspection catches defects but doesn't prevent them. Cost of quality favors prevention over appraisal, and prevention here is an automated check in the product.`},
   {t:`Retrain the model on more data so it learns not to fill gaps with likely medications.`,s:0,d:{trust:0,conf:0,health:-3},
    after:`Retraining takes three weeks and the behavior improves but doesn't go away. Models still guess.`,
    why:`More training might reduce the rate, but it doesn't guarantee safety. For a known failure with patient risk, add a deterministic control.`},
   {t:`Add a warning in the interface telling nurses to double-check all medications in drafts.`,s:0,d:{trust:0,conf:-1,health:-1},
    after:`Maria reads the warning text and says, <span class="said" data-who="Maria">"Nobody reads these after day two."</span> She's right.`,
    why:`Pushing the burden to the user is the weakest control. Fix the defect at the source.`}
  ]},
 {id:`f7s8`, domain:`Process`, task:`R3`, title:`The mid-sprint ask`,
  text:(s,all,G)=>[`Wednesday of the next sprint, Maria messages the team channel directly. Cascade's pharmacy committee wants allergy alerts shown above the note, starting with this release. <span class="said" data-who="Maria">"Can you add it this sprint?"</span>`,`The sprint goal is the grounding check across all three hospitals' templates. Priya estimates the alert at five points. The team committed to thirty.`],
  opts:[
   {t:`Ask the team how it affects the sprint goal; if it threatens it, Maria tops next sprint.`,s:3,best:true,d:{trust:4,conf:2,health:3},
    after:`The team says it would push the grounding check. Maria agrees safety comes first and puts the alerts at the top of the next sprint. Pharmacy gets a date and is fine with it.`,
    why:`The product owner can change the product backlog any time, but the sprint backlog is the team's commitment. Protect the sprint goal and let the team and product owner negotiate.`},
   {t:`Add it, since Maria is the product owner and she has the authority to change priorities.`,s:0,d:{trust:-3,conf:2,health:-3},
    after:`The team adds it and quietly drops part of the grounding check work. Nobody announces the trade.`,
    why:`Product owner authority covers the product backlog, not reshaping the team's sprint commitment without their input. Unspoken trades are how quality slips.`},
   {t:`Tell Maria no, the sprint is locked, and ask her to submit it through the change process.`,s:1,d:{trust:0,conf:-2,health:1},
    after:`Technically defensible. Maria hears it as a door closing and goes quiet for a day.`,
    why:`Protecting the sprint is right, but a flat no from the PM skips the conversation. Bring the team and product owner together to weigh it.`},
   {t:`Have the Kraków team build the alert in parallel so the sprint goal isn't affected.`,s:0,d:{trust:-1,conf:1,health:-2},
    after:`Kraków starts on it without a refined story and builds the wrong layout. Tomasz is annoyed to be treated as overflow.`,
    why:`Adding work to a team outside the plan dodges the prioritization question and creates integration risk. Let the backlog decide.`}
  ]},
 {id:`f7s9`, domain:`Process`, task:`R2`, title:`The debt`,
  text:(s,all,G)=>[`Priya brings Sam a list. Fourteen shortcuts the team took to make the demo, from hard-coded hospital templates to a test suite that only covers the happy path. <span class="said" data-who="Priya">"None of it is on fire,"</span> she says. <span class="said" data-who="Priya">"All of it will be."</span>`,`The release date hasn't moved, and Grant has already promised Northgate a demo next quarter.`],
  opts:[
   {t:`Make the debt visible in the backlog and reserve some capacity each sprint to pay it.`,s:3,best:true,d:{trust:4,conf:1,health:5},
    after:`The team sets aside about fifteen percent of each sprint. Maria agrees because Priya shows her which items carry patient safety risk. The list shrinks every sprint.`,
    why:`Technical debt should be visible, prioritized with the product owner, and paid down steadily. A fixed slice of capacity keeps it from piling up without stopping delivery.`},
   {t:`Plan a full hardening sprint after go-live to clean up all fourteen items at once.`,s:1,d:{trust:1,conf:0,health:1},
    after:`It's a plan, but hardening sprints get cut first when dates press, and go-live will press.`,
    why:`A dedicated cleanup sprint isn't wrong, but it tends to get deferred. Steady repayment builds quality into normal work.`},
   {t:`Leave the debt alone until the release ships, since none of it is causing problems today.`,s:0,d:{trust:-2,conf:0,health:-5},
    after:`Two of the shortcuts break during hospital two's configuration. They cost more to fix under pressure.`,
    why:`Debt accrues interest. Ignoring it until after a release usually means paying it at the worst time.`},
   {t:`Ask the team to fix the debt in their own time so feature delivery stays on track.`,s:0,d:{trust:-6,conf:0,health:-1},
    after:`Devin works two weekends. Then he stops answering messages after six.`,
    why:`Unpaid overtime isn't capacity. It burns out the team and hides the real cost of the work.`}
  ]},
 {id:`f7s10`, domain:`Process`, task:`R3`, title:`Will the backlog fit`,
  text:(s,all,G)=>[`Elena wants to know whether the remaining work fits before go-live. The team has completed four sprints since re-planning: 31, 27, 34, and 28 points.`,`There are 96 points of must have work left for the first three hospitals, and 168 points in the full release backlog.`],
  opts:[
   {t:`Forecast from average velocity and give Elena a range for both scopes.`,s:3,best:true,d:{trust:1,conf:5,health:3},
    after:`Sam shows a simple chart: about four sprints for the must haves, about six for everything. Elena asks what could make it worse. Sam already has the answer.`,
    why:`Velocity from the same team is the honest basis for an agile forecast. Showing a range and separating must haves from the rest gives the sponsor something to decide with.`},
   {t:`Forecast with the best sprint, 34 points, since the team is improving and learning fast.`,s:0,d:{trust:0,conf:-3,health:-2},
    after:`The forecast looks great until the next sprint comes in at 29.`,
    why:`Using the best data point is optimism, not forecasting. Use the average and show the range.`},
   {t:`Ask the team to re-estimate the backlog in hours so Sam can give Elena an exact date.`,s:1,d:{trust:-1,conf:1,health:0},
    after:`Converting points to hours takes two days of the team's time and produces false precision.`,
    why:`Hours aren't more accurate than points, just more detailed. A velocity forecast with a range is the agile answer.`},
   {t:`Compare Halcyon's velocity with Kraków's to see which team should take the remaining work.`,s:0,d:{trust:-4,conf:0,health:-1},
    after:`Tomasz hears about it and asks, coldly, whether his team's points are worth less.`,
    why:`Velocity is specific to one team's estimating. Comparing teams by velocity is a classic misuse and damages trust.`}
  ]},
 {id:`f7s11`, domain:`People`, task:`P6`, title:`The retrospective`,
  text:(s,all,G)=>[`The sprint retrospective starts badly. Devin says the invented medication happened because Kraków wrote the prompt templates. Tomasz, on video at eleven at night his time, says Denver never gave them clinical examples.`,`Maria sat in to listen. She's watching Sam, not the screen.`],
  opts:[
   {t:`Steer it to the process: what let the gap reach a draft, and what changes now.`,s:3,best:true,d:{trust:6,conf:3,health:3},
    after:`Sam writes "How did the system let this through?" on the board. The answers change. Missing clinical examples, no grounding check, no shared test cases. Three actions, three owners, one of them Tomasz. Maria tells Ochoa later that the retro was the moment she trusted the team.`,
    why:`Retrospectives look at the process, not people. A blameless format gets honest answers and produces concrete improvement actions with owners.`},
   {t:`Let them argue it out, since the conflict needs to surface before the team can move past it.`,s:1,d:{trust:-1,conf:-2,health:0},
    after:`It surfaces. It also gets personal, in front of the customer, and nobody leaves with an action.`,
    why:`Healthy conflict is good, but a facilitator keeps it on the problem. A retro without structure turns into blame.`},
   {t:`End the retro and talk to Devin and Tomasz separately afterward to cool things down.`,s:0,d:{trust:-2,conf:-1,health:-1},
    after:`Both feel heard privately. The team never learns what actually went wrong.`,
    why:`Private conversations have a place, but cancelling the retro loses the team-level learning, which is the point of the ceremony.`},
   {t:`Ask Maria to leave so the team can speak freely about what went wrong with the demo.`,s:0,d:{trust:0,conf:-3,health:0},
    after:`Maria goes. She tells Ochoa that Halcyon asked her to leave the room after a safety issue.`,
    why:`A product owner is part of the team and belongs in the retro. Excluding the customer after a safety issue sends exactly the wrong signal.`}
  ]},
 {id:`f7s12`, domain:`People`, task:`P5`, title:`The second demo`,
  text:(s,all,G)=>[`Week ten. The same six nurses and the hospitalist, the same room. This time Becca tries to break it on purpose: a record with three gaps and an allergy listed twice.`,`Every gap is flagged in red. The allergy shows once, at the top. Becca laughs. Afterward Ochoa asks whether Laramie could join the first wave, since the nurses there are already trained.`],
  opts:[
   {t:`Thank him, explain the impact on the first wave, and offer to bring it as a change request.`,s:3,best:true,d:{trust:2,conf:5,health:2},
    after:`Ochoa nods. <span class="said" data-who="Ochoa">"Show me the tradeoff on paper."</span> The change request goes to the next steering meeting with the impact spelled out, and Laramie is scheduled first in the second wave instead.`,
    why:`Align expectations by making tradeoffs visible. A reasonable request still goes through the change process so the decision is informed and recorded.`},
   {t:`Agree on the spot, since Laramie's nurses are trained and Ochoa has been a strong partner.`,s:0,d:{trust:-2,conf:2,health:-5},
    after:`The team learns about it from Ochoa's email. Laramie's interface configuration alone takes nine days nobody had planned.`,
    why:`Saying yes to scope changes in the room skips impact analysis and the team's input. Goodwill doesn't add capacity.`},
   {t:`Tell him the first wave is fixed by contract and can't change, so Laramie stays in wave two.`,s:1,d:{trust:0,conf:-2,health:1},
    after:`It's accurate, but Ochoa hears no instead of let's look.`,
    why:`Protecting the baseline is right, but the better move is to analyze and present the tradeoff, so the customer decides with real information.`},
   {t:`Say Sam will ask Grant, since Grant owns the commercial terms of the Cascade relationship.`,s:0,d:{trust:0,conf:-1,health:0},
    after:`Grant says yes before Sam can get a word in.`,
    why:`A scope change on the project goes through the project's change process. Sending it to sales invites a commitment without analysis.`}
  ]}
 ],
 drills:[
  {after:`f7s10`, title:`Velocity forecast`,
   setup:[`The team completed 31, 27, 34, and 28 story points in its last four sprints. Sprints are two weeks.`,`There are 96 points of must have work and 168 points in the full release backlog.`],
   table:[[`Sprint`,`Points completed`],[`1`,`31`],[`2`,`27`],[`3`,`34`],[`4`,`28`]],
   fields:[{label:`Average velocity (points per sprint)`,answer:30,tol:0},{label:`Sprints to finish the must haves (round up)`,answer:4,tol:0},{label:`Sprints to finish the full backlog (round up)`,answer:6,tol:0}],
   solution:[`Average velocity = (31 + 27 + 34 + 28) / 4 = 120 / 4 = 30 points per sprint.`,`Must haves: 96 / 30 = 3.2 sprints, which rounds up to 4 sprints, or about 8 weeks.`,`Full backlog: 168 / 30 = 5.6 sprints, which rounds up to 6 sprints, or about 12 weeks.`,`You round up because a partial sprint still takes a whole sprint. Give the sponsor the range and say what could change it.`]}
 ],
 quiz:[
  {q:`A sales director asks the development team to move a feature to the top of the backlog because it was promised to a client. What should the project manager do?`,opts:[`Direct the sales director to the product owner, who orders the backlog`,`Reorder the backlog, since commitments to clients must come first`,`Ask the team to vote on whether the feature should move to the top`,`Escalate the request to the sponsor for a decision on the priority`],a:0,why:`The product owner owns backlog order. The PM connects stakeholders to the product owner rather than overriding the role.`,task:`R3`,domain:`Process`},
  {q:`A team is planning the first release of a new product with many uncertain user needs. Which approach best supports value-based delivery?`,opts:[`Build every requested feature before the first release to the users`,`Release a minimum viable product and gather feedback from real users`,`Complete a detailed design for all features before any development`,`Deliver the easiest features first to show progress to the sponsor`],a:1,why:`An MVP tests key assumptions with real users early, which is the heart of value-based delivery under uncertainty.`,task:`R3`,domain:`Process`},
  {q:`Which statement best describes the difference between the definition of done and acceptance criteria?`,opts:[`They're the same thing and the terms can be used interchangeably`,`Acceptance criteria are set by the team, done is set by the sponsor`,`Done applies to every item, acceptance criteria apply to one item`,`Done is written after testing, acceptance criteria before planning`],a:2,why:`The definition of done is the team's standard for all items. Acceptance criteria are specific conditions for a single item, usually from the product owner.`,task:`R7`,domain:`Process`},
  {q:`During a sprint review, a customer finds a serious defect. What should the project manager do first?`,opts:[`Explain that the defect was likely caused by the demo test data`,`End the review so the team can investigate without the customer`,`Ask a developer to fix the defect live so the customer sees it work`,`Acknowledge the defect openly, log it, and continue the review`],a:3,why:`Transparency and logging come first. The review exists to surface problems, and investigating properly follows.`,task:`R7`,domain:`Process`},
  {q:`A product owner wants to add a new item in the middle of a sprint. The team says it would put the sprint goal at risk. What is the best response?`,opts:[`Add the item to the product backlog for the next sprint`,`Add it to the current sprint, since the product owner decides`,`Cancel the sprint and start a new one including the new item`,`Ask the team to work extra hours so both items can be done`],a:0,why:`Protect the sprint goal. The product owner can reorder the product backlog so the item is first in the next sprint.`,task:`R2`,domain:`Process`},
  {q:`A team has completed 22, 26, 24, and 28 story points in four sprints. 125 points remain. About how many sprints remain?`,opts:[`Five sprints, based on the team's average velocity`,`Six sprints, based on the team's average velocity`,`Four and a half sprints, based on the best sprint`,`Seven sprints, based on the team's slowest sprint`],a:0,why:`Average velocity is (22 + 26 + 24 + 28) / 4 = 25 points. 125 / 25 = 5 sprints. Forecast from the average, not the best or worst sprint.`,task:`R3`,domain:`Process`},
  {q:`Two developers blame each other's code during a retrospective. What should the facilitator do?`,opts:[`Let the argument run its course so the conflict fully surfaces`,`End the meeting and meet with each developer privately later`,`Refocus the team on how the process let the problem through`,`Ask the manager of both developers to decide who was at fault`],a:2,why:`Retrospectives are blameless and focus on the process. Steering the conversation to systemic causes produces improvement actions.`,task:`P6`,domain:`People`},
  {q:`A team keeps taking shortcuts to meet sprint deadlines, building up technical debt. What should the project manager encourage?`,opts:[`Ignoring the debt until the product is released to production`,`Asking developers to fix the debt on weekends and evenings`,`Scheduling one large cleanup project after the final release`,`Making the debt visible and paying it down every iteration`],a:3,why:`Visible, steadily repaid debt keeps quality built in without stopping delivery.`,task:`R7`,domain:`Process`},
  {q:`Before an important demo, a key customer stakeholder asks what to expect. What is the best response?`,opts:[`Set honest expectations about the product's maturity and format`,`Promise a polished experience to keep the stakeholder confident`,`Refer the stakeholder to the sales lead who owns the relationship`,`Send the full product backlog so the stakeholder can see the scope`],a:0,why:`Aligning expectations honestly before an event lets stakeholders judge it against the right standard.`,task:`P5`,domain:`People`},
  {q:`A project manager wants to compare the velocity of two agile teams to decide which is more productive. What is the problem with this approach?`,opts:[`Velocity can only be measured after a full release is delivered`,`Velocity depends on each team's own estimating and isn't comparable`,`Velocity measures quality, not the amount of work that was completed`,`Velocity is only valid for teams using two week iterations or longer`],a:1,why:`Story points are relative to each team. Velocity is a planning tool for one team, not a cross-team productivity score.`,task:`R3`,domain:`Process`},
  {q:`A safety defect was found in a customer demo. An executive asks the PM not to mention it in writing until it's fixed. What should the PM do?`,opts:[`Follow the executive's guidance, since the fix is already underway`,`Tell the customer verbally and send nothing until the fix is ready`,`Send the customer a written summary of the defect and next steps`,`Ask the sponsor to decide whether to tell the customer about it`],a:2,why:`Honest, timely, written communication about safety issues is required. Hiding it to protect appearances violates both the PMI mindset and the Code of Ethics.`,task:`P6`,domain:`People`},
  {q:`A customer asks to add a site to the first release during a demo. The request seems reasonable. What should the project manager do?`,opts:[`Agree immediately, because the customer relationship is strong`,`Decline, since the first release scope is fixed in the contract`,`Refer the customer to sales, who owns the commercial relationship`,`Analyze the impact and take it through the change control process`],a:3,why:`Even good requests need impact analysis and an informed decision through change control.`,task:`P5`,domain:`People`},
  {q:`After a defect reached a customer, the team found the root cause was a missing check. What is the best long-term fix?`,opts:[`Build an automated check into the definition of done for all work`,`Add a manual reviewer to inspect every output before release`,`Retrain the team on the importance of careful development work`,`Add a warning in the product telling users to verify the output`],a:0,why:`Prevention built into the process beats inspection or warnings. Adding it to the definition of done protects every future item.`,task:`R7`,domain:`Process`},
  {q:`Which technique sorts backlog items into must have, should have, could have, and won't have this time?`,opts:[`Kano model`,`MoSCoW`,`Weighted shortest job first`,`Planning poker`],a:1,why:`MoSCoW is the quick prioritization technique that uses those four categories.`,task:`R2`,domain:`Process`},
  {q:`A team member says several stories are "basically done" except for testing the day before a review. What should the project manager do?`,opts:[`Count them as done and schedule the testing for the next sprint`,`Postpone the review until all of the stories are fully tested`,`Hold every story to the team's definition of done before the review`,`Ask the product owner to accept the stories without testing them`],a:2,why:`Only items meeting the definition of done are shown as complete. Untested work isn't done.`,task:`R7`,domain:`Process`}
 ],
 closing:(s,all,G)=>[
  `Friday evening, Sam and Maria walked out of the building together. The light over the Front Range had gone orange.`,
  `<span class="said" data-who="Maria">"You know what I was looking for on Thursday?"</span> Maria said. <span class="said" data-who="Maria">"Not whether it would fail. Everything fails. I was watching what you'd do when it did."</span>`,
  (G.hiddefect?`She didn't mention the eight days. She didn't need to. Sam had been carrying them all week.`:`<span class="said" data-who="Maria">"You told us the same day,"</span> she added. <span class="said" data-who="Maria">"In writing. I took that to our safety committee and they relaxed for the first time since we signed."</span>`),
  `At home, Dana asked how the demo went. <span class="said" data-who="Sam">"The first one was a disaster,"</span> he said. <span class="said" data-who="Sam">"The second one was the best day I've had at Halcyon."</span> She said that sounded about right for anything worth doing.`,
  `Monday morning, Joan Pruitt from procurement was waiting outside his office with a thick folder and a look Sam would come to recognize. <span class="said" data-who="Joan">"LabelForge sent their final invoice,"</span> she said. <span class="said" data-who="Joan">"And Cascade wants to change the contract. We should talk."</span>`
 ],
 episode:{src:`audio/full-ch07.mp3`, len:`about 35 minutes`},
 next:`The Contract`
});
