// Full Course, Chapter 8. See full/BIBLE.md for the format.
(window.HALCYON_FULL=window.HALCYON_FULL||[]).push({
 num:8, part:`Part One: The Cascade Launch`, title:`The Contract`, weeks:`Weeks 9 to 11`,
 tasks:[`R5`,`B3`,`B2`],
 cast:[[`Joan Pruitt`,`Halcyon procurement lead. Contract precise. Secretly loves a good negotiation.`]],
 opening:[
  `Joan Pruitt's office was the only one at Halcyon with a paper filing cabinet. It was gray, it was dented, and it held a printed copy of every contract the company had signed since its seed round, each one tabbed in a color code nobody else understood.`,
  `<span class="said" data-who="Joan">"People think procurement is paperwork,"</span> she said, sliding the LabelForge folder across the desk. <span class="said" data-who="Joan">"Procurement is memory. Everybody forgets what they promised. The contract doesn't."</span>`,
  `LabelForge's final invoice was for the full fixed price, $186,000, as if the first batch hadn't arrived three weeks late and the third batch hadn't needed forty percent of its labels redone by Cascade's nurses. Joan had already highlighted section 7.2 in yellow. Sam didn't know what 7.2 said yet. He could tell from her face that it said something.`,
  `On top of that, Cascade wanted to change the deal. Their pharmacy committee had seen the grounding check and wanted discharge instructions moved from phase two into the current contract. Grant had replied to that email with three exclamation points. Joan had forwarded it to Sam with none.`,
  `And IronPeak was offering to expand the GPU cluster for the second wave under a new kind of contract Hal Brennan called "fixed price with upside." Joan called it something else.`,
  `That night Sam told Dana he was learning contract law. She asked whether that was a promotion or a punishment. He said he'd let her know.`
 ],
 lesson:{
  title:`Procurement, contracts, and change`,
  sections:[
   {h:`The procurement process`,
    body:[`Procurement runs in three parts. Plan it: decide what to buy, whether to make or buy, which contract type to use, and how you'll pick a seller. Conduct it: get responses, evaluate them, negotiate, and award. Control it: manage the relationship, the changes, the payments, and the claims, and close it out.`,
     `The documents have names you need to know. A statement of work describes what the seller will deliver. A request for information gathers general market knowledge. A request for quotation asks for price on a well defined item. A request for proposal asks sellers to propose a solution and a price when the approach matters. A bidder conference gives every prospective seller the same information at the same time, which keeps the process fair. Source selection criteria, decided before you see proposals, keep the evaluation objective.`,
     `A make-or-buy analysis compares the full cost and risk of doing work in house with buying it. It includes more than price: skills, control, intellectual property, ongoing maintenance, and how long you'll need it.`],
    terms:[[`Statement of work`,`The description of what the seller must deliver.`],[`RFI, RFQ, RFP`,`Request for information, quotation, proposal. Use RFQ for price on known items, RFP when the solution matters.`],[`Bidder conference`,`A meeting where all prospective sellers get the same information.`]],
    exam:`If a question describes a seller getting information others didn't, the answer is about fairness, usually a bidder conference or a written addendum to all bidders.`},
   {h:`Contract types and who carries the risk`,
    body:[`Firm fixed price puts the cost risk on the seller. Use it when scope is well defined. Fixed price incentive fee is fixed price with a sharing formula: if the seller comes in under target cost they earn more fee, if over they earn less, up to a ceiling price the buyer will never exceed. Fixed price with economic price adjustment covers long contracts where inflation or currency moves matter.`,
     `Cost reimbursable contracts put more risk on the buyer. Cost plus fixed fee pays actual allowable costs plus a fee fixed as a dollar amount based on the estimated cost. Cost plus incentive fee pays costs plus a fee that moves with a sharing ratio, like the fixed price version but without a ceiling. Cost plus award fee pays a fee based on the buyer's subjective judgment of performance. Use cost reimbursable contracts when scope is uncertain and you need the seller to start before it's defined.`,
     `Time and materials pays an hourly rate plus materials. It's quick to set up and useful for staff augmentation or small uncertain work, but the buyer carries the risk of the hours growing, so add a not-to-exceed limit.`],
    terms:[[`FFP`,`Firm fixed price. Seller carries cost risk.`],[`FPIF`,`Fixed price incentive fee. Shared savings or overruns, capped by a ceiling price.`],[`CPFF`,`Cost plus fixed fee. Buyer pays costs plus a fixed dollar fee.`],[`T&M`,`Time and materials. Hourly rates; add a not-to-exceed cap.`]],
    exam:`Know the risk spectrum. Buyer risk is lowest with firm fixed price and highest with cost plus percentage of cost, which most organizations avoid. Also know that the contract type should match how well the scope is defined: the clearer the scope, the more the risk can sit with the seller, and the less clear it is, the more the buyer has to carry.`},
   {h:`Incentive math`,
    body:[`In a fixed price incentive fee contract you have a target cost, a target fee, a target price (cost plus fee), a share ratio, and a ceiling price. The share ratio is written buyer over seller. With 70/30, the seller keeps 30 percent of any underrun and absorbs 30 percent of any overrun through a lower fee.`,
     `To compute the final fee: find the difference between target and actual cost, multiply by the seller's share, and add it to the target fee for an underrun or subtract it for an overrun. Final price is actual cost plus final fee, but never more than the ceiling price.`,
     `The point of total assumption is the cost at which the seller starts carrying every additional dollar, because the ceiling has been reached. The formula is target cost plus the difference between the ceiling price and target price, divided by the buyer's share. Above that point, the seller's fee shrinks dollar for dollar.`],
    terms:[[`Share ratio`,`Buyer and seller split of savings or overruns, written buyer over seller.`],[`Point of total assumption`,`PTA = target cost + (ceiling price minus target price) / buyer share ratio.`]],
    exam:`Read the share ratio carefully. The first number is the buyer. Most calculation errors on the exam come from swapping it.`},
   {h:`Claims, changes, and compliance`,
    body:[`A claim is a disputed change, often about delays, quality, or scope. Claims administration means documenting the facts, following the dispute process in the contract, and preferring negotiation over litigation. Keep records as you go. Memory fades and contracts don't.`,
     `Closing a procurement means confirming every deliverable was accepted, settling open claims, making final payment, and archiving the records. A procurement audit then looks back at how the whole process went, from planning to closure, so the organization buys better next time. Lessons from a difficult vendor belong in that audit, not in a hallway story.`,
     `Integrated change control applies to procurement too. Changes to a contract go through the change control process defined in the plan. A change control board reviews significant changes and approves or rejects them. The project manager analyzes impact and facilitates, but doesn't approve changes beyond their authority. Only the procurement or contracting authority can change the contract itself.`,
     `Compliance obligations flow down. If your contract with a hospital requires a business associate agreement under HIPAA, any subcontractor that touches patient data needs the same protections. Privity of contract matters too: you have a contract with your seller, not your seller's subcontractors, so you direct them through your seller.`],
    terms:[[`Claim`,`A disputed request for compensation or change under a contract.`],[`Change control board`,`The group that reviews and approves or rejects changes.`],[`Flow-down`,`Contract obligations that must be passed to subcontractors.`]],
    exam:`When a vendor is late, the first move is almost always to review the contract terms and talk with the vendor, not to terminate or withhold payment on your own.`}
  ],
  video:[`BsIJJs0X_7k`,`PMP Exam CONTRACT Types SIMPLIFIED: FP, CR, T&M`,`Praizion`,`13:41`]
 },
 scenes:[
 {id:`f8s1`, domain:`Process`, task:`R5`, title:`The full invoice`,
  text:(s,all,G)=>[`Joan slides the contract across, tabbed in yellow.`,`<prop type="doc" title="LabelForge master services agreement, section 7.2">Late delivery. For each full week a batch is delivered after its scheduled date, the price for that batch drops by one and a half percent, up to a maximum of ten percent of the contract price.</prop>`,`The first batch was three weeks late. LabelForge billed the full $186,000 anyway.`,`Grant says pay it and move on, Cascade is happy. Lena says don't pay a cent until they redo the third batch.`],
  opts:[
   {t:`Pay the undisputed amount, document the delay, and raise the rest under the contract.`,s:3,best:true,d:{trust:2,conf:3,health:2},
    after:`Joan pays the undisputed portion on time and sends a written notice citing 7.2 with the delivery dates attached. LabelForge's account manager calls within the hour, which Joan says is the fastest she's ever seen them move.`,
    why:`Follow the contract: pay what's owed, document the facts, and handle the disputed part through the contract's claims process. That protects your rights and the relationship.`},
   {t:`Pay the full invoice to keep the vendor relationship strong for future work with Halcyon.`,s:0,d:{trust:0,conf:0,health:-2},
    after:`LabelForge thanks them. Halcyon gives up about $8,000 it was entitled to, and LabelForge learns the dates don't matter.`,
    why:`Waiving contract terms without a reason weakens your position and sets a precedent. The contract exists so you don't have to rely on goodwill.`},
   {t:`Withhold the whole payment until LabelForge redoes the third batch to Cascade's standard.`,s:0,d:{trust:0,conf:-1,health:-2},
    after:`LabelForge's lawyer replies that withholding undisputed amounts is a breach. Now Halcyon is the one in trouble.`,
    why:`Withholding undisputed payment can put the buyer in breach. Use the contract's remedies, not leverage you invent.`},
   {t:`Ask Cascade whether they want Halcyon to enforce the clause, since they used the labels.`,s:1,d:{trust:0,conf:-1,health:0},
    after:`Ochoa politely points out that Halcyon's vendor contract isn't Cascade's business.`,
    why:`The customer can inform the quality picture, but Halcyon holds the contract with LabelForge. Privity of contract means the decision is Halcyon's.`}
  ]},
 {id:`f8s2`, domain:`Process`, task:`R5`, title:`Before the negotiation`,
  text:(s,all,G)=>[`LabelForge asks for a call to "resolve the invoice." Joan wants an hour with Sam first.`,`<span class="said" data-who="Joan">"Tell me what we actually want,"</span> she says. <span class="said" data-who="Joan">"Not what we're mad about. What we want."</span>`],
  opts:[
   {t:`Work out Halcyon's interests, LabelForge's likely interests, and our walk-away option.`,s:3,best:true,d:{trust:2,conf:1,health:3},
    after:`They write it out. Halcyon wants clean labels for wave two more than money. LabelForge probably wants a reference and repeat business. The walk-away is another vendor, six weeks out. Joan circles the overlap.`,
    why:`Good negotiation preparation separates interests from positions and knows your best alternative. It points you toward a deal both sides can live with.`},
   {t:`Set a target of the full ten percent credit and decide not to accept anything less on the call.`,s:1,d:{trust:0,conf:0,health:0},
    after:`It's a clear goal. It also leaves no room for what Halcyon actually needs, which is better labels next time.`,
    why:`Knowing your number is useful, but a fixed position ignores interests. You may win the money and lose what matters.`},
   {t:`Let Grant lead the call, since he negotiates commercial terms every day with customers.`,s:0,d:{trust:-1,conf:0,health:-1},
    after:`Grant is great at selling. He's never bought anything, and he concedes the credit in the first five minutes to be liked.`,
    why:`Vendor negotiations belong with the procurement authority, supported by the PM. Sales skill isn't the same as buying skill.`},
   {t:`Skip preparation and listen first, since LabelForge called the meeting and should go first.`,s:0,d:{trust:0,conf:0,health:-1},
    after:`LabelForge frames the whole discussion around their costs. Halcyon spends the call reacting.`,
    why:`Listening matters, but walking in without knowing your interests and alternatives lets the other side set the frame.`}
  ]},
 {id:`f8s3`, domain:`Process`, task:`R5`, title:`At the table`,
  text:(s,all,G)=>[`LabelForge's CEO joins the call. She opens with a five percent credit and an apology for the third batch, then says they're losing money on the contract.`,`Joan looks at Sam. It's his project. She's let him take this one.`],
  opts:[
   {t:`Offer seven percent plus free relabeling of batch three by their nurse team before wave two.`,s:3,best:true,d:{trust:1,conf:3,health:5},
    after:`The CEO pauses, then agrees, because relabeling costs her less than cash and keeps Halcyon as a reference. Joan writes it up as a contract amendment before the call ends. Afterward she says, <span class="said" data-who="Joan">"That's the one I would have asked for."</span>`,
    why:`A strong negotiated outcome addresses both sides' interests. Trading some of the credit for work Halcyon actually needs is a win-win, and it's documented in the contract.`},
   {t:`Accept the five percent and the apology, since the vendor is already losing money on it.`,s:1,d:{trust:0,conf:0,health:0},
    after:`It's fair but leaves Halcyon with bad labels going into wave two.`,
    why:`Reasonable, but it settles the money and ignores Halcyon's real interest, which is label quality for the next phase.`},
   {t:`Insist on the full ten percent the contract allows and end the call if they won't agree.`,s:0,d:{trust:0,conf:-1,health:-2},flag:`squeezedlabelforge`,
    after:`LabelForge agrees, then assigns its weakest annotators to the remaining work. You get what you pay for.`,
    why:`Hard bargaining can win the clause and damage the relationship you still depend on. Win-lose outcomes tend to cost you later.`},
   {t:`Tell them Halcyon will consider it and get back to them after talking with Elena and Grant.`,s:0,d:{trust:0,conf:-1,health:-1},
    after:`It takes two more weeks of email. The offer gets worse, not better.`,
    why:`If you have the authority and a good deal is on the table, close it. Deferring without a reason just loses momentum.`}
  ]},
 {id:`f8s4`, domain:`Business Environment`, task:`B3`, title:`Cascade's change`,
  text:(s,all,G)=>[`Cascade formally asks to move discharge instructions from phase two into the current contract, for the second wave. Ochoa's note is friendly and firm.`,`Grant replies to everyone before Sam is out of his first meeting.`,`<prop type="email" from="Grant Mercer" to="Dr. Raymond Ochoa; Sam Okafor; Elena Vasquez" time="8:07 AM" subject="Re: Discharge instructions in wave two"><span class="said" data-who="Grant">Absolutely doable!!!</span></prop>`,...(G.paddedestimates?[`Sam opens the estimates to size it and stops. Every number in the plan carries padding he added back in week two, and nobody can tell how much is real work and how much is cushion. The impact analysis will take twice as long.`]:[])],
  opts:[
   {t:`Log it as a change request, analyze the impact, and take it to the change control board.`,s:3,best:true,d:{trust:2,conf:3,health:4},
    after:`Sam sends a short note to everyone on the thread: received, logged as CR-014, impact analysis by Friday, decision at the next board meeting. Grant calls him, annoyed. Ochoa replies, <span class="said" data-who="Ochoa">"Perfect, that's how we'd do it."</span>`,
    why:`Every change goes through integrated change control: log it, assess impact on scope, schedule, cost, quality, and risk, then a decision by whoever has the authority. Grant's reply doesn't change the process.`},
   {t:`Agree with Grant's reply and ask the team to plan discharge instructions into wave two.`,s:0,d:{trust:-4,conf:2,health:-6},
    after:`The team estimates it at six weeks. Wave two was four. Nobody asked them first.`,
    why:`Accepting a change without impact analysis or approval is how projects fail. A salesperson's reply-all isn't change control.`},
   {t:`Reply that it's a phase two item and can't be considered until the current contract closes.`,s:1,d:{trust:0,conf:-3,health:1},
    after:`True to the plan, but it shuts down a reasonable request without looking at it.`,
    why:`Protecting scope is good, but changes deserve analysis. The customer should get an informed answer, not a reflexive no.`},
   {t:`Ask Elena to call Ochoa and sort it out executive to executive before it becomes an issue.`,s:0,d:{trust:0,conf:-1,health:0},
    after:`Elena agrees in principle on the call, which is worse than Grant's email because she's the CEO.`,
    why:`Executive conversations don't replace impact analysis. The change process gives the decision makers real information first.`}
  ]},
 {id:`f8s5`, domain:`Business Environment`, task:`B3`, title:`Who decides`,
  text:(s,all,G)=>[`The impact analysis is clear: adding discharge instructions to wave two means six more weeks or dropping two must haves, plus $140,000 of work.`,`Grant asks Sam to approve it as project manager and sort out the money later.`],
  opts:[
   {t:`Take it to the change board named in the plan, with the options, and let it decide.`,s:3,best:true,d:{trust:1,conf:4,health:3},
    after:`The board is Elena, Ochoa, Maria, and Lena. They pick a middle path: discharge instructions as a separate statement of work starting the week after wave two, at a price. Grant gets a signed order. Sam gets his plan back.`,
    why:`The PM facilitates and analyzes, but approval belongs to the authority defined in the change management plan. A change that affects contract value goes to the board and the contracting authority.`},
   {t:`Approve it, since the PM is responsible for the project and the analysis has been done.`,s:0,d:{trust:0,conf:-2,health:-4},
    after:`Joan finds out and points out that Sam has no authority to change contract value. The approval is void.`,
    why:`A PM can only approve changes within the authority the charter and change plan grant. Contract value changes need the contracting authority.`},
   {t:`Reject it, since the impact on the schedule and budget is clearly too large to absorb.`,s:1,d:{trust:0,conf:-2,health:2},
    after:`The analysis supports caution, but it wasn't Sam's call to reject a change this size either.`,
    why:`Your analysis informs the decision. The decision on a change of this size still goes to the board.`},
   {t:`Ask Cascade to decide, since they're paying for it and know what they want most.`,s:0,d:{trust:0,conf:-1,health:-1},
    after:`Ochoa asks how Cascade can decide Halcyon's schedule. It's a fair question.`,
    why:`The customer is a key voice and often sits on the board, but neither party decides alone. The defined board does.`}
  ]},
 {id:`f8s6`, domain:`Process`, task:`R5`, title:`Make or buy`,
  text:(s,all,G)=>[`Discharge instructions need dictation. Priya says the team can build a speech component for about $90,000, then about $2,000 a month to run. A vendor licenses one for $6,000 a month with no build cost.`,`Elena wants to know which is cheaper. Priya wants to build it because it's interesting.`],
  opts:[
   {t:`Run a make-or-buy that compares breakeven, skills, control, and how long we'll need it.`,s:3,best:true,d:{trust:2,conf:3,health:3},
    after:`Breakeven is about twenty-two and a half months. Halcyon plans to replace the component within eighteen when its own model is ready. Buying wins, and Priya agrees once she sees the timeline. Sam gives her the vendor integration to lead.`,
    why:`Make-or-buy looks at total cost over the period you'll need it, plus risk, skills, and control. Breakeven alone doesn't decide it, but it frames it.`},
   {t:`Build it, since owning the component gives Halcyon full control and no monthly license fee.`,s:0,d:{trust:1,conf:0,health:-3},
    after:`It takes the team two sprints longer than estimated, and it's replaced fourteen months later.`,
    why:`Control has value, but this decision ignores how long you'll use it. You pay the build cost and never reach breakeven.`},
   {t:`Buy it, since buying is always faster and lower risk than building new technology yourself.`,s:1,d:{trust:0,conf:1,health:1},
    after:`It turns out to be the right answer, for the wrong reason.`,
    why:`Buying isn't always lower risk. The right call came from analysis of cost over time, not a rule of thumb.`},
   {t:`Ask the vendor for a discount first, then decide based on whichever price ends up lower.`,s:0,d:{trust:0,conf:0,health:0},
    after:`The vendor offers five percent off. It doesn't change the math or the question.`,
    why:`Price is one input. The analysis needs total cost over the useful life, plus nonfinancial factors.`}
  ]},
 {id:`f8s7`, domain:`Process`, task:`R5`, title:`The integration contract`,
  text:(s,all,G)=>[`The dictation vendor offers to help integrate the component into the agents. Nobody knows yet how much work it is. Priya guesses two to six weeks.`,`Joan asks Sam what contract type he wants for the integration help.`],
  opts:[
   {t:`Time and materials with a not-to-exceed cap, revisited once the scope is much clearer.`,s:3,best:true,d:{trust:1,conf:1,health:3},
    after:`Joan writes it with a cap at five weeks of effort and a checkpoint after two. At the checkpoint, the scope is clear enough to convert the rest to fixed price.`,
    why:`When scope is uncertain and you need to start, time and materials is quick to set up. The cap protects the buyer, and you can move to fixed price once you know more.`},
   {t:`Firm fixed price, since it moves all of the cost risk onto the vendor from the start.`,s:1,d:{trust:0,conf:0,health:-1},
    after:`The vendor prices in every unknown and quotes eight weeks of effort.`,
    why:`Fixed price fits defined scope. With this much uncertainty, the seller adds a large risk premium, and you pay for it.`},
   {t:`Cost plus a percentage of cost, so the vendor is motivated to start the work right away.`,s:0,d:{trust:0,conf:0,health:-3},
    after:`Joan refuses to even draft it. The more the vendor spends, the more they earn.`,
    why:`Cost plus percentage of cost rewards spending and is avoided by most organizations. It gives the buyer the worst risk position.`},
   {t:`No contract; let the vendor help informally as part of the license relationship for now.`,s:0,d:{trust:0,conf:0,health:-2},
    after:`The vendor's engineer helps for a week, then gets pulled to a paying client mid-sprint.`,
    why:`Work without a contract has no defined obligations or remedies. Even small engagements need terms.`}
  ]},
 {id:`f8s8`, domain:`Process`, task:`R5`, title:`IronPeak's offer`,
  text:(s,all,G)=>[`IronPeak's expansion for wave two comes as a fixed price incentive fee contract: target cost $400,000, target fee $40,000, a 70/30 share ratio, and a $480,000 ceiling price.`,`Hal Brennan says it's the "fixed price with upside" he promised. Joan wants Sam to understand exactly what upside, and for whom.`],
  opts:[
   {t:`Work through the incentive math with Joan, including the point of total assumption.`,s:3,best:true,d:{trust:1,conf:2,health:3},
    after:`They work it on Joan's whiteboard. If IronPeak comes in at $380,000, they earn $46,000. Above about $457,000 in cost, IronPeak carries every extra dollar. Joan approves of the ceiling. Sam understands exactly what Halcyon is buying.`,
    why:`Understanding the incentive structure tells you how the seller is motivated and where your exposure stops. The point of total assumption is where the seller takes all remaining overrun.`},
   {t:`Sign it, since any fixed price contract protects Halcyon from cost overruns automatically.`,s:0,d:{trust:0,conf:0,health:-1},
    after:`Halcyon signs without realizing it shares overruns up to the ceiling.`,
    why:`An incentive fee contract shares overruns until the ceiling price. Fixed price doesn't mean fixed total exposure at the target.`},
   {t:`Ask IronPeak to switch to firm fixed price at the target price so there's no math involved.`,s:1,d:{trust:0,conf:0,health:0},
    after:`IronPeak counters with a firm fixed price of $470,000 to cover its risk.`,
    why:`Simpler isn't free. Asking a seller to carry all the risk usually raises the price. The incentive structure may be the better deal.`},
   {t:`Ask Grant whether the incentive terms are standard, since he deals with vendors on renewals.`,s:0,d:{trust:0,conf:0,health:-1},
    after:`Grant says they look fine. He hasn't read them.`,
    why:`Contract analysis belongs with procurement and the PM. Understand the terms you're accepting.`}
  ]},
 {id:`f8s9`, domain:`Business Environment`, task:`B2`, title:`Kraków and the data`,
  text:(s,all,G)=>[`Joan's contract review turns up something nobody noticed. Halcyon's agreement with Cascade requires any subcontractor that touches patient data to sign a business associate agreement. The Kraków team has been testing with production-like records.`,`Tomasz says the records were "mostly anonymous."`],
  opts:[
   {t:`Stop Kraków's access to real-looking data, involve compliance, and check the BAA chain.`,s:3,best:true,d:{trust:1,conf:4,health:-1},
    after:`Halcyon's compliance lead confirms the records were synthetic but too close to real formats to be sure. Kraków moves to fully de-identified test data and signs a subcontractor agreement. Ochoa is told in writing. He thanks them for catching it.`,
    why:`Compliance obligations flow down to subcontractors. When you find a possible gap, contain it, involve the compliance experts, verify, and disclose as required.`},
   {t:`Have Tomasz confirm in writing that the data was anonymous and keep testing as before.`,s:0,d:{trust:0,conf:-3,health:1},
    after:`It produces a piece of paper and doesn't answer the question.`,
    why:`A self-attestation from the party at risk isn't a compliance review. Involve the people who can actually determine it.`},
   {t:`Move all testing with clinical data back to Denver so Kraków never touches it again.`,s:1,d:{trust:-3,conf:1,health:-3},
    after:`It solves the exposure but triples Denver's testing load, and Tomasz reads it as distrust.`,
    why:`Containing the risk is right, but the better fix keeps the team productive through de-identified data and proper agreements.`},
   {t:`Raise it at the next steering meeting, since nothing has actually gone wrong with the data.`,s:0,d:{trust:0,conf:-2,health:0},
    after:`The next steering meeting is in two weeks. The testing continues until then.`,
    why:`A potential compliance gap involving patient data needs action now, not at the next scheduled meeting.`}
  ]},
 {id:`f8s10`, domain:`Business Environment`, task:`B2`, title:`The training records`,
  text:(s,all,G)=>[`Cascade's compliance office asks for evidence that everyone on the project completed HIPAA training. Denver's records are clean. Two of the Kraków engineers have no record at all.`,`Grant suggests sending Denver's records and "following up" on Kraków.`],
  opts:[
   {t:`Send what exists, state the Kraków gap and the fix plainly, and get it closed this week.`,s:3,best:true,d:{trust:1,conf:4,health:1},
    after:`The two engineers complete training by Thursday. Cascade's compliance officer notes the gap as found and closed by the vendor. That's the best entry you can get in an audit.`,
    why:`Compliance requires accurate records and honest disclosure. Reporting a gap with its remediation builds more trust than an incomplete picture that looks clean.`},
   {t:`Send Denver's records now and send Kraków's once the two engineers finish their training.`,s:1,d:{trust:0,conf:1,health:0},
    after:`Cascade asks why the list is short. The answer arrives a week late.`,
    why:`Partial records without stating the gap look like concealment, even when they aren't. Say what's missing and when it will be fixed.`},
   {t:`Ask the two engineers to complete training today and backdate the records to the project start.`,s:0,d:{trust:-3,conf:-8,health:0},
    after:`Joan refuses, and tells Sam she's glad she misheard him.`,
    why:`Falsifying records violates the PMI Code of Ethics and compliance law. Honesty is not negotiable.`},
   {t:`Remove the two engineers from the project so the records Cascade sees are complete.`,s:0,d:{trust:-5,conf:-1,health:-2},
    after:`Kraków loses two good engineers for a training gap that takes an hour to fix.`,
    why:`Hiding a gap by reshuffling people is still hiding it, and it punishes the team for a process failure.`}
  ]},
 {id:`f8s11`, domain:`Business Environment`, task:`B5`, title:`The rumor`,
  text:(s,all,G)=>[`Hal Brennan mentions over coffee that LabelForge is "having a rough quarter," and two of their nurse annotators have left. Wave two depends on their relabeling.`,`It's a rumor. It's also a risk.`],
  opts:[
   {t:`Log it as a risk, assess it, and plan a response like holding copies of all labeled data.`,s:3,best:true,d:{trust:1,conf:2,health:4},
    after:`The risk register gets a new entry with an owner. Joan confirms Halcyon's right to the labeled data and has it delivered in batches, not at the end. Priya identifies a second labeling vendor as a fallback. The cost is a few phone calls.`,
    why:`A credible rumor is a risk to be assessed, not ignored or acted on in panic. A response that protects your work products and sets up a fallback reduces impact at low cost.`},
   {t:`Ignore it until LabelForge actually misses something, since it's only coffee talk.`,s:0,d:{trust:0,conf:0,health:-3},
    after:`It's coffee talk until it isn't.`,
    why:`Risks are uncertain by definition. Waiting until it happens turns a manageable risk into an issue.`},
   {t:`Move all remaining labeling to a second vendor now to remove the dependency on LabelForge.`,s:0,d:{trust:0,conf:-1,health:-3},
    after:`Halcyon breaks a contract it was happy with and pays a new vendor to ramp up on a rumor.`,
    why:`Avoiding a risk entirely can cost more than the risk. Assess probability and impact before choosing a response.`},
   {t:`Call LabelForge's CEO and ask directly whether the company is in financial trouble.`,s:1,d:{trust:0,conf:0,health:1},
    after:`She says everything is fine. That's what anyone would say.`,
    why:`Talking to the vendor is reasonable, but it doesn't replace a planned response. Assess and prepare regardless of the answer.`}
  ]},
 {id:`f8s12`, domain:`People`, task:`P4`, title:`Go or no-go`,
  text:(s,all,G)=>[`Week eleven. Go-live for the first three hospitals is in three weeks. Elena asks Sam how they'll decide whether to go.`,`<span class="said" data-who="Grant">"Gut feel,"</span> Grant says, only half joking. Ochoa, on the call, does not laugh.`],
  opts:[
   {t:`Agree measurable go/no-go criteria in writing with Cascade and Halcyon leads this week.`,s:3,best:true,d:{trust:2,conf:6,health:4},
    after:`They land on eight criteria: grounding check pass rate, open safety defects, training completion per unit, rollback tested, support staffed, and three others. Ochoa signs. Maria adds one. Elena says it's the first time a launch decision has felt like a decision.`,
    why:`Engage stakeholders early to agree objective criteria for major decisions. Written criteria agreed in advance make the go/no-go call about facts, not pressure.`},
   {t:`Draft the criteria internally at Halcyon and share them with Cascade the week of go-live.`,s:1,d:{trust:0,conf:-1,health:2},
    after:`Cascade has different priorities and the criteria get renegotiated during the most stressful week.`,
    why:`Criteria the customer didn't help write aren't really agreed. Involve them early.`},
   {t:`Let Elena make the call the week before, since she's the sponsor and carries the risk.`,s:0,d:{trust:0,conf:-2,health:-1},
    after:`Elena makes it under board pressure, which is exactly what everyone wanted to avoid.`,
    why:`The sponsor decides, but against criteria agreed in advance. Leaving it to judgment under pressure invites a bad call.`},
   {t:`Plan to go live on the date regardless, since it's in the contract and moving it is costly.`,s:0,d:{trust:-2,conf:-3,health:-3},
    after:`Maria asks what happens if a safety defect is open on the day. Nobody has an answer.`,
    why:`A contract date doesn't replace readiness. Clear criteria let you either go with confidence or raise a delay with evidence.`}
  ]}
 ],
 drills:[
  {after:`f8s6`, title:`Make or buy breakeven`,
   setup:[`Build: $90,000 up front, then $2,000 per month to run.`,`Buy: $6,000 per month license, no up-front cost.`,`Halcyon expects to replace the component within 18 months.`],
   fields:[{label:`Breakeven point (months)`,answer:22.5,tol:0.1},{label:`Total cost to build over 18 months ($)`,answer:126000,tol:1},{label:`Total cost to buy over 18 months ($)`,answer:108000,tol:1}],
   solution:[`Breakeven is where the costs are equal: 90,000 + 2,000m = 6,000m, so 90,000 = 4,000m, and m = 22.5 months.`,`Build over 18 months: 90,000 + (2,000 x 18) = 90,000 + 36,000 = $126,000.`,`Buy over 18 months: 6,000 x 18 = $108,000.`,`Since the component will be replaced before breakeven, buying is cheaper. Nonfinancial factors like control and skills still matter, but they'd need to be worth $18,000 to change the answer.`]},
  {after:`f8s8`, title:`Fixed price incentive fee`,
   setup:[`IronPeak's expansion: target cost $400,000, target fee $40,000, target price $440,000, share ratio 70/30 (buyer/seller), ceiling price $480,000.`,`Assume IronPeak's actual cost comes in at $380,000.`],
   table:[[`Term`,`Value`],[`Target cost`,`$400,000`],[`Target fee`,`$40,000`],[`Target price`,`$440,000`],[`Share ratio`,`70/30`],[`Ceiling price`,`$480,000`],[`Actual cost`,`$380,000`]],
   fields:[{label:`Final fee ($)`,answer:46000,tol:1},{label:`Final price ($)`,answer:426000,tol:1},{label:`Point of total assumption ($, round to nearest dollar)`,answer:457143,tol:1}],
   solution:[`Underrun = target cost minus actual cost = 400,000 minus 380,000 = $20,000.`,`Seller's share of the underrun = 30% x 20,000 = $6,000. Final fee = 40,000 + 6,000 = $46,000.`,`Final price = actual cost + final fee = 380,000 + 46,000 = $426,000, which is under the $480,000 ceiling.`,`PTA = target cost + (ceiling price minus target price) / buyer share = 400,000 + (480,000 minus 440,000) / 0.70 = 400,000 + 57,142.86 = $457,142.86, about $457,143.`,`Above $457,143 in actual cost, IronPeak pays every extra dollar itself, because the price is stuck at the ceiling.`]}
 ],
 quiz:[
  {q:`Your team needs fifty identical rack servers with a known spec, and you just want the best price. Which document do you send to vendors?`,opts:[`Request for information`,`Request for quotation`,`Request for proposal`,`Letter of intent`],a:1,why:`You already know exactly what you want, so you only need prices. That's a request for quotation. You'd use an RFP if you wanted sellers to propose how they'd solve the problem, and an RFI if you were still figuring out what's out there.`,task:`R5`,domain:`Process`},
  {q:`A cost plus fixed fee contract has an estimated cost of $200,000 and a fee of 10 percent of the estimated cost. Actual costs are $230,000. What does the buyer pay?`,opts:[`$253,000, which is actual cost plus ten percent of actual`,`$230,000, since the fee is forfeited when costs overrun`,`$250,000, which is actual cost plus the fixed $20,000 fee`,`$220,000, which is the estimated cost plus the fixed fee`],a:2,why:`The trap here is thinking the fee moves with the cost. It doesn't. In cost plus fixed fee, the fee gets set once, from the estimate, so it's $20,000 no matter what. The buyer covers the real $230,000 of cost and adds the $20,000, for $250,000.`,task:`R5`,domain:`Process`},
  {q:`Which contract type places the most cost risk on the buyer?`,opts:[`Firm fixed price`,`Fixed price incentive fee`,`Time and materials with a cap`,`Cost plus percentage of cost`],a:3,why:`Think about what the seller wants. If their fee is a percentage of whatever they spend, every extra dollar they spend earns them more. That's why most organizations won't sign one, and why it sits at the far buyer-risk end of the spectrum.`,task:`R5`,domain:`Process`},
  {q:`A vendor is three weeks late on a deliverable. The contract includes a late delivery clause. What should the project manager do first?`,opts:[`Review the contract terms and discuss the delay with the vendor`,`Terminate the contract and begin onboarding a backup vendor`,`Withhold all payments until the vendor delivers the full scope`,`Ask the customer whether the vendor should be penalized for it`],a:0,why:`Before you do anything dramatic, find out what the contract actually says and why the vendor is late. Terminating or holding back money are real options, but only as the contract allows, and usually after you've talked.`,task:`R5`,domain:`Process`},
  {q:`During a bid process, one prospective seller asks a question by phone and receives an answer the others didn't. What should the buyer do?`,opts:[`Nothing, since the seller showed initiative by asking first`,`Share the question and answer in writing with every bidder`,`Disqualify the seller for contacting the buyer outside the process`,`Restart the procurement with a new request for proposal`],a:1,why:`One bidder now knows something the others don't, and that's not fair. You fix it by sending the question and the answer to everyone in writing. Punishing the bidder for asking, or starting over, goes much further than it needs to.`,task:`R5`,domain:`Process`},
{q:`A fixed price incentive fee contract has a target cost of $250,000, a target fee of $25,000, a buyer/seller share ratio of 75/25, and a ceiling price of $300,000. Actual cost is $230,000. What is the final price?`,opts:[`$255,000`,`$275,000`,`$260,000`,`$250,000`],a:2,why:`The seller came in $20,000 under target cost and keeps 25 percent of that, $5,000, so the fee rises to $30,000. Actual cost of $230,000 plus the $30,000 fee is $260,000, well under the ceiling.`,task:`R5`,domain:`Process`},
{q:`Same contract: target cost $250,000, target fee $25,000, share 75/25, ceiling $300,000. This time the seller's actual cost is $295,000. What does the buyer pay?`,opts:[`$308,750`,`$295,000`,`$283,333`,`$300,000`],a:3,why:`The formula gives a $45,000 overrun, the seller absorbs 25 percent ($11,250), the fee drops to $13,750, and the price would be $308,750. That's above the $300,000 ceiling, so the buyer pays the ceiling. The point of total assumption is $283,333 (250,000 plus 25,000 divided by 0.75); past it, the seller pays every extra dollar.`,task:`R5`,domain:`Process`},
  {q:`A sales executive emails a customer that a requested scope change is approved before any analysis. What should the project manager do?`,opts:[`Log it, analyze the impact, and take it to the decision makers`,`Honor the executive's email, since it came from senior management`,`Tell the customer the executive's email was sent by mistake`,`Ask the sponsor to discipline the executive for exceeding authority`],a:0,why:`Integrated change control still applies. Log, analyze, and route to the defined authority, communicating that clearly.`,task:`B3`,domain:`Business Environment`},
  {q:`A change request would increase the contract value by 15 percent. Who should approve it?`,opts:[`The project manager, who analyzed the impact of the change`,`The authority defined in the change plan and contract`,`The customer, who requested the change and will pay for it`,`The project team, who will carry out the additional work`],a:1,why:`Approval belongs to whoever the change management plan and contract authorize, often a change control board and the contracting authority.`,task:`B3`,domain:`Business Environment`},
  {q:`A project manager discovers a subcontractor may have handled regulated data without the required agreement. What should the project manager do first?`,opts:[`Ask the subcontractor to confirm in writing that nothing went wrong`,`Report it at the next steering meeting on the regular schedule`,`Contain the exposure and bring in the compliance experts`,`Replace the subcontractor so the issue doesn't happen again`],a:2,why:`Contain first, then involve compliance to assess and determine disclosure. Self-attestation and waiting are inadequate.`,task:`B2`,domain:`Business Environment`},
  {q:`A customer asks for training records for all project staff. Two contractors have no records. What should the project manager do?`,opts:[`Send only the complete records and follow up on the rest later`,`Have the two contractors complete training and backdate the records`,`Remove the two contractors from the project before sending the records`,`Send the records, disclose the gap, and state when it will be closed`],a:3,why:`Honest disclosure with a remediation plan is required. Backdating violates the Code of Ethics.`,task:`B2`,domain:`Business Environment`},
  {q:`The scope of a small integration is highly uncertain, and work must start right away. Which contract type is most suitable?`,opts:[`Time and materials with a not-to-exceed limit`,`Firm fixed price for the full integration`,`Cost plus percentage of cost to motivate speed`,`Fixed price with economic price adjustment`],a:0,why:`T&M is fast to set up for uncertain, short work. The cap limits the buyer's risk.`,task:`R5`,domain:`Process`},
  {q:`A project manager hears a credible rumor that a key vendor is in financial trouble. What should the project manager do?`,opts:[`Wait until the vendor misses a deliverable before taking action`,`Record it as a risk, assess it, and plan an appropriate response`,`Terminate the vendor's contract to remove the dependency now`,`Ask the vendor's competitors whether the rumor is accurate`],a:1,why:`Treat it as a risk: assess probability and impact and plan a proportionate response.`,task:`B5`,domain:`Business Environment`},
  {q:`In a negotiation, what should a project manager focus on to reach an agreement both sides can accept?`,opts:[`Each party's starting position and the gap between them`,`The other party's weaknesses and how to exploit them`,`Both sides' underlying interests and their alternatives`,`Winning the largest concession possible in the first offer`],a:2,why:`Interest-based negotiation and knowing your best alternative lead to win-win outcomes.`,task:`R5`,domain:`Process`},
  {q:`A project needs a decision on whether to go live. How should the go/no-go decision be set up?`,opts:[`Let the sponsor decide based on judgment the week of the launch`,`Go live on the contract date, since delays are costly to everyone`,`Have the project team vote on whether they feel ready to launch`,`Agree measurable criteria with key stakeholders well in advance`],a:3,why:`Objective criteria agreed early with stakeholders make the go/no-go decision about evidence, not pressure.`,task:`P4`,domain:`People`}
 ],
 closing:(s,all,G)=>[
  `Joan stayed late on Friday to file the LabelForge amendment. Sam found her putting it in the gray cabinet behind a yellow tab.`,
  `<span class="said" data-who="Joan">"You did fine,"</span> she said, which from Joan was a standing ovation. <span class="said" data-who="Joan">"Most PMs either fold or go to war. You traded."</span>`,
  `He drove home past Union Station with the go/no-go criteria printed on the seat beside him. Eight lines on one page. Together they'd decide whether three hospitals turned on software that wrote notes about real patients.`,
  `Dana was grading lab reports at the kitchen table. She looked at the page over her glasses. <span class="said" data-who="Dana">"You never bring home work that looks like a checklist,"</span> she said. <span class="said" data-who="Dana">"That's how I know you're scared."</span>`,
  `She wasn't wrong. On Monday, Maria called from Cheyenne. The nurses there had read about the agents in a union newsletter, and they had questions. Denise Harmon, the nurse manager, had a list. <span class="said" data-who="Maria">"You should come up,"</span> Maria said. <span class="said" data-who="Maria">"Bring coffee. A lot of it."</span>`
 ],
 episode:{src:`audio/full-ch08.mp3`, len:`about 35 minutes`},
 next:`Go-Live`
});
