// Full Course, Chapter 9. See full/BIBLE.md for the format.
(window.HALCYON_FULL=window.HALCYON_FULL||[]).push({
 num:9, part:`Part One: The Cascade Launch`, title:`Go-Live`, weeks:`Weeks 11 to 14`,
 tasks:[`B2`,`B7`,`R7`,`P6`,`B4`],
 cast:[[`Denise Harmon`,`Nurse manager, Cascade's Cheyenne hospital. Twenty-two years on the floor. Has a list.`]],
 opening:[
  `The Cheyenne hospital sat on a rise west of town, where the wind came straight off the high plains and didn't stop for anything. Sam drove up on a Tuesday with four boxes of coffee and Maria in the passenger seat reading him the union newsletter out loud.`,
  `The headline said "AI Will Write Your Notes. Who Will Read Them?" The article claimed the agents would be used to cut nursing staff, that the hospital would track how fast each nurse signed notes, and that a mistake by the software would be the nurse's license on the line.`,
  `<span class="said">"Two of those are false,"</span> Maria said. <span class="said">"The third one is true. If a nurse signs a note, it's her note. That's how charting works. That's why they're scared."</span>`,
  `Denise Harmon met them in the break room. She'd been a nurse for twenty-two years and a nurse manager for eight. She had a yellow legal pad with nineteen numbered items on it, and she put it on the table between the coffee boxes like a deposition.`,
  `<span class="said">"I'm not against you,"</span> she said. <span class="said">"I'm against anything that gets put on my nurses without asking them first. We've had three 'efficiency' systems in ten years. Every one of them made the night shift worse."</span>`,
  `Go-live for Fort Collins, Greeley, and Cheyenne was in three weeks. Cheyenne had the lowest training completion of the three, and Denise, Sam was starting to understand, was the reason. Driving home through the wind, he thought about the flight line again. You can't make a crew chief trust a new procedure by telling him to. You show him why, and then you let him try to break it.`
 ],
 lesson:{
  title:`Compliance, organizational change, and going live`,
  sections:[
   {h:`Plan and manage compliance`,
    body:[`Compliance means meeting the legal, regulatory, contractual, and organizational requirements that apply to your project. On the July 2026 outline it's its own task in the Business Environment domain. The work is to identify the requirements early, decide how you'll meet them, build those controls into the plan, check them, and act fast when something goes wrong.`,
     `When a compliance issue appears, the order matters. Contain it so it can't get worse. Escalate it to the people in your organization who own that area, like the privacy officer or legal. Follow the defined incident process, which usually includes notifying the customer under your contract. Don't investigate quietly on your own, don't minimize it, and never hide it. The exam rewards transparency every time.`,
     `Compliance also shapes quality decisions. If a regulation or contract requires testing, sign-off, or records, skipping them to protect a date isn't an option the PM can offer.`],
    terms:[[`Compliance requirement`,`A rule the project must meet, from law, regulation, contract, or internal policy.`],[`Incident process`,`The organization's defined steps for containing, escalating, and reporting a breach or violation.`]],
    exam:`For a possible violation, look for the answer that contains, escalates to the right internal owner, and follows the process. Answers that investigate alone first or wait for proof are usually wrong.`},
   {h:`Support organizational change`,
    body:[`Projects change how people work, and people don't change because a system went live. Supporting organizational change is its own exam task. You plan for adoption as carefully as for delivery.`,
     `ADKAR describes what each person needs in order: Awareness of why the change is happening, Desire to take part, Knowledge of how to change, Ability to do it in real work, and Reinforcement so it sticks. Resistance usually means one of those is missing. A nurse who knows how to use the agent but doesn't want to lacks desire, and more training won't fix that. Kotter's eight steps describe the same journey for an organization, starting with creating urgency and building a guiding coalition. Lewin's model is simpler: unfreeze, change, refreeze.`,
     `The most effective tool is usually involvement. Bring respected people from the affected group into the design, train them first, and let them become champions. A respected skeptic who becomes a supporter is worth more than any email from leadership.`],
    terms:[[`ADKAR`,`Awareness, Desire, Knowledge, Ability, Reinforcement. A model for individual change.`],[`Change champion`,`A respected member of the affected group who supports and helps others adopt the change.`],[`Resistance`,`A normal reaction to change, usually a signal that a need hasn't been met.`]],
    exam:`When users resist a new system, the exam rarely wants you to escalate or mandate. It wants you to understand the cause and involve them.`},
   {h:`Transition, go-live, and hypercare`,
    body:[`Going live is a planned transition, not a switch. You need agreed readiness criteria, a cutover plan with steps, owners, and timing, a tested rollback plan with clear triggers, and support ready for the first days. The go/no-go meeting reviews status against the criteria, and the people named as decision makers decide. The PM presents facts and options, including any risks of going.`,
     `Hypercare is the period right after go-live when extra support is on hand: people on the floor, a faster escalation path, daily check-ins. It ends when the system is stable and the operations team can support it normally. That handoff, with documentation, training, and an agreed support model, is part of the project, not an afterthought.`],
    terms:[[`Cutover plan`,`The step by step plan for moving to the new system, with owners and timing.`],[`Rollback plan`,`How you return to the previous state if go-live fails, and what triggers it.`],[`Hypercare`,`A period of heightened support right after go-live.`]],
    exam:`A rollback plan that hasn't been tested is a hope, not a plan. If a readiness criterion is red, the answer is to fix it or decide openly with the decision makers, not to quietly proceed.`},
   {h:`Measuring whether it worked`,
    body:[`Before you go live, capture a baseline for the benefit you promised. For Cascade, that's documentation time per note and per shift, measured the same way before and after. Without a baseline, nobody can prove the project delivered value, and the benefits conversation turns into opinions.`,
     `Baselines also protect the team. If the agents save nurses twenty minutes a shift, that's a story worth telling. If they don't, you want to know early, while you can still fix the workflow, rather than a year later in a budget review. Agree with the customer which measures matter, who collects them, and when, as part of transition planning. Write it down as a benefits measurement plan with a named business owner, because the measuring will go on long after the project team has moved to other work.`,
     `Readiness has a people side too. Operational readiness covers support staffing, runbooks, escalation paths, and the knowledge the operations team needs to run the system without the project team. If those aren't in place, the project hasn't really transitioned, however well the cutover went.`],
    terms:[[`Benefits baseline`,`The measured starting point used to show whether the promised benefit was achieved.`],[`Operational readiness`,`Whether the people, processes, and support needed to run the product are in place.`]],
    exam:`If a question asks how to show a project delivered its intended value, look for an answer that compares results against a baseline measured before the change.`},
   {h:`Quality under pressure`,
    body:[`The most common late project pressure is to cut testing. A sponsor sees the date at risk and asks whether the final test cycle is really necessary. The PM's job is to make the risk visible: what the testing covers, what could reach users if you skip it, and what options exist, like a shorter risk-based test that focuses on the highest risk areas.`,
     `Then the sponsor decides, inside the limits of compliance and safety. If testing is required by contract or regulation, it isn't optional. The PMI Code of Ethics asks you to be honest about risks and to protect the people affected by your work. That includes patients you'll never meet.`],
    terms:[[`Risk-based testing`,`Focusing test effort on the areas with the highest likelihood or impact of failure.`]],
    exam:`When a sponsor asks to cut a quality activity, look for the answer that explains the risk and offers options. Silently agreeing and flatly refusing are both usually wrong.`}
  ],
  video:[`4Ok2BKSuAew`,`ADKAR: What is Prosci's ADKAR Model of Change?`,`Mike Clayton`,`6:39`]
 },
 scenes:[
 {id:`f9s1`, domain:`Business Environment`, task:`B7`, title:`The legal pad`,
  text:(s,all,G)=>[`Denise slides the legal pad across the table. Item one: "Who decided this?" Item seven: "What happens when it's wrong at 3 AM?" Item nineteen: "Will you be here after go-live, or just at the party?"`,(G.hiddefect?`She adds, without looking up, <span class="said">"I also heard you sat on a bad medication for a week."</span> Maria winces.`:`Maria sits back and lets Sam answer.`)],
  opts:[
   {t:`Go through every item with her, answer what he honestly can, and write down what he can't.`,s:3,best:true,d:{trust:4,conf:5,health:2},
    after:`It takes two hours and three refills. Sam answers eleven items, admits he doesn't know six, and agrees two of them are real problems. Denise doesn't smile. She does ask when he's coming back.`,
    why:`Resistance usually means a need hasn't been met. Listening to each concern and being honest about what you don't know is how you find the real causes and start building trust.`},
   {t:`Present the benefits of the agents first, then take her questions once she sees the value.`,s:1,d:{trust:0,conf:1,health:0},
    after:`Denise waits politely through eight slides. Then she says, <span class="said">"That's what the last three vendors said,"</span> and turns to item one.`,
    why:`Explaining why the change matters builds awareness, but leading with a pitch to someone who has specific concerns signals you didn't come to listen.`},
   {t:`Ask Ochoa to tell Denise the rollout is a hospital decision that isn't up for debate.`,s:0,d:{trust:-2,conf:-4,health:-2},
    after:`Ochoa does. Denise complies. Cheyenne's training numbers drop the following week.`,
    why:`Mandates get compliance, not adoption. Forcing a change on a skeptical, respected leader turns quiet resistance into organized resistance.`},
   {t:`Thank her for the list and promise a written response to every item within two weeks.`,s:0,d:{trust:-1,conf:-1,health:0},
    after:`The response is thorough. It arrives after go-live training has already started without her.`,
    why:`A written response has its place, but deferring every concern to a document misses the chance to engage in person when it matters.`}
  ]},
 {id:`f9s2`, domain:`Business Environment`, task:`B7`, title:`Bring her in`,
  text:(s,all,G)=>[`Two of Denise's items are real. The training was built for day shift and assumes a quiet hour that nights never get. And nobody asked a floor nurse how the review screen should look at 3 AM.`,`Maria has an idea. Sam has the same one.`],
  opts:[
   {t:`Ask Denise and two of her night nurses to help redesign the training and review screen.`,s:3,best:true,d:{trust:6,conf:4,health:3},
    after:`Denise says she'll think about it, which Maria says means yes. Her night nurses cut the review screen from three clicks to one and rewrite the training for twenty minute bursts. Denise starts calling it <span class="said">"our version."</span>`,
    why:`Involving respected members of the affected group in the design builds desire, the hardest part of change. A skeptic who shapes the change often becomes its strongest champion.`},
   {t:`Fix the two problems with the Denver team and show Denise the improved version next week.`,s:1,d:{trust:1,conf:2,health:2},
    after:`The fixes are decent. Denise notes that they were made for her, not with her.`,
    why:`Fixing real problems is good, but doing it without the users misses the bigger win, which is ownership.`},
   {t:`Leave Cheyenne for the second wave and swap in Laramie, where training is further along.`,s:0,d:{trust:-2,conf:-3,health:-3},
    after:`It's a three week replan, and it tells every nurse in the network that pushing back gets you skipped.`,
    why:`Avoiding resistance by changing the plan doesn't address the cause and creates a large scope change late in the project.`},
   {t:`Offer Cheyenne extra training hours to bring completion up before go-live.`,s:0,d:{trust:0,conf:0,health:-1},
    after:`Attendance stays low. More training doesn't fix not wanting to come.`,
    why:`Training builds knowledge. Cheyenne's gap is desire. Match the intervention to the missing step.`}
  ]},
 {id:`f9s3`, domain:`People`, task:`P6`, title:`The newsletter`,
  text:(s,all,G)=>[`The union newsletter article is being forwarded to all eleven hospitals. Two of its claims are false. One is true and frightening.`,`Grant wants a press-style rebuttal. Maria wants nothing said at all, so it blows over.`],
  opts:[
   {t:`Write an honest FAQ with Cascade and Denise that answers all three claims directly.`,s:3,best:true,d:{trust:3,conf:6,health:1},
    after:`The FAQ says plainly that no staffing changes are tied to the agents, that signing speed isn't tracked, and that yes, a signed note is the nurse's note, which is why every medication is now traced and flagged. Denise's name is on it as a reviewer. The newsletter runs it the next month.`,
    why:`Manage expectations with honest, timely communication through trusted channels. Addressing the true concern directly, and showing what you've done about it, builds credibility a rebuttal never would.`},
   {t:`Issue a firm statement correcting the false claims and leave the license question to Cascade.`,s:1,d:{trust:0,conf:2,health:0},
    after:`The corrections land. The question nurses actually cared about goes unanswered.`,
    why:`Correcting falsehoods is fine, but avoiding the real fear leaves the biggest concern unaddressed.`},
   {t:`Say nothing publicly and let the article blow over before the first hospitals go live.`,s:0,d:{trust:0,conf:-4,health:-1},
    after:`It doesn't blow over. Silence reads as confirmation.`,
    why:`Silence lets stakeholders fill the gap with their fears. Communication should be proactive, especially when misinformation is spreading.`},
   {t:`Ask Cascade's leadership to tell the union the article was inaccurate and should be pulled.`,s:0,d:{trust:-2,conf:-3,health:-1},
    after:`The union runs a follow-up headline about management trying to silence nurses.`,
    why:`Pressuring a stakeholder group to retract escalates the conflict. Answer concerns openly instead.`}
  ]},
 {id:`f9s4`, domain:`Business Environment`, task:`B7`, title:`Training that sticks`,
  text:(s,all,G)=>[`Training completion across the three hospitals is 81 percent with two and a half weeks to go. The target in the go/no-go criteria is 95.`,`The original plan was a two hour classroom session per nurse.`],
  opts:[
   {t:`Switch to short role-based sessions and train super users on every single shift.`,s:3,best:true,d:{trust:3,conf:3,health:5},
    after:`Twenty minute sessions, scheduled at shift change, run by Denise's redesigned material. Every unit gets two super users per shift who'll be on the floor at go-live. Completion climbs four points a week.`,
    why:`Good change support builds knowledge and ability in a form that fits real work, and puts trained peers where people will need help. Super users also reinforce adoption after launch.`},
   {t:`Make training mandatory and report each unit's completion rate to hospital leadership.`,s:1,d:{trust:-2,conf:1,health:2},
    after:`Completion jumps. So does resentment, and the training that gets completed is rushed.`,
    why:`Requirements and visibility can help, but mandating without fixing the format gets attendance, not learning.`},
   {t:`Lower the target to 80 percent, since most nurses will learn it on the job anyway.`,s:0,d:{trust:0,conf:-3,health:-3},
    after:`Maria refuses to sign the revised criteria. She's right.`,
    why:`Changing readiness criteria to match current progress defeats the point of having them.`},
   {t:`Have Halcyon staff deliver the training to give it more technical depth and authority.`,s:0,d:{trust:-1,conf:-1,health:-1},
    after:`The Halcyon trainers are clear and correct and nobody remembers a word.`,
    why:`Peers who do the job are more credible trainers for the people affected by a change than the vendor.`}
  ]},
 {id:`f9s5`, domain:`Business Environment`, task:`B2`, title:`The logs`,
  text:(s,all,G)=>[`Week twelve, Wednesday night. Priya calls Sam at 10:40. While chasing a performance problem, she found that a debug setting turned on last month has been writing full patient names and dates of birth from the staging environment into a log file.`,`The staging environment uses a copy of real Cascade records for final testing. The log has been readable by about forty Halcyon staff.`],
  opts:[
   {t:`Have Priya stop the logging and lock the file now, then wake Halcyon's privacy officer.`,s:3,best:true,d:{trust:2,conf:4,health:-1},
    after:`The logging is off in eight minutes and the file locked in twelve. Ken Ito, Halcyon's privacy officer, is on a call by 11:15 and opens an incident. Cascade's privacy office is notified the next morning through the channel the business associate agreement requires, with facts, scope, and next steps.`,
    why:`Contain first so it can't get worse, then escalate to the person who owns privacy incidents and follow the defined process, which includes notifying the customer as the contract requires.`},
   {t:`Ask Priya to find out exactly who accessed the file before anyone else is told about it.`,s:0,d:{trust:0,conf:-4,health:-1},
    after:`She works until 3 AM on access logs. The exposure continues the whole time.`,
    why:`Investigating alone before containing and escalating delays the response and keeps you outside the incident process. Specialists handle the investigation.`},
   {t:`Call Ochoa tonight, since Cascade's patients are affected and he deserves to know first.`,s:1,d:{trust:0,conf:2,health:-1},
    after:`Ochoa appreciates the call and asks what Halcyon's privacy officer said. Sam hasn't called him yet.`,
    why:`Customer notification matters, but it goes through your organization's incident process, which starts with containment and your own privacy officer.`},
   {t:`Delete the log file so the patient data is gone and the exposure is over for good.`,s:0,d:{trust:0,conf:-6,health:-2},
    after:`Ken Ito explains, gently, that the log was evidence. Now nobody can establish what was exposed.`,
    why:`Deleting evidence makes an incident worse and can violate legal obligations. Contain, preserve, and escalate.`}
  ]},
 {id:`f9s6`, domain:`Business Environment`, task:`B4`, title:`Locked out`,
  text:(s,all,G)=>[`The incident response locks down staging access for everyone except four people while the investigation runs. Final regression testing was scheduled there for next week.`,`Tomasz messages that Kraków has nothing to test against. Twelve engineers are idle.`],
  opts:[
   {t:`Work with Ken to stand up a fully de-identified test environment so testing can continue.`,s:3,best:true,d:{trust:4,conf:2,health:5},
    after:`Ken approves a synthetic data environment by Friday. Kraków is testing again on Monday. The incident investigation continues untouched.`,
    why:`Removing impediments is a core PM task. Find a path that keeps the team productive without undermining the incident process or compliance.`},
   {t:`Ask Ken to restore Kraków's staging access early, since the logging problem is already fixed.`,s:0,d:{trust:0,conf:-2,health:1},
    after:`Ken says no, politely, and adds Sam to a list of people he keeps an eye on.`,
    why:`Pushing to bypass incident controls for schedule reasons puts the investigation and compliance at risk.`},
   {t:`Give Kraków other backlog items to work on until staging access comes back.`,s:1,d:{trust:1,conf:0,health:-1},
    after:`They stay busy, but regression testing slips a week, right into go-live.`,
    why:`Redirecting work keeps people busy but leaves the real impediment, no test environment, in place.`},
   {t:`Log it as an issue and report it in Friday's status, since the incident isn't Sam's to manage.`,s:0,d:{trust:-1,conf:0,health:-3},
    after:`It's in the status report. It's still blocking twelve people.`,
    why:`Reporting an impediment isn't removing it. The PM owns clearing blockers within their reach.`}
  ]},
 {id:`f9s7`, domain:`Process`, task:`R7`, title:`One red line`,
  text:(s,all,G)=>[`Week thirteen. Seven of the eight go/no-go criteria are green. The eighth, "rollback tested end to end," is red. The rollback plan exists. Nobody has ever run it.`,`Lena says it's a formality. <span class="said">"We wrote it carefully."</span>`],
  opts:[
   {t:`Schedule a full end to end rollback rehearsal in staging this week with the go-live team.`,s:3,best:true,d:{trust:2,conf:3,health:6},
    after:`The rehearsal fails at step eleven. A database script assumes a table that the second wave renamed. They fix it and run it again Thursday. Clean. Lena buys the team lunch and says she'll never call anything a formality again.`,
    why:`A rollback plan that hasn't been tested is an assumption. Quality means verifying the plan works before you need it, and the readiness criteria exist so you don't skip that.`},
   {t:`Have two engineers walk through the rollback plan on paper and mark the criterion green.`,s:1,d:{trust:0,conf:0,health:1},
    after:`The walkthrough doesn't catch the renamed table. Paper doesn't run.`,
    why:`A desk check is better than nothing, but it isn't a test. The criterion said tested end to end for a reason.`},
   {t:`Accept the red criterion, since rollback is unlikely to be needed with seven greens.`,s:0,d:{trust:0,conf:-2,health:-4},
    after:`Everyone agrees. Nobody writes down who decided.`,
    why:`Accepting a known gap without deciding openly with the decision makers undermines the criteria you agreed.`},
   {t:`Ask Kraków to write a second, simpler rollback plan as a backup in case the first one fails.`,s:0,d:{trust:-1,conf:0,health:-1},
    after:`Now there are two untested plans.`,
    why:`More plans aren't more readiness. Test the one you have.`}
  ]},
 {id:`f9s8`, domain:`People`, task:`P6`, title:`The ask`,
  text:(s,all,G)=>[`Elena calls Sam into her office on Monday of week fourteen. The incident cost four days. <span class="said">"The final regression cycle is five days,"</span> she says. <span class="said">"Skip it. The agents haven't changed since the last cycle. We go Friday."</span>`,(G.hidnumbers?`She adds, <span class="said">"And don't give me a scary number. Last time your numbers were rounder than they should have been."</span>`:`<span class="said">"You've been straight with me since week one,"</span> she says. <span class="said">"So tell me straight."</span>`),`That night Ruth calls. She heard from the board. She doesn't tell him what to do. She tells him about a sensor reading she saw in her second year at Johnson, on an uncrewed vehicle, that she decided was probably noise because she didn't want to look like the nervous new kid. <span class="said">"It wasn't noise,"</span> she says, and then she changes the subject.`],
  opts:[
   {t:`Show Elena what changed, the risk of skipping it, and a two day targeted test.`,s:3,best:true,d:{trust:2,conf:5,health:5},
    after:`Sam shows her the list: the logging fix, the rollback script, and two configuration changes, all touching patient data paths. He offers a two day targeted regression on those paths. Elena takes it. Go-live holds.`,
    why:`When a sponsor wants to cut quality work, make the risk visible and offer options. Here the honest answer is that things did change, and a risk-based test protects both the date and the patients.`},
   {t:`Agree to skip it, since the sponsor owns the decision and the date is in the contract.`,s:0,flag:`skippedtest`,d:{trust:-2,conf:0,health:-6},
    after:`They go live Friday without the regression cycle. The thing nobody tested is waiting.`,
    why:`The sponsor decides, but only with the risks laid out, and never against safety or compliance requirements. Agreeing without making the risk visible fails both the sponsor and the patients.`},
   {t:`Refuse, and tell Elena that skipping the test cycle would be unethical and unsafe for patients.`,s:1,d:{trust:0,conf:-2,health:3},
    after:`Elena backs down, irritated. The cycle runs the full five days and go-live slips three days.`,
    why:`Standing firm on safety is right, but a flat refusal without options turns a decision into a standoff. A risk-based alternative serves everyone better.`},
   {t:`Ask Ochoa whether Cascade would accept going live without the final regression cycle.`,s:0,d:{trust:0,conf:-3,health:0},
    after:`Ochoa asks why Halcyon is asking him that. It's a fair question with no good answer.`,
    why:`Pushing your internal quality decision onto the customer shifts responsibility and erodes their trust.`}
  ]},
 {id:`f9s9`, domain:`Process`, task:`R7`, title:`Cutover`,
  text:(s,all,G)=>[`Wednesday, two days out. The cutover plan has forty-one steps across three hospitals, Halcyon, and IronPeak. Priya asks what happens if Greeley's interface engine is slow to reconnect.`,`The rollback plan says "roll back if critical issues occur."`],
  opts:[
   {t:`Agree clear rollback triggers with Cascade, and name who gets to make the call.`,s:3,best:true,d:{trust:2,conf:4,health:5},
    after:`They write five triggers, like "interface down more than 45 minutes" and "any untraced medication in a signed note," and name Ochoa and Sam as the two people who can call rollback. Priya sleeps better.`,
    why:`A rollback plan needs objective triggers and named decision makers, agreed in advance. "Critical issues" leaves the hardest call to be made under pressure at 3 AM.`},
   {t:`Leave the trigger as written so the team can use judgment on the night itself.`,s:0,d:{trust:0,conf:-1,health:-3},
    after:`On the night, three people have three definitions of critical.`,
    why:`Judgment under pressure is exactly what clear triggers protect you from.`},
   {t:`Ask IronPeak to stay on call all night so any infrastructure issue gets fixed fast.`,s:1,d:{trust:0,conf:1,health:2},
    after:`Hal agrees. It's useful. It doesn't answer Priya's question.`,
    why:`Support coverage helps, but it doesn't define when to roll back. You need both.`},
   {t:`Add a step to the plan for the team to meet at midnight and decide whether to continue.`,s:0,d:{trust:0,conf:0,health:-1},
    after:`It's a meeting, not a decision rule.`,
    why:`A checkpoint without criteria just schedules the argument.`}
  ]},
 {id:`f9s10`, domain:`People`, task:`P6`, title:`The go/no-go meeting`,
  text:(s,all,G)=>[`Thursday. The go/no-go meeting. Seven criteria are green. Training completion is 93 percent against a target of 95: Fort Collins and Greeley are at 97, Cheyenne at 88.`,`Denise is on the call. So are Ochoa, Maria, Elena, and Lena.`],
  opts:[
   {t:`Present each criterion, the Cheyenne gap, and the options, and let the decision makers decide.`,s:3,best:true,d:{trust:3,conf:6,health:3},
    after:`Sam lays it out: go with Cheyenne's super users doubled for the first week, or hold Cheyenne for five days. Denise speaks up. <span class="said">"My night nurses trained the day shift this week. We're ready."</span> The decision makers vote to go, all three hospitals.`,
    why:`At go/no-go the PM presents status against the agreed criteria, including gaps and options. The named decision makers decide. That keeps the decision honest and owned.`},
   {t:`Recommend going live, since 93 percent is close enough and the other seven are green.`,s:1,d:{trust:0,conf:1,health:0},
    after:`They agree, but Maria notes that "close enough" wasn't one of the criteria.`,
    why:`A recommendation is fine, but it should come after presenting the gap and options, so the decision makers see the full picture.`},
   {t:`Mark training green, since Cheyenne's super users can cover the gap on the first nights.`,s:0,d:{trust:0,conf:-4,health:-1},
    after:`Denise points out on the call that her unit is at 88. The room goes quiet.`,
    why:`Reporting a criterion as met when it isn't is misreporting, even with good intentions.`},
   {t:`Postpone the meeting a day so Cheyenne can push completion over 95 percent first.`,s:0,d:{trust:0,conf:-2,health:-1},
    after:`Cheyenne gets to 95 by pulling nurses off the floor. The cutover window shrinks.`,
    why:`Delaying the decision to make the numbers look right avoids the real choice. Present the facts and let the decision makers decide.`}
  ]},
 {id:`f9s11`, domain:`Business Environment`, task:`B4`, title:`2:14 AM`,
  text:(s,all,G)=>[`Saturday, 2:14 AM. The Greeley interface engine drops. Notes queue but don't post to the hospital record. Priya is on the bridge. Ochoa is asleep. The rollback trigger is forty-five minutes.`,((s.flags.skippedtest||G.skippedtest)?`Nobody knows yet whether it's Cascade's network or the logging path that changed, the one the skipped regression cycle would have covered.`:`It's a network change on Cascade's side. Nothing Halcyon touched.`)],
  opts:[
   {t:`Work the runbook with Cascade's interface team and update the bridge every 15 minutes.`,s:3,best:true,d:{trust:4,conf:4,health:4},
    after:`Cascade's on-call engineer finds the problem at 2:41. The interface reconnects at 2:49, thirty-five minutes in. Queued notes post in order. Ochoa wakes up to a three line summary and a timeline.`,
    why:`Work the impediment through the plan you made: triage with the right people, communicate on schedule, and use the agreed trigger. Calm execution beats heroics.`},
   {t:`Roll back Greeley now to be safe, without waiting for the forty-five minute trigger.`,s:1,d:{trust:0,conf:0,health:-2},
    after:`Rollback works. The fix on Cascade's side comes five minutes later, and Greeley spends Sunday re-cutting.`,
    why:`Erring on the side of safety isn't wrong, but the team agreed triggers so these calls wouldn't be made on instinct.`},
   {t:`Have Priya patch the interface code directly in production to get notes posting again.`,s:0,d:{trust:0,conf:-2,health:-4},
    after:`The patch skips change control and introduces a second problem.`,
    why:`Emergency changes still follow the emergency change process. Untested fixes in production at 2 AM create new incidents.`},
   {t:`Wake Elena and Ochoa immediately so the executives can decide what to do next.`,s:0,d:{trust:0,conf:-1,health:-1},
    after:`Both executives join, ask what the runbook says, and go back to bed.`,
    why:`Escalate per the plan, not by reflex. The bridge has the authority and the triggers it needs.`}
  ]},
 {id:`f9s12`, domain:`Business Environment`, task:`B7`, title:`Hypercare`,
  text:(s,all,G)=>[`Day three of hypercare. Fort Collins and Greeley are steady. Cheyenne's nurses are signing more notes than either, faster, with fewer edits. Two complaints keep coming in: the review screen times out during long codes, and the night shift wants a way to flag a draft as wrong without fixing it.`,`Denise sends Sam a photo of her unit's whiteboard. Someone has written "AI note of the shift" with a nurse's name under it.`],
  opts:[
   {t:`Fix the top two complaints fast, share the wins, and keep the champions close.`,s:3,best:true,d:{trust:4,conf:5,health:4},
    after:`The timeout fix ships on day five. The "flag as wrong" button ships on day nine, designed by Denise's night shift. Maria shares Cheyenne's numbers with the other eight hospitals. Three of them ask whether they can talk to Denise.`,
    why:`Reinforcement makes change stick: respond quickly to feedback, celebrate real wins, and keep champions at the center. That's how a skeptic's unit becomes the model for everyone else.`},
   {t:`Batch the complaints into the phase two backlog so the current release stays stable.`,s:1,d:{trust:-1,conf:0,health:2},
    after:`Stable, yes. The night shift notices nobody did anything about the timeout.`,
    why:`Stability matters in hypercare, but small, fast fixes to real pain points are part of reinforcement.`},
   {t:`End hypercare early at Cheyenne, since their adoption is already better than the others.`,s:0,d:{trust:-1,conf:-1,health:-2},
    after:`The super users go back to normal duty right as the night shift hits its first busy weekend.`,
    why:`Hypercare ends on stability and a clean handoff to operations, not on early good news.`},
   {t:`Ask Halcyon's marketing team to turn Cheyenne's story into a case study for new customers.`,s:0,d:{trust:-2,conf:-2,health:0},
    after:`Denise sees a draft. She is not pleased to be a marketing asset on day three.`,
    why:`Recognizing a team's success is good. Using it externally before the users are ready, and without asking, isn't.`}
  ]}
 ],
 exercise:{after:`f9s4`, title:`Which ADKAR step is missing?`, intro:`Each nurse below is struggling with the change. Pick the step of ADKAR they're missing.`,
  items:[
   {prompt:`A nurse hasn't heard why the hospital is adopting AI documentation at all.`,choices:[`Awareness`,`Desire`,`Knowledge`,`Ability`,`Reinforcement`],answer:0,why:`She doesn't know why the change is happening. That's awareness, the first step.`},
   {prompt:`A nurse understands the reasons but says she just doesn't want to rely on software for her notes.`,choices:[`Awareness`,`Desire`,`Knowledge`,`Ability`,`Reinforcement`],answer:1,why:`She knows why but doesn't want to take part. That's a desire gap, and training won't close it.`},
   {prompt:`A nurse wants to use the agents but has never been shown how to review and sign a draft.`,choices:[`Awareness`,`Desire`,`Knowledge`,`Ability`,`Reinforcement`],answer:2,why:`She's willing but doesn't know how. That's knowledge.`},
   {prompt:`A nurse completed training but freezes when she tries it during a busy real shift.`,choices:[`Awareness`,`Desire`,`Knowledge`,`Ability`,`Reinforcement`],answer:3,why:`She knows how in theory but can't yet do it in real work. That's ability, which practice and at-the-elbow support build.`},
   {prompt:`A unit adopted the agents well for a month, then slowly drifted back to typing notes by hand.`,choices:[`Awareness`,`Desire`,`Knowledge`,`Ability`,`Reinforcement`],answer:4,why:`The change didn't stick. That's reinforcement: recognition, feedback, and fixing what makes people slide back.`},
   {prompt:`A night nurse says nobody ever explained what problem the agents are supposed to solve for her shift.`,choices:[`Awareness`,`Desire`,`Knowledge`,`Ability`,`Reinforcement`],answer:0,why:`Again, the why is missing. Awareness has to come before anything else will land.`}
  ]},
 quiz:[
  {q:`A project manager learns that a system has been logging regulated personal data where it shouldn't. What should the project manager do first?`,opts:[`Investigate who accessed the data before telling anyone else`,`Delete the logs so the exposure stops immediately and fully`,`Contain the exposure and escalate to the privacy owner`,`Call the customer's executive sponsor directly to report it`],a:2,why:`Contain first, then escalate to the internal owner and follow the incident process. Deleting evidence or investigating alone makes it worse.`,task:`B2`,domain:`Business Environment`},
  {q:`End users at one site strongly resist a new system and its training completion is low. What should the project manager do first?`,opts:[`Ask site leadership to make training mandatory for every user`,`Meet with the users to understand why they're resisting`,`Move the site to a later rollout wave to avoid the resistance`,`Add more training sessions to raise the completion numbers`],a:1,why:`Resistance signals an unmet need. Understanding the cause comes before choosing an intervention.`,task:`B7`,domain:`Business Environment`},
  {q:`In the ADKAR model, a user who knows why a change is happening but doesn't want to take part is missing which element?`,opts:[`Awareness`,`Knowledge`,`Ability`,`Desire`],a:3,why:`Awareness is present. Desire, the will to participate, is missing.`,task:`B7`,domain:`Business Environment`},
  {q:`A respected skeptic in the user community has raised valid concerns about a new system. What is the most effective approach?`,opts:[`Involve them in improving the design and the training`,`Ask their manager to address their concerns about the system`,`Explain the benefits again in a more detailed presentation`,`Exclude them from the pilot so their views don't spread further`],a:0,why:`Involving a respected skeptic builds ownership and often creates a strong champion.`,task:`B7`,domain:`Business Environment`},
  {q:`A sponsor asks the project manager to skip the final test cycle to meet a date. Several components changed since the last test. What should the project manager do?`,opts:[`Skip the testing, since the sponsor owns the schedule decision`,`Refuse, because skipping testing is never acceptable on a project`,`Ask the customer whether they'll accept going live without testing`,`Explain the risk of skipping and offer a shorter risk-based option`],a:3,why:`Make the risk visible and offer options. The sponsor decides with full information, within safety and compliance limits.`,task:`R7`,domain:`Process`},
  {q:`Seven of eight go-live criteria are met. The rollback plan has never been tested. What should the project manager do?`,opts:[`Test the rollback plan before the go-live decision`,`Mark it as met, since the plan was written carefully`,`Proceed, since rollback is unlikely to be needed now`,`Write a backup rollback plan in case the first fails`],a:0,why:`An untested rollback plan is an assumption. Test it.`,task:`R7`,domain:`Process`},
  {q:`At a go/no-go meeting, one readiness criterion is slightly below its target. What is the project manager's role?`,opts:[`Report the criterion as met, since it's close to its target`,`Present the status, gap, and options to the decision makers`,`Delay the meeting until the criterion fully meets its target`,`Make the final go-live decision as the person most accountable`],a:1,why:`The PM presents facts, gaps, and options. The named decision makers decide.`,task:`P6`,domain:`People`},
  {q:`Which element is most important in a rollback plan?`,opts:[`A list of everyone who should attend the go-live call`,`An estimate of how long the original cutover will take`,`Clear triggers and named people who can call a rollback`,`A summary of the benefits the new system will deliver`],a:2,why:`Objective triggers and decision authority keep the hardest call from being made under pressure without rules.`,task:`R7`,domain:`Process`},
  {q:`A misleading article about a project is circulating among the users who will be affected. What should the project manager do?`,opts:[`Stay silent and wait for the article to be forgotten by users`,`Ask the publication to retract the article as inaccurate`,`Issue a statement correcting only the false claims it made`,`Answer every concern honestly through trusted channels`],a:3,why:`Proactive, honest communication, including the true concerns, builds credibility. Silence and pressure backfire.`,task:`P6`,domain:`People`},
  {q:`An incident response locks the team out of its test environment, blocking work. What should the project manager do?`,opts:[`Find a compliant alternative that lets testing continue`,`Ask security to restore access early to protect the date`,`Report the blocker in the next status report and wait`,`Reassign the team to unrelated work until access returns`],a:0,why:`Removing impediments within the rules keeps the team productive without undermining the incident process.`,task:`B4`,domain:`Business Environment`},
  {q:`During hypercare, users report two small but annoying problems. What should the project manager do?`,opts:[`Defer both to the next release to keep the system stable`,`Fix them quickly and share early wins to reinforce adoption`,`End hypercare at the busiest site to free up support staff`,`Ask users to log every complaint in a formal change request`],a:1,why:`Fast responses to feedback and visible wins reinforce adoption during hypercare.`,task:`B7`,domain:`Business Environment`},
  {q:`What usually signals that hypercare can end?`,opts:[`The go-live date passes without any major incident at all`,`The sponsor declares the project a success to the board`,`The system is stable and operations can support it`,`The project budget for extra support has been fully spent`],a:2,why:`Hypercare ends on stability and a clean handoff to the operations team.`,task:`R7`,domain:`Process`},
  {q:`At 2 AM during go-live, an interface fails. The rollback trigger is 45 minutes. What should the project manager do?`,opts:[`Wake the executives so they can decide what the team should do`,`Patch the code directly in production to restore service quickly`,`Roll back immediately to be safe before the trigger is reached`,`Triage per the runbook and communicate on the agreed schedule`],a:3,why:`Follow the plan: triage with the right people, communicate, and apply the agreed trigger.`,task:`B4`,domain:`Business Environment`},
  {q:`A contract requires a specific test to be completed before go-live. The sponsor wants to skip it. What is true?`,opts:[`The test isn't optional, since the contract requires it`,`The sponsor may skip it if the risk is documented first`,`The project manager may skip it with the team's agreement`,`The test may be skipped if the customer isn't told about it`],a:0,why:`Contractual and regulatory requirements aren't the sponsor's to waive alone, and hiding it would violate the Code of Ethics.`,task:`B2`,domain:`Business Environment`},
  {q:`Which approach best builds users' ability to work with a new system during the first weeks after launch?`,opts:[`A long classroom session held a month before go-live`,`Trained peer super users available on every shift`,`A detailed user manual sent to everyone by email`,`A recorded video from the vendor's technical trainers`],a:1,why:`Ability is built in real work with support at hand. Peer super users on each shift do that best.`,task:`B7`,domain:`Business Environment`}
 ],
 closing:(s,all,G)=>[
  `Sunday morning, the third day of hypercare, Sam drove back up to Cheyenne. Denise was at the nurses' station with a coffee from one of his boxes, which had to be cold by now.`,
  `<span class="said">"Item nineteen,"</span> she said. <span class="said">"You came back."</span> She didn't say anything else about it. She didn't have to.`,
  ((s.flags.skippedtest||G.skippedtest)?`On the drive home he thought about Greeley. The outage had been Cascade's network, not the path they'd skipped testing. They'd gotten lucky. He wrote "lucky isn't a plan" in his notebook so he wouldn't forget it.`:`On the drive home he thought about the two day regression cycle and the logging path it had covered. Nothing had broken there. That was the point.`),
  `That evening he called Ruth. He asked her what happened after the sensor reading, in her second year. There was a long pause on the line.`,
  `<span class="said">"Another time,"</span> she said. <span class="said">"You've got eight hospitals left and a contract to close. Get some sleep, Sam. Three of them are live. On the date."</span>`,
  `He did sleep. Monday, the second wave started. So did the work nobody talks about, the closing of a project, which Ruth said was where you find out what you actually built.`
 ],
 episode:{src:`audio/full-ch09.mp3`, len:`about 35 minutes`},
 next:`Closeout`
});
