// Full Course, chapter 10. Format: see full/BIBLE.md.
(window.HALCYON_FULL=window.HALCYON_FULL||[]).push({
 num:10, part:`Part One: The Cascade Launch`, title:`Closeout`, weeks:`Weeks 15 to 18`,
 tasks:[`R10`,`B6`,`P7`,`P4`,`R5`,`R3`],
 cast:[
  [`Marcus Bell`,`Head of customer support at Halcyon. Inherits Cascade once the project ends.`],
  [`Joan Pruitt`,`Halcyon procurement lead. Reads every contract twice and enjoys the second read more.`]
 ],
 opening:[
  `Three hospitals went live on the contract date, and the thing Sam remembered afterward wasn't the dashboard turning green. It was a night nurse in Greeley named Alma who signed her first AI-drafted note at 3:40 in the morning, read it twice, and said to nobody in particular, <span class="said" data-who="woman">"Huh. It got the wound measurements right."</span> Priya had been on the bridge call. She texted Sam a single word: <span class="said" data-who="Priya">"Alma."</span> He knew exactly what she meant.`,
  `Monday of week fifteen there were donuts in the LoDo office, and that was the whole party. Eight hospitals were still waiting. Phase one wasn't finished until all eleven were live, Cascade had formally accepted, the support team owned the system, and every vendor was paid and closed. Elena wanted it wrapped by the end of week eighteen, before the board met.`,
  `Ruth had sent a text on go-live night. <span class="said" data-who="Ruth">"Splashdown isn't the end of a mission. Recovery is. Sleep."</span> Sam had slept five hours. It felt like leave.`,
  `At home, Dana had taped a sticky note to the coffee maker: <span class="said" data-who="Dana">"You smiled at your phone last night. Who is Alma?"</span> He wrote underneath it, <span class="said" data-who="Sam">"A nurse in Greeley. Long story. Good one."</span> When he came back down an hour later she'd added, <span class="said" data-who="Dana">"Tell me tonight. Not at 11 PM."</span>`,
  `He thought about his old flight chief, Ray Mendez, who used to say the most dangerous part of any launch was the walk back from the jet, when everybody relaxed and started leaving tools in intakes. Ray had made his crews do a full tool count after every sortie, even the ones that went perfectly. Especially those.`,
  `Sam opened a fresh page in his notebook and wrote one word at the top. <span class="said" data-who="Sam">"Finish."</span> Then, under it, smaller: <span class="said" data-who="Sam">"Tool count."</span>`
 ],
 lesson:{
  title:`Closing a project well`,
  sections:[
   {h:`Closing is a process, not an event`,
    body:[`Most projects don't fail at the end. They fade. The team drifts to new work, the customer stops getting answers, the vendor keeps invoicing, and six months later nobody can say whether the thing delivered what it promised. Closing is the work of ending the project on purpose.`,
          `In PMBOK terms you close a project or a phase by confirming the work is done and accepted, transferring the result to whoever will own it, closing out contracts, releasing people and resources, capturing what you learned, and getting formal sign-off that the project is over. On a hybrid project you also close the agile side: the product backlog either moves to a product team or is retired, and the final increment is accepted against the definition of done.`,
          `Closure applies to projects that end early, too. A cancelled project still gets closed: document why, record what was finished and what wasn't, release resources, and archive. On the exam, "the project was cancelled, what now?" almost always points to following the closure process, not just walking away.`,`Phases close too. A long project might close its design phase, its build phase, and each release separately, using the same steps at a smaller scale. Phase closure is where you confirm the phase met its exit criteria, update the plan for the next phase, and decide whether the business case still holds. A phase gate review is the governance moment where the sponsor or a steering group decides to continue, change course, or stop. Closing well at each phase makes the final closure short, because most of the work has already been done along the way.`],
    terms:[[`Final acceptance`,`Formal confirmation from the customer or sponsor that deliverables meet the agreed acceptance criteria.`],[`Transition`,`Handing the product, its documentation, and its support to the operations or business owner.`],[`Administrative closure`,`Archiving records, closing accounts, and getting sign-off that the project is complete.`]],
    exam:`Watch for "before closing the project" stems. The PMI order is: confirm acceptance, transfer the deliverable, close contracts, capture lessons, release resources, then formal closure and archive. Releasing the team before the lessons learned is a classic wrong answer.`},
   {h:`Acceptance and transition`,
    body:[`Acceptance is measured against criteria agreed earlier, usually in the scope statement, the contract, or the definition of done. You don't negotiate new criteria at the end. Open defects don't automatically block acceptance; minor items can be accepted with a documented punch list and owners, if the customer agrees and the contract allows it.`,
          `Transition is a deliverable of its own. The operations team needs runbooks, training, access, escalation paths, known issues, and a period of shadowing. A good hypercare period has exit criteria agreed in advance, such as defect rates or ticket volumes, so it ends on evidence instead of exhaustion.`,`Think about who will own each part of the product the day after the project ends. The support team owns incidents. A product owner owns the backlog. A business owner owns the benefits. Facilities or IT owns the infrastructure. Write those owners down, confirm each one has agreed, and make sure each has what they need: access, training, budget, and authority. A transition that only covers the support desk leaves the backlog, the vendor relationships, and the benefits orphaned.`],
    terms:[[`Hypercare`,`A period of heightened support right after go-live, with clear exit criteria.`],[`Punch list`,`A documented list of minor open items accepted with owners and dates.`]],
    exam:`If the customer refuses to sign because of something that was never in the requirements, the answer is to refer back to the agreed acceptance criteria and handle the new item through change control, not to absorb it quietly.`},
   {h:`Contract closure`,
    body:[`Every contract gets closed formally. Confirm all deliverables were received and accepted, settle open claims, make final payments, and record vendor performance for future decisions. Claims are best settled by negotiation; the contract's dispute process (alternative dispute resolution, then litigation as a last resort) is there if negotiation fails. Procurement audits look back at the whole buying process to learn what worked.`,
          `Contract closure usually happens before the project closes, because you can't call the project done while money and obligations are still open.`,`Read the contract before you close it. Check for warranty periods that outlast the project, retention amounts held back until acceptance, liquidated damages for late delivery, caps on those damages, and any notice periods for ending reservations or services. Then record the vendor's performance in a form the next buyer can use: on time, on budget, quality of work, responsiveness. That record is what turns one project's pain into the organization's leverage at the next negotiation.`],
    terms:[[`Claims administration`,`Documenting, processing, and resolving contested changes or disputes with a seller.`],[`Procurement audit`,`A structured review of the procurement process to capture lessons for future contracts.`],[`Liquidated damages`,`A pre-agreed amount the seller pays per unit of delay, written into the contract.`]],
    exam:`Negotiation is the preferred way to settle claims. If a question offers "take the vendor to court" next to "negotiate a settlement," negotiation wins unless negotiation has already failed.`},
   {h:`Lessons learned and continuous improvement`,
    body:[`Lessons learned are captured throughout the project, not only at the end, and they go into the organization's lessons learned repository so the next team can use them. The session itself must be safe: focus on the process and the system, never on blame. People only tell the truth about mistakes when it's safe to.`,
          `Continuous improvement turns lessons into changed practice. A lesson that sits in a document changes nothing. Kaizen, retrospectives, and Plan Do Check Act all share the same idea: small, owned, measured changes to how the work gets done. At the organization level, a PMO often owns updating templates, checklists, and standards based on what projects learned.`],
    terms:[[`Organizational process assets`,`The templates, procedures, and historical information, including lessons learned, that an organization keeps for future projects.`],[`Kaizen`,`Continuous, incremental improvement owned by the people doing the work.`],[`Benefits realization`,`Measuring whether the business outcomes the project was meant to enable actually happen, often after the project ends.`]],
    exam:`Benefits are often realized after the project closes, so the exam expects you to transfer benefits measurement to a named business owner with a plan, not to keep the project open until the benefits show up.`}
  ],
  video:[`29M-mDQAoQQ`,`4.7 Close Project or Phase, PMBOK Video Course`,`David McLachlan`,`11:50`]
 },
 scenes:[
  {id:`f10s1`, domain:`Process`, task:`R10`, title:`Eight hospitals, one weekend`,
   text:(s,all,G)=>[(G.skippedtest?`The skipped final test from week fourteen came back to bite on Tuesday: a field mapping bug that testing would have caught surfaced in Cheyenne, and it took Priya's team two days to fix. Elena didn't mention it. She didn't have to. `:``)+`Elena stops by Sam's desk with a coffee she clearly didn't get for herself. <span class="said" data-who="Elena">"The first three went great. Why don't we do the other eight in one weekend and be done?"</span>`,`The plan says three waves over four weeks, each wave gated on a readiness checklist at the hospitals: training complete, super users named, interfaces tested. Two of the eight hospitals haven't finished training.`],
   opts:[
    {t:`Agree to one weekend, since the first three proved the platform and support can surge.`,s:0,d:{trust:-3,conf:-2,health:-6},after:`Support drowns on the Sunday. Two hospitals that hadn't finished training flood the queue with how-do-I tickets and one unit goes back to paper for a shift.`,why:`One good wave doesn't remove the readiness gates. The waves exist because hospitals become ready at different times. Changing the plan to chase a date throws away the controls that made the first wave work.`},
    {t:`Keep the waves, and pull forward any hospital that passes its readiness check.`,s:3,best:true,d:{trust:2,conf:4,health:4},after:`Elena likes the offer more than she expected. One hospital in Laramie passes early and moves into wave two. The rest go on plan, and nothing breaks.`,why:`You kept the controls and still gave the sponsor a real lever. Readiness criteria decide the pace, not the calendar. That's managing the end of a project with the same discipline as the middle.`},
    {t:`Tell Elena the plan was baselined and can't change without a formal change request.`,s:1,d:{trust:0,conf:-2,health:1},after:`Elena files the request with visible annoyance. It gets the same answer a week later that a two-minute conversation would have given her today.`,why:`Change control is right for real changes, but you can answer the underlying question here: what would let us go faster safely? Leading with process instead of options costs goodwill.`},
    {t:`Ask Ochoa which approach Cascade prefers and let the customer choose the rollout.`,s:0,d:{trust:0,conf:-1,health:-2},after:`Ochoa says he'll think about it. Now there are two people waiting on a decision that the readiness data already answered.`,why:`The customer's input matters, but this is a delivery decision with data behind it. Pushing it to Ochoa without a recommendation adds delay and makes Halcyon look unsure.`}
   ]},
  {id:`f10s2`, domain:`Process`, task:`R10`, title:`The acceptance letter`,
   text:(s,all,G)=>[`Week sixteen. Cascade's project office sends back the acceptance form unsigned. Their note lists six open items. Four are minor display issues already scheduled for the next release. Two are requests for features that were never in the statement of work: a Spanish language mode and a dictation shortcut.`,`Ochoa calls. <span class="said" data-who="Ochoa">"I want to sign. My team wants everything closed first. Help me out here."</span>`],
   opts:[
    {t:`Fix all six items before asking again, so Cascade has no reason left to withhold sign-off.`,s:0,d:{trust:-2,conf:1,health:-6},after:`The team spends three weeks building two features nobody estimated. Phase one's budget goes red right before the board meeting.`,why:`Absorbing out-of-scope requests to get a signature is scope creep with a bow on it. The acceptance criteria were agreed. New features go through change control as new scope.`},
    {t:`Use the agreed criteria: punch list the four, change requests for the two.`,s:3,best:true,d:{trust:1,conf:5,health:4},after:`Ochoa's team agrees the four minor items can be a dated punch list. The two features become change requests for phase two. Ochoa signs on Thursday.`,why:`Acceptance is judged against the criteria agreed up front. Minor open items can be accepted with owners and dates when the customer agrees. New requests are new scope and go through change control.`},
    {t:`Escalate to Elena so she can call Ochoa's boss and push the signature through faster.`,s:0,d:{trust:0,conf:-5,health:0},after:`Ochoa hears about the call from his own CEO. He signs, and he stops taking Sam's calls for a week.`,why:`Going over a cooperative stakeholder's head damages the relationship you'll need for phase two. Ochoa asked for help, so help him with a clear path.`},
    {t:`Tell Ochoa that by contract the system is accepted after thirty days in production anyway.`,s:1,d:{trust:0,conf:-3,health:2},after:`Technically true, and Ochoa knows it. He signs, but his note to his team calls Halcyon "contractual."`,why:`Deemed acceptance clauses exist, but leaning on them first turns a partner into an opponent. Use the criteria and a punch list to get a real yes.`}
   ]},
  {id:`f10s3`, domain:`People`, task:`P7`, title:`Handing it to Marcus`,
   text:(s,all,G)=>[`Marcus Bell runs Halcyon's support team, and from week nineteen Cascade is his. He's polite about it the way people are polite about a used car. <span class="said" data-who="Marcus">"I've got six agents and a wiki. Your team has three months of tribal knowledge. How is this supposed to work?"</span>`,`Priya is the only person who knows how half the integrations behave at 2 AM. She's also supposed to start on phase two in three weeks.`],
   opts:[
    {t:`Send Marcus the runbooks and architecture diagrams and set a handoff meeting next week.`,s:1,d:{trust:0,conf:0,health:1},after:`The meeting goes fine. Two weeks later a support agent spends four hours on a problem Priya would have fixed in ten minutes.`,why:`Documents carry explicit knowledge. A lot of what Priya knows is tacit: how the system feels when it's about to go wrong. That transfers through shadowing and paired work, not a wiki.`},
    {t:`Plan the transfer: runbooks, paired shifts with Priya, and hypercare exit criteria.`,s:3,best:true,d:{trust:4,conf:2,health:5},after:`Marcus's agents shadow Priya for two weeks, then lead while she watches. Hypercare ends when ticket volume holds under the agreed line for ten days. Marcus signs the handoff himself.`,why:`Knowledge transfer needs both explicit tools and tacit practice, plus clear exit criteria so the handoff ends on evidence. That's how you make sure the knowledge survives the project.`},
    {t:`Keep Priya on Cascade support part time for six months so nothing slips through.`,s:0,d:{trust:-2,conf:1,health:-3},after:`Priya never fully moves to phase two. She's tired, and Marcus's team never learns to stand on its own.`,why:`Tying a key person to the old system indefinitely is a dependency, not a transfer. It delays the next project and leaves the operations team unable to own what they now own.`},
    {t:`Ask Marcus to hire a contractor who already knows clinical AI platforms inside out.`,s:0,d:{trust:-1,conf:0,health:-2},after:`The contractor knows clinical AI. He doesn't know this one. Marcus is out a budget line and still has the same gap.`,why:`New capacity doesn't replace project-specific knowledge. The knowledge lives in your team, so the transfer has to come from your team.`}
   ]},
  {id:`f10s4`, domain:`Process`, task:`R5`, title:`LabelForge, the last invoice`,
   text:(s,all,G)=>[`Joan Pruitt from procurement drops a folder on Sam's desk with obvious pleasure. <span class="said" data-who="Joan">"LabelForge sent their final invoice for the full contract. They were twelve business days late on batch one. The contract has a liquidated damages clause. Also, they say the delay was our fault because we changed the annotation guide."</span>`,`Sam remembers the guide change. It happened, but after the batch was already late.`],
   opts:[
    {t:`Pay the full invoice to keep the vendor relationship warm for phase two labeling.`,s:0,d:{trust:0,conf:-1,health:-3},after:`Finance asks why Halcyon waived a clause worth eighteen thousand dollars. Joan looks personally wounded.`,why:`Waiving contractual remedies without a reason isn't relationship building, it's a control failure. Close the contract according to its terms, then decide about future work on performance data.`},
    {t:`Pull the delivery records, apply the clause, and negotiate the claim with them.`,s:3,best:true,d:{trust:1,conf:2,health:4},after:`The timeline shows the guide change came after the slip. LabelForge's account lead concedes in the second call. Joan closes it with the damages applied and a clean performance record on file.`,why:`Claims are settled with facts and negotiation first. Use the documented timeline, apply the contract as written, and record vendor performance for future procurement decisions.`},
    {t:`Refuse payment until LabelForge admits fault in writing for the whole delay.`,s:0,d:{trust:0,conf:-2,health:-2},after:`LabelForge refuses on principle. The invoice sits open, and so does the project.`,why:`Withholding all payment to extract an admission escalates a dispute you can settle. Pay what's owed, apply the remedy that's documented, and negotiate the rest.`},
    {t:`Hand it to legal and close the project, since claims aren't the project manager's job.`,s:1,d:{trust:0,conf:0,health:-1},after:`Legal is happy to help, but they need Sam's timeline to do anything. The claim drags three weeks longer than it needed to.`,why:`Legal supports claims, but the project manager owns procurement closure on the project and holds the facts. You can't close the project with an open contract.`}
   ]},
  {id:`f10s5`, domain:`Process`, task:`R5`, title:`The rack nobody uses`,
   text:(s,all,G)=>[`Reconciling the IronPeak bill, Sam finds Halcyon is still paying for a spare GPU rack reserved during the burn-in failure. It's been idle for nine weeks. Hal Brennan, the IronPeak account manager, says the reservation runs to the end of the quarter.`,`Joan flags something else: nobody ever ran the procurement review on the IronPeak deal that the purchasing policy requires.`],
   opts:[
    {t:`Check the reservation terms, release the rack if allowed, run the procurement audit.`,s:3,best:true,d:{trust:1,conf:2,health:4},after:`The terms allow release with thirty days' notice. Sam gives it. The audit finds the original deal had no service credits for hardware failures, which goes straight into the template for the next contract.`,why:`Close obligations according to the contract and run the procurement audit to capture lessons. The audit's value is in the next contract, not this one.`},
    {t:`Keep the spare rack through the quarter in case phase two needs extra capacity later.`,s:0,d:{trust:0,conf:-1,health:-3},after:`Phase two doesn't need the capacity for five months. The rack costs more than the Kraków team's last sprint.`,why:`Holding resources for a different project's hypothetical needs isn't closure. Release what this project no longer needs; phase two can request capacity through its own plan.`},
    {t:`Ask Hal to waive the rest of the reservation cost as a goodwill gesture this time.`,s:1,d:{trust:0,conf:0,health:1},after:`Hal gives a ten percent credit and a smile. The audit still doesn't happen.`,why:`Asking is fine, but it skips the actual work: understanding the terms, closing properly, and capturing the lesson that the contract was weak.`},
    {t:`Skip the procurement audit, since the deal is done and the team is busy closing.`,s:0,d:{trust:0,conf:0,health:-2},after:`The next GPU contract is signed from the same template. It has the same missing service credits.`,why:`A procurement audit is how the organization learns from buying. Skipping it means repeating the same contract gaps on the next deal.`}
   ]},
  {id:`f10s6`, domain:`Business Environment`, task:`B6`, title:`Nobody wants a blame session`,
   text:(s,all,G)=>[`Sam books two hours for a lessons learned session. Grant declines: <span class="said" data-who="Grant">"We won. Let's not reopen wounds."</span> Priya asks quietly whether it's going to be about the burn-in failure, because she still thinks that one was partly hers.`,`Tomasz, from Kraków, emails to ask if contractors are invited or if this is a Halcyon-only meeting.`],
   opts:[
    {t:`Run it with Kraków and Cascade's leads, and set a no-blame rule focused on process.`,s:3,best:true,d:{trust:6,conf:2,health:3},after:`Sam opens by naming his own worst decision of the project. Priya talks about the burn-in. Tomasz says the Kraków team was told about changes last for twelve weeks. Every lesson goes into the repository with an owner.`,why:`Lessons learned need everyone who did the work, including vendors and the customer, and they need safety. A blameless format focused on the system is how you get the truth, and the repository is how the organization keeps it.`},
    {t:`Send an anonymous survey instead, so people can be honest without sitting in a meeting.`,s:1,d:{trust:0,conf:0,health:1},after:`The survey gets nine answers, mostly "communication could be better." Nothing specific enough to change.`,why:`Surveys can supplement, but they rarely surface the specific, connected lessons a facilitated conversation does. Safety comes from how you run the session, not from avoiding it.`},
    {t:`Skip it this time, since Grant is right that morale is good and the result was a win.`,s:0,d:{trust:-1,conf:0,health:-3},after:`Six months later the Northgate project hits the same vendor timing problem.`,why:`Successful projects have lessons too, and they're easier to talk about while morale is good. Skipping lessons learned guarantees repeating the same mistakes.`},
    {t:`Hold it with Halcyon staff only, so internal problems stay internal to the company.`,s:0,d:{trust:-3,conf:0,health:0},after:`Tomasz reads the invite list and stops volunteering ideas.`,why:`The people who experienced the problems need to be in the room. Excluding the vendor team loses their view and signals they aren't part of the team.`}
   ]},
  {id:`f10s7`, domain:`People`, task:`P4`, title:`The closing review with Cascade`,
   text:(s,all,G)=>[`Ochoa asks for a closing review in person at Cascade's Fort Collins office. Maria Santos will come. So will Denise Harmon from Cheyenne, who led the nurses' resistance before she became the best champion they had.`,`Grant wants to use the meeting to pitch phase two pricing.`],
   opts:[
    {t:`Let Grant lead with phase two pricing while Cascade's leadership is all in one room.`,s:0,d:{trust:0,conf:-4,health:0},after:`Denise leaves before the pricing slide is over. Ochoa says, pleasantly, that he thought this was a review.`,why:`A closing review is for confirming outcomes and hearing the customer's feedback. Turning it into a sales meeting tells the stakeholders you weren't listening.`},
    {t:`Review outcomes against the objectives and ask for feedback. Sales can wait.`,s:3,best:true,d:{trust:2,conf:6,health:1},after:`Denise tells the story of the first night shift in Cheyenne. Maria brings data on note time. Ochoa asks, on his own, when they can talk about phase two.`,why:`Engaging stakeholders at closure means confirming what was delivered against what was promised and listening to their experience. Good closure creates the next opportunity on its own.`},
    {t:`Send a polished closing report and skip the meeting, since everyone is busy.`,s:1,d:{trust:0,conf:1,health:0},after:`Ochoa reads it. Denise never sees it. The stories that would have shaped phase two stay in Cheyenne.`,why:`A report is part of closure, but stakeholder engagement is a conversation. The people who lived the change have things to tell you that no report captures.`},
    {t:`Invite only Ochoa, since he's the decision maker and the others are operational.`,s:0,d:{trust:0,conf:-2,health:0},after:`Ochoa comes alone and asks where Maria is.`,why:`Engagement includes the stakeholders who were affected and who influenced success, not just the executive. Leaving out the nurse champions loses the most useful feedback.`}
   ]},
  {id:`f10s8`, domain:`Process`, task:`R10`, title:`Letting Kraków go`,
   text:(s,all,G)=>[`The Kraków contract ends with phase one. Tomasz calls on a Friday evening his time. <span class="said" data-who="Tomasz">"My people want to know if they're being let go or if there is more work. Nobody has told them anything. They are reading Slack like tea leaves."</span>`,`Phase two might use some of them, but it isn't funded yet.`],
   opts:[
    {t:`Say nothing until phase two is funded, so nobody hears a promise you can't keep.`,s:0,d:{trust:-5,conf:0,health:-2},after:`Two of the Kraków engineers take other jobs the same week. They were the two you'd have wanted back.`,why:`Silence is worse than uncertain news. People deserve to know when their assignment ends and what's known about what comes next.`},
    {t:`Release them on the planned date, say what's uncertain, and give them honest feedback.`,s:3,best:true,d:{trust:5,conf:1,health:2},after:`Sam joins Tomasz's team meeting at 7 AM Denver time. He tells them the end date, that phase two isn't funded, and what each person did well. He offers references. Four of them say they'd come back.`,why:`Releasing resources is a planned closure activity: clear dates, honest communication about what's unknown, performance feedback, and recognition. It protects people and your organization's reputation.`},
    {t:`Extend their contract a month on overhead to keep the team together for phase two.`,s:0,d:{trust:2,conf:-1,health:-3},after:`Finance asks what budget the extension came from. There isn't one.`,why:`Spending without authorization to hold a team for unfunded work isn't yours to decide. Raise it as a recommendation to the sponsor if retaining them matters.`},
    {t:`Ask Tomasz to tell his team, since they're his employees and his company's contract.`,s:1,d:{trust:-1,conf:0,health:0},after:`Tomasz tells them. They still wonder whether Halcyon valued the work.`,why:`Tomasz is the right person for employment questions, but the project manager owes the team feedback and recognition for the project. Do both.`}
   ]},
  {id:`f10s9`, domain:`People`, task:`P3`, title:`Saying thank you`,
   text:(s,all,G)=>[`Elena gives Sam a budget for recognition. <span class="said" data-who="Elena">"Five thousand dollars. Do something nice."</span>`,`The team is spread across Denver, Kraków, and three Cascade sites. Devin, who almost washed out in week seven, carried the integration testing. Priya held the platform together. Maria made the backlog sane.`],
   opts:[
    {t:`Throw a big party in Denver with an open bar, a slideshow, and a toast for the team.`,s:1,d:{trust:2,conf:0,health:0},after:`The Denver people have a good time. Kraków watches it on a laggy video call at midnight.`,why:`Celebration matters, but recognition works best when it's specific and reaches everyone who contributed, including remote and customer team members.`},
    {t:`Write specific thanks to each person for what they did, remote people included.`,s:3,best:true,d:{trust:6,conf:2,health:1},after:`Devin reads his note twice and asks if he can keep it. Kraków gets a team dinner on Halcyon and individual notes. Maria gets a letter to her CNO.`,why:`Recognition is a leadership tool. It's most effective when it's timely, specific, tied to real contributions, and personal. Fair recognition across the whole team builds the trust you take into the next project.`},
    {t:`Split the money evenly as cash bonuses so it feels fair to everyone on the team.`,s:0,d:{trust:0,conf:0,health:0},after:`Everyone gets a modest check and nobody remembers it a month later.`,why:`Even splits feel fair but say nothing about what people did. Recognition that isn't specific doesn't reinforce the behaviors you want.`},
    {t:`Give the whole budget to Priya, since she carried the most weight on this project.`,s:0,d:{trust:-4,conf:0,health:0},after:`Priya is embarrassed. Devin, who worked every weekend in testing, notices.`,why:`Singling out one person while overlooking others' visible contributions damages team trust. Recognize everyone, and recognize standout work specifically.`}
   ]},
  {id:`f10s10`, domain:`Business Environment`, task:`B6`, title:`From lessons to changes`,
   text:(s,all,G)=>[`The lessons learned session produced thirty-one items. Lena reads the list and sighs. <span class="said" data-who="Lena">"We had a list like this after the last big project. Nobody ever looked at it again."</span>`,`Three items keep showing up: vendors told about changes last, sales dates set before engineering estimates, and no definition of done for hospital readiness.`],
   opts:[
    {t:`File all thirty-one items in the repository so the next project manager can read them.`,s:1,d:{trust:0,conf:0,health:1},after:`They're filed. Nobody reads them.`,why:`The repository matters, but storing lessons isn't improving. Continuous improvement means turning the top lessons into changed practice with owners.`},
    {t:`Turn the top three into process changes with owners and dates, then check they stuck.`,s:3,best:true,d:{trust:3,conf:2,health:5},after:`Grant co-owns a new rule that delivery signs off on any customer date. Joan adds vendor change notices to the contract template. Maria helps write a hospital readiness checklist. Sam checks all three in ninety days.`,why:`That's continuous improvement: small, owned, measured changes, then a check that they worked. Plan, Do, Check, Act, applied to the organization.`},
    {t:`Write a full delivery methodology for Halcyon covering all thirty-one lessons at once.`,s:0,d:{trust:-1,conf:0,health:-2},after:`Two months later the methodology is eighty pages long and in draft.`,why:`Trying to fix everything at once usually fixes nothing. Prioritize the few changes with the most impact and make them stick.`},
    {t:`Ask Elena to mandate that every team read the lessons before any new project.`,s:0,d:{trust:-2,conf:0,health:0},after:`People skim the list to check the box. Behavior doesn't change.`,why:`A reading mandate doesn't change process. Lessons become improvements when someone owns a specific change to how work gets done.`}
   ]},
  {id:`f10s11`, domain:`Process`, task:`R3`, title:`Who measures the benefit`,
   text:(s,all,G)=>[`The business case promised that AI drafting would cut nurse documentation time by thirty percent within a year. The first three hospitals show twenty-two percent after six weeks, which is promising and nowhere near proven.`,`Elena asks Sam to keep the project open until the thirty percent is confirmed, so the board sees the full win.`],
   opts:[
    {t:`Keep the project open with a small team measuring results until the target is met.`,s:0,d:{trust:0,conf:-1,health:-4},after:`The project stays open for eight months with a skeleton team and a burn rate nobody can explain.`,why:`Benefits often arrive after the project ends. Holding the project open to wait for them ties up resources and blurs accountability.`},
    {t:`Close it and hand benefit tracking to a named Cascade owner with a measurement plan.`,s:3,best:true,d:{trust:1,conf:4,health:4},after:`Cascade's chief nursing officer owns the measure, with Maria running it quarterly. Halcyon gets the reports. The board sees the plan and the twenty-two percent, and that's enough.`,why:`Benefits realization belongs to the business after transition. The project's job is to deliver the capability and set up measurement with a clear owner, a baseline, and a schedule.`},
    {t:`Report the twenty-two percent as the final result and close without further measurement.`,s:1,d:{trust:0,conf:0,health:2},after:`It's honest, but nobody ever learns whether the thirty percent happened.`,why:`Closing is right, but dropping measurement means the organization can't confirm the value it paid for. Transfer the measurement, don't end it.`},
    {t:`Project the trend forward and report thirty percent to the board as achieved.`,s:0,d:{trust:-2,conf:-6,health:0},after:`At the next board meeting Victor Adeyemi asks for the data behind the thirty percent. There isn't any.`,why:`Reporting a forecast as a result is a misrepresentation. Report what's measured, show the trend, and say what's still unproven.`}
   ]},
  {id:`f10s12`, domain:`Process`, task:`R10`, title:`The last signature`,
   text:(s,all,G)=>[`Week eighteen, Thursday. Acceptance signed, Marcus owns support, LabelForge and IronPeak closed, Kraków released, lessons filed with owners. One thing left.`,`Lena asks, <span class="said" data-who="Lena">"Do we really need a formal closeout? Everybody knows it's done."</span>`],
   opts:[
    {t:`Agree, since everyone knows it's done, and move the team straight to phase two.`,s:0,d:{trust:0,conf:-2,health:-3},after:`Three months later finance is still charging hours to the Cascade project code.`,why:`Without formal closure, accounts stay open, records aren't archived, and nobody can say the project officially ended. Informal endings leak cost and confusion.`},
    {t:`Write the final report, get Elena's sign-off, close the accounts, and archive it all.`,s:3,best:true,d:{trust:1,conf:4,health:4},after:`The final report is four pages: what was delivered, cost and schedule against baseline, benefits plan, and the top lessons. Elena signs it. Finance closes the code. The documents go to the archive.`,why:`Formal closure means a final report, sponsor sign-off that the project is complete, closed financial accounts, and archived records. It's the last tool count.`},
    {t:`Send the team a "project complete" email and close the project's Slack channel.`,s:1,d:{trust:1,conf:0,health:0},after:`The team appreciates it. Finance and the archive never hear about it.`,why:`Communicating the end matters, but closure needs the sponsor's formal sign-off, the financial and contract accounts closed, and records archived.`},
    {t:`Ask Cascade to send a formal closure letter so the project can be closed on their word.`,s:0,d:{trust:0,conf:0,health:-1},after:`Cascade already signed acceptance. Their closure letter doesn't close anything inside Halcyon.`,why:`The customer accepts deliverables. The sponsor inside the performing organization formally closes the project.`}
   ]}
 ],
 drills:[
  {after:`f10s4`, title:`Closing the LabelForge contract`,
   setup:[`Joan pulls the numbers. LabelForge's fixed price contract is worth $240,000. The liquidated damages clause is $1,500 per business day late, capped at 10 percent of the contract value. Batch one was 12 business days late, and the timeline shows the delay was theirs.`,`Halcyon has already paid $160,000 in milestone payments.`],
   table:[[`Item`,`Value`],[`Contract value`,`$240,000`],[`Damages rate`,`$1,500 per business day`],[`Cap`,`10% of contract value`],[`Days late`,`12`],[`Already paid`,`$160,000`]],
   fields:[{label:`Liquidated damages owed by LabelForge ($)`,answer:18000,tol:1},{label:`Final payment Halcyon owes LabelForge ($)`,answer:62000,tol:1}],
   solution:[`Damages = 12 days × $1,500 = $18,000. The cap is 10% × $240,000 = $24,000, so the full $18,000 applies.`,`Total owed = $240,000 − $18,000 = $222,000. Already paid $160,000, so the final payment is $222,000 − $160,000 = $62,000.`,`On the exam, check whether a cap applies before you finalize any penalty, and remember that damages reduce the amount owed, they don't replace closing the contract.`]}
 ],
 exercise:{after:`f10s12`, title:`Put the closing steps in the right bucket`, intro:`For each activity, pick which part of closure it belongs to.`,
  items:[
   {prompt:`Cascade signs the form confirming the agents meet the agreed criteria.`,choices:[`Final acceptance`,`Transition`,`Contract closure`,`Administrative closure`,`Lessons learned`],answer:0,why:`Formal customer confirmation against agreed criteria is final acceptance.`},
   {prompt:`Marcus's support agents shadow Priya, then lead while she watches.`,choices:[`Final acceptance`,`Transition`,`Contract closure`,`Administrative closure`,`Lessons learned`],answer:1,why:`Transferring ownership and knowledge to operations is transition.`},
   {prompt:`Joan applies the damages clause and makes LabelForge's final payment.`,choices:[`Final acceptance`,`Transition`,`Contract closure`,`Administrative closure`,`Lessons learned`],answer:2,why:`Settling claims and final payments are part of contract closure.`},
   {prompt:`Finance closes the project's cost code and records go to the archive.`,choices:[`Final acceptance`,`Transition`,`Contract closure`,`Administrative closure`,`Lessons learned`],answer:3,why:`Closing accounts and archiving records is administrative closure.`},
   {prompt:`The team names the three changes Halcyon should make before the next project.`,choices:[`Final acceptance`,`Transition`,`Contract closure`,`Administrative closure`,`Lessons learned`],answer:4,why:`Capturing what to do differently next time is lessons learned.`},
   {prompt:`IronPeak's idle rack is released with thirty days' notice under the terms.`,choices:[`Final acceptance`,`Transition`,`Contract closure`,`Administrative closure`,`Lessons learned`],answer:2,why:`Ending a vendor obligation under the contract's terms is contract closure.`}
  ]},
 quiz:[
  {q:`A project is cancelled halfway through by the sponsor. What should the project manager do next?`,opts:[`Release the team immediately so they can start other work`,`Follow the closing process and document the status`,`Finish the current sprint so the work isn't wasted`,`Ask the sponsor to reconsider using the business case`],a:1,why:`Cancelled projects are still closed formally: document what was done and why it ended, release resources, close contracts, and archive.`,task:`R10`,domain:`Process`},
  {q:`The customer refuses to sign acceptance until a feature that was never in scope is added. What should the project manager do?`,opts:[`Add the feature to secure acceptance quickly`,`Escalate to the customer's executive sponsor`,`Review the criteria and log the request as a change`,`Close the project without the customer's signature`],a:2,why:`Acceptance is judged against agreed criteria. New features are new scope and go through change control.`,task:`R10`,domain:`Process`},
  {q:`Which activity should happen before the project team is released?`,opts:[`Capturing lessons learned with the team`,`Archiving the final project documents`,`Sending the final invoice to the customer`,`Closing the project cost accounts`],a:0,why:`Lessons learned need the people who did the work, so capture them before releasing the team.`,task:`R10`,domain:`Process`},
  {q:`A seller disputes a contractual penalty for late delivery. What is the preferred first approach?`,opts:[`Begin litigation to enforce the contract`,`Waive the penalty to preserve goodwill`,`Withhold all payment until they agree`,`Negotiate a settlement using the records`],a:3,why:`Claims are best resolved through negotiation using documented facts. Formal dispute processes come only if negotiation fails.`,task:`R5`,domain:`Process`},
  {q:`What is the main purpose of a procurement audit at closure?`,opts:[`To find who caused the vendor problems`,`To learn from the process for future contracts`,`To confirm the vendor's invoices are correct`,`To check the vendor's financial statements`],a:1,why:`A procurement audit reviews the whole procurement process to capture lessons for future buying.`,task:`R5`,domain:`Process`},
  {q:`Benefits of a project are expected to appear twelve months after go-live. What should the project manager do at closure?`,opts:[`Keep the project open until benefits are confirmed`,`Report projected benefits as achieved`,`Transfer benefits measurement to a business owner`,`Remove benefits from the final report`],a:2,why:`Benefits realization continues after closure. Assign a business owner with a baseline and measurement plan.`,task:`R3`,domain:`Process`},
  {q:`During a lessons learned session, team members are reluctant to talk about mistakes. What should the project manager do?`,opts:[`Ask the sponsor to require full participation`,`Model openness and keep the focus on process`,`Collect anonymous surveys instead of meeting`,`Skip the mistakes and record only successes`],a:1,why:`Psychological safety comes from a blameless format and leaders modeling openness. Focus on the system, not individuals.`,task:`B6`,domain:`Business Environment`},
  {q:`A team captured many lessons learned on its last project, but nothing changed afterward. What would best support continuous improvement?`,opts:[`Store the lessons in a searchable repository`,`Require each project to read prior lessons`,`Write a complete methodology covering every lesson`,`Turn the top lessons into owned process changes`],a:3,why:`Continuous improvement means owned, measured changes to how work is done, then checking the changes worked.`,task:`B6`,domain:`Business Environment`},
  {q:`Operations staff are taking over a new system. Which approach best transfers tacit knowledge?`,opts:[`Paired work and shadowing with experts`,`A detailed architecture document`,`A recorded walkthrough of the system`,`A frequently asked questions page`],a:0,why:`Tacit knowledge transfers through shared experience such as shadowing and paired work. Documents carry explicit knowledge.`,task:`P7`,domain:`People`},
  {q:`How should a hypercare period after go-live end?`,opts:[`When the project budget runs out`,`When agreed exit criteria are met`,`After a fixed thirty days in every case`,`When the project team is reassigned`],a:1,why:`Hypercare should end on evidence, using exit criteria agreed in advance, such as ticket volume or defect rates.`,task:`R10`,domain:`Process`},
  {q:`A vendor team's contract is ending and future work is uncertain. What should the project manager do?`,opts:[`Wait until future work is confirmed to say anything`,`Extend their contract to keep the team intact`,`Communicate the end date and what is still unknown`,`Let the vendor manager handle all communication`],a:2,why:`Releasing resources includes clear, honest communication about dates and uncertainty, plus feedback and recognition.`,task:`R10`,domain:`Process`},
  {q:`Which recognition approach is most effective for a distributed team?`,opts:[`Specific recognition for every contributor`,`Equal cash bonuses for every team member`,`A single award for the top performer`,`A celebration held at headquarters`],a:0,why:`Recognition works best when it's specific, timely, personal, and fair to everyone who contributed, including remote members.`,task:`P3`,domain:`People`},
  {q:`At a closing review, a sales executive wants to pitch the next phase to the customer. What should the project manager do?`,opts:[`Allow the pitch while the leadership is in the room`,`Cancel the review and send a written report`,`Invite only the customer's executive to the review`,`Keep the review on outcomes and feedback first`],a:3,why:`A closing review confirms outcomes and gathers feedback. Selling during it undermines stakeholder trust.`,task:`P4`,domain:`People`},
  {q:`Who typically provides formal sign-off that a project is closed in the performing organization?`,opts:[`The customer's procurement lead`,`The project sponsor`,`The project team lead`,`The operations manager`],a:1,why:`The customer accepts deliverables, but the sponsor in the performing organization formally closes the project.`,task:`R10`,domain:`Process`},
  {q:`A fixed price contract includes a damages cap of 5 percent of $400,000. The seller is 30 days late at $1,000 per day. What are the damages?`,opts:[`$30,000, the full daily amount`,`$400,000, the full contract value`,`$20,000, the capped amount`,`$10,000, half the capped amount`],a:2,why:`30 × $1,000 = $30,000, but the cap is 5% × $400,000 = $20,000, so damages are $20,000.`,task:`R5`,domain:`Process`}
 ],
 closing:(s,all,G)=>[
  `Friday of week eighteen the board met for two hours. Phase one got eleven minutes, most of them spent on the benefits plan. Victor Adeyemi, the newest board member, asked one question: <span class="said" data-who="Victor">"Who owns the thirty percent now?"</span> Sam told him. Victor wrote it down and moved on, which Ruth told Sam later was the highest compliment Victor gave.`,
  `After the meeting Elena asked Sam to stay. She didn't sit down this time either.`,
  `<span class="said" data-who="Elena">"I want to build a delivery office,"</span> she said. <span class="said" data-who="Elena">"Every customer project, every vendor, one person who tells me the truth about all of it. Director of Delivery. I want it to be you."</span>`,
  `Sam started to say he'd never run more than one project. Elena held up a hand. <span class="said" data-who="Elena">"Eighteen weeks ago you'd never run one. Think about it over the weekend. Talk to Dana."</span>`,
  (s.score>=26?`In the parking lot Ruth was leaning on her car, which was not a coincidence. <span class="said" data-who="Ruth">"Flight directors don't get promoted for the launches that go well,"</span> she said. <span class="said" data-who="Ruth">"They get promoted for the ones where they told the truth when it was expensive. Go home, Sam."</span>`:`In the parking lot Ruth was leaning on her car. <span class="said" data-who="Ruth">"You'll be good at it,"</span> she said. <span class="said" data-who="Ruth">"Not because you were perfect. Because you kept counting the tools. Go home, Sam."</span>`),
  `He drove home the long way, past the airport, and watched a regional jet climb out over the plains. Dana was on the porch with two beers and the sticky note from the coffee maker. <span class="said" data-who="Dana">"Okay,"</span> she said. <span class="said" data-who="Dana">"Alma. And whatever Elena said. Both."</span>`
 ],
 episode:{src:`audio/full-ch10.mp3`, len:`about 35 minutes`},
 next:`The Offer`
});
