// Full Course, chapter 11. Format: see full/BIBLE.md.
(window.HALCYON_FULL=window.HALCYON_FULL||[]).push({
 num:11, part:`Part Two: The PMO`, title:`The Offer`, weeks:`Month 6`,
 tasks:[`B1`,`P1`,`R6`,`B8`,`P4`],
 cast:[
  [`Dana Okafor`,`Sam's wife. High school chemistry teacher. Dry humor, notices when he isn't sleeping.`],
  [`Victor Adeyemi`,`New Halcyon board member from a private equity firm. Precise, patient, wants proof.`],
  [`Keisha Moore`,`Project manager Sam hires for phase two. Came from a hospital IT department.`],
  [`Rob Delgado`,`Halcyon's longest serving project manager. Allergic to new process.`]
 ],
 opening:[
  `Dana listened to the whole thing on the porch without interrupting, which was how Sam knew she was taking it seriously. Alma in Greeley. The board. Elena not sitting down. When he finished she turned her beer bottle a quarter turn on the railing, the way she did when a student gave an answer that was almost right.`,
  `<span class="said" data-who="Dana">"You know what you were like in March,"</span> she said. <span class="said" data-who="Dana">"You'd come home and fix the dishwasher at nine at night because it was the only thing all day you could actually fix with your hands."</span>`,
  `<span class="said" data-who="Sam">"The dishwasher was broken."</span>`,
  `<span class="said" data-who="Dana">"The dishwasher was fine, Sam."</span> She smiled. <span class="said" data-who="Dana">"Here's my question. If you take this, are you going to try to run every project yourself? Because that's the job you'd hate. And it's the one you'd be bad at."</span>`,
  `He thought about Ray Mendez, his old flight chief, who had been offered a commission twice and turned it down both times. <span class="said" data-who="Ray">"I'd rather keep twelve jets flying than brief one general about them,"</span> Ray used to say. Sam had always thought that was wisdom. Sitting on the porch, he wondered for the first time if it had partly been fear.`,
  `<span class="said" data-who="Sam">"No,"</span> Sam said. <span class="said" data-who="Sam">"The job is making other people able to run them. I'd be building the thing, not flying it."</span>`,
  `<span class="said" data-who="Dana">"Then take it,"</span> Dana said. <span class="said" data-who="Dana">"And put that sentence somewhere you'll see it every morning."</span>`,
  `Monday he told Elena yes. Her reply came before he was back at his desk.`,
  `<prop type="email" from="Elena Vasquez" to="Sam Okafor" time="9:41 AM" subject="Director of Delivery">Good. Start date is the first. You own how Halcyon delivers, not what each project delivers. The PMs are yours to grow, not yours to replace.<br>One more thing. The board added a seat last week. Victor Adeyemi wants thirty minutes with you on Wednesday. Be ready for numbers.<br>E.</prop>`,
  `Tuesday he wrote the sentence on an index card and taped it above his monitor. Wednesday he met Victor Adeyemi.`
 ],
 lesson:{
  title:`PMOs, governance, and choosing the right projects`,
  sections:[
   {h:`What a PMO is for`,
    body:[`A project management office is the part of an organization that standardizes how projects are run and helps them succeed. PMBOK describes three broad types by how much control they hold. A supportive PMO provides templates, training, and lessons learned, and has little control. A controlling PMO requires compliance with its methods, templates, and reviews, and has moderate control. A directive PMO manages the projects directly, and has high control.`,
          `There is no best type. The right one depends on the organization's maturity, culture, and what problem leadership is trying to solve. A company like Halcyon, with a few strong project managers and a habit of selling dates before estimating them, needs enough control to fix the date problem without drowning good teams in paperwork. Starting lighter and adding control where the data shows it's needed usually beats announcing a heavy process on day one.`,
          `Agile organizations sometimes call this a value delivery office or an agile center of excellence. The function is similar: coach teams, set minimum standards, connect strategy to the work, and make performance visible.`],
    terms:[[`Supportive PMO`,`Provides templates, training, and guidance. Low control.`],[`Controlling PMO`,`Requires compliance with methods and reviews. Moderate control.`],[`Directive PMO`,`Directly manages projects. High control.`]],
    exam:`Questions often describe a PMO's behavior and ask what type it is. "Provides templates and best practices on request" is supportive. "Audits projects for compliance" is controlling. "Assigns and manages the project managers" is directive.`},
   {h:`Governance`,
    body:[`Governance is the framework of decision rights, escalation paths, approval thresholds, and reviews that guides a project and connects it to the organization. It answers questions like: who can approve a change over fifty thousand dollars, who decides whether to continue after a phase, and where does a project manager take a risk that's beyond their authority.`,
          `Good governance is tailored. A small internal project might need a sponsor and a monthly check. A large customer contract might need a steering committee, phase gates, and a change control board. Governance should make decisions faster and clearer, not slower. If teams wait weeks for approvals that could be delegated, the governance is wrong.`,
          `On the July 2026 exam outline, defining and establishing project governance is its own task in the Business Environment domain. Expect questions where the right answer is to clarify decision rights or escalation paths before acting.`],
    terms:[[`Phase gate`,`A review at the end of a phase where the sponsor or a board decides to continue, change, or stop.`],[`Steering committee`,`A group of senior stakeholders who provide direction and make key decisions for a project or program.`],[`Escalation path`,`The agreed route for raising issues beyond a person's authority.`]],
    exam:`If a project manager hits a decision outside their authority, the answer is to use the escalation path defined in governance, not to make the decision anyway or to sit on it.`},
   {h:`Business cases and project selection`,
    body:[`A business case justifies a project: the problem or opportunity, the options considered, the expected costs and benefits, the risks, and the assumptions. It's a living document. If the facts behind it change, the business case gets revisited, and sometimes the right answer is to stop.`,
          `Organizations compare projects with financial and non-financial criteria. Net present value discounts future cash flows to today's dollars: NPV is the present value of the benefits minus the present value of the costs. Positive NPV means the project earns more than the discount rate. When choosing between projects, the higher NPV wins; the number of years is already built into the calculation, so don't adjust for it again. Internal rate of return is the discount rate at which NPV equals zero; higher is better. The payback period is how long until cumulative cash inflows cover the investment; shorter is better, but it ignores what happens after payback. The benefit cost ratio divides benefits by costs; above 1 is good. Opportunity cost is the value of the option you didn't choose.`,
          `Non-financial criteria matter just as much: strategic fit, regulatory need, risk, and capacity. Many organizations use a weighted scoring model to combine them.`],
    terms:[[`Net present value`,`Present value of benefits minus present value of costs, using a discount rate.`],[`Payback period`,`Time until cumulative inflows recover the initial investment.`],[`Benefit cost ratio`,`Present value of benefits divided by present value of costs.`],[`Opportunity cost`,`The value of the best alternative you gave up.`]],
    exam:`Classic traps: choosing a project by its project length when NPV is given (NPV already accounts for time), and preferring the shorter payback when NPV and payback disagree. When financial measures conflict, NPV is usually the best single measure.`},
   {h:`Watching the world outside`,body:[`Governance also has to look outward. Victor's question to Sam, what's changing outside this building, is the external business environment task on the 2026 outline. Markets shift, competitors launch, regulators publish guidance, and customers' budgets tighten, and any of those can make a well run project the wrong project.`,`A simple structure is PESTLE: political, economic, social, technological, legal, and environmental factors. A delivery office can run a short quarterly scan with an owner for each category. Each finding either becomes a risk with a trigger, prompts a business case review, or is dropped on purpose. The habit matters more than the format.`],terms:[[`PESTLE`,`Political, economic, social, technological, legal, and environmental factors used to scan the world outside the project.`]],exam:`When a question asks how to stay ahead of market or regulatory change, look for a regular, owned scan that feeds the risk register and business case, not a one time report.`},
  {h:`A common vision`,
    body:[`Developing a common vision is the first People task on the 2026 outline. A vision isn't a slogan. It's a shared picture of what success looks like and why it matters, built with the people who'll do the work so they recognize themselves in it. A delivery office imposed from the top gets compliance. A delivery office the project managers helped design gets ownership.`,`In practice that means asking before telling. Ask the team what's gone wrong before, what good would look like, and what they'd keep. Write the vision in their words, keep it short enough to remember, and connect every later standard back to it. When someone asks why a rule exists, the answer should point to the vision, not to the person who wrote the rule. A vision that people can repeat from memory, in their own words, is doing its job.`],
    terms:[[`Vision`,`A shared, concrete picture of the future the team is working toward.`]],
    exam:`When a team resists a new direction, the exam usually prefers involving them in shaping it over mandating it.`}
  ],
  video:[`UJT18LPYZZw`,`Project Return Forecasting with FV, NPV and IRR`,`David McLachlan`,`10:09`]
 },
 scenes:[
  {id:`f11s1`, domain:`Business Environment`, task:`B1`, title:`What kind of office`,
   text:(s,all,G)=>[`Elena's version of the delivery office fits in one sentence. <span class="said" data-who="Elena">"Every project goes through you, every date gets your sign-off, every PM reports to you. Done."</span>`,`Halcyon has four project managers. Two are good. One, Rob Delgado, has been there eleven years and considers templates a personal insult. The real problem, the one that nearly sank Cascade, was sales committing dates nobody estimated.`],
   opts:[
    {t:`Build exactly what Elena described, since the CEO is the sponsor of the new office.`,s:0,d:{trust:-4,conf:1,health:-1},after:`Rob files a complaint about the new approval form within a week. Two good PMs start wondering out loud about other jobs.`,why:`A sponsor's request is a starting point, not a design. A heavy directive PMO imposed on a low maturity culture usually gets resistance, not results.`},
    {t:`Start light on control, but require delivery sign-off on any customer date.`,s:3,best:true,d:{trust:3,conf:4,health:3},after:`Elena hesitates, then agrees when Sam shows her that one rule would have prevented the Cascade date problem. The PMs get templates they can use or ignore, and one rule they can't.`,why:`Tailor the PMO to the organization's maturity and the actual problem. Control goes where the data shows it's needed. That's governance that helps instead of slowing things down.`},
    {t:`Make it purely supportive, offering templates and coaching with no required steps.`,s:1,d:{trust:3,conf:-1,health:0},after:`The PMs like it. Grant sells a date for a new pilot the following week without asking anyone.`,why:`A purely supportive PMO leaves the root problem untouched. Some control is needed where the organization has a known, costly failure.`},
    {t:`Run a six week maturity assessment before deciding on any PMO structure at all.`,s:0,d:{trust:0,conf:-3,health:-2},after:`Six weeks in, Elena asks what the delivery office has done. The answer is a survey.`,why:`Assessment is useful, but you already have strong evidence of the main problem. Acting on known issues while you learn beats waiting for a perfect diagnosis.`}
   ]},
  {id:`f11s2`, domain:`Business Environment`, task:`B1`, title:`Who decides what`,
   text:(s,all,G)=>[`In his first week Sam gets nineteen requests for decisions. Some are trivial (a PM asking if she can move a demo by a day). Some aren't (a vendor contract over two hundred thousand dollars). Everyone is sending everything to him because nobody knows what they're allowed to decide.`],
   opts:[
    {t:`Decide everything himself for a month to learn the patterns, then delegate later.`,s:0,d:{trust:-2,conf:0,health:-3},after:`Sam becomes the bottleneck. It's Theo all over again, except now it's him.`,why:`Centralizing every decision creates a constraint. Governance should define decision rights so most decisions are made close to the work.`},
    {t:`Write decision rights with thresholds and escalation paths for each level.`,s:3,best:true,d:{trust:3,conf:3,health:5},after:`One page. PMs decide schedule moves under a week and spending under ten thousand. Sam takes up to one hundred thousand. Elena and the steering group take the rest. Requests drop from nineteen to four.`,why:`Defining decision rights, thresholds, and escalation paths is the core of project governance. It speeds decisions up by putting them in the right place.`},
    {t:`Tell the PMs to use their judgment and only bring him things that truly matter.`,s:1,d:{trust:2,conf:0,health:0},after:`Each PM has a different idea of what matters. One brings everything. One brings nothing, including a contract she shouldn't have signed.`,why:`Trusting judgment is good, but without explicit thresholds people guess differently. Governance makes the boundaries clear.`},
    {t:`Send everything over fifty thousand dollars to Elena so the CEO controls all spend.`,s:0,d:{trust:0,conf:-2,health:-2},after:`Elena gets eleven approvals in a week and asks why she has a delivery office.`,why:`Pushing decisions up past the level that needs them slows everything down. Thresholds should match risk and authority, not default to the top.`}
   ]},
  {id:`f11s3`, domain:`People`, task:`P1`, title:`Rob doesn't want a vision`,
   text:(s,all,G)=>[`Sam calls the four project managers together to talk about what the delivery office is for. Rob Delgado arrives with a coffee and a look. <span class="said" data-who="Rob">"I've seen four of these. They start with a vision statement and end with a forty page template. Can we skip to the part where you tell us what to fill out?"</span>`,`Keisha Moore, two weeks into the job, watches Sam to see what he'll do.`],
   opts:[
    {t:`Present the vision Elena approved and explain clearly how it will help each of them.`,s:1,d:{trust:0,conf:1,health:0},after:`It's a fine vision. Rob nods politely and changes nothing.`,why:`A vision handed down gets polite agreement. The 2026 outline treats a common vision as something you develop with the team so they own it.`},
    {t:`Agree with Rob, skip the vision talk, and hand out the new templates to get started.`,s:0,d:{trust:-1,conf:0,health:-1},after:`Rob is pleased for about a day. Then he sees the templates and is exactly as unhappy as he predicted.`,why:`Skipping the why leaves the team guessing at the purpose of every rule. People resist process they don't understand.`},
    {t:`Ask them to describe the worst project week they've had, then design the fix together.`,s:3,best:true,d:{trust:6,conf:1,health:3},after:`Rob tells a story about a date sales set in 2019. It's almost word for word the Cascade problem. By the end of the hour the PMs have written the date rule themselves, and Rob wrote the best line in it.`,why:`A shared vision starts from the team's real experience. When people help define what success looks like, they own it. Resistance often turns into leadership when people are heard.`},
    {t:`Meet with Rob privately afterward to get his support before the next group meeting.`,s:1,d:{trust:2,conf:0,health:0},after:`Rob appreciates the conversation. The other PMs feel like they missed the real meeting.`,why:`One-on-one conversations help, but the vision has to be built with the whole team, in the open, so everyone shares it.`}
   ]},
  {id:`f11s4`, domain:`Process`, task:`R6`, title:`Grant's phase two shortcut`,
   text:(s,all,G)=>[`Cascade wants discharge instructions, the feature that was pushed to phase two. Grant has a verbal yes from Ochoa. <span class="said" data-who="Grant">"They'll pay. We don't need a business case. Business cases are for projects nobody wants."</span>`,`The build needs about five hundred thousand dollars of engineering and infrastructure. Cascade's contract would bring in revenue over three years.`],
   opts:[
    {t:`Write a business case with the costs, benefits, NPV, risks, and assumptions.`,s:3,best:true,d:{trust:1,conf:4,health:4},after:`The case is positive, but it surfaces an assumption nobody had checked: the third year of revenue depends on Cascade renewing. That becomes a named risk with an owner.`,why:`A business case justifies the investment and makes assumptions visible. Even a project the customer wants needs a case, because it's how the organization chooses between this and other uses of its money.`},
    {t:`Skip the business case, since the customer already wants it and is willing to pay.`,s:0,flag:`nobusinesscase`,d:{trust:0,conf:-2,health:-3},after:`Halcyon starts building. Two months later Victor asks for the return on the project. Nobody knows. Victor writes something in the small notebook he carries and doesn't say what.`,why:`Customer demand isn't the same as a sound investment. Without a business case there's no baseline to judge the project or to decide later if it should continue.`},
    {t:`Ask Cascade's finance team to write the business case, since they'll benefit most.`,s:0,d:{trust:0,conf:-1,health:-1},after:`Cascade's business case is about Cascade's savings. It says nothing about Halcyon's costs.`,why:`The performing organization needs its own business case to decide whether to invest its resources. The customer's case answers a different question.`},
    {t:`Approve the project now and write the business case later during planning.`,s:1,d:{trust:0,conf:0,health:-1},after:`The case gets written after the team is hired. It's tilted to justify a decision already made.`,why:`A business case written after the decision tends to confirm the decision. It should inform the choice to start.`}
   ]},
  {id:`f11s5`, domain:`Process`, task:`R6`, title:`Three projects, one team`,
   text:(s,all,G)=>[`Halcyon has capacity for one new major project this quarter. There are three candidates: Cascade discharge instructions, a mobile app for nurses, and an internal billing system rebuild. Each sponsor is sure theirs is the obvious choice.`,...((s.flags.nobusinesscase||G.nobusinesscase)?[`Discharge instructions is already being built, so it isn't even on the table. That's the problem. Nobody can say what it returns, and the other two sponsors notice.`]:[`Keisha has the discharge instructions numbers on one page, which is more than the other two sponsors have.`,`<prop type="doc" title="Discharge instructions: business case summary">Investment: $500,000 up front.<br>Net cash inflows: $200,000, $250,000, $250,000 over three years.<br>NPV at 10 percent: $76,258. Benefit cost ratio: 1.15. Payback: 2.2 years.<br>Key assumption: year three depends on Cascade renewing.</prop>`]),`Then Victor emails Sam.`,`<prop type="email" from="Victor Adeyemi" to="Sam Okafor" time="7:05 AM" subject="Three projects">How are you going to choose? I'd like to understand the method before I hear the answer.</prop>`],
   opts:[
    {t:`Pick whichever has the highest NPV, since money is the clearest measure of value.`,s:1,d:{trust:0,conf:1,health:1},after:`Discharge instructions wins on NPV. It's probably right, but the mobile app sponsor points out that NPV ignored a regulatory deadline.`,why:`NPV is the strongest single financial measure, but selection should also weigh strategy, risk, compliance, and capacity.`},
    {t:`Score all three on agreed criteria and let the steering group decide.`,s:3,best:true,d:{trust:2,conf:5,health:3},after:`The steering group agrees the criteria first, then sees the scores. Discharge instructions wins, the mobile app is deferred one quarter, and the billing rebuild is cancelled. Nobody likes it, everybody understands it.`,why:`Project selection uses agreed criteria, combining financial measures like NPV with strategic fit and risk, decided by the right governance body. Victor asked about the method because the method is what makes the answer legitimate.`},
    {t:`Ask Elena to choose, since she knows the company strategy better than anyone.`,s:0,d:{trust:0,conf:-2,health:0},after:`Elena chooses the mobile app because she liked the demo. Victor asks how it was chosen.`,why:`Leaving selection to one executive's preference skips the criteria that make the choice defensible and repeatable.`},
    {t:`Run all three with smaller teams so no sponsor is disappointed this quarter.`,s:0,d:{trust:-1,conf:-1,health:-6},after:`All three projects crawl. None of them finishes on time.`,why:`Starting more work than you have capacity for slows everything down. Selection exists to choose, so the chosen work can finish.`}
   ]},
  {id:`f11s6`, domain:`Business Environment`, task:`B1`, title:`Who signs the charter`,
   text:(s,all,G)=>[`Discharge instructions is approved. Keisha Moore will manage it. Sam drafts the charter and asks who should sign it. Grant volunteers. Elena says she's too busy. Lena says it's an engineering project, so maybe her.`],
   opts:[
    {t:`Have Keisha sign it herself, since she's the project manager and knows the details.`,s:0,d:{trust:0,conf:-1,health:-3},after:`The charter has a signature but no authority. The first time Keisha needs a resource from Lena's team, it means nothing.`,why:`The project manager is named and authorized by the charter. The charter itself is issued by the sponsor, who has the authority to commit resources.`},
    {t:`Ask Elena to name the sponsor, who then issues the charter naming Keisha as PM.`,s:3,best:true,d:{trust:2,conf:3,health:4},after:`Elena names Grant as executive sponsor, to everyone's surprise including Grant's. Grant signs the charter. He reads it first, which Sam takes as a good sign.`,why:`The sponsor issues the charter and authorizes the project manager. When it's unclear who the sponsor is, clarifying that through governance is the first step.`},
    {t:`Have all three executives sign it so everyone shares ownership of the project.`,s:1,d:{trust:1,conf:1,health:0},after:`Three signatures, no single sponsor. When a decision is needed, all three wait for the others.`,why:`Shared signatures can look like shared ownership but often mean no clear accountability. A project needs one accountable sponsor.`},
    {t:`Skip the charter, since phase two continues phase one and has the same sponsor.`,s:0,d:{trust:0,conf:-1,health:-2},after:`Nobody's sure who the sponsor is. It turns out nobody is.`,why:`A new project needs its own charter. Phase one's sponsor and authority ended when that project closed.`}
   ]},
  {id:`f11s7`, domain:`Business Environment`, task:`B8`, title:`Victor's first question`,
   text:(s,all,G)=>[`At Victor Adeyemi's first full board meeting he asks Sam a question nobody else has asked. <span class="said" data-who="Victor">"What's changing outside this building that could make your projects wrong? I don't mean risks inside the plan. I mean the world."</span>`,`Sam has an answer for the plan. He doesn't have one for the world.`],
   opts:[
    {t:`Say the project risk registers already cover everything that could go wrong.`,s:0,d:{trust:0,conf:-4,health:0},after:`Victor smiles politely. <span class="said" data-who="Victor">"Then I'd like to read them."</span> They don't mention competitors or regulation once.`,why:`Project risk registers focus inward. Evaluating the external business environment is its own task: market, regulatory, technology, and economic changes that could affect objectives.`},
    {t:`Admit the gap and commit to a regular scan of market, regulatory, and tech change.`,s:3,best:true,d:{trust:1,conf:5,health:3},after:`Victor nods. Two weeks later Sam brings a one page external scan: two competitors, a state guidance in draft, and a hospital budget squeeze. Victor reads it twice and asks to see it every quarter.`,why:`Honest acknowledgment plus a concrete plan builds credibility. Scanning the external environment, often with a tool like PESTLE, feeds risks and business case updates.`},
    {t:`Ask Grant to answer, since sales sees the market more closely than delivery does.`,s:1,d:{trust:0,conf:0,health:0},after:`Grant talks about competitors confidently and gets two of the three facts wrong.`,why:`Sales has useful market insight, but the delivery office should own how external changes affect projects and their business cases.`},
    {t:`Promise a full market research report from an outside firm for the next meeting.`,s:0,d:{trust:0,conf:-1,health:-2},after:`The report costs forty thousand dollars and arrives after the next meeting.`,why:`External scanning should be a regular, lightweight practice owned inside the organization, not a one-time expensive report.`}
   ]},
  {id:`f11s8`, domain:`People`, task:`P4`, title:`Coffee with Victor`,
   text:(s,all,G)=>[`Victor asks Sam to coffee. He's precise and unhurried. <span class="said" data-who="Victor">"My fund thinks Halcyon spends too much on delivery. I'm going to propose a twenty percent cut in your office's budget. I wanted you to hear it from me first."</span>`,`Sam's office budget is mostly the four project managers and two coordinators.`],
   opts:[
    {t:`Push back immediately and explain that cuts would put the Cascade relationship at risk.`,s:1,d:{trust:0,conf:-1,health:0},after:`Victor listens and says, <span class="said" data-who="Victor">"That's a feeling. Show me the numbers."</span>`,why:`The concern may be right, but arguing before understanding the stakeholder's goal rarely moves them. Start by learning what problem they're trying to solve.`},
    {t:`Ask what result his fund is after, then offer to bring data and options to the board.`,s:3,best:true,d:{trust:1,conf:5,health:2},after:`Victor's real concern is that delivery costs grew faster than revenue. Sam comes back with cost per hospital go-live falling, and two options that save twelve percent without cutting a PM. Victor takes one of them.`,why:`Engaging a stakeholder means understanding their interests and influence, then working with data. A powerful, skeptical stakeholder becomes an ally when you treat their concern as real.`},
    {t:`Agree to the cut to build the relationship with a powerful new board member.`,s:0,d:{trust:-4,conf:0,health:-4},after:`Sam loses a coordinator. Keisha's project starts without one. Victor notes that Sam didn't push back on anything.`,why:`Agreeing without analysis doesn't build trust with someone who values evidence. It also harms projects you're accountable for.`},
    {t:`Tell Elena right away so she can stop Victor before he raises it at the board.`,s:0,d:{trust:0,conf:-3,health:0},after:`Elena calls Victor. Victor calls Sam. <span class="said" data-who="Victor">"I came to you first for a reason,"</span> he says.`,why:`Going around a stakeholder who came to you directly damages the relationship. Engage them first.`}
   ]},
  {id:`f11s9`, domain:`Process`, task:`R6`, title:`The phase two budget`,
   text:(s,all,G)=>[`Keisha brings Sam her budget for discharge instructions. It's a single number, five hundred thousand dollars, with a note: "based on phase one actuals." Sam knows phase one ran over on GPU costs and labeling.`],
   opts:[
    {t:`Approve it, since it's based on real actuals and Keisha has good judgment.`,s:0,d:{trust:1,conf:0,health:-3},after:`The number turns out to include phase one's burn-in costs, which won't repeat, and miss Spanish language labeling, which will.`,why:`An analogous estimate from actuals can be a starting point, but a budget needs to be built from the work and adjusted for what's different.`},
    {t:`Have her build it bottom up, with contingency, and Grant holding the reserves.`,s:3,best:true,d:{trust:2,conf:3,health:5},after:`The bottom-up estimate comes to $462,000, plus $38,000 contingency for identified risks. Grant holds a $25,000 management reserve. Keisha understands every line.`,why:`A cost baseline is built from the work, with contingency reserve for identified risks inside the baseline and management reserve for unknowns held outside it by the sponsor.`},
    {t:`Add twenty percent to her number to be safe, since phase one went over budget.`,s:1,d:{trust:0,conf:0,health:1},after:`Six hundred thousand dollars gets approved. Nobody can say what the extra hundred thousand is for.`,why:`Padding isn't the same as reserves. Reserves should be tied to identified risks or held as management reserve with clear rules.`},
    {t:`Cut it to four hundred thousand dollars to show Victor the delivery office is lean.`,s:0,d:{trust:-2,conf:1,health:-5},after:`The project is underfunded from day one. Keisha starts her first project already behind.`,why:`Cutting an estimate to send a message produces an unrealistic baseline. Estimates should reflect the work; savings come from scope or approach changes.`}
   ]},
  {id:`f11s10`, domain:`Business Environment`, task:`B1`, title:`Northgate wants an answer`,
   text:(s,all,G)=>[`Grant bursts into Sam's office. Northgate Health, a hospital system in Nebraska, wants Halcyon. Their CEO wants to sign this week with a go-live in ninety days. <span class="said" data-who="Grant">"I know the new rule,"</span> Grant says. <span class="said" data-who="Grant">"So sign off on the date. Ninety days. It's the same product."</span>`],
   opts:[
    {t:`Sign off on ninety days, since it's the same product and the team has done this before.`,s:0,d:{trust:-2,conf:-2,health:-5},after:`Sam signs. Three days later Priya points out that Northgate uses a different EHR with no existing integration.`,why:`Approving a date without an estimate repeats the original Cascade mistake. The rule exists so dates come from analysis.`},
    {t:`Refuse to give any date until a full plan is built, which will take a month.`,s:0,d:{trust:-2,conf:-3,health:1},after:`Northgate's CEO signs with a competitor's pilot instead. Grant is furious, and this time he has a point.`,why:`Governance should give a fast, reasoned answer, not a month of silence. A quick feasibility estimate with ranges is usually possible.`},
    {t:`Run a quick feasibility check with Priya and Keisha and give a range within two days.`,s:3,best:true,d:{trust:3,conf:4,health:4},after:`Two days later Sam gives Grant a range: 120 to 150 days because of the new EHR integration, with one way to hit 100 days using a phased start. Grant takes it to Northgate, and they accept a phased plan.`,why:`Good governance gives decisions quickly using the right input. A rough order of magnitude estimate with a range and options respects both the sales need and delivery reality.`},
    {t:`Let Grant choose the date this time, since he owns the Northgate relationship.`,s:1,d:{trust:1,conf:-1,health:-2},after:`Grant chooses ninety days. Everyone remembers the rule they just made.`,why:`The relationship owner should be involved, but delivery dates need delivery's analysis. Otherwise the governance rule means nothing the first time it's tested.`}
   ]},
  {id:`f11s11`, domain:`People`, task:`P1`, title:`Standards Rob will use`,
   text:(s,all,G)=>[`Sam needs minimum standards for every project: a charter, a risk register, a status format. Rob Delgado says his projects already work fine without them, and he's mostly right. Keisha says she'd love templates, since her old hospital had none.`],
   opts:[
    {t:`Write the standards himself over a weekend and require them on every project from Monday.`,s:0,d:{trust:-3,conf:0,health:-1},after:`The templates are good. Rob fills them in after the fact, and they stop being useful within a month.`,why:`Mandated standards built without the people using them become paperwork. Involving practitioners makes them useful and owned.`},
    {t:`Have Rob and Keisha co-design a minimum set, kept to what every project truly needs.`,s:3,best:true,d:{trust:5,conf:1,health:3},after:`Rob cuts Keisha's draft from twelve templates to four. Keisha adds a one page status that Rob ends up using himself. The standards fit on a single page.`,why:`Engaging experienced and new practitioners together creates a shared vision of what good looks like. Minimum viable process gets adopted; maximum process gets worked around.`},
    {t:`Exempt Rob from the standards, since his projects already deliver well without them.`,s:1,d:{trust:1,conf:0,health:-1},after:`Rob is happy. The other PMs ask why the rules don't apply to everyone.`,why:`Exemptions undermine shared standards. Better to make the standards light enough that good PMs don't mind them.`},
    {t:`Buy a commercial PMO template library so the standards come from industry practice.`,s:0,d:{trust:0,conf:0,health:-1},after:`The library has two hundred templates. Nobody opens it after the first week.`,why:`Industry templates can help, but they need tailoring to the organization. Without the team's involvement, they won't be used.`}
   ]},
  {id:`f11s12`, domain:`Process`, task:`R4`, title:`Two customers, one platform team`,
   text:(s,all,G)=>[`Northgate signs with a phased plan. Now Priya's platform team supports Cascade's phase two and Northgate's integration at the same time. Elena sends a one line email: <span class="said" data-who="Elena">"Great news! Same team can handle both, right?"</span>`],
   opts:[
    {t:`Reply yes, since the team proved itself on Cascade and morale is high right now.`,s:0,d:{trust:-3,conf:-1,health:-5},after:`By week three Priya is working Theo's old hours. Sam notices and feels sick about it.`,why:`Committing capacity without analysis overloads the team and repeats the bottleneck problem.`},
    {t:`Analyze the capacity impact on both projects and bring options to the steering group.`,s:3,best:true,d:{trust:3,conf:3,health:5},after:`The analysis shows Priya's team can carry both only if two contractors are added or Cascade phase two slips four weeks. The steering group funds two contractors, and Sam knows exactly who to call.`,why:`When a new commitment affects existing projects, assess the impact and give decision makers options with tradeoffs. That's how portfolio decisions should be made.`},
    {t:`Pause Cascade phase two until Northgate is live, to protect the new customer.`,s:1,d:{trust:0,conf:-2,health:1},after:`Northgate is protected. Ochoa hears about the pause from Grant and asks why nobody asked him.`,why:`Prioritizing may be the right answer, but it's a decision for the steering group with affected stakeholders informed, not a unilateral call.`},
    {t:`Ask Priya to decide how to split her team, since she knows the work best of anyone.`,s:0,d:{trust:1,conf:0,health:-2},after:`Priya splits it evenly. Both projects slow down, and she feels responsible for both.`,why:`Priya should inform the analysis, but tradeoffs between two customers are a portfolio decision above the team level.`}
   ]}
 ],
 drills:[
  {after:`f11s4`, title:`The discharge instructions business case`,
   setup:[`Keisha's numbers for the business case. The project costs $500,000, paid up front in year 0. Cascade's contract brings Halcyon net cash inflows of $200,000 in year 1, $250,000 in year 2, and $250,000 in year 3. Halcyon uses a 10 percent discount rate.`,`Present value factors at 10 percent: year 1 is 1 ÷ 1.10, year 2 is 1 ÷ 1.21, year 3 is 1 ÷ 1.331. Round your answers to the nearest dollar, and to two decimal places for the ratio and payback.`],
   table:[[`Year`,`Cash flow`],[`0`,`−$500,000`],[`1`,`$200,000`],[`2`,`$250,000`],[`3`,`$250,000`]],
   fields:[{label:`Net present value ($)`,answer:76258,tol:3},{label:`Benefit cost ratio (PV of inflows ÷ cost)`,answer:1.15,tol:0.01},{label:`Simple payback period (years)`,answer:2.2,tol:0.01}],
   solution:[`PV of inflows: $200,000 ÷ 1.10 = $181,818. $250,000 ÷ 1.21 = $206,612. $250,000 ÷ 1.331 = $187,829. Total = $576,258.`,`NPV = $576,258 − $500,000 = $76,258. Positive, so the project earns more than the 10 percent rate.`,`Benefit cost ratio = $576,258 ÷ $500,000 = 1.15. Above 1 is good.`,`Payback: after year 1, $200,000 recovered; after year 2, $450,000. The remaining $50,000 comes from year 3's $250,000, which is 0.2 of a year. Payback = 2.2 years.`,`On the exam, prefer the higher NPV when comparing projects, and don't adjust NPV for project length again.`]}
 ],
 exercise:{after:`f11s2`, title:`What kind of PMO is this?`, intro:`Read each description and pick the PMO type.`,
  items:[
   {prompt:`The PMO publishes templates and runs a monthly community of practice. Using them is optional.`,choices:[`Supportive`,`Controlling`,`Directive`],answer:0,why:`Optional guidance and resources with little control is a supportive PMO.`},
   {prompt:`The PMO audits every project quarterly and requires its status format and gate reviews.`,choices:[`Supportive`,`Controlling`,`Directive`],answer:1,why:`Requiring compliance with methods and reviews is a controlling PMO.`},
   {prompt:`All project managers report to the PMO, which assigns them and manages the projects.`,choices:[`Supportive`,`Controlling`,`Directive`],answer:2,why:`Directly managing projects and the PMs is a directive PMO.`},
   {prompt:`The PMO requires delivery sign-off on any customer date, and otherwise offers coaching.`,choices:[`Supportive`,`Controlling`,`Directive`],answer:1,why:`A mandatory control point makes it controlling, even if most of what it does is supportive.`},
   {prompt:`The PMO maintains the lessons learned repository and trains new PMs when asked.`,choices:[`Supportive`,`Controlling`,`Directive`],answer:0,why:`Repositories and on-request training without required compliance are supportive functions.`}
  ]},
 quiz:[
  {q:`An organization wants its PMO to provide templates and training without requiring their use. What type of PMO is this?`,opts:[`Directive`,`Supportive`,`Controlling`,`Strategic`],a:1,why:`A supportive PMO provides resources and guidance with low control.`,task:`B1`,domain:`Business Environment`},
  {q:`A project manager needs a decision that exceeds their approval authority. What should they do?`,opts:[`Make the decision and inform the sponsor`,`Wait until the next steering committee meeting`,`Use the escalation path in the governance plan`,`Ask the team to vote on the decision`],a:2,why:`Governance defines escalation paths for decisions beyond a person's authority. Use them.`,task:`B1`,domain:`Business Environment`},
  {q:`Project A has an NPV of $120,000 over 5 years. Project B has an NPV of $95,000 over 2 years. Which should be selected on financial grounds?`,opts:[`Project B, because it finishes sooner`,`Project A, because its NPV is higher`,`Project B, because its yearly NPV is higher`,`Either, because they are roughly equal`],a:1,why:`NPV already accounts for the time value of money. Choose the higher NPV and don't adjust for project length.`,task:`R6`,domain:`Process`},
  {q:`What does a positive net present value indicate?`,opts:[`The project earns more than the discount rate`,`The project will pay back within one year`,`The project's costs exceed its benefits`,`The project's internal rate of return is zero`],a:0,why:`Positive NPV means the discounted benefits exceed the discounted costs at the chosen rate.`,task:`R6`,domain:`Process`},
  {q:`A project costs $300,000 and returns $100,000 per year. What is the payback period?`,opts:[`1 year`,`2 years`,`4 years`,`3 years`],a:3,why:`$300,000 ÷ $100,000 per year = 3 years.`,task:`R6`,domain:`Process`},
  {q:`Who is responsible for issuing the project charter?`,opts:[`The project manager`,`The PMO director`,`The project sponsor`,`The customer`],a:2,why:`The sponsor issues the charter and authorizes the project manager to use resources.`,task:`B1`,domain:`Business Environment`},
  {q:`Which reserve is held outside the cost baseline for unknown risks?`,opts:[`Contingency reserve`,`Schedule reserve`,`Management reserve`,`Cost of quality`],a:2,why:`Management reserve covers unknown unknowns and sits outside the cost baseline, controlled by management or the sponsor.`,task:`R6`,domain:`Process`},
  {q:`A team resists a new delivery framework. What is the best way to build a common vision?`,opts:[`Have the sponsor explain the benefits in a meeting`,`Involve the team in shaping how it will work`,`Require the framework and review compliance`,`Pilot it on one project without telling others`],a:1,why:`A common vision is developed with the team so they own it. Involvement turns resistance into ownership.`,task:`P1`,domain:`People`},
  {q:`A board member asks how external changes could affect the portfolio. What tool helps structure the answer?`,opts:[`PESTLE analysis`,`Earned value analysis`,`A RACI chart`,`A burndown chart`],a:0,why:`PESTLE scans political, economic, social, technological, legal, and environmental factors outside the organization.`,task:`B8`,domain:`Business Environment`},
  {q:`An organization must choose between three projects with limited capacity. What is the best approach?`,opts:[`Start all three with smaller teams`,`Let the CEO choose based on experience`,`Pick the one with the shortest duration`,`Score them against agreed criteria`],a:3,why:`Selection uses agreed criteria, financial and strategic, so the decision is defensible and repeatable.`,task:`R6`,domain:`Process`},
  {q:`A powerful stakeholder proposes a budget cut you believe will harm projects. What should you do first?`,opts:[`Understand their objective and bring data`,`Accept the cut to maintain the relationship`,`Ask the CEO to overrule the stakeholder`,`Refuse the cut and explain the risks`],a:0,why:`Engage the stakeholder by understanding their interests first, then work with evidence and options.`,task:`P4`,domain:`People`},
  {q:`What is the benefit cost ratio of a project with $450,000 in present value benefits and $300,000 in present value costs?`,opts:[`0.67`,`1.50`,`1.33`,`2.00`],a:1,why:`$450,000 ÷ $300,000 = 1.50. Above 1 means benefits exceed costs.`,task:`R6`,domain:`Process`},
  {q:`A business case was approved last year, but a key assumption has changed. What should happen?`,opts:[`Continue, since the case was already approved`,`Revisit the business case with the sponsor`,`Cancel the project to avoid more spending`,`Update the schedule to absorb the change`],a:1,why:`The business case is a living document. When assumptions change, revisit it with the sponsor to decide whether to continue.`,task:`R6`,domain:`Process`},
  {q:`A sales executive wants a firm delivery date the same day for a new customer. What should the delivery lead do?`,opts:[`Approve the date to win the customer`,`Give a quick estimate range with options`,`Refuse until a full plan is complete`,`Let the sales executive pick the date`],a:1,why:`Good governance gives timely, reasoned answers. A quick range with options serves both sales and delivery.`,task:`B1`,domain:`Business Environment`},
  {q:`Which statement about the payback period is true?`,opts:[`It ignores cash flows after payback`,`It accounts for the time value of money`,`Longer payback periods are preferred`,`It is always the best selection measure`],a:0,why:`Simple payback ignores what happens after the investment is recovered, which is why NPV is usually preferred.`,task:`R6`,domain:`Process`}
 ],
 closing:(s,all,G)=>[
  `Friday night Sam took the index card down from above his monitor to read it again. <span class="said" data-who="Sam">"The job is making other people able to run them."</span> Keisha had a charter. Rob had a one page standard he'd written half of. Priya had two contractors coming. Sam had touched none of the actual projects all week, and for the first time that felt like the point instead of a failure.`,
  `Victor sent a two line email at 9 PM. <span class="said" data-who="Victor">"Your external scan mentioned a draft state guidance on clinical AI disclosure. My fund's lawyers think it will be final within sixty days. Are your projects ready for that?"</span>`,
  `Sam read it twice. Then he read the draft guidance, all forty pages of it, at the kitchen table while Dana graded quizzes across from him.`,
  `<span class="said" data-who="Dana">"Bad?"</span> she asked, without looking up.`,
  (s.score>=26?`<span class="said" data-who="Sam">"Not bad yet,"</span> he said. <span class="said" data-who="Sam">"Early. Early is the good kind of bad."</span> Dana wrote a red check mark on someone's quiz and said, <span class="said" data-who="Dana">"You sound like Ruth."</span>`:`<span class="said" data-who="Sam">"I don't know yet,"</span> he said. <span class="said" data-who="Sam">"That's the part I don't like."</span> Dana wrote a red check mark on someone's quiz and said, <span class="said" data-who="Dana">"So find out. You're good at that."</span>`),
  `On Monday a competitor called Meridian Scribe announced a clinical documentation product at forty percent of Halcyon's price. Grant forwarded the press release to Sam with no message at all.`
 ],
 episode:{src:`audio/full-ch11.mp3`, len:`about 35 minutes`},
 next:`The Shock`
});
