// Full Course, chapter 12. Format: see full/BIBLE.md.
(window.HALCYON_FULL=window.HALCYON_FULL||[]).push({
 num:12, part:`Part Two: The PMO`, title:`The Shock`, weeks:`Month 7`,
 tasks:[`B8`,`B5`,`B2`,`P2`,`B3`,`B7`,`R8`],
 cast:[
  [`Nora Kim`,`Halcyon's head of security and compliance. Calm, thorough, hates surprises.`]
 ],
 opening:[
  `Meridian Scribe's press release was four paragraphs and a price. Forty percent of Halcyon's. By Tuesday morning two prospective customers had asked Grant for a discount, and one of them used the word "commodity," which Grant repeated in the executive meeting like it was a diagnosis.`,
  `By Tuesday afternoon the state health department published its final guidance on clinical AI. It was close to the draft Sam had read at the kitchen table, with one change that mattered: any AI-drafted clinical note now had to carry a visible disclosure to the patient record, and hospitals had to keep an audit trail of which clinician reviewed it. Cascade's agents did the second. They didn't do the first.`,
  `By Wednesday Victor had sent a memo to the board proposing that Halcyon cut operating costs twenty five percent across the board, starting with delivery and engineering. The memo was clear, well reasoned, and treated people like line items, which Victor would have said was the point of a memo.`,
  `Sam found Lena in the stairwell between floors three and four, which was where Lena went when she didn't want to be found. She was holding Victor's memo and not reading it.`,
  `<span class="said" data-who="Lena">"Elena's going to say yes to this,"</span> Lena said. <span class="said" data-who="Lena">"She's going to say yes because she's scared of Meridian, and then she's going to ask me to cut the team that would actually beat Meridian. And I'm going to nod. I always nod."</span>`,
  `Sam sat down two steps below her. He thought of Ray Mendez, who used to say a crew chief's most important tool was the word "stop," and that most people never learned to use it on anyone above them.`,
  `<span class="said" data-who="Sam">"What would you say,"</span> Sam asked, <span class="said" data-who="Sam">"if you weren't going to nod?"</span>`,
  `Lena was quiet for a long time. Then she told him. It took twenty minutes, and it was the best analysis of Halcyon's market he'd heard from anyone.`
 ],
 lesson:{
  title:`When the world changes under your project`,
  sections:[
   {h:`Scanning the external environment`,
    body:[`Projects live inside a business, and the business lives inside a market, a legal system, an economy, and a technology landscape that don't care about your baseline. The 2026 exam outline includes evaluating external business environment changes as its own task. The project manager is expected to notice changes, assess their impact on the project's objectives and business case, and bring the right people into the response.`,
          `A common structure is PESTLE: political, economic, social, technological, legal, and environmental factors. You don't need a consultant to use it. A quarterly one page scan with owners for each category is enough for most organizations. The scan feeds the risk register, triggers business case reviews, and sometimes leads to a change request.`,
          `The key exam idea: when an external change happens, first assess its impact on the project, then update the relevant documents and engage the sponsor or governance body. Don't ignore it, and don't overreact by changing scope before you've analyzed what the change actually means.`,`External changes aren't only threats. A new regulation can become a selling point if you meet it first, and a competitor's launch can show you which features customers actually value. Separate the change itself from its effect on your project: Meridian's lower price changed Halcyon's market, but it didn't change Cascade's signed contract. That distinction tells you whether you need a project change, a business case review, or just a note for the product roadmap.`],
    terms:[[`PESTLE`,`Political, economic, social, technological, legal, and environmental factors used to scan the external environment.`],[`Business case review`,`Revisiting a project's justification when assumptions or conditions change.`]],
    exam:`A stem that starts "a new regulation was announced" or "a competitor released" usually wants you to assess the impact first, then update plans and risks through the proper process.`},
   {h:`Compliance as a requirement`,
    body:[`Compliance requirements come from laws, regulations, standards, contracts, and internal policies. On the 2026 outline, planning and managing project compliance is a Business Environment task. The project manager's job is to identify compliance requirements, make sure each one has an owner and a plan, build them into scope and testing, and track them to completion.`,
          `When a new regulation arrives mid-project, it isn't optional and it isn't a nice-to-have. It's a requirement that goes through change control so its cost and schedule impact are visible and approved. Bring in the compliance or legal experts; don't interpret regulations alone. And never cut a compliance requirement to save time or money.`,`Compliance work has its own deliverables: a register of requirements and their sources, evidence that each one is met, and someone who signs off. Build tests for compliance requirements just as you would for features, and keep the evidence where an auditor or the customer's security team can find it. When a customer asks whether you comply, the answer should come from that evidence and the compliance owner, not from memory or a sales promise. A wrong yes on compliance costs more trust than an honest, dated plan.`],
    terms:[[`Compliance requirement`,`An obligation from a law, regulation, standard, contract, or policy that the project must meet.`],[`Requirements traceability matrix`,`A table linking each requirement, including compliance requirements, to its source, design, and test.`]],
    exam:`If the choice is between meeting a regulation late and skipping it to stay on schedule, compliance wins. The project manager adjusts the plan through change control.`},
   {h:`Risk when the stakes rise`,
    body:[`Risk management is a Business Environment task on the 2026 outline. Risks are uncertain events that could affect objectives, positively or negatively. When the environment shifts, the risk register needs a fresh look: new risks, changed probabilities and impacts, and responses that may no longer fit. Threat responses are avoid, transfer, mitigate, accept, and escalate. Opportunity responses are exploit, share, enhance, accept, and escalate.`,
          `Escalation deserves special attention. Escalate a risk when it's outside the project's scope or beyond the project manager's authority, such as a funding risk that only the board can address. Escalating isn't passing the buck. Once a risk is escalated, the project records it and the people at the higher level own the response.`,
          `Risk thresholds and appetite also matter. An organization under financial pressure may lower its tolerance for cost risk and raise its tolerance for schedule risk. The project manager should understand the current appetite before choosing responses.`],
    terms:[[`Risk appetite`,`How much uncertainty an organization is willing to take on in pursuit of its goals.`],[`Escalate`,`A response for threats or opportunities outside the project's scope or the PM's authority, handed to the right level of the organization.`],[`Trigger`,`An early warning sign that a risk is about to happen.`]],
    exam:`Escalate is the right response only when the risk is outside the project manager's authority or scope. If you can address it within the project, choose a response you own.`},
   {h:`Conflict at the top, and compressing the schedule`,
    body:[`Conflict among senior leaders is still conflict, and the same modes apply: collaborate or problem solve (usually best when time allows), compromise or reconcile, smooth or accommodate, force or direct, and withdraw or avoid. A project manager can't order executives to collaborate, but can make collaboration easier: bring data, frame the shared interest, and suggest a private conversation rather than a public fight.`,
          `When cuts arrive and a date still matters, schedule compression comes up. Crashing adds resources to critical path activities to shorten them, and it costs money; you crash the activities with the lowest cost per unit of time saved first. Fast tracking runs activities in parallel that were planned in sequence, and it adds risk and rework rather than direct cost. Both only help on the critical path.`],
    terms:[[`Crashing`,`Shortening critical path activities by adding resources, usually at added cost.`],[`Fast tracking`,`Overlapping activities that were planned in sequence, adding risk.`],[`Cost slope`,`(Crash cost − normal cost) ÷ (normal duration − crash duration), the cost per unit of time saved.`]],
    exam:`When asked which activity to crash first, choose the critical path activity with the lowest cost slope. Crashing a non-critical activity saves nothing.`}
  ],
  video:[`bYn4CyL3r5w`,`PESTEL Analysis Explained`,`Business To You`,`9:49`]
 },
 scenes:[
  {id:`f12s1`, domain:`Business Environment`, task:`B8`, title:`Meridian Scribe`,
   text:(s,all,G)=>[`<prop type="doc" title="Health IT Weekly">Meridian launches Scribe at half the price of incumbents. Ambient documentation, discharge summaries, and coding suggestions included. Three health systems signed in beta.</prop>`,`In the executive meeting Grant wants to respond to Meridian by adding three new features to Cascade phase two and Northgate, <span class="said" data-who="Grant">"so we're clearly better and worth the price."</span> Elena seems to like it. Keisha and Priya aren't in the room.`],
   opts:[
    {t:`Assess what Meridian really changes for each project and for its business case.`,s:3,best:true,d:{trust:2,conf:4,health:4},after:`Sam's one page analysis shows Meridian's product doesn't integrate with Cascade's EHR at all, and Northgate's contract is signed. The real threat is to new deals, not current projects. The three features go to the product roadmap, not into live projects.`,why:`When the external environment changes, assess the impact on objectives and the business case before changing scope. Then update risks and engage governance with what you found.`},
    {t:`Add the three features to both projects now so customers see value right away.`,s:0,d:{trust:-3,conf:-1,health:-6},after:`Both projects slip. Neither customer asked for the features.`,why:`Changing project scope as a reaction, without analysis or change control, puts current commitments at risk for an unproven benefit.`},
    {t:`Ignore Meridian, since current contracts are signed and the projects are safe.`,s:0,d:{trust:0,conf:-3,health:0},after:`Two months later Cascade's renewal conversation starts with Meridian's price list.`,why:`Ignoring an external change is as risky as overreacting. Evaluate it, record what it means, and watch the triggers.`},
    {t:`Ask Keisha and Priya to estimate the three features before anyone decides.`,s:1,d:{trust:1,conf:1,health:1},after:`They estimate them carefully. It's useful, but it answers how much the features cost, not whether they're needed.`,why:`Estimating is part of analysis, but the first question is how the change affects objectives. Otherwise you're estimating a solution to an undefined problem.`}
   ]},
  {id:`f12s2`, domain:`Business Environment`, task:`B2`, title:`The disclosure rule`,
   text:(s,all,G)=>[`The new guidance requires a visible AI disclosure on every AI-drafted note. Cascade's agents don't have one. Northgate's integration hasn't started. Grant suggests waiting: <span class="said" data-who="Grant">"Enforcement won't start for months. Let's not slow anything down."</span>`],
   opts:[
    {t:`Wait for enforcement guidance, as Grant suggests, so current delivery isn't slowed.`,s:0,d:{trust:0,conf:-4,health:-2},after:`Ochoa's compliance officer asks Halcyon about the disclosure the following week. Halcyon has no answer.`,why:`A compliance requirement isn't optional because enforcement is later. Plan for it now, through the proper process.`},
    {t:`Have Nora Kim define the requirement, then route it through change control.`,s:3,best:true,d:{trust:2,conf:5,health:4},after:`Nora maps the guidance to three specific requirements. Keisha raises a change request for Cascade phase two and builds the requirement into Northgate's design from day one. Both customers get a plan before they ask.`,why:`Identify compliance requirements with the right experts, then build them into scope through change control so impact is visible and approved. That's planning and managing compliance.`},
    {t:`Have Priya's team add a disclosure banner this sprint and tell the customers after.`,s:1,d:{trust:0,conf:0,health:1},after:`The banner ships fast, but it doesn't match what the guidance actually requires. Nora has to redo it.`,why:`Acting quickly is good, but interpreting a regulation without compliance experts and bypassing change control often produces the wrong fix.`},
    {t:`Ask both customers how they want to handle the guidance before doing anything.`,s:1,d:{trust:0,conf:1,health:0},after:`Both customers say they assumed Halcyon would handle it.`,why:`Customers should be engaged, but the product's compliance with regulation is the vendor's requirement to plan for.`}
   ]},
  {id:`f12s3`, domain:`Business Environment`, task:`B5`, title:`The register is out of date`,
   text:(s,all,G)=>[`Sam opens the delivery office risk register. It was last updated three weeks ago. It doesn't mention Meridian, the guidance, or Victor's proposed cuts. The top risk is still IronPeak hardware.`],
   opts:[
    {t:`Reassess the register with each project: new risks, new scores, owners, responses.`,s:3,best:true,d:{trust:2,conf:2,health:5},after:`The review adds six risks and changes the ranking. A funding cut becomes the top threat. A new opportunity appears too: Northgate wants the disclosure feature first, which could become a selling point.`,why:`Risk management is ongoing. When the environment changes, reassess probabilities and impacts, add new risks, assign owners, and update responses. Look for opportunities too.`},
    {t:`Add the three new risks at the top and leave the rest of the register as it is.`,s:1,d:{trust:0,conf:0,health:1},after:`The new risks are listed. The old IronPeak risk, now irrelevant, still eats attention in every review.`,why:`Adding risks helps, but a real reassessment also rescores existing ones, retires the ones that no longer apply, and revisits responses.`},
    {t:`Ask each project manager to update their own register by the end of the month.`,s:1,d:{trust:1,conf:0,health:0},after:`The registers get updated slowly and differently, and nobody sees the portfolio picture.`,why:`Project level registers matter, but a shift that hits every project at once needs a coordinated review with portfolio level risks and owners.`},
    {t:`Hold off on updates until Victor's cut decision, since everything depends on it.`,s:0,d:{trust:0,conf:-1,health:-3},after:`The decision takes three weeks. The register stays wrong the whole time.`,why:`Uncertainty is exactly when the register is most useful. Record the decision as a risk with triggers rather than waiting for it to resolve.`}
   ]},
  {id:`f12s4`, domain:`Business Environment`, task:`B3`, title:`Ochoa's change request`,
   text:(s,all,G)=>[`Keisha sends the disclosure change request to Cascade. It adds three weeks and forty thousand dollars to phase two. Ochoa calls Sam directly. <span class="said" data-who="Ochoa">"This is your product's compliance problem. Why is Cascade paying for it?"</span>`,(G.overrodepo?`Maria Santos is on the call too. She hasn't forgotten week nine, when Sam overrode her on the backlog, and she lets Ochoa's question hang without helping.`:`Maria Santos is on the call too. <span class="said" data-who="Maria">"Raymond, the disclosure protects our nurses as much as it protects them,"</span> she says. It doesn't settle anything, but it lowers the temperature.`)],
   opts:[
    {t:`Agree that Halcyon absorbs it to keep Ochoa happy during a competitive period.`,s:1,d:{trust:0,conf:3,health:-2},after:`Ochoa is pleased. Victor asks why a forty thousand dollar decision didn't go through governance.`,why:`Absorbing the cost might be right, but it's a decision above the PM that should go through the change control process with the sponsor.`},
    {t:`Hold firm that the contract puts regulatory changes on the customer's side.`,s:0,d:{trust:0,conf:-4,health:0},after:`The contract does say that. Ochoa reads it, says <span class="said" data-who="Ochoa">"fine,"</span> and asks his team to check Meridian's pricing again.`,why:`Being contractually right isn't the same as managing the stakeholder well. Use the change process to find a fair answer, not to win.`},
    {t:`Check the contract with Joan and take cost-share options to the change board.`,s:3,best:true,d:{trust:1,conf:4,health:3},after:`The contract splits regulatory changes. The change board approves a split: Halcyon covers the product work, Cascade covers its own testing. Ochoa accepts and says it's the first vendor change request he's read that made sense.`,why:`Changes go through change control with impact analysis and the right decision makers. Bringing options grounded in the contract keeps the relationship and the governance intact.`},
    {t:`Pause the change request until Ochoa calms down and the market settles.`,s:0,d:{trust:0,conf:-2,health:-3},after:`The disclosure work waits. The compliance deadline doesn't.`,why:`Delaying a required change creates compliance risk. Work the change through the process promptly.`}
   ]},
  {id:`f12s5`, domain:`Business Environment`, task:`B5`, title:`Victor's twenty five percent`,
   text:(s,all,G)=>[`The board meets Thursday. Elena asks Sam for his position on Victor's proposal to cut delivery and engineering by twenty five percent. She makes it clear she's leaning yes. Victor's memo is already in the board packet.`,`<prop type="doc" title="Board memo: operating efficiency">Proposal: reduce delivery and engineering spend 25 percent this half.<br>${(s.flags.nobusinesscase||G.nobusinesscase)?`First cut: discharge instructions phase two. No documented business case or return.`:`Candidates: duplicate tooling, unfilled roles, lowest NPV initiatives.`}<br>Outcome sought: 18 months of runway without new financing.</prop>`],
   opts:[
    {t:`Support the cuts across the board, since the CEO and the board are leaning that way.`,s:0,flag:`cutcorners`,d:{trust:-5,conf:1,health:-6},after:`The cut goes through without analysis. Northgate loses its contractors and the disclosure work slips past the compliance date.`,why:`Agreeing to major cuts without analyzing their effect on objectives, compliance, and risk is the opposite of risk management. Decision makers need impact analysis.`},
    {t:`Model what each cut level does to both projects and compliance, then recommend.`,s:3,best:true,d:{trust:3,conf:5,health:4},after:`Sam's model shows a fifteen percent cut is survivable if it comes from the cancelled billing project and slower hiring. Twenty five percent breaks the compliance date. The board approves fifteen. Victor says the model is the most useful thing he's seen from management.`,why:`A funding risk at this level is escalated to the board, and the PM's job is to give them impact analysis and options. Decision makers can then choose with eyes open.`},
    {t:`Refuse to take any position, since budget decisions belong to the board alone.`,s:1,d:{trust:0,conf:-2,health:0},after:`The board decides without delivery's view. It decides twenty five percent.`,why:`The decision is the board's, but the delivery office owes them analysis of the impact. Silence isn't neutrality, it's missing information.`},
    {t:`Oppose any cut and warn the board that projects will fail if they make it.`,s:0,d:{trust:1,conf:-3,health:0},after:`Victor asks for the analysis behind the warning. There isn't any yet.`,why:`Opposition without data is easy to dismiss. Give decision makers modeled options, not predictions.`}
   ]},
  {id:`f12s6`, domain:`People`, task:`P2`, title:`Lena says it out loud`,
   text:(s,all,G)=>[(G.publicfight?`Lena catches Sam before the meeting. <span class="said" data-who="Lena">"Last time Grant and I fought, you let it play out in front of the whole team. Please don't do that today."</span> `:``)+`In Thursday's pre-board session, Lena finally does it. She tells Elena, in front of Grant and Victor, that cutting engineering to chase Meridian's price would kill the one advantage Halcyon has. Elena's face goes still. Grant starts to defend Elena. Victor watches everyone.`,`Lena looks at Sam. She's asking for backup.`],
   opts:[
    {t:`Back Lena firmly right there, since she's right and someone needs to say so.`,s:1,d:{trust:2,conf:-1,health:0},after:`Elena feels ambushed by two people now. The meeting turns into sides.`,why:`Support matters, but turning a disagreement into a public two-against-one pushes people toward forcing and withdrawing. The goal is to move the conversation to shared interests.`},
    {t:`Stay quiet, since a fight between executives isn't the delivery office's business.`,s:0,d:{trust:-4,conf:0,health:0},after:`Lena loses the argument and stops speaking for the rest of the meeting.`,why:`Withdrawing leaves the conflict unresolved and abandons a colleague who brought real data. Avoiding isn't neutral.`},
    {t:`Name the shared goal of beating Meridian and offer data on both views in private.`,s:3,best:true,d:{trust:5,conf:3,health:2},after:`The room exhales. Elena agrees to a working session with Lena and Sam that afternoon. In private, with Sam's model on the table, Elena and Lena reach a plan neither would have reached in the meeting.`,why:`In a conflict, focus people on the shared interest, bring facts, and move the hard part to a setting where collaboration can happen. Collaborate and problem solve is usually the best mode when time allows.`},
    {t:`Suggest a compromise on the spot, cutting half of what Victor proposed.`,s:1,d:{trust:0,conf:1,health:0},after:`Everyone agrees to twelve and a half percent. Nobody believes in it.`,why:`Compromise can end a conflict quickly, but here it skips the analysis that could find a better answer. Collaboration first, compromise if that fails.`}
   ]},
  {id:`f12s7`, domain:`People`, task:`P2`, title:`Two teams, two tools`,
   text:(s,all,G)=>[`The fifteen percent cut merges two engineering teams. One team uses Jira. The other uses Azure Boards. The merged team's first standup is a twenty minute argument about tools, and the two leads have stopped speaking to each other.`],
   opts:[
    {t:`Pick Jira for them, since more of Halcyon already uses it and the argument wastes time.`,s:1,d:{trust:-1,conf:0,health:2},after:`The argument stops. The Azure Boards team stops volunteering ideas.`,why:`Forcing ends a conflict fast and sometimes it's necessary, but it costs commitment. When there's time, collaborating on criteria gets a better result.`},
    {t:`Have the two leads agree what the tool must do, then decide together.`,s:3,best:true,d:{trust:5,conf:1,health:3},after:`They agree on four criteria in an hour. Jira wins on three of them. The Azure Boards lead suggests the migration plan herself.`,why:`Collaboration works by separating the people from the problem and agreeing on objective criteria first. The decision becomes theirs, so they commit to it.`},
    {t:`Let each half keep its own tool until the merger settles down a little.`,s:0,d:{trust:1,conf:0,health:-3},after:`Status takes twice as long. Dependencies fall between the two boards.`,why:`Avoiding the decision keeps the peace for a week and costs the team a single view of its work.`},
    {t:`Escalate the tool decision to Lena as CTO so it's settled from the top.`,s:0,d:{trust:-1,conf:0,health:0},after:`Lena, mid crisis, picks one in an email. Both leads feel overruled.`,why:`This conflict is within the team's ability to solve. Escalating it removes ownership from the people who'll live with the result.`}
   ]},
  {id:`f12s8`, domain:`Business Environment`, task:`B5`, title:`The bank's covenant`,
   text:(s,all,G)=>[`Halcyon's CFO mentions, almost in passing, that a bank loan has a covenant: if revenue drops below a certain level for two quarters, the bank can call part of the loan. Two lost renewals would trigger it. Cascade's renewal is in five months.`,`It isn't in any risk register.`],
   opts:[
    {t:`Add it to the delivery office register and plan a mitigation for it himself.`,s:1,d:{trust:0,conf:0,health:1},after:`Sam writes a mitigation. It's mostly about delivering well, which he was already doing.`,why:`Recording it is good, but a financing risk is outside the delivery office's authority. Escalate it to the level that can actually respond.`},
    {t:`Escalate it to the CFO and Elena as an enterprise risk and log it as escalated.`,s:3,best:true,d:{trust:1,conf:4,health:3},after:`The CFO takes ownership and opens a conversation with the bank. Sam records the risk as escalated, with the CFO as owner, and links Cascade's renewal as a trigger.`,why:`Escalate risks that are outside the project's scope or the project manager's authority. Record that it was escalated and who owns it now.`},
    {t:`Ignore it, since banking covenants have nothing to do with project delivery.`,s:0,d:{trust:0,conf:-2,health:-1},after:`Five months later, the covenant is the only thing anyone wants to talk about.`,why:`Risks outside the project can still affect it. If you can't own the response, escalate it.`},
    {t:`Tell the project teams so they understand why the Cascade renewal matters so much.`,s:0,d:{trust:-1,conf:0,health:-2},after:`Rumors start that Halcyon is about to lose its funding.`,why:`Sharing sensitive financial risk broadly without context creates alarm. Escalate to the owners first.`}
   ]},
  {id:`f12s9`, domain:`Business Environment`, task:`B8`, title:`Making the scan a habit`,
   text:(s,all,G)=>[`Victor asks Sam how Halcyon will avoid being surprised next time. <span class="said" data-who="Victor">"You saw the guidance coming. Nobody acted until it was final."</span>`],
   opts:[
    {t:`Hire an analyst whose full time job is watching the market and regulation.`,s:1,d:{trust:0,conf:1,health:0},after:`The analyst is good. Nobody reads the reports, because nobody owns acting on them.`,why:`Capacity helps, but scanning only matters if findings flow into risks and decisions with owners.`},
    {t:`Set a quarterly PESTLE scan with owners that feeds the risk register and reviews.`,s:3,best:true,d:{trust:2,conf:4,health:3},after:`Six owners, one page each quarter. Every finding either becomes a risk with a trigger or gets dropped on purpose. Victor asks to sit in on the first one.`,why:`Evaluating the external environment works best as a regular, owned practice that feeds risk management and business case reviews.`},
    {t:`Ask each project manager to watch for external changes affecting their own project.`,s:1,d:{trust:1,conf:0,health:0},after:`Each PM watches their own corner. Nobody sees the competitor until it's a press release.`,why:`Project managers should stay alert, but organization wide changes need a coordinated scan with clear owners.`},
    {t:`Subscribe to an industry newsletter and forward relevant articles to the team.`,s:0,d:{trust:0,conf:0,health:0},after:`The articles pile up unread.`,why:`Information alone doesn't change anything. Scanning needs owners, a cadence, and a path into decisions.`}
   ]},
  {id:`f12s10`, domain:`Process`, task:`R8`, title:`Northgate's date after the cut`,
   text:(s,all,G)=>[`The cut costs Northgate two weeks. Northgate's go-live is tied to their fiscal year and can't move. Keisha shows Sam the critical path. Two remaining critical activities can be shortened by adding people: the EHR interface build and the clinical validation.`],
   opts:[
    {t:`Shorten whichever activity Keisha's team feels most confident about.`,s:1,d:{trust:1,conf:0,health:1},after:`They crash clinical validation, which turns out to be the more expensive option by a third.`,why:`Team confidence matters for feasibility, but the first filter is cost per week saved on critical path activities.`},
    {t:`Fast track by starting validation before the interface build is finished.`,s:1,d:{trust:0,conf:0,health:1},after:`Validation starts on half-built interfaces. Rework eats a week of the savings.`,why:`Fast tracking costs no money directly but adds rework risk. It can be right, but compare it with crashing on cost and risk.`},
    {t:`Crash the critical activity with the lowest cost per week, then recheck the path.`,s:3,best:true,d:{trust:1,conf:3,health:5},after:`The interface build is cheaper per week. Crashing it two weeks costs twelve thousand dollars, which fits the remaining contingency. The critical path doesn't shift.`,why:`When crashing, shorten critical path activities with the lowest cost slope first, and recheck the critical path after each step since it can change.`},
    {t:`Ask Northgate for a two week extension, since the cut was outside anyone's control.`,s:0,d:{trust:0,conf:-3,health:0},after:`Northgate says no. Their fiscal year doesn't care about Halcyon's budget.`,why:`When the date is a hard constraint, exhaust compression options first. Asking for relief you know isn't available wastes time.`}
   ]},
  {id:`f12s11`, domain:`Business Environment`, task:`B2`, title:`Northgate wants proof`,
   text:(s,all,G)=>[`Northgate's security team asks for Halcyon's SOC 2 report and confirmation that the disclosure requirement will be met at go-live. Grant wants to tell them yes on both today.`],
   opts:[
    {t:`Tell Northgate yes on both today to keep the deal moving smoothly ahead.`,s:0,d:{trust:0,conf:-3,health:-2},after:`The SOC 2 report turns out to be a year old with a bridge letter needed. Northgate's security lead notices.`,why:`Compliance commitments must be verified before they're made. A wrong yes damages trust more than a careful answer.`},
    {t:`Have Nora confirm what's current, then send them the evidence with the plan.`,s:3,best:true,d:{trust:1,conf:4,health:3},after:`Nora sends the report with a bridge letter and the disclosure requirement traced to its test case. Northgate's security lead calls it the cleanest package she's received this year.`,why:`Verify compliance status with the people who own it, then communicate accurately with evidence. Traceability from requirement to test is what auditors and customers look for.`},
    {t:`Send the SOC 2 report now and promise the disclosure plan at a later date.`,s:1,d:{trust:0,conf:0,health:0},after:`Half an answer. Northgate follows up twice.`,why:`Partial answers create follow-up and doubt. Confirm and send what's needed together when you can.`},
    {t:`Ask Northgate to wait until the end of the project for compliance evidence.`,s:0,d:{trust:0,conf:-2,health:-1},after:`Northgate's security team flags Halcyon as a risk vendor.`,why:`Compliance is planned and evidenced throughout the project, not saved for the end.`}
   ]},
  {id:`f12s12`, domain:`Business Environment`, task:`B7`, title:`Telling people about the cut`,
   text:(s,all,G)=>[`The board approves the fifteen percent cut. The billing project is cancelled, two teams merge, and hiring freezes. Eleven people are reassigned. Nobody is laid off, but nobody has been told that yet, and the Slack channels are full of guesses.`],
   opts:[
    {t:`Wait until every detail is final before saying anything to anyone at all.`,s:0,d:{trust:-5,conf:0,health:-2},after:`By Monday a rumor says forty people are being laid off. Two engineers interview elsewhere.`,why:`In organizational change, silence fills with rumor. Communicate early and honestly, even with incomplete details.`},
    {t:`Ask Elena to send a company-wide email explaining the cut and the reasons.`,s:1,d:{trust:0,conf:1,health:0},after:`The email is clear. People still don't know what it means for their own work.`,why:`Leadership communication is necessary, but change lands at the team level. People need to hear what it means for them, from someone who can answer questions.`},
    {t:`Say what's decided and unknown, then meet each reassigned person.`,s:3,best:true,d:{trust:6,conf:2,health:3},after:`Sam and Lena hold an open session Friday: no layoffs, what's cancelled, what's merged, what isn't known yet. Then they meet each of the eleven. Two of them ask to join Northgate. Both end up there.`,why:`Supporting organizational change means clear, honest, early communication, a chance to ask questions, and individual attention for the people most affected. People can handle hard news. They can't handle not knowing.`},
    {t:`Let each team lead explain the changes to their team however they think best.`,s:0,d:{trust:-1,conf:0,health:-1},after:`Six team leads give six different versions. The rumors get more specific, not fewer.`,why:`Delegating without a consistent message produces contradictions. Align the message first, then cascade it.`}
   ]}
 ],
 drills:[
  {after:`f12s10`, title:`Which activity to crash`,
   setup:[`Keisha's two critical path activities can be shortened by adding people. Northgate needs two weeks back. Both activities are on the critical path in sequence, and shortening either by up to two weeks won't change which path is critical.`],
   table:[[`Activity`,`Normal duration`,`Normal cost`,`Crash duration`,`Crash cost`],[`EHR interface build`,`6 weeks`,`$40,000`,`4 weeks`,`$52,000`],[`Clinical validation`,`5 weeks`,`$30,000`,`3 weeks`,`$46,000`]],
   fields:[{label:`Cost slope of the interface build ($ per week)`,answer:6000,tol:1},{label:`Cost slope of clinical validation ($ per week)`,answer:8000,tol:1},{label:`Cheapest added cost to recover two weeks ($)`,answer:12000,tol:1}],
   solution:[`Cost slope = (crash cost − normal cost) ÷ (normal duration − crash duration).`,`Interface build: ($52,000 − $40,000) ÷ (6 − 4) = $12,000 ÷ 2 = $6,000 per week.`,`Clinical validation: ($46,000 − $30,000) ÷ (5 − 3) = $16,000 ÷ 2 = $8,000 per week.`,`Crash the cheaper activity first. Two weeks from the interface build costs 2 × $6,000 = $12,000.`,`On the exam, only crash critical path activities, start with the lowest cost slope, and recheck the critical path after each change.`]}
 ],
 exercise:{after:`f12s9`, title:`Sort the scan`, intro:`For each change Halcyon noticed, pick the PESTLE category it belongs to.`,
  items:[
   {prompt:`The state health department finalizes guidance on AI disclosure in patient records.`,choices:[`Political`,`Economic`,`Social`,`Technological`,`Legal`,`Environmental`],answer:4,why:`A binding regulation or guidance with compliance obligations is a legal factor.`},
   {prompt:`Hospital budgets tighten as interest rates rise and reimbursement falls.`,choices:[`Political`,`Economic`,`Social`,`Technological`,`Legal`,`Environmental`],answer:1,why:`Budgets, rates, and reimbursement are economic factors.`},
   {prompt:`Nurses' unions publicly question AI in clinical documentation.`,choices:[`Political`,`Economic`,`Social`,`Technological`,`Legal`,`Environmental`],answer:2,why:`Workforce attitudes and public opinion are social factors.`},
   {prompt:`A new open source language model matches Halcyon's accuracy at lower cost.`,choices:[`Political`,`Economic`,`Social`,`Technological`,`Legal`,`Environmental`],answer:3,why:`New technology that changes what's possible or cheap is a technological factor.`},
   {prompt:`A state election brings in a governor who promises to fund rural hospital technology.`,choices:[`Political`,`Economic`,`Social`,`Technological`,`Legal`,`Environmental`],answer:0,why:`Government priorities and policy direction are political factors.`},
   {prompt:`IronPeak's data center faces new limits on power use during summer heat.`,choices:[`Political`,`Economic`,`Social`,`Technological`,`Legal`,`Environmental`],answer:5,why:`Climate and energy constraints are environmental factors.`}
  ]},
 quiz:[
  {q:`A competitor releases a cheaper product during your project. What should the project manager do first?`,opts:[`Add features to stay competitive`,`Assess the impact on objectives`,`Ask the sponsor to cut the price`,`Continue as planned and ignore it`],a:1,why:`Evaluate the external change's impact on objectives and the business case before changing anything.`,task:`B8`,domain:`Business Environment`},
  {q:`A new regulation affecting the product is announced mid-project. What is the best next step?`,opts:[`Wait for enforcement guidance`,`Have the team implement a quick fix`,`Define requirements with compliance`,`Ask the customer how to handle it`],a:2,why:`Identify compliance requirements with the right experts, then manage them through change control.`,task:`B2`,domain:`Business Environment`},
  {q:`A risk is outside the project manager's authority and affects the whole organization. Which response is appropriate?`,opts:[`Mitigate`,`Accept`,`Transfer`,`Escalate`],a:3,why:`Escalate risks outside the project's scope or the PM's authority, and record the new owner.`,task:`B5`,domain:`Business Environment`},
  {q:`Activity A can be crashed at $4,000 per week, and activity B at $3,000 per week. Both are critical. Which should be crashed first?`,opts:[`Activity B`,`Activity A`,`Both equally`,`Neither`],a:0,why:`Crash the critical path activity with the lowest cost slope first.`,task:`R8`,domain:`Process`},
  {q:`What is the main risk of fast tracking a schedule?`,opts:[`Higher direct labor costs`,`Rework from overlapping work`,`A longer critical path`,`Lower team morale`],a:1,why:`Fast tracking overlaps activities planned in sequence, which increases risk and potential rework.`,task:`R8`,domain:`Process`},
  {q:`Two senior leaders disagree sharply in a meeting. What should the project manager do?`,opts:[`Support the leader with better data`,`Stay out of executive conflicts`,`Propose splitting the difference`,`Refocus on the shared goal with facts`],a:3,why:`Focus on shared interests and facts, and move the conflict to a setting where collaboration can happen.`,task:`P2`,domain:`People`},
  {q:`Which conflict resolution approach usually produces the most lasting result when time allows?`,opts:[`Collaborate or problem solve`,`Compromise or reconcile views`,`Smooth over or accommodate`,`Force the decision or direct`],a:0,why:`Collaboration addresses underlying interests and builds commitment, making it the preferred mode when time allows.`,task:`P2`,domain:`People`},
  {q:`An organization announces restructuring, and rumors are spreading. What should the project manager do?`,opts:[`Wait until all details are final`,`Share what's decided and what's unknown`,`Let team leads explain it their own way`,`Forward the CEO's announcement email`],a:1,why:`Early, honest communication about what's known and unknown limits rumors and supports people through change.`,task:`B7`,domain:`Business Environment`},
  {q:`A customer pushes back on paying for a change driven by new regulation. What should the project manager do?`,opts:[`Absorb the cost to keep the customer`,`Insist the contract makes them pay`,`Review the contract and present options`,`Delay the change until they agree`],a:2,why:`Use the contract and change control to bring fair options to the decision makers.`,task:`B3`,domain:`Business Environment`},
  {q:`Which tool links each requirement, including compliance needs, to its source and test?`,opts:[`Requirements traceability matrix`,`Risk breakdown structure`,`Responsibility assignment matrix`,`Work breakdown structure`],a:0,why:`The requirements traceability matrix traces requirements from source through design and testing.`,task:`B2`,domain:`Business Environment`},
  {q:`A sponsor proposes deep budget cuts. What should the project manager provide?`,opts:[`Agreement to show they are a team player`,`A warning that the project will fail`,`No input, since budget is the sponsor's call`,`Impact analysis with options at each level`],a:3,why:`Give decision makers impact analysis and options so they can decide with full information.`,task:`B5`,domain:`Business Environment`},
  {q:`After major external changes, how should the risk register be updated?`,opts:[`Add the new risks at the top`,`Reassess all risks, scores, and owners`,`Wait until the situation settles`,`Let each owner update their own risks`],a:1,why:`Reassess the whole register: new risks, rescored existing risks, retired risks, and updated responses.`,task:`B5`,domain:`Business Environment`},
  {q:`An activity's normal cost is $20,000 for 8 weeks; its crash cost is $29,000 for 5 weeks. What is its cost slope?`,opts:[`$1,800 per week`,`$9,000 per week`,`$3,000 per week`,`$3,600 per week`],a:2,why:`($29,000 − $20,000) ÷ (8 − 5) = $9,000 ÷ 3 = $3,000 per week.`,task:`R8`,domain:`Process`},
  {q:`Which PESTLE category does a change in data privacy law fall under?`,opts:[`Political`,`Technological`,`Social`,`Legal`],a:3,why:`Laws and regulations are legal factors.`,task:`B8`,domain:`Business Environment`},
  {q:`Two team leads argue over which tool to use. The project manager has time. What is the best approach?`,opts:[`Agree on criteria, then decide together`,`Choose the tool most of the company uses`,`Let each team keep its own tool for now`,`Escalate the decision to the CTO`],a:0,why:`Collaborate by agreeing on objective criteria first. The people who live with the decision should make it.`,task:`P2`,domain:`People`}
 ],
 closing:(s,all,G)=>[
  ((s.flags.cutcorners||G.cutcorners)?`The cuts went deeper than they needed to, and Sam knew it. Northgate was short two contractors and the disclosure work was a week behind. He wrote it on the index card under the first sentence: "Agreed without the numbers. Don't again."`:`The fifteen percent cut held. Nobody was laid off. Northgate kept its contractors, and the disclosure feature shipped to Cascade three days before the compliance date.`),
  `Friday evening Lena came by Sam's office with two coffees, which was new. <span class="said" data-who="Lena">"Elena called me after the board,"</span> she said. <span class="said" data-who="Lena">"She said she should have asked me what I thought months ago. Then she asked me to present the Meridian strategy next quarter."</span> Lena put a coffee on his desk. <span class="said" data-who="Lena">"I didn't nod once. It was terrible. I'd do it again."</span>`,
  `Ruth called on the drive home, which she did about once a month now. Sam told her about the board, the covenant, and Lena in the stairwell.`,
  `<span class="said" data-who="Ruth">"At NASA we had a phrase,"</span> Ruth said. <span class="said" data-who="Ruth">"Go fever. When everybody wants the launch so badly that nobody wants to be the one to say stop. The best thing that happened to you this month isn't the cut. It's that Lena learned to say stop."</span> She paused. <span class="said" data-who="Ruth">"Some people never learn it. I learned it late."</span> She didn't explain, and Sam didn't ask. He was starting to understand that she'd tell him when she was ready.`,
  `On Monday the merged team started on Northgate and Cascade phase two at the same time. Priya had two projects, two customers, and one platform. On Tuesday morning an email arrived from a name Sam hadn't seen in four months. <span class="said" data-who="Theo">"Heard you might need someone who knows the old inference pipeline. Contract only. My terms. Theo."</span>`
 ],
 episode:{src:`audio/full-ch12.mp3`, len:`about 35 minutes`},
 next:`Two Projects`
});
