(window.HALCYON_FULL=window.HALCYON_FULL||[]).push({
  num: 13, part: "Part Two: The PMO", title: "Two Projects", weeks: "Months 7 to 9",
  tasks: ["R4","P5","P8","R8","P3"],
  cast: [["Dr. Helen Park","CIO, Northgate Health. Precise, polite, keeps score."],["Ken Ito","Halcyon security lead. Owns the people every project wants."]],
  opening: [
    `The merger memo went out on a Thursday, which Sam had learned was the day companies chose for news they hoped would be forgotten by Monday. Two teams became one. A product line that three people had loved was gone. The org chart on the wiki now had Sam's name above two projects instead of one.`,
    `Project one was phase two for Cascade: the discharge instructions agents that Grant had promised on a sales call fourteen months ago and that had finally earned a charter of their own. Project two was Northgate Health, a nine hospital system in Kansas and Nebraska that had signed in month six with a go-live date its board had already announced to the press.`,
    `Both projects needed the same people. Priya Shah, who now ran the platform. Tomasz Nowak's team in Kraków, who knew the integration layer better than anyone in Denver. Ken Ito's two security engineers, who reported to Ken and only lent themselves out when someone asked nicely and early.`,
    `Victor Adeyemi had joined the board in month six with a private equity background and a habit of asking what things cost before asking what they were for. His first email to Sam was one line long. <span class="said" data-who="Victor">"Show me utilization by person, weekly."</span>`,
    `Dana found Sam at the kitchen table at eleven that night with two schedules printed side by side and a highlighter in each hand. <span class="said" data-who="Dana">"You know they make software for that,"</span> she said.`,
    `<span class="said" data-who="Sam">"The software says Priya is a hundred and forty percent allocated,"</span> Sam said. <span class="said" data-who="Sam">"I wanted to see if paper agreed."</span>`,
    `She looked over his shoulder. <span class="said" data-who="Dana">"Paper agrees. Paper also says you should go to bed."</span>`,
    `He didn't. He sat there another twenty minutes thinking about something Ray Mendez used to say on the flight line when two jets needed the same hydraulic mule at the same time. <span class="said" data-who="Ray">"You can't wish a second mule into existence. Somebody waits. Your job is deciding who, and telling them before they find out."</span>`
  ],
  lesson: {
    title: `Resources across more than one project`,
    sections: [
      { h: `Planning resources is planning people`,
        body: [
          `A resource management plan says how you'll estimate, acquire, manage, and release the people and physical resources a project needs. It usually includes roles and responsibilities, a project organization chart, how you'll get people (pre-assignment, negotiation, acquisition from outside), training needs, recognition, and how you'll release people when their work is done. A RACI chart is the common tool for showing who is responsible, accountable, consulted, and informed for each deliverable. There should be exactly one accountable person per deliverable.`,
          `A resource histogram shows how many hours of a person or role you need in each period. When the bars go above the line that shows availability, you have an over-allocation. That's the moment to optimize, not the moment to ask people to work weekends. A resource calendar tells you the line: when each person is actually available, after holidays, training, and other projects are subtracted.`
        ],
        terms: [[`Resource histogram`,`Bar chart of resource demand per time period against availability.`],[`RACI`,`Responsible, Accountable, Consulted, Informed. One A per deliverable.`],[`Resource calendar`,`When a person or resource is actually available, including holidays and other commitments.`]],
        exam: `If a question shows a resource over-allocated, the exam wants you to analyze and optimize the schedule, then negotiate, before adding overtime or escalating.` },
      { h: `Leveling versus smoothing`,
        body: [
          `Resource leveling adjusts start and finish dates to fix over-allocation. Because it moves work based on resource limits, it can change the critical path and push out the end date. Resource smoothing also adjusts activities, but only within their float, so the end date and critical path don't move. Smoothing may not fix every over-allocation; leveling will, at the cost of time.`,
          `A quick way to remember it: leveling flattens the hills even if the road gets longer. Smoothing sands the bumps without moving the destination.`
        ],
        terms: [[`Resource leveling`,`Rescheduling to resolve resource limits; can extend the schedule and change the critical path.`],[`Resource smoothing`,`Rescheduling within available float only; the end date doesn't change.`],[`Float`,`How long an activity can slip without delaying the project end date.`]],
        exam: `Watch the wording. "Without changing the end date" points to smoothing. "Even if the finish date moves" points to leveling.` },
      { h: `Organization structure decides your authority`,
        body: [
          `In a functional organization the functional manager controls people and budget, and the project manager has little authority. In a weak matrix the PM is closer to a coordinator. In a balanced matrix authority is shared. In a strong matrix the PM has more authority than the functional manager and often a dedicated team. In a projectized organization the PM controls nearly everything.`,
          `Most project managers live in some kind of matrix. That means negotiation with functional managers is a core skill. Ask early, explain the business need, offer something back such as a clear end date or a growth opportunity for their person, and get agreements in writing in the resource plan.`
        ],
        terms: [[`Functional manager`,`Owns the people and their day jobs; lends them to projects.`],[`Strong matrix`,`PM has significant authority and a full time role.`]],
        exam: `When a functional manager won't release someone, the first move is a conversation with that manager about need and impact, not an escalation to the sponsor.` },
      { h: `Dependencies and scaling agile`,
        body: [
          `Dependencies come in four kinds. Mandatory dependencies are built into the work (you can't test code that doesn't exist). Discretionary ones are preferences or best practice. External dependencies involve parties outside the project. Internal ones are within the project's control. Mandatory and external dependencies limit your options when you try to compress a schedule.`,
          `When several agile teams build one product, they need a way to coordinate. A scrum of scrums brings a representative from each team together often to surface dependencies and blockers. Larger frameworks such as SAFe use a shared planning event, often called PI planning, where all teams plan the next increment together and make dependencies visible on a program board. You don't need to memorize a framework for the exam, but you do need to know that coordination and visible dependencies are the answer, not each team planning alone.`
        ],
        terms: [[`Scrum of scrums`,`Regular meeting of team representatives to coordinate across teams.`],[`Program board`,`A visual map of features and cross team dependencies for an increment.`]],
        exam: `For multiple agile teams with tangled dependencies, pick the answer that gets the teams planning together and makes dependencies visible.` },
      { h: `Recognition, development, and release`,
        body: [
          `Resource management doesn't end at assignment. Teams need to be developed through training, coaching, and stretch assignments, and recognized in ways that matter to them. Recognition works best when it's specific, timely, and public when the person is comfortable with that. Rewards should reinforce the behavior you want, such as collaboration, rather than heroics that hide planning problems.`,
          `Releasing people is part of the plan too. When someone's work is done, release them on schedule so their functional manager can count on getting them back. Projects that hold people past their need make functional managers reluctant to lend them next time. A clean release, with a thank you and a note to their manager about what they did, is how you earn the next yes.`
        ],
        terms: [[`Pre-assignment`,`People named to the project in advance, often in the charter or a proposal.`],[`Virtual team`,`A team that works across locations and time zones, relying on shared tools and agreements.`]],
        exam: `If a question asks how to keep functional managers willing to share people, look for timely release and honest, early communication about need.` },
      { h: `Communication and alignment at scale`,
        body: [
          `Every new stakeholder adds communication channels, and the number grows fast. The formula from chapter three still applies: n times n minus 1, divided by 2. Ten people have 45 channels; add four more and you have 91. The answer isn't more meetings. It's a communication plan tailored to each group: what they need, how often, in what format, from whom. Information radiators such as shared boards let people pull status instead of waiting for it to be pushed. When two customers want different things from the same team, bring them to a shared, transparent prioritization rather than making separate promises you can't both keep.`
        ],
        terms: [[`Information radiator`,`A visible display of project information anyone can check.`],[`Communication management plan`,`Who needs what information, when, how, and from whom.`]],
        exam: `When stakeholders have conflicting expectations, the exam favors bringing them together with clear criteria over negotiating with each one separately.` }
    ],
    video: [`NnYhXHcn2zs`,`Resource Leveling versus Resource Smoothing`,`David McLachlan`,`4:07`]
  },
  scenes: [
    { id:`f13s1`, domain:`Process`, task:`R4`, title:`Two projects, one Priya`,
      text:(s,all,G)=>[`Monday's numbers are worse than Sunday's. Priya is planned at 140 percent for the next six weeks. Tomasz's team is double booked for three sprints. Ken's security engineers are promised to both projects in the same two weeks.`,`<prop type="chart" kind="bars" title="Planned allocation, next six weeks (percent of capacity)" labels="Priya,Tomasz's team,Ken's security engineers,Keisha" values="140,200,200,90"></prop>`,`Victor wants a decision by Friday. Elena wants both projects on time. Priya wants someone to tell her which fire to stand in.`],
      opts:[
        {t:`Map both projects' demand in one view and bring options to the governance forum.`, s:3, best:true, d:{trust:3,conf:5,health:5}, after:`Sam merges both schedules into one histogram and walks the delivery governance meeting through three options with their costs. Elena and Victor pick an order. Priya finally has an answer she can repeat to her team.`, why:`Two projects competing for one person is a portfolio decision, not a coin flip in your head. Make the conflict visible with real data, bring options, and let the people with authority choose. That's governance working the way it should.`},
        {t:`Decide himself that Northgate wins, since it has the board announcement behind it.`, s:1, d:{trust:0,conf:-2,health:2}, after:`Northgate gets everything. Ochoa finds out from a Cascade engineer that phase two slipped, and calls Elena before Sam can explain.`, why:`Your reasoning might be right, but the decision belongs to the sponsors through governance. Deciding alone also means nobody else owns the consequences you just created for Cascade.`},
        {t:`Split every shared person evenly so neither project can say it was shortchanged.`, s:0, d:{trust:-3,conf:0,health:-5}, after:`Priya spends her days switching between two codebases. Both projects slow down, and nobody is happy with the even split.`, why:`An even split feels fair and usually hurts both projects, because constant context switching wastes time. Allocation should follow priority, and priority comes from governance.`},
        {t:`Ask recruiting to open three new roles today so the shortage simply goes away.`, s:0, d:{trust:0,conf:-3,health:-1}, after:`Victor declines the requisitions within the hour. Even if he hadn't, new hires wouldn't be productive for two months.`, why:`Hiring may help later, but it doesn't solve a six week conflict and you didn't analyze the need first. Optimize and prioritize what you have before asking for more.`}
      ]},
    { id:`f13s2`, domain:`Process`, task:`R8`, title:`The leveling question`,
      text:(s,all,G)=>[`The Northgate integration plan has two activities that both need Priya on the same days: building the Northgate data adapter and hardening the shared authentication service. After both finish, Tomasz's team runs the end to end tests.`,`Sam's planner shows a finish date that assumes Priya can be in two places at once. Victor has already copied that date into his board deck.`],
      opts:[
        {t:`Level the plan to Priya's real availability and share the new end date.`, s:3, best:true, d:{trust:2,conf:3,health:5}, after:`The leveled schedule adds three days. Sam shows Victor before the board deck goes out, along with the two ways to get the days back.`, why:`If one person is the constraint, leveling gives you a schedule you can actually hit. It may move the end date, and that's the honest answer. Tell people early, with options.`},
        {t:`Keep the date and ask Priya to work both tasks in parallel with extra hours.`, s:0, flag:`overloadedpriya`, d:{trust:-5,conf:0,health:-3}, after:`Priya says yes, because she always says yes. Both tasks finish late and the authentication service ships with a bug. She stops eating lunch at her desk and starts skipping it.`, why:`Overtime isn't a plan for a known over-allocation. It burns out your most important person and usually costs quality. Fix the schedule, not the person.`},
        {t:`Smooth the schedule inside the float and accept whatever over-allocation remains.`, s:1, d:{trust:0,conf:0,health:1}, after:`Smoothing helps a little, but the activities have almost no float. Priya is still double booked for four days.`, why:`Smoothing is the right first try when you need to protect the end date, but it only works within float. When the float isn't there, you need leveling and an honest new date.`},
        {t:`Give the authentication work to Devin quietly, without updating the official plan.`, s:0, d:{trust:-2,conf:-1,health:-2}, after:`Devin doesn't know the auth service. The plan still says Priya. When it slips, nobody can tell why from the plan.`, why:`Reassigning work can be valid, but doing it off the books leaves the plan wrong and the risk invisible. Any change goes through the plan so everyone sees the real picture.`}
      ]},
    { id:`f13s3`, domain:`People`, task:`P3`, title:`Theo comes back`,
      text:(s,all,G)=>[(G.blamedtheo?`Sam still remembers saying Theo's name in front of the whole team after the burn-in failure. Theo remembers it too. `:``)+`Theo Lindqvist is back, on a six month contract, working three days a week from his new place in Boulder. He looks rested for the first time since Sam met him.`,`Within two days, four engineers have already asked him to "just take a quick look" at things outside his scope.`],
      opts:[
        {t:`Scope Theo's role to pairing and teaching, with deliverables in his contract.`, s:3, best:true, d:{trust:5,conf:1,health:4}, after:`Theo's statement of work says he pairs with Priya's team and leaves runbooks behind, not that he fixes things himself. Requests go through Priya. Theo says it's the first job description he's liked.`, why:`You learned what a single point of failure costs. Bring the expertise back in a way that spreads knowledge instead of concentrating it. Clear scope protects Theo and the team.`},
        {t:`Let the team use Theo however they need. He's the expert and time is short.`, s:0, d:{trust:-2,conf:0,health:-3}, after:`By week three Theo is the bottleneck again, and this time he's a contractor who can leave on two weeks' notice.`, why:`That's how you rebuild the exact problem you spent a year fixing. Expertise without boundaries becomes a constraint again.`},
        {t:`Have Theo report only to Sam so his time can be protected from everyone else.`, s:1, d:{trust:-1,conf:0,health:1}, after:`Theo is protected, but now Sam is the bottleneck for every question about the platform.`, why:`Protecting his time is right. Routing everything through yourself just moves the constraint. Put the boundary in the role, and let the team lead manage requests.`},
        {t:`Keep Theo off the main projects and use him only for a separate research spike.`, s:0, d:{trust:0,conf:-1,health:-2}, after:`Theo writes an excellent research paper. Meanwhile the integration problems he could have taught the team to solve stay unsolved.`, why:`Isolating your best expert wastes the main reason you brought him back, which is to grow the people who'll stay.`}
      ]},
    { id:`f13s4`, domain:`People`, task:`P5`, title:`Two customers, one roadmap`,
      text:(s,all,G)=>[`Ochoa wants discharge instructions before winter flu season. Dr. Helen Park at Northgate wants the medication history feature her board announced. Both features need the same team in the same quarter.`,`Both CIOs have been told by someone at Halcyon that they're the top priority.`],
      opts:[
        {t:`Hold a joint roadmap session where both CIOs see the same criteria and tradeoffs.`, s:3, best:true, d:{trust:1,conf:6,health:3}, after:`It's tense for twenty minutes. Then Park points out that her board date is a press release, not a clinical deadline, and Ochoa's flu season isn't negotiable. They agree on an order that neither would have accepted from Halcyon alone.`, why:`When stakeholders have conflicting expectations, align them openly with shared criteria. People accept tradeoffs they can see better than decisions made about them in private.`},
        {t:`Meet each CIO separately and tell each one a slightly different version of the plan.`, s:0, d:{trust:0,conf:-7,health:0}, after:`Park and Ochoa know each other from a regional health IT group. It takes them nine days to compare notes.`, why:`Telling different stories to different stakeholders is an honesty problem and it always comes out. The Code of Ethics and basic trust both rule it out.`},
        {t:`Let Elena pick the order, then tell both CIOs what she decided and why.`, s:1, d:{trust:0,conf:1,health:2}, after:`Elena picks Cascade. Park accepts it but feels handled, and says so in the next steering meeting.`, why:`Escalating to the sponsor gets a decision, which is better than drifting. But you skip the chance to build agreement with the stakeholders, so you inherit resentment.`},
        {t:`Promise both features in the same quarter and add Kraków capacity to cover it.`, s:0, d:{trust:-2,conf:2,health:-6}, after:`Tomasz's team is already full. The promise holds for six weeks and then breaks for both customers at once.`, why:`Promising both without analyzing capacity defers the conflict and makes it bigger. Manage expectations with facts now rather than disappointment later.`}
      ]},
    { id:`f13s5`, domain:`People`, task:`P8`, title:`Too many meetings`,
      text:(s,all,G)=>[`Two customers, four teams, two offshore time zones, a board member who wants weekly utilization, and a sponsor who wants a Friday page. Sam counts thirty one standing meetings on his calendar.`,`Priya says she spends more time reporting status than producing it.`],
      opts:[
        {t:`Rebuild the comms plan by audience and move status to a shared live board.`, s:3, best:true, d:{trust:4,conf:3,health:4}, after:`Sam asks each group what they actually use. Status moves to a live board anyone can check. Eleven meetings disappear, and Victor gets his utilization view without a meeting at all.`, why:`Scale communication by tailoring it to each audience and letting people pull information from radiators. More meetings isn't communication; the right information to the right people is.`},
        {t:`Cancel every recurring meeting for two weeks and see which ones people miss.`, s:1, d:{trust:2,conf:-3,health:1}, after:`The team loves it. Park's team doesn't, because nobody told them, and they spend a week guessing.`, why:`Pruning meetings is good instinct, but cutting communication without a plan leaves stakeholders in the dark. Change the plan deliberately and tell people what replaces what.`},
        {t:`Add a weekly all-hands across both projects so everyone hears the same thing.`, s:0, d:{trust:-1,conf:0,health:-2}, after:`The all-hands has fifty people and is useful to about five of them.`, why:`One broadcast meeting for everyone ignores that different stakeholders need different information. It adds load instead of reducing it.`},
        {t:`Have Priya's team send detailed written updates every day to all stakeholders.`, s:0, d:{trust:-3,conf:1,health:-2}, after:`The updates are thorough. Nobody reads them past Tuesday, and Priya's team loses an hour a day.`, why:`Pushing more information isn't the same as communicating. It shifts the burden to the team and buries what stakeholders need.`}
      ]},
    { id:`f13s6`, domain:`Process`, task:`R4`, title:`Ken says no`,
      text:(s,all,G)=>[`Northgate's security review needs one of Ken Ito's engineers for three weeks starting Monday. Ken says no. His team has an audit of its own and he's already lent people to Sam twice this year.`,`Halcyon is a balanced matrix. Ken owns his people. Sam owns the Northgate date.`],
      opts:[
        {t:`Meet Ken, explain the Northgate impact, and find timing that fits his audit too.`, s:3, best:true, d:{trust:3,conf:2,health:4}, after:`Ken's audit crunch is the first two weeks. They agree his engineer starts in week two, and Sam lends Ken a Kraków tester for the audit's evidence work. Both dates hold.`, why:`In a matrix the functional manager owns the resource. Negotiate with them directly, understand their constraints, and look for an exchange that works for both. Escalate only if that fails.`},
        {t:`Escalate to Elena and ask her to direct Ken to release the engineer Monday.`, s:0, d:{trust:-4,conf:0,health:2}, after:`Elena tells Ken to do it. Ken does, and stops returning Sam's messages for a month.`, why:`Going over a functional manager's head before talking it through damages a relationship you'll need again. Escalation is for after a real attempt fails.`},
        {t:`Ask Ken's engineer directly if she'd be willing to help in her spare time.`, s:0, d:{trust:-3,conf:0,health:0}, after:`She agrees, then her manager finds out. Now Ken has a reason to be angry and so does she.`, why:`Recruiting someone around their manager undermines the matrix and puts that person in a bad spot. Work through the manager.`},
        {t:`Accept the no, log a schedule risk, and push the security review back three weeks.`, s:1, d:{trust:1,conf:-2,health:-3}, after:`Logging it is correct. Accepting it without trying to solve it costs Northgate three weeks it didn't need to lose.`, why:`Documenting the risk is good practice, but you skipped negotiating. Try to resolve the constraint before accepting the impact.`}
      ]},
    { id:`f13s7`, domain:`People`, task:`P3`, title:`Tangled teams`,
      text:(s,all,G)=>[`Four teams now touch the Northgate release: platform, integration in Kraków, the agents team, and security. Each runs its own two week sprints. Each discovers the other teams' changes when something breaks.`,`Last sprint, two teams built the same data mapping without knowing it.`],
      opts:[
        {t:`Plan the next increment with all four teams and put dependencies on one board.`, s:3, best:true, d:{trust:4,conf:2,health:5}, after:`The planning day is long and loud. By the end there's a program board with every cross team dependency pinned and an owner on each one. A twice weekly scrum of scrums keeps it current.`, why:`Multiple agile teams on one product need shared planning and visible dependencies. That's the core of every scaling approach, whatever its name.`},
        {t:`Make all four teams use the same sprint calendar so their work lines up.`, s:1, d:{trust:0,conf:0,health:2}, after:`Aligned cadences help, but teams still plan alone and still collide mid sprint.`, why:`A shared cadence is a good start and often part of scaling. By itself it doesn't make dependencies visible or coordinated.`},
        {t:`Merge all four teams into one large team with a single backlog and standup.`, s:0, d:{trust:-2,conf:0,health:-3}, after:`The standup has thirty one people and runs fifty minutes.`, why:`Agile teams work best small. Scaling means coordinating several small teams, not building one huge one.`},
        {t:`Have Sam review every team's sprint plan and resolve conflicts before each sprint.`, s:0, d:{trust:-3,conf:0,health:-1}, after:`Sam becomes the integration point for four teams and the reason sprints start late.`, why:`Centralizing coordination in the PM turns you into the bottleneck and takes ownership away from the teams. Help them coordinate with each other.`}
      ]},
    { id:`f13s8`, domain:`Process`, task:`R8`, title:`The API is late`,
      text:(s,all,G)=>[`Kraków's new patient record API, a mandatory dependency for the Northgate integration, is eight days late. The integration team is waiting. Northgate's go-live is in five weeks.`,`Victor's message is short. <span class="said" data-who="Victor">"Add people or work weekends. Pick one."</span>`,(G.nolessons?`It's the LabelForge pattern all over again, a dependency nobody tracked weekly. There's no lessons file to point to, because Cascade never held a lessons learned session.`:`Sam pulls up the Cascade lessons file. Lesson four: track every external dependency weekly with a named owner. They did, which is why they know on day eight instead of day twenty.`)],
      opts:[
        {t:`Measure the critical path impact first, then choose how to compress it.`, s:3, best:true, d:{trust:2,conf:3,health:5}, after:`The analysis shows four of the eight days are absorbed by float. Overlapping integration testing with the last API work recovers the rest, at some added risk Sam writes down.`, why:`Analyze before you compress. Know whether the delay hits the critical path and how much, then choose fast tracking (overlap, adds risk) or crashing (add resources, adds cost) based on facts.`},
        {t:`Add two contractors to the Kraków team right away to get the API back on track.`, s:0, d:{trust:-1,conf:0,health:-2}, after:`The new contractors need a week to ramp up, and the Kraków team slows down to onboard them.`, why:`Crashing late work by adding people often slows it further. And you acted without knowing whether the delay even mattered to the end date.`},
        {t:`Ask the Kraków team to work the next two weekends to recover the eight days.`, s:0, d:{trust:-5,conf:0,health:-1}, after:`Tomasz agrees and says nothing more. Two of his engineers resign the following month.`, why:`Overtime as a first response treats people as the buffer. Analyze first, and if you do compress, choose the option with the least harm.`},
        {t:`Tell Park the go-live date is at risk and propose moving it by eight days.`, s:1, d:{trust:0,conf:1,health:0}, after:`Park appreciates the warning, then asks what's on the critical path. Sam doesn't know yet.`, why:`Early transparency is right, but you're telling the customer about an impact you haven't measured. Analyze first so what you share is accurate.`}
      ]},
    { id:`f13s9`, domain:`People`, task:`P5`, title:`Grant at dinner`,
      text:(s,all,G)=>[`Park forwards Sam a note from a dinner she had with Grant. Grant told her the medication history feature would be in the Northgate go-live.`,`It isn't. It's in the next release, as agreed in the joint roadmap session three weeks ago.`],
      opts:[
        {t:`Talk to Grant privately, then reset Park's expectation with him in writing.`, s:3, best:true, d:{trust:2,conf:4,health:2}, after:`Grant admits he got carried away. He joins Sam's call with Park and corrects it himself. Park says it's the first time a vendor's sales lead has walked something back in front of her.`, why:`Talk to the person who caused the gap before going around them, then reset the stakeholder's expectation openly. Bringing Grant in preserves the relationship and the truth.`},
        {t:`Reply to Park right away that Grant was mistaken and the roadmap hasn't changed.`, s:1, d:{trust:-2,conf:2,health:0}, after:`Park has the right information. Grant hears about it from her before he hears it from Sam, and he's furious.`, why:`The facts are right and fast, which matters. But you bypassed Grant, which damages a relationship you need. Talk to him first unless something urgent prevents it.`},
        {t:`Ask the team whether they could squeeze the feature in so Grant's promise holds.`, s:0, d:{trust:-3,conf:1,health:-5}, after:`The team starts looking. Two committed stories slip while they do.`, why:`Reshaping the plan around an unauthorized promise rewards it and destabilizes the team. Any change goes through change control.`},
        {t:`Say nothing to Park and let the roadmap speak for itself when she reviews it.`, s:0, d:{trust:0,conf:-6,health:0}, after:`Park's team plans their nurse training around a feature that won't be there.`, why:`Silence lets a wrong expectation grow. Managing expectations means correcting them early and clearly.`}
      ]},
    { id:`f13s10`, domain:`People`, task:`P8`, title:`Eleven at night in Kraków`,
      text:(s,all,G)=>[`Tomasz asks for fifteen minutes. He's polite and very direct. Every joint meeting is scheduled for Denver's morning, which is late evening in Kraków. His team hears about decisions after Denver has already made them.`,`<span class="said" data-who="Tomasz">"We are not a vending machine,"</span> he says. <span class="said" data-who="Tomasz">"You put in a ticket and code comes out."</span>`],
      opts:[
        {t:`Rotate meeting times, write decisions up async, and credit Kraków's work by name.`, s:3, best:true, d:{trust:7,conf:1,health:3}, after:`The next demo opens with Tomasz's team presenting their own API work. Decisions now get written up before they're final, so Kraków can weigh in during their day.`, why:`Virtual teams need communication that respects time zones and includes everyone in decisions. Recognition matters too, especially for a team that feels used.`},
        {t:`Apologize and ask Tomasz to send a summary of his concerns for the next retro.`, s:1, d:{trust:1,conf:0,health:0}, after:`Tomasz sends it. The retro is two weeks away and nothing changes until then.`, why:`Taking it seriously is good, but the problem is clear and in your power to fix now. Act on it instead of queuing it.`},
        {t:`Move every meeting to Kraków's afternoon so the burden switches to Denver.`, s:0, d:{trust:0,conf:0,health:-2}, after:`Denver now meets at six in the morning. Within a week, Denver is complaining instead.`, why:`Shifting the whole burden to the other side isn't fair either. Share it, and lean on asynchronous communication.`},
        {t:`Let Tomasz's team skip the joint meetings and get a recording afterward.`, s:0, d:{trust:-4,conf:0,health:-2}, after:`Kraków is now formally excluded from decisions about their own work.`, why:`Recordings are useful, but making a team watch decisions after the fact confirms the problem Tomasz raised.`}
      ]},
    { id:`f13s11`, domain:`Process`, task:`R4`, title:`The hiring freeze`,
      text:(s,all,G)=>[`Victor announces a hiring freeze for the rest of the year. Sam's leveled plan for both projects depended on two hires starting next month.`,`Without them, the Cascade phase two date slips five weeks.`],
      opts:[
        {t:`Show the sponsor the resource gap, its impact on dates, and options to close it.`, s:3, best:true, d:{trust:1,conf:5,health:4}, after:`Elena and Victor look at the options together. They approve two six month contractors and trim one low value feature from phase two. The date moves two weeks, not five.`, why:`When a business decision changes your resources, quantify the impact and bring options to the people who can decide. That's how you keep decisions informed.`},
        {t:`Absorb the gap quietly by asking each team to take on a little more work.`, s:0, d:{trust:-4,conf:0,health:-4}, after:`Everyone takes on a little more. The five week slip arrives anyway, with tired people attached.`, why:`Quietly absorbing a resource cut hides the real impact from the people who made the decision.`},
        {t:`Move the Cascade date out five weeks and send the new schedule to Ochoa.`, s:1, d:{trust:0,conf:-1,health:2}, after:`It's honest. Ochoa asks whether anything else was considered, and Sam has to say no.`, why:`An honest new date is better than a fake one, but you skipped looking for options that could have protected more of it.`},
        {t:`Ask Elena to make an exception to the freeze just for the delivery office.`, s:1, d:{trust:0,conf:0,health:1}, after:`Elena asks what it would get her. Sam hasn't put numbers on it yet.`, why:`Asking for an exception may be right, but without the impact analysis you're asking for a favor instead of a business decision.`}
      ]},
    { id:`f13s12`, domain:`People`, task:`P3`, title:`Priya isn't sure`,
      text:(s,all,G)=>[`Sam asks Priya to lead the Northgate technical workstream. She says she'll think about it. The next morning she says Devin would be better.`,(G.sidelineddevin?`Devin would not be better. Back in Storming, Sam took Devin off the work instead of coaching him, and Devin has kept his head down ever since. Nobody, Devin included, thinks of him as a lead.`:`Devin has come a long way since the coaching in Storming, but he would not be better here. Priya knows the platform better than anyone except Theo.`)],
      opts:[
        {t:`Ask what worries her, then agree on weekly coaching and a clear escalation path.`, s:3, best:true, d:{trust:6,conf:0,health:3}, after:`It turns out she's afraid of the customer calls, not the work. Sam joins her first three calls and then stops. By the fourth, Park is asking for Priya by name.`, why:`Leading the team includes growing people into roles they're ready for. Understand the hesitation, then give support that builds confidence without taking the job back.`},
        {t:`Respect her answer and give the workstream to Devin as she suggested.`, s:1, d:{trust:1,conf:0,health:-1}, after:`Devin does fine. Priya watches and wonders whether she should have said yes.`, why:`Respecting people's choices matters, but you didn't learn why she said no, and you lost a chance to develop someone ready for more.`},
        {t:`Tell her the decision is already made and that she'll be great at it.`, s:0, d:{trust:-3,conf:0,health:0}, after:`She takes it and quietly dreads every customer call for a month.`, why:`Assigning stretch work without understanding the person's concern skips the coaching that makes stretch work succeed.`},
        {t:`Have Priya shadow Sam on Northgate for a quarter before giving her the lead.`, s:0, d:{trust:0,conf:0,health:-2}, after:`A quarter of shadowing teaches her to watch Sam lead instead of leading.`, why:`Shadowing has a place, but she already has the skills. Long shadowing delays growth and keeps the work on you.`}
      ]}
  ],
  drills: [
    { after:`f13s2`, title:`Resource leveling`,
      setup:[`Here's the Northgate slice of the schedule. Activity A (data adapter) and activity B (authentication hardening) can both start on day 1 and both need Priya full time. Activity C (end to end tests, Kraków) starts when both A and B are done.`,`Durations: A is 4 days, B is 3 days, C is 2 days. Priya can only work one activity at a time.`],
      table:[[`Activity`,`Duration (days)`,`Predecessor`,`Resource`],[`A Data adapter`,`4`,`None`,`Priya`],[`B Auth hardening`,`3`,`None`,`Priya`],[`C End to end tests`,`2`,`A and B`,`Kraków`]],
      fields:[ {label:`Project duration ignoring Priya's limit (days)`, answer:6, tol:0}, {label:`Total float on B before leveling (days)`, answer:1, tol:0}, {label:`Project duration after leveling (days)`, answer:9, tol:0}, {label:`Days added by leveling`, answer:3, tol:0} ],
      solution:[`Without the resource limit, A and B run in parallel. The longer one, A at 4 days, drives the path, then C adds 2: 4 + 2 = 6 days.`,`B takes 3 days on a 4 day window, so its float is 4 minus 3 = 1 day.`,`Priya can't do both at once, so leveling runs them one after the other: 4 + 3 = 7 days, then C: 7 + 2 = 9 days. Whichever order you choose, A and B take 7 days in a row.`,`Leveling added 9 minus 6 = 3 days and changed the critical path to A, B, C. Smoothing couldn't fix this, because B only has 1 day of float and the overlap is 3 days.`] }
  ],
  exercise: { after:`f13s7`, title:`Name the dependency`, intro:`Pick the type that fits each situation.`,
    items:[
      {prompt:`Integration tests can't run until the API they test exists.`, choices:[`Mandatory`,`Discretionary`,`External`,`Internal`], answer:0, why:`It's inherent in the work. You can't test what doesn't exist.`},
      {prompt:`The team prefers to finish the design review before coding, though it isn't required.`, choices:[`Mandatory`,`Discretionary`,`External`,`Internal`], answer:1, why:`It's a preference or best practice the team chose, so it can be changed when compressing the schedule.`},
      {prompt:`Northgate must finish its network upgrade before Halcyon can connect.`, choices:[`Mandatory`,`Discretionary`,`External`,`Internal`], answer:2, why:`It depends on a party outside the project team.`},
      {prompt:`The agents team needs the platform team's new logging library first.`, choices:[`Mandatory`,`Discretionary`,`External`,`Internal`], answer:3, why:`Both teams are inside the project, so it's within the project's control.`},
      {prompt:`Halcyon's style guide says user research happens before any interface design.`, choices:[`Mandatory`,`Discretionary`,`External`,`Internal`], answer:1, why:`It's an organizational practice, not a physical necessity, so it's discretionary.`},
      {prompt:`A state agency must approve the data sharing agreement before go-live.`, choices:[`Mandatory`,`Discretionary`,`External`,`Internal`], answer:2, why:`An outside party controls it, so it's external, and you can't compress it by working harder.`}
    ]},
  quiz: [
    {q:`A key engineer is over-allocated on two activities that both have some float. The sponsor says the end date can't move. Which technique should the project manager try first?`, opts:[`Resource leveling across all of the activities`,`Resource smoothing within available float`,`Crashing by adding contractors right away`,`Fast tracking every remaining activity`], a:1, why:`Smoothing adjusts work within float without moving the end date, which fits the constraint. Leveling can extend the schedule.`, task:`R4`, domain:`Process`},
    {q:`After resource leveling, what is most likely to happen to the schedule?`, opts:[`The end date and critical path may both change`,`The critical path stays exactly the same every time`,`Total float on every activity grows by one day`,`The budget is reduced automatically to match it`], a:0, why:`Leveling resolves resource limits by moving activities, which can extend the end date and change the critical path.`, task:`R8`, domain:`Process`},
    {q:`In a balanced matrix, a functional manager refuses to release a needed specialist. What should the project manager do first?`, opts:[`Escalate to the sponsor and ask for the release`,`Ask the specialist to help after normal hours`,`Record the issue and replan without the person`,`Meet the manager to discuss need and timing`], a:3, why:`In a matrix, negotiate directly with the functional manager first. Escalate only if that fails.`, task:`R4`, domain:`Process`},
    {q:`Two customers each believe their feature is the top priority for the same team next quarter. What is the best approach?`, opts:[`Meet each customer alone and tailor the message`,`Bring both together to set priorities openly`,`Let the sales lead decide, since he owns both`,`Commit to both and add overtime to absorb it`], a:1, why:`Align conflicting expectations openly with transparent criteria rather than separate promises.`, task:`P5`, domain:`People`},
    {q:`Four agile teams keep breaking each other's work because of hidden dependencies. What should the project manager encourage?`, opts:[`Merge all four teams into one large team`,`Have the PM approve each team's sprint plan`,`Separate the teams so they never share code`,`Plan together and map dependencies visibly`], a:3, why:`Scaled agile relies on joint planning and visible dependencies, often with a scrum of scrums.`, task:`P3`, domain:`People`},
    {q:`A project has 6 stakeholders. Four more are added. How many additional communication channels does this create?`, opts:[`15`,`30`,`45`,`60`], a:1, why:`6 stakeholders: 6 x 5 / 2 = 15. 10 stakeholders: 10 x 9 / 2 = 45. The increase is 45 minus 15 = 30.`, task:`P8`, domain:`People`},
    {q:`Which document describes how team members will be acquired, managed, and released?`, opts:[`Resource management plan`,`Communications management plan`,`Stakeholder engagement plan`,`Scope management plan`], a:0, why:`The resource management plan covers acquiring, developing, managing, and releasing resources.`, task:`R4`, domain:`Process`},
    {q:`A remote team feels excluded because decisions happen during their night. What is the best response?`, opts:[`Record each meeting and send links each morning`,`Move all meetings to their afternoon from now on`,`Ask the remote lead to attend for the whole team`,`Rotate times and decide in shared written notes`], a:3, why:`Share the time zone burden and use asynchronous communication so the whole team is included in decisions.`, task:`P8`, domain:`People`},
    {q:`A dependency on an outside vendor is late. The project manager wants to compress the schedule. Which is true?`, opts:[`External dependencies limit how much you can compress`,`External dependencies can always be fast tracked safely`,`Crashing an external dependency costs the project nothing`,`External dependencies work the same as discretionary ones`], a:0, why:`External and mandatory dependencies constrain compression because you don't control them.`, task:`R8`, domain:`Process`},
    {q:`A sales executive promised a customer a feature that isn't in the agreed roadmap. What should the project manager do first?`, opts:[`Correct the customer in writing that afternoon`,`Ask the team to fit the feature in this release`,`Talk privately with the executive about it`,`Escalate to the CEO with the customer's email`], a:2, why:`Talk to the person first, then reset the customer's expectation together through proper channels.`, task:`P5`, domain:`People`},
    {q:`A critical activity is 8 days late. Before choosing fast tracking or crashing, the project manager should:`, opts:[`ask the team to work weekends until it recovers`,`add two contractors to the late activity now`,`tell the customer the go-live date slips 8 days`,`find the impact on the critical path and end date`], a:3, why:`Analyze first. The delay may be partly absorbed by float, and the choice of compression depends on the data.`, task:`R8`, domain:`Process`},
    {q:`An engineer is ready to lead a workstream but turns it down. In private she says the customer calls scare her, not the technical work. What should the project manager do?`, opts:[`Take the customer calls himself and let her lead the rest`,`Give the workstream to an engineer who wants it more`,`Join her first few calls, then step back as she settles`,`Send her to a presentation course before she starts`], a:2, why:`She has the skills; the gap is confidence with customers. Coaching in the real work, then stepping back, builds it. Taking the calls yourself keeps her from ever growing into them, and a course delays the role without addressing the fear.`, task:`P3`, domain:`People`},
    {q:`What is the main purpose of an information radiator?`, opts:[`To show current status without anyone asking`,`To store approvals for the change control board`,`To replace the project management plan in agile`,`To track individual hours for performance reviews`], a:0, why:`Radiators make information visible so people can pull it when they need it.`, task:`P8`, domain:`People`},
    {q:`A board-mandated hiring freeze removes two planned hires. What should the project manager do?`, opts:[`Ask each team to absorb a little more work`,`Move the end date and tell the customer`,`Request an exception to the freeze for the team`,`Quantify the impact and bring options to the sponsor`], a:3, why:`Analyze the impact and bring options to decision makers so the tradeoff is made knowingly.`, task:`R4`, domain:`Process`},
    {q:`A returning expert is being pulled into every team's problems again. What best prevents a new bottleneck?`, opts:[`Let the team use the expert wherever needed`,`Route all requests through the project manager`,`Scope the role to pairing and documentation`,`Assign the expert to a separate research project`], a:2, why:`Shape the role to spread knowledge rather than concentrate it, with clear boundaries.`, task:`P3`, domain:`People`}
  ],
  closing:(s,all,G)=>[
    `By the end of month nine, Northgate's integration is two days behind a schedule that is finally honest. Phase two for Cascade has a date that survived the hiring freeze. Theo has written more documentation in eight weeks than in four years on staff, and has started calling Priya for advice instead of the other way around.`,
    `Victor's weekly utilization view shows nobody above a hundred percent for the first time. He sends Sam a one word email. <span class="said" data-who="Victor">"Better."</span> Dana says that's practically a love letter from a private equity guy.`,
    `On Thursday evening, after most of LoDo has emptied, Grant Mercer knocks on the glass of Sam's office. He doesn't have his jacket on. He doesn't have his usual smile on either.`,
    `<span class="said" data-who="Grant">"Do you have a minute?"</span> he says. <span class="said" data-who="Grant">"Actually, do you have an hour. There's something wrong with Northgate, and I think it's my fault."</span>`
  ],
  episode:{src:`audio/full-ch13.mp3`, len:`about 35 minutes`},
  next:`The Hard Conversation`
});
