(window.HALCYON_FULL=window.HALCYON_FULL||[]).push({
  num: 14, part: "Part Two: The PMO", title: "The Hard Conversation", weeks: "Month 9",
  tasks: ["B7","P6","B4","B1","P4"],
  cast: [["Alyssa Kemp","Halcyon sales engineer. Two years in, asked to do something she knew was wrong."]],
  opening: [
    `Grant talked for fifty minutes without stopping, which Sam had never seen him do. Usually Grant asked a question every thirty seconds to see how the room was taking him. Tonight he looked at the desk.`,
    `In month six, to close Northgate, Grant had told Dr. Helen Park that Halcyon's agents could reconcile medication lists in real time against a patient's pharmacy records. They couldn't. Nobody had built it. There was a slide that showed it working, made by a designer for a conference, and Grant had used it in the final pitch.`,
    `Then, in September, the Northgate status report had gone out green on scope. Someone on Grant's team had edited the scope section after Sam's office drafted it, to keep the medication feature off the "not in this release" list. Sam had signed the cover email without rereading the attachment. He'd been in Kraków that week.`,
    `<span class="said" data-who="Grant">"Park's board is going to ask about it next month,"</span> Grant said. <span class="said" data-who="Grant">"Their press release mentions it. I kept thinking I could get it built before anyone noticed. Then I saw your leveled schedule and realized there's no version of next quarter where that happens."</span>`,
    `He finally looked up. <span class="said" data-who="Grant">"I know what this does to me. I'm telling you anyway, because if I don't tell you, you'll find out the way Ochoa found things out last year, and you'll be right not to trust me ever again."</span>`,
    `Sam drove home on Speer with the radio off. Dana was grading lab reports at the kitchen table. She took one look at him and pushed the stack aside.`,
    `<span class="said" data-who="Dana">"Somebody lied?"</span> she asked.`,
    `<span class="said" data-who="Sam">"A few somebodies,"</span> Sam said. <span class="said" data-who="Sam">"And my name's on one of them."</span>`
  ],
  lesson: {
    title: `Ethics, honesty, and leading change`,
    sections: [
      { h: `The PMI Code of Ethics and Professional Conduct`,
        body: [
          `The Code rests on four values: responsibility, respect, fairness, and honesty. Each value has aspirational standards, which describe the conduct we strive for, and mandatory standards, which set firm requirements. Violating a mandatory standard can lead to disciplinary action by PMI. The exam expects you to act on all four values, not just avoid breaking rules.`,
          `Start with responsibility, because it's the one Sam is staring at. You own what you decide and what it causes, mistakes included. You don't take on work you aren't qualified to do. You keep your word, guard confidential information, and follow the law and company policy. If you see something unethical or illegal, you report it to someone who can act. And when the error is yours, you fix it now, not in the hope that nobody looks.`,
          `Respect is listening to views you don't share, negotiating in good faith, taking conflict to the person instead of around them, and never using your position to push people around or damage a reputation. Fairness is deciding without favorites, saying so out loud when you have a conflict of interest, and making sure everyone gets the same information and the same shot. Honesty means telling the truth in communication and conduct, including not creating false impressions through half truths, selective facts, or silence.`
        ],
        terms: [[`Aspirational standard`,`Conduct we strive to uphold as practitioners.`],[`Mandatory standard`,`A firm requirement; violations can bring disciplinary action.`],[`Conflict of interest`,`A situation where personal interest could influence a professional decision. Disclose it and step back.`]],
        exam: `When an ethics question appears, the answer almost never involves hiding, softening, or delaying the truth. Look for the option that is honest, follows policy, and reports through proper channels.` },
      { h: `Honesty in reporting`,
        body: [
          `Status reports are a promise that what you're showing is true. A report that's technically accurate but leaves out the one thing the reader needs is still dishonest. If you discover a report you sent was wrong, issue a correction, explain what was wrong, and say what you're changing so it doesn't happen again. Owning the mistake protects more trust than any explanation will.`,
          `Teams sometimes call the opposite a watermelon report: green on the outside, red on the inside. This also applies to forecasts. A PM who knows a date is unrealistic and reports it as on track isn't being optimistic. They're taking a decision away from the people entitled to make it.`
        ],
        terms: [[`Watermelon reporting`,`Green outside, red inside. Status that looks fine and isn't.`]],
        exam: `If you find an error in something you already reported, the answer is to correct it with the affected stakeholders, not to quietly fix it in the next report.` },
      { h: `Integrity under pressure`,
        body: [
          `Ethical problems on projects rarely look dramatic. They look like a sponsor who wants the dashboard to stay green one more week, a customer who'd rather not hear the date moved, or a colleague who asks you to leave one line out of a report. The pressure is real, and the person applying it often believes they're protecting the project.`,
          `It helps to have plain language ready. "I can't report that as green, but I can show the recovery plan next to it." "I'm required to take this to the sponsor today. Do you want to come with me?" "I don't know yet, and I'll tell you by Thursday." Sentences like these let you hold the line without turning the conversation into an accusation.`,
          `Speaking up also depends on the environment you build. If people get punished for raising bad news, they stop raising it, and you find out late. Thank people who bring problems forward, protect them from retaliation, and make it normal to say "something looks wrong" early. That culture is the real control.`
        ],
        terms: [[`Psychological safety`,`A shared belief that it's safe to speak up, admit mistakes, and raise concerns.`],[`Retaliation`,`Punishing someone for raising a concern in good faith. Prohibited and corrosive.`]],
        exam: `If someone raises an ethical concern to you, the right answer protects them and acts through proper channels. Ignoring it or exposing them is always wrong.` },
      { h: `Issues, escalation, and governance`,
        body: [
          `A risk is something that might happen. An issue is something that has happened and needs action. Issues go in an issue log with an owner, a description, priority, actions, and a target date. When an issue is beyond your authority, escalate it through the escalation path in your governance framework. Escalation isn't failure. It's how organizations make sure the right people decide.`,
          `Governance defines who decides what. A good framework names the sponsor, steering groups, decision rights, thresholds that trigger escalation, and how the board is informed. When someone asks you to keep something from the people governance says should know, that's a request to break the framework, and the answer is no.`
        ],
        terms: [[`Issue log`,`Record of current problems with owners, actions, and due dates.`],[`Escalation path`,`The agreed route for raising matters beyond your authority.`]],
        exam: `Known problems belong in the issue log, not the risk register. Escalate through the defined path, starting with the sponsor.` },
      { h: `Supporting organizational change`,
        body: [
          `Projects often change how people work, and sometimes the change a project reveals is in the organization itself. People don't resist change so much as they resist losing something: status, control, comfort, income. Models help. ADKAR describes what each person needs: Awareness of why, Desire to take part, Knowledge of how, Ability to do it, and Reinforcement so it sticks. Kotter's steps start with a sense of urgency and a guiding coalition and end with anchoring the change in the culture.`,
          `In practice: explain the reason honestly, involve the people affected in designing the change, find champions inside the group, pilot before you roll out, train, and reinforce the new behavior when it shows up. Mandating a change from above with no involvement usually produces quiet workarounds.`
        ],
        terms: [[`ADKAR`,`Awareness, Desire, Knowledge, Ability, Reinforcement.`],[`Change champion`,`Someone inside the affected group who models and supports the change.`]],
        exam: `For resistance to change, choose the answer that addresses the cause by involving people and explaining why, not the one that forces compliance.` }
    ],
    video: [`500tmpXOsDw`,`PMI Code of Ethics and Professional Responsibility`,`EduHubSpot`,`10:32`]
  },
  scenes: [
    { id:`f14s1`, domain:`People`, task:`P6`, title:`Grant's confession`,
      text:(s,all,G)=>[`Grant has just finished. He's waiting to see what Sam does with it.`,`It's 7:40 on a Thursday night. Park's board meets in five weeks.`],
      opts:[
        {t:`Thank Grant, then gather every fact before deciding what happens next.`, s:3, best:true, d:{trust:4,conf:1,health:2}, after:`Sam asks for the pitch deck, the contract language, and the edited report. By ten that night he knows exactly what was promised, in writing and out loud.`, why:`Acknowledge the person who raised it, then assess before you act. You need the facts to respond honestly and in proportion.`},
        {t:`Call Park tonight and tell her everything Grant just said, before anything else.`, s:1, d:{trust:-2,conf:1,health:0}, after:`Park is surprised to hear from Sam at night. He can't answer half her questions because he hasn't seen the documents.`, why:`Disclosure is coming and that instinct is right. But disclosing before you know the facts leads to a second correction later. Assess first, and quickly.`},
        {t:`Tell Grant to fix it himself with Park, since the promise came from his team.`, s:0, d:{trust:-2,conf:-2,health:-1}, after:`Grant tries. Park asks about delivery dates he can't answer, and the status report Sam signed.`, why:`Sam's name is on the report and Sam owns delivery. Handing the whole thing back avoids responsibility you share.`},
        {t:`Ask Grant to keep this between them until Sam can think about it over the weekend.`, s:0, d:{trust:0,conf:-3,health:0}, after:`Two days of silence feels like a plan. It isn't one, and it makes Sam part of keeping it hidden.`, why:`Asking for secrecy, even briefly, starts down the path of concealment. Keep the circle tight while you get facts, but don't agree to hide it.`}
      ]},
    { id:`f14s2`, domain:`Business Environment`, task:`B4`, title:`Risk or issue`,
      text:(s,all,G)=>[`Friday morning. Priya asks where to put it. The risk register already has a line about Northgate scope expectations, rated medium.`,`The feature doesn't exist, it was promised in a signed deal, and the customer's board is going to ask about it.`],
      opts:[
        {t:`Log it as an issue with an owner, actions, and a date; close the risk.`, s:3, best:true, d:{trust:1,conf:1,health:4}, after:`The issue log gets its first critical entry in months. Owner: Sam. First action: sponsor briefing today.`, why:`The risk materialized. It's an issue now, with known impact, and it needs owned actions with dates. Update the risk register to reflect that it occurred.`},
        {t:`Raise the risk's rating to critical and add a mitigation plan to the register.`, s:1, d:{trust:0,conf:0,health:1}, after:`The register looks alarming. Nobody is clearly on the hook for doing anything by a date.`, why:`It isn't a risk anymore. Something that has already happened belongs in the issue log with actions, not in the register as a possibility.`},
        {t:`Keep it off every log until legal reviews it, so nothing is written down yet.`, s:0, d:{trust:-2,conf:-2,health:-1}, after:`Legal asks why there's no record of when Halcyon knew.`, why:`Avoiding documentation to avoid accountability is an honesty problem. Record it accurately; involve legal as well.`},
        {t:`Add a change request to build the medication feature to the Northgate backlog.`, s:0, d:{trust:0,conf:0,health:-3}, after:`The change request treats the problem as missing scope, not a broken promise. It doesn't address what Park was told.`, why:`Building the feature may be part of the answer later, but first the issue itself needs owning, escalating, and disclosing.`}
      ]},
    { id:`f14s3`, domain:`People`, task:`P4`, title:`The report with his name on it`,
      text:(s,all,G)=>[`Sam rereads the September report. The scope section was changed after his team wrote it.`,`<prop type="doc" title="Northgate status report, September">Overall: Green.<br>Scope: Green. Medication reconciliation on track for release two.<br>Schedule: Green. Go-live date unchanged.</prop>`,`His cover email is still in his sent folder.`,`<prop type="email" from="Sam Okafor" to="Dr. Helen Park" time="4:52 PM" subject="September status">Dr. Park, attached is the reviewed September status report for Northgate. Happy to walk through it on Thursday.<br>Sam</prop>`,`It wasn't reviewed. Not by him.`],
      opts:[
        {t:`Send Park a corrected report, say plainly what was wrong, and own his part of it.`, s:3, best:true, d:{trust:3,conf:5,health:2}, after:`The correction is short and plain. It says what changed, that Sam should have caught it, and what's different now: reports are locked after his review. Park replies with one word. <span class="said" data-who="Helen">"Noted."</span> Then, a day later, <span class="said" data-who="Helen">"Thank you."</span>`, why:`Honesty and responsibility mean correcting information you put out, including your own mistakes. A clear correction protects more trust than silence ever does.`},
        {t:`Fix the scope section in the October report so the record is right going forward.`, s:0, d:{trust:0,conf:-5,health:0}, after:`October is accurate. September is still wrong in Park's files, and now there's a silent change between them.`, why:`Quietly fixing it next time leaves a false impression standing. The Code calls for correcting it with the people who received it.`},
        {t:`Send the corrected report but leave out that anyone edited it after his review.`, s:1, d:{trust:0,conf:2,health:0}, after:`Park has the right facts. When the full story comes out at her board, she wonders what else was left out.`, why:`Correcting the facts is good. Leaving out how it happened, when it matters, is a half truth. Be complete.`},
        {t:`Ask Grant's team member who edited it to send the correction to Park.`, s:0, d:{trust:-3,conf:-1,health:0}, after:`Park gets a correction from someone she's never heard of, about a report signed by Sam.`, why:`The report went out under Sam's name. Owning the correction is his responsibility, not something to delegate away.`}
      ]},
    { id:`f14s4`, domain:`Business Environment`, task:`B1`, title:`Who needs to know`,
      text:(s,all,G)=>[`Halcyon's governance framework says commitments that change contract scope or revenue go to the sponsor within one business day and to the board's audit committee if they touch revenue reporting.`,`The Northgate deal was booked at a value that assumed the medication feature.`],
      opts:[
        {t:`Brief Elena today, then follow the framework's path to the audit committee.`, s:3, best:true, d:{trust:1,conf:4,health:3}, after:`Elena is quiet for a long time. Then she says, <span class="said" data-who="Elena">"Thank you for not waiting."</span> She calls the audit committee chair herself that afternoon.`, why:`Use the escalation path governance defines, starting with the sponsor and on the timeline it sets. That's exactly what the framework is for.`},
        {t:`Go straight to the audit committee chair, since revenue reporting may be involved.`, s:1, d:{trust:0,conf:1,health:1}, after:`The chair asks whether the CEO knows. She doesn't yet. Elena hears about it from the board instead of from Sam.`, why:`The concern is valid, but skipping the sponsor breaks the path and the relationship. Brief the sponsor first, then follow the path promptly.`},
        {t:`Brief only Lena, since it's a delivery problem and she runs engineering.`, s:0, d:{trust:0,conf:-2,health:0}, after:`Lena is sympathetic and has no authority over sales commitments or revenue.`, why:`Telling someone who can't decide doesn't escalate anything. Go to the people governance names.`},
        {t:`Wait until the monthly steering meeting so it can be discussed with full context.`, s:0, d:{trust:0,conf:-4,health:-1}, after:`The steering meeting is three weeks away. The framework says one business day.`, why:`Governance thresholds exist so serious issues don't wait for a calendar slot. Follow the timeline the framework sets.`}
      ]},
    { id:`f14s5`, domain:`Business Environment`, task:`B1`, title:`Victor's suggestion`,
      text:(s,all,G)=>[(G.cutcorners?`Sam remembers agreeing to Victor's cuts in month seven without running the numbers first. He's not going to make that mistake twice. `:``)+`Victor calls Sam directly. He's heard. He suggests keeping it out of the board packet until next quarter, when there might be a fix to announce alongside the problem.`,`<span class="said" data-who="Victor">"Problems with solutions attached are easier for a board to hear,"</span> he says.`],
      opts:[
        {t:`Decline, explain the framework requires it now, and offer a recovery plan too.`, s:3, best:true, d:{trust:1,conf:5,health:2}, after:`Victor pushes once more, then stops. <span class="said" data-who="Victor">"Fine. Bring the plan."</span> Sam does.`, why:`Delaying required disclosure isn't a judgment call you get to make. Hold the line on governance and honesty, and offer what you can: a plan alongside the truth.`},
        {t:`Agree to wait a quarter, since Victor sits on the board and knows how it works.`, s:0, d:{trust:0,conf:-8,health:0}, after:`Park's board finds out first, from Park. Halcyon's board finds out from Northgate's lawyer.`, why:`A board member asking you to delay disclosure doesn't make it right. The Code and the framework both require reporting through proper channels.`},
        {t:`Tell Victor he's asking for something unethical and that Sam will report the call.`, s:1, d:{trust:-1,conf:1,health:0}, after:`Victor goes cold. The disclosure happens, but now there's a new fight layered on top of it.`, why:`Holding the line is right, but leading with accusation adds conflict without adding value. Decline firmly and respectfully, and offer a constructive path.`},
        {t:`Say nothing to Victor and let Elena handle the board as she sees fit.`, s:1, d:{trust:0,conf:0,health:0}, after:`Elena does handle it. Victor assumes Sam agreed with him, which comes up again later.`, why:`Elena owns the board relationship, so deferring has some logic. But leaving Victor's request unanswered can read as agreement. Answer it clearly.`}
      ]},
    { id:`f14s6`, domain:`People`, task:`P6`, title:`Telling Park`,
      text:(s,all,G)=>[`Sam and Grant fly to Omaha to see Dr. Helen Park in person. She's already read the corrected report.`,`<span class="said" data-who="Helen">"Tell me what you can actually deliver,"</span> she says, <span class="said" data-who="Helen">"and when. Then tell me why I should believe the date."</span>`],
      opts:[
        {t:`Own the gap, give an honest estimate with its range, and offer options.`, s:3, best:true, d:{trust:2,conf:6,health:3}, after:`Sam lays out three options: a manual reconciliation workflow at go-live, the real feature in two quarters, and a contract credit for the gap. Park picks the first two and asks for the credit in writing. She also asks that Grant stay on the account.`, why:`Manage expectations with honest information and real choices. The customer decides with facts; your job is to make the facts trustworthy.`},
        {t:`Promise the feature next quarter so Park has something firm to tell her board.`, s:0, d:{trust:-2,conf:-3,health:-6}, after:`Park writes the date down. Sam's own leveled schedule says it's impossible.`, why:`A second unrealistic promise to fix the first one repeats the original mistake. Give the honest estimate even when it's harder to hear.`},
        {t:`Let Grant lead the meeting, since the commitment was his and he owns the account.`, s:1, d:{trust:1,conf:0,health:0}, after:`Grant apologizes well. When Park asks about delivery dates, he turns to Sam anyway.`, why:`Grant should be there and should own his part. But delivery facts are Sam's to give. Shared accountability, clear roles.`},
        {t:`Focus the meeting on what Northgate is getting, rather than on the missing feature.`, s:0, d:{trust:0,conf:-5,health:0}, after:`Park lets Sam finish the slide, then asks again about the medication feature.`, why:`Redirecting attention from the problem is spin. The stakeholder asked a direct question; answer it directly.`}
      ]},
    { id:`f14s7`, domain:`People`, task:`P4`, title:`Grant's job`,
      text:(s,all,G)=>[`Back in Denver, Elena asks Sam for his view on Grant. Some board members want him gone. Grant made the promise. Grant also came forward on his own when he could have stayed quiet.`,`Sam has no authority over Grant's job. Elena is asking because she wants an honest read.`],
      opts:[
        {t:`Give Elena the facts on both sides, including that Grant came forward himself.`, s:3, best:true, d:{trust:3,conf:2,health:1}, after:`Elena decides Grant stays, with a new rule: no sales commitment on delivery without the delivery office's sign-off. Grant agrees before she finishes the sentence.`, why:`Fairness means giving decision makers complete, impartial information, including what reflects well on someone, without deciding for them.`},
        {t:`Tell Elena that Grant should go, since the original promise caused all of this.`, s:0, d:{trust:-3,conf:0,health:0}, after:`Elena takes note. Word gets around that the person who came forward got pushed out, and the next problem stays hidden longer.`, why:`Punishing the person who raised a problem teaches everyone else to hide theirs. Fairness also means weighing the whole picture.`},
        {t:`Decline to give a view, since it isn't Sam's place to judge a peer's job.`, s:1, d:{trust:0,conf:-1,health:0}, after:`Elena decides without Sam's view, and with less information than she could have had.`, why:`You don't decide, but withholding relevant facts when the decision maker asks isn't neutral. Share the facts fairly.`},
        {t:`Defend Grant strongly so the team sees Sam stands by people who make mistakes.`, s:1, d:{trust:2,conf:-1,health:0}, after:`Elena wonders whether Sam is being objective, and asks Lena for a second opinion.`, why:`Loyalty is a good instinct, but advocacy isn't the same as fairness. Give the complete picture and let the decision rest with the person accountable.`}
      ]},
    { id:`f14s8`, domain:`Business Environment`, task:`B4`, title:`The demo next week`,
      text:(s,all,G)=>[`Alyssa Kemp, a sales engineer, asks to talk to Sam privately. Her manager told her to run the conference medication reconciliation demo for a new prospect next Tuesday and describe it as live.`,`<span class="said" data-who="Alyssa">"I don't want to do it,"</span> she says. <span class="said" data-who="Alyssa">"I also don't want to lose my job."</span>`],
      opts:[
        {t:`Thank her, stop the demo through the sponsor today, and protect her.`, s:3, best:true, d:{trust:5,conf:2,health:2}, after:`Elena kills the demo that afternoon and tells the sales team in writing that mockups are always labeled as concepts. Alyssa's manager is told plainly that retaliation is a firing offense.`, why:`An instruction to mislead a prospect is an impediment and an ethics violation. Remove it quickly through people with authority, and protect the person who raised it.`},
        {t:`Advise Alyssa to run the demo but call it a concept if anyone asks directly.`, s:0, d:{trust:-4,conf:-2,health:0}, after:`Nobody asks directly. The prospect leaves believing the feature exists.`, why:`A false impression is still dishonest even if you'd tell the truth when asked. Honesty includes not misleading by omission.`},
        {t:`Talk to Alyssa's manager directly and ask him to change the instruction.`, s:1, d:{trust:0,conf:0,health:1}, after:`The manager agrees, then asks who complained. Alyssa feels exposed.`, why:`Talking to the person first is often right, but here the person raising it fears retaliation. Protect her by going through someone with authority.`},
        {t:`Tell Alyssa to document it and raise it with HR if she still feels uncomfortable.`, s:1, d:{trust:-1,conf:0,health:0}, after:`HR opens a ticket. The demo is still on the calendar for Tuesday.`, why:`Documenting is useful and HR may need to be involved, but the demo is days away. Act to stop the harm, don't just route it.`}
      ]},
    { id:`f14s9`, domain:`Business Environment`, task:`B7`, title:`The deal desk`,
      text:(s,all,G)=>[`Elena asks Sam to design a fix so sales commitments never outrun delivery again. Sam sketches a deal desk: any commitment about features or dates in a deal gets delivery sign-off before signature.`,`On paper it's simple. In practice, it changes how forty salespeople do their jobs.`],
      opts:[
        {t:`Design it with sales leaders, pilot it on a handful of deals, then adjust as needed.`, s:3, best:true, d:{trust:4,conf:2,health:3}, after:`Two account executives help design the intake form. They make it shorter than Sam would have. The pilot catches one overpromise in its first week, and the reps tell the story themselves.`, why:`Organizational change sticks when the people affected help design it. Champions, a pilot, and adjustment reduce resistance and improve the change itself.`},
        {t:`Have Elena announce the deal desk as mandatory starting Monday for every deal.`, s:1, d:{trust:-2,conf:1,health:1}, after:`Compliance is high. Within a month, reps start describing commitments in vaguer language to avoid triggering a review.`, why:`Sponsor backing is essential, but mandating change without involvement often produces workarounds. Pair authority with participation.`},
        {t:`Build a detailed policy document and send it to the sales team to read and sign.`, s:0, d:{trust:-1,conf:0,health:0}, after:`Thirty one people sign it. Four read it.`, why:`A document isn't a change. People need to understand why, help shape how, and get support doing it.`},
        {t:`Have Sam personally review every deal before signature until things settle down.`, s:0, d:{trust:0,conf:0,health:-3}, after:`Sam becomes the bottleneck for revenue. Grant jokes that he should get a commission.`, why:`Centralizing it in yourself doesn't build a lasting process and doesn't scale. Design a system the organization owns.`}
      ]},
    { id:`f14s10`, domain:`Business Environment`, task:`B7`, title:`The pushback`,
      text:(s,all,G)=>[`At the sales kickoff, a senior rep stands up. <span class="said" data-who="man">"So now delivery decides what we can sell? That's going to cost us deals."</span>`,`Half the room nods.`],
      opts:[
        {t:`Acknowledge the worry, share why it started, and ask the reps how to keep it fast.`, s:3, best:true, d:{trust:4,conf:2,health:2}, after:`Sam tells the Northgate story without naming names. The room gets quiet. Then the same rep suggests a forty eight hour review promise, and Elena adopts it on the spot.`, why:`Resistance usually comes from a real concern. Address awareness and desire: explain why honestly, and involve people in solving the part they're worried about.`},
        {t:`Remind the room that Elena approved it and that the decision is final.`, s:0, d:{trust:-4,conf:0,health:0}, after:`The room stops nodding and starts texting.`, why:`Pointing to authority ends the discussion, not the resistance. People comply on paper and work around it in practice.`},
        {t:`Offer to exempt deals under a certain size so the change affects fewer reps.`, s:1, d:{trust:1,conf:0,health:-1}, after:`It calms the room. It also exempts the exact kind of deal where Northgate's promise was made.`, why:`Tailoring a change can be smart, but don't trade away the purpose of the change to reduce discomfort. Solve the concern without gutting the control.`},
        {t:`Take the question offline and follow up with the rep after the kickoff.`, s:1, d:{trust:0,conf:0,health:0}, after:`The rep feels brushed off. The room decides the answer is that there isn't one.`, why:`Following up one on one has a place, but a public concern shared by half the room deserves a public, honest answer.`}
      ]},
    { id:`f14s11`, domain:`People`, task:`P4`, title:`Ruth's story`,
      text:(s,all,G)=>[(G.hidnumbers?`Sam tells Ruth about the month he softened the earned value numbers for the board, back during Cascade. He's never said it out loud before. `:``)+`The night before the board meeting, Sam meets Ruth at the coffee shop in Golden. He asks how to present it.`,`Ruth doesn't answer right away. Then she tells him the whole story she's been telling in pieces for a year.`,`In 1991, as a young engineer, she saw a sensor reading on an uncrewed vehicle that didn't look right. Small. Probably nothing. Raising it would have meant a hold, a slipped launch, and being the new person who cried wolf. She told herself she'd watch it. The vehicle was lost eleven minutes after launch. The review board found the anomaly in the telemetry she had watched. <span class="said" data-who="Ruth">"Nobody blamed me,"</span> Ruth says. <span class="said" data-who="Ruth">"Nobody knew. That was the worst part. I knew."</span>`],
      opts:[
        {t:`Lead with exactly what happened, his own part in it, the impact, and the recovery plan.`, s:3, best:true, d:{trust:2,conf:6,health:2}, after:`Ruth nods once. <span class="said" data-who="Ruth">"Say the bad part first,"</span> she says. <span class="said" data-who="Ruth">"Then don't apologize for it again. Then show them what you're doing."</span>`, why:`Responsibility and honesty with governance: complete facts, ownership of your part, clear impact, and a credible plan. No softening, no blame shifting.`},
        {t:`Lead with the recovery plan so the board sees the solution before the problem.`, s:1, d:{trust:0,conf:1,health:1}, after:`Ruth shakes her head. <span class="said" data-who="Ruth">"They'll spend the whole plan wondering what you're not telling them."</span>`, why:`A plan matters, but leading with it can look like you're managing the reaction. State the problem plainly first, then the plan.`},
        {t:`Frame it as Grant's sales issue, since delivery didn't make the original promise.`, s:0, d:{trust:-3,conf:-3,health:0}, after:`Ruth puts her cup down. <span class="said" data-who="Ruth">"Whose name was on the September report?"</span>`, why:`Shifting blame when you share responsibility violates respect and honesty, and the board will see it.`},
        {t:`Present it as a minor scope clarification already resolved with the customer.`, s:0, d:{trust:0,conf:-8,health:0}, after:`Ruth looks at him the way she must have looked at that telemetry. Sam drops the idea before she says a word.`, why:`Minimizing a material issue to a governing body is exactly the silence Ruth is warning against. Be honest about scale.`}
      ]},
    { id:`f14s12`, domain:`Business Environment`, task:`B1`, title:`The board`,
      text:(s,all,G)=>[`The board meets in the big room on the fourth floor. Sam presents for twenty minutes. When he finishes, Victor Adeyemi is the first to speak.`,...(G.nobusinesscase?[`Victor's small notebook is open in front of him. Sam can guess what's on the page: discharge instructions, months in, still no business case. One more thing Halcyon decided on a feeling.`]:[]),`<span class="said" data-who="Victor">"Is it as bad as it sounds?"</span> he asks.`],
      opts:[
        {t:`Say yes, restate the impact in plain numbers, and walk through the new controls.`, s:3, best:true, d:{trust:2,conf:7,health:3}, after:`The room is quiet. Then Victor says, <span class="said" data-who="Victor">"Good. I'd rather fund someone who tells me that."</span> The board approves the recovery plan, the contract credit, and the deal desk.`, why:`When governance asks a direct question, give a direct answer. Honest reporting to the board is what lets it govern.`},
        {t:`Say it's serious but manageable, and that the team has it under control now.`, s:1, d:{trust:0,conf:1,health:0}, after:`Victor asks how serious. Sam ends up giving the numbers anyway, and the hedge cost him a little credibility.`, why:`"Under control" can be a softening phrase. Lead with the plain answer and the numbers; let the plan show the control.`},
        {t:`Say it could have been worse and point out that the customer is still with Halcyon.`, s:0, d:{trust:0,conf:-4,health:0}, after:`Victor writes something down. Sam suspects it isn't a compliment.`, why:`Comparing to a worse outcome deflects the question. The board asked about this outcome.`},
        {t:`Defer the question to Elena, since the board relationship belongs to the CEO.`, s:0, d:{trust:0,conf:-3,health:0}, after:`Elena answers, and then looks at Sam as if to ask why he didn't.`, why:`The question was about facts Sam owns. Answer within your responsibility; don't pass it up the chain.`}
      ]}
  ],
  drills: [],
  exercise: { after:`f14s8`, title:`Which value is at stake`, intro:`Match each situation to the PMI Code of Ethics value it tests most directly.`,
    items:[
      {prompt:`Priya finds a mistake in last week's Cascade report, which went out under her name. She sends Ochoa a fix the same day.`, choices:[`Responsibility`,`Respect`,`Fairness`,`Honesty`], answer:0, why:`She's owning her own error and fixing it fast. Honesty is in there too, but the main act is taking ownership.`},
      {prompt:`Joan's brother in law runs one of the firms bidding on the new labeling contract. She tells Sam and sits out the scoring.`, choices:[`Responsibility`,`Respect`,`Fairness`,`Honesty`], answer:2, why:`Disclosing a conflict of interest and stepping back from the decision is fairness.`},
      {prompt:`Lena could call the Northgate API work "on track." It's two weeks behind, so she marks it red.`, choices:[`Responsibility`,`Respect`,`Fairness`,`Honesty`], answer:3, why:`She's refusing to create a false impression. That's honesty.`},
      {prompt:`In a loud design review, Sam stops the room so Devin can finish a point he started twice.`, choices:[`Responsibility`,`Respect`,`Fairness`,`Honesty`], answer:1, why:`Making room for someone's view, and keeping the meeting civil, is respect.`},
      {prompt:`Two vendors ask Joan the same question about the bid. She answers both by email, at the same hour.`, choices:[`Responsibility`,`Respect`,`Fairness`,`Honesty`], answer:2, why:`Giving everyone the same information at the same time is fairness.`},
      {prompt:`Elena asks Priya to run a security audit. Priya says she isn't qualified and names Ken's engineer instead.`, choices:[`Responsibility`,`Respect`,`Fairness`,`Honesty`], answer:0, why:`Only taking work you're qualified for is a responsibility standard.`}
    ]},
  quiz: [
    {q:`A project manager learns that last month's status report, sent under her name, overstated progress. What should she do?`, opts:[`Correct it in next month's report`,`Send a correction to recipients now`,`Ask the author of the error to fix it`,`Wait to see if anyone noticed it`], a:1, why:`Responsibility and honesty require correcting information you put out, promptly, with the people who received it.`, task:`P4`, domain:`People`},
    {q:`Which are the four values of the PMI Code of Ethics and Professional Conduct?`, opts:[`Integrity, respect, fairness, quality`,`Responsibility, respect, fairness, honesty`,`Honesty, loyalty, competence, and fairness`,`Respect, transparency, value, honesty`], a:1, why:`The Code rests on responsibility, respect, fairness, and honesty.`, task:`P4`, domain:`People`},
    {q:`A board member asks the project manager to leave a serious problem out of the board packet until a fix is ready. What should the project manager do?`, opts:[`Agree, since board members set what boards see`,`Report the board member to PMI right away`,`Decline and follow the required disclosure path`,`Let the CEO decide without saying anything`], a:2, why:`Delaying required disclosure isn't acceptable. Follow governance and honesty, and offer a plan alongside the facts.`, task:`B1`, domain:`Business Environment`},
    {q:`A medium-rated scope risk about a customer's expectations has turned out to be real: a promised feature was never built, and the customer's board meets in five weeks. Where does this belong now?`, opts:[`On the risk register, rerated as critical`,`In the backlog, as a new feature to build`,`In a legal hold file, until counsel reviews`,`In the issue log, with an owner and dates`], a:3, why:`Once a risk occurs it is an issue: known impact, owned actions, target dates, and escalation if it's beyond your authority. Rerating it keeps treating a fact as a possibility, and building the feature or waiting on legal skips owning and disclosing the problem.`, task:`B4`, domain:`Business Environment`},
    {q:`A team member reports that her manager told her to present a mockup to a prospect as a working product. What should the project manager do first?`, opts:[`Advise her to call it a concept if asked`,`Act through the sponsor to stop the demo`,`Tell her to document it and contact HR`,`Ask her manager who raised the concern`], a:1, why:`Stop the misleading act quickly through someone with authority, and protect the person who raised it.`, task:`B4`, domain:`Business Environment`},
    {q:`Which describes an aspirational standard in the PMI Code of Ethics?`, opts:[`Conduct we strive to uphold as practitioners`,`A rule whose violation brings PMI discipline`,`A legal requirement set by government agencies`,`A contract term between buyer and seller`], a:0, why:`Aspirational standards describe the conduct practitioners strive for. Mandatory standards set firm requirements.`, task:`P4`, domain:`People`},
    {q:`A project manager's close friend owns a firm bidding on the project. What is the best action?`, opts:[`Score the bid fairly and say nothing`,`Disqualify the friend's firm right away`,`Disclose it and step out of the evaluation`,`Ask the friend to withdraw the bid quietly`], a:2, why:`Disclose conflicts of interest and remove yourself from the decision. That's fairness.`, task:`P4`, domain:`People`},
    {q:`Sales staff resist a new review step for deal commitments. Using ADKAR, what should the change leader address first?`, opts:[`Ability, through hands-on training sessions`,`Reinforcement, through bonuses for using it`,`Knowledge, through a detailed policy manual`,`Awareness and desire, by explaining why`], a:3, why:`ADKAR starts with awareness of why the change matters and desire to take part. Training comes after people buy in.`, task:`B7`, domain:`Business Environment`},
    {q:`An organizational change is mandated by the CEO with no input from affected staff. What is the most likely result?`, opts:[`Fast, lasting adoption across the teams`,`Quiet workarounds and shallow compliance`,`Higher morale from the clear direction given`,`Lower costs from skipping the design work`], a:1, why:`Changes imposed without involvement often produce surface compliance and workarounds.`, task:`B7`, domain:`Business Environment`},
    {q:`A customer asks a direct question about a missing feature. The project manager should:`, opts:[`answer directly with honest facts and options`,`redirect to the features that are on schedule`,`ask the sales lead to answer for the company`,`promise a firm date to restore confidence`], a:0, why:`Managing expectations means honest, direct answers and real options, not redirection or new promises.`, task:`P6`, domain:`People`},
    {q:`A governance framework says scope-changing commitments go to the sponsor within one business day. The PM discovers one on Thursday. What should the PM do?`, opts:[`Raise it at next month's steering meeting`,`Go straight to the board's audit chair`,`Brief the sponsor by Friday as required`,`Tell the CTO, who owns engineering work`], a:2, why:`Follow the escalation path and timeline governance defines, starting with the sponsor.`, task:`B1`, domain:`Business Environment`},
    {q:`A report is technically accurate but leaves out the one fact the reader most needs. This is best described as:`, opts:[`acceptable, because nothing in it is false`,`a fairness issue about equal access to data`,`a respect issue about the reader's feelings`,`an honesty issue, creating a false impression`], a:3, why:`Honesty includes not creating false impressions through omission or selective facts.`, task:`P4`, domain:`People`},
    {q:`During a sponsor's decision about a colleague who made a mistake and then reported it, the PM is asked for input. What should the PM provide?`, opts:[`Complete, impartial facts on both sides`,`A strong recommendation to remove them`,`No input, since it isn't the PM's call`,`A strong defense out of team loyalty`], a:0, why:`Fairness means giving decision makers complete, impartial information without deciding for them.`, task:`P6`, domain:`People`},
    {q:`A senior employee publicly objects to a new process at a kickoff, and many agree. What is the best response?`, opts:[`Note that the CEO approved it and move on`,`Exempt their group so the room calms down`,`Address it openly and ask for their solutions`,`Take it offline and follow up with him later`], a:2, why:`A shared, public concern deserves an honest public answer, and involving people in solving it reduces resistance.`, task:`B7`, domain:`Business Environment`},
    {q:`What is the main purpose of an escalation path in project governance?`, opts:[`To route issues beyond the PM's authority to the people who decide`,`To let team members bypass the project manager when they disagree`,`To record every change request before the change control board meets`,`To protect the project manager from blame for decisions made later on`], a:0, why:`Escalation paths make sure matters beyond the PM's authority reach the people with decision rights.`, task:`B1`, domain:`Business Environment`}
  ],
  closing:(s,all,G)=>[
    `After the board meeting, Victor stops Sam in the hallway. <span class="said" data-who="Victor">"For the record,"</span> he says, <span class="said" data-who="Victor">"I asked you to wait because I wanted to see if you would. Most people do."</span> Sam isn't sure whether to believe him. He decides it doesn't matter.`,
    `Park's board takes the news better than anyone expected. Their press office issues a short update about a phased release. Park sends Sam a photo of her nurses training on the manual reconciliation workflow, with a note: <span class="said" data-who="Helen">"Not what we were promised. What we can trust."</span>`,
    `Grant buys the whole delivery office lunch, which he insists isn't an apology, and then apologizes to Alyssa in front of everyone, which is.`,
    `That night Sam tells Dana about Ruth's story. Dana listens all the way through, which she almost never does without interrupting.`,
    `<span class="said" data-who="Dana">"Thirty five years,"</span> she says. <span class="said" data-who="Dana">"She's been carrying that for thirty five years, and she spent the last one making sure you wouldn't have to carry one."</span>`,
    `The next morning there's an email from Ruth, sent at 5:50 AM. Subject line: <span class="said" data-who="Ruth">"One more launch."</span> It says she's stepping off the board after Northgate goes live, and she'd like to be in the room when it does.`
  ],
  episode:{src:`audio/full-ch14.mp3`, len:`about 35 minutes`},
  next:`Liftoff`
});
