(window.HALCYON_FULL=window.HALCYON_FULL||[]).push({
  num: 15, part: "Part Two: The PMO", title: "Liftoff", weeks: "Month 10 and after",
  tasks: ["P7","P3","R10","B6","P1"],
  cast: [["MSgt (ret.) Ray Mendez","Sam's old flight chief. Retired in Tucson. Still answers on the second ring."]],
  opening: [
    `Priya's project had a name before it had a charter, which Sam took as a good sign. She called it Pharmacy Connect. It was the medication reconciliation feature Grant had promised Northgate a year ago, the one that didn't exist. Now it had a business case, a sponsor, a budget, and a project manager who had never been a project manager before. Cascade, which had been asking for the same thing more quietly, would get it first. Northgate would follow once it was proven.`,
    `<span class="said" data-who="Priya">"Why me?"</span> she'd asked when Elena signed the charter.`,
    `<span class="said" data-who="Sam">"Because you know what it costs when a promise gets ahead of the work,"</span> Sam had said. <span class="said" data-who="Sam">"And because you'll ask for help before it's too late. Most people don't."</span>`,
    `Northgate's go-live was set for the second Tuesday of the month. Ruth had asked to be in the room. Theo's contract ended the Friday after. Victor had started copying Sam on emails he used to send only to Elena, which Dana said was either a promotion or a warning, and probably both.`,
    `On Sunday night Sam called Ray Mendez in Tucson, something he did about twice a year. Ray answered on the second ring, the way he always had.`,
    `<span class="said" data-who="Ray">"You sound tired, Okafor."</span>`,
    `<span class="said" data-who="Sam">"I'm about to hand the most important project we have to someone who's never run one,"</span> Sam said. <span class="said" data-who="Sam">"And I'm supposed to stay out of her way."</span>`,
    `Ray laughed, a long smoker's laugh he'd kept after quitting twenty years ago. <span class="said" data-who="Ray">"You remember your first jet? I stood behind you for three months with my hands in my pockets. Hardest thing I ever did on that flight line. You turned out fine. Mostly."</span>`
  ],
  lesson: {
    title: `Closing well, and leaving something behind`,
    sections: [
      { h: `What closing a project actually involves`,
        body: [
          `Closing confirms that the work is done and accepted, and then deliberately ends the project. The main steps: get formal acceptance of deliverables from the customer or sponsor against agreed acceptance criteria; transition the product to the people who'll operate and support it; close out contracts and procurements; finalize and archive records; capture lessons learned; release resources; and report final performance. A phase can be closed the same way at the end of each phase. It helps to know where closing sits among the five process groups. Initiating authorizes the work. Planning decides how it will be done, including how people will be released at the end. Executing builds the deliverables. Monitoring and controlling compares progress to the baseline and forecasts. Closing confirms acceptance, closes contracts, archives records, and reports final results. Planning how to release people happens early; actually releasing them happens at the end.`,
          `Formal acceptance matters. "They seem happy" isn't acceptance. A signed acceptance against the criteria in the scope baseline protects both sides and starts warranty and support clocks. If a project is terminated early, you still close it: document why, what was delivered, and what was learned.`
        ],
        terms: [[`Formal acceptance`,`Documented sign-off that deliverables meet acceptance criteria.`],[`Transition`,`Handing the product to operations or support with the knowledge they need.`],[`Final report`,`Summary of performance against scope, schedule, cost, quality, and benefits.`]],
        exam: `If a deliverable is finished but the customer hasn't formally accepted it, the project isn't closed. The next step is obtaining formal acceptance.` },
      { h: `Closing contracts`,
        body: [
          `Procurement closure confirms the seller delivered everything required, resolves any open claims, makes final payment, and records the seller's performance for future selection. Claims are best settled by negotiation; alternative dispute resolution comes next; litigation is a last resort. Keep the procurement file complete, because audits often look at it later.`
        ],
        terms: [[`Claim`,`A request by buyer or seller for compensation or adjustment under the contract.`],[`Procurement audit`,`A review of the procurement process to find lessons for future contracts.`]],
        exam: `Before final payment, verify all deliverables were received and accepted. Unresolved claims block closure.` },
      { h: `Knowledge transfer that actually transfers`,
        body: [
          `Explicit knowledge can be written down: runbooks, designs, decision logs. Tacit knowledge lives in people: judgment, shortcuts, the feel for when something is wrong. Documents capture explicit knowledge. Tacit knowledge moves through pairing, shadowing, communities of practice, storytelling, and people doing the work while the expert watches.`,
          `The test of knowledge transfer isn't whether the document exists. It's whether someone else can do the work without the expert in the room. Lessons learned work the same way. Capture them throughout the project in a lessons learned register, not only at the end, and make them findable and used at the start of the next project. A lessons learned document nobody reads is a souvenir, not a lesson.`
        ],
        terms: [[`Tacit knowledge`,`Know-how that's hard to write down; shared through experience and conversation.`],[`Lessons learned register`,`A running record of lessons captured during the project.`],[`Organizational process assets`,`The templates, procedures, and historical information an organization keeps and reuses.`]],
        exam: `For knowledge transfer, prefer answers where people practice the work with support over answers that only produce documents.` },
      { h: `Continuous improvement`,
        body: [
          `Continuous improvement turns experience into better processes. Retrospectives do it for a team every iteration. Kaizen does it in small steady steps. Plan, Do, Check, Act is the classic cycle. At the organization level, it means updating templates, checklists, and policies when lessons show they need it, assigning owners to those changes, and measuring whether things actually got better.`,
          `Measure outcomes, not activity. Forecast accuracy, escaped defects, lead time from request to delivery, and customer satisfaction say something about how well delivery works. Hours logged and meetings held mostly say how busy people were.`
        ],
        terms: [[`Kaizen`,`Continuous improvement through small, frequent changes.`],[`PDCA`,`Plan, Do, Check, Act. A cycle for testing and adopting improvements.`]],
        exam: `When a lesson is identified, the strong answer updates the process or template and assigns an owner, not just records the lesson.` },
      { h: `Transition and releasing people`,
        body: [
          `Transition is where many projects stumble. The project team knows the product inside out; the operations or support team inherits it on a Monday. A good transition plan starts well before go-live: support staff join testing, runbooks are written with them, there's a period of shared ownership (often called hypercare), and a clear date when support fully owns it. Ask the receiving team what they need to feel ready, and don't declare the handoff done until they agree.`,
          `Releasing people is the last thing you do for your team. Release them on the date you promised their managers. Tell each person, and their manager, what they contributed. Update the resource calendar so nobody is double counted. A project manager who releases people well finds it much easier to get good people the next time.`,
          `Finally, celebrate. Marking the end of a project helps people let go of it and move on with energy. Recognition at closing should be specific and include everyone who contributed, wherever they sit.`
        ],
        terms: [[`Hypercare`,`A period of extra support right after go-live, before normal operations take over.`]],
        exam: `If operations isn't ready to accept the product, the project isn't ready to close. Work with them on what they need before handing off.` },
      { h: `Leading by growing other leaders`,
        body: [
          `Servant leadership means helping others succeed. At its best, it means building people who can lead without you. Coaching asks questions that help someone reach their own answer. Mentoring shares your experience. Delegating real authority, with support and a safety net, is how people grow. Taking the decision back the first time it gets hard teaches them they were never really trusted.`,
          `Then there's vision. Plans change every week; a reason doesn't. If the team wrote the vision with you, and it ties their work to why it matters to a nurse at two in the morning, they'll keep pulling in the same direction after the plan breaks and you're not in the room.`
        ],
        terms: [[`Coaching`,`Helping someone find their own answers through questions and feedback.`],[`Shared vision`,`A common picture of the goal and why it matters, built with the team.`]],
        exam: `If a new leader asks the PM to make a decision that's within their own role, the best answer usually coaches them to decide rather than deciding for them.` }
    ],
    video: [`uSkD5JnjebQ`,`Master the Close Project Process`,`PM Master Prep`,`16:23`]
  },
  scenes: [
    { id:`f15s1`, domain:`People`, task:`P1`, title:`Priya's kickoff`,
      text:(s,all,G)=>[`Priya shows Sam her kickoff deck the night before. It's thirty slides. The plan is complete, the architecture is chosen, and the vision statement is a sentence she wrote alone at midnight.`,`<span class="said" data-who="Priya">"Is it too much?"</span> she asks.`],
      opts:[
        {t:`Suggest she shape the vision with the team before showing them any plan.`, s:3, best:true, d:{trust:5,conf:1,health:3}, after:`Priya cuts the deck to six slides and opens the kickoff with one question: what would make a pharmacist trust this? The team talks for an hour. The vision they write is better than hers, and it's theirs.`, why:`A shared vision built with the team creates ownership and alignment that a finished plan handed down can't. Developing a common vision is a core People task.`},
        {t:`Tell her it's excellent and she should present every slide exactly as planned.`, s:0, d:{trust:-1,conf:0,health:-1}, after:`The kickoff goes smoothly. The team nods through thirty slides and leaves with Priya's plan, not their own.`, why:`A polished plan delivered to a team is still someone else's plan. Encouragement is kind, but it skips the chance to build a shared vision.`},
        {t:`Offer to present the vision himself so the team knows leadership supports her.`, s:0, d:{trust:-2,conf:0,health:0}, after:`The team watches Sam present Priya's project. Afterward, two of them ask Sam their questions instead of her.`, why:`Stepping in front of a new leader signals who's really in charge. Support her from behind, not by taking the stage.`},
        {t:`Suggest she trim the deck down to ten slides and keep the plan as it's written.`, s:1, d:{trust:1,conf:0,health:1}, after:`A shorter deck helps. The plan and vision are still hers alone, and the team treats them that way.`, why:`Tightening the deck is useful feedback, but the bigger gap is involvement. The vision lands harder when the team helps build it.`}
      ]},
    { id:`f15s2`, domain:`People`, task:`P3`, title:`Just tell me`,
      text:(s,all,G)=>[`Three weeks in, Priya's team is split between two designs for connecting to pharmacy systems. Both are defensible. The debate has gone in circles for four days.`,`Priya walks into Sam's office and closes the door. <span class="said" data-who="Priya">"You've done this longer than me. Just tell me which one."</span>`],
      opts:[
        {t:`Ask her which criteria matter most here, and what each design does to them.`, s:3, best:true, d:{trust:4,conf:0,health:3}, after:`Twenty minutes of questions later, Priya realizes the deciding factor is which design Northgate's IT team can support. She calls them that afternoon and makes the call herself.`, why:`Coaching helps someone reach their own answer. If you decide for a new leader every time it's hard, they learn to wait for you.`},
        {t:`Pick the design he'd choose and explain his reasoning so she learns from it.`, s:1, d:{trust:0,conf:0,health:2}, after:`The decision is good. Priya learns what Sam thinks. She doesn't learn how to decide.`, why:`Explaining your reasoning has teaching value, but the decision is within her role and her growth comes from making it.`},
        {t:`Tell her to let the team vote and go with the majority to end the debate.`, s:0, d:{trust:0,conf:0,health:-1}, after:`The vote is five to four. The four start working around the decision within a week.`, why:`Voting ends the discussion but not the disagreement, and it skips the criteria that should drive a technical choice.`},
        {t:`Send her back to keep the debate going until the team reaches full agreement.`, s:0, d:{trust:-1,conf:0,health:-3}, after:`Four more days pass. Full agreement doesn't come.`, why:`Consensus isn't always possible. Leaders sometimes have to decide with good criteria and move on.`}
      ]},
    { id:`f15s3`, domain:`People`, task:`P7`, title:`Theo's last month`,
      text:(s,all,G)=>[(G.blamedtheo?`Theo hasn't mentioned the burn-in meeting in months. Sam has thought about it most weeks. `:``)+`Theo's contract ends in four weeks. His runbooks fill eleven pages of the wiki. The team says they're clear.`,`Sam isn't sure clear on paper means ready in an outage at two in the morning.`],
      opts:[
        {t:`Have the team run the next real incident while Theo watches and coaches.`, s:3, best:true, d:{trust:4,conf:1,health:4}, after:`The incident comes on a Wednesday. Priya's team fumbles for ten minutes, then finds it. Theo says nothing until the end, then adds three lines to the runbook about what they missed.`, why:`The real test of knowledge transfer is doing the work without the expert. Practice with coaching moves tacit knowledge that documents can't.`},
        {t:`Ask Theo to record video walkthroughs of every system before he leaves.`, s:1, d:{trust:0,conf:0,health:2}, after:`The videos are good. Nobody watches them until the next outage, when there isn't time.`, why:`Recordings help with explicit knowledge, but they don't prove anyone can do the work. Pair them with hands-on practice.`},
        {t:`Extend Theo's contract three more months so the team has a safety net.`, s:0, d:{trust:0,conf:0,health:-1}, after:`The team relaxes. Three months later, nothing has transferred that hadn't already.`, why:`More time with the expert in the room often delays transfer. The team learns by doing it without him.`},
        {t:`Have the team sign off that they've read and understood all of the runbooks.`, s:0, d:{trust:-1,conf:0,health:0}, after:`Everyone signs. It proves they can read.`, why:`A sign-off on documentation doesn't show capability. Test the transfer with real work.`}
      ]},
    { id:`f15s4`, domain:`Process`, task:`R10`, title:`Go-live in Omaha`,
      text:(s,all,G)=>[`Northgate's nine hospitals go live on a Tuesday. Ruth sits in the back of the command center in Omaha with a cup of coffee and doesn't say a word for six hours.`,`By evening every acceptance criterion in the contract is met. Park shakes Sam's hand and says, <span class="said" data-who="Helen">"Looks good. We'll get you something formal eventually."</span>`],
      opts:[
        {t:`Ask Park to sign acceptance this week against the contract's criteria.`, s:3, best:true, d:{trust:1,conf:3,health:4}, after:`Park signs Thursday, criterion by criterion. The warranty period starts the same day, and support takes over with a clear start date.`, why:`A handshake isn't acceptance. Formal sign-off against the agreed criteria is what closes the deliverable and starts warranty and support.`},
        {t:`Treat the handshake as acceptance and start moving the team to other work.`, s:0, d:{trust:0,conf:-1,health:-3}, after:`Six weeks later, Northgate's finance team disputes the final invoice because nothing was formally accepted.`, why:`Without formal acceptance, the project isn't closed and the customer can still reopen scope or payment.`},
        {t:`Wait for Park to send the formal paperwork whenever she's ready to send it.`, s:1, d:{trust:0,conf:0,health:-1}, after:`Park means well. The paperwork takes five weeks, and the team can't be released until it arrives.`, why:`Patience with a customer is fine, but closing is your process to drive. Ask for acceptance promptly against the criteria.`},
        {t:`Send Park an email summarizing go-live and treat no reply as acceptance.`, s:0, d:{trust:0,conf:-2,health:-1}, after:`Park doesn't reply for two weeks because she's busy. Legal says silence isn't acceptance under this contract.`, why:`Acceptance should be affirmative and documented, according to the contract's terms.`}
      ]},
    { id:`f15s5`, domain:`Process`, task:`R10`, title:`Closing Theo's contract`,
      text:(s,all,G)=>[`Theo's last invoice arrives. Joan Pruitt asks Sam to approve final payment so she can close the contract.`,`The statement of work listed six deliverables. Sam has seen five.`],
      opts:[
        {t:`Confirm all six deliverables were received and accepted before final payment.`, s:3, best:true, d:{trust:1,conf:1,health:3}, after:`The sixth deliverable, a dependency map, is sitting finished in Theo's drafts. He sends it within the hour. Joan pays and records Theo's performance as excellent for the next time someone wants to hire him.`, why:`Contract closure verifies every deliverable, resolves anything open, makes final payment, and records seller performance.`},
        {t:`Approve payment now, since five of six were delivered and Theo was excellent.`, s:0, d:{trust:0,conf:0,health:-2}, after:`Theo moves on to a new client. The dependency map is never seen again.`, why:`Paying before verifying all deliverables loses your leverage and your record. Good performance doesn't replace verification.`},
        {t:`Hold all payment until Theo explains in writing why one item is missing.`, s:1, d:{trust:-2,conf:0,health:1}, after:`Theo is hurt by the tone, then sends the map. It arrives a week later than it would have.`, why:`Verifying is right, but leading with a formal hold strains a good relationship. A quick conversation would have resolved it.`},
        {t:`Ask Joan to close the contract and handle the missing item as a separate request.`, s:0, d:{trust:0,conf:0,health:-1}, after:`The contract closes with an open gap, and no vehicle to get the deliverable later.`, why:`Closing with known gaps defeats the purpose of closure. Resolve deliverables before you close.`}
      ]},
    { id:`f15s6`, domain:`People`, task:`P1`, title:`Ruth's last board meeting`,
      text:(s,all,G)=>[`At Ruth's final board meeting, Elena asks Sam to describe where the delivery office goes next year. Victor has a spreadsheet ready. Ruth has her reading glasses on top of her head and a small smile.`,`Sam has a list of initiatives. He also has five minutes.`],
      opts:[
        {t:`Describe one clear picture of what delivery will mean, and how it ties to strategy.`, s:3, best:true, d:{trust:2,conf:5,health:2}, after:`Sam says: by next year, nobody at Halcyon promises a customer anything that delivery can't stand behind, and every customer can see the truth about their project any time they want. Then he names three things that get there. Victor puts the spreadsheet down.`, why:`A vision people can repeat aligns stakeholders better than a list of tasks. Tie it to the organization's goals, then show the path.`},
        {t:`Walk the board through every initiative on his list in the five minutes he has.`, s:0, d:{trust:0,conf:-1,health:0}, after:`He gets through eleven initiatives. Nobody remembers more than two.`, why:`A list isn't a vision. Too many items in too little time leaves no shared picture.`},
        {t:`Ask Victor to share his spreadsheet first, and build the plan around its numbers.`, s:1, d:{trust:0,conf:1,health:0}, after:`The numbers are useful. The conversation becomes about cost, and the purpose gets lost.`, why:`Financial grounding matters, but leading with it lets the cost conversation define the vision instead of support it.`},
        {t:`Defer to Elena, since setting company direction belongs to the CEO, not delivery.`, s:0, d:{trust:0,conf:-2,health:0}, after:`Elena raises an eyebrow. She asked for his view.`, why:`The sponsor asked you to set direction for your area. Owning a vision for your function is part of leading it.`}
      ]},
    { id:`f15s7`, domain:`Business Environment`, task:`B6`, title:`The big retrospective`,
      text:(s,all,G)=>[`Sam runs a retrospective across everything since Cascade: two customers, a merger, a near disaster with Northgate, and a hiring freeze. Forty people, three time zones, a lot of sticky notes.`,`By the end there are sixty two lessons on the board.`],
      opts:[
        {t:`Turn the few lessons that matter most into process changes with owners.`, s:3, best:true, d:{trust:3,conf:2,health:5}, after:`Six lessons become six changes: the deal desk form, report locking, a resource view across projects, and three more. Each has an owner and a review date. Sixty two sticky notes become a page people use.`, why:`Continuous improvement means changing how work gets done, not just listing what went wrong. Prioritize, assign owners, and follow up.`},
        {t:`Document all sixty two lessons in a detailed report and share it with everyone.`, s:1, d:{trust:1,conf:1,health:1}, after:`The report is thorough. It's opened forty times in the first week and twice the month after.`, why:`Capturing lessons is good. Without turning the important ones into changes with owners, they don't change anything.`},
        {t:`Ask each team to pick its own lessons and apply them however it sees fit.`, s:0, d:{trust:1,conf:0,health:-1}, after:`Each team improves its own corner. The cross-team problems, the ones that nearly sank Northgate, belong to nobody.`, why:`Team-level improvement matters, but organizational lessons need organizational owners.`},
        {t:`Thank everyone and schedule the same retrospective again in six months.`, s:0, d:{trust:0,conf:0,health:-2}, after:`Six months later, the same lessons show up again.`, why:`A retrospective without action is a meeting about feelings. Improvement requires change.`}
      ]},
    { id:`f15s8`, domain:`People`, task:`P7`, title:`Where lessons go to die`,
      text:(s,all,G)=>[`Priya tells Sam she never once opened the lessons learned folder before starting Pharmacy Connect. Nobody told her it existed. It holds fourteen documents, most named "Final_Lessons_v2."`,`Three of them would have saved her a week.`],
      opts:[
        {t:`Make lessons searchable by topic, and review the relevant ones at every kickoff.`, s:3, best:true, d:{trust:2,conf:1,health:4}, after:`The folder becomes a short searchable register. Every kickoff checklist now starts with fifteen minutes on lessons tagged to that kind of project.`, why:`Lessons are only valuable if they're found and used. Make them accessible and build their use into how projects start.`},
        {t:`Rename every file clearly and send an announcement that the folder exists.`, s:1, d:{trust:0,conf:0,health:1}, after:`The announcement gets a few thumbs up. Usage barely moves.`, why:`Better organization helps, but awareness alone doesn't change behavior. Build lessons into the process.`},
        {t:`Ask project managers to read every past lessons document before each project.`, s:0, d:{trust:-1,conf:0,health:0}, after:`Nobody reads fourteen documents before a kickoff.`, why:`Requiring people to read everything isn't practical. Make the relevant lessons easy to find at the moment they matter.`},
        {t:`Have Priya write up the three lessons she missed so others don't miss them.`, s:0, d:{trust:0,conf:0,health:0}, after:`Now there are fifteen documents nobody opens.`, why:`Adding more documents to an unused folder doesn't fix the problem of nobody using it.`}
      ]},
    { id:`f15s9`, domain:`People`, task:`P3`, title:`Recognition`,
      text:(s,all,G)=>[`Elena gives Sam a budget for recognizing the Northgate team. The obvious move is a party in Denver.`,`The Kraków team built the integration. Alyssa Kemp stopped a demo that would have repeated the original mistake.`,(G.sidelineddevin?`And Devin, the engineer Sam once moved off the work instead of coaching, walked up to Priya in the spring, asked for a real task, and wrote the reconciliation workflow that saved go-live. Sam owes him thanks and an apology, in that order.`:`And Devin, who was coasting a year ago, wrote the reconciliation workflow that saved go-live.`)],
      opts:[
        {t:`Recognize people specifically for what each did, in ways that fit each of them.`, s:3, best:true, d:{trust:7,conf:1,health:2}, after:`Kraków gets a team dinner in Kraków and Elena on a video call naming their work. Alyssa gets a public thank you from Elena at the all-hands. Devin, who hates attention, gets a handwritten note and the lead on the next integration.`, why:`Recognition works when it's specific, timely, and fits the person. Include everyone who contributed, wherever they are.`},
        {t:`Throw one big party in Denver and fly in anyone who wants to come.`, s:1, d:{trust:2,conf:0,health:0}, after:`It's a good party. Half of Kraków can't travel that week, and Devin leaves early.`, why:`A celebration is good, but one format doesn't fit everyone. Specific recognition lands better than a general one.`},
        {t:`Split the budget evenly as cash bonuses for every person on the project.`, s:0, d:{trust:0,conf:0,health:0}, after:`Everyone gets the same amount. Nobody feels seen.`, why:`Equal cash treats a year of different contributions as interchangeable. Recognition is about what people did.`},
        {t:`Give the whole budget to the three standout people Sam can name right now.`, s:0, d:{trust:-3,conf:0,health:0}, after:`Three people are thrilled. Thirty are quietly annoyed.`, why:`Singling out a few without acknowledging the team undermines the collaboration that made it work.`}
      ]},
    { id:`f15s10`, domain:`Business Environment`, task:`B6`, title:`Measuring better`,
      text:(s,all,G)=>[`Victor wants a single dashboard showing whether the delivery office is improving. His draft has hours logged, meetings held, and tickets closed.`,`Sam thinks those mostly measure how busy people were.`],
      opts:[
        {t:`Propose outcome measures like forecast accuracy, escaped defects, and lead time.`, s:3, best:true, d:{trust:1,conf:4,health:3}, after:`Victor pushes back on two and keeps three. Forecast accuracy goes on the board's monthly page. In two quarters it rises from 58 to 81 percent.`, why:`Measure outcomes that show whether delivery got better, not activity. That's how you know continuous improvement is working.`},
        {t:`Accept Victor's draft, since any measurement is better than none at all.`, s:0, d:{trust:-1,conf:0,health:-2}, after:`Hours logged go up. Nothing else does.`, why:`Activity metrics reward busyness and can drive the wrong behavior. What you measure is what you get.`},
        {t:`Add Sam's outcome measures beside Victor's, so the dashboard shows both sets.`, s:1, d:{trust:0,conf:1,health:1}, after:`The dashboard has fourteen numbers. People look at the ones that went up.`, why:`Including outcome measures is right, but cluttering the view with activity metrics dilutes the signal.`},
        {t:`Skip the dashboard and report improvement through stories at each board meeting.`, s:0, d:{trust:0,conf:-2,health:0}, after:`The stories are good. The board can't tell whether they're typical or exceptions.`, why:`Stories bring data to life, but without measures, improvement can't be verified.`}
      ]},
    { id:`f15s11`, domain:`Process`, task:`R10`, title:`Final report`,
      text:(s,all,G)=>[`The Northgate project is formally accepted and the contracts are closed. The team is ready to move on. Sam has one week left on the closeout checklist.`,`The benefits in Northgate's business case, documentation time saved per note, won't be measurable for six months.`],
      opts:[
        {t:`Name a Northgate benefits owner, then archive and release the team.`, s:3, best:true, d:{trust:3,conf:2,health:4}, after:`Northgate's chief nursing officer owns the benefits measure with a baseline and a six month check. The archive is complete, the final report is filed, and every person is released on the date their managers were promised.`, why:`Closure includes a final report, archived records, released resources, and a clear owner for benefits that outlast the project.`},
        {t:`Keep the project open six months so Sam can report the benefits himself.`, s:0, d:{trust:-1,conf:0,health:-2}, after:`The team is stuck in limbo, half released. Functional managers start asking when they get their people back.`, why:`Projects end; benefits continue. Transfer benefits ownership to the business and close the project.`},
        {t:`Release the team now and leave the archive and final report for later.`, s:1, d:{trust:1,conf:0,health:-1}, after:`The team is happy. Three months later, an auditor asks for records that were never filed.`, why:`Releasing on time is right, but closing the records is part of closure too.`},
        {t:`Note in the final report that benefits will be measured someday by someone.`, s:0, d:{trust:0,conf:-1,health:-1}, after:`Someday never comes, and nobody can say whether the project paid off.`, why:`Benefits need a named owner and a plan, or they don't get measured.`}
      ]},
    { id:`f15s12`, domain:`People`, task:`P3`, title:`Priya's first slip`,
      text:(s,all,G)=>[`On a Thursday afternoon Priya walks into Sam's office white faced. A pharmacy system vendor changed its interface without notice. Pharmacy Connect will slip two weeks.`,`<span class="said" data-who="Priya">"Ochoa is going to be furious,"</span> she says. <span class="said" data-who="Priya">"Can you call him? He trusts you."</span>`],
      opts:[
        {t:`Help her plan the call to Ochoa, then let her make it herself.`, s:3, best:true, d:{trust:6,conf:2,health:3}, after:`They spend thirty minutes on what she'll say: what happened, the impact, two options, and what she needs from Cascade. Priya calls. Ochoa is quiet, then says, <span class="said" data-who="Ochoa">"Thank you for calling before Friday."</span> She comes back to Sam's office grinning.`, why:`Support a new leader through the hard moment without taking it from her. Coaching her through it builds the confidence and trust she needs to lead the next one alone.`},
        {t:`Call Ochoa himself, since he has the relationship and this one matters.`, s:0, d:{trust:-3,conf:2,health:0}, after:`Ochoa takes it well. Next time something goes wrong, he calls Sam instead of Priya.`, why:`Taking the hard call teaches the customer and the new leader who's really in charge. Support her; don't replace her.`},
        {t:`Join the call with her and let her lead it, ready to help if needed.`, s:1, d:{trust:2,conf:2,health:1}, after:`Priya leads well. Ochoa notices Sam is there and directs the last question to him.`, why:`Joining can be useful the first time, but your presence can still pull authority away from her. Prepare her, then trust her.`},
        {t:`Tell her to send Ochoa a written update instead, so it's documented.`, s:0, d:{trust:0,conf:-2,health:0}, after:`Ochoa reads the email on his phone between meetings and calls Sam to ask what's really going on.`, why:`Bad news to a key stakeholder deserves a conversation, followed by documentation, not documentation alone.`}
      ]}
  ],
  drills: [
    { after:`f15s11`, title:`Measuring the benefit`,
      setup:[`Northgate's business case promised to reduce the time clinicians spend on documentation. Before go-live, a typical note took 16 minutes. Six months after go-live, Northgate's chief nursing officer measures it at 11 minutes.`,`Northgate's nine hospitals produce about 1,200 of these notes per day. Assume 250 working days in a year.`],
      fields:[ {label:`Minutes saved per note`, answer:5, tol:0}, {label:`Clinician hours saved per day`, answer:100, tol:0}, {label:`Clinician hours saved per year`, answer:25000, tol:0} ],
      solution:[`Minutes saved per note: 16 minus 11 = 5 minutes.`,`Per day: 1,200 notes x 5 minutes = 6,000 minutes. 6,000 / 60 = 100 hours.`,`Per year: 100 hours x 250 days = 25,000 hours.`,`That's the number the benefits owner reports, long after the project closed. It's why the project existed in the first place.`] }
  ],
  exercise: { after:`f15s5`, title:`Is it closing work`, intro:`Decide which part of the project each activity belongs to.`,
    items:[
      {prompt:`Park signs acceptance of the deliverables against the contract criteria.`, choices:[`Closing`,`Executing`,`Monitoring and controlling`,`Planning`], answer:0, why:`Formal acceptance of final deliverables is a closing activity.`},
      {prompt:`The team compares this week's progress against the baseline and updates the forecast.`, choices:[`Closing`,`Executing`,`Monitoring and controlling`,`Planning`], answer:2, why:`Comparing performance to the plan and forecasting is monitoring and controlling.`},
      {prompt:`Joan verifies Theo's six deliverables, pays the last invoice, and files his performance rating.`, choices:[`Closing`,`Executing`,`Monitoring and controlling`,`Planning`], answer:0, why:`Procurement closure belongs to closing.`},
      {prompt:`Priya's team builds the pharmacy interface adapter.`, choices:[`Closing`,`Executing`,`Monitoring and controlling`,`Planning`], answer:1, why:`Doing the work to produce deliverables is executing.`},
      {prompt:`Sam writes how the team will release each person when their work ends.`, choices:[`Closing`,`Executing`,`Monitoring and controlling`,`Planning`], answer:3, why:`Deciding in advance how resources will be released is part of resource planning.`},
      {prompt:`The team's records are archived and the final report is filed.`, choices:[`Closing`,`Executing`,`Monitoring and controlling`,`Planning`], answer:0, why:`Archiving records and final reporting happen at closing.`}
    ]},
  quiz: [
    {q:`All deliverables are complete and the customer says informally that they're satisfied. What should the project manager do next?`, opts:[`Release the team to other projects`,`Obtain formal acceptance of deliverables`,`Archive records and file the final report`,`Run the final lessons learned session`], a:1, why:`Formal acceptance against criteria comes before other closing steps that depend on it.`, task:`R10`, domain:`Process`},
    {q:`A seller has delivered five of six contracted items and asks for final payment. What should the project manager do?`, opts:[`Approve payment given their good record`,`Hold payment and send a formal notice`,`Confirm all items before final payment`,`Close the contract and request it later`], a:2, why:`Procurement closure verifies all deliverables before final payment.`, task:`R10`, domain:`Process`},
    {q:`What is the best test that knowledge transfer from a departing expert has worked?`, opts:[`The expert's documentation is fully complete`,`The team signs off that they read the runbooks`,`The team performs the work without the expert`,`The expert's contract is extended as a fallback`], a:2, why:`Capability is shown when others can do the work without the expert present.`, task:`P7`, domain:`People`},
    {q:`Theo's last month is coming. Which of these does the team most need to pick up by working beside him, because no runbook will capture it?`, opts:[`The ordered restart steps for the inference cluster`,`His feel for which log warnings mean a real outage`,`The current network diagram for the IronPeak racks`,`The list of vendor contacts and their phone numbers`], a:1, why:`That judgment is tacit knowledge: built from experience and hard to write down, so it moves through pairing and practice. Restart steps, diagrams, and contact lists are explicit knowledge, and a document handles them fine.`, task:`P7`, domain:`People`},
    {q:`A retrospective produces many lessons. What should happen next to achieve continuous improvement?`, opts:[`Publish all lessons in a detailed report`,`Have each team apply lessons as it wishes`,`Schedule another retrospective in six months`,`Turn key lessons into changes with owners`], a:3, why:`Continuous improvement changes processes, with owners and follow-up.`, task:`B6`, domain:`Business Environment`},
    {q:`Which metric best indicates whether a delivery organization is improving?`, opts:[`Forecast accuracy over time`,`Total hours logged by the team`,`Number of meetings held per week`,`Count of tickets opened each month`], a:0, why:`Outcome measures like forecast accuracy show improvement. Activity measures show busyness.`, task:`B6`, domain:`Business Environment`},
    {q:`A new project lead asks the PM to make a technical decision that falls within her role. What should the PM do?`, opts:[`Make the decision to save the team time`,`Have the team vote on the decision`,`Coach her through deciding it herself`,`Ask her to wait for full consensus first`], a:2, why:`Coaching builds the new leader's ability to decide. Deciding for her teaches dependence.`, task:`P3`, domain:`People`},
    {q:`What is the main purpose of a lessons learned register?`, opts:[`To record lessons throughout the project for reuse`,`To document blame for problems on the project`,`To replace the final report at project closure`,`To track defects found during quality control`], a:0, why:`The register captures lessons as they happen so they can be applied during and after the project.`, task:`P7`, domain:`People`},
    {q:`Project benefits won't be measurable until months after closure. What should the project manager do?`, opts:[`Keep the project open until benefits appear`,`Note that benefits will be measured someday`,`Assign a business owner to track benefits`,`Remove benefits from the final report`], a:2, why:`Projects close; benefits ownership transfers to the business with a plan to measure.`, task:`R10`, domain:`Process`},
    {q:`The most effective way to build a shared vision for a new project is to:`, opts:[`present a finished vision statement at kickoff`,`develop the vision together with the team`,`borrow the vision from the business case`,`have the sponsor announce the vision alone`], a:1, why:`A vision built with the team creates ownership and alignment.`, task:`P1`, domain:`People`},
    {q:`Which activity belongs to closing a project?`, opts:[`Comparing progress to the baseline`,`Building the final deliverables`,`Planning how resources will be released`,`Archiving records and the final report`], a:3, why:`Archiving records and final reporting happen at closure.`, task:`R10`, domain:`Process`},
    {q:`A team is recognized with one celebration that some members can't attend. What would make recognition more effective?`, opts:[`Recognition that is specific to each person`,`A larger celebration with more attendees`,`Equal cash bonuses for every team member`,`Rewards for the top three contributors only`], a:0, why:`Specific, fitting recognition that includes everyone works better than a one-size approach.`, task:`P3`, domain:`People`},
    {q:`A new project lead must tell a key customer about a two week slip and asks the PM to make the call. What is the best response?`, opts:[`Make the call, since the PM has the relationship`,`Have her send a written update to the customer`,`Help her plan the call, then let her make it`,`Make the call together and let the PM lead`], a:2, why:`Support the new leader through it without taking it from her. That builds her credibility with the customer.`, task:`P3`, domain:`People`},
    {q:`Which cycle is a classic model for continuous improvement?`, opts:[`Plan, Do, Check, Act`,`Initiate, Plan, Execute, Close`,`Forming, Storming, Norming, Performing`,`Awareness, Desire, Knowledge, Ability`], a:0, why:`PDCA is the classic improvement cycle.`, task:`B6`, domain:`Business Environment`},
    {q:`During closure, the project manager discovers the lessons learned folder is rarely used. What is the best improvement?`, opts:[`Announce the folder at the next all-hands`,`Require PMs to read every past document`,`Add this project's lessons to the folder too`,`Make lessons searchable and use them at kickoff`], a:3, why:`Lessons need to be easy to find and built into how projects start.`, task:`P7`, domain:`People`}
  ],
  closing:(s,all,G)=>[
    `On the last night in Omaha, after the command center emptied, Ruth found Sam in the parking garage. She handed him a small cloth patch, faded, with a mission name and a date from 1991.`,
    `<span class="said" data-who="Ruth">"I've kept that in a drawer for thirty five years,"</span> she said. <span class="said" data-who="Ruth">"I want it to live somewhere it gets looked at. Hang it where you'll see it when the numbers are bad."</span>`,
    `<span class="said" data-who="Sam">"Ruth, I can't take this."</span>`,
    `<span class="said" data-who="Ruth">"You already did,"</span> she said. <span class="said" data-who="Ruth">"A year ago, in that coffee shop, when you told Elena eighteen weeks instead of fourteen."</span> She got in her car. Then she rolled the window down. <span class="said" data-who="Ruth">"Go for launch, Sam."</span>`,
    `Theo's going away lunch was at a taco place on Larimer. He gave a short speech about Priya, who turned red, and a shorter one about Sam. <span class="said" data-who="Theo">"He was the first manager who fixed the system instead of fixing me,"</span> Theo said, and sat down before anyone could make it weird.`,
    (s.score>=27?`Dana framed the patch. She hung it in Sam's office herself, above the desk, at eye level. <span class="said" data-who="Dana">"For the bad numbers,"</span> she said. <span class="said" data-who="Dana">"Though from what I hear, you don't hide those anymore."</span>`:`Dana framed the patch and hung it in Sam's office, above the desk. <span class="said" data-who="Dana">"For the bad numbers,"</span> she said. <span class="said" data-who="Dana">"You'll still have them. Just don't hide them."</span>`),
    (G.forcedrollout?`Nothing came from Cheyenne. The nurses there use the agents now, grudgingly, and every few weeks one of them files a ticket that reads like a protest. Sam keeps Denise Harmon's old legal pad list pinned by his desk. Some rollouts you only win on paper.`:`From Cheyenne, Denise Harmon sent a photo: her night shift, eleven nurses, holding a hand lettered sign. FINISHED CHARTING BEFORE MIDNIGHT, 41 NIGHTS RUNNING. Sam pinned it next to where the patch would go.`),
    `Kraków sent a box. Inside was a mug with the Halcyon logo printed slightly crooked and a card signed by all nine of Tomasz's engineers. Tomasz had added a line at the bottom in block capitals: NOT A VENDING MACHINE. Sam put the mug on the shelf next to the patch and used it every day.`,
    `Three months after that, Sam's phone buzzed on the nightstand at 6:12 on a Monday.`,
    `He almost didn't look. For most of last year, an email that early meant somebody quit or something broke. At Halcyon, nobody sent good news before seven.`,
    (G.overloadedpriya?`It was Priya. Sam knew what it had cost her to get here. Last spring he'd stacked both projects on her, and she'd stopped taking lunch and stopped saying no. He'd apologized and fixed the plan, but he read her name with that in his chest.`:`It was Priya.`),
    `<prop type="email" from="Priya Shah" to="Sam Okafor" time="6:11 AM" subject="Pharmacy Connect: accepted">Cascade signed acceptance on Saturday, a week ahead of the revised date. Dr. Ochoa wrote a note at the bottom of the form: First vendor project in my career that finished when it said it would. Tell Sam he taught you well. Then tell him I said you didn't need him.<br>One more thing, before I talk myself out of it. I want to talk about what I run next. I think I'm ready, and I think you'll tell me if I'm not.<br>Priya</prop>`,
    `Sam read it twice in the dark and a third time with the lamp on. Dana rolled over. <span class="said" data-who="Dana">"Bad?"</span> He said no. <span class="said" data-who="Dana">"Then go make coffee,"</span> she said, already back asleep, and he went.`,
    `The kitchen was cold. He filled the mug and forgot about it on the counter, and after a while he picked up the phone and dialed Tucson.`,
    `Ray answered on the second ring, the way he had for twenty years, gravel in his voice. <span class="said" data-who="Ray">"Okafor. Do you know what time it is?"</span>`,
    `<span class="said" data-who="Sam">"About the time you used to kick me out of the barracks,"</span> Sam said. <span class="said" data-who="Sam">"You got a minute, Chief? I've got news. Somebody else's, for once."</span>`
  ],
  episode:{src:`audio/full-ch15.mp3`, len:`about 35 minutes`}
});
