(((window.HALCYON_DATA=window.HALCYON_DATA||{}).asep=window.HALCYON_DATA.asep||{}).full=window.HALCYON_DATA.asep.full||[]).push({
  num: 1, part: `Part One: Concept`, title: `Kickoff`, weeks: `Week 1`,
  tasks: [`T1`,`T2`,`T11`,`M1`,`M6`,`A2`,`O1`,`O4`,`X1`,`X2`,`X5`],
  cast: [
    [`Frank Brooks`,`Nadia's father. Retired Xcel lineman in Pueblo. Texts in all caps.`],
    [`Helen Cho-Ramirez`,`Halo Orbital, director of crew operations. Spent eleven years as a flight surgeon for long duration crews.`]
  ],
  opening: [
    `Nadia Brooks sat in her car in the Front Range Orbital lot at 6:40 on a Monday morning and watched the sun come up behind a sign that still said Centennial Lighting Works.`,
    `The company had bought the old factory two years ago and never taken the sign down. Somebody had added a sticker under it, a little drawing of a space station, and that was the rebrand. Inside, she'd been told, was a high bay big enough to stand a city bus on its end, a pressure test cell, and four hundred people who built things that held air.`,
    `Her badge said Systems Engineer. She had never been one. For five years she had been a test engineer at an avionics shop in Colorado Springs, the person who wrote the procedure, ran the unit through it, and signed the sheet that said it passed. She was good at it. She was fast and careful and she never fudged a number.`,
    `And in her second year she had signed the acceptance sheet on a cockpit display, serial 0447, that passed every step of the procedure she wrote. Eight months later it went dark on a night training flight over the Nevada range. The pilot landed on the standby instruments. Nobody was hurt. The investigation found the unit had done exactly what the test said it would do. The test had just never asked it to do what the pilots actually needed: start up after two hours of cold soak at altitude.`,
    `Nobody blamed her. That was almost worse. Every step had passed. She had built a perfect answer to the wrong question.`,
    `Her phone buzzed. Her father, who had climbed power poles for Xcel for thirty one years and now texted exclusively in capital letters.`,
    `<prop type="text" from="Dad" time="6:44 AM">FIRST DAY. PROUD OF YOU. REMEMBER YOU DONT CLIMB A POLE YOU HAVENT GROUNDED.</prop>`,
    `She smiled, typed back a heart, and went inside.`,
    `By nine she was in a conference room with a whiteboard that still had a lighting fixture wiring diagram ghosted under the erasures. At the head of the table sat Wes Harland, the chief engineer, fifty eight, sleeves rolled, the man who had designed more pressure vessels than anyone in the building. Amara Osei, the program manager, had the signed contract open on her laptop. Luis Ferreira from integration and test leaned against the wall with a coffee. A young engineer named Jun Takeda had a laptop covered in stickers and an open modeling tool.`,
    `<span class="said" data-who="Amara">"Halo Orbital signed Friday,"</span> Amara said. <span class="said" data-who="Amara">"HEARTH. A habitat module for their station. Ninety cubic meters, crew of four, fifteen year design life, launch in thirty months. Firm fixed price on development. This is the biggest thing this company has ever won, and the people who will sleep in it are astronauts."</span>`,
    `<span class="said" data-who="Wes">"It's a can with air in it,"</span> Wes said. <span class="said" data-who="Wes">"We've built eleven cargo modules. We know what to build. I'd like a layout on this board by Friday."</span>`,
    `Everyone looked at the new systems engineer. Nadia thought about serial 0447, and about how sure everyone had been.`
  ],
  lesson: {
    title: `Ruth's Flight Notes: start with the problem`,
    sections: [
      { h: `What a systems engineer is for`,
        body: [`Ruth Calder met her at a diner on Arapahoe Road that afternoon, ordered pie, and listened to the whole story about the cold display without interrupting. Then she pulled a napkin over. <span class="said" data-who="Ruth">"You already know the most important thing in this job. You learned it the expensive way."</span>`,
          `Systems engineering is a way of making sure a whole thing works, for the people who need it, across its whole life. A system is a set of parts that interact to do something none of them can do alone. That last part is the point. A habitat module is a pressure shell, an air system, a thermal loop, power, data, crew quarters, and a hatch. None of those keeps four people alive. Together they might. The behavior that only shows up when the parts work together is called emergent behavior, and it's where both the value and the surprises live. Systems thinking means looking at the whole, the interactions, and the environment the system lives in, instead of one part at a time.`,
          `<span class="said" data-who="Ruth">"Wes is right that he knows how to build a can,"</span> Ruth said. <span class="said" data-who="Ruth">"Your job is to make sure it's the right can."</span>`],
        terms: [[`System`,`An arrangement of parts or elements that together exhibit behavior or meaning that the individual parts don't.`],[`Emergent behavior`,`Behavior of the whole system that comes from the interactions of its parts, not from any single part.`],[`Systems thinking`,`Looking at the whole system, the relationships between its parts, and its environment over its full life.`]],
        exam: `Expect definition questions. If an answer talks about the whole, the interactions, the stakeholders, and the full life cycle, it's usually the systems engineering answer. If it optimizes one part in isolation, it usually isn't.` },
      { h: `The life cycle and its gates`,
        body: [`Ruth drew six boxes on the napkin. Every system moves through life cycle stages. The handbook's generic set is Concept, Development, Production, Utilization, Support, and Retirement. Concept is where you figure out what's needed and whether it's feasible. Development is where you define, design, build, and verify it. Production makes it, Utilization is when people use it, Support keeps it working, and Retirement takes it out of service and disposes of it. Utilization and Support run side by side. HEARTH will spend fifteen years in those two stages, and somebody will eventually have to plan how it leaves orbit with the station.`,
          `Between stages sit decision gates. A gate is a planned point where leaders look at the evidence and decide what happens next. The options aren't just yes or no. They can proceed to the next stage, keep working in the current one, go back to an earlier stage, put the project on hold, or end it. Technical reviews, like a system requirements review or a preliminary design review, feed those decisions with evidence. <span class="said" data-who="Ruth">"A gate is where you're allowed to say we're not ready,"</span> Ruth said. <span class="said" data-who="Ruth">"Use it."</span>`],
        terms: [[`Life cycle stages`,`Concept, Development, Production, Utilization, Support, and Retirement in the handbook's generic model.`],[`Decision gate`,`A planned decision point between stages where the evidence is reviewed and leaders decide to proceed, continue, go back, hold, or terminate.`]],
        exam: `Know the six generic stages in order, and know that Utilization and Support overlap. Know that a gate decision can be more than proceed or stop.` },
      { h: `The V and the processes`,
        body: [`Then she drew a V. Down the left side you define: stakeholder needs, system requirements, architecture, design. At the bottom you build. Up the right side you integrate and prove: parts into subsystems, subsystems into the system, then verification and validation. Every level on the left has a partner on the right. The requirement you write on the way down is the thing you test on the way up. <span class="said" data-who="Ruth">"Your cold display was a right side problem that started on the left side,"</span> she said. <span class="said" data-who="Ruth">"Nobody wrote down what the pilots needed, so nobody tested it."</span>`,
          `The handbook organizes the work into four process groups from ISO/IEC/IEEE 15288. Agreement processes cover buying and supplying. Organizational project-enabling processes give projects what they need: life cycle models, infrastructure, people, quality, and knowledge. Technical management processes plan, assess, decide, and control. Technical processes do the engineering, from mission analysis all the way to disposal. Verification asks whether you built it right, against the requirements. Validation asks whether you built the right thing, for the stakeholders, in the real environment.`],
        terms: [[`Verification`,`Confirming, with objective evidence, that the system meets its specified requirements. Did we build it right?`],[`Validation`,`Confirming that the system meets the stakeholders' intended use in its intended environment. Did we build the right thing?`],[`Process groups`,`Agreement, organizational project-enabling, technical management, and technical processes, per ISO/IEC/IEEE 15288.`]],
        exam: `Verification and validation questions are everywhere on this exam. Requirements go with verification. Stakeholder needs and intended use go with validation.` },
      { h: `Mission analysis comes before the layout`,
        body: [`The first technical process is business or mission analysis. Its purpose is to define the problem or opportunity, characterize the solution space, and identify the kinds of solutions that could work. You ask why the system should exist, who it serves, what success looks like, and what constraints you can't move. You produce a problem statement and early life cycle concepts, including how it will be operated, before anyone draws a layout. For HEARTH that means asking what Halo is really trying to do with this module, not just what the contract volume is.`,
          `Planning starts in the first week too. Project planning produces the plans, and for the engineering work that's usually a systems engineering management plan, or SEMP. It says which processes you'll use, how you'll tailor them, what reviews you'll hold, who owns what, and how technical work ties to the schedule. <span class="said" data-who="Ruth">"Wes wants a layout by Friday,"</span> Ruth said, finishing the pie. <span class="said" data-who="Ruth">"Give him something better by Friday. Give him the problem."</span>`],
        terms: [[`Business or mission analysis`,`The process that defines the problem or opportunity, characterizes the solution space, and determines potential solution classes.`],[`SEMP`,`Systems engineering management plan. Describes how the technical effort will be planned, tailored, reviewed, and controlled.`]],
        exam: `If a question describes a team jumping to a design before the problem is defined, the best answer goes back to mission analysis and stakeholder needs.` }
    ],
    video: [`CMNklYtqpsg`,`INCOSE SE Handbook, Video 1: Intro to Systems, Life Cycles, and SE Life Cycle Processes`,`Lance Sherry`,`14:05`]
  },
  scenes: [
    { id:`f1s1`, domain:`Technical`, task:`T1`, title:`A layout by Friday`,
      text:(s,all,G)=>[`Wes was already at the whiteboard with a marker. He drew a long cylinder, a hatch on one end, and started sketching four boxes along one wall. <span class="said" data-who="Wes">"Crew quarters here. Galley in the middle. Hygiene on the far end so it's away from the food. Nadia, you can start tracking the mass."</span>`,`Jun glanced at her. Luis raised an eyebrow over his coffee. Nobody had asked what Halo was trying to do with the module. What does Nadia do?`],
      opts:[
        {t:`Start tracking mass on Wes's layout, since he's built eleven of these and the clock is running.`, s:0, d:{trust:3,conf:-2,health:-5},
          after:`The spreadsheet looks great by Thursday. On Friday Halo's crew operations director asks, in passing, where the crew shelters during a fire. Nobody in the room knows, and the layout has no answer for it.`,
          why:`Wes's experience is real, and it's experience with cargo. You can't track a design you haven't asked the right question of. Mission analysis comes before the layout, every time, because the layout is only as good as the problem it answers.`},
        {t:`Ask Wes for two days to write down Halo's mission, success measures and constraints first.`, s:3, best:true, d:{trust:1,conf:5,health:5},
          after:`Wes grunts. <span class="said" data-who="Wes">"Two days."</span> Nadia reads Halo's business plan, the station design guide, and the mission profile, and puts one page on his desk Wednesday night: what Halo is trying to do, how a crew will use the module, and the constraints nobody can move. Wes reads it twice and doesn't say anything. He also doesn't erase it.`,
          why:`Business or mission analysis defines the problem and the solution space before anyone commits to a solution. It's quick when you do it early and very expensive when you skip it. You didn't fight Wes. You gave him a better starting line.`},
        {t:`Tell Wes in front of the team that his layout is premature and he's skipping the process.`, s:0, d:{trust:-7,conf:-1,health:0},
          after:`The room goes quiet. Wes caps his marker and says, <span class="said" data-who="Wes">"Noted."</span> For the rest of the week he routes his questions through Luis.`,
          why:`You were right about the order of work and wrong about how to say it. Process is a tool for getting the right answer, not a stick. A chief engineer you embarrass on day one is a chief engineer you can't influence on day ninety.`},
        {t:`Let Wes keep sketching while she quietly drafts a list of open questions on the side.`, s:1, d:{trust:2,conf:1,health:1},
          after:`The questions are good ones. They also sit in a file nobody reads while the layout picks up momentum, and by Friday three of them are harder to change.`,
          why:`Asking the questions is the right instinct. Asking them where they can't change the decision isn't enough. Mission analysis has to happen before the design hardens, and it has to be visible.`}
      ]},
    { id:`f1s2`, domain:`Cross-cutting`, task:`X1`, title:`Skip to PDR`,
      text:(s,all,G)=>[`Tuesday morning Amara put the program schedule on the screen. It started with contract award and went straight to a preliminary design review in month four.`,`<span class="said" data-who="Amara">"The contract's signed, so we're past the concept stuff,"</span> she said. <span class="said" data-who="Amara">"We don't need a mission concept review or a requirements review. Halo already bought the module. I want to save the six weeks."</span>`],
      opts:[
        {t:`Agree. The contract settles the concept, and six weeks of margin is worth a lot on a crewed program.`, s:0, d:{trust:2,conf:-2,health:-5},
          after:`The schedule looks clean. In month four the PDR turns into an argument about what the requirements are, because nobody ever agreed on them.`,
          why:`A signed contract settles who pays whom. It doesn't settle what the system needs to do. Reviews early in the life cycle are where you find out you're wrong cheaply. Skipping them moves the argument to a more expensive review.`},
        {t:`Keep a short concept and requirements review, sized to the program, as a real decision gate.`, s:3, best:true, d:{trust:1,conf:4,health:5},
          after:`Amara pushes back, then agrees to a combined review in week seven, one day long, with clear entry and exit criteria. It costs her two weeks instead of six, and she gets a written baseline she can hold Halo to.`,
          why:`Life cycle stages end in decision gates, and the gate is where you're allowed to say not yet. Tailoring means right sizing the review, not deleting it. You kept the decision and cut the overhead.`},
        {t:`Ask Halo whether they'd mind skipping the early reviews, and do whatever they prefer.`, s:0, d:{trust:0,conf:-3,health:-2},
          after:`Halo's program office says it's up to FRO. That doesn't help anybody decide anything.`,
          why:`How you run your technical reviews is your engineering responsibility. The customer can attend and should, but handing them your gate decisions is handing off your job.`},
        {t:`Hold both reviews at full scale as written in the old government handbook FRO has on file.`, s:1, d:{trust:-2,conf:1,health:2},
          after:`The reviews happen and they're thorough. They also cost Amara the full six weeks and a lot of goodwill, and half the checklist items are for a program twice this size.`,
          why:`Keeping the gates is right. Running them unchanged from a template for a different kind of program isn't tailoring. Fit the review to the program's risk and size, and write down why.`}
      ]},
    { id:`f1s3`, domain:`Technical management`, task:`M1`, title:`What's the plan`,
      text:(s,all,G)=>[`Amara stopped by Nadia's desk after lunch. <span class="said" data-who="Amara">"I have a schedule. I don't have an engineering plan. Halo's contract asks for one in thirty days. What do you need from me?"</span>`,`Nadia had written test plans. She had never written a plan for how an entire program does its engineering.`],
      opts:[
        {t:`Copy FRO's last cargo module SEMP, change the names, and send it to Halo by the deadline.`, s:0, d:{trust:1,conf:-3,health:-4},
          after:`Halo's reviewer sends it back with a question in the margin of page two: where are the crew safety reviews? The cargo modules never had crew.`,
          why:`A plan written for a different system describes a different program. Reuse is fine as a starting point. Unchanged, it hides every place the new program is different, which is where the risk is.`},
        {t:`Ask Amara for a few days and write it after the first design review has settled the baseline.`, s:0, d:{trust:0,conf:-2,health:-3},
          after:`The deadline slips. Meanwhile three teams start work with three different ideas of how reviews, changes, and approvals will run.`,
          why:`Planning comes first because everything else hangs on it. A plan can be updated as you learn. Work without one can't be coordinated.`},
        {t:`Draft a SEMP: processes used, how tailored, key reviews, owners, and how it ties to schedule.`, s:3, best:true, d:{trust:2,conf:5,health:5},
          after:`She builds it from the handbook outline, borrowing what still fits from the cargo SEMP and marking every tailoring choice with a reason. Amara reads the review section, adds two milestones to her schedule, and says, <span class="said" data-who="Amara">"Now I can defend this."</span>`,
          why:`Project planning produces the plans that tell everyone how the technical work will happen. The SEMP is the engineering half of that. Writing tailoring decisions down, with reasons, is what separates tailoring from skipping.`},
        {t:`Let Amara's schedule stand as the plan and add an engineering column to it with owners.`, s:1, d:{trust:2,conf:1,health:1},
          after:`It's better than nothing. It shows who and when. It doesn't say how reviews, changes, or technical decisions will run, which is what Halo asked for.`,
          why:`A schedule says when. A SEMP says how. You need both, and they have to agree with each other.`}
      ]},
    { id:`f1s4`, domain:`Agreement and organizational`, task:`O1`, title:`The cargo playbook`,
      text:(s,all,G)=>[`FRO had a binder. Literally a binder, three inches thick, called the Product Development Process. Wes had written most of it ten years ago for cargo modules. Every program at FRO followed it.`,`Reading it Wednesday night, Nadia found what she half expected. There was no step for a crew safety review, no human factors evaluation, nothing about a hazard report. The binder had been built for modules that carried food and spare parts.`],
      opts:[
        {t:`Ignore the binder for HEARTH and run the program from the INCOSE handbook directly.`, s:0, d:{trust:-5,conf:-1,health:0},
          after:`It works for a month. Then quality assurance audits the program against the binder and writes up nine findings, and Wes takes it personally.`,
          why:`The organization's life cycle model is how the company keeps its programs consistent. Going around it creates audit findings and enemies. The handbook is a reference for improving the model, not a reason to abandon it.`},
        {t:`Follow the binder exactly and note the missing crew steps as a risk for later.`, s:1, d:{trust:2,conf:0,health:-2},
          after:`The program runs clean against the binder. The crew safety work sits in a risk entry with no owner and no date.`,
          why:`Following the company process is right. Leaving a known gap in it isn't. A risk entry doesn't do the missing work. Somebody has to change the process.`},
        {t:`Add the missing crew safety steps herself and start using them without telling anybody.`, s:0, d:{trust:-3,conf:0,health:1},
          after:`The steps are good. Nobody else knows they exist, so nobody else follows them, and the next program starts from the old binder again.`,
          why:`A process change only one person knows about isn't a process change. It's a habit. Changes to the life cycle model go through whoever owns it, so they stick.`},
        {t:`Take the gap to the binder's owner and propose a crewed program tailoring, with the reasons.`, s:3, best:true, d:{trust:3,conf:4,health:4},
          after:`The owner turns out to be Wes. He reads her two pages, grumbles about the length, and signs it. <span class="said" data-who="Wes">"Should have done this when we bid it."</span> The binder gets a new tab: crewed programs.`,
          why:`Life cycle model management means the organization owns its processes and improves them deliberately. When a new kind of program shows up, you change the model through its owner. Next time the steps are already there.`}
      ]},
    { id:`f1s5`, domain:`Technical`, task:`T2`, title:`Who cares about this module`,
      text:(s,all,G)=>[`Jun had started a stakeholder list in the model. It had two names on it: Halo Orbital and FRO.`,`<span class="said" data-who="Jun">"That's who signed the contract,"</span> he said. <span class="said" data-who="Jun">"Who else is there?"</span>`],
      opts:[
        {t:`That's right for now. The contract parties are the stakeholders; add others when they show up.`, s:0, d:{trust:1,conf:-3,health:-5},
          after:`The list stays short. Months later a fictional federal office that certifies human spaceflight asks why it was never consulted, and the answer is that nobody thought to.`,
          why:`Stakeholders are anyone who affects or is affected by the system across its life, not just the people on the contract. The ones you miss early come back at the most expensive moment.`},
        {t:`Add the crew, Halo ops, the station, launcher, ground control, OCSC, maintainers, disposal.`, s:3, best:true, d:{trust:3,conf:4,health:5},
          after:`The list grows to fourteen. Jun adds a column for what each one needs and another for how they'd know the module works. Two of the fourteen, the station's robotic arm team and the disposal planners, have requirements nobody had heard of.`,
          why:`Stakeholder identification covers the whole life cycle: users, operators, maintainers, regulators, interfacing systems, and the people who'll retire it. Each brings needs, and missing needs become missing requirements.`},
        {t:`Add the astronauts, since they're the real users, and leave the rest to Amara's contract team.`, s:1, d:{trust:2,conf:1,health:1},
          after:`Adding the crew was the most important single change. But the station, the launch provider, and the certifying office all have needs that will show up as requirements, and the contract team won't find them.`,
          why:`Users matter most, and they aren't the only stakeholders. Interfacing systems, regulators, and maintainers bring needs too.`},
        {t:`Ask Halo for their stakeholder list and use theirs, since it's their station and their crew.`, s:0, d:{trust:0,conf:0,health:-2},
          after:`Halo sends a list of their internal departments. It doesn't include FRO's own maintainers, the launch provider, or anyone who'll handle disposal.`,
          why:`The customer's view is one input. Your stakeholder analysis covers your system across its whole life, and the customer won't think of everyone.`}
      ]},
    { id:`f1s6`, domain:`Agreement and organizational`, task:`A2`, title:`Ninety cubic meters`,
      text:(s,all,G)=>[`Thursday, reading the statement of work line by line, Nadia found a sentence that bothered her. "Habitable volume shall be at least 90 cubic meters." There was no definition of habitable volume anywhere in the contract.`,`Pressurized volume, the inside of the shell, was about ninety. Habitable volume, the space a person can actually move in after the racks and quarters are installed, would be a lot less.`],
      opts:[
        {t:`Read it as pressurized volume, which HEARTH meets, and move on without raising it.`, s:0, d:{trust:0,conf:-4,health:-5},
          after:`It's the easy reading. Eight months later Halo reads it the other way, and FRO is suddenly ninety cubic meters short of its own contract.`,
          why:`An ambiguous term in an agreement doesn't go away when you pick the convenient reading. As the supplier, you clarify it through the agreement before you design to it.`},
        {t:`Ask Helen at Halo what she meant and design to whatever she says on the phone.`, s:1, d:{trust:3,conf:0,health:1},
          after:`Helen is helpful and specific. She's also not the contracting officer, and what she says on a phone call doesn't change the contract.`,
          why:`Talking to the customer is good. Clarifying a contract term through a hallway answer isn't. Get the answer, then make it official.`},
        {t:`Raise it with Amara so FRO asks Halo to clarify the term formally and records the answer.`, s:3, best:true, d:{trust:2,conf:5,health:4},
          after:`Amara sends a formal clarification request through the contracts channel that afternoon. Halo's answer comes back in a week, in writing, and it's the habitable reading. Nadia is glad she asked in week one instead of month nine.`,
          why:`In the supply process, the supplier makes sure it understands what the acquirer is asking for and that the agreement says it clearly. Ambiguity gets resolved through the agreement, in writing, early.`},
        {t:`Make the module bigger to be safe, so it meets either definition of habitable volume.`, s:0, d:{trust:0,conf:-1,health:-4},
          after:`Wes laughs out loud. The launch fairing has a fixed diameter, and the mass budget already has no room. Bigger isn't a choice.`,
          why:`Overdesigning around an ambiguity costs money and margin you don't have, and it still leaves the term undefined. Resolve the ambiguity instead.`}
      ]},
    { id:`f1s7`, domain:`Technical management`, task:`M6`, title:`Where things live`,
      text:(s,all,G)=>[`By Thursday afternoon Nadia had found three versions of the HEARTH mission profile. One was on Wes's laptop, one was attached to an email chain, and one was printed and pinned to the wall in the high bay with handwritten notes.`,`They disagreed about the launch date.`],
      opts:[
        {t:`Pick the newest one, email it to everybody, and ask them to delete the others.`, s:1, d:{trust:1,conf:1,health:1},
          after:`It helps for a week. Then a fourth version shows up on a shared drive with someone else's edits.`,
          why:`Fixing one document is good. Without a single controlled place and a rule for how things get updated, the problem comes back.`},
        {t:`Set up one controlled repository and an owner, version and status for each program document.`, s:3, best:true, d:{trust:2,conf:3,health:5},
          after:`It takes a day of setup and a short note to the team. Luis is the first to move his test documents in. The pinned printout in the high bay gets a sticky note on it: "Current version lives here," with a link.`,
          why:`Information management makes sure the right people have the right information, current and controlled, for the whole life cycle. On a fifteen year program, where things live is an engineering decision.`},
        {t:`Leave it. Everyone knows Wes's laptop copy is the real one, since he's the chief engineer.`, s:0, d:{trust:2,conf:-2,health:-4},
          after:`Wes goes on vacation for a week in month two. Nobody can find the current profile.`,
          why:`Authority isn't the same as control. Program information has to be available to everyone who needs it, whether or not one person is in the building.`},
        {t:`Make a page in her own notebook tracking which version is current and check it each time.`, s:0, d:{trust:0,conf:0,health:-2},
          after:`Nadia always knows which version is right. Nobody else does.`,
          why:`Personal tracking solves your problem, not the program's. Information management is for the team.`}
      ]},
    { id:`f1s8`, domain:`Cross-cutting`, task:`X5`, title:`Saying it to Wes`,
      text:(s,all,G)=>[`By Thursday evening the pattern was clear. Wes made calls fast, and his calls were usually right, and nobody ever asked him why. Nadia had three things she needed to raise with him: the layout, the binder, and the volume question.`,`She was thirty one. He'd been building pressure vessels since before she was born. Her stomach did the thing it always did before she told somebody senior they might be wrong.`],
      opts:[
        {t:`Ask Wes for twenty minutes alone, hear his view on each, then share hers.`, s:3, best:true, d:{trust:6,conf:3,health:2},
          after:`Wes talks for fifteen of the twenty minutes, about a cargo module in 2019 that leaked at the hatch seal and how he found it. Then he listens. On the volume question he says, <span class="said" data-who="Wes">"Good catch."</span> On the layout he says, <span class="said" data-who="Wes">"Fine. Give me your problem statement. But I'm not waiting forever."</span>`,
          why:`Systems engineering is a team sport, and influence is part of the job. Go to the person first, privately, with curiosity before conclusions. You learned something from him, and he heard you because you asked first.`},
        {t:`Put all three issues in a long email to Wes, copying Amara so there's a record.`, s:0, d:{trust:-5,conf:0,health:0},
          after:`Wes reads it as a complaint filed with his boss. His reply is two words: <span class="said" data-who="Wes">"Got it."</span>`,
          why:`A record matters, but leading with one tells a senior colleague you don't trust him. Talk first. Write it down after.`},
        {t:`Raise them with Amara and let the program manager decide whether to bring them to Wes.`, s:1, d:{trust:-1,conf:2,health:1},
          after:`Amara handles the volume issue well. She won't touch the layout, which is Wes's call, and she tells Nadia so.`,
          why:`Escalating program issues to the program manager is appropriate. Technical disagreements with the chief engineer you need to bring to him yourself.`},
        {t:`Wait until she's been there long enough to have credibility, then raise all three.`, s:0, d:{trust:1,conf:-2,health:-4},
          after:`By the time she's earned enough credibility, the layout is baselined and the volume question is a contract dispute.`,
          why:`Credibility comes from raising things well, not from waiting. The cost of an issue grows every week you sit on it.`}
      ]},
    { id:`f1s9`, domain:`Technical`, task:`T11`, title:`The test engineer's instinct`,
      text:(s,all,G)=>[`Luis pulled up a chair Friday morning. <span class="said" data-who="Luis">"You're a test person. I'm a test person. Let's get ahead of it. Help me start the verification plan now and we'll be the only program at FRO that isn't scrambling at the end."</span>`,`It was exactly what Nadia was good at, and she felt the pull. She also thought about serial 0447, which had passed its verification perfectly.`],
      opts:[
        {t:`Start the verification plan with Luis now, since early test planning saves time later.`, s:1, d:{trust:4,conf:1,health:1},
          after:`They make good progress. But with no requirements yet, the plan is a list of tests they know how to run, which isn't the same as tests the crew needs.`,
          why:`Early test planning is good. Verification proves you met the requirements, and you don't have them yet. Start with what proves the stakeholders' needs are met.`},
        {t:`Tell Luis test planning is premature and should wait until after CDR.`, s:0, d:{trust:-4,conf:0,health:-2},
          after:`Luis shrugs and goes back to the high bay. He doesn't offer again for a while.`,
          why:`Waiting until design is done to think about proof is how programs end up with untestable requirements. Bring test thinking in early, and aim it at the right question.`},
        {t:`Ask Halo to define the acceptance tests now so FRO knows exactly what it has to pass.`, s:0, d:{trust:0,conf:-1,health:-2},
          after:`Halo sends a list of tests from the old station program. Half of them don't apply to a commercial module.`,
          why:`Acceptance testing comes later and is negotiated through the agreement. What you need now is the customer's intended use, so you know what validation has to show.`},
        {t:`Ask Luis to help capture how Halo will judge if HEARTH works for the crew, then plan from that.`, s:3, best:true, d:{trust:3,conf:4,health:5},
          after:`Luis thinks about it and grins. <span class="said" data-who="Luis">"Validation first. I like it."</span> They draft four questions for Halo about how a crew will actually live in and leave the module, and the first one is about a fire.`,
          why:`Validation asks whether you built the right thing for its intended use. Setting validation intent early means the requirements, and then the verification, point at what the crew actually needs.`}
      ]},
    { id:`f1s10`, domain:`Agreement and organizational`, task:`O4`, title:`Jun's model`,
      text:(s,all,G)=>[`Amara needed a drafter for Wes's layout drawings and had Jun's name on a sticky note.`,`Jun had told Nadia on Tuesday that he'd joined FRO to do model-based systems engineering, and that this was the first program where anyone had let him open the modeling tool. He had a SysML model of the stakeholder list already. He'd built it on his own time.`],
      opts:[
        {t:`Let Amara assign him. Drawings are needed now and the model can wait a quarter.`, s:0, d:{trust:-4,conf:0,health:-2},
          after:`Jun draws for three months. He starts answering recruiters on LinkedIn in month two.`,
          why:`Human resource management means getting the right skills onto the project and growing them. Spending your one model-based engineer on drafting wastes the skill and risks losing the person.`},
        {t:`Make the case to Amara for Jun on the system model, with a short plan for growing him.`, s:3, best:true, d:{trust:5,conf:3,health:3},
          after:`Amara agrees, on the condition Nadia finds her a drafter. Nadia does, a contractor Luis knows. Jun gets the model and a development plan with two milestones on it. He brings Nadia a coffee the next morning without saying why.`,
          why:`Projects need the right people with the right competencies, and people need to grow. You matched the skill to the work, solved the manager's real problem, and invested in someone.`},
        {t:`Have Jun split his time between drawings and the model so both get some attention.`, s:1, d:{trust:2,conf:1,health:0},
          after:`Both happen, slowly. The model falls behind every time a drawing is due.`,
          why:`Splitting is a reasonable compromise, and it shortchanges the work that matters more. Solve the drafting need another way.`},
        {t:`Tell Jun to talk to Amara himself, since it's his career and he should advocate for it.`, s:0, d:{trust:-2,conf:0,health:0},
          after:`Jun doesn't. He's twenty four and new, and the program manager wrote his name on a sticky note.`,
          why:`Self advocacy matters, but the people who see the fit have a role in making it happen. Speak up for the people whose skills the program needs.`}
      ]},
    { id:`f1s11`, domain:`Cross-cutting`, task:`X2`, title:`Safety later`,
      text:(s,all,G)=>[`At Friday's staff meeting Nadia suggested inviting someone from FRO's tiny safety office and a human factors specialist to the concept work.`,`<span class="said" data-who="Wes">"Safety reviews the design,"</span> Wes said. <span class="said" data-who="Wes">"They don't make it. They'll get it at PDR like always."</span>`],
      opts:[
        {t:`Agree with Wes. Safety at PDR is the FRO process, and she just changed the binder once already.`, s:0, d:{trust:3,conf:-2,health:-5},
          after:`Safety arrives at PDR and finds the crew quarters have one way out. Moving them then costs three months.`,
          why:`Safety, human factors, reliability, and maintainability are qualities the system has from the start, or doesn't. Bringing them in at PDR means they review decisions they should have shaped.`},
        {t:`Invite safety and human factors now, with clear roles, so crew hazards shape the concept.`, s:3, best:true, d:{trust:1,conf:5,health:5},
          after:`The safety engineer is a quiet woman named Odette who asks one question in the first meeting: <span class="said" data-who="woman">"Where does the crew go if the air goes bad?"</span> Nobody has an answer. Now it's on the list.`,
          why:`Quality characteristics, like safety and human systems integration, get designed in. On a crewed program they belong in the concept, because the cheapest time to remove a hazard is before anyone has drawn it.`},
        {t:`Have safety review the concept later, once it's written, so they don't slow the early work.`, s:1, d:{trust:2,conf:1,health:1},
          after:`Safety's comments are sharp and arrive after the concept is written. About half of them are easy to take. The other half would mean starting over.`,
          why:`Earlier is better than PDR. Reviewing finished work is still later than shaping it, though.`},
        {t:`Do the safety thinking herself, since she understands test failures, and skip the specialists.`, s:0, d:{trust:-1,conf:0,health:-2},
          after:`Her list of hazards is thoughtful and has gaps a safety engineer would have caught in an hour.`,
          why:`Specialty engineering exists because these disciplines are deep. Systems engineering pulls in the specialists. It doesn't replace them.`}
      ]},
    { id:`f1s12`, domain:`Technical`, task:`T2`, title:`Helen's question`,
      text:(s,all,G)=>[`Friday at four, Halo's director of crew operations called in for a get-to-know-you. Helen Cho-Ramirez had spent eleven years as a flight surgeon for long duration crews, and she didn't waste time.`,`<span class="said" data-who="Helen">"I read your contract. It says ninety cubic meters. That's not what I need. I need four people to live in there for six months, and if there's a fire in the galley at three in the morning, I need all four of them to get out, or to a safe place, before the smoke gets them. I don't see that anywhere in the paperwork."</span>`],
      opts:[
        {t:`Tell Helen that's not in the contract, so it would have to be a change order.`, s:0, d:{trust:-4,conf:-3,health:-2},
          after:`Helen says, <span class="said" data-who="Helen">"I see,"</span> in a voice Nadia recognizes from doctors delivering bad news. The call ends early.`,
          why:`The contract question is real, but leading with it to a stakeholder describing a life safety need tells her you care about the paperwork more than the crew. Capture the need first.`},
        {t:`Promise Helen the module will have a safe haven and two egress paths, and FRO will make it work.`, s:0, d:{trust:4,conf:-2,health:-3},
          after:`Helen is relieved. Amara is not, when she hears about it Monday. Nadia just committed FRO to a design change nobody has priced.`,
          why:`Promising a solution before the need is analyzed, traced, and agreed is how programs end up with unfunded commitments. Listen, capture, and run it through the process.`},
        {t:`Thank her, write the need down as she said it, and say FRO will trace it and follow up.`, s:3, best:true, d:{trust:4,conf:5,health:4},
          after:`Nadia asks three follow up questions: how long smoke takes to become dangerous, where Helen thinks the crew sleeps, and what the old station did. Helen answers all three in detail. At the end she says, <span class="said" data-who="Helen">"You're the first person at FRO who asked me what I need."</span>`,
          why:`A stakeholder need, stated in the stakeholder's words, is gold. Capture it, understand it, and take it into needs and requirements definition, where it can be traced and, if needed, handled through the agreement. Don't dismiss it and don't promise around it.`},
        {t:`Ask her to put it in writing through Halo's program office so it goes through proper channels.`, s:1, d:{trust:-1,conf:2,health:1},
          after:`Helen does, eventually. The written version is shorter and loses the three in the morning detail that made it real.`,
          why:`Getting it formal matters, and it's a second step. First, listen to the person who knows the need best while she's on the phone.`}
      ]}
  ],
  exercise: { after:`f1s5`, title:`Which stage is it?`, intro:`The handbook's generic life cycle has six stages: Concept, Development, Production, Utilization, Support, and Retirement. Match each HEARTH activity to the stage it belongs to.`,
    items:[
      {prompt:`Figuring out whether a crew of four can live in HEARTH for 180 days, and what kinds of solutions could work.`, choices:[`Concept`,`Development`,`Production`,`Utilization`], answer:0, why:`Exploring needs, feasibility, and solution classes is the Concept stage.`},
      {prompt:`Defining the requirements and design, building qualification hardware, and verifying it meets the requirements.`, choices:[`Concept`,`Production`,`Development`,`Support`], answer:2, why:`Detailed definition, design, and verification of the system happen in Development.`},
      {prompt:`Building the flight module that will actually launch, to the approved design.`, choices:[`Development`,`Production`,`Utilization`,`Retirement`], answer:1, why:`Producing the system to the approved design is the Production stage.`},
      {prompt:`Four crew members living and working in HEARTH on a six month mission.`, choices:[`Support`,`Concept`,`Retirement`,`Utilization`], answer:3, why:`Using the system for its intended purpose is Utilization.`},
      {prompt:`Replacing a failed air system pump on orbit with a spare launched on a cargo flight.`, choices:[`Support`,`Production`,`Development`,`Utilization`], answer:0, why:`Keeping the system working through maintenance and logistics is Support, which runs alongside Utilization.`},
      {prompt:`Planning how HEARTH leaves orbit safely with the station after fifteen years.`, choices:[`Support`,`Utilization`,`Retirement`,`Concept`], answer:2, why:`Taking the system out of service and disposing of it is Retirement, and it should be planned long before it happens.`}
    ]},
  quiz: [
    {q:`A team begins sketching a module layout before anyone has written down what the customer is trying to accomplish. Which process has been skipped?`, opts:[`System architecture definition`,`Business or mission analysis`,`Design definition`,`Integration`], a:1, why:`Business or mission analysis defines the problem or opportunity and the solution space before solutions are chosen.`, task:`T1`, domain:`Technical`},
    {q:`Which list shows the handbook's generic life cycle stages in order?`, opts:[`Concept, Development, Production, Utilization, Support, Retirement`,`Concept, Design, Build, Test, Operate, Dispose`,`Planning, Analysis, Design, Build, Operate, Retire`,`Development, Concept, Production, Support, Utilization, Retirement`], a:0, why:`The generic stages are Concept, Development, Production, Utilization, Support, and Retirement, with Utilization and Support overlapping.`, task:`X1`, domain:`Cross-cutting`},
    {q:`At a decision gate, leaders find the requirements aren't mature enough. Which option is available to them?`, opts:[`Only proceed or terminate`,`Proceed, then fix it in the next stage`,`Continue the current stage before deciding`,`Let the customer decide on their behalf`], a:2, why:`Gate outcomes include proceeding, continuing the current stage, going back, holding, or terminating. Continuing the current stage is a legitimate choice.`, task:`X1`, domain:`Cross-cutting`},
    {q:`What does verification confirm?`, opts:[`The system meets the stakeholders' intended use`,`The customer is satisfied with the delivery`,`The design is the lowest cost option`,`The system meets its specified requirements`], a:3, why:`Verification provides objective evidence that specified requirements are met. Intended use is validation.`, task:`T11`, domain:`Technical`},
    {q:`A test proves a display meets every requirement, but it fails pilots in a condition nobody specified. Which activity would most likely have caught this?`, opts:[`Validation against the intended use`,`More thorough unit verification`,`A configuration audit of the unit`,`Additional regression testing`], a:0, why:`Validation checks the system against stakeholders' intended use in the real environment, which is where the missing condition lived.`, task:`T11`, domain:`Technical`},
    {q:`Which document typically describes how a program will plan, tailor, review, and control its technical effort?`, opts:[`The program's statement of work`,`The interface control document`,`The systems engineering management plan`,`The verification cross-reference matrix`], a:2, why:`The SEMP, a product of project planning, describes how the technical work will be done and controlled.`, task:`M1`, domain:`Technical management`},
    {q:`A program decides not to hold a full system requirements review because the contract is small. What makes this tailoring rather than skipping?`, opts:[`The program manager approved it in a meeting`,`The decision and its reasons are documented`,`The customer didn't ask for the review`,`Other programs at the company did the same`], a:1, why:`Tailoring is a deliberate, documented decision with a rationale, fitted to the program's risk and size.`, task:`X4`, domain:`Cross-cutting`},
    {q:`A company's development process has no steps for crew safety reviews, and it just won its first crewed program. What is the best response?`, opts:[`Follow the process exactly as written`,`Use an outside handbook instead`,`Add the steps informally on this program`,`Update the process through its owner`], a:3, why:`Life cycle model management means the organization improves its processes deliberately, through the owner, so the change sticks.`, task:`O1`, domain:`Agreement and organizational`},
    {q:`Which group is MOST likely to be missed in stakeholder identification for a space station module?`, opts:[`The crew who will live in it`,`The planners who handle disposal`,`The customer's program office`,`The company's own engineers`], a:1, why:`Stakeholders across the whole life cycle, like maintainers and disposal planners, are the ones most often missed.`, task:`T2`, domain:`Technical`},
    {q:`A supplier finds an undefined term in the contract's statement of work. What should it do first?`, opts:[`Ask for clarification through the agreement`,`Design to the more convenient reading`,`Design to satisfy every possible reading`,`Ask an engineer at the customer by phone`], a:0, why:`In the supply process, ambiguity in the agreement is resolved through the agreement, formally and early.`, task:`A2`, domain:`Agreement and organizational`},
    {q:`Three versions of a key program document disagree. Which process is the most direct fix?`, opts:[`Configuration audit`,`Risk management`,`Quality assurance review`,`Information management`], a:3, why:`Information management keeps the right information available, current, and controlled for the people who need it.`, task:`M6`, domain:`Technical management`},
    {q:`When should safety and human factors specialists first be involved in a crewed system?`, opts:[`At the preliminary design review`,`During the concept stage`,`After the design is baselined`,`During verification testing`], a:1, why:`Quality characteristics like safety are designed in. Involving specialists in the concept is the cheapest time to remove hazards.`, task:`X2`, domain:`Cross-cutting`},
    {q:`A new engineer has needed modeling skills, but a manager wants him on drafting. Which process addresses this?`, opts:[`Human resource management`,`Infrastructure management`,`Portfolio management`,`Knowledge management`], a:0, why:`Human resource management provides the project with skilled people and develops their competencies.`, task:`O4`, domain:`Agreement and organizational`},
    {q:`A customer describes a need that isn't in the contract. What should the systems engineer do first?`, opts:[`Tell the customer it needs a change order`,`Commit to a design that meets the need`,`Ask the customer to submit it in writing`,`Capture and understand the need as stated`], a:3, why:`Capture the stakeholder need first, understand it, then trace it and handle any contract impact through the process.`, task:`T2`, domain:`Technical`},
    {q:`On the V model, what sits on the right side opposite stakeholder needs on the left?`, opts:[`Component design`,`Unit implementation`,`System validation`,`Subsystem integration`], a:2, why:`Each level on the left pairs with one on the right. Stakeholder needs at the top left pair with validation at the top right.`, task:`X1`, domain:`Cross-cutting`}
  ],
  closing:(s,all,G)=>[
    `Nadia stayed late Friday. She opened a new document in the repository she had set up on Thursday, titled it HEARTH Stakeholder Needs, and typed Helen's words exactly as Helen had said them, three in the morning and all.`,
    (s.score>=28
      ?`It had been a good week, and she knew it. She'd given Wes a problem instead of a fight, kept the gates without wasting the schedule, and gotten the volume question in writing before anyone built to the wrong number. Wes had stopped calling her the test kid sometime on Thursday. She hadn't noticed when.`
      :`It had been a mixed week. Some of her calls had cost her trust she'd have to earn back, and Ruth would probably tell her which ones before she finished her coffee on Monday. But she'd found the question. That was the part that mattered.`),
    `On the drive home she called her father. He picked up on the first ring, the way he always did.`,
    `<span class="said" data-who="Frank">"So,"</span> he said. <span class="said" data-who="Frank">"Did you ground the pole?"</span>`,
    `<span class="said" data-who="Nadia">"I think I found out there's a pole nobody's looked at,"</span> she said. She told him about Helen, about the galley fire at three in the morning, about four people in a can two hundred and fifty miles up with nowhere to go.`,
    `He was quiet for a while. Her father had been quiet like that on the phone the night a crew he'd trained had a man burned on a line that should have been dead.`,
    `<span class="said" data-who="Frank">"Then that's your job,"</span> he said. <span class="said" data-who="Frank">"Somebody's got to be the one who asks where they go."</span>`,
    `Monday morning Helen's email was waiting.`,
    `<prop type="email" from="Helen Cho-Ramirez" to="Nadia Brooks" time="Sunday, 9:47 PM" subject="Following up on fire and safe haven">Nadia,<br>Thank you for Friday. I've attached the old station's emergency response times for fire and depressurization, and a sketch of where I think the crew sleeps. Please check the far crew quarter. I don't think anyone can reach your hatch from there in time.<br>Helen</prop>`
  ],
  episode:{src:`audio/full-ch01.mp3`, len:`about 35 minutes`},
  next:`What They Actually Need`
});
